### ISSUE TITLE
Build not triggered after commit

### ISSUE THREAD

**Issue by oscarsgit** [amplication/amplication#1023]
**Describe the bug**
Once I committed a change, the build was not triggered. This causes an issue where if I go to the commit that did not cause a build, I get a "forbidden resource" message. And once that occurs, I cannot view anything else in the entire application and have to logout and back in. 

**To Reproduce**
1. Create a commit that does not trigger the build
2. Navigate to the commit
3. See Forbidden Resource error once screen is loaded
4. Navigate to any other screen, Forbidden Resource error is displayed and information is unavailable

**Expected behavior**
A build is triggered every time a commit is issued.

**Screenshots**
Unfortunately I was unable to capture the screenshot whilst the issue was present.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: Edge
 - Version: 87.0.664.60

**Additional context**
The issue can be overcome by creating another commit.

**Comment by yuval-hazaz** [comment]
Thanks @oscarsgit for the detailed report, we will look into it

**Comment by yuval-hazaz** [comment]
resolved in 0.5.0
