### ISSUE TITLE
Entity Fields Options

### ISSUE THREAD

**Issue by AndrewTraub** [amplication/amplication#1033]
When creating an entity of type Options, I cannot enter a number for the value field - only a text string.
Also, it doesn't appear that I can set a default value (but this appears true for other fields as well)

**Comment by yuval-hazaz** [comment]
Closing this as a duplicate of #675 

Also, created a new feature request for default fields #1045

**Comment by yuval-hazaz** [comment]
Duplicate of #675

**Comment by yuval-hazaz** [comment]
Created #1045
