### ISSUE TITLE
⭐️ Plugin: Opentelemetry

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#1068]
Add support for https://opentelemetry.io/ 

This plugin will leverage the amplication maintained package [@amplication/opentelemetry-nestjs ](https://www.npmjs.com/package/@amplication/opentelemetry-nestjs).

Acceptance criteria:
- The generated code will contain the docker-compose service for jaeger
- The generated code will use `BatchSpanProcessor` and OTLPTraceExporter from `@opentelemetry/exporter-trace-otlp-grpc` to export traces to jaeger
- The generated code will configure the OpenTelemetryModule with serviceName from the amplication service name
- The settings will allow user to define:
   - exporter url that amplication will use to configure an environment variable named:     `OTEL_EXPORTER_OTLP_ENDPOINT`. i.e.    
   ```
   OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
   ```
   - optional configurable service name

 ## Tech notes

An example of a working solution is available here: https://github.com/overbit/otel-workshop

**Icon:**
![opentelemetry](https://github.com/amplication/amplication/assets/112330500/f776e1fe-0903-49d3-92ac-3b4c90f44825)

**Comment by yuval-hazaz** [comment]
should be implemented as a plugin

**Comment by Shurtu-gal** [comment]
@overbit Can I be assigned to this?
