### ISSUE TITLE
Server: Add more authentication providers for the generated app 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#1084]
Currently, the generated app is shipped with BASIC HTTP Authentications only. While it is good for a starter we should add more authentication providers like JWT and social.

The developer should be able to choose which authentication provider to use in the app.

**Comment by Kelz29** [comment]
@yuval-hazaz  Pretty keen to contribute to add the JWT authorization type.

**Comment by yuval-hazaz** [comment]
@Kelz29 you are more than welcome.
let's break this into two parts:
1. make the code changes on a sample generated app to make the feature work end to end 
2. implement the required code changes in the code generation process 

Are you on our Discord channel? 
if not, please join and find me there so we can discuss the details if you need to

**Comment by Kelz29** [comment]
Yes I am already on the channel 🤙🏾

**Comment by yuval-hazaz** [comment]
@all-contributors please add @Kelz29  for research and example

https://github.com/Kelz29/sample-app

**Comment by tupe12334** [comment]
will resolved in v0.10.0
