### ISSUE TITLE
Bug: Unable to build multiple apps locally because the Docker container name is identical

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#1085]
**Describe the bug**
Unable to build multiple apps locally because the Docker container name is identical

**To Reproduce**
1. Create an app and download the source code
2. Follow the instructions to deploy a local dev environment.
3. Create another app and download the source code
4. Follow the instructions to deploy a local dev environment for the second app.
5. The second app docker is not built since the first app's docker has the same name

**Expected behavior**
Both applications will be able to run side by side or at least one at a time.

**Comment by yuval-hazaz** [comment]
@iddan what do you think about this?

**Comment by yenicelik** [comment]
probably related to a general app-naming scheme again?: https://github.com/amplication/amplication/issues/1258

**Comment by yuval-hazaz** [comment]
resolved in #1424
