### ISSUE TITLE
notification not disappearing

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#1113]
**Describe the bug**
in pending changes there is a notification that doesn't disappear or tells me what the notification is about.

**Expected behavior**
it should disappear or at least tell me why the notification popped up

**Screenshots**
<img width="397" alt="Screen Shot 2021-01-08 at 13 48 00" src="https://user-images.githubusercontent.com/8940907/104012539-a3456b00-51b8-11eb-9d53-a8e0e5cb4284.png">

**Desktop (please complete the following information):**
 - OS: Mojave MacOS 10.14.6
 - Browser Google Chrome  
 - Version 87.0.4280.88

**Comment by yuval-hazaz** [comment]
@Leeyaacov @MatanForU , 
I suggest that when opening the panel, the number in the title "Pending Changes" will be displayed in the same style of the badge so it is clear that the badge number describes the number of pending changes.

what do you think?

**Comment by Leeyaacov** [comment]
I think we can let go of the number in the title. This number and the badge tells me the same.

**Comment by yuval-hazaz** [comment]
So, how would you resolve the issue Matan presented?

**Comment by Leeyaacov** [comment]
The badge number needs to stay until I'll commit my changes. The badge's purpose is to tell me I have changes that I didn't commit yet. Exactly like in Visual studio behavior. 

If the pending changes list is not understood, maybe we need to think about more info to add to each change.

**Comment by MatanForU** [comment]
What about an indication dot next to everything that might pop, which lead us to a more clear looks and tell us exactly where the notification is?

**Comment by Leeyaacov** [comment]
Not sure I understand...

**Comment by MatanForU** [comment]
![Pending Changes Optional](https://user-images.githubusercontent.com/8940907/104119265-ea596a80-5336-11eb-8043-1ad4c48a9900.png)

maybe something like this?

**Comment by yuval-hazaz** [comment]
@all-contributors please add @MatanForU  for design
