### ISSUE TITLE
Server: Deployment to sandbox environment failed.

### ISSUE THREAD

**Issue by galileor97** [amplication/amplication#1120]
Building Docker image

2021-01-12T19:54:48.991Z  (Info) Starting to build Docker image. It should take a few minutes. 
2021-01-12T19:54:50.475Z  (Info) Waiting for Docker image... 
2021-01-12T19:56:04.261Z  (Info) Waiting for Docker image... 
2021-01-12T19:57:09.344Z  (Info) Waiting for Docker image... 
2021-01-12T19:58:08.069Z  (Info) Waiting for Docker image... 
2021-01-12T19:59:03.308Z  (Info) Waiting for Docker image... 
2021-01-12T20:00:12.262Z  (Info) Waiting for Docker image... 
2021-01-12T20:01:05.136Z  (Info) Waiting for Docker image... 

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7
 - Browser Brave
 - Version  1.18.77

**Comment by yuval-hazaz** [comment]
appId ckjudwlj217271810s6ngx0c9ju

**Comment by yuval-hazaz** [comment]
@galileor97 we had a performance issue yesterday on the hosted service at app.amplication.com which caused build and publish processes to fail
It is now back on, please try again.

**Comment by ipacheco-uy** [comment]
Hi Yuval, i am seeing the same thing now, with appId ckju9q6hi133423310s6yrxs4rx5 in build zq97xpb4

**Comment by yuval-hazaz** [comment]
> Hi Yuval, i am seeing the same thing now, with appId ckju9q6hi133423310s6yrxs4rx5 in build zq97xpb4

Thanks, we will look at it

**Comment by mikeedwards** [comment]
Hi Yuval, I also experienced this with app ckjy4hc59107758810s6f7zbdr1i in build 1er6hph1.

I noticed when I downloaded the code, I couldn't get it to build right away locally with Docker either. I had to update versions in the package.json of the admin and server apps before it was able to build (I used `npm update` to do that.)

**Comment by yuval-hazaz** [comment]
> Hi Yuval, I also experienced this with app ckjy4hc59107758810s6f7zbdr1i in build 1er6hph1.
> 
> I noticed when I downloaded the code, I couldn't get it to build right away locally with Docker either. I had to update versions in the package.json of the admin and server apps before it was able to build (I used `npm update` to do that.)

Appreciate the details. it is very helpful.
we will check that.

**Comment by yuval-hazaz** [comment]
resolved in 0.5.0
