### ISSUE TITLE
Client: Misleading One-to-Many switch label

### ISSUE THREAD

**Issue by gabrielmoncea** [amplication/amplication#1143]
**Describe the bug**
Current label, "Allow multiple selection", for One-to-Many relationship switch between entities is misleading.

**Expected behavior**
I would have expected to see a different label e.g. "Associate with more than one element" or just "One-to-Many" in case we are going to support other relations like "Many-to-Many"

**Screenshots**
<img width="432" alt="Screenshot 2021-01-17 at 22 14 34" src="https://user-images.githubusercontent.com/39256258/104854856-b91e0300-5911-11eb-99d3-c1b6c5bf1e6a.png">

**Comment by yuval-hazaz** [comment]
resolved in #1080
