### ISSUE TITLE
Allow user to add new joined entity from drop down list

### ISSUE THREAD

**Issue by mgetz** [amplication/amplication#1167]
Currently:
When choosing a joined entity, a drop down list is presented. If the choice you need is not on that list, then you need to select the joined entity page, add new record, then return to your previous record and select the value you just entered.

Future:
When choosing a joined entity, a drop down list is presented with an "Add" option at the bottom of the list. Selecting that choice opens a new blank record for that joined entity. Once the new record is saved, the user is returned to their original record and the new record is shown as the selected joined entity.

**Comment by yuval-hazaz** [comment]
I like this idea! definitely a better experice

**Comment by varun-khachane** [comment]
Hi, I would like to work on this issue. Can you assign it to me?
