### ISSUE TITLE
Add Recipes and/or Tutorials for Third-Party APIs

### ISSUE THREAD

**Issue by bulletpr00f** [amplication/amplication#1170]
**Is your feature request related to a problem? Please describe.**
I am a very busy developer and I love using `amplication` to explore, experiment, and build data-driven apps.  One of the immediate use cases that I thought of was integration with third-party APIs such as Google Maps or Twitter.  I like the way `amplication` is already closely integrated with GitHub and would like to see more integrations like this.

**Describe the solution you'd like**
Create tutorials/recipes to show busy developers how to quickly build data integrations with 3rd Party APIs.

**Describe alternatives you've considered**
[Public apps](https://github.com/amplication/amplication/issues/1158) might also work.  @yuval-hazaz I take it this might be a showcase of community-derived examples that could even extend beyond third-party integrations?

**Additional context**
Example idea for [public app / recipe / tutorial]: 
Create an app that aggregates tweets from https://twitter.com based on user-defined parameters such as hashtags and allow special actions to be assigned for incoming tweets that match a certain criteria.

**Comment by yuval-hazaz** [comment]
This will be provided as plugins.
