### ISSUE TITLE
Client: All strings should be localised in a file for future translations

### ISSUE THREAD

**Issue by gabimoncha** [amplication/amplication#1171]
**Is your feature request related to a problem? Please describe.**
Currently, all strings are hardcoded in the app. Because of this, the task of translating the client in the future will become too tedious for anyone to do it.

**Describe the solution you'd like**
An internationalisation solution should be implemented, like [react-i18next](https://github.com/i18next/react-i18next), and all strings should be moved in the same place. This way when we decide to add language support it would be much easier to do.

**Describe alternatives you've considered**
Other libraries can be implemented, but from my experience [react-i18next](https://react.i18next.com/) it's the easiest to setup.

**Additional context**

**Comment by yenicelik** [comment]
what strings are you referring to? I am used to manually implementing i18next, and from my understanding, the admin-ui is more a "test/showcase" tool and the backend is amplication's real product?

**Comment by yuval-hazaz** [comment]
This FR is about the Amplication UI and not about the generated app. 
React-Admin includes a built-in i18n support, so if needed we can also implement it in the generated app, but it is not in our current focus or roadmap.
