### ISSUE TITLE
Allow selecting single repositories for GitHub Sync

### ISSUE THREAD

**Issue by MarcMogdanz** [amplication/amplication#1187]
**Is your feature request related to a problem? Please describe.**
When activating the GitHub Sync it will ask to give read and _write_ permissions to _all_ of your repositories.

**Describe the solution you'd like**
I'd like to have the option to only grant permissions for one or multiple repositories.

**Additional context**
This is how Amplication handles it currently:

<img width="483" alt="Screenshot 2021-01-30 at 16 28 00" src="https://user-images.githubusercontent.com/20729218/106360324-1fdeeb80-6318-11eb-817b-fb42ecd42ace.png">

This is how [Vercel](https://vercel.com) handles it:

![Screenshot 2021-01-30 at 16 31 09](https://user-images.githubusercontent.com/20729218/106360406-8fed7180-6318-11eb-89ca-3c8801e23cfb.png)

**Comment by mtvw** [comment]
This is kind of a red flag for me...
I'm not going to use github sync if I have to share all my repo's

**Comment by yuval-hazaz** [comment]
> This is kind of a red flag for me...
> I'm not going to use github sync if I have to share all my repo's

I agree this should be changed sooner rather than later. We will give it a priority. Thanks for the feedback

**Comment by mtvw** [comment]
Thanks!
I'm only stumbled upon Amplication yesterday and I must say I'm impressed!
Keep up the good work!

**Comment by mshidlov** [comment]
Hi @MarcMogdanz ,
Thank you for posting this issue. It is going to be fixed in [issue](#2202) #2202. As such, I will close this issue.
