### ISSUE TITLE
Client: Discard changes button not really delete all my lasted changes

### ISSUE THREAD

**Issue by Leeyaacov** [amplication/amplication#1202]
**Describe the bug**
After I create a new field, it’s shown on the pending changes menu. When I discard the change, the field didn't delete from the entity fields.

**Expected behavior**
Discard changes button need to delete all my lasted changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/65485193/106752926-a99dfa00-6633-11eb-9121-7031a5f45adc.png)

![image](https://user-images.githubusercontent.com/65485193/106752987-bd496080-6633-11eb-8285-4282b8db7089.png)

**Comment by yuval-hazaz** [comment]
I can confirm this is a bug in the cache on the client-side. After refreshing the page the new field no longer appear
