### ISSUE TITLE
Client: Does not support single letter fields in Entities

### ISSUE THREAD

**Issue by moorbren** [amplication/amplication#1204]
**Describe the bug**
The client does not allow to save a field with a single letter as the name. 

**To Reproduce**
1. Add a field to an Entity
2. Give it a single letter as the name (a-z, A-Z)
3. Client will show message saying that the name needs to contain letters, etc...

NOTE: It will let you add the field, but you can't edit anything about it without changing the name. 

**Expected behavior**
The client should allow you to have single letter fields. 

**Screenshots**
Screenshot showing message:
![image](https://user-images.githubusercontent.com/43553605/106829468-0bb12c00-6641-11eb-8b65-6c617d642815.png)

Screenshot showing that you can create single letter fields, but not edit them. 
![image](https://user-images.githubusercontent.com/43553605/106829501-21265600-6641-11eb-8bf2-5559aac448f3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox 85

**Comment by yuval-hazaz** [comment]
thanks @moorbren 
While I understand the bug you describe, can you please share a use case where you will use a single letter field name
A use case will help us prioritize and better understand the need

**Comment by yuval-hazaz** [comment]
Perfect, thank you very much for sharing.
Since it should be pretty easy to fix, we will  include it soon.
By the way, I would love to hear more about your use case, if you don’t mind sharing.
You can find me on our discord, or you can email me directly. My email is available of my profile

**Comment by moorbren** [comment]
It's nothing that interesting haha, I just need to store the position of a user on a Seating Chart. I've just been working with on some game projects on the side, and graphics/positioning variables tend to be a letter or two at most.
