### ISSUE TITLE
Client: message in button bar is not aligned to the center

### ISSUE THREAD

**Issue by Leeyaacov** [amplication/amplication#1208]
**Describe the bug**
The message I got after I synced with the GitHub repo is not aligned to the center of the button bar

**Expected behavior**
Should be vertical center alignment 

**Screenshots**
![image](https://user-images.githubusercontent.com/65485193/106888032-a6b40f80-66ee-11eb-8ba0-5229ec6789dc.png)

**Comment by jainpawan21** [comment]
@souravjain540 I think this can be closed. As linked PR has fixed this issue.

**Comment by souravjain540** [comment]
thanks @jainpawan21!
