### ISSUE TITLE
Open sandbox environment button doesn't work

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#1211]
**Describe the bug**
open sandbox environment button in the bottom page doesn't work and leads me to Error 404 

**Screenshots**
<img width="295" alt="Screen Shot 2021-02-04 at 16 56 05" src="https://user-images.githubusercontent.com/8940907/106910771-39ae7300-670a-11eb-93c9-aff2e0ac5b9c.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Browser Google Chrome
 - Version 88.0.4324.96

**Comment by yuval-hazaz** [comment]
Can you please add the following details:
- Is that a new app?
- Did it work before and stopped working?
- Can you show a screenshot of the error (is it originating from Amplication or from your cloud deployment)?
- What is the ID of your app?
-

**Comment by MatanForU** [comment]
Is that a new app? 
yes, it is from the new app.

Did it work before and stopped working? 
Haven't checked before, just this one.

Can you show a screenshot of the error (is it originating from Amplication or from your cloud deployment)?
it opens up a new tab with the 404 google error.
<img width="912" alt="Screen Shot 2021-02-04 at 18 46 18" src="https://user-images.githubusercontent.com/8940907/106926030-57370900-6719-11eb-9d61-5179aa0c23fd.png">


What is the ID of your app?
rgvaq4f6
