### ISSUE TITLE
DSG: One-to-one - select the "leading" side

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#1215]
**Is your feature request related to a problem? Please describe.**
When creating a one-to-one relation only one side should have a foreign key, while the other side is just used for navigation.
Currently, when DSG automatically selects the side to hold the FK.
Instead, the user should select on which side of the relation to place the FK.

example:
below is an example of a one-to-one relation between a user and a profile. 
In this example, the FK is placed on the user model, while the profile model only has a navigation property back to the user without a FK.

model User
- id
- profile
- profileId
- 
model profile
- id
- user

**Describe the solution you'd like**
Allow the user to select on which side of the relation to place the FK\

**Design** - https://www.figma.com/file/g56PMEpymt2I3Ecrtb3LH5/%231215---One-to-one%E2%80%A8select-the-%22leading%22-side?node-id=2041%3A14924&t=qqCGD9kMWLmQQZ33-1

**Additional context**
see this article from Prisma with more details on how they expect the schema to be created
https://www.prisma.io/docs/concepts/components/prisma-schema/relations#one-to-one-relations

**Comment by yenicelik** [comment]
I think this is related to this issue: https://github.com/amplication/amplication/issues/1387

**Comment by yuval-hazaz** [comment]
When creating a one-to-many relation - it is clear that the foreign key is on the "many" side. 
When creating a many-to-many relation - Prisma automatically generated a connection table with foreign keys to both sides.
When creating a one-to-one relation - currently Amplication chooses randomly one side to hole the FK. This FR is to allow the developer to set that manually. 

In most cases, this behavior does not impact the functionality at all and the developer is not even aware of it.

**Comment by yuval-hazaz** [comment]
@abrl91 have a look at this one 😃
it is open since Feb 21... I added it now to the backlog
