### ISSUE TITLE
Admin: Deleted current admin user

### ISSUE THREAD

**Issue by vimota** [amplication/amplication#1217]
I logged in as the default admin user and created a new user and proceeded to delete the current/admin user. After that no users showed up (presumably because I was no longer authorized), but I was not able to login as the new user either, so I'm left unable to access the admin app at all.

I committed a new change in order to trigger a clean db and was not able to reproduce the new user disappearing but the rest of the issues occurred. Not sure why the new user I had created disappeared the first time around..

1. Go to admin app, log in as default user.
2. Create new user (assuming no other user exists).
3. Delete current admin user
4. See authorized errors, try to login as the new user.

**Expected behavior**
1. If you're deleting the current authed user the admin app should warn you (and probably disallow it if there are no other users so you don't lock yourself out).
2. If you delete the current authed user, it should probably log you out of the admin app so that the user doesn't think there's a bug in the admin app causing them to see empty data. It seems like some sort of logged-in state is preserved so that even if you reload the page it shows the schema which maybe shouldn't work if you're not authorized any longer?

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox

**Comment by yuval-hazaz** [comment]
Thanks @vimota 
I can confirm that the user deletes their own record, they left "signed in" on the client-side but can't access any data on the server. 
But, I couldn't reproduce the other part - after clicking on the "sign out" button, I managed to sign in with the new user with no issue.

I agree with the details you provided under expected behavior.

**Comment by vimota** [comment]
Thanks! Yeah, I can't reproduce it either, so I'll just keep an eye out if it happens again - perhaps I deleted both users by accident.
