### ISSUE TITLE
[Server]: [Phone number]

### ISSUE THREAD

**Issue by OstapFilipenko** [amplication/amplication#1236]
** add a new Data-Type Phone Number and add validation to it

**Comment by alonram** [comment]
@OstapFilipenko, Since there are so many different phone number formats, how do you see it being implemented?
We do plan on adding regex option for text data type but that's a different issue.

**Comment by bitlab-code** [comment]
consider https://github.com/google/libphonenumber

**Comment by yenicelik** [comment]
yh i am also used to saving phone numbers as a string and parsing them with a library ; I dont think it's common to save a phone number format in the database

**Comment by yuval-hazaz** [comment]
I am closing this request due to inactivity and low impact
