### ISSUE TITLE
DB migrations for app versions

### ISSUE THREAD

**Issue by bitlab-code** [amplication/amplication#1242]
I've downloaded the app’s source code: running app in docker: all works.

Then I've created a new entity, downloaded - again - the app’s source code but got an error with migration:
```
> db:init
> run-s "db:migrate-save -- --name 'initial version'" db:migrate-up seed
> db:migrate-save
> prisma --experimental migrate save "--name" "initial version"
Prisma schema loaded from prisma/schema.prisma
Error: There are more migrations in the database than locally. This must not happen.
Local migration ids: (empty).
Remote migration ids: 20210215142959-initial-version
npm ERR! code 1
npm ERR! path /app/server
npm ERR! command failed
npm ERR! command sh -c prisma --experimental migrate save "--name" "initial version"
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-02-15T15_56_51_551Z-debug.log
ERROR: "db:migrate-save -- --name 'initial version'" exited with 1.
npm ERR! code 1
npm ERR! path /app/server
npm ERR! command failed
npm ERR! command sh -c run-s "db:migrate-save -- --name 'initial version'" db:migrate-up seed
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-02-15T15_56_51_603Z-debug.log
```
it's a bug or am I doing something wrong in the process?
Thanks.

**Comment by bitlab-code** [comment]
it seem related to #881 (closed)

**Comment by bitlab-code** [comment]
follow manual instructions (https://docs.amplication.com/docs/how-to/dev-env/#initialize-your-database) migration works.

but running with `docker-compose up -d` still got the same error

**Comment by yuval-hazaz** [comment]
Hi @bitlab-code 
Migration is still an open issue. 
Currently, when you deploy to sandbox the database is re-created with every deployment so it completes successfully. 
When you try to deploy with Docker on an existing DB, the migration list is out of sync, and Prisma Migrations fail.

As you mention, you can manually run the migrations to work around it.

We have this item as a priority for one of the next few sprints.
