### ISSUE TITLE
Allow selection between express and Fastify for the generated app

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#1244]
**Is your feature request related to a problem? Please describe.**
Currently, the app is generated with Express framework with no other options.

**Describe the solution you'd like**
The user should have an option to choose whether to generate the app with Express or Fastify to handle the HTTP traffic.

**Comment by fungilation** [comment]
Issue with Fastify option (in Nest) is that doesn't support Passport for auth

**Comment by yuval-hazaz** [comment]
Thanks @fungilation . I didn't know that.

**Comment by fungilation** [comment]
Don't get me wrong though, I use Nest + Fastify myself so I want to see Fastify as option for this project (just found this project yesterday btw, awesome "bundling" of the best OSS Node stacks!)
