### ISSUE TITLE
[Data Service Generator]: Support pagination in generated GraphQL API

### ISSUE THREAD

**Issue by vimota** [amplication/amplication#1250]
Allow pagination in GraphQL API generated from the entities, similar to https://graphql.org/learn/pagination/ or https://hasura.io/learn/graphql/intro-graphql/graphql-queries/#fetch$limitnumberoftodos.

**Comment by yuval-hazaz** [comment]
Resolved in v0.6.0

**Comment by yuval-hazaz** [comment]
@all-contributors please add @vimota  for ideas
