### ISSUE TITLE
[Data Service Generator]: Support entity definition via an API

### ISSUE THREAD

**Issue by vimota** [amplication/amplication#1251]
Support programmatic creation of entity definitions (which I imagine would require also a commit API?), to allow use cases like setup scripts (ie. https://github.com/vercel/next.js/blob/canary/examples/with-graphql-faunadb/scripts/setup.js).

**Comment by yuval-hazaz** [comment]
@vimota, Amplication API expose all endpoints including entity defintion with GraphQL.
Also, we are working on a CLI with the same functionality that will work with the API.

Are you referring to an SDK that wraps that API? 
If so, do you think it should be a one-to-one mapping? 

Or, do you see benefits of wrapper functions that do multiple calls to the API? 
For example, createEntity function that gets both the entity properties and a list of fields

**Comment by vimota** [comment]
@yuval-hazaz perhaps I'm missing something! I'm imagining an API that lets you create a new entity / object model (for example: my current data model only includes Users by default, but I want to create a Guestbook Entry table).

Is that what you're saying exists already 😄 ? Is that API documented anywhere? Can you call the public/hosted API (http://app.amplication.com/) directly, and if so is there a secrets/token mechanism for auth?

**Comment by vimota** [comment]
Ah it looks like this is probably it? https://github.com/amplication/amplication/blob/4a69739bbb2719c480a95f07d484765af208ad2e/packages/amplication-server/src/core/entity/entity.service.ts#L352

**Comment by vimota** [comment]
I think indeed a CLI would help a lot for this sort of setup script scenario 👍

**Comment by yuval-hazaz** [comment]
> @yuval-hazaz perhaps I'm missing something! I'm imagining an API that lets you create a new entity / object model (for example: my current data model only includes Users by default, but I want to create a Guestbook Entry table).
> 
> Is that what you're saying exists already 😄 ? Is that API documented anywhere? Can you call the public/hosted API (http://app.amplication.com/) directly, and if so is there a secrets/token mechanism for auth?

yes, this is the main graphQL API used by Amplication UI.
It is not documented yet. 
Soon we will release the CLI which will be a wrapper around the GraphQL API. You can already see PR #1221

**Comment by vimota** [comment]
Ah this is awesome! Once that CLI is in I'll do a separate PR to improve the nextjs example to use it for setup :)

**Comment by yuval-hazaz** [comment]
great, I will close this issue and we'll track the progress of the CLI separately
