### ISSUE TITLE
Add next.js with Amplication example

### ISSUE THREAD

**Issue by vimota** [amplication/amplication#1252]
Given the popularity of next.js as a web development framework, it may help users get started to have a full end-to-end example using Amplication as the backend for a next.js frontend.

**Comment by vimota** [comment]
PR here: https://github.com/vercel/next.js/pull/22399

**Comment by yuval-hazaz** [comment]
@vimota as always, thanks for the inspiring contributions. 
I am closing this issue as the progress is now tracked on the PR

**Comment by yuval-hazaz** [comment]
@all-contributors please add @vimota  for example
