### ISSUE TITLE
DSG: DB name is not unique per app

### ISSUE THREAD

**Issue by alonram** [amplication/amplication#1258]
**Describe the bug**
When running the generated app locally, it initializes the database with the name "postgres". When running a 2nd app locally it tries to use the same name and causes conflict between apps.

**To Reproduce**
Generate more than one app and install it locally.

**Expected behavior**
Database name should use a unique name

**Additional context**

**Comment by jithinlal** [comment]
The database name should be that of the app name. will that be of any use? or should we randomize it?

**Comment by yuval-hazaz** [comment]
> The database name should be that of the app name. will that be of any use? or should we randomize it?
yes, the app name is a good suggestion. We may also allow the developer to set the DB name and even the DB port in a settings page

**Comment by yuval-hazaz** [comment]
resolved in #1424
