### ISSUE TITLE
DSG: Allow setting the DB credentials for the generated app   

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#1263]
**Is your feature request related to a problem? Please describe.**
The DB credentials used on the generated app are by default "admin/admin" and cannot be charged from Amplicaiton.
A developer must change the credentials manually in the generated app (.env file) and before running the docker-compose.

**Describe the solution you'd like**
Add an app setting for the DB credentials so the user can easily change the user name and password.\

**Additional context**
When implemented, consider the following story:\
A user is changing the credentials after the app was deployed (locally or on hosted env). The credentials on the docker image should be updated on the next deployment.\

**Comment by yenicelik** [comment]
probably related to setting a DB name: https://github.com/amplication/amplication/issues/1258

**Comment by yuval-hazaz** [comment]
resolved in #1424
