### ISSUE TITLE
Generated app - add logout functionality 

### ISSUE THREAD

**Issue by ramandhingra** [amplication/amplication#1268]

**Comment by yuval-hazaz** [comment]
@ramandhingra can you please provide more context? I didn't understand what you are referring to

**Comment by ramandhingra** [comment]
Yuval, I went through the source code but didn't find the logout() function. Are we supposed to implement it of our own? That is all.

**Comment by yuval-hazaz** [comment]
Thank @ramandhingra 
Currently, the generated apps use Basic HTTP authentication, where the user needs to send the credentials with any request in the header. We also not yet tracking the user session on the server.  So, there is no actual sign-out functionality on the server-side.  You just need to "forget" the credentials on the client-side. 
Once we will add more authentication providers, we will also provide a sign-out functionality to invalidate the user's token. 
I will leave this feature request open and we to track the progress and implementation once we'll start working on it.

**Comment by yenicelik** [comment]
reference https://github.com/amplication/amplication/issues/1084

**Comment by yuval-hazaz** [comment]
As we moved to the new Admin UI with React-Admin, the generated app now includes a signout button that deletes the local storage credentials.
