### ISSUE TITLE
Client Generator

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#129]
Spec: https://www.notion.so/amplication/Generating-Admin-UI-Code-8f2cb498da6d42f6ba3ff23ace030f3e

**Comment by pomazanbohdan** [comment]
It might be worth looking at https://github.com/marmelab/react-admin ?

**Comment by iddan** [comment]
@pomazanbohdan thank you! React Admin looks cool! We want to use our own design system, is that possible with it?

**Comment by pomazanbohdan** [comment]
React Admin use https://material-ui.com/

Probably need to watch this https://material-ui.com/customization/theming/

**Comment by pomazanbohdan** [comment]
I have been looking and looking for a platform for a long time that can generate database structures, APIs and immediately an administrative (or even user) interface.
You have a good idea, and for a web interface it is better than react-admin.

**Comment by iddan** [comment]
Yeah, so I think we are going to implement our own thing. You can track our progress or join the effort at https://github.com/amplication/amplication/pull/782

**Comment by pomazanbohdan** [comment]
look more at https://github.com/ukrbublik/react-awesome-query-builder

**Comment by yuval-hazaz** [comment]
> look more at https://github.com/ukrbublik/react-awesome-query-builder

Cool, thanks.

I love your input. 
You are invited to join our discord channel, we would be happy to keep hearing your thought and feedback
https://discord.gg/b8MrjU6

**Comment by iddan** [comment]
@pomazanbohdan ooh https://github.com/ukrbublik/react-awesome-query-builder looks great!

**Comment by iddan** [comment]
We are shipping Admin UI in this release! You can try it with the latest master
