### ISSUE TITLE
DSG: @Transform decorators

### ISSUE THREAD

**Issue by EndersDev** [amplication/amplication#1291]
**Describing the bug**

1. On the "WhereInput.ts" files the decorator `@Transform(JSON.parse)` does not work.

2. On "schema.prisma", the decorator `@reference` need an property that it does not have, references, with its id.

**Fixing**
1. Considering that it is a function that needs an non-string type and the inside of @Transform needs to be a function I was able 
to make it work replacing that statement with `@Transform(field => JSON.parse(field.value))` 

2. So I was able to substitute `@relation(fields: [sellerId])` by `@relation(fields: [sellerId], references: [id])`.

**Context**
1. When relation 2 or more entities. 
The properties of field variable are [value, obj, key, type], I'm new to back-end programming so I yet don't know which one to use, there for, I'll use "value" and then if I find any errors on the application I'll try the others (by the name I guess that the only other possible is obj).
2. Binding a user (seller) in the client entity.

**Comment by yuval-hazaz** [comment]
@EndersDev thanks for reporting
for the second one, I just pushed a fix on this one yesterday. It will be part of the next release. have a look at this https://github.com/amplication/amplication/issues/1287

I will look into the first one.

**Comment by yuval-hazaz** [comment]
@EndersDev can you please share the error you receive regarding the @trasnform decorator?

By the reference of the decorator 
![image](https://user-images.githubusercontent.com/43705455/112853620-b714b500-90b5-11eb-9f9d-1a223ccbdb88.png)
the decorator expect as the first parameter a function transformFn that receive as the first parameter the value

using this code 
```
@Transform(JSON.parse)
```

is just a shorthand of this
```
@Transform(value => JSON.parse(value))
```

which should work, as it is a function that gets the value as the first parameter and executes JSON.parse on the value



I also tested it and didn't get any errors. 
(by the way, the property was missing the @Field decorator and i opened a new issue about it #1298 )

**Comment by yuval-hazaz** [comment]
This issue was closed because it has been inactive for more than 30 days
