### ISSUE TITLE
Client & Server: Validation for entity name plural vs singular form

### ISSUE THREAD

**Issue by dnordberg** [amplication/amplication#1293]
A model can be created successfully with both versions being plural, once committed, the error shows up in the build log when generating the app. Need validation to ensure plural and singular forms are actually plural and singular.

**To Reproduce**
1. Create a model, give it a plural name
2. Commit the model
3. It will deploy and the build will show the error

**Expected behavior**
Automatically give a singular form label if plural form is given.

**Comment by yuval-hazaz** [comment]
Currently, when this happens the user cannot complete the build without manually changing the entity name to a singular form. Even after changing the entity name and the build completes successfully, the app cannot be deployed (see #1294 )
