### ISSUE TITLE
Client: accessibility colors

### ISSUE THREAD

**Issue by Leeyaacov** [amplication/amplication#1296]
**Describe the bug**
Some of the text colors are not working well for accessibility.

**Expected behavior**
Changing the 'white' color to our black 100 color

We should change this on:
1. App name on the menu
![image](https://user-images.githubusercontent.com/65485193/112310688-87c50900-8cad-11eb-9352-b743df9dee1e.png)

2. App page:
     -banner(application-home header) 
     -name(circle-badge)
![image](https://user-images.githubusercontent.com/65485193/112310922-c78bf080-8cad-11eb-8cf4-031f82f8a44f.png)

3. Users label
![image](https://user-images.githubusercontent.com/65485193/112311072-f3a77180-8cad-11eb-8938-b88caf0f5030.png)
![image](https://user-images.githubusercontent.com/65485193/112311088-f99d5280-8cad-11eb-93d4-723556129411.png)

4. Commit changes list
![image](https://user-images.githubusercontent.com/65485193/112311157-1174d680-8cae-11eb-888a-1d4577864d51.png)

**Comment by almogbhl** [comment]
@yuval-hazaz hi, 

can @IsaacM890 take it?

**Comment by yuval-hazaz** [comment]
> can @IsaacM890 take it?

sure

**Comment by yuval-hazaz** [comment]
@IsaacM890 would you please add a comment here so I can assign you to the issue? GitHub requires some kind of interaction with the repo in order to assign issues to you.

**Comment by IsaacM890** [comment]
Hi Yuval , sure .

**Comment by yuval-hazaz** [comment]
Let me know if you need help with the project setup and onboarding

**Comment by divikshrivastava** [comment]
@yuval-hazaz I am a beginner in react, can I take this up ?

**Comment by yuval-hazaz** [comment]
@divikshrivastava sure, go ahead. I will assign you with the task 

Let me know if you need any help with getting the environment up and running.

**Comment by divikshrivastava** [comment]
@yuval-hazaz while running "npm run bootstrap" in this directory, it's stuck at below stage, any resolution ?
![image](https://user-images.githubusercontent.com/22555188/135865348-b631de74-d781-4ad3-ab1d-49b31f61e36a.png)

**Comment by yuval-hazaz** [comment]
@divikshrivastava would you please join our Discord server? @tupe12334 will be there to help you.

**Comment by yuval-hazaz** [comment]
@alexbass86 please have a look at this issue. If there is anything left to do, please open a new separate issue and close this one

**Comment by alexbass86** [comment]
In our new design, we changed many problematic areas with accessibility & overall design issues, so let's make sure we put the exact colors we have in the new design.
