### ISSUE TITLE
text search input in the entity field is unreadable [Bug Title]

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#1303]
text in the search input in the entity field is unreadable due to lack of contrast, letters are not bright enough to seen

**Expected behavior**
just a bug fix to make the letters white 

**Screenshots**
<img width="446" alt="Screen Shot 2021-04-04 at 11 45 04" src="https://user-images.githubusercontent.com/8940907/113503593-8dd3a900-953b-11eb-98db-be71178b80be.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by harsharay** [comment]
I want to contribute. How can i do that

**Comment by yuval-hazaz** [comment]
> I want to contribute. How can i do that

Great. 
If you already have a running env and just want me to assign this to you, I can do that.
If you need help with getting a dev env up and running we can talk on our discord server https://discord.gg/KSJCZ24vj2
