### ISSUE TITLE
Server: Swagger documentation does not match REST-API

### ISSUE THREAD

**Issue by timhuebener** [amplication/amplication#1314]
**Describe the bug**
A project's swagger documentation page (http://localhost:3000/api/) requires an ID for the GET/<entity> endpoint (e.g. /api/users). 

The same goes for sub-entities. For example, /api/users/<id>/comments requires an ID for the user and the comment. Thus you can't get all comments of a user. 

**To Reproduce**
1. Go to http://localhost:3000/api/
2. Click on GET /api/users

**Expected behavior**
The swagger documentation should not require an ID for GET many requests.

**Comment by yuval-hazaz** [comment]
Thanks @timhuebener we are looking into the fix. It seems like an issue with the swagger decorators and the way they handle child properties of the query objects. I will keep you updated

**Comment by yuval-hazaz** [comment]
It seems like an issue with nest-swagger
I created a bug report and waiting for a response. 
https://github.com/nestjs/nest/issues/6885

**Comment by yuval-hazaz** [comment]
I found a way to make it work, I added the details on the issue on nest repo
https://github.com/nestjs/swagger/issues/1299
