### ISSUE TITLE
Server: JSON type not compatible between REST, GraphQL, and Admin UI

### ISSUE THREAD

**Issue by alonram** [amplication/amplication#1321]
**Describe the bug**
Creating records with data type json using GraphQL cause an error on Admin UI view, REST Get works fine 
Creating records with data type json using REST cause an error on GraphQL query, Admin UI works fine

**To Reproduce**
1. Create an entity with at least one JSON dayatype
2. Use GraphQL Mutation and create a new record
3. Open Admin UI and view all records gets an error (show blank screen)
4. Use REST POST to create a new record
5. Open GraphQL, Query will fail "JSONObject cannot represent non-object value"

Using Amplication sandbox
![Screenshot (58)](https://user-images.githubusercontent.com/40050499/115242856-49760a80-a0f0-11eb-9179-a256c4677c95.png)

**Comment by yenicelik** [comment]
can you specify your entities that you use for this?

**Comment by yuval-hazaz** [comment]
I could reproduce this issue with the default sample project

**Comment by exsilium** [comment]
Created an Entity that includes a json object field. It seems it's not possible to create / edit that type of data within the React-Admin client.

**Comment by yuval-hazaz** [comment]
> Created an Entity that includes a json object field. It seems it's not possible to create / edit that type of data within the React-Admin client.

@exsilium that is correct. 
Usually, the JSON represents an object with multiple fields.  You need to use code to build the JSON from multiple input fields and send the object with the request to the API. 
If you want to allow the user to add a JSON string to a text field you will need to add the text field to the client yourself, as it is not created by Amplication for the reason mentioned above.

**Comment by exsilium** [comment]
Thank you for the explanation @yuval-hazaz , I think my expectation for a JSON data type I had when trying Amplication out was that I was expecting a simple text box that would allow me to create or update a json structure for that particular object / data field I had defined within Amplication Entity. (Syntax validating the json structure would of course be a plus) :sunglasses:

**Comment by yuval-hazaz** [comment]
That can work maybe with a flag on the UI whether to display the field on the client or not. So, by default, it will not be set, and in case you do want to show the field you will be able to enable the flag.

would you mind opening a new feature request with these details. although it is not that common, I agree It may be needed in some use cases
