### ISSUE TITLE
[Server/Client]: client dont show if git env missing

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1326]
when deploy the server and client localy without the git local end file, error show:
Cannot return null for non-nullable field AuthorizeAppWithGithubResult.url.

**To Reproduce**
1. start up localy server and client
2. enter Sync with GitHub in app
3. trun on and off the option

**Screenshots**
<img width="1392" alt="Screen Shot 2021-04-25 at 14 36 31" src="https://user-images.githubusercontent.com/61761153/115991949-ba775f80-a5d3-11eb-98fa-ffdd5802933e.png">

**Comment by yuval-hazaz** [comment]
Thanks @tupe12334 

When the required env parameters are missing throw a dedicated error with details  

see this doc for more details
https://docs.amplication.com/docs/connect-server-to-github

The required parameters are :

GITHUB_SECRET_SECRET_NAME=use_local_settings
GITHUB_CLIENT_SECRET=[use your own secret] 
GITHUB_CLIENT_ID=[use your own client ID]
GITHUB_SCOPE=user:email
GITHUB_REDIRECT_URI=http://localhost:3001/github/callback
GITHUB_APP_AUTH_SCOPE=user:email,repo,read:org
GITHUB_APP_AUTH_REDIRECT_URI=http://localhost:3001/github-auth-app/callback/{appId}
