### ISSUE TITLE
Server: Add schema and resolvers for managing user's preferences

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#1335]
Currently, we are saving some local user preferences on the local storage on the client-side.
Instead, we should use server-side mechanics, to allow the user to carry her preferences from one client to another

**Comment by yenicelik** [comment]
wouldn't this be done through custom columns in the user entity?

**Comment by yuval-hazaz** [comment]
This feature is about Amplication server and not about the generated app. 
There are several preferences that are currently saved in the client using local storage (for example, dark/light mode)
The idea is to create a generic API to save user preferences instead of adding a custom field for every use case.
It is a lower priority as its impact is very low right now.
