### ISSUE TITLE
Server: node 16 depreciation of node_http_parser

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1343]
when i updated my node to v 16 and run the command start:debug in amplication-server folder i got the error:

**start of error**

node[10985]: ../src/node_http_parser.cc:567:static void node::(anonymous namespace)::Parser::Initialize(const FunctionCallbackInfo<v8::Value> &): Assertion `args[3]->IsInt32()' failed.
 1: 0x10dc0fee5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x10c8c5dc9 node::Abort() [/usr/local/bin/node]
 3: 0x10c8c5c31 node::Assert(node::AssertionInfo const&) [/usr/local/bin/node]
 4: 0x10c8e306f node::(anonymous namespace)::Parser::Initialize(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 5: 0x10cab6ae5 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 6: 0x10cab60b8 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 7: 0x10cab567f v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x10d344a19 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]

**end of error**

Desktop :
 - OS: macos 11.2.3

**Comment by yuval-hazaz** [comment]
@tupe12334 is this still relevant?
