### ISSUE TITLE
Data Service Generator: add to the base folder *dont overwrite*

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1345]
in the base folder in the code that generated adding comment that say not to overwrite the contant to prevent git collision

**Comment by yenicelik** [comment]
from what I understand the base files are all generated through amplication, and we need to use these as base classes. or maybe i misunderstand the request: can you be more specific with the request?

**Comment by yuval-hazaz** [comment]
I had the chance to talk with @tupe12334 about it. His request was to add a static comment to all files in the base folder to describe exactly that... Telling the developer not to change it manually and expect any manual change to be overwritten

**Comment by yuval-hazaz** [comment]
PR #1871 fixes this issue partially.
We leave this issue open for completing the task for all other auto-generated files

**Comment by mshidlov** [comment]
@yuval-hazaz I think it will be best to open a new feature request for that and refer to this issue. 
This issue already merged to a milestone that is going to be released, and it already has 2 PR's attached to it.

**Comment by yuval-hazaz** [comment]
done.
I opened #2215

**Comment by souravjain540** [comment]
@tupe12334  can you explain what's this issue about particularly?

**Comment by tupe12334** [comment]
@souravjain540 i dont think this pr is part of the release, ask @mshidlov because its not all finish

**Comment by mshidlov** [comment]
@souravjain540 comment to **all** files in the entities base folder (for example `user.controller.base.ts`,`user.resolver.base.ts`, `user.service.base.ts`) to describe exactly that... Telling the developer not to change it manually and expect any manual change to be overwritten
