### ISSUE TITLE
Data Service Generator: roles not saving properly

### ISSUE THREAD

**Issue by jithinlal** [amplication/amplication#1346]
**Describe the bug**
Could not see the role on the database side of things for a user.

**Expected behavior**
A specific role name or role id should be shown

**Comment by jithinlal** [comment]
![Uploading 04-05-2021 23-59-34.png…]()

**Comment by yuval-hazaz** [comment]
the screenshot was not uploaded correctly, can you please try again?
from the description you provided I am not sure what the issue it

**Comment by jithinlal** [comment]
seems like the role based items are not getting committed. 
![04-05-2021 23-59-34](https://user-images.githubusercontent.com/9658385/117052563-83bcea00-ad35-11eb-956d-4a5466d71751.png)

**Comment by yuval-hazaz** [comment]
> seems like the role based items are not getting committed.
can you please describe how did you try to update it?

**Comment by jithinlal** [comment]
I tried to add a new role, but seems like apart from the other features, role does not seems to commit for VCS. also the above entry pops up in the DB. `{user}` Is this expected?

**Comment by yuval-hazaz** [comment]
Just to make sure I understand - 
you are trying to update a user record in the generated app with a new role and it is not saved. right?

Are you using the Admin UI to update the record? or is it via the API (graph? REST?)

Did you try to create a new user record? 

how many roles do you have in your app?

thanks!

**Comment by jithinlal** [comment]
I am using the Admin UI

**Comment by jithinlal** [comment]
And i have 2 roles

**Comment by yuval-hazaz** [comment]
resolved in new admin UI with react-admin
