### ISSUE TITLE
[Documentation]: [Missing import line]

### ISSUE THREAD

**Issue by yenicelik** [amplication/amplication#1364]
**Describe the bug**
when i follow all the docs from amplication.com
the REST or graphql examples dont seem to work
specifically, 
 
```
  @graphql.Query(() => [User])
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async users(
      @graphql.Args() args: UserFindManyArgs,
      @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const results = await this.service.findMany({
      ...args,
      take: 100,
    });
    return results.map((result) => permission.filter(result));
  }
```
 

`gqlUserRoles`  here seems to not be found
did i miss adding any export, or is this a bug?

**To Reproduce**

this one, for example: https://docs.amplication.com/docs/custom-code/graphql-query
How to add an query to a GraphQL resolver | Amplication Docs
How to add a query to a GraphQL resolver
yes, i copied / modified it from the base folder

**Fix**
ah nvm that fixed it, apparently the import import * as gqlUserRoles from "../auth/gqlUserRoles.decorator";  was missing
webstorm autocompleted when i copy-pasted it a second time from the base
but failed to auto-suggest imports.

probably adding this line to the docs would be useful

**Comment by yenicelik** [comment]
same goes for the REST approach

**Comment by yuval-hazaz** [comment]
resolved in https://github.com/amplication/docs/pull/65
