### ISSUE TITLE
Client with 0.6.0 build: Can't capitalize more than first letter of entity name

### ISSUE THREAD

**Issue by twavis** [amplication/amplication#1377]
**Describe the bug**
Schema isn't generated/linked properly if entity name has an uppercase character after the first letter.

**To Reproduce**
1. Create an entity with PascalCase name
2. Build
3. Check out the admin ui/client for that entity. It will error that the schema does not exist.

**Comment by twavis** [comment]
Display name spacing/capitalization may be a problem also.

**Comment by tupe12334** [comment]
@twavis happy to let you know that i fix that in the next version of the data provider

**Comment by souravjain540** [comment]
Server Fix
Now you can create the entity name in pascalCase too.

**Comment by mshidlov** [comment]
this is reopened issue - the bug was fixed in earlier versions. the current fix is related to relations between entities. this is a client error that parses the relations incorrectly when using camel case entities relation.
