### ISSUE TITLE
Data Service Generator: Relation fields are not displayed on parent (discrepancy between data representation and type) 

### ISSUE THREAD

**Issue by yenicelik** [amplication/amplication#1387]
**Describe the bug**
Not entirely a bug, could also be seen as a feature request, but an "important" one.

**To Reproduce**
I have defined this entity "Order" in amplication.com

<img width="972" alt="Screenshot_2021-05-20_at_12 30 00" src="https://user-images.githubusercontent.com/8946130/118968593-62cada80-b96c-11eb-92af-7692ce0783b3.png">

The generated type looks as follows:

```
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";

export type Order = {
  absoluteDiscount: number;
  createdAt: Date;
  currency: string;
  dateSubmitted: Date;
  expectedDeliveryDate: string | null;
  id: string;
  note: string | null;
  origin: string | null;
  paidOnDate: Date | null;
  reference: string;
  shipmentAddress: string;
  status?:
    | "CustomerIsWaitingForOffer"
    | "VendorIsWaitingForConfirmation"
    | "CustomerWaitingForDelivery"
    | "DeliverySent";
  taxRate: number;
  totalPriceIncludingDiscountAndTaxRate: number | null;
  updatedAt: Date;
  user?: UserWhereUniqueInput | null;
  validThroughDate: Date | null;
};
```

The child does include these fields, however.

<img width="932" alt="Screenshot_2021-05-20_at_12 31 18" src="https://user-images.githubusercontent.com/8946130/118968822-ad4c5700-b96c-11eb-90ca-14e46bb6e82b.png">

**Expected behavior**
The generated type is missing the "files" and "orderItems" keys which are foreign keys. These are defined in the database like that, and can also be queryable by graphql, but don't seem to be included in the type definition. This is a discrepancy between the data, and the data represention (thus, kinda a bug). These fields should be added to the generated types, as this is how the database (and graphql) include these.

**Comment by yenicelik** [comment]
Also, @yuval-hazaz , a short question:

The child-keys are not recorded within the entities as properties. When I want to insert a new entity like the following one (pseudo-code of the types):

```
Order {
    id,
    reference,
    createdAt,
    parts: [
        id,
        stockKeepingUnit,
        partQuantity
    ]
}
```

How would I best go about this? 

The current implementation (to my understanding), does not support inserting this into the "createOrder" graphql-endpoint. Would doing two-mutate queries as follows do the job?:

```
createOrder({
    id,
    reference,
    createdAt,
})
```

and then 

```
createParts([
        id,
        stockKeepingUnit,
        partQuantity,
        orderId
    ])
```

?

**Comment by yuval-hazaz** [comment]
I agree it is the expected to see the relation field on the model.

It should be there, regardless whether we add support for multiple child inserts (currently not supported)

**Comment by yenicelik** [comment]
also, just checking again; the parent id is not included in the "Create" schema of the child, and the child id is not included in the "Create" schema of the parent (i.e. for a mutation, and during a creation of any of these objects, i cannot specify the foreign key for either one of them).

Does this mean that i would have to (1) create the parent, (2) create the child and _only_ then (3) update the foreign key of the child with the parent's id?

The generated interfaces (Create, and full entity-interfaces) look as follows for parent and child (Order, and OrderItem respectively):

```
export type OrderItem = {
  createdAt: Date;
  id: string;
  order?: OrderWhereUniqueInput;
  part?: PartUpdateInput | null;  // Same with Part, all of Part should be retrieved ...
  quantity: number | null;
  itemListPrice: number | null;
  singleItemPriceIncludingMargin: number | null;
  updatedAt: Date;
};
```

and

```
export type Order = {
  absoluteDiscount: number;
  createdAt: Date;
  currency: string;
  dateSubmitted: Date;
  expectedDeliveryDate: string | null;
  id: string;
  note: string | null;
  origin: string | null;
  paidOnDate: Date | null;
  reference: string;
  shipmentAddress: string;
  status?:
    | "CustomerIsWaitingForOffer"
    | "VendorIsWaitingForConfirmation"
    | "CustomerWaitingForDelivery"
    | "DeliverySent";
  taxRate: number;
  totalPriceIncludingDiscountAndTaxRate: number | null;
  updatedAt: Date;
  user?: UserWhereUniqueInput | null;
  validThroughDate: Date | null
};
```

(and for the creation interfaces, such foreign keys are missing completely)

```
export type OrderCreateInput = {
  absoluteDiscount: number;
  currency: string;
  dateSubmitted: Date;
  expectedDeliveryDate?: string | null;
  note?: string | null;
  origin?: string | null;
  paidOnDate?: Date | null;
  reference: string;
  shipmentAddress: string;
  status:
    | "CustomerIsWaitingForOffer"
    | "VendorIsWaitingForConfirmation"
    | "CustomerWaitingForDelivery"
    | "DeliverySent";
  taxRate: number;
  totalPriceIncludingDiscountAndTaxRate?: number | null;
  user?: UserWhereUniqueInput | null;
  validThroughDate?: Date | null;
  orderItems: OrderItemCreateInput[];
};
```

and 

```

export type OrderItemCreateInput = {
  part?: PartWhereInput | null;
  quantity?: number | null;
  itemListPrice?: number | null;
  singleItemPriceIncludingMargin?: number | null;
};
```

**Comment by yuval-hazaz** [comment]
The relation are set in the create mutation using the "EntityWhereUniqueInput" interface... 
For example, in the OrderCreateInput you showed above, you can see the property `user?: UserWhereUniqueInput | null;`

Based on the description I would expect to see `order?: OrderWhereUniqueInput;` on `OrderItemCreateInput`.
So, it is either something wrong in the definition of your OrderItem, or there is a bug.

Please provide a screenshot of the Order and OrderItems Entities - specifically on the relation fields between them

**Comment by yenicelik** [comment]
Definition of Order

<img width="1038" alt="Screenshot 2021-05-23 at 10 49 07" src="https://user-images.githubusercontent.com/8946130/119254061-82544400-bbb4-11eb-9761-dc464f78aa85.png">

Definition of OrderItems

<img width="1037" alt="Screenshot 2021-05-23 at 10 49 32" src="https://user-images.githubusercontent.com/8946130/119254070-91d38d00-bbb4-11eb-91f0-ebef45d6050a.png">

@yuval-hazaz Is this sufficient information?

**Comment by yuval-hazaz** [comment]
OK. 

> I just deleted and re-created the columns, the column does show up now. So maybe this was a bug from a prior version?

OK. thanks.
There are several tests that cover this area, including a snapshot test of an entire sample app. 
From what I can, it looks OK
Have a look here for example
https://github.com/amplication/amplication/blob/598e74d1b83ede3035da3dfdcdd7be26a47a2812/packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap#L257 


In any case, this issue will remain open for the first part (missing properties on the model)

**Comment by TKGZ** [comment]
@yuval-hazaz  I have the same issue

**Comment by yuval-hazaz** [comment]
> @yuval-hazaz I have the same issue when trying to insert an object
Are you referring to the missing relation properties on the model or the missing EntityWhereUniqueInput on the CreateInput?
