### ISSUE TITLE
Dashboard: Delete App

### ISSUE THREAD

**Issue by daniellaera** [amplication/amplication#1389]
Describe the bug
Delete an application impossible in the dashbpard > https://app.amplication.com

To Reproduce
go to https://app.amplication.com/

Expected behavior
Delete an App or clicking on it and delete it somewhere

**Comment by yenicelik** [comment]
this ticket would probably make more sense as a feature request?

**Comment by yuval-hazaz** [comment]
this was requested several times already on the Discord channel and should be easy to implement. 
Help needed, if anyone is up to it

**Comment by ChakshuGautam** [comment]
I would like to take this up @yuval-hazaz.

**Comment by yuval-hazaz** [comment]
Great:
1. Add a delete button on ApplicationCard.tsx
2. On Click-> Show ConfirnationDialog (1import { ConfirmationDialog } from "@amplication/design-system";`)
