### ISSUE TITLE
Admin-ui: node-sass required to run

### ISSUE THREAD

**Issue by TKGZ** [amplication/amplication#1391]
![image](https://user-images.githubusercontent.com/36269621/119383065-3217d780-bcc3-11eb-9bca-ca40c9358789.png)

When I start admin-ui after pulling from Amplication, I get the issue above.

This is fixed when doing `npm i node-sass`.

Could this be an issue of my local configuration?

**Comment by yuval-hazaz** [comment]
I could guess that node-sass may be installed globally on some machines and this is why we didn't see this error yet, but... I would at least expect to see this error when we deploy to the sandbox environment... and we never saw that

Did you follow the instructions on this doc?
https://docs.amplication.com/docs/getting-started/dev-env

**Comment by TKGZ** [comment]
I assume it's a local error since it works fine on my Friend's amplication. But it doesn't seem to be in the package.json by default, right?

**Comment by TKGZ** [comment]
So it's not sepossed to need it?

**Comment by yuval-hazaz** [comment]
> I assume it's a local error since it works fine on my Friend's amplication. But it doesn't seem to be in the package.json by default, right?

It is not in the packge.json but probably a dependency of another package. From the image you've attached, it looks like a dependency of react-scripts... but still you should have not installed it manually. 
Usually in this type of error, deleting the entire node_modules folder helps before running `npm i` again

**Comment by TKGZ** [comment]
Thanks!

**Comment by twavis** [comment]
I ran into this issue as well. I think adding it to devDependancies in the package.json would be a logical solution.
