### ISSUE TITLE
[Admin-UI]: Changing plural of an entity cause error

### ISSUE THREAD

**Issue by dj-fiorex** [amplication/amplication#1401]
**Describe the bug**
When i create an entity (Prodotto) and then change the plural name (Prodotti), the Admin-ui show the old plural name "Prodottos" and this error: 
"Unknown resource Prodotto. Make sure it has been declared on your server side schema. Known resources are User"

**To Reproduce**
1. Create new project
2. Create new Entity
3. Change plural name
4. Build
5. Go to Admin-UI

**Expected behavior**
I can change plural name of an entity 

***EDIT
if i change the plural to default it works

**Comment by yuval-hazaz** [comment]
@abrl91 if I remember correctly you already fixed this issue , can you please confirm?

**Comment by abrl91** [comment]
> @abrl91 if I remember correctly you already fixed this issue , can you please confirm?

I don't remember. I can check.
What about this PR:
https://github.com/amplication/amplication/pull/2429

**Comment by abrl91** [comment]
@yuval-hazaz 
I generated a sample app and changed the plural name of the Product entity to Prodotti. The ProductList component was generated as follows:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/39680385/180620519-75d7d81b-b3eb-4953-95b2-1c6fc8cf3f79.png">

I added data on the Admin UI and everything worked as expected.

Therefore, I think we can close this issue.
