### ISSUE TITLE
Automatic Code Generation: Should not overridepackage.json, Dockerfile, .env files

### ISSUE THREAD

**Issue by yenicelik** [amplication/amplication#1407]
**Is your feature request related to a problem? Please describe.**
Assuming the user has modified 

- the Dockerfile
- the environment files
- the package.json file
- the package-lock.json file

all these files are overwritten when a new amplication PR is created. This is destructive of the user's work, and requires the user to time-intensively fix the PR.

**Describe the solution you'd like**
Perhaps only instantiating these files at the beginning, or some checkboxes in the UI which allow the user to define which files to overwrite? Another more scalable solution would be something like an `.amplicationignore` file (similar to .gitignore, .ebignore) that can be defined in github, and that defined which files to not overwrite.

**Comment by yuval-hazaz** [comment]
We plan to offer a more robust solution that will allow you to merge to skip changes coming from Amplication - and as long as there are no changes from Amplication, leaving your local changes in place.

but other than that, I like the .amplicationignore approach.
It may be very helpful with edge cases

**Comment by yuval-hazaz** [comment]
we are tracking the progress of this issue on https://github.com/amplication/amplication/issues/3051
closing this as a duplicate
