### ISSUE TITLE
Server: Is prisma cascade delete supported?

### ISSUE THREAD

**Issue by aridgupta** [amplication/amplication#1409]
Prisma doesn't yet support cascade deletes. One would normally need to write raw SQL to handle cascade deletes. This is a [discussion](https://github.com/prisma/prisma/issues/2810) on the prisma repo. Does this library support cascade deletes using prisma?

**Comment by yuval-hazaz** [comment]
A few days ago Prisma released v2.26.0 with cascade delete support (in preview)
https://github.com/prisma/prisma/releases/tag/2.26.0

We will wait for a future release with GA before we implement cascade delete

**Comment by thebiglabasky** [comment]
We're currently planning to promote this one to GA around the beginning to mid-september.

**Comment by yuval-hazaz** [comment]
@thebiglabasky thanks for sharing
Keep up the excellent work with Prisma

**Comment by janpio** [comment]
Here you go: https://github.com/prisma/prisma/releases/tag/3.0.1 Make sure to read the release notes properly and take not of the potential breaking changes.
