### ISSUE TITLE
Data Service Generator: Support for unique constraints and indexes

### ISSUE THREAD

**Issue by richardweaver** [amplication/amplication#1489]
**Is your feature request related to a problem? Please describe.**
I am building an app where I have already manually created a Prisma schema and am trying to reproduce in Amplication. Not all Prisma schema features can be represented in the Amplication UI which reduces my ability to shape the schema how I would like.

**Describe the solution you'd like**
Add support for Prisma attributes ([https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference/#attributes]https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference/#attributes)
1. The ability to add a unique constraint (`@unique` attribute in Prisma schema) to entity fields. Presumably best represented with a checkbox in the UI.
2. The ability to define multi-column unique constraints (`@@unique` in Prisma schema) on entities.
3. The ability to define indexes (`@@index` in Prisma schema) on entities.

I will attempt to implement when I get time...

**Comment by yuval-hazaz** [comment]
Suggestions 1 is implemented in #1493 
This issue remains open for tracking the suggestions 2 and 3
