### ISSUE TITLE
Server: Adding unique fields

### ISSUE THREAD

**Issue by NullF0rest** [amplication/amplication#1493]
Adding support for unique indexes/fields.

For things like email, company id, national id so on. having a constraint like this in the DB level would be great. 
I think it should be is supported in Prisma as well.

**Comment by richardweaver** [comment]
Great minds think alike: I opened #1489 yesterday.

**Comment by yuval-hazaz** [comment]
@lalit8347 will implement adding "Unique field" toggle on the entity field. 
in this phase, we will only support unique field per a single field, without multi-columns unique fields,

After implementing the first phase, we will consider adding support for multi-columns

**Comment by yuval-hazaz** [comment]
@all-contrbutors please add @NullF0rest for ideaa

**Comment by yuval-hazaz** [comment]
@all-contributors please add @NullF0rest for ideas

**Comment by yuval-hazaz** [comment]
implemented in  #1615
