### ISSUE TITLE
Data Service Generator: missing types cant tsc

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1612]
cant run tsc in data service generator inside `npm run build -- --scope @amplication/server --include-dependencies`
got error

`> @amplication/data-service-generator@0.7.0 build:compile
> tsc

src/server/resource/controller/controller.base.template.ts:14:30 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

14 import { plainToClass } from "class-transformer";
                                ~~~~~~~~~~~~~~~~~~~

src/server/resource/dto/graphql/find-many/find-many-args.template.ts:3:22 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

3 import { Type } from "class-transformer";
                       ~~~~~~~~~~~~~~~~~~~

src/server/resource/service/service.base.template.ts:18:24 - error TS2339: Property 'DELEGATE' does not exist on type 'PrismaService'.

18     return this.prisma.DELEGATE.count(args);
                          ~~~~~~~~

src/server/resource/service/service.base.template.ts:24:24 - error TS2339: Property 'DELEGATE' does not exist on type 'PrismaService'.

24     return this.prisma.DELEGATE.findMany(args);
                          ~~~~~~~~

src/server/resource/service/service.base.template.ts:29:24 - error TS2339: Property 'DELEGATE' does not exist on type 'PrismaService'.

29     return this.prisma.DELEGATE.findUnique(args);
                          ~~~~~~~~

src/server/resource/service/service.base.template.ts:46:24 - error TS2339: Property 'DELEGATE' does not exist on type 'PrismaService'.

46     return this.prisma.DELEGATE.delete(args);
                          ~~~~~~~~

src/server/resource/service/to-many.template.ts:17:24 - error TS2339: Property 'DELEGATE' does not exist on type 'PrismaService'.

17     return this.prisma.DELEGATE.findUnique({
                          ~~~~~~~~

src/server/resource/service/to-one.template.ts:12:24 - error TS2339: Property 'DELEGATE' does not exist on type 'PrismaService'.

12     return this.prisma.DELEGATE.findUnique({
                          ~~~~~~~~

src/server/seed/seed.template.ts:2:10 - error TS2305: Module '"../../../node_modules/@prisma/client"' has no exported member 'PrismaClient'.

2 import { PrismaClient } from "@prisma/client";
           ~~~~~~~~~~~~

src/server/static/scripts/clean.ts:5:10 - error TS2305: Module '"../../../../node_modules/@prisma/client"' has no exported member 'PrismaClient'.

5 import { PrismaClient } from "@prisma/client";
           ~~~~~~~~~~~~

src/server/static/src/auth/Credentials.ts:3:26 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

3 import { IsString } from "class-validator";
                           ~~~~~~~~~~~~~~~~~

src/server/static/src/util/BooleanFilter.ts:3:28 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

3 import { IsOptional } from "class-validator";
                             ~~~~~~~~~~~~~~~~~

src/server/static/src/util/BooleanFilter.ts:4:22 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

4 import { Type } from "class-transformer";
                       ~~~~~~~~~~~~~~~~~~~

src/server/static/src/util/BooleanNullableFilter.ts:3:28 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

3 import { IsOptional } from "class-validator";
                             ~~~~~~~~~~~~~~~~~

src/server/static/src/util/BooleanNullableFilter.ts:4:22 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

4 import { Type } from "class-transformer";
                       ~~~~~~~~~~~~~~~~~~~

src/server/static/src/util/DateTimeFilter.ts:3:28 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

3 import { IsOptional } from "class-validator";
                             ~~~~~~~~~~~~~~~~~

src/server/static/src/util/DateTimeFilter.ts:4:22 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

4 import { Type } from "class-transformer";
                       ~~~~~~~~~~~~~~~~~~~

src/server/static/src/util/DateTimeNullableFilter.ts:3:28 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

3 import { IsOptional } from "class-validator";
                             ~~~~~~~~~~~~~~~~~

src/server/static/src/util/DateTimeNullableFilter.ts:4:22 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

4 import { Type } from "class-transformer";
                       ~~~~~~~~~~~~~~~~~~~

src/server/static/src/util/FloatFilter.ts:3:28 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

3 import { IsOptional } from "class-validator";
                             ~~~~~~~~~~~~~~~~~

src/server/static/src/util/FloatFilter.ts:4:22 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

4 import { Type } from "class-transformer";
                       ~~~~~~~~~~~~~~~~~~~

src/server/static/src/util/FloatNullableFilter.ts:3:28 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

3 import { IsOptional } from "class-validator";
                             ~~~~~~~~~~~~~~~~~

src/server/static/src/util/FloatNullableFilter.ts:4:22 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

4 import { Type } from "class-transformer";
                       ~~~~~~~~~~~~~~~~~~~

src/server/static/src/util/IntFilter.ts:3:28 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

3 import { IsOptional } from "class-validator";
                             ~~~~~~~~~~~~~~~~~

src/server/static/src/util/IntFilter.ts:4:22 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

4 import { Type } from "class-transformer";
                       ~~~~~~~~~~~~~~~~~~~

src/server/static/src/util/IntNullableFilter.ts:3:28 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

3 import { IsOptional } from "class-validator";
                             ~~~~~~~~~~~~~~~~~

src/server/static/src/util/IntNullableFilter.ts:4:22 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

4 import { Type } from "class-transformer";
                       ~~~~~~~~~~~~~~~~~~~

src/server/static/src/util/JsonNullableFilter.ts:6:28 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

6 import { IsOptional } from "class-validator";
                             ~~~~~~~~~~~~~~~~~

src/server/static/src/util/StringFilter.ts:4:28 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

4 import { IsOptional } from "class-validator";
                             ~~~~~~~~~~~~~~~~~

src/server/static/src/util/StringFilter.ts:5:22 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

5 import { Type } from "class-transformer";
                       ~~~~~~~~~~~~~~~~~~~

src/server/static/src/util/StringNullableFilter.ts:4:28 - error TS7016: Could not find a declaration file for module 'class-validator'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-validator/bundles/index.umd.js' implicitly has an 'any' type.
  Try `npm install @types/class-validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-validator';`

4 import { IsOptional } from "class-validator";
                             ~~~~~~~~~~~~~~~~~

src/server/static/src/util/StringNullableFilter.ts:5:22 - error TS7016: Could not find a declaration file for module 'class-transformer'. '/Users/ofek/Documents/Git/amplication/packages/amplication-data-service-generator/node_modules/class-transformer/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/class-transformer` if it exists or add a new declaration (.d.ts) file containing `declare module 'class-transformer';`

5 import { Type } from "class-transformer";
                       ~~~~~~~~~~~~~~~~~~~

Found 32 errors.

The terminal process "/bin/zsh '-c', 'npm run build:compile'" terminated with exit code: 2.

Terminal will be reused by tasks, press any key to close it.`

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - MacBook m1

**Comment by yuval-hazaz** [comment]
thanks @tupe12334 
I think this issue was already resolved in #1421

Please see that you have the latest version from `master` and try again

if you still experiencing this issue with the latest version let us know
