### ISSUE TITLE
[Server/Data Service Generator]: [Add an ability to import or write schema.prisma to amplication]

### ISSUE THREAD

**Issue by sandbox-apps** [amplication/amplication#1617]
**Is your feature request related to a problem? Please describe.**
I love how good Amplication is using the UI for creating model/entity.
But really the easiness and the joy writing a schema using Prisma DSL sometimes makes a lot more sense and faster than specifying all by clicking and selecting, connecting types in the form...

**Describe the solution you'd like**
Add a feature where we can add a schema.prisma file or directly write a schema.prisma file inside amplicationn much like a prisma playground and generate all the entities base on the prisma file

**Comment by sandbox-apps** [comment]
Maybe if we can also build things like this all other things like this issue can be solve at least without the UI Form
https://github.com/amplication/amplication/issues/1493

**Comment by yuval-hazaz** [comment]
Thanks! that is a good idea and it can be very helpful also to cover all use cases which are not yet supported by the UI or CLI

@all-contributors please add @sandbox-apps  for ideas

**Comment by sandbox-apps** [comment]
Yeah after all Prisma will have much more new features coming out. Like specifying also triggers and constraint in the schema.. Also. maybe a creating a virtual table view in near future. :)

**Comment by yuval-hazaz** [comment]
agree

**Comment by sandbox-apps** [comment]
By this if will be implemented, we can also have the cascading option on specifying models that I believe is not yet available in the UI?

**Comment by yuval-hazaz** [comment]
That is correct, cascade is not available yet. 
see #1409

**Comment by yuval-hazaz** [comment]
already implemented
