### ISSUE TITLE
Server: Custom seed script

### ISSUE THREAD

**Issue by richardweaver** [amplication/amplication#1618]
**Is your feature request related to a problem? Please describe.**
I would like to add a custom seed script to my server application as I have a number of pre-filled reference tables.

**Describe the solution you'd like**
An extension endpoint for database seeding. So the generated seeding for users and roles is maintained by Amplication, but I can add a custom seed function that is called by the base (much as there is for controllers, modules, resolvers and services).

**Describe alternatives you've considered**
I tried implementing this as a SQL script that needs to be run manually, but because of the use of `cuid` as the ID type it is difficult.

**Comment by yuval-hazaz** [comment]
@richardweaver I like this idea!
It can be very beneficial for may, and totally aligned with our roadmap and vision 
I will see how and when we can include this

**Comment by yuval-hazaz** [comment]
@all-contributors please add @richardweaver for ideas

**Comment by MatthiasWanner** [comment]
Indeed it would be interesting to be able to customize seeds to add informations concerning the created user: rôle, etc...
Your tool is very impressive. Congratulations

**Comment by yuval-hazaz** [comment]
@all-contributors please add @richardweaver for ideas

**Comment by yuval-hazaz** [comment]
@all-contributors please add @MatthiasWanner for ideas
