### ISSUE TITLE
[Server]: [Docs section for managing/using roles]

### ISSUE THREAD

**Issue by sandbox-apps** [amplication/amplication#1651]
**Is your feature request related to a problem? Please describe.**
Im trying to find docs about using and managing roles in amplication as I might that good about authentication and authorization. 

**Describe the solution you'd like**
Atleast have some walkthrough/setup and best practices for security using roles..
Such as record ownership and many others...

**Comment by yuval-hazaz** [comment]
see this doc with steps on how to use roles
https://docs.amplication.com/docs/first-app

Currently, Amplication does not support "record ownership" or multi-tenancy permission schema. 
There are multiple feature requests in this domain and it is on our backlog.
