### ISSUE TITLE
Server: Update to NestJS 8

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#1659]
https://trilon.io/blog/announcing-nestjs-8-whats-new

**Comment by tupe12334** [comment]
started to work on that just update that right now it is stuck because the package @codebrew/nestjs-storage is have rxjs 6 as peer dep and nestjs 8 use rxjs 7, i created a pr in the repository to fix that and remove rxjs from the peer dependenices list

**Comment by souravjain540** [comment]
Server Feature

NestJS is updated to version 8.
