### ISSUE TITLE
[Data Service Generator]: [GENERATED CODE - DO NOT MODIFY BY HAND] for files that are not recommended to be modified

### ISSUE THREAD

**Issue by sandbox-apps** [amplication/amplication#1677]
**Is your feature request related to a problem? Please describe.**
There should be a warning for the user about the base files
Maybe on top of the file

// **************************************************************************
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************

Something like this. So that no newcomers will ever do such thing :)

**Comment by yuval-hazaz** [comment]
duplicate of #1345
