### ISSUE TITLE
Data Service Generator: choose between REST, GraphQL or both

### ISSUE THREAD

**Issue by sandbox-apps** [amplication/amplication#1681]
**Is your feature request related to a problem? Please describe.**
Add an option to select only Rest API or GraphQL or both for generating code

**Comment by yuval-hazaz** [comment]
Another good idea! thanks
There are some implications we need to consider before implementing this feature but I totally agree it is needed.  
for example, the admin UI is working with GraphQL API - so without it on the server, the client will not work.

**Comment by sandbox-apps** [comment]
Yes that would be a breaking changes with admin UI...
But this is just a cleanup project issue if ever for clients and developers to use what they and not exposing other endpoints :D
