### ISSUE TITLE
Storybook Integration/Support

### ISSUE THREAD

**Issue by regicsolutions** [amplication/amplication#1693]
It would be great to have [Storybook](https://storybook.js.org/) integration where you are able make use of UI components.

**Comment by yuval-hazaz** [comment]
Thanks @regicsolutions 
As a choice, we mainly focus on the server-side, and most of our efforts are on it. 
We do provide the client as a starting point and will continue adding support on the client for using new features from the server.
But, I do not see how we invest time in this type of integration.

I will leave this request open so anyone can add its thought about it. 
Thanks

**Comment by yuval-hazaz** [comment]
@all-contributors please add @regicsolutions for ideas
