### ISSUE TITLE
Generated App - Secrets manager

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#1696]
**Is your feature request related to a problem? Please describe.**
In many scenarios, there is a need to use secrets in the code. 
e.g. to generate a JWT token there is a need for a secret (or certificate public key)

It can be very beneficial to have a built-in generic service in the generated app to fetch secrets from a vault. 

**Describe the solution you'd like**
A built-in generic SecretService with a single function "getSecret".
By default, for the development environment, the secret service will return the secret from the ConfigService (.env files)

The SecretService will be built as a factory and will allow implementations of different providers by the developer.

As a second phase, we can add providers for common services like AWS, GCP, etc...

**Comment by tupe12334** [comment]
isn't that finish?

**Comment by yuval-hazaz** [comment]
resolved in #1714
