### ISSUE TITLE
⭐️ Plugin: ESLint/Prettier by default with your own config

### ISSUE THREAD

**Issue by MatthiasWanner** [amplication/amplication#1703]
I'm a Digital Copilote team member. We use your tool to make reliable, robust and scalable APIs. We think that to extend your code cleanly, it might be interesting to install eslint and prettier by default with your own configuration

**Comment by tupe12334** [comment]
Starting to work on it!!!

**Comment by shikhar13012001** [comment]
Can I work on this please?

**Comment by yuval-hazaz** [comment]
will be implemented as a plugin

**Comment by overbit** [comment]
A new plugin will be developed as part of https://github.com/amplication/amplication/issues/6605
