### ISSUE TITLE
Generated App: Add User object to the request in REST API endpoints

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#1723]
**Is your feature request related to a problem? Please describe.**
The User object is available using the @UserData decorators in GraphQL. Also, it is available as part of the request object. 
This is not the current case with REST API - but it should. 

**Describe the solution you'd like**
Make sure the User object is available on the request, also consider adding a @userData decorator for REST API.

based on the use case described in #1722

**Comment by mshidlov** [comment]
merged to release `0.11.3`
