### ISSUE TITLE
Data Service Generator: Auto generate test for endpoints

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1779]
auto-generate test for all endpoint by template and for the special ones like health and auth

**Comment by mshidlov** [comment]
@tupe12334 please elaborate and add code locations to help continbuters.

**Comment by tupe12334** [comment]
@jainpawan21 We have some tests in the generated controllers, we can add them to the resolvers too.
And add tests for the health and auth controllers and the auth resolver

**Comment by jainpawan21** [comment]
Hi @tupe12334, Can you please route me to correct file?
It will be very helpful
