### ISSUE TITLE
Server: Connected Repository Default README.md 

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#1792]
Creare default amplication README.md file for connected GitHub repositories.

When users create a new GitHub repository through Amplication, repositories should be created with Amplication default README.md file.

**Comment by yuval-hazaz** [comment]
@mshidlov is this still relevant?

**Comment by mshidlov** [comment]
@yuval-hazaz today when a new repository is created from amplication we create a readme file that contains only the app name.

We should put in the readme some relevant content like how to run the server/client, docker, and docker-compose, folders in the repo, etc.

**Comment by mshidlov** [comment]
this can be a documentation for @MoFoGo

**Comment by jainpawan21** [comment]
Hi @MoFoGo, Can you please share contents that should be in README.md file of generated repo?
I would like to work on this. 
@mshidlov Can you please assign this to me?

**Comment by mshidlov** [comment]
@jainpawan21 sure once we will decide on content for it you can start working on it

**Comment by yuval-hazaz** [comment]
@jainpawan21 I think we can use the content from this doc (starting from step 2)
https://docs.amplication.com/docs/getting-started/dev-env
