### ISSUE TITLE
Update GitHub Actions CI\CD for Release Methodology 

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#1793]
- [x] #1989
- [x] #1990
- [x] #1991
- [x] #1992
- [ ] #1993
- [x] #1994
- [x] #1995
- [x] #1996
- [x] #1997
- [ ] Rebase release branch
- [x] #2078

**Comment by yuval-hazaz** [comment]
@mshidlov can you please update this one and close it if the tasks are completed

**Comment by arielweinberger** [comment]
Completed, we will tackle #1993 separately
