### ISSUE TITLE
Working with release branch

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1800]
update the contribute file to talk about the working with release branches

**Comment by yuval-hazaz** [comment]
@tupe12334 are you planning to take this one? should you send it to @MoFoGo ?

**Comment by tupe12334** [comment]
@yuval-hazaz please send it to @MoFoGo

**Comment by yuval-hazaz** [comment]
@tupe12334  if there is a need, @MoFoGo will need the content from you anyway
