### ISSUE TITLE
Amplication Server - Entity Service Coverage 

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#1808]
Improve entity service tests coverage.
add new tests and improve existing ones.

Service path: `./packages/amplication-server/src/core/entity/entity.service.ts`
Tests path: `./packages/amplication-server/src/core/entity/entity.service.spec.ts`

We use `jest` for tests and `jest-mock-extended` for mocking.

**Comment by g-traub** [comment]
Can I work on this issue ? :grinning:

**Comment by mshidlov** [comment]
Sure 👍 I'm assigning you
