### ISSUE TITLE
Amplication Server - Entity Resolver Coverage 

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#1809]
Improve entity resolver tests coverage.
add new tests and improve existing ones.

Service path: `./packages/amplication-server/src/core/entity/entity.resolver.ts`
Tests path: `./packages/amplication-server/src/core/entity/entity.resolver.spec.ts`

We use jest for tests and jest-mock-extended for mocking.

**Comment by souravjain540** [comment]
> Can it be closed if linked PR is solving the this?

@mshidlov @tupe12334
