### ISSUE TITLE
Amplication CLI - Support AuthProvider `JWT` 

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#1811]
In amplication-server version `0.10.0`, JWT AuthProvider was added.

Add to the CLI `auth` flag to choose between the different providers.

The default provider is the JWT provider.

JWT related issue: #1714

**Comment by nguyenhung15913** [comment]
Hi, is this issue still available to grab ?

**Comment by devblin** [comment]
Hey @souravjain540, can I work on this issue ?.

**Comment by souravjain540** [comment]
> Hey @souravjain540, can I work on this issue ?.

Hey @devblin 

As far as I can see, you've contributed to Amplication earlier as well?

This issue is assigned for DIFT campaign which is for First time contributions to Amplication.

**Comment by devblin** [comment]
Oh ok, got it 👍🏽

**Comment by souravjain540** [comment]
> Oh ok, got it 👍🏽 

If you've any friend who can contribute, do tell them :)

**Comment by kinb98** [comment]
Hi can I work on this ?

**Comment by souravjain540** [comment]
> Hi can I work on this ?

Hello @kinb98 am assigning you this issue! 

Have a good time working on it. Limited Edition Amplication SWAG are waiting for your PR 😉

If you need any help just reply to me. We are more than happy to help you in your first PR to Amplication 💜

**Comment by souravjain540** [comment]
Hi @kinb98 are you working on it?

**Comment by souravjain540** [comment]
![Screenshot 2022-06-07 at 12 07 32 PM](https://user-images.githubusercontent.com/53312820/172312424-24b2777e-958a-42b2-b655-f8a3162201af.png)
