### ISSUE TITLE
Amplication Server - Auth Guard Coverage

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#1812]
Improve auth guard tests coverage.
add new tests and improve existing ones.

Auth guard path: `./packages/amplication-server/src/guards/gql-auth.guard.ts`
Auth guard tests path: `./packages/amplication-server/src/guards/gql-auth.guard.spec.ts`

We use `jest` for tests and `jest-mock-extended` for mocking.

**Comment by narayand16** [comment]
@mshidlov Can you assign this issue to me ?

**Comment by yuval-hazaz** [comment]
@mshidlov is this still relevant or can we close this?
