### ISSUE TITLE
Main docker file

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1833]
In the main docker file in the root folder there is a command `npm run bootstrap -- -- --production --loglevel=silent --scope @amplication/server --scope @amplication/client --include-dependencies` 
this command stract in a wrong order, the flags `--scope @amplication/server --scope @amplication/client --include-dependencies` entering the npm and the flags ` --production --loglevel=silent` enter the lerna.
the command needs to be like this:
`npm run bootstrap -- --scope @amplication/server --scope @amplication/client --include-dependencies -- --production --loglevel=silent`

**Comment by mshidlov** [comment]
merged by @yuval-hazaz pull request #1834
