### ISSUE TITLE
Data Service Generator: console log in test

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1850]
in the file `amplication/packages/amplication-data-service-generator/src/server/resource/dto/graphql/order-by-input/order-by-input.spec.ts` there is a  console.log(print(createInput).code);

its need to be remove

**Comment by SachinHatikankar100** [comment]
Hi @mshidlov got below message while pushing the changes.
![image](https://user-images.githubusercontent.com/12583179/139491249-c4a076dc-8ab8-465e-be3d-2972821bd1b6.png)

**Comment by SachinHatikankar100** [comment]
Hi @mshidlov I have submitted a PR. Please review
