### ISSUE TITLE
Data Service Generator: add type to swaggerSetupOptions

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1853]
In the file `swagger.template.ts` the swaggerSetupOptions const missing the type declaration `SwaggerCustomOptions`

**Comment by mshidlov** [comment]
Hey @tupe12334 thank you for reporting that issue.
Can you please provide context for this. 

please share file path

**Comment by yuval-hazaz** [comment]
@tupe12334 please add details that will help contributors to implement this change

**Comment by AlexVCS** [comment]
Hi @tupe12334 I went to that file and added SwaggerCustomOptions but what did you want inside of that? Thanks

**Comment by ahlavorato** [comment]
If you could give more detail about this issue, I would like to work on it =)

**Comment by tupe12334** [comment]
Hi @ahlavorato You just need to add the SwaggerCustomOptions typescript type from the package `@nestjs/swagger` in the line https://github.com/amplication/amplication/blob/a76977dd1fcb1c82517b7c4614408396edc56f4f/packages/amplication-data-service-generator/src/server/swagger/swagger.template.ts#L16

**Comment by Smartmind12** [comment]
@tupe12334 Can i work on this issue ??

**Comment by alinehaxkar** [comment]
@tupe12334  perfect i'm doing it =)

**Comment by GreenMachine01** [comment]
@Smartmind12 @alinehaxkar @ahlavorato Thank you for wanting to contribute.
As @alinehaxkar already submitted a PR I will assign the item to him.

We are working on a more structured protocol for community task assignments

**Comment by ahlavorato** [comment]
I already submitted a PR, sorry for the delay.
