### ISSUE TITLE
🚀 [Authentication]: Include 3rd-party auth provider as part of autogenerated code

### ISSUE THREAD

**Issue by Mingyang-Li** [amplication/amplication#1858]
### 🔖 Feature description

Instead of only including passport.js, giving us the option to choose a 3rd party auth provider SDK as an alternative to passport.js would be hugely beneficial.

### 🎤 Pitch

Most development teams do not implement authentication & authorisation themselves. Instead, they use 3rd party auth services such as Auth0, Firebase, AWS Cognito or Azure IAM to save time and safeguard security, etc. It would be helpful to add the popular auth services as options for Amplication users when generating new template for ourselves.

### ✌️ Solution

When generating new template using the CLI, ideally we would be presented with options for choose our preferred authentication provider:

1. Auth0
2. Firebase
3. AWS Cognito
4. Azure IAM
5. etc

### 🔄️ Alternative

For time-being, the team at Amplication can try implement to only provide Auth0 as an alternative, as Auth0 is the most widely-used auth service and & it's easier to configure

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by yuval-hazaz** [comment]
this will be supported using the plugins architecture
