### ISSUE TITLE
🐛 Bug Report: naming convention in generated package.jsons names

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1859]
### 📜 Description

in the generated package.json in the server and the admin UI the naming convention is {name}-server instead of @{name}/server or @{name}/admin

### 👟 Reproduction steps

generate a new app

### 👍 Expected behavior

@{name}/server

### 👎 Actual Behavior

{name}-server

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by souravjain540** [comment]
fixes (gen app)
 naming convention fixed from {name}-server to @{name}-server in the package.json?

**Comment by tupe12334** [comment]
@souravjain540 @{name}/server*
