### ISSUE TITLE
🐛 Bug Report: Dockerfile build fails

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#1861]
### 📜 Description

Dockerfile build fails **sometimes** with a timeout error

#15 764.1 npm ERR! code ERR_SOCKET_TIMEOUT
#15 764.1 npm ERR! errno ERR_SOCKET_TIMEOUT
#15 764.1 npm ERR! request to https://registry.npmjs.org/workbox-google-analytics failed, reason: Socket timeout

Node version `14.x`
npm version `7.3`

### 👟 Reproduction steps

Docker build .

### 👍 Expected behavior

Docker build should always run from start to complete.

### 👎 Actual Behavior

run  sometimes

### 💻 Device

Desktop

### 💻 Operating system

Linux

### 🌍 Browser

Something Else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by yuval-hazaz** [comment]
@mshidlov is this still relevant? can we close it?
