### ISSUE TITLE
🐛 Bug Report: many dev dependencies in dependencies

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1865]
### 📜 Description

moving many dev dependencies to the dependencies section

### 👟 Reproduction steps

not relevent

### 👍 Expected behavior

not relevent

### 👎 Actual Behavior

not relevent

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by mshidlov** [comment]
duplicate move conversation to #1807
