### ISSUE TITLE
🐛 Bug Report: Exiting "Create new workspace" shows error

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#1868]
### 📜 Description

when clicking on the X button in order to exit "create new workspace" popup, the input behaving like its an error and not exit smooth.

<img width="479" alt="Screen Shot 2021-11-01 at 9 47 48" src="https://user-images.githubusercontent.com/8940907/139639901-c8b70822-af0f-4978-a268-1f63781a350e.png">
### 👟 Reproduction steps

click new workspace > than click the X button > before it quits it shows an error in the input and quits.

### 👍 Expected behavior

should be exit without any error behavior.

### 👎 Actual Behavior

should be exit the pop-up without any behavior that doesn't require the action that requested.

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by yuval-hazaz** [comment]
@souravjain540 please make sure this is still open, and if it is you may implement the same fix you did in the other issue

**Comment by Shubhdeep12** [comment]
@souravjain540 can I work on this issue

**Comment by souravjain540** [comment]
Sure @Shubhdeep12!

assigned, join our discord for any help :)

**Comment by Shubhdeep12** [comment]
Sure,
thanks.
