### ISSUE TITLE
🚀 Feature: git create repo name indication

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1879]
### 🔖 Feature description

the UI will indicate if the name of the repo is available or not in the name text field
in the git create branch:

<img width="1279" alt="Screen Shot 2021-11-04 at 14 34 08" src="https://user-images.githubusercontent.com/61761153/140314241-8d83728d-92a1-4742-9006-2e75c82a153f.png">

<img width="1279" alt="Screen Shot 2021-11-04 at 14 34 25" src="https://user-images.githubusercontent.com/61761153/140314253-e646d0b2-5c85-4312-9bdf-d830e3e8b0b3.png">

Wanted:
<img width="1279" alt="Screen Shot 2021-11-04 at 14 34 25" src="https://user-images.githubusercontent.com/61761153/140314516-8d90c1ba-a6a5-40af-82a1-e7c9dabafa04.png">

**Comment by jainpawan21** [comment]
Hi @tupe If this is not resolved and still relevant,
Can you please assign this to me?

**Comment by tupe12334** [comment]
@jainpawan21 Yes, but @alexbass86 do you want to create a valid UI?

**Comment by alexbass86** [comment]
> @jainpawan21 Yes, but @alexbass86 do you want to create a valid UI?

Yes please, lets do quick zoom meeting

**Comment by yuval-hazaz** [comment]
I moved this issue to "staled" 
please reply soon if you think we should be moving forward with that, or can we close the issue

**Comment by yuval-hazaz** [comment]
I moved this issue to "staled" 
please reply soon if you think we should be moving forward with that, or can we close the issue

**Comment by alexbass86** [comment]
Great idea. Let's create a new UI for this.
I will create something soon and post it here for review.
