### ISSUE TITLE
🐛 Bug Report: anchor version

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1880]
### 📜 Description

anchor all the package.json versions

### 👟 Reproduction steps

no relevant

### 👍 Expected behavior

no relevant

### 👎 Actual Behavior

no relevant

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by mshidlov** [comment]
Duplicate with #1807
