### ISSUE TITLE
🐛 Bug Report: linter dont block empty file

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1891]
### 📜 Description

the linter allow me to upload empty file to the repo

### 👟 Reproduction steps

when i upload to the repo empty file its let me

### 👍 Expected behavior

show a linter error

### 👎 Actual Behavior

the linter dont send me any error

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by jainpawan21** [comment]
Is this still relevant and needs to work on?

**Comment by tupe12334** [comment]
@jainpawan21 Yes, the linter needs to block empty files.

**Comment by jainpawan21** [comment]
@tupe12334  Please share steps to reproduce. I am a bit confused 😅

**Comment by tupe12334** [comment]
@jainpawan21  Try to add a new empty file to the dsg and run the linter script
