### ISSUE TITLE
🐛 Bug Report: using of apollo-server-express in generated app

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1896]
### 📜 Description

In the generated app we use the apollo-server-express package for the gql\`query...\` instead of the graphql-tag package,
apollo-server-express implement graphql-tag in the back stage

### 👟 Reproduction steps

no relevent

### 👍 Expected behavior

using the graphql-tag package

### 👎 Actual Behavior

using apollo-server-express package

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by mshidlov** [comment]
@tupe12334 thank you for reporting this issue.
If you can please share why do you think this is a bug?
Does `apollo-server-express` used only for using `graphql-tag` functionality? 
Does `apollo-server-express` extend or simplify `graphql-tag` functionality?

**Comment by yuval-hazaz** [comment]
from what I see, we only use `ApolloError` from `apollo-server-express` and we are not using `gql` - so I am not sure we can switch to `grqphql-tag`

I think we should anyway keep using `apollo-server-express` as we may need it for future features likes generating tests to the resolvers 

I recommend to close this issue
