### ISSUE TITLE
🏆 Node.TLV: Duck tamgochi 

### ISSUE THREAD

**Issue by amirbh1106** [amplication/amplication#1906]
### 💡 My idea is

Duck tamgochi that you can talk to that lives inside the camputer 

### ✅ The idea is awesome because

It's saves rubber

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
