### ISSUE TITLE
🏆 Node.TLV: Leveraging on design patterns and reuse a lot of code

### ISSUE THREAD

**Issue by carlomigueldy** [amplication/amplication#1915]
### 💡 My idea is

Leveraging on design patterns to get things done easier, following the best practices that have emerged with-in the team or oneself, refactoring code where necessary and at least aim to refactor everyday, leveraging on test-driven development and write lots and lots of tests. And finally reuse somebody's code, reuse somebody's code, reuse one's code, reuse and reuse as much as possible.

### ✅ The idea is awesome because

This is just being clever to get things done in a smart-ish-lazy way.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀

We appreciate your idea to make backend developers life easier and encourage you to contribute in the future as well. 💜
