### ISSUE TITLE
🏆 Node.TLV:  open source Sequel ORM

### ISSUE THREAD

**Issue by Gamedoper** [amplication/amplication#1917]
### 💡 My idea is

My Idea is .. In ruby we have a open source Sequel ORM by Jeremy Evans if we have something like this in Node Js ... backend would become more easier ....! and Time saving

### ✅ The idea is awesome because

Becaue i work on Ruby So i shared this ...

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀

We appreciate your idea to make backend developers life easier and encourage you to contribute in the future as well. 💜
