### ISSUE TITLE
🏆 Node.TLV: [Ergonomic table and chair]

### ISSUE THREAD

**Issue by niraj-kumar-r** [amplication/amplication#1919]
### 💡 My idea is

Invest in a good ergonomic table and chair, and just make your whole setup, more comfortable for your body, so that your future self has no problems down the road.

### ✅ The idea is awesome because

Because I am a broke student, and I don't have a table and or chair, and I will have to sit for online classes of IIT Tirupati starting Dec 2021. 

I could be considered fit by general standards but it is still hard on my body to sit comfortably for so long without lumbar support.

Believe me you realise the importance of good ergonomics, very fast, when you don't have even basic ergonomics.

[Also, I could really use that MacBook pro right now]

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀

We appreciate your idea to make backend developers life easier and encourage you to contribute in the future as well. 💜
