### ISSUE TITLE
🏆 Node.TLV: Settings change in real time

### ISSUE THREAD

**Issue by AvivBenShoham** [amplication/amplication#1921]
### 💡 My idea is

Aren't you tired of updating production service due to env changes? Implement websockets between pods and clients and add an oplog listener, and add dynamic real time changes to your app!

### ✅ The idea is awesome because

dynamic real time changes to your app, no need of updating production due to env changes

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
