### ISSUE TITLE
🏆 Node.TLV: [Pro tips for backend developer]

### ISSUE THREAD

**Issue by Nishi-16-K** [amplication/amplication#1925]
### 💡 My idea is

•Don't trust your server

•When stuck, write program on paper.

•Use inheritance. 

• Try to use simpler programming language, complex ones increase cognitive load on brain. 

•Debug your code with "print statements."

• Make mistakes, ask questions, get rapid feedback.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
