### ISSUE TITLE
🏆 Node.TLV: Add monitoring - generate metrics and dashboards.

### ISSUE THREAD

**Issue by orsegal9** [amplication/amplication#1926]
### 💡 My idea is

Add monitoring - generate metrics and dashboards.

### ✅ The idea is awesome because

Performance is super important, especially when relying on generated core modules.

**Comment by Adammagnezy** [comment]
Sagi the king👑

**Comment by ofekdeitch-fiverr** [comment]
Yallaaaaaaa

**Comment by ItamarPeeri** [comment]
Best idea ever ever!!

**Comment by mikenussbaumer** [comment]
This is awesome!

**Comment by gosyseng** [comment]
Great Idea ! let's do it.

**Comment by 7mode** [comment]
so needed!!!
Great idea!! 👑

**Comment by yoavabadi-fiverr** [comment]
Go for it!!! 🚀

**Comment by A-Asf** [comment]
+1
