### ISSUE TITLE
🏆 Node.TLV: multiple open source templates/boilerplates

### ISSUE THREAD

**Issue by Lowkey98** [amplication/amplication#1928]
### 💡 My idea is

My idea is to have a website that has multiple open source templates/boilerplates running on the web on separated visualized databases. Where you can test the code and it features with ease before checking the code.

### ✅ The idea is awesome because

This idea is beneficial for beginner backend developers who aren't comfortable enough with big portion projects or intimidated by the process it takes to test and understand what features a template gives them.
This idea is awesome because these backend developers will be motivated on testing what the feature does and know that it is what they need for their project. Instead of looking for different codes and not knowing if that is what they looking for.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
