### ISSUE TITLE
🏆 Node.TLV:  concepts of a backend architecture

### ISSUE THREAD

**Issue by anurag1302** [amplication/amplication#1931]
### 💡 My idea is

1. Understand the security concepts of a backend architecture, implement them carefully.
2. Read backend related research papers (like https://oauth.net/specs/) instead of blindly copying stuffs from the internet. 
3. Understand how queues work, how messaging works.
4. Understand the HTTP status codes, return them wisely. Ex: difference between 401 & 403.
5. Understand the HTTP verbs, use them judiciously.
6. Lastly, document for other people's learning & feedback

### ✅ The idea is awesome because

The above list focuses on basics and creating a strong foundation with a learning acumen. Once the basics are sorted, the dev will himself/herself devise new techniques to stay relevant, create awesome backend architectures and excel.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
