### ISSUE TITLE
🏆 Node.TLV: autoTDD

### ISSUE THREAD

**Issue by orstav** [amplication/amplication#1932]
### 💡 My idea is

The developer writes his given when then test name and the marvelous AI generates test that fails for the new feature 

You as a developer just need to fix the test and refactor.

### ✅ The idea is awesome because

The idea is awesome because TDD is awesome and AI is also awsome

**Comment by Ariellllll123** [comment]
You are the best capara

**Comment by Ofekiki1212** [comment]
יפה מאוד

**Comment by danielstrrr** [comment]
MY MAN!

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
