### ISSUE TITLE
🏆 Node.TLV: [Best Practices for Backend developer

### ISSUE THREAD

**Issue by SampurnaC** [amplication/amplication#1934]
### 💡 My idea is

Top 7 tips that makes backend developers life easier :  
1. Add test cases to your codebase : Add test cases and you aim for higher code coverage ~ 80% . 
2. Use  automation: Work on automating things. You can use background jobs to not slow down your applications . 
3. Query optimisation : check how long it takes to perform certain queries and look if you can optimize it . 
4. Read blog posts : you will learn more if you read constantly .
5. Add documentation: Add documentation to your codebase, this will help you and your team to understand the codebase.
6. Use bug tracking tools like bugsnag: Bugsnag is a great tool for bug tracking. you can easily see bugs in the bugsnag dashboard and take action immediately.
7. Take feedback in a good way: constant improvement and taking feedback from others plays a vital role.

### ✅ The idea is awesome because

I have learned all these best cases from my 5 years of experience as a backend developer . And I am sure it will be a beneficial for other developers too .

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
