### ISSUE TITLE
🏆 Node.TLV: Tips for becoming a good backend developer

### ISSUE THREAD

**Issue by demonicirfan** [amplication/amplication#1935]
### 💡 My idea is

# Tips for becoming a good backend developer.
- Be Proactive and scheduled.
- Strong core skills.
- Understanding of Datastructures and Algorithms.
- Always develop with CI/CD in mind.

### ✅ The idea is awesome because

These are some of the things which helped me become a better at backend devlopment

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
