### ISSUE TITLE
🏆 Node.TLV: Inherit all model from a single base

### ISSUE THREAD

**Issue by Hagai-Arzi** [amplication/amplication#1936]
### 💡 My idea is

Inherit all model from a single base one, and supply Tha basic methods like create update and so on with a single file.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
