### ISSUE TITLE
🏆 Node.TLV: Add best practice for each code snippet or commonly used pattern

### ISSUE THREAD

**Issue by ntedgi** [amplication/amplication#1939]
### 💡 My idea is

Add best practice for each code snippet or commonly used pattern

### ✅ The idea is awesome because

We all know how to use the tuturial example , but not fermiler on how to fo it in real world app
For example connect to mysql with connection or with clusterPOol

**Comment by yuval-hazaz** [comment]
this should be implemented as plugins in the coming plugin system
I will close this issue
