### ISSUE TITLE
🏆 Node.TLV: generate micro service skeleton

### ISSUE THREAD

**Issue by InnaTrava** [amplication/amplication#1942]
### 💡 My idea is

Generate micro service skeleton with code and infra based on open api and/or simple recources list

### ✅ The idea is awesome because

Developers can have a fast and simple way to start the development . They will have ready placeholders for all the building blocks. They will save time and will be alligned with best practices.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
