### ISSUE TITLE
🏆 Node.TLV: Read docs and reuse the code

### ISSUE THREAD

**Issue by Satish-baradiya** [amplication/amplication#1946]
### 💡 My idea is

1). Read docs.
2). Reuse the Code.

### ✅ The idea is awesome because

One used read docs because reading docs can solve most of the errors or problems and one can understand any concept more clearly using docs.
Reusing code can save time.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
