### ISSUE TITLE
🏆 Node.TLV: Watch model files, and auto generate all other stuff, like db schemes and swagger

### ISSUE THREAD

**Issue by yantrab** [amplication/amplication#1948]
### 💡 My idea is

It is useless to modify models in the interface,  with typescript compiler you can do it easily.

I actually start working on npm package that do that in real time, see https://www.npmjs.com/package/strongly

### ✅ The idea is awesome because

It is avoid the necessary to work with the interface for minor changes.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
