### ISSUE TITLE
🏆 Node.TLV: Automate your initial codes

### ISSUE THREAD

**Issue by sunilpanda13** [amplication/amplication#1950]
### 💡 My idea is

Automate your initial codes which are used in every project, also make snippets for your regularly used npm packages.  

### ✅ The idea is awesome because

Because of automation devs can save time in the setup of their projects and writing initial codes for their npm packages. They can use that time in writing complex logic and algorithms.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
