### ISSUE TITLE
🏆 Node.TLV: Support production debugging and code replacement

### ISSUE THREAD

**Issue by roeezolantz** [amplication/amplication#1951]
### 💡 My idea is

Add support to remote debug the code in production and even replace a piece of code with another one, directly on production (or lets say, dev..), maybe with safety flags or any way that can make this process a bit safer yet optional.

### ✅ The idea is awesome because

This feature is missing in most of the modern stacks and the community shouts that this availability is needed, even just for edge cases - but yet needed.

**Comment by myaffe-quotient** [comment]
I really like this Idea !
