### ISSUE TITLE
🏆 Node.TLV: [Backend Developer Productivity Tips]

### ISSUE THREAD

**Issue by thegeekyb0y** [amplication/amplication#1952]
### 💡 Productivity Tips 

I am an experienced advanced level python programmer, here I gave the important productivity tips for developers.

**1. More Automation**
_Much repition is sometimes boring , Hence automation is needed to save your time. Also , we have Python , used for automation, start doing it from now :)_

**2. Project Based Learning**
_When we enter the world of programming , project based learning is the best for your growth, as much projects , the more the growth._

**3. Consistency**
_Consistency is the key , as everyone says it , I too say the same , do some programming daily , Grow 1% or more daily to become a good programmer._

### ✅ The idea is awesome because

Past year , during the lockdown , I started learning Backend specially python , I completed 100 days of Code and I am an advanced coder in Python. This consistency and project based learning really worked for me. Also throughout this journey, I learnt to automate harder tasks in easy and clean code. You should surely give it a try ;)

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
