### ISSUE TITLE
🏆 Node.TLV: TDD

### ISSUE THREAD

**Issue by nazarenads** [amplication/amplication#1953]
### 💡 My idea is

Use TDD to ensure that your tests are not biased in favour of your implementation and to improve your test coverage

### ✅ The idea is awesome because

Since I've learned about TDD I've been using it for all the code that I have to write. I think many programmers could benefit from using it because it could help them reduce significantly the amount of bugs they have and also give them a better understanding of the code and tests they're writing.

**Comment by NicoAbbruzzese** [comment]
Great idea, wish i'd come up with that one lol! 😁🚀

**Comment by mosaic-melisa-cerda** [comment]
Awesome!!

**Comment by mosaic-martin-carlin** [comment]
Totally agree with your pov!

**Comment by Antoromi** [comment]
Love it!

**Comment by AdrianRamiro** [comment]
Great idea!

**Comment by sashalda** [comment]
Great idea ❤️

**Comment by marumosquera** [comment]
Great idea!!

**Comment by lonmp** [comment]
It is an awesome idea!

**Comment by inimueller** [comment]
🚀🚀

**Comment by ncastrohub** [comment]
Embrace TDD :red_circle: :white_check_mark: :wrench: :repeat:

**Comment by blindMoe** [comment]
Huge fan of TDD!

**Comment by daviduehlinger** [comment]
Excellent !!!!

**Comment by ChineseStuff** [comment]
Yeeeah! with TDD we will go back to the stratosphere and from there we can choose the place where we want to go <3
