### ISSUE TITLE
🏆 Node.TLV: Pro Tips

### ISSUE THREAD

**Issue by Mubarik-Khan** [amplication/amplication#1954]
### 💡 My idea is

Try to learn new technology 
Make notes for longer memory
Share your learning with others 
Code daily
Take feedback of others
Spent time with family for afresh start

And
Really need a laptop not macbook which you can provide😊

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
