### ISSUE TITLE
How your backend life should start

### ISSUE THREAD

**Issue by mrABR** [amplication/amplication#1955]
### 💡 My idea is

Ideas that make life easier:
. Get to know your tools
. If you spend an amount of time doing something, script it
. Follow people and frameworks around your tech stack. It is a constant learning process
. Don't over do it, keep it simple
. Focus on yourself and your mental health

### ✅ The idea is awesome because

. Get to know your tools
You should know the power you've got, what you've harvested and what you can gain. This will allow you to explore to the fullest what you can do.
Ps: the only limitation is the one you set for yourself

. If you spend an amount of time doing something, script it
Optimization should be your middle name, time consumption should be your arch enemy.

. Follow people and frameworks around your tech stack. It is a constant learning process
Don't allow yourself to be left behind. Use your socials to help you keep up to date with new trends or new techniques, or even share your ideas with others. We devs wouldn't make it without each other sharing knowledge.

. Don't over do it, keep it simple
Don't complicate that documentation, that feature or those comments. Your future self will appreciate it. It doesn't have to be complex to be a good system.

. Focus on yourself and your mental health
Take your time, it's never too late for anything. Ask that girl/boy out, work out, drive safe, party safe, watch that anime series, do whatever you want in your free time, but do something. Don't exhaust yourself, it's not worth it. Your future self will thank you

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
