### ISSUE TITLE
Ability to connect to monorepos like nx

### ISSUE THREAD

**Issue by YonatanKra** [amplication/amplication#1956]
### 💡 My idea is

Currently it is possible to build the app on a standalone repo. If I want to manage multiple apps in a monorepo it is not possible. This feature should enable that. Integration with Nx is highly valuable.

**Comment by Tuhaj** [comment]
Good idea!

**Comment by yuval-hazaz** [comment]
candidate to be implemented as a plugin

**Comment by yuval-hazaz** [comment]
already available
