### ISSUE TITLE
🏆 Node.TLV: [Play Code Golf]

### ISSUE THREAD

**Issue by Kayrah87** [amplication/amplication#1958]
### 💡 My idea is

spend 10% of your time, that's 1 day every 2 weeks, playing code golf! Yes, that's right, play with the code you've already written. Instead of writing new code for new things, spend the time reviewing and revisiting the code that you've already committed to try and make it leaner, faster, smarter!

### ✅ The idea is awesome because

Every time you review your own code and try and shave those milliseconds off code execution you're sharpening your muscle memory to be able to code that way in the first place!

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
