### ISSUE TITLE
⭐️ Plugin: MongoDB

### ISSUE THREAD

**Issue by rachgreen** [amplication/amplication#1959]
### 💡 My idea is

Add suport for MongoDB. 

### ✅ The idea is awesome because

I like no sql db

**Comment by zaitsev1** [comment]
https://www.prisma.io/docs/concepts/database-connectors/mongodb

**Comment by yuval-hazaz** [comment]
candidate to be implemented as a plugin

**Comment by GreenMachine01** [comment]
@yuval-hazaz @arielweinberger 
What are the client-side implications of supporting this plugin? 
Do we need to handle the service configuration differently if the Mongo plugin is activated on it?

**Comment by abrl91** [comment]
I review the plugin https://github.com/amplication/plugins/pull/25
