### ISSUE TITLE
Anton🏆 Node.TLV: [Use Kotlin best practices in JS]

### ISSUE THREAD

**Issue by rokhlin** [amplication/amplication#1960]
### 💡 My idea is

Use Kotlin best-practices in JS.

### ✅ The idea is awesome because

Unification

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
