### ISSUE TITLE
⭐️ Plugin: Redis integration - [ cache solution ]

### ISSUE THREAD

**Issue by ran-kalir-jeeng** [amplication/amplication#1962]
As a user, I want to be able to use a Redis plugin on my service, so that I can cache data and improve the performance of my application.

**Acceptance Criteria:**

1. The Redis plugin should be available in the plugin marketplace of Amplication.
2. Users should be able to easily add the Redis plugin to their services.
3. The Redis plugin should be configurable so that users can customize it based on their needs.
4. The Redis plugin should be compatible with all types of services supported by Amplication.
5. Users should be able to easily remove the Redis plugin from their services if they no longer need it.
6. Documentation should be provided to guide users on how to use and configure the Redis plugin.

**Icon:**
![Redis](https://github.com/amplication/amplication/assets/112330500/8467ae1d-d193-434f-90e1-fa0d303dc504)

**Comment by yuval-hazaz** [comment]
candidate to be implemented as a plugin

**Comment by overbit** [comment]
@d-sonuga

**Comment by overbit** [comment]
## Tested successfully:

✅ 
![Image](https://github.com/amplication/amplication/assets/2861984/b21aec6b-bca8-484d-8234-e0dbb5221df2)
