### ISSUE TITLE
🏆 Node.TLV: Be a pessimist, you don't need all the features you think

### ISSUE THREAD

**Issue by sertxudev** [amplication/amplication#1965]
### 💡 My idea is

Be a pessimist, only implement the features you actually need.

### ✅ The idea is awesome because

This will avoid a lot of headaches and you will be able to focus only on the features you actually need.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
