### ISSUE TITLE
🏆 Node.TLV: Logging tool.  Please read.

### ISSUE THREAD

**Issue by shaurya-blip** [amplication/amplication#1971]
### 💡 My idea is

An online logger. The server sends a post request to a link with a made-up error code (later explained*) in it, and a message. 
When we go to the GUI it shows a list of all the error codes sent, at what time, for what reason, and the output of the program which caused the error. You can sort by date, time, etc. Anywhere. Also sends email and notification to the people who have subscribed to the list. Also what about different lists for different programs? Like monday.com but except for items in them, there is a list of logs. 

* The made-up error code will be made by the user in the GUI. Like 4444(made-up) | Reason: Program failed to send SMS.

This will really help me, and all the other backend developers out there.

That's it, Thanks for reading.
SblipDev

### ✅ The idea is awesome because

This tool will really help me, Thanks for reading.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
