### ISSUE TITLE
🏆 Node.TLV: [Automate Unit Testing Code]

### ISSUE THREAD

**Issue by subba16** [amplication/amplication#1976]
### 💡 My idea is

Automate Unit Testing Code for all basic CRUD

### ✅ The idea is awesome because

This saves time and focus on more on Business logic.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
