### ISSUE TITLE
🏆 Node.TLV: [model scanner]

### ISSUE THREAD

**Issue by Chipanzee** [amplication/amplication#1977]
### 💡 My idea is

Add existing client-side models scanner for API generation.

### ✅ The idea is awesome because

In case that you already have a client-side, you can skip the typing action for model initiation.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
