### ISSUE TITLE
🏆 Node.TLV: plugin to check nulls

### ISSUE THREAD

**Issue by yubrajpokharel** [amplication/amplication#1978]
### 💡 My idea is

A plugin to check nulls.

### ✅ The idea is awesome because

Lots of programs are crashed just because sometime we miss null checks in our code which may cause issues

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
