### ISSUE TITLE
🏆 Node.TLV: optimised endpoints via ML or DL

### ISSUE THREAD

**Issue by ashish-ad** [amplication/amplication#1980]
### 💡 My idea is

Developing an ML or DL for acquiring endpoints of a website without reading the API doc of the website like twitter and suggesting optimised endpoints via ML or DL(extra feature).

### ✅ The idea is awesome because

This is a great idea since I have not experienced suggest tools in devs community.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
