### ISSUE TITLE
🏆 Node.TLV: One programming language with many compiling ways

### ISSUE THREAD

**Issue by TheTelematic** [amplication/amplication#1981]
### 💡 My idea is

Implement a universal programming language, with this one we would have one single source code and many different ways of compiling depending on the target platform/language (of the consumer app).

### ✅ The idea is awesome because

This would be very interesting to implement libraries with one single source code and get different compiled libraries depending on the final app programming language or the platform where it's executed.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
