### ISSUE TITLE
🏆 Node.TLV: support canary deployment out of the box.

### ISSUE THREAD

**Issue by elrankalili** [amplication/amplication#1985]
### 💡 My idea is

support canary deployment out of the box.
i want to deploy my new version with X% routed to new version and (1-X)% routed to old in order to make an A-B test and monitor my ERROR logs with newer version so i can know the new one is stable.

### ✅ The idea is awesome because

cause today only 4 biggest (GMAF) companies work with canary deployment

**Comment by yuval-hazaz** [comment]
@elrankalili  although this is a great idea, we were focusing on providing features on the backend, while the users should be able to connect the code base to any existing pipelines for deployments. 
I will close this issue.
Thank you
