### ISSUE TITLE
🏆 Node.TLV: Be a Good Developer

### ISSUE THREAD

**Issue by pratik-7span** [amplication/amplication#2001]
### 💡 My idea is

Here are the ideas to make backend developer's life easier:

1. Always document your code 
2. Do not trust the server ever
3. Communicate decisions
4. Estimate honestly
5. Give a thorough description of your PRs

### ✅ The idea is awesome because

It is super necessary thing to become a good developer.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
