### ISSUE TITLE
🏆 Node.TLV: [cascading dependent dropdowns

### ISSUE THREAD

**Issue by paulica40** [amplication/amplication#2002]
### 💡 My idea is

it woul be nice to generate dependent dropdowns from api like country, state, city or companies, line of business,area, etc

### ✅ The idea is awesome because

some projects need this and it is easier to to understand the references from one table to another

**Comment by yuval-hazaz** [comment]
@paulica40 as this is a great idea, we were focusing on providing features on the backend, while the users should be able to use the API to achieve this functionality on the client side. 
I will close this issue. 
Thank you
