### ISSUE TITLE
🏆 Node.TLV: API map

### ISSUE THREAD

**Issue by princecodes247** [amplication/amplication#2003]
### 💡 My idea is

An application that makes a visual representation of an API endpoints.

### ✅ The idea is awesome because

Whenever I develop an API, I always find it difficult to wrap my mind around my API endpoints. With a visual representation, it'll to understand how an API works because (humans process images faster and better than text)

**Comment by yuval-hazaz** [comment]
Thanks! something similar will be part of the new feature to support micro-services
I will close this issue
