### ISSUE TITLE
🏆 Node.TLV: Make interactive and challenging websites for backend developers where they can practice and enrich their skills in backend.

### ISSUE THREAD

**Issue by Kardev07** [amplication/amplication#2008]
### 💡 My idea is

To make interactive and challenging websites for backend developers where they can practice and enrich their skills in backend.

### ✅ The idea is awesome because

In this way backend developers not only improve their skills and gain motivation and confidence to build bigger projects but also expand their horizon of knowledge via implementing. I chose this because frontend developers have websites like [Frontend Mentor](https://frontendmentor.io) to practice their skills but backend developers do not specifically have any.

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
