### ISSUE TITLE
🏆 Node.TLV: [Skeltons/Starter Templates for crud full stack apps]

### ISSUE THREAD

**Issue by tomgrigory** [amplication/amplication#2009]
### 💡 My idea is

Skeltons/Starter Templates for crud full stack apps.

for eg: mongodb crud starter, faunadb crud starter and so on.

### ✅ The idea is awesome because

To speed up the dev proceess. Removing all the boring repetive stuff from backend dev and making the dev focus on the intersting and cool stuff

**Comment by souravjain540** [comment]
Thank you so much for contributing to the NODE TLV Conference and making open-source a better place. 🚀 

We appreciate your idea to make backend life easier and encourage you to contribute in the future as well. 💜
