### ISSUE TITLE
🐛 Bug Report: server linter allows function without return type

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2011]
### 📜 Description

no relevent

### 👟 Reproduction steps

run linter on server

### 👍 Expected behavior

block without return

### 👎 Actual Behavior

allow without return

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by mshidlov** [comment]
@tupe12334 thank you for reporting we will address it in the future in more broad approach
