### ISSUE TITLE
🐛 Bug Report: Change all import to direct import

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2014]
We are using the * (all) import option in some of the generated code instead of the {<name>} (direct) import and its increasing the bundle size of the code 

for more info https://stackoverflow.com/questions/42051588/wildcard-or-asterisk-vs-named-or-selective-import-es6-javascript

for example
```
// bad
import * as common from "@nestjs/common"; 
import * as swagger from "@nestjs/swagger";
// good 
import { InjectRolesBuilder, RolesBuilder } from "nest-access-control";
import { CustomerService } from "./customer.service";
import { CustomerControllerBase } from "./base/customer.controller.base";
```

**Comment by mshidlov** [comment]
Hi @tupe12334, this is not clear, can you please explain what are you trying to solve and how?

**Comment by yuval-hazaz** [comment]
closed due to inactivity

**Comment by tupe12334** [comment]
@yuval-hazaz Why did you close that? i think its a good issue and even better as a good first issue

**Comment by yuval-hazaz** [comment]
@tupe12334 I don't think it will be easy to dynamically load all the imports needed on the page based on the generated code. Doable, of course, but with the cost compared to the value, we should not invest time on that. 
As we move forward with plugins, we may be able to introduce more integrated mechanics to manage the import. 
for now, I don't see the value
