### ISSUE TITLE
🐛 Bug Report:  Icon is too close to the text in the community page

### ISSUE THREAD

**Issue by MatanAmplication** [amplication/amplication#2015]
### 📜 Description

as the title
<img width="240" alt="Screen Shot 2021-11-24 at 12 42 55" src="https://user-images.githubusercontent.com/93521174/143228161-a25f9243-be1d-4f04-bff5-6d43959210da.png">

### 👟 Reproduction steps

.

### 👍 Expected behavior

a little bit of space

### 👎 Actual Behavior

.

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by thisisbillall** [comment]
@MatanAmplication can i handle this?

**Comment by MatanForU** [comment]
Sure!

**Comment by MatanAmplication** [comment]
yeah sure!

**Comment by thisisbillall** [comment]
> yeah sure!

Thanks !

**Comment by mshidlov** [comment]
@0xsapphir3 are you on it?

**Comment by 0xsapphir3** [comment]
Yes, in fact, I already opened a PR for that a long time back (https://github.com/amplication/site/pull/149)

**Comment by yuval-hazaz** [comment]
That is true, I will handle it today on the website repo 👍
