### ISSUE TITLE
🐛 Bug Report: Disabled input has an hover state behaving

### ISSUE THREAD

**Issue by MatanAmplication** [amplication/amplication#2019]
### 📜 Description

all of the fields that disabled has the hover state behaving 
<img width="1277" alt="Screen Shot 2021-11-28 at 13 30 34" src="https://user-images.githubusercontent.com/93521174/143766016-b19aa0b4-1fd0-4cb9-aa99-9f8329cb24f8.png">

### 👟 Reproduction steps

.

### 👍 Expected behavior

should be disabled with any hover states

### 👎 Actual Behavior

it has hover states

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by AsianCat54x** [comment]
Can I work on this issue :D

**Comment by tupe12334** [comment]
@AsianCat54x 
Go head!

**Comment by AsianCat54x** [comment]
Oh okay ;)

**Comment by AsianCat54x** [comment]
Hey, can you just tell me where I can find the source code? Like I don't think it is in this repo and I even searched in [this](https://github.com/amplication/site) repo.

**Comment by tupe12334** [comment]
@AsianCat54x is not on the site repo it's on this repo, the client folder/src/Entity/EntityFieldForm.tsx

**Comment by tupe12334** [comment]
https://github.com/amplication/amplication/blob/master/packages/amplication-client/src/Entity/EntityFieldForm.tsx

@AsianCat54x

**Comment by AsianCat54x** [comment]
Oh! Maybe I just missed out on that, sorry about that.

**Comment by mshidlov** [comment]
@0xsapphir3 are you working on it?

**Comment by mshidlov** [comment]
@alexbass86 can you verify wanted behavior

**Comment by alexbass86** [comment]
@mshidlov it shouldn't have any hover effect if it's disabled.
also please make sure the input field has the correct color palate we use for the disabled state.
input text color = #A3A8B8
input bg color = #2C3249
input stroke color = #444B66

**Comment by mshidlov** [comment]
@alexbass86 Thank you

**Comment by suryaraj1** [comment]
@souravjain540 can I work on this issue?

**Comment by souravjain540** [comment]
> @souravjain540 can I work on this issue?

Have a good time working on it

**Comment by suryaraj1** [comment]
Thanks a lot 😄

**Comment by nik132-eng** [comment]
if anything remains can I work on this issue?

**Comment by nik132-eng** [comment]
@souravjain540

**Comment by souravjain540** [comment]
Are you working on this issue? @suryaraj1

**Comment by suryaraj1** [comment]
Hi @souravjain540, I have raised a PR for this issue - https://github.com/amplication/amplication/pull/2453

**Comment by souravjain540** [comment]
thank you :)

**Comment by souravjain540** [comment]
hey @suryaraj1, the email mentioned in your bio is the correct one to contact you?

**Comment by suryaraj1** [comment]
yes it is 😄 , sorry for the late reply, got really caught up. Thanks for the shirt!!
