### ISSUE TITLE
🐛 Bug Report: deleted entity show error

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2032]
### 📜 Description

found a bug that allows you to click a deleted entity

![Screen Shot 2021-12-05 at 16 45 50](https://user-images.githubusercontent.com/61761153/144754484-251c95ca-32c1-48af-ab78-20fa9a705398.png)

### 👟 Reproduction steps

generate app
add entity
commit it and build
delete the entity and don't commit 
press the entity name

### 👍 Expected behavior

don't let the user press a deleted entity

### 👎 Actual Behavior

no relevant

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by mshidlov** [comment]
@alexbass86 and @yuval-hazaz please advise for correct behavior.

**Comment by yuval-hazaz** [comment]
@mshidlov I think the item should not be clickable

**Comment by tupe12334** [comment]
@yuval-hazaz  i thought that too but @alexbass86 said that we need to give the user input about why this item is not clickable

**Comment by alexbass86** [comment]
@mshidlov it should be disabled visually also make sure it's unclickable in order to make people understand what happened, we can add a tiny tooltip with an explanation of why it's unclickable.
![Solution option 1](https://user-images.githubusercontent.com/96179897/146675772-2686bc60-58ba-4277-8216-3d7ebd450d85.png)

**Comment by muhsinkamil** [comment]
@mshidlov I would like to work on this

**Comment by tupe12334** [comment]
> @mshidlov I would like to work on this

go ahead! go luck ;)

**Comment by mshidlov** [comment]
@muhsinkamil sure I'm assigning you 👍

**Comment by muhsinkamil** [comment]
Hey @mshidlov, Any reason why the PR got closed 🤔

**Comment by yuval-hazaz** [comment]
> Hey @mshidlov, Any reason why the PR got closed 🤔

I think it was a mistake. I added to a comment on the PR asking to re-open it

**Comment by mshidlov** [comment]
@muhsinkamil merged your PR, thank you 👍
