### ISSUE TITLE
🐛 Bug Report: Run docker image node alpine on M1 chipset

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2034]
### 📜 Description

Prisma cant generate client code on Alpine image that runs on computers with M1 architecture.

[M1: Provide precompiled binaries for aarch64-unknown-linux-musl target](https://github.com/prisma/prisma/issues/8478)

### 👟 Reproduction steps

In the generated application folder, run:

`run docker build .`

### 👍 Expected behavior

docker run needs to finish with success

### 👎 Actual Behavior

docker build -t test .
[+] Building 57.8s (13/15)                                         
 => [internal] load build definition from Dockerfile          0.4s
 => => transferring dockerfile: 1.23kB                        0.0s
 => [internal] load .dockerignore                             0.5s
 => => transferring context: 35B                              0.0s
 => [internal] load metadata for docker.io/library/node:14-a  0.0s
 => [ 1/11] FROM docker.io/library/node:14-alpine             0.0s
 => [internal] load build context                             0.4s
 => => transferring context: 3.07MB                           0.1s
 => CACHED [ 2/11] RUN npm i -g npm@7.3.0                     0.0s
 => CACHED [ 3/11] WORKDIR /app                               0.0s
 => [ 4/11] COPY server/package.json server/package-lock.jso  0.7s
 => [ 5/11] COPY admin-ui/package.json admin-ui/package-lock  0.9s
 => [ 6/11] RUN cd server; npm ci --loglevel=silent;         24.5s
 => [ 7/11] RUN cd admin-ui; npm ci --loglevel=silent;       27.4s 
 => [ 8/11] COPY server/prisma/schema.prisma ./server/prisma  0.9s 
 => ERROR [ 9/11] RUN cd server; npm run prisma:generate;     1.9s 
------                                                             
 > [ 9/11] RUN cd server; npm run prisma:generate;:                
#13 1.258                                                          
#13 1.258 > prisma:generate
#13 1.258 > prisma generate
#13 1.258 
#13 1.547 Error: Unknown binaryTarget linux-arm-openssl-undefined and no custom binaries were provided
#13 1.560 npm ERR! code 1
#13 1.560 npm ERR! path /app/server
#13 1.563 npm ERR! command failed
#13 1.563 npm ERR! command sh -c prisma generate
#13 1.610 
#13 1.610 npm ERR! A complete log of this run can be found in:
#13 1.610 npm ERR!     /root/.npm/_logs/2021-12-06T13_02_13_348Z-debug.log
------
executor failed running [/bin/sh -c cd server; npm run prisma:generate;]: exit code: 1

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Something Else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by mshidlov** [comment]
Prisma [issue](https://github.com/prisma/prisma/issues/8478) that solves this, is scheduled to version [3.7.0](https://github.com/prisma/prisma/milestone/86)

**Comment by mshidlov** [comment]
Update this was not released in prisma version `3.7.0`

**Comment by morhag90** [comment]
Also happened in the generate application. 

 Log attached:

` => ERROR [ 9/11] RUN cd server; npm run prisma:generate;                                                                                                     0.9s 
------                                                                                                                                                             
 > [ 9/11] RUN cd server; npm run prisma:generate;:                                                                                                                
#13 0.532                                                                                                                                                          
#13 0.532 > prisma:generate                                                                                                                                        
#13 0.532 > prisma generate
#13 0.532 
#13 0.833 Error: Unknown binaryTarget linux-arm64-openssl-undefined and no custom binaries were provided
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c cd server; npm run prisma:generate;]: exit code: 1`

@mshidlov

**Comment by souravjain540** [comment]
@morhag90 @mshidlov is this still relevant?

**Comment by morhag90** [comment]
@souravjain540 I will check it soon and update the issue

**Comment by yuval-hazaz** [comment]
@arielweinberger @mshidlov I move this issue to "stale" 
Please add your comments and let me know if we need to close this issue or not
