### ISSUE TITLE
🚀 Feature: Upgrade prisma version to 3.6

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2035]
### 🔖 Feature description

Move from prisma version `2.X`  to version `3.6.0`
To solve #2034 we need to upgrade prisma version to`3.7.0`.

### 🎤 Pitch

Until `3.7.0` will be released, this upgrade will solve most of the effort 
migration to `3.X` version and give us a head start in solving #2034.

### ✌️ Solution

change prisma dependency version to `3.6.0` and update the code to work with the `3.6.0` changes.

### 🔄️ Alternative

none relevant 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by souravjain540** [comment]
Updated prisma version from 2.X to 3.6.0, preparing for the next prisma update(3.7.0) that will work on M1 architecture.

amplication server, feature?

**Comment by tupe12334** [comment]
@souravjain540 yes
