### ISSUE TITLE
🚀 Feature: Upgrade npm version to 8.1.x

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2037]
### 🔖 Feature description

Upgrade npm version to `8.1.x`

### 🎤 Pitch

this issue is related to #2036 

node `16.13.1` ships by default with npm `8.1.x`

### ✌️ Solution

Upgrade npm version to `8.1.x`

1. make sure all packages pass install, build, test, and run
2. do sanity tests to validate functionality is not broken
3. update dockerfile to use npm version `8.1.x`
4. update GitHub actions to use npm version `8.1.x`

### 🔄️ Alternative

non relevant

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by souravjain540** [comment]
Feature addition? @tupe12334 

"npm version update to 8.1.x, now we support all npm versions less than or equal to v8"
