### ISSUE TITLE
🐛 Bug Report: userinfo insted of user in auth resolver

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2040]
### 📜 Description

In the auth resolver of the generated app we declare the userInfo in the query function to be user info but in real it User type

### 👟 Reproduction steps

generate app
go to auth/auth.resolver

### 👍 Expected behavior

Correct typing

### 👎 Actual Behavior

Userinfo type

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by mshidlov** [comment]
@tupe12334 thank you for sharing this issue. 

please elaborate on your description.
You can share code snippets if it will help you explain.

**Comment by tupe12334** [comment]
Yes

**Comment by yuval-hazaz** [comment]
I am moving this issue to 'stalesd. 
please provide more details so someone will be able to implement it or let's close it
