### ISSUE TITLE
Replace `.pretttierignore` with `.prettierignore` in server

### ISSUE THREAD

**Issue by AsianCat54x** [amplication/amplication#2042]
Going through the server code generated by Amplication, I came across this spelling mistake of file in  `/server/`. It should be `.prettierignore` not `.pretttierignore`.

**Comment by tupe12334** [comment]
@mshidlov want to add this to the next milestone?

**Comment by AsianCat54x** [comment]
You can add if you want

**Comment by souravjain540** [comment]
this going to be part of release notes?

**Comment by tupe12334** [comment]
@souravjain540 yes

**Comment by souravjain540** [comment]
Amplication Server

Fixes

Improved a typo in naming convention of .prettierignore from .pretttierignore
