### ISSUE TITLE
🚀 Feature: moving to nest-access-control UserRoles decorator in resolver

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2043]
### 🔖 Feature description

We generate a src/auth/gqlUserRoles decorator in the generated app, instead of that I went to the official repository of nest-access-control and add support to graphql in the lib.
so now instead of implementing a separated decorator to graphql we can use the nest-access-control lib

### 🎤 Pitch

by doing that we can use an already existing lib that is maintained by the community

### ✌️ Solution

not relevant

### 🔄️ Alternative

existing

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by mshidlov** [comment]
@tupe12334 do we use this package today? please share more information about this package.
