### ISSUE TITLE
🐛 Bug Report: update graphql code gen

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2049]
### 📜 Description

We can upgrade to the latest graphql codegen because the braking change not effect us https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/CHANGELOG.md#200

### 👟 Reproduction steps

not relevant

### 👍 Expected behavior

not relevant

### 👎 Actual Behavior

not relevant

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by souravjain540** [comment]
going to be part of RN?

**Comment by mshidlov** [comment]
merge release `0.11.3`
