### ISSUE TITLE
🐛 Bug Report: Conflicting options in Amplication's CLI 

### ISSUE THREAD

**Issue by 0xsapphir3** [amplication/amplication#2100]
### What happened?

There is a conflicting option in the Amplication's CLI (`entities:fields:update`)

The option for setting field and format has the same shortcut (`-f`).

### What you expected to happen

```
$ amp entities:fields:update --displayName "Creation Date" -f ckxt0rbjj8294951bs645fkdmr1
 ›   Error: Expected --format=ckxt0rbjj8294951bs645fkdmr1 to be one of: JSON, styledJSON, table
 ›   See more help with --help
```

The `-f` flag was supposed to be treated as `field`

### How to reproduce

1. Open a terminal
2. Type `amp entities:fields:update --displayName "When was it created" -f ckxt0rbjj8294951bs645fkdmr1`
3. See the error (The `-f` flag was meant for field but it is treated as for `--format`)0.

### Amplication version

0.1.4

### Environment

-

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by mshidlov** [comment]
merged in #2171
