### ISSUE TITLE
Dtos index file

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2104]
### Feature description

In the folder that we generating the dtos we can add an index file that include all the dtos

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by mshidlov** [comment]
Hi, @tupe12334 thank you for your suggestion. can you please explain what do you want to accomplish and why this is needed?

**Comment by tupe12334** [comment]
@mshidlov I want to implement a best practice that tell to export all the files from folder via index.ts file

**Comment by yuval-hazaz** [comment]
is that something we are still considering or can we close it?

**Comment by tupe12334** [comment]
@yuval-hazaz I still think that its the smart thing to do and even have a pr that does that

**Comment by yuval-hazaz** [comment]
I think it would be a good example of a plugin that will control the style of the code 
Let's keep this open and we can revisit it once the plugin systems is ready

**Comment by arielweinberger** [comment]
This is not a common practice in NestJS so I'm going to close this.
