### ISSUE TITLE
🐛 Bug Report: setup:dev action missing cache

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2105]
### What happened?

In the setup script github action, we don't have a cache at all, it makes the script run for a long time and cancel

### What you expected to happen

Load all the un changed packages from the cache

### How to reproduce

Run the script and see

### Amplication version

0.11.0

### Environment

not relevant

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by mshidlov** [comment]
merged in PR #2106
