### ISSUE TITLE
🐛 Bug Report: @ockuf/test in cli

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2114]
### What happened?

The oclif/test package in the cli is not in use inside the code

### What you expected to happen

Remove the package or write tests that use that

### How to reproduce

not relevant

### Amplication version

0.11.0

### Environment

not relevant

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by yuval-hazaz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/3oOFXGNt/11-test)

**Comment by devblin** [comment]
Hey @mshidlov , I am willing to work on this issue.

**Comment by yuval-hazaz** [comment]
cool, go ahead I assigned you

**Comment by devblin** [comment]
Made PR for the fix.

**Comment by yuval-hazaz** [comment]
thanks @devblin, we will review soon
