### ISSUE TITLE
Add @amplication/server docker file 

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2165]
Create a dedicated docker file to @amplication/server.

Using Node 16.3.1 alpine base image, and build best practices:
- Optimize docker layers
- Image size
- Use pinned specific versions

Refer root docker file in master branch, and root docker file branch [refactor/npm-prune](https://github.com/amplication/amplication/tree/refactor/npm-prune)

**Comment by timothy-amplication** [comment]
@mshidlov 
The error below occurs when you only build `amplication/server` and excluding `amplication/client` (`npm run build -- --scope @amplication/server`)
```sh
# Browser Client @ localhost:3000

{"statusCode":404,"message":"ENOENT: no such file or directory, stat '/Users/oz/amplication/packages/amplication-client/build/index.html'"}
```

1. `amplication/server` is using the [NestJS Serve-Static Package](https://docs.nestjs.com/recipes/serve-static) which is serving up the `amplication/client` compiled assets. If we want to separate the Server and Client into their own container images we will most likely need to rip out the *`ServeStaticModule` from [amplication-server/src/app.module.ts](https://github.com/amplication/amplication/blob/master/packages/amplication-server/src/app.module.ts#L21-L30).*
    1. Are there any concerns with this approach?
    2. Are there other areas in `amplication/server` that use/depend on `amplication/client` which may be subject to similar remediation tasks like the above?
2. Are there any ping or health-checks in `amplication/server` I can use to validate that the server is listening and accepting requests (nice to have when testing the server in isolation; and for sending traffic to healthy services)? I didn't see any NestJS specific Health-checks, perhaps it'd be worthwhile to implement [HttpHealthIndicator](https://docs.nestjs.com/recipes/terminus#healthchecks-terminus).

**Comment by mshidlov** [comment]
@timothy-amplication

1. You are definitely right about the relation between `@amplication/server` and `@amplication/client`. if we will break that relationship now, it will cause the root docker file to break. As of today, this is the Dockerfile we are deploying.
Let's do it in steps. For now, keep and ignore `@amplication/client` in the server Docker file.

2. You are right. Readiness and liveliness are essential when making infrastructure aware of the application's availability. I will open up an issue regarding this matter. Would you like me to assign you?

**Comment by timothy-amplication** [comment]
@mshidlov I gone ahead and set up the initial task for Health Checks for `@amplication/server` - https://github.com/amplication/amplication/issues/2192. Feel free to add anything else i may be forgetting.
