### ISSUE TITLE
@amplication/client- Commit menu location change

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2173]
### Feature description

Currently, we have 2 steps for our menu, just for the commit button.
To create consistent behavior in our menu, we decided to move the commit\rebuild button changes to their own space on the right side of the screen.
This change will create a more consistent flow in our primary menu.

1. Adding loading skeleton animation - on rebuild\commit
2. Changing commit location

![Code View - Skelaton](https://user-images.githubusercontent.com/91742238/148974262-2a17a08c-1b7d-4bd9-89bf-8d06b9e8eb6b.png)

![Code View - App](https://user-images.githubusercontent.com/91742238/148974257-30e5fad6-c099-4d6b-bd2c-2c2a5479e971.png)

[figma](https://www.figma.com/file/70wYn5kbPayUCZ57KV3Kqu/Menu-Change---Commit?node-id=363%3A1521)

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by jainpawan21** [comment]
@mshidlov I think figma link mentioned by you is not public

**Comment by mshidlov** [comment]
Hey @jainpawan21, the figma link is private, but the screens are here in the issue.

**Comment by mshidlov** [comment]
merged in #2171
