### ISSUE TITLE
🐛 Bug Report: tool tip doesn't show on 13 inch screen

### ISSUE THREAD

**Issue by MatanAmplication** [amplication/amplication#2180]
### What happened?

the tool tip in the in the user name is barely showing

<img width="1440" alt="Screen Shot 2022-01-12 at 15 02 35" src="https://user-images.githubusercontent.com/93521174/149213973-7e16a7c2-2aa9-42a9-8efc-e64f6bf1612d.png">
 

### What you expected to happen

if it goes above the screen layout it should go to the bottom according to the screen size

### How to reproduce

.

### Amplication version

0.11

### Environment

.

### Anything else

.

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by noyagasi** [comment]
Hey Matan, I tried to solve it with #2189 . I hope it'd help.

**Comment by MatanAmplication** [comment]
Thanks! :)
