### ISSUE TITLE
🐛 Bug Report: Amplication client is using the default React icon for preview

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2196]
### What happened?

Amplication client is missing a social preview 
currently it shows the default react icon

![image](https://user-images.githubusercontent.com/43705455/149669470-7dca97c6-b3cc-4662-aaff-3016f8586b52.png)

### What you expected to happen

instead of the default React icon, it should show a styled banner or icon

### How to reproduce

add a link to whatsapp to https://app.amplication.com and see the preview 

### Amplication version

0.11.2

### Environment

a

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by noyagasi** [comment]
should be fixed by #2197
it called rich preview and it usually used by the open graph protocol

**Comment by yuval-hazaz** [comment]
Thanks @noyagasi 👍
