### ISSUE TITLE
🐛 Bug Report: position of  the error message when trying to login with a user that doesn't exist

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2201]
### What happened?

When I tried to sign in with a user that does not exist, I got an error in the terminal. 
![image](https://user-images.githubusercontent.com/39680385/149796038-a6a37a9e-fdc5-4566-8c3b-4e713ae9e812.png)

I also got an error message presented by a toaster at the left corner of the screen, which I also think is a bad user experience because It was for a short time, and I did not expect to see an error there.

![image](https://user-images.githubusercontent.com/39680385/150208034-4e24e465-575a-4096-a1cf-da2df7bd34fb.png)

### What you expected to happen

I expect that the server will catch the error, and the client will show it to the user while the terminal will be clean.
I also expect to see the error message in the form area for an extended period or even persistent until the user fixes the error.

### How to reproduce

Run the dev environment and open http://localhost:3001/login
open the web console
try to log in with a user that you didn't register with
you will see the error on the terminal

### Amplication version

0.11.1

### Environment

Node version: 14.17.3
npm version: 8.3.1
docker version: 20.10.8
browser: chrom version 97

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by yuval-hazaz** [comment]
Thanks @abrl91 
I assigned the issue to you, so you can go ahead and fix it

**Comment by yuval-hazaz** [comment]
@abrl91 
please use this design for displaying the message.

![image](https://user-images.githubusercontent.com/43705455/150300806-84c3412b-c705-446f-a405-854443df84d5.png)


There is already a code on the page that show other types of errors in the suggested way - so, what is best to do:

1. Create a new component in ../amplication-client/src/components/ErrorMessage.tsx
2. Replace the existing code in login.tsx to use the new component
3. use the new component to show the login error message
