### ISSUE TITLE
Add `opened pull request` Discord notification

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2209]
### Feature description

To improve Amplication team responsiveness to community PRs, we can add a notification on Discord that notify the team that a new PR was opened in the Amplication repository.

### Use case

Any PR that will be opened, a notification with the PR details will be sent to Amplication team over Discord.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by yuval-hazaz** [comment]
@mshidlov can we close this one?

**Comment by mshidlov** [comment]
yes
