### ISSUE TITLE
🐛 Bug Report: Unauthorized pop up after creating new credentials and deleting the old one.

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#2216]
### What happened?

When we go to the react admin after creating the application using Amplication console, and creates a new user with new credentials and delete the admin one then we got this pop up-![image](https://user-images.githubusercontent.com/53312820/150951432-79996c17-1453-41a5-a7b3-f9e3314457fc.png)

And when we cannot do anything after that it is showing unauthorized.

### What you expected to happen

App should work with new credentials after deleting the admin one.

### How to reproduce

1.) Open Amplication Console
2.) Create some entities with the user.
3.) Create a new user from React admin
4.) Delete the admin user
5.) Try to make a new user, you'll get an unauthorized pop-up.

### Amplication version

0.11.1

### Environment

Amplication Console and React Admin

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by mshidlov** [comment]
@souravjain540 Thank you for reporting that issue 👍

**Comment by mshidlov** [comment]
@yuval-hazaz Is it possible that this a roles problem that can be solved with existing behavior?

**Comment by souravjain540** [comment]
any updates @yuval-hazaz ?

**Comment by yuval-hazaz** [comment]
I think that we can limit the option for a user to delete their own account.
We can add some detailed instructions and make this a good first issue

**Comment by yuval-hazaz** [comment]
I think this behavior is expected when a user deletes their own account that they will be kicked out of the system
I agree that we may be able to implement some logic that will prevent a user from deleting their own account, but I think this is a low priority with low impact for now, so I will close this issue
