### ISSUE TITLE
🐛 Bug Report: New Issue Template - typo 

### ISSUE THREAD

**Issue by 0p-knight** [amplication/amplication#2217]
### What happened?

![unnamed.jpg](https://user-images.githubusercontent.com/93305414/151020637-c66c6322-23fe-460e-af59-40a462671503.jpg) 
*The wrong spelling is in the fourth line*
Spelling of Herokue is wrong.

### What you expected to happen

The correct spelling is Heroku.

### How to reproduce

-

### Amplication version

1.1

### Environment

Amplication Console

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by yuval-hazaz** [comment]
Thanks @Royalpurpl7 
Would you please share a screenshot or a URL of the page when you see the wrong spelling?

**Comment by 0xsapphir3** [comment]
![IMG-20220125-WA0011.jpg](https://user-images.githubusercontent.com/82395440/151018975-3ef55938-478a-4967-a927-f5ee0c8b5f65.jpg)

Here is the screenshot (You can see it in the fourth line)

**Comment by yuval-hazaz** [comment]
Thanks!

**Comment by yuval-hazaz** [comment]
@Royalpurpl7 I assigned this issue to you, so please feel free to fix it and send a new PR

**Comment by Royalpurpl7** [comment]
_Okay sir I'll be doing it in some time_

**Comment by preet-2** [comment]
Can i take this issue

**Comment by souravjain540** [comment]
> Can i take this issue

done. @preet-2 !

Have a good time working on it.

**Comment by Dvip07** [comment]
Hey, Can I take Issue?

**Comment by gorakh999** [comment]
Hey, can i take this issue ?

**Comment by souravjain540** [comment]
hey @preet-2, I need your email to contact you :)

**Comment by preet-2** [comment]
> hey @preet-2, I need your email to contact you :)

My email id is - bhatiapreet059@gmail.com
