### ISSUE TITLE
🐛 Bug Report: Use of @rmwc/icon

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2229]
### What happened?

In the client/src/components/ErrorMessage.tsx we use @rmwc/icon package even if its not in our package.json

### What you expected to happen

not relevant

### How to reproduce

not relevant

### Amplication version

0.11.2

### Environment

not relevant

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by mshidlov** [comment]
@tupe12334, I'm closing it because this is already fixed
