### ISSUE TITLE
🐛 Bug Report: Close button o

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2238]
### What happened?

When I'm on a single tab, we shouldn't have a close button
![image](https://user-images.githubusercontent.com/96179897/151980046-e217a641-179a-488f-9935-3edccd9b057d.png)

### What you expected to happen

If we have a close button on a tab logically, it should close it, but in this case, nothing happens.

### How to reproduce

By opening the app and having only one tab open

### Amplication version

0.11.2

### Environment

Something will probably need to go here, but I don't know really what

### Anything else

Cows moo with regional accents.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by mshidlov** [comment]
@alexbass86 can you please give an explanation on what should be presented when a single tab is closed?

**Comment by alexbass86** [comment]
> @alexbass86 can you please give an explanation on what should be presented when a single tab is closed?

It should be full screen without any tab (tab appears only when it has more than a few options clicked).
something like this:
![image](https://user-images.githubusercontent.com/96179897/152675052-8a0a648a-f223-4ea4-83f4-3ef2ddd4c5ad.png)

Or a tab without the "close" button (we need to hide the button only when it's a single tab open).
something like this:
![image](https://user-images.githubusercontent.com/96179897/152675246-5a10b448-ee9a-4499-8181-caba47128fe6.png)

**Comment by mshidlov** [comment]
@alexbass86 I think that it should be an empty screen when clicking the `X` button. It is not very clear to have part of the time button and part of the time not, the same goes for the tab itself.

**Comment by alexbass86** [comment]
> @alexbass86 I think that it should be an empty screen when clicking the `X` button. It is not very clear to have part of the time button and part of the time not, the same goes for the tab itself.

From how it works currently, we usually don't have that type of screen. When you are inside an app, the overview is our first screen. 
I don't think we need an empty screen as it can confuse people where they are at on specific moment

**Comment by alexbass86** [comment]
> @alexbass86 I think that it should be an empty screen when clicking the `X` button. It is not very clear to have part of the time button and part of the time not, the same goes for the tab itself.

From how it works currently, we usually don't have that type of screen. When you are inside an app, the overview is our first screen. 
I don't think we need an empty screen as it can confuse people where they are at on specific moment

**Comment by alexbass86** [comment]
@mshidlov hey any update?

**Comment by souravjain540** [comment]
@alexbass86 @mshidlov any updates on this?

**Comment by yuval-hazaz** [comment]
I suggest that we close this issue as it had a minimal to no impact at all and any attempt to "resolve" it will require too many efforts
