### ISSUE TITLE
🐛 Bug Report: Missing Commit/Rebuild Collapse button

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2239]
### What happened?

We don't have a closing button
![image](https://user-images.githubusercontent.com/96179897/151996954-15c366bb-8a1c-4ac1-9a73-af3d6dc8a1c6.png)

Here example from the design
![image](https://user-images.githubusercontent.com/96179897/151997043-12d8a4ea-e882-45d9-931a-3a99088994db.png)

### What you expected to happen

we have two options to collapse our commit/rebuild section by clicking on the icon bellow
![image](https://user-images.githubusercontent.com/96179897/151997307-4ac221f7-e76a-4ba6-9a11-4ff4b8c423e1.png)
and by clicking on the close button on top, which is missing
![image](https://user-images.githubusercontent.com/96179897/151997650-848fd52a-09a4-4124-9ff4-72a22c3c3706.png)

### How to reproduce

Open the app, and it's on the right side of the screen.

### Amplication version

0.11.2

### Environment

.

### Anything else

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by yuval-hazaz** [comment]
Congrat @alexbass86 for your first Issue 🚀

**Comment by yuval-hazaz** [comment]
@all-contributors please add  @alexbass86  for design and bug

**Comment by muhsinkamil** [comment]
@alexbass86 Can I take it up ?

**Comment by alexbass86** [comment]
> @alexbass86 Can I take it up ?

sure, I assigned you :) good luck mate

**Comment by mshidlov** [comment]
thank you @muhsinkamil, this issue was merged in release `0.11.3`
