### ISSUE TITLE
The issue template on all other public repos, show include instructions to open issues on amplication/amplication

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2241]
### Describe the issue with documentation

Under our organization on GitHub we have several public repos like site, blog, and docs.
Since we are not tracking issues on all other repos, we need to update the issue template on those repos and ask the community to report the issue on the main (this) repo

### How to solve the problem

Update the issue template on all other public repos and ask the community to open issues on amplication/amplication

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by alceil** [comment]
I would like to help with this issue. Can you assig me this issue? @yuval-hazaz . I would like some pointers on how to proceed as well. I need to use the same issue template that this repo has right?

**Comment by yuval-hazaz** [comment]
@alceil sorry I missed your request! 
yes, you can go ahead and do that

What we need is to create a single issue template that will include instructions and a link to open the issue in this repo instead of in the other repo.

The new template should be added to all other public repositories under the Amplication organization https://github.com/orgs/amplication/repositories

Something like 
```
Hi there 👋
We are not tracking issues in this repo. To report an issue related to this repo, please open the issue on our main repo amplication/amplication https://github.com/amplication/amplication/issues/new/choose
```

**Comment by souravjain540** [comment]
> Can I work on this?

you can work on maximum one issue :)

**Comment by Ash-KODES** [comment]
> > Can I work on this?
> 
> you can work on maximum one issue :)

Ya sure,,actually i thought its a different issue,,apologies

**Comment by sohailg** [comment]
Can i work on this?

**Comment by sohailg** [comment]
> > Can i work on this?
> 
> Have a good time working on it.

I've changed the code in amplication/doc 
https://github.com/amplication/docs/pull/119

**Comment by yuval-hazaz** [comment]
perfect, thanks
I will close this issue, and we will consider doing the same for all other public repos. 
If needed, I will open a new issue with a list of all other repos that need the same thing
