### ISSUE TITLE
🐛 Bug Report: main page/team page issues when screen wider than 1920px

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2242]
### What happened?

It seems that the hero is aligned to the left while all other content is in the center. It's noticeable as soon as the screen becomes wider than the regular 1920 px width
![image](https://user-images.githubusercontent.com/96179897/152116862-98a05b6e-25ac-4528-a298-bcc0ba25aaf7.png)

also, on the team page, when we go wider than 1920px, the text on the left side become tiny while the main img on the right grow with the page due to the responsive
![image](https://user-images.githubusercontent.com/96179897/152117507-46f1a567-a27d-4672-8b1a-deb48ffed117.png)

### What you expected to happen

On the main page, the text should be more significant after 1920, so it won't look tiny on larger screens. It's noticeable because the img on the right is getting larger related to screen size``

### How to reproduce

Just view it on a larger screen

### Amplication version

0.11.2

### Environment

.

### Anything else

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by mshidlov** [comment]
@alexbass86 
Hey, thank you for reporting that issue. can you please explain what did you mean when you talked about the "hero"?
maybe you can share a screenshot and highlight the issue on top of the screenshot?

**Comment by souravjain540** [comment]
@alexbass86 is this on your task list or for the community?
