### ISSUE TITLE
🐛 Bug Report: wrong download icon in build screen

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2244]
### What happened?

Wrong icon
![image](https://user-images.githubusercontent.com/96179897/152136258-c0538683-c8f4-45dd-8150-346f7d591f35.png)

### What you expected to happen

We should be consistent with our icons, which means if we have a specific download icon, 
it should be the same across the app.

so let's use the icon called "**download1**" for all our download buttons
![image](https://user-images.githubusercontent.com/96179897/152136450-259e09e4-a6b0-441f-ad14-fe2d3c08ca31.png)

### How to reproduce

Click on the build button

### Amplication version

0.11.2

### Environment

.

### Anything else

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by mshidlov** [comment]
@alexbass86 Thank you for reporting that issue

**Comment by kwinyyyc** [comment]
Can I take this?

**Comment by tupe12334** [comment]
@kwinyyyc go luck @mshidlov please assign him
