### ISSUE TITLE
🐛 Bug Report: dockerode package update

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2255]
### What happened?

We need to update the dockerode package in the server/container-builder/deployer but the types we use is not compatible to the up to date types.
the error happened in the src/docker/DockerProvider -> DockerProvider class -> build function

this issue is open to replace [#2183](https://github.com/amplication/amplication/pull/2143) pull request

### What you expected to happen

not relevant

### How to reproduce

not relevant

### Amplication version

0.11.3

### Environment

not relevant

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by yuval-hazaz** [comment]
@tupe12334 is that still relevant? should we handle it or close it?
