### ISSUE TITLE
🐛 Bug Report: Updating the apollo-server-express package

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2259]
### What happened?

We need to update the apollo-server-express package
I opened this issue to replace the renovate pr #2151 

### What you expected to happen

not relevant

### How to reproduce

not relevant

### Amplication version

0.11.3

### Environment

not relevant

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by theamanbhargava** [comment]
Can I take a look at this please?

**Comment by souravjain540** [comment]
done @theamanbhargava

**Comment by yuval-hazaz** [comment]
@arielweinberger @tupe12334 @mshidlov please let me know if we can close this issue or is it still relevant
