### ISSUE TITLE
🐛 Bug Report: Generated app - gqlUserRoles.decorator.ts fails for public queries 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2268]
### What happened?

The decorator `gqlUserRoles.decorator.ts` does not check for the existence of the user on the request and fails when there is no user in context

### What you expected to happen

The decorator should return null or an empty array when there is no user in context

### How to reproduce

See #2006 

### Amplication version

0.11.2

**Comment by tupe12334** [comment]
This solution build from 2 steps

- [x]  : update our use of the user roles for use only nest access control package

(i did that in the #2325 pr)

- [ ]  update the nest access control package with the logic the prevent crashes

(i did that in https://github.com/nestjsx/nest-access-control/pull/71 pr, wait for approval)
