### ISSUE TITLE
🐛 Bug Report: Unable to access graphql playground

### ISSUE THREAD

**Issue by muhsinkamil** [amplication/amplication#2270]
### What happened?

On navigating to `localhost:3000/graphql`, blank screen appears.

<img width="1415" alt="Screenshot 2022-02-05 at 12 57 13 PM" src="https://user-images.githubusercontent.com/62111075/152632971-8855a0b9-e5d5-49d6-bd4a-e983485712dd.png">

### What you expected to happen

graphql playground should be available at localhost:3000/graphql

### How to reproduce

- Finish dev setup. 
- Start docker, amplication-server
- Try `localhost:3000/graphql`

### Amplication version

0.11.3

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mshidlov** [comment]
@muhsinkamil thank you for reporting this bug and submitting a PR
