### ISSUE TITLE
Create Kubernetes Setup

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2284]
Create kubernetes setup.

Use the separated docker images (@amplication/server, @amplication/client) Create all relevant yaml files for deployments and network.

This setup should enable running Amplication on local\remote environment.

**Comment by mshidlov** [comment]
Amplication Helm Chart(s)
    1. Client
    2. Server
    3. Postgres Helm
    4. Ingress-Controller

**Comment by arielweinberger** [comment]
Closing, will create a separate issue for remote development
