### ISSUE TITLE
🐛 Bug Report: missing one to one relation in test data

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2305]
### What happened?

In the e2e test and snap shot test we use data but the data dont have one to one relation test.
it critical for detection of changes to the one to one in the snapshot.

### What you expected to happen

have a test for all options

### How to reproduce

not relevant

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mshidlov** [comment]
Thank you @tupe12334 for reporting this issue

**Comment by souravjain540** [comment]
is this a good explanation and a good fit for 10-issues-10-shirts? @mshidlov @tupe12334

**Comment by tupe12334** [comment]
@souravjain540 I think so

**Comment by tupe12334** [comment]
closed in #3180 @abrl91
