### ISSUE TITLE
🐛 Bug Report: sorting icon behaving as a dropdown

### ISSUE THREAD

**Issue by MatanAmplication** [amplication/amplication#2306]
### What happened?

<h2> the workspace sorting icon is there instead of dropdown </h2>

<img width="287" alt="Screen Shot 2022-02-16 at 14 16 54" src="https://user-images.githubusercontent.com/93521174/154263748-413ebb34-14f1-44ba-b99b-48c1cda038cc.png">
<img width="294" alt="Screen Shot 2022-02-16 at 14 16 44" src="https://user-images.githubusercontent.com/93521174/154263752-50ccda99-373a-41a8-a1cd-6fb662c1cba1.png">

### What you expected to happen

change the icon

### How to reproduce

.

**Comment by mshidlov** [comment]
Thank you @MatanAmplication for reporting this issue
@alexbass86 can you please share what is the correct icon to use here?

**Comment by alexbass86** [comment]
> Thank you @MatanAmplication for reporting this issue @alexbass86 can you please share what is the correct icon to use here?

Yes please use the one called "chevron_down" 
![image](https://user-images.githubusercontent.com/96179897/154836529-41453cb3-f7cb-4ed7-b282-543f1fb88724.png)

also, make sure when the list opens up, the icon should change to "chevron_up"
![image](https://user-images.githubusercontent.com/96179897/154836593-8ce0b71f-7c01-4029-90fe-b1f274c3e44a.png)

**Comment by mshidlov** [comment]
Thank you @alexbass86

**Comment by molaycule** [comment]
@mshidlov, how can this issue be reproduced?

**Comment by mshidlov** [comment]
Hey @molaycule this feature is not part of the OSS so this can be reproduced only on Amplication SaaS version.

you can find it on https://app.amplication.com
