### ISSUE TITLE
🐛 Bug Report: Tooltip text is not visible in light theme mode

### ISSUE THREAD

**Issue by molaycule** [amplication/amplication#2323]
### What happened?

In light theme mode, when hovering on a component that has tooltip, the tooltip text is not visible to the user.

### What you expected to happen

Tooltip text should be visible even in light theme mode.

![Screenshot (407)](https://user-images.githubusercontent.com/20028628/154815207-b3fddf07-e331-4256-afd7-e6b5fa2cd923.png)

### How to reproduce

Switch to light theme mode, then hover on any sidebar item that has tooltip, you would notice that the tooltip text is not visible.

### Amplication version

0.11.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mshidlov** [comment]
Thank you @molaycule for reporting this issue and submitting a PR, we will review the PR soon
