### ISSUE TITLE
🐛 Bug Report: the left side of the panel should be fixed while scrolling

### ISSUE THREAD

**Issue by MatanAmplication** [amplication/amplication#2327]
### What happened?

the left side of the panel should be fixed while scrolling down
<img width="1440" alt="Screen Shot 2022-02-20 at 16 00 17" src="https://user-images.githubusercontent.com/93521174/154848326-59402ada-0f8b-45c3-9142-bf124cb28caa.png">
<img width="1440" alt="Screen Shot 2022-02-20 at 16 00 27" src="https://user-images.githubusercontent.com/93521174/154848334-19f821db-42f5-4f4c-bb96-26be5e3fcdb1.png">

### What you expected to happen

it should show me the status while I'm scrolling down as well

### How to reproduce

.

### Amplication version

11.3

**Comment by molaycule** [comment]
@mshidlov, I would like to work on this, can you assign to me?

**Comment by mshidlov** [comment]
@alexbass86 please approve this change by:
1. changing the backlog board statue to Accepted
2. adding  `status: accepted` label
3. adding  `help wanted`  and `good first issue` if this should be opened for the community to help (and this one should) 


Check this doc for guidance -> https://docs.amplication.com/docs/community/handling-a-new-issue
or just ping me.

**Comment by mshidlov** [comment]
@mshidlov sure no problem I will assign you soon 👍

**Comment by KayhanB** [comment]
Hi, I think this container can be shown at the top of the build log container as a sticky stepper header and the user can scroll it horizontally. in this way, we will gain space on the page.

**Comment by molaycule** [comment]
Hi @KayhanB, I am guessing just the build log container scrolls while every other container stays in place.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/20028628/154909871-72a6086f-ed98-4203-8e4f-f4c7663ca0e6.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/20028628/154910667-e9085268-6ff9-433c-beea-a8c100d2f76b.png">

**Comment by yuval-hazaz** [comment]
> Hi, I think this container can be shown at the top of the build log container as a sticky stepper header and the user can scroll it horizontally. in this way, we will gain space on the page.

I agree with @KayhanB - moving the steps to the top of the screen will give more space for the logs and will also remove the horizontal scrolls in most screens

**Comment by alexbass86** [comment]
> Hi, I think this container can be shown at the top of the build log container as a sticky stepper header and the user can scroll it horizontally. in this way, we will gain space on the page.

It's an excellent idea, but we can't just move it on top of the page. 
It will require a new design for this container.

**Comment by alexbass86** [comment]
After some think here few possible options, please let us hear your opinion:

**Option 1**, the same stepper with less width space, also changed how progress represented each step, and the copy is now shorter. No significant changes, yet we get more screen space. Also, this stepper is a sticky one.
![v1](https://user-images.githubusercontent.com/96179897/154994168-9cd152c8-3e2d-448c-aec5-cf0dd50ad03c.png)

**Option 2**, we move the stepper to be on top, which helps us get more screen space for the container. Cleaner look with a straightforward approach. This one I personally really like. This stepper become sticky as soon as we start to scroll
![v3](https://user-images.githubusercontent.com/96179897/154994649-cfa23a53-19a6-4c9b-8002-798978356ba0.png)

Looking forward to hearing your thoughts :)

**Comment by molaycule** [comment]
@alexbass86 option 2 looks neat, but what happens if there are going to be more build steps along the line, will the build step container have a horizontal scrollbar? And how will the user be able to see all the build steps at one glance if the build steps are more than four or is the build steps just limited to just these four steps?

**Comment by abrl91** [comment]
for gaining more space on the screen we can implement collapsed sidebar

https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_collapse_sidebar

**Comment by tupe12334** [comment]
I stand for the second option that give as the option in the future to add more details

**Comment by yuval-hazaz** [comment]
@abrl91 and @molaycule I love how you think very logically on the future functional requirements. 
I agree that we may have additional steps in the future and although I vote for option 2, you made me change my mind and I vote for option 1

@alexbass86 If needed, we can add a longer and more descriptive text for each step with tooltips

**Comment by mshidlov** [comment]
@alexbass86 @yuval-hazaz I also think option 1 is the best one.

can we decide on option 1?

**Comment by jainpawan21** [comment]
Hi, 
Any update on this?
I would like to work on this issue if it is finalized.

**Comment by yuval-hazaz** [comment]
I think the current options are not impactful in a way that is worth investing time in it right now. 
@alexbass86 I suggest that we rethink this issue in a holistic way with the rest of the planned changes

**Comment by alexbass86** [comment]
> I think the current options are not impactful in a way that is worth investing time in it right now. @alexbass86 I suggest that we rethink this issue in a holistic way with the rest of the planned changes

Agree

**Comment by souravjain540** [comment]
@yuval-hazaz @alexbass86 is this still relevant?

**Comment by alexbass86** [comment]
> @yuval-hazaz @alexbass86 is this still relevant?
not anymore, we doing new design for this screens
