### ISSUE TITLE
Feature: Manage Code State

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2336]
### Feature description

Every time a developer generates the code, the entire code based is synced to GitHub in a pull request, with no knowledge of which files were changed since the last build.

This causes unnecessary override of files that were not changed since the last build but still are pushed to GitHub. 

In case the developer customizes any of the files in git, they will be overridden for no reason.

Instead, the generated code should be saved on Amplication. When creating a new build, the newly generated code should be compared with the last saved state and only the files that were changed should be pushed to GitHub. 

This is another step that will allow better flexibility for customization. It will allow the developer to customize many files that are rarely changed by Amplication.

### Use case

For example, The developer will be able to customize `package.json` to add new packages.

As long as there are no changes in Amplication in this file, the developer will still be able to push new builds to GitHub without losing the custom changes. 

When the `package.json` file is changed in Amplicaiton, it will still override the custom changes in Git (via Pull Request. This should be handled in a new scope that will allow code merge and files ownership.

**Comment by yuval-hazaz** [comment]
@mshidlov can we link this issue with the recent PRs and close it?

**Comment by mshidlov** [comment]
#2596
