### ISSUE TITLE
🐛 Bug Report: Docs - chat icon on top of fast menu (Mobile)

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2341]
### What happened?

We have two icons, one on top of each other, which make the fast nav menu unclickable
![image](https://user-images.githubusercontent.com/96179897/154981387-0a600341-2564-4d58-a255-d08f6c873a0e.png)

if we remove the chat icon, we can see this fast nav
![image](https://user-images.githubusercontent.com/96179897/154981531-fb87cc80-a19d-41a2-a45b-9d1c713bcdfd.png)

### What you expected to happen

Both icons need to be clickable. 
We have a menu on top that doesn't have anything except a URL for our Github. We should use this menu for the fast doc navigation and leave the chat icon in the same place
![image](https://user-images.githubusercontent.com/96179897/154982019-f48b56cb-2722-48ae-acb6-4afa9ffc4878.png)

Also, the menu place should be consistent with our website, which is on our right side, search should be next to the menu icon

**Docs**
![image](https://user-images.githubusercontent.com/96179897/154982464-c9af1cad-4b96-4100-878c-d14ff1c8f5d0.png)

**Website**
![image](https://user-images.githubusercontent.com/96179897/154982553-17ae0e53-6df2-4efd-875c-5abdaf41f7d3.png)

### How to reproduce

Mobile version of our docs.
docs.amplication.com

### Amplication version

0.11.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mshidlov** [comment]
Thank you, @alexbass86, for reporting that issue. 
just adding that the docs repository [link](https://github.com/amplication/docs)

**Comment by yuval-hazaz** [comment]
fixed in https://github.com/amplication/docs/pull/112
