### ISSUE TITLE
🐛 Bug Report: Notification color should be the same in both ways

### ISSUE THREAD

**Issue by MatanAmplication** [amplication/amplication#2342]
### What happened?

the notification should be in the same color as the bottom one
<img width="152" alt="Screen Shot 2022-02-21 at 15 34 45" src="https://user-images.githubusercontent.com/93521174/154967412-6656596a-7854-4e93-8551-afd8e05a3d20.png">

### What you expected to happen

it should be in the same color

### How to reproduce

.

### Amplication version

11.3

**Comment by Rutam21** [comment]
I will like to work on this.

**Comment by Rutam21** [comment]
@yuval-hazaz Thanks for assigning this to me. Can you point me to the file where this needs to be done? Thanks.

**Comment by yuval-hazaz** [comment]
This is the file
packages/amplication-client/src/VersionControl/PendingChanges.tsx

**Comment by souravjain540** [comment]
@Rutam21 are you still working on this?

**Comment by MichaelSolati** [comment]
@souravjain540 I have the time and don't mind getting to this today.

**Comment by yuval-hazaz** [comment]
You can go for it @MichaelSolati . I will assign it to you
