### ISSUE TITLE
Add i18n support for Amplication

### ISSUE THREAD

**Issue by Rutam21** [amplication/amplication#2343]
### Feature description

I would suggest that we set up an i18n infrastructure so that contributors can contribute and add regional language support for Amplication so that it can be widely used across all geographical regions in the native language as needed.

### Use case

This would add multiple language support to Amplication and would increase the accessibility of multiple locales with technical and cultural needs. 

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mshidlov** [comment]
Hey @Rutam21, thank you for opening that feature request; I accepted your suggestion. Would you like to be assigned for it?

**Comment by abrl91** [comment]
Hey @mshidlov , if @Rutam21 don't want to work on this issue, I would love to :)

**Comment by abrl91** [comment]
I will start reading i18n documentation and find out the best solution for implementing this feature

**Comment by Rutam21** [comment]
I believe for setting up the correct repo structure and what needs to be translated and how the task needs to be divided into sub-tasks, we need to sit together with someone from the Amplication team. This is a bigger chunk of task setting up the infra first and then open issues for contributors to translate to their native languages.
CC: @mshidlov @yuval-hazaz

**Comment by yuval-hazaz** [comment]
@abrl91 that would be great
@Rutam21 I agree ☝️. We will wait for Amit’s recommendations and then we can discuss the best approach

**Comment by byt3h3ad** [comment]
has a proper roadmap been figured out for this? will like to contribute to it.

**Comment by martinez-hugo** [comment]
Hi ! Can I work on this issue ?

**Comment by yuval-hazaz** [comment]
hi @martinez-hugo, thanks for your support. 
I will be happy to assign this to you.
Before you proceed, please share the strategy/ technology you plan to use for this issue.

Also, this task can be broken down into many pieces. Can you suggest a list of tasks so we can track the progress better and consider splitting the work among multiple contributors?

**Comment by martinez-hugo** [comment]
Hi @yuval-hazaz and thanks for your trust !

For this project, I suggest to use Lingui (npm package) and Translation.io (translation manager).
Translation.io are free for Open Source with just one condition : to be sure to to mention Translation.io in our public README file, is it possible for Amplication ?

Lingui support good monorepo project. We will have one lingui.config.js file at root and then one more inside each package folder which extend the root file.

So, in operationally words, I suggest to proceed as this : 
1. Initialization of Lingui
- Installation of package + creation and settings of lingui.config.js (root)
- Updating babel.config.js
- Installing ESLint Lingui Plugin

2. Extending Lingui on 1 first test package to check if all process is good
- Creation and settings of lingui.config.js inside package folder
- Message extraction inside package

3. Testing this 1 package translation on Translation.io

If all is good we can iterate on other package.

Are you ok with this process ?

This is official docs about this 2 tools : 
- Lingui : https://lingui.dev/
- Translation.io : https://translation.io/

If we launch that, what will be the first language priority ? French ? Spanish ?
On test time, I think it's better to test on one language only.
