### ISSUE TITLE
🐛 Bug Report: Roles section- Should be a + icon instead of a whole input

### ISSUE THREAD

**Issue by MatanAmplication** [amplication/amplication#2345]
### What happened?

When adding more Roles into the system, the search input stays on top and is not very useful when having lots of roles, also when having lots of roles, it forces me to go all the way down in order to create another role.
<img width="1437" alt="Screen Shot 2022-02-22 at 10 21 33" src="https://user-images.githubusercontent.com/93521174/155092524-9048c7d6-8205-4895-babc-2a965577950e.png">

in this scenario, I can use the search input in order to look for other roles.
<img width="723" alt="Screen Shot 2022-02-22 at 10 26 45" src="https://user-images.githubusercontent.com/93521174/155092691-2054bf51-cf75-44c8-a37f-2f8c1442be92.png">

### What you expected to happen

add a plus (+) icon in the top of the column in order to make it easier to add more roles

### How to reproduce

.

### Amplication version

11.3

**Comment by MatanAmplication** [comment]
or even a sticky + on top

**Comment by mshidlov** [comment]
Thank you @MatanAmplication, @alexbass86 what do you say?

**Comment by alexbass86** [comment]
> Thank you @MatanAmplication, @alexbass86 what do you say?

I don't see an issue with the current state, @MatanAmplication please explain to me with more details
