### ISSUE TITLE
App - New Project Screen - UI/UX

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2347]
Redesigning the first page our users land on and make it easier for them to understand what each option give

- [x] Research
- [x] UX / UI
- [x] Detailed design
- [x] Conclusions
- [x] Handoff (if needed)

**Comment by alexbass86** [comment]
@yuval-hazaz Please review both options and let me know what you think.
https://www.figma.com/file/dGkhhCfG8ielBxuKQSKOZl/APP---Start-New-Project?node-id=111%3A6742

**Comment by alexbass86** [comment]
@yuval-hazaz please update

**Comment by yuval-hazaz** [comment]
I liked #2 but you can decide based on the feedback you received from everyone and then open an issue in amplication/amplication with the details

This will not be part of 10-issues-10-shirts since it is too big to start with

**Comment by muhsinkamil** [comment]
Hey @yuval-hazaz, Are the requirements finalised for this ? If so, please assign to me. Would love to take up this :heart:

**Comment by yuval-hazaz** [comment]
@muhsinkamil yes! you can take it.
@alexbass86 will provide the latest design files and you can start

**Comment by alexbass86** [comment]
@muhsinkamil Hello, here is the link for the new design feel free to contact me if you have any questions :)
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=16%3A3154
GOOD LUCK!

**Comment by yuval-hazaz** [comment]
@alexbass86 the prototype is not working as expected (it shows the project card instead of the actual design)

**Comment by alexbass86** [comment]
> @alexbass86 the prototype is not working as expected (it shows the project card instead of the actual design)

fixed

**Comment by MoFoGo** [comment]
@alexbass86 I'm not sure the following is clear

![image](https://user-images.githubusercontent.com/96979533/160279402-f979c8a1-5ddb-43b1-9d2b-ee3262ff77ef.png)

I would suggest changing the text. Currently, it could be understood to mean that the Node.js is generated automatically once you load the CSV file.

I would suggest as follows:

Just upload an Excel or CSV file to import its schema, and then generate your node.js application source code.

**Comment by alexbass86** [comment]
> @alexbass86 I'm not sure the following is clear
> 
> ![image](https://user-images.githubusercontent.com/96979533/160279402-f979c8a1-5ddb-43b1-9d2b-ee3262ff77ef.png)
> 
> I would suggest changing the text. Currently, it could be understood to mean that the Node.js is generated automatically once you load the CSV file.
> 
> I would suggest as follows:
> 
> Just upload an Excel or CSV file to import its schema, and then generate your node.js application source code.

Love it. Good job! @MoFoGo 
I just updated it
![B](https://user-images.githubusercontent.com/96179897/160279982-ef9f2e81-eba6-4daf-957b-9d2045fdb7c9.png)

**Comment by MoFoGo** [comment]
@mshidlov - do we know in what release this will be included?

**Comment by muhsinkamil** [comment]
@alexbass86 prototype link seems broken again. 

- Could you please check it. 
https://www.figma.com/proto/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?page-id=16%3A3154&node-id=1%3A2131&viewport=401%2C48%2C0.37&scaling=min-zoom&starting-point-node-id=16%3A4832

- Also, could you please review B3 in figma and confirm if the text should be changed to "Just upload an Excel or CSV file to import its schema, and then generate your node.js application source code." there as well.

Thank you


<img width="1329" alt="Screenshot 2022-03-28 at 6 00 50 PM" src="https://user-images.githubusercontent.com/62111075/160398328-61a7d580-f577-4d1d-bb9e-2f42350cec80.png">

**Comment by yuval-hazaz** [comment]
@muhsinkamil about light mode - if you use the correct theme variables in CSS the light mode should work fine. We are not managing the design system of the light mode any longer to save redundant work. 
So, once you complete the work, let us know so we will review the results on the light mode and if needed will give you comments

**Comment by muhsinkamil** [comment]
@yuval-hazaz I see, understood ! Thank you. 

@alexbass86 The background of "Start from scratch" in [Figma](https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=163%3A4153) is a gif. Should we add it as gif or to animate with svg or image ?
If to animate, Can I get an image to add.

**Comment by alexbass86** [comment]
> @yuval-hazaz I see, understood ! Thank you.
> 
> @alexbass86 The background of "Start from scratch" in [Figma](https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=163%3A4153) is a gif. Should we add it as gif or to animate with svg or image ? If to animate, Can I get an image to add.
> 
> **Edit:** Do we need a left and bottom bar in create screen as seen in [Figma B screen](https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=163%3A4044) ? We could possibly get left bar but bottom bar is very specific to the application that the user uses at any point in time. Since at the "Create app" screen, user does not have any info about the app, Do we still need bottom-bar 🤔 @yuval-hazaz @alexbass86
> 
> Also, from our app architecture point of view, `Last commit` ( bottom bar component ) needs `application id `to be specified, which is just not possible before creating app ? 🤔

gif at this point attached both gifs

![sample](https://user-images.githubusercontent.com/96179897/160776880-be160cd1-eb87-434d-bc56-14c3e279dfeb.gif)

![clean](https://user-images.githubusercontent.com/96179897/160776855-5104df67-0c55-4c17-b4d3-590b4f82291b.gif)

**Comment by alexbass86** [comment]
> @alexbass86 Thank you ! Could you please fix the prototype link, would be much helpful ❤️ 🙏

Yes sorry for the delay, let me know if that works for you
https://www.figma.com/proto/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?page-id=16%3A3154&node-id=163%3A4044&viewport=397%2C48%2C0.36&scaling=min-zoom&starting-point-node-id=163%3A4044
make sure you don't use the prototype to get the code, use the working file
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=163%3A4044

**Comment by muhsinkamil** [comment]
@alexbass86 What happens on clicking "More info" on upload excel option ?

<img width="830" alt="Screenshot 2022-04-02 at 5 53 42 PM" src="https://user-images.githubusercontent.com/62111075/161383150-ba67d05e-c830-4a48-930f-3becb00fd04d.png">

**Comment by yuval-hazaz** [comment]
@muhsinkamil that should link to a doc on our docs site. 
since the doc does not exist yet, you can remove the link for now.
@MoFoGo please add a task on your list to create the missing doc and after that we will be able to add the link from the app into the doc
