### ISSUE TITLE
Separate Git Functionality from `@amplication/server` to `@amplication/git-service`

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2363]
Separation of Concerns is one of the key principles of software architecture that makes it easier to design, build and maintain scalable applications. In practice, it means that each piece of software has a single, clearly defined role that is distinct from another piece of the system.

As the first step in the way of separating `@amplication/server` and separating functionality to dedicated services, we are going to separate git-oriented functionality to a dedicated service `@amplication/git-service`.

All API's that are git-oriented like connecting and disconnecting a repository shell be moved to `@amplication/git-service`.
`@amplication/git-service` will include `gitRepository` and `gitOrganization` operations.

This effort should include the following tasks:
- [x] #2462
- [x] #2476
- [x] #2477
- [x] #2478

**Comment by yuval-hazaz** [comment]
@mshidlov we need to update the details on this issue based on our recent talk

**Comment by morhag90** [comment]
@Yes of course
