### ISSUE TITLE
🐛 Bug Report: screen is cutting the gif

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#2365]
### What happened?

the sticky nav bar cuts off the gif design
<img width="1311" alt="Screen Shot 2022-02-27 at 17 18 20" src="https://user-images.githubusercontent.com/8940907/155890300-02da623f-c551-408e-8f0f-48a2a517aa95.png">

### What you expected to happen

be responsive to the screen size

### How to reproduce

.

### Amplication version

11.3

**Comment by mshidlov** [comment]
@MatanForU Thank you for reporting this issue
