### ISSUE TITLE
🐛 Bug Report: Sorting issue 

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2366]
### What happened?

When we generate the server for the users we giving them a orderBy dtos.
the order by dto we generate is an object but prisma require an array (in able to know which sort is first)

![WhatsApp Image 2022-02-23 at 15 45 37](https://user-images.githubusercontent.com/61761153/155892740-73acc142-985f-44a3-9a4d-e0cdaa33c220.jpeg)

### What you expected to happen

We need to generate an orderBy as an array

### How to reproduce

generate an app and go to one of the entities find many args dto

### Amplication version

0.11.4

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@mshidlov this should be a candidate for 12.1
