### ISSUE TITLE
Prebuild hook / Postbuild hook

### ISSUE THREAD

**Issue by kwinyyyc** [amplication/amplication#2369]
### Feature description

Would like to see if it is possible to run some scripts before or after committing the entity changes.

Possible parameters for prebuild hooks
- `PendingChange[]`

Possible parameters for postbuild hooks
- Files that get generated after build

### Use case

Case 1.
run `graphql-code-gen`
Run the graphql code gen script after build so that it generates updated type definition which I use for my UI application

Case 2
Run some custom script to generate a custom "search" endpoint for all entities.
Currently, the default `GET` api doesn't return the child object.
So we manually create a "search" endpoint for every entity that simply returning related entity rather than just returning the id field

```
const results = await this.service.findMany({
      ...args,
      include: {
        user: true, // Return all fields
        lastModifiedBy: true,
        createdBy: true,
      },
    });
```

**Comment by yuval-hazaz** [comment]
Thanks @kwinyyyc 
about the 2nd use case - we have plans to add custom endpoints from Amplication so you can easily add new endpoints with custom parameters and return types.

Knowing that this is going to be a separate feature, can you think of another use case to use the post generation hook?

**Comment by kwinyyyc** [comment]
@yuval-hazaz 
That's great, that covers the most important use-case

Another use case could be running linter and prettier but currently I am not doing that for amplication generated app.
This use case and 1st use case can more or less do manually, that just result in another commit.

Can't think of other use-case right now.

**Comment by yuval-hazaz** [comment]
@kwinyyyc please see this RFC with details about the plugin system we are working on
https://github.com/amplication/amplication/discussions/2634

**Comment by yuval-hazaz** [comment]
I also added a link from the RFC to this issue. for now I will close this issue and we will keep tracking progress on the RFC and new backlog items for the implementation tasks
