### ISSUE TITLE
🐛 Bug Report: Roles can't be deleted

### ISSUE THREAD

**Issue by molaycule** [amplication/amplication#2370]
### What happened?

Roles added can't be deleted

### What you expected to happen

I should be able to delete a role that is no longer needed or mistakenly created

### How to reproduce

When user add a role, there is no delete button to remove that role.

### Amplication version

0.11.4

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by molaycule** [comment]
@yuval-hazaz is there a way to know the roles or keep track of the roles that are actively used for entity permission, so that such roles can't be deleted only roles created by mistake or inactive roles can be deleted.

**Comment by yuval-hazaz** [comment]
this issue still requires a design - deleting a role has impacts that need to be carefully considered. 
We should keep this issue open for future reference
