### ISSUE TITLE
Docs: Permissions and roles in the generated app

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2372]
### Describe the issue with documentation

The docs are missing details on the permissions and roles in the generated app

* The built-in User entity
* The built-in Roles field
* Roles page
* Entity Permissions tab (enable/disable, all roles/ granular, specific fields...)
* Include in Search
* Public end-points

### How to solve the problem

Add the missing doc/s

**Comment by MoFoGo** [comment]
See https://github.com/amplication/docs/issues/107#issue-1160626442

The permission and roles information will be included in the restructured section, currently titled **Your First Application**
