### ISSUE TITLE
Upgrade to Apollo Server 3

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2375]
### What happened?

Apollo Server 3 introduced new graphql sandbox: 
https://www.apollographql.com/docs/apollo-server/testing/build-run-queries/ 
https://www.apollographql.com/docs/studio/explorer/explorer/#account-free-sandbox

On this version, it is easier to build queries and understand the schemas and the types.

According to nest.js documentation, we first need to upgrade the @nestjs/graphql on data-service-generator to version>=9
and we may add @nestjs/apollo^10 (which we are not using right now)
https://docs.nestjs.com/graphql/quick-start#installation

### What you expected to happen

I expect to get the new Apollo Server graphql sandbox

### How to reproduce

Generate an app, follow the instruction: to run the environment (https://docs.amplication.com/docs/getting-started/dev-env), go to localhost:3000/graphql and see the old version of Apollo server playground

### Amplication version

0..11.4

### Environment

node version 14.17.0
npm version 7.3.0
macOS

### Are you willing to submit PR?

Yes I am willing to submit a PR!

- [x] #2394
- [x] #2395

**Comment by theamanbhargava** [comment]
@souravjain540 Can I work on this please?

**Comment by yuval-hazaz** [comment]
done
