### ISSUE TITLE
🐛 Bug Report: width of the create repository popup is changing when error is shown

### ISSUE THREAD

**Issue by amitbarletz** [amplication/amplication#2385]
### What happened?

After choosing an organization and clicking on create new repository button, type one letter and move the focus outside of the textbox - an error message will show, and the width of the popup is changed.

![image](https://user-images.githubusercontent.com/101094117/157209292-a2feca00-599b-454f-adb2-582724cfa0f3.png)

![image](https://user-images.githubusercontent.com/101094117/157209329-acd0c35e-4219-4bc2-b125-6fba8121b177.png)

### What you expected to happen

The width of the popup should be stable

### How to reproduce

click on github icon on the left side
chose your organization
click on new repository button
type 1 letter and click on Tab
observe the change in the width

### Amplication version

12.0.0

### Environment

node version 14.17.0
npm version 7.3.0
macOS

**Comment by jainpawan21** [comment]
Hi @souravjain540 and @amitbarletz
I would like to work on this.
Can you please assign this to me?

**Comment by souravjain540** [comment]
sure @jainpawan21
