### ISSUE TITLE
🐛 Bug Report: create new repository popup shows error message on first keystroke

### ISSUE THREAD

**Issue by amitbarletz** [amplication/amplication#2386]
### What happened?

error message on the first keystroke

![image](https://user-images.githubusercontent.com/101094117/157209447-1e16867f-0148-415b-bfd2-3110c245582d.png)

### What you expected to happen

The error message should appear on blur

### How to reproduce

click on github icon on the left side
chose your organization
click on new repository button
start typing
see the error meesage

### Amplication version

12.0.0

### Environment

node version 14.17.0
npm version 7.3.0
macOS

**Comment by muhsinkamil** [comment]
@amitbarletz I can look into it, if you haven't already did so 😆 
Please assign to me
