### ISSUE TITLE
Add option to create Global/Common Enums. 

### ISSUE THREAD

**Issue by hmiiro** [amplication/amplication#2392]
### Feature description

Amplication should have a way to create  common enums to re-use an existing enum other than generating a new one for each entity even if the enums have the same values. 

### Use case

For example one field that is common to most entities is say status and values are Active and Inactive. But if u use the option-set datatype, you end up with 20 different enums like 
enum EnumProjectStatus {
  Active
  Inactive
}, 
EnumPaymentStatus {
  Active
  Inactive
}..etc etc

desired behaviour:

enum Status {
  Active
  Inactive
}

**Comment by yuval-hazaz** [comment]
@all-contributors please add @hmiiro for ideas

**Comment by souravjain540** [comment]
@mshidlov are we working on it?

**Comment by yuval-hazaz** [comment]
It should stay open in the backlog

**Comment by hmiiro** [comment]
Is there any feedback or progress on this please?

**Comment by arielweinberger** [comment]
I am a doubtful about the usability of this feature for our wide range of users.

In reality, it is very rare that a single `enum Status {}` will serve the purpose of multiple entities in the mid/long term, and in fact can add complexity and limitations as naturally entities and services evolve and require more specific statuses (e.g. `ARCHIVED`, `PENDING` etc), in which case a common enum like this does not scale.

**Comment by hmiiro** [comment]
> I am a doubtful about the usability of this feature for our wide range of users.
> 
> In reality, it is very rare that a single `enum Status {}` will serve the purpose of multiple entities in the mid/long term, and in fact can add complexity and limitations as naturally entities and services evolve and require more specific statuses (e.g. `ARCHIVED`, `PENDING` etc), in which case a common enum like this does not scale.
> 
> The current situation of having distinct enums seems reasonable to me (especially considering the effort to implement the suggested change, versus the amount of interest we have received).

Understandable!
