### ISSUE TITLE
Upgrade `@amplication/server` to Apollo Server 3

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2395]

**Comment by souravjain540** [comment]
@mshidlov is this relevant?

**Comment by souravjain540** [comment]
@mshidlov is this relevant?

**Comment by yuval-hazaz** [comment]
@mshidlov @tupe12334 isn't that something we already did?

**Comment by tupe12334** [comment]
I see that we did it already see file ```packages/amplication-server/package.json```
