### ISSUE TITLE
Database First - connect to existing DB

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2397]
### Feature description

Add an option to import the data models from an existing DB schema.

### Use case

A developer has an existing DB with or without data and they want to use Amplication to create a service on top of the DB. 
The developer should be able to connect to the database to import its schema to automatically generate all the entities in Amplication based on the database schema. 

### Spec 

Usually, the database will not be available for access from the Amplication server either because it is behind a firewall, or permissions cannot be provided, or it is on a local machine. 

We can use Amplication CLI to allow the user to run the CLI on any machine with access to the DB.  This way the user will also not be required to provide the credential to any remote server. 

The CLI will be able to read the schema from the DB and send it to the Amplication server to create the entities. 

After Amplication generates the code for the backend, the developer will be able to update the connection string in order to run the generated app with their database. 

- [x] #4290

**Comment by souravjain540** [comment]
@yuval-hazaz is this a priority for engg team or this is supposed to be done by community?

**Comment by yuval-hazaz** [comment]
should stay open in the backlog

**Comment by GreenMachine01** [comment]
**Notes from Kickoff:**
Support import of Prisma Schema into Amplication
Provide info or tool to help with extracting Prisma Schema from existing user DB

Info - https://www.prisma.io/docs/concepts/components/introspection
