### ISSUE TITLE
Epic: Custom API Endpoints 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2398]
### Feature description

The APIs generated by Amplication (REST/ GraphQL) include all CRUD operations for the entities and related entities. 

In most real-life cases, the CRUD operations are not enough and the developer of the application will be required to add more endpoints/ queries/ mutations.

Today, we allow the developer to add custom code to the resolvers/ controllers in order to add new endpoints/ queries/ mutations. But using this way will still require the developers to handle all the boilerplate code for the custom endpoints - e.g. authentication, authorization (roles), logging, filtering. 

It would be very beneficial for the developer to be able to create custom endpoints in Amplication which will automatically generate all the code, and the developer will only be required to write the business logic for the operation.

**Comment by souravjain540** [comment]
@yuval-hazaz still relevant?

**Comment by yuval-hazaz** [comment]
shoudl remain open in the backlog

**Comment by Mingyang-Li** [comment]
Correct me if I'm wrong, but I believe we can already add custom business logic while not breaking the default CRUD endpoints/resolvers by extending CRUD operations from the `/base` folder of each DB entity. Is this issue still relavent? @yuval-hazaz

**Comment by yuval-hazaz** [comment]
@Mingyang-Li, you are correct. You can add custom endpoints and business logic by extending the existing services and controllers. 
This feature request is about the ability to add custom endpoints to the API directly from Amplication, so instead of creating the entire code from scratch, Amplication will generate the skeleton of the API including the routing and all necessary decorators for the developers.
So, I believe we should still keep this feature request open on our backlog for future implementations
