### ISSUE TITLE
🐛 Bug Report:  Error in UI behavior. When role is applied to  a field it jumps to the top of the list. 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2401]
### What happened?

When setting the permissions specific to a field, when selecting a role for a particular field in the second or lower position, it jumps to the top of the list - for no reason. 

In the following example, when the role **Contributor** is selected for the **updatedAt** field (in the bottom row) it jumps to the top row. 

1.
![Web capture_9-3-2022_164353_app amplication com](https://user-images.githubusercontent.com/96979533/157464605-c8dea58b-24ef-4d6a-91fd-caa9c5a3799b.jpeg)

2.
![Web capture_9-3-2022_164445_app amplication com](https://user-images.githubusercontent.com/96979533/157464766-6130be83-a61b-4311-ae96-925eb86aedf6.jpeg)

### What you expected to happen

The row should not have moved its position. 

### How to reproduce

Select an entity, select **Permissions**, select **Granular**, select **+ Add Field** (add several fields), set **Roles** to any field in the list (not the first row).

The field row with the selected role jumps to the first row position. 

### Amplication version

0.12.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
Sure, best of luck @muhsinkamil :)
