### ISSUE TITLE
Design System alignment - Main Issue

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2402]
### Feature description

To be consistent in the dev and UI/UX, we need to update our assets according to the new Design System.
here are all the elements we need to align using the design system:

- [x] #2403
- [x] #2404
- [x] #2405
- [x] #2406
- [x] #2407
- [x] #2408
- [x] #2409
- [x] #2410

### Use case

Single source of truth for the team involved in product creation. 
It will allow us to design, develop and maintain the quality of the product.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@alexbass86 I will close this issue and the rest of the issues in the family - and we will handle it separately
