### ISSUE TITLE
Design System Task - Inputs

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2403]
Please update all our inputs in the app to be aligned with our design system.
[**Figma Link**](https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=8%3A432)

**Comment by MichaelSolati** [comment]
The figma link isn't public, so new contributors don't have a reference 😢

**Comment by alexbass86** [comment]
@MichaelSolati Please give me your email. I will add you to our "10 issues 10 shirts" project on figma

**Comment by NisanAyash** [comment]
Can I take this issue?

**Comment by souravjain540** [comment]
> Can I take this issue?

@alexbass86 please see if you can assign him this issue.

**Comment by alexbass86** [comment]
> Can I take this issue?

Good luck :)

**Comment by ishubham21** [comment]
Please assign me this

**Comment by souravjain540** [comment]
Best of luck @ishubham21 !

**Comment by yuval-hazaz** [comment]
@souravjain540 please talk to @barshimi abougvthia issue first. I know there is a larger project going on and it is better to be aligned with him before making progress here

**Comment by yuval-hazaz** [comment]
@alexbass86 I will close this issue and the rest of the issues in the family - and we will handle it separately
