### ISSUE TITLE
Design System Task - Buttons

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2405]
Please update all our buttons in the app to be aligned with our design system.
[**Figma Link**](https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=0%3A1)

**Comment by tupe12334** [comment]
I'm adding a todo list
- [ ] Colors
- [ ] Sizes
- [ ] States

**Comment by yuval-hazaz** [comment]
@alexbass86 I will close this issue and the rest of the issues in the family - and we will handle it separately
