### ISSUE TITLE
Design System Task - Typography

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2408]
Please update all our Font sizes to match the design system. 
We made some significant changes and reduced the amount of variation we currently have to the minimal amount possible, making it more consistent and helping us make the design process much faster.
[**Figma Link**](https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=288%3A5612)

**Comment by yuval-hazaz** [comment]
@alexbass86 I will close this issue and the rest of the issues in the family - and we will handle it separately
