### ISSUE TITLE
Design System Task - Dropshadow

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2410]
Please update all our drop-shadow effects in the app to be aligned with our design system.
[**Figma Link**](https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=357%3A8546)

**Comment by MichaelSolati** [comment]
_If_ this is open for the public to try to help with I think some sort of screenshot would be helpful. The figma link seems to be private, so I'm not sure what it's supposed to look like.

**Comment by alexbass86** [comment]
@MichaelSolati Hi :)
here is the code coming from Figma for the shadow style

box-shadow: 0px 44px 40px -24px #090B144D;
or
box-shadow: 0px 44px 40px -24px rgba(9, 11, 20, 0.3);

let me know if that's help

**Comment by souravjain540** [comment]
Hello @MichaelSolati :)

**Comment by innub** [comment]
Hey, if this issue is unassigned, I would love to pick this up.

**Comment by souravjain540** [comment]
> Hey, if this issue is unassigned, I would love to pick this up.

Sure!

**Comment by innub** [comment]
There seems to be several different types of box shadows specified in amplication-design-system + other custom ones scattered throughout the app. Do I unify all the colors but keep the pixels offsets? 
I got access to the Figma via [this comment](https://github.com/amplication/amplication/issues/2403#issuecomment-1067649978), but the Dropshadow page is rather vague.

**Comment by jainpawan21** [comment]
Hi @innub Are you still working on this?

**Comment by yuval-hazaz** [comment]
@alexbass86 I will close this issue and the rest of the issues in the family - and we will handle it separately
