### ISSUE TITLE
🐛 Bug Report: button has a drop down but it doesn't function as drop down

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#2411]
### What happened?

it has a dropdown, but opens a modal
<img width="1692" alt="Screen Shot 2022-03-09 at 18 25 30" src="https://user-images.githubusercontent.com/8940907/157485800-16bf2ad1-b6f3-44cf-a865-127c96827f7f.png">

### What you expected to happen

or cancel the dropdown icon or put a dropdown.

### How to reproduce

.

### Amplication version

0.12

**Comment by mshidlov** [comment]
@MatanForU Thank you for reporting this issue @alexbass86 can you add design for this

**Comment by Ash-KODES** [comment]
Can i work on this?
@souravjain540

**Comment by souravjain540** [comment]
> Can i work on this? @souravjain540

yes, sure! have a good time working on it.

**Comment by souravjain540** [comment]
Are you working on it? @Ash-KODES

**Comment by Lucarnosky** [comment]
Hi, can I be assigned to this task?

**Comment by Ash-KODES** [comment]
I will be making a pr in 2 days,if not done you can definetly work on it:)

**Comment by Lucarnosky** [comment]
Is just that after a week of silent for a simple task I've tought you were not working on it.

**Comment by souravjain540** [comment]
Thanks for your PR @Lucarnosky

**Comment by Lucarnosky** [comment]
@souravjain540 Glad to contribute

**Comment by souravjain540** [comment]
hey @Lucarnosky , the email mentioned in your bio is the right one to contact you?

**Comment by Lucarnosky** [comment]
@souravjain540 Yes it is
