### ISSUE TITLE
🐛 Bug Report: The dropdown icon is shown incorrectly

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2412]
### What happened?

The arrow icon in our dropdown field is in the wrong place. 
It should be on the right side.

Currently, it is on the left side like this:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/96179897/157485876-0d294e8f-94b9-4e1a-85d2-311cbc7cec42.png">

### What you expected to happen

It should be on the right side:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/96179897/157486058-fabc3a49-40fa-44e6-815c-542eed838c2b.png">

Figma link
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1%3A4515

### How to reproduce

Click on the GitHub icon on the side menu, and it will probably happen in all places where we have a dropdown/select button.

### Amplication version

0.11.2

### Environment

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jainpawan21** [comment]
Hi @mshidlov,
I would like to work on this, Can you please assign this to me?

**Comment by yuval-hazaz** [comment]
@jainpawan21 yes you can. 
Please note that this control is in @amplication/designs-system so before you make the change please remember that it may impact multiple places. 

best way to approach would be to add an optional parameter with the position of the icon (left/right) with the default in current place, and use the other value for the specific location where we need to make the change currently
