### ISSUE TITLE
🐛 Bug Report: "Change repo" button leads me to select repo page instead to the select repo modal.

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#2414]
### What happened?

this button leads me to 
<img width="1990" alt="Screen Shot 2022-03-09 at 18 26 18" src="https://user-images.githubusercontent.com/8940907/157486574-33832b7c-2979-4fb1-85c1-7666ee5d12a3.png">

but then, it leads me back to
<img width="1992" alt="Screen Shot 2022-03-09 at 18 48 25" src="https://user-images.githubusercontent.com/8940907/157489739-59353ff3-028b-4daf-8ce1-a032908e36a0.png">

### What you expected to happen

it should lead me back to
<img width="1991" alt="Screen Shot 2022-03-09 at 18 49 14" src="https://user-images.githubusercontent.com/8940907/157489956-c4df10e5-b898-4720-b258-bdfe55b7eba3.png">

instead of reselecting again 

### How to reproduce

.

### Amplication version

0.12

**Comment by yuval-hazaz** [comment]
thanks @MatanForU 
This behavior is by design to allow the user to use the option to create a repo instead of selecting an existing one.

There is another issue open asking to change the text on the button to "Disconnect" to better describe the action
