### ISSUE TITLE
🐛 Bug Report:  Many-to-many relationship entity with merging of generating entity names causes problems in Deployment

### ISSUE THREAD

**Issue by EdroViegas** [amplication/amplication#2420]
### What happened?

I have entity Teams that Own a lot of services, so I created TeamServices, but that caused  Deploy to fail without much additional information.
![Captura de ecrã 2022-03-10, às 12 40 57](https://user-images.githubusercontent.com/21107004/157906405-99c9df5d-cbcf-4879-ae7c-f296a187a7a9.png)

### What you expected to happen

I was trying to create a table generated by a many to many relationship, I created it using the join of the names of the tables that generate.

I was expecting to have the pivot table created  joining the names  , like Team has many to many relation with Services , then I was expecting to have success creating TeamService entity .

### How to reproduce

Go to entities and create two that are many related to many and then create a third entity with the junction of the names of the entities that generated it and for example Team and Service , the generated table would be TeamService .

TeamService field Team and Service , where:
 Team : One 'TeamService' can be related to one 'Team'
 Service : One 'TeamService' can be related to one 'Service'

TEAM  ENTITY

![Team](https://user-images.githubusercontent.com/21107004/157914278-0a4ecda4-4c7b-4530-af1a-31a7a2c1c650.png)

 
SERVICE ENTITY
![Service](https://user-images.githubusercontent.com/21107004/157915172-b79762af-620b-4bdd-a288-1c92e3a114e5.png)

GENERATED ENTITY TEAMSERVICE (Each image shows the selected relation , one for Team and other for Service)
![TeamService](https://user-images.githubusercontent.com/21107004/157915072-184682af-ba7e-4b98-a4ae-2d8577620283.png)

![TeamServiceTeam](https://user-images.githubusercontent.com/21107004/157915092-b7723cec-6135-401f-bc62-4f61933ae305.png)

### Amplication version

0.12.0

### Environment

Node Version : 17.5.0
NPM Version: 8.4.1

**Comment by abrl91** [comment]
Hi @EdroViegas, can you please add screenshots of your 3 entities from Amplictaion dashboard? It would be very helpful

**Comment by abrl91** [comment]
discord thread: https://discord.com/channels/757179260417867879/951445834803855390

**Comment by yuval-hazaz** [comment]
@tupe12334 
IIUC from your reply on discord - the error is related to the name of the entity which uses the word "Service"?

If that is the case, let's check the exact conditions which cause it to fail. 
Can we use the word "Service" at all?
IS the problem happen only when the entity name ends with the word "Service"?
What if the entire name of the entity is "Service"?

Please note: 
There is already a way to block usage of reserved names here `packages/amplication-server/src/core/entity/reservedNames.ts` - but it only checks for the entire name.

**Comment by yuval-hazaz** [comment]
@all-contributors please add @EdroViegas for bug report

**Comment by EdroViegas** [comment]
![Captura de ecrã 2022-03-14, às 11 49 33](https://user-images.githubusercontent.com/21107004/158157668-f9dfdaba-2adc-4eb7-8fbc-c07f325b47b4.png)

Iam going to change my Service Entity name for something else ... The project is working perfectly in Sandbox but not on my machine , gives the error above (Image) .

**Comment by souravjain540** [comment]
Hey @yuval-hazaz, can you look into it

> ![Captura de ecrã 2022-03-14, às 11 49 33](https://user-images.githubusercontent.com/21107004/158157668-f9dfdaba-2adc-4eb7-8fbc-c07f325b47b4.png)
> 
> Iam going to change my Service Entity name for another. The project is working perfectly in Sandbox but not on my machine , gives the error above (Image) .

**Comment by tupe12334** [comment]
@EdroViegas Are you still encounter this problem?

**Comment by yuval-hazaz** [comment]
we can close this issue, it was already fixed in a previous version
