### ISSUE TITLE
🐛 Bug Report: info popup state is always open after clicking

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2423]
### What happened?

when a user clicks on the info icon (?) it stays open even after he clicks on one of the options.

![image](https://user-images.githubusercontent.com/39680385/158058083-32c24fc1-37d2-446f-b502-250172e841bd.png)

### What you expected to happen

I accept that this popup will get closed on clicking outside and when a user clicks on one of the options

### How to reproduce

open Amplication dashboard and click on the (?) info button

### Amplication version

12.0.0

### Environment

node v16.3.0
npm v7.15.1
macOS

**Comment by GaneshSonarSD** [comment]
can i take this @souravjain540

**Comment by ParkourKarthik** [comment]
I would like to pick this up.

**Comment by GaneshSonarSD** [comment]
> can i take this @souravjain540

i am using windows is it ok

**Comment by souravjain540** [comment]
> > can i take this @souravjain540
> 
> i am using windows is it ok

can you reproduce the issue?

**Comment by GaneshSonarSD** [comment]
> 

how can i do that can you help

**Comment by GaneshSonarSD** [comment]
> > > can i take this @souravjain540
> > 
> > 
> > i am using windows is it ok
> 
> can you reproduce the issue?

yes ill do it

**Comment by GaneshSonarSD** [comment]
yes thank you @souravjain540

**Comment by poposki317** [comment]
Can I try to fix this?

**Comment by souravjain540** [comment]
Hey @GaneshSonarSD, are you working on this?

If not I can assign this to other members.

**Comment by GaneshSonarSD** [comment]
yes working on it.....

**Comment by GaneshSonarSD** [comment]
> Hey @GaneshSonarSD, are you working on this?
> 
> If not I can assign this to other members.

yup working on it @souravjain540

**Comment by GaneshSonarSD** [comment]
> Hey @GaneshSonarSD, are you working on this?
> 
> If not I can assign this to other members.

please assign this to other member @souravjain540

**Comment by abrl91** [comment]
> Can I try to fix this?

@poposki317 you can work on it :)

**Comment by souravjain540** [comment]
Hello @poposki317, are you working on it?

Can we help you in some way? We would love to help you!

**Comment by souravjain540** [comment]
Hey @salindae25, do you want to work on this issue?

This is a part of 10 Issues for First timers, submitting PR for this will give you an exclusive merch from Amplication.

**Comment by salindae25** [comment]
> Hey @salindae25, do you want to work on this issue?
> 
> This is a part of 10 Issues for First timers, submitting PR for this will give you an exclusive merch from Amplication.

@souravjain540  I would love to give it a try.

**Comment by souravjain540** [comment]
Thanks for your PR @salindae25  :)

**Comment by souravjain540** [comment]
hey @salindae25, the email mentioned in your bio is the right one to contact you?

**Comment by salindae25** [comment]
Hi @souravjain540, yes that is my personal one.
