### ISSUE TITLE
ra-data-graphql-amplication package.json alignment

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2425]
### Feature description

We need to update the packages in the package json file of the ra-data-graphql-amplication to match the packages of ra-data-graphql-simple

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mshidlov** [comment]
@tupe12334 as part of the dependency updates let's make sure that the generated `Admin-UI` dependencies are updated as well and that we are solving the dependency issues we encountered lately.
