### ISSUE TITLE
🐛 Design: App Screen - Empty State

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#2430]
### Feature description

We need to replace our current "no app" screen attached to the one we currently have

![image](https://user-images.githubusercontent.com/53312820/158169284-0f78efbd-1136-4ec9-bf08-98b921fcfd60.png)

This is what we want it to be:

![image](https://user-images.githubusercontent.com/53312820/158169324-f19c96bb-8cb5-47dc-822a-a772d05f4f3c.png)

The image:
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1%3A2096

**Comment by yuval-hazaz** [comment]
@souravjain540 please get the new image from Alex and attach it to this issue

**Comment by alexbass86** [comment]
@souravjain540 Here the img
![empty-state](https://user-images.githubusercontent.com/96179897/158322498-9d2890aa-fc4d-438d-aaf3-fee29e6fffcc.png)

**Comment by alexbass86** [comment]
@souravjain540 Here is the img for the empty stat
![empty-state](https://user-images.githubusercontent.com/96179897/158322977-cebeeb1b-5af4-4e88-aed5-354c927018f3.png)
e

**Comment by alexbass86** [comment]
@souravjain540 Please use this link to download the SVG img
i prefer svg not png
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1%3A2096

**Comment by rkshaw20** [comment]
Can I take this one?

**Comment by souravjain540** [comment]
> Can I take this one?

Have a good time working on it.

**Comment by rkshaw20** [comment]
Thanks Brother

**Comment by souravjain540** [comment]
Are you working on it? @rkshaw20

**Comment by Sairam022** [comment]
I think @rkshaw20 already working on it?

**Comment by rkshaw20** [comment]
Yes, I am working on it.
 @souravjain540

**Comment by souravjain540** [comment]
Hey @rkshaw20, are you still working on it?

Can we help you in someway?

**Comment by souravjain540** [comment]
> I think @rkshaw20 already working on it?

Checking it, will assign you it in few hours if he is not working :)

**Comment by Sairam022** [comment]
Ok

**Comment by rkshaw20** [comment]
> 

Everything is done, facing issue while placing the img in center of the page. Code is correct but don't know what's the issue. I will try to fix it by today evening.

**Comment by souravjain540** [comment]
> > 
> 
> Everything is done, facing issue while placing the img in center of the page. Code is correct but don't know what's the issue. I will try to fix it by today evening.

Great! You can ask for help anytime in discord in the (support) channel. We will love to help you

**Comment by souravjain540** [comment]
Thanks for your PR @rkshaw20

**Comment by rkshaw20** [comment]
Thanks for giving me the opportunity to contribute to open-source.
