### ISSUE TITLE
Improve `README`s

### ISSUE THREAD

**Issue by MichaelSolati** [amplication/amplication#2432]
### Describe the issue with documentation

For a complete newbie to this project it's hard to tell how the different packages relate to each other. For example, in order to use the client you also need to be running server (it seems like), but the README in the client doesn't tell you that.

### How to solve the problem

I think the README in the root should list all the different packages with a one line synopsis and link to the associated README's. Also if one package depends on another, such as client requiring server, it should be stated and again, link to the README.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@abrl91 can you please share the chart you created with @MoFoGo 
We should create a packages diagram and explain the relations of all the packages

**Comment by abrl91** [comment]
@MichaelSolati 
@yuval-hazaz You made me share  a spoiler for my tomorrow's meeting with Michael 🙈 

![IMG_1778](https://user-images.githubusercontent.com/39680385/161530931-b57ab881-f2b0-4812-83c3-95bad129863c.jpg)

**Comment by yuval-hazaz** [comment]
looks good
@alexbass86 please prepare a styled design from this. 
You can have a chat with @abrl91  to arrange it properly for design, maybe even create a few different charts

**Comment by MoFoGo** [comment]
> @alexbass86

Any estimate of when this diagram will be done

**Comment by alexbass86** [comment]
> > @alexbass86
> 
> Any estimate of when this diagram will be done

I will try to finish it by end of the week, max mid-next one

**Comment by yuval-hazaz** [comment]
We need to make sure we use standards of how this type of chart should look like
also, the whiteboard @abrl91 created includes several charts that can be created separately.

@abrl91 let's schedule a time to review it together before @alexbass86 is starting to work on it

**Comment by MoFoGo** [comment]
> We need to make sure we use standards of how this type of chart should look like also, the whiteboard @abrl91 created includes several charts that can be created separately.
> 
> @abrl91 let's schedule a time to review it together before @alexbass86 is starting to work on it

@yuval-hazaz Any progress with this?
