### ISSUE TITLE
Ten Issues For First Timers

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#2435]
### Feature description

# 10 Issues For First Timers 👕

 

Hello contributors 👋

 

As proud members of the open-source community, we inspire developers to contribute to open-source projects 💜

To help you get started we have found 10 issues for first-time contributors, that can be a great way to fire-start your journey of the open-source contribution.

By giving back to the community, you’re also getting a chance to win cool **limited-edition** swag.

For each PR that will get merged by a new contributor, we will reward each one of them with our **unique** Amplication T-shirt!

 

⚠️ The rules are simple:

- This activity applies only to the issues listed as “10-issues-for-first-timers”
- Only new contributors to Amplication are entitled to receive T-shirts
- Each new contributor can solve up to (1) one issue and can get up to (1) one T-shirt
- Only the person assigned by Team Amplication will be considered as a valid contributor
- This activity is on a “first come first serve” basis

# Issues 💯

| Issue                                                                                                                                | Description                                                           |
| ------------------------------------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |
| <a href="https://github.com/amplication/amplication/issues/2423"><img src="https://img.shields.io/badge/2423%20-bug-green.svg"/></a> | info popup state is always open after clicking. |
| <a href="https://github.com/amplication/amplication/issues/2217"><img src="https://img.shields.io/badge/2217%20-bug-green.svg"/></a> |New Issue Template - typo.|
| <a href="https://github.com/amplication/amplication/issues/2385"><img src="https://img.shields.io/badge/2385%20-bug-green.svg"/></a> | Fix the unstable width of popup comes when error is shown while creating a new repository. |
| <a href="https://github.com/amplication/amplication/issues/2430"><img src="https://img.shields.io/badge/2430%20-feat-blue.svg"/></a> |Update the design of "no-app" screen by the new image. |
| <a href="https://github.com/amplication/amplication/issues/2431"><img src="https://img.shields.io/badge/2431%20-bug-green.svg"/></a> | Menu background color is not visible on the default page background. |
| <a href="https://github.com/amplication/amplication/issues/2388"><img src="https://img.shields.io/badge/2388%20-bug-green.svg"/></a> | user generated controller tests missing types. |
| <a href="https://github.com/amplication/amplication/issues/2387"><img src="https://img.shields.io/badge/2387%20-bug-green.svg"/></a> |Use `HttpStatus.NOT_FOUND` enum instead of `404` in controller test.|
| <a href="https://github.com/amplication/amplication/issues/2411"><img src="https://img.shields.io/badge/2411%20-bug-green.svg"/></a> |Button has a drop down but it doesn't function as drop down.|
| <a href="https://github.com/amplication/amplication/issues/2241"><img src="https://img.shields.io/badge/2241%20-bug-green.svg"/></a> |Create a single issue template that will include instructions and a link to open the issue.|
| <a href="https://github.com/amplication/amplication/issues/2019"><img src="https://img.shields.io/badge/2019%20-bug-green.svg"/></a> |Disabled input has an hover state behaving.|

**Comment by 0xsapphir3** [comment]
Can I take the fourth one :eyes:

**Comment by souravjain540** [comment]
> Can I take the fourth one 👀

So nice of you :) But Rule No- 2. Only for new contributors!

**Comment by 0xsapphir3** [comment]
Sad, well no problem :smile:

**Comment by souravjain540** [comment]
> Am I considered a first time contributor ? Am not in contributor list 😜

Sorry for that. I will add you to the list of contributors ❤️

**Comment by Ash-KODES** [comment]
Please add me in:)
@souravjain540

**Comment by jainpawan21** [comment]
Hi @souravjain540, 
I would like to work on [3rd](https://github.com/amplication/amplication/issues/2385) issue
Can you please assign that issue to me?

**Comment by souravjain540** [comment]
> Can i take second issue

sure!

**Comment by souravjain540** [comment]
> Please add me in:) @souravjain540 8th issue

Comment there!

**Comment by souravjain540** [comment]
> Hi @souravjain540, I would like to work on [3rd](https://github.com/amplication/amplication/issues/2385) issue Can you please assign that issue to me?

comment on that issue.

**Comment by Dhoni77** [comment]
Can I work on #2411

**Comment by Sairam022** [comment]
Any issue left to work on or everything solved

**Comment by souravjain540** [comment]
> Any issue left to work on or everything solved

you can try #2430

**Comment by souravjain540** [comment]
> Any issues left to work on or is the one above the last one? Thanks.

Hey @RepeaterCreeper, you can work on #2388

**Comment by souravjain540** [comment]
> Can I work on #2411

Yes please leave a comment on that issue and I will assign it to you.  🤝

**Comment by hiteshpatwari** [comment]
@souravjain540 could you please add me to the contributors list.

**Comment by souravjain540** [comment]
> @souravjain540 could you please add me to the contributors list.

Have you worked on any issues?

**Comment by Sairam022** [comment]
So everythig solved or anything left to work?

**Comment by souravjain540** [comment]
> So everything solved or anything left to work?

#2388 is still pending :) You can work on it.

**Comment by Holajuwon** [comment]
> > So everything solved or anything left to work?
> 
> #2388 is still pending :) You can work on it.

HI @souravjain540 is this still pending, can I work on it?

**Comment by souravjain540** [comment]
> > > So everything solved or anything left to work?
> > 
> > 
> > #2388 is still pending :) You can work on it.
> 
> HI @souravjain540 is this still pending, can I work on it?

Yes please comment in #2388 once and I will assign it to you.

**Comment by Holajuwon** [comment]
> > > > So everything solved or anything left to work?
> > > 
> > > 
> > > #2388 is still pending :) You can work on it.
> > 
> > 
> > HI @souravjain540 is this still pending, can I work on it?
> 
> Yes please comment in #2388 once and I will assign it to you.

I have done that.

**Comment by dortam888** [comment]
Hello @souravjain540.
Any issue is still pending or can you recommend another issue that is good for first time? 
Really looking forward to donate it looks like a great project :)
Thanks in advance.

**Comment by souravjain540** [comment]
> Hello @souravjain540. Any issue is still pending or can you recommend another issue that is good for first time? Really looking forward to donate it looks like a great project :) Thanks in advance.

#2388 is still pending :)
