### ISSUE TITLE
Git Pull Service: sync changes from remote repositories

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2437]
Create a service called `@amplication/git-pull-service` for pulling changes from remote repositories.

`@amplication/git-pull-service` will subscribe to a queue containing `repository-push` events. The `repository-push` events represent a developer's (client)  past action of pushing changes to a repository on GitHub (or in the **future** any other vendor).

`repository-push` event data include:
- **provider:** Git Provider Enum (String)
- **owner:** the name of the git account that the repository is part of (String)
- **repository:** the name of the repository (String)
- **branch:** the branch name that received the push event (String)
- **commit:** the push commit head (String)
- **push_at:** timestamp of the origin push action (String -Timestamp)
- **installation_id:** the integration id for the git provider (String)

When an event is received, the service should clone the repository if it is the first time we are pulling the changes and pull the changes if we already did a clone before. The repository files should be saved to a local drive on `git-remote/[provider]/[owner]/[name]/[branch]/[commit]` (The local drive shell be mapped to provisioned volume on the Kubernetes level using EFS on the cloud infra).

To avoid conflicts with distributed usage and support a history of version changes will implement a mechanism of changes window.

Each `repository-push` event will trigger a pull operation that will copy the last commit version and perform a `git pull` operation on it.

Once finished with the process, the service will try and clean the oldest commit folder from the storage drive.

For synchronization and updates, the service should use a postgress database with repository pull events tracking table.
the table should contain:
- **id:** UUID
- **provider:** String
- **owner:** String
- **name:** String
- **branch:** String
- **push_at:** Timestamp
- **status:** String
- **created_at:** Timestamp
- **updated_at:** Timestamp

The service should update the table according to the progress to allow shared storage usage.

The service should use a logger and log the progress of the operation for trace, monitoring, and overall service visibility.

**Service flow diagram:**
![Blank diagram (1)](https://user-images.githubusercontent.com/91742238/158433659-0cf61e17-9625-4fc1-8a9b-5cbc6bae134b.png)

- [x] #2463

- [x] #2464
- [x] #2465
- [x] #2466

**Comment by abrl91** [comment]
@mshidlov What about assets? Should I clone images and videos too?

**Comment by mshidlov** [comment]
Currently, we should pull only code. so images, videos, and other assets should be excluded

**Comment by yuval-hazaz** [comment]
@mshidlov few comments:
1. I think we should call the service differently not to be confused with "pull requests", or even git "pull" (although this is exactly what we are doing in the service, in addition to clone). How about "git-sync" or "git-sync-remote" or "git-fetch-changes"? any other ideas?
2. Since it is a new DB, I think this is a good opportunity to use numbers for IDs as you wanted before.
3. are we listening just for "push" events? what about commits that are done directly on the remote repo?
4. I understand this service is generic and should get the params from the queue, but should we listen just to a specific branch for events? should we let the user select which branch?

**Comment by mshidlov** [comment]
1. Any one of the above is fine by me.
2. OK
3. I believe that direct commits are performing push behind the scenes, but in case this is e different webhook it can be handled on the service that will process the webhooks. this service is not aware of the event source.
4. that answer is similar to 3 this should be part of the service that will process the webhooks.

The service that will process the webhooks will have to:
- validate the webhook received for authentication token
- validate that the repository and the branch are tracked by us (we have a repository defined is our DB)
- create a push event message with data from the event received and data from our DB (installation id)
- sending the push event message to a queue

for now, my plan is to listen by default only to main\master and to keep the specific branch logic for the future when it will be needed (it may or may not depends on our needs) but this is an open discussion and we can think on more use cases and our future needs.

**Comment by abrl91** [comment]
@mshidlov I'm tagging you to review if I understood you.
We talk about adding indices for the database table:
1. pushed_at
2. combined index of: provider + ownerName + repositoryName

for 'looking good' press 👍  otherwise leave a comment :)

**Comment by abrl91** [comment]
Filter files' size <= 250KB
