### ISSUE TITLE
🐛 Bug Report: unnecessary dependencies in generate admin-ui

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2441]
### What happened?

When we generate an app for the user we give him in the admin-ui package.json several unnecessary dependencies:
- graphql-tag (we have it as a dep of @apollo/client
- typescript (needs to move to devDeps)
- gql (we have it via the @apollo/client)

### What you expected to happen

not relevant

### How to reproduce

not relevant

### Amplication version

0.12.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Hap-i** [comment]
@souravjain540 please assign it to me.

**Comment by souravjain540** [comment]
> @souravjain540 please assign it to me.

Sure @Hap-i !

Join our discord if you need any help in solving the issue!
