### ISSUE TITLE
🐛 Bug Report: Usage of hard coded RGB color value instead of  css variable 

### ISSUE THREAD

**Issue by jainpawan21** [amplication/amplication#2451]
### What happened?

I see there are a few places we are using hard-coded RGB color values
We should use CSS variables to avoid re-work when we need to change some color

### What you expected to happen

We should use CSS variables for color values

### How to reproduce

See one example in this file:-
`packages/amplication-client/src/Application/git/dialogs/GitCreateRepo/GitCreateRepo.scss`
at line no. 22 we are using hardcoded color value.

### Amplication version

0.12.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
Thanks!
l will assign this issue to you
