### ISSUE TITLE
Docs: The page headings are not formatted consistently 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2457]
Current situation: The headings are sometimes sentence case and sometimes title case. We should be consistent. 

Change required: Change the title for each topic  to Title Case (each word starts with an upper case letter).

**Comment by Shubh28698** [comment]
Hi @MoFoGo @souravjain540 

Can I take up this issue? 

Thanks

**Comment by Shubh28698** [comment]
Also if assigned, can you let me know which page needs the change ( sending page link here would be helpful) 

Thank you

**Comment by souravjain540** [comment]
> Also if assigned, can you let me know which page needs the change ( sending page link here would be helpful) 
> 
> Thank you

Hey @Shubh28698 sure! Assigned.

@MoFoGo please help him.

**Comment by MoFoGo** [comment]
Hi, @Shubh28698.  You should go through all the docs, and see where the Title in the sidebar is different from the Title in the article. 
Here are a few examples:
https://docs.amplication.com/docs/about/roadmap
https://docs.amplication.com/docs/helm-chart
https://docs.amplication.com/docs/how-to/create-entity-field
https://docs.amplication.com/docs/getting-started/getting-started/phone-home
https://docs.amplication.com/docs/about/roadmap

Don't worry about making the title in the sidebar very long.

**Comment by MoFoGo** [comment]
Hi, @Shubh28698.  Will you be dealing with this?

**Comment by yuval-hazaz** [comment]
I hope you are well now 🙏

**Comment by Shubh28698** [comment]
> I hope you are well now 

Yes I am doing well. Thanks a lot for asking. I would like to contribute actively & aggresively to amplication. 

Thank you✌

**Comment by yuval-hazaz** [comment]
great! looking forward to that. 
Feel free to reach out on our Discord server to get the Contributor role and chat with the team (in case you didn't already)

http://amplication.com/discord

**Comment by Shubh28698** [comment]
Is this PR fine?

**Comment by Shubh28698** [comment]
> great! looking forward to that. 
> Feel free to reach out on our Discord server to get the Contributor role and chat with the team (in case you didn't already)
> 
> http://amplication.com/discord
> 

I had joined the discord community. Can you please let me know how can I assign contributor role to myself? 

Thanks!

**Comment by souravjain540** [comment]
> > great! looking forward to that.
> > Feel free to reach out on our Discord server to get the Contributor role and chat with the team (in case you didn't already)
> > http://amplication.com/discord
> 
> I had joined the discord community. Can you please let me know how can I assign contributor role to myself?
> 
> Thanks!

Hi, I will assign it to you!
