### ISSUE TITLE
Docs :  Improve description of  Relation to Entity data type.

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2458]
Also, the Owner field description does not mention the dialog that opens following the selection of the Relation to Entity data type. 

![image](https://user-images.githubusercontent.com/96979533/158066761-d57e5082-1422-4ce7-ba43-dd8772a71399.png)

_Originally posted by @MoFoGo in https://github.com/amplication/docs/issues/113#issuecomment-1066124104_

**Comment by yuval-hazaz** [comment]
@MoFoGo can you please split this issue into 2 separate issues?
