### ISSUE TITLE
Docs: Add an article about GitHub sync including the schema hierarchy 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2459]
the doc will explain how we install the GitHub App on the organization or personal account - and how it maps to a workspace. 
Also. how all apps in the workspace can use the same app, each app with a different repo.

How you can add multiple apps to a workspace

Also, have a look at this issue - 
https://github.com/amplication/amplication/issues/2396

we need to explain how org admin can sign in to Amplication to install the GitHub app and allow users without permissions to the org still use the installed app on specific repos

**Comment by lukaskwkw** [comment]
Also how to make it working with local env. How to setup i.e. https://smee.io and how to fill all .env properties like GITHUB_APP_INSTALLATION_URL  etc.
