### ISSUE TITLE
Docs: Reformat the GitHub Sync articles 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2460]
1. Rearange the two articles related to the GitHub Synchronization next to each other on the navigation sidebar.

https://docs.amplication.com/docs/sync-with-github
https://docs.amplication.com/docs/connect-server-to-github

2. Update the _Connect Server_ to GitHub app article to remove references to "new" 
3. Correct the formatting for paths in _Connect Server to GitHub app_

**Comment by hiteshpatwari** [comment]
I can submit a pr for this one.

**Comment by souravjain540** [comment]
Hey @hiteshpatwari! I've asked @MoFoGo about it. Wait for his reply then I'll assign it to you if he agrees :)

**Comment by souravjain540** [comment]
Okay, @MoFoGo has completed this issue already and PR is in review by him!

@hiteshpatwari you can work on another issue. There are many open issues that needs an awesome developer like you ;)

You can check it here - https://github.com/amplication/amplication/issues

**Comment by yuval-hazaz** [comment]
@MoFoGo is this still open?

**Comment by souravjain540** [comment]
> @MoFoGo is this still open?

no, he has submitted a PR

**Comment by yuval-hazaz** [comment]
so we need to close the issue
