### ISSUE TITLE
git pull service - flow and logics

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2465]
1. Build the flow:
queue => controller listen and get the event data => trigger the git-pull service => clone and pull logic
=> (git client, git provider) => manage DB and storage
    (`git-remote/[provider]/[owner]/[name]/[branch]/[commit]`)
    
2. Add logger

**Comment by abrl91** [comment]
was merged

**Comment by mshidlov** [comment]
merged in #2548
