### ISSUE TITLE
Docs: Remove mention of translation in Contributing Article 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2467]
https://docs.amplication.com/docs/contributing

The opening paragraph includes translation as one of the ways a contributor can contribute.

This is false, so the word translate should be deleted.

**Comment by souravjain540** [comment]
Hey @MoFoGo, can I work on this?

**Comment by MoFoGo** [comment]
> Hey @MoFoGo, can I work on this?

Sure @souravjain540

**Comment by yuval-hazaz** [comment]
@souravjain540 are you working on this?

**Comment by souravjain540** [comment]
> @souravjain540 are you working on this?

yes :)

**Comment by souravjain540** [comment]
PR : https://github.com/amplication/docs/pull/129
