### ISSUE TITLE
Add note that the Sandox is removed after 30 days 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2473]
Need to add the the docs a note that the Sandbox is removed after 30 days

**Comment by trishitapingolia** [comment]
Can you mention where do you need this note in docs. I want to contribute to this issue.

**Comment by yuval-hazaz** [comment]
Thanks for your interest to contribute to Amplication.
This issue is not longer relevant and we can close it. 
Please let us know if you see anything else you can work on and we would be happy to assign it to you
