### ISSUE TITLE
Poor quality screen shots in Docs

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2474]
The screen captures in the Docs are of poor quality. Also, the detail is very small
We need to find a solution for:
1. Better quality images
2. Focusing on the required part of the screen (without always showing the whole screen)

**Comment by alexbass86** [comment]
@MoFoGo can i close this issue?

**Comment by MoFoGo** [comment]
@alexbass86 - let's keep it open because I still need to make the changes in the docs. I will unassign you.

**Comment by alexbass86** [comment]
Please close this issue if it's not relevant any longer @MoFoGo

**Comment by MoFoGo** [comment]
No longer relevant
