### ISSUE TITLE
`@amplication/server` Phone-Home

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2486]
### Feature description

To help the Amplicaion team understand and be more aware of `@amplication/server` usage a notification event should be added on server load.

The loading event should not include any private personal data.
The event should include only:

- Build version
- Server version
- Runtime environments (OS, node version, ...)

### Use case

When `@amplication/server` is loaded it should send a loading notification message.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MoFoGo** [comment]
@mshidlov - please supply details of how to deactivate the feature.
