### ISSUE TITLE
Conflicting Shortcut: (CMD+SHIFT+P) is new private window on Firefox

### ISSUE THREAD

**Issue by duanecilliers** [amplication/amplication#2489]
I'm not sure if I've somehow got a custom shortcut config, but I don't remember changing it and [found this here](https://balsamiq.com/support/faqs/privatebrowsing/#mozilla-firefox
).

![Screenshot 2022-03-22 at 21 51 30](https://user-images.githubusercontent.com/1135407/159564265-59d72738-a125-4996-beb5-2edefc66a85f.png)
![Screenshot 2022-03-22 at 21 53 56](https://user-images.githubusercontent.com/1135407/159564688-4220d795-0c9c-43fc-ac57-b86ab46ba019.png)

## Expected Behavior
CMD+SHIFT+P opens search

## Actual Behavior
New private browsing window is opened.

## Solutions?
Overide or change shortcut?

**Comment by muhsinkamil** [comment]
Interesting. I am checking this. 
Seems react-command-palette already checks at https://github.com/asabaylus/react-command-palette/blob/main/src/command-palette.js#L90. 
But unfortunately, only works on chrome. I will update the progress here. Most probably we would need to change the shortcut key since the option/func to override is not provided from react-command-palette

**Comment by muhsinkamil** [comment]
Did more digging. 
[React command palette](https://github.com/asabaylus/react-command-palette/blob/main/package.json#L91) internally uses [Mousetrap](https://github.com/ccampbell/mousetrap). And there seems to be an [issue reported at mousetrap](https://github.com/ccampbell/mousetrap) long time back and is still open. 

So our option would be to change the shortcut, I guess. 

@yuval-hazaz How about we change the shortcut to 

- for mac:   cmd + shift + k
- for other: ctrl + shift + k

PS: `ctrl + shift + k` is the shortcut that github uses for command palette 🔍 
I thought of going for `/` but seems `/` opens firefox search 😢

**Comment by duanecilliers** [comment]
Nice work @muhsinkamil

`/` and `cmd + k` is search on https://docs.amplication.com/docs/first-app/ which works in Firefox. I'm guessing the docs isn't using mousetrap.

I think `cmd/ctrl + shift + k` is a decent alternative.

**Comment by muhsinkamil** [comment]
> / and cmd + k is search on https://docs.amplication.com/docs/first-app/ which works in Firefox. I'm guessing the docs isn't using mousetrap.

yes @duanecilliers, docs uses algolia search.

**Comment by souravjain540** [comment]
Hey @duanecilliers and @muhsinkamil 👋 

Thank you so much for taking the time to open an issue.

As far as I see, @muhsinkamil gave a nice alternative.

So, I am closing this issue for now. You can open a new issue anytime. 💜

**Comment by muhsinkamil** [comment]
Hey @souravjain540 The alternative is not implemented though. I was waiting for Yuval's reply. Let me open a PR to it :+1

**Comment by souravjain540** [comment]
Amazing ;)
