### ISSUE TITLE
option to create a private repo when connecting to GitHub

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2490]
### Feature description

Right now, when creating a new repo for the sync with GitHub it is created as public by default. 
We should allow the user to select whether the new repo in Github will be created as private or public

**Comment by jainpawan21** [comment]
Hi @yuval-hazaz ,
I think it can be implemented server-side easily as [Github API](https://docs.github.com/en/rest/repos/repos#create-an-organization-repository) supports private flag
Do we need a design for the client-side or can we add a checkbox or dropdown in creating a new repo popup?

**Comment by yuval-hazaz** [comment]
@jainpawan21 you can add a checkbox to the creation popup
