### ISSUE TITLE
build never gets succeeding 

### ISSUE THREAD

**Issue by karunakerreddyv** [amplication/amplication#2495]
deployment never succeeded for sample app

**Comment by yuval-hazaz** [comment]
thanks @karunakerreddyv 
we are working to expand the capacity on the deployment server. When we are experiencing a very high volume of traffic the cloud services used for the sandbox deployment reach some limits. 

We are in a middle of a migration process to new cloud infrastructure and that will also resolve this issue. 
Until then, users may experience some delays when deploying to the cloud sandbox environment. 

please note that this should not prevent you from downloading the code or pushing it to a GitHub repo and running or deploying the code on your own

**Comment by karunakerreddyv** [comment]
thanks for the speedy response

**Comment by PiggyPlex** [comment]
good luck with everything! and look forward to the future of amplication
