### ISSUE TITLE
Docs: Missing info in ReadMe re running client and server after npm setup 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2496]
### Describe the issue with documentation

The ReadMe does not explain that i n the dev environment, you need to run the server and the client. 
ReadMe is  missing the instructions to run the client and the server after `npm run setup:dev`

### How to solve the problem

Update the ReadMe with the required information

**Comment by MichaelSolati** [comment]
Related to #2432

**Comment by MoFoGo** [comment]
> Related to #2432
 @MichaelSolati - will close this, as is a duplicate of #2432
