### ISSUE TITLE
🐛 Bug Report: ra-data-graphql-amplication user create

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2503]
### What happened?

When we go to the generated admin UI and try to make a new user instance with the same roles it will crash.
The error:
```
{
    "errors": [
        {
            "message": "Variable \"$data\" got invalid value { connect: [\"user\"] } at \"data.roles\"; String cannot represent a non string value: { connect: [\"user\"] }",
            "locations": [
                {
                    "line": 1,
                    "column": 21
                }
            ],
            "extensions": {
                "code": "BAD_USER_INPUT"
            }
        }
    ]
}
```

The source of the error is in the buildVarubles.ts line 373

### What you expected to happen

The user needs to be created with the role

### How to reproduce

Generate an app -> go to the sandbox -> login and create new user

### Amplication version

0.12.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abrl91** [comment]
> @abrl91 Do you have any additional data?

This is not the correct error that appears. The error is Not Found 404

**Comment by tupe12334** [comment]
I'm talking about the network request @abrl91

**Comment by ysfbsf** [comment]
It seems there is an issue with the generated GraphQL request : 

`{
  "where": {
    "id": "cl19sqx2c0000ye2seza4hxvf"
  },
  "data": {
    "roles": {
      "set": [
        "admin",
        "autoEntrepreneur"
      ]
    },
    "username": "admin"
  }
}`

After passing the array of roles directly as value of the **roles** attribute, this query seems working:

`{
  "where": {
    "id": "cl19sqx2c0000ye2seza4hxvf"
  },
  "data": {
    "roles": [
        "admin",
        "autoEntrepreneur"
      ],
    "username": "admin"
  }
}`

**Comment by abrl91** [comment]
> It seems there is an issue with the generated GraphQL request, that doesn't seem to like passing a **set** object of the roles: 
> 
> 
> 
> `{
> 
>   "where": {
> 
>     "id": "cl19sqx2c0000ye2seza4hxvf"
> 
>   },
> 
>   "data": {
> 
>     "roles": {
> 
>       "set": [
> 
>         "admin",
> 
>         "autoEntrepreneur"
> 
>       ]
> 
>     },
> 
>     "username": "admin"
> 
>   }
> 
> }`
> 
> 
> 
> After passing the array of roles directly as value of the **roles** attribute, this query seems working:
> 
> 
> 
> `{
> 
>   "where": {
> 
>     "id": "cl19sqx2c0000ye2seza4hxvf"
> 
>   },
> 
>   "data": {
> 
>     "roles": [
> 
>         "admin",
> 
>         "autoEntrepreneur"
> 
>       ],
> 
>     "username": "admin"
> 
>   }
> 
> }`
> 
> 

Thanks @ysfbsf we already fixed. In the upcoming release you will be able to create and update users.

**Comment by abrl91** [comment]
@tupe12334 this bug is not related to amplication/amplication. 
I opened a bug report and PR on amplication/ra-data-graphql-amplication about this issue. I think you can close this issue :)

**Comment by yuval-hazaz** [comment]
@abrl91 we want to track all issues in this repo, including issues related to the other repos. 
we should implement the issue template we use in the docs in all other repos

**Comment by abrl91** [comment]
@yuval-hazaz 
so the following issue and the issue that was tagged on this issue's description resolved it
https://github.com/amplication/amplication/pull/2528

May I close this issue?

**Comment by abrl91** [comment]
https://github.com/amplication/amplication/pull/2528 solved it
