### ISSUE TITLE
Duplicate step in first-app documentation

### ISSUE THREAD

**Issue by rienheuver** [amplication/amplication#2519]
### Describe the issue with documentation

Bullet point 6 of step 5 of the "Your first application" documentation seems duplicate of bullet 5, just worded slightly differentyl and less clear than bullet 5:
https://docs.amplication.com/docs/first-app/#set-entity-permissions

### How to solve the problem

Seems to me like bullet 6 can be removed. And I believe people in discord agree:
https://discordapp.com/channels/757179260417867879/781089015548870695/958041908574306345

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MoFoGo** [comment]
resolved
