### ISSUE TITLE
🐛 Bug Report: Material-UI: the createMuiTheme function was renamed to createTheme.

### ISSUE THREAD

**Issue by rienheuver** [amplication/amplication#2520]
### What happened?

When running the code generated by Amplication, it will throw the following error in your browser console when running the admin app:
```
index.js:1 Material-UI: the createMuiTheme function was renamed to createTheme.

You should use `import { createTheme } from '@material-ui/core/styles'`
```

My UI looked really weird as well. Looks to me like a package was updated but someone forgot to look at the breaking changes :wink:

### What you expected to happen

No errors to be thrown and the UI to work normally

### How to reproduce

Generated an app by Amplication, run the admin app (without making any changes to the code yourself).

### Amplication version

0.1.4

### Environment

Node: v14.18.1
NPM: 8.5.5.
Docker: 20.10.14
OS:
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
Linux rienheuver-XPS-15 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tupe12334** [comment]
' My UI looked really weird as well. Looks to me like a package was updated but someone forgot to look at the breaking changes 😉 '

@rienheuver can you send a snapshot of what you see wrong with the admin UI

**Comment by rienheuver** [comment]
![image](https://user-images.githubusercontent.com/9960351/160586658-953529aa-2701-4ddd-a914-3ec6cdef9569.png)

![image](https://user-images.githubusercontent.com/9960351/160586774-e5848970-2cd4-4322-85f0-519305e5e94c.png)

For some reason I need to login and logout to see this change.

**Comment by tupe12334** [comment]
@rienheuver Can you elaborate more about you envierment and open a different issue, about that?

**Comment by rienheuver** [comment]
If I'm not mistaken, it happens when you open a fresh project in Amplication, download the code and start the UI. Anyway, what do you want a new issue to be about? Because this issue is about this weird looking UI right? I'm not sure I understand what you mean
