### ISSUE TITLE
🐛 Bug Report: Commit window view just broke

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2526]
### What happened?

![image](https://user-images.githubusercontent.com/96179897/160624266-65552e48-880a-4c82-8b9f-42e1776c4050.png)

The close button should be on top of the text.

### What you expected to happen

![image](https://user-images.githubusercontent.com/96179897/160624747-82d58029-8645-44d3-a49b-50b81eca0791.png)

1. Title should be - 14px bold
2. Commit message box should be more extensive - 130px hight
The number of changes (when none) should be in a grey circle, not yellow. Only when there is a commit (number larger than null) does it changes to yellow
4. delete & compare icons should be white - #ffffff
5. "No pending..." text below the box img should be - 12px #a3a888
6. We should disconnect the button "Commit changes" from the message box

### How to reproduce

.

### Amplication version

0.11.2

### Environment

.

### Are you willing to submit PR?

Yes, I am willing to submit a PR!

**Comment by jainpawan21** [comment]
@souravjain540 
I think this is the file path
`packages/amplication-client/src/VersionControl/PendingChangesBar.tsx`

**Comment by jainpawan21** [comment]
Hi @alexbass86, It will be very helpful if you can share figma link for the same

**Comment by alexbass86** [comment]
> Can I work on this issue? I have a fair idea of these changes

Sure here is the new redesign for commit @jainpawan21 
Figma Public File:
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=267%3A4014

Old Look:
[image](https://user-images.githubusercontent.com/96179897/161053625-ea3b9327-3d97-4fa5-986c-bd980b605d2e.png)

New Look:
[image](https://user-images.githubusercontent.com/96179897/161053731-669f328c-6e25-4758-aad8-51363bcedde4.png)
