### ISSUE TITLE
🐛 Bug Report: Refreshed design for commit section

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2533]
### What happened?

The current commit section looks outdated and not aligned with our new design system. Currently, the button is connected to the message box, which can confuse some users to think that they first need to fill the commit message to commit changes.

Also, we don't have buttons connected to another component in our new design system. It's always separated.

**Old Look:**
![image](https://user-images.githubusercontent.com/96179897/161053625-ea3b9327-3d97-4fa5-986c-bd980b605d2e.png)

**New Look:**
![image](https://user-images.githubusercontent.com/96179897/161053731-669f328c-6e25-4758-aad8-51363bcedde4.png)

**Figma Public File:**
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=267%3A4014

### What you expected to happen

.

### How to reproduce

.

### Amplication version

0.11.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jainpawan21** [comment]
@alexbass86 I think #2526 is the same issue
