### ISSUE TITLE
React Admin is not listed in the technology stack  

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2543]
### Describe the issue with documentation

The list of technologies in this list is missing React Admin
https://docs.amplication.com/docs/getting-started

We should add React Admin under client-side with a link to their web site

https://marmelab.com/react-admin/

**Comment by MoFoGo** [comment]
PR -  ReadMe-update-stack #136

**Comment by souravjain540** [comment]
Hey @MoFoGo 👋 

Is this issue still relevant or should we close it?
