### ISSUE TITLE
🐛 Bug Report:  amplication client apollo link

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2545]
### What happened?

The apollo link in the amplication client is static to the server type deployment, we need to extract the URI property in the create HTTP link function of the apollo server to an env variable.

### What you expected to happen

The data source needs to be dependent on the env

### How to reproduce

not relevant

### Amplication version

0.12.3

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@tupe12334 can you please describe the reason behind this change for future reference.

**Comment by tupe12334** [comment]
@yuval-hazaz This change gives us the option to consume the client data from a different data source.
now we deploy the client throws the server, in the future, we want to make a separation.

**Comment by yuval-hazaz** [comment]
so, to be more precise - it is not about changing the endpoint from /graphql to something else... it is more about using a different domain or subdomain for the client

**Comment by tupe12334** [comment]
@yuval-hazaz you are right
