### ISSUE TITLE
Add docs for /api/_health

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2549]
### Describe the issue with documentation

The generated app includes endpoints for health checks
We should document this feature and explain what is the purpose of these endpoints and how to use it

![image](https://user-images.githubusercontent.com/43705455/161983060-f7f2982a-9a78-47bb-baac-c4fe274e0f3c.png)

**Comment by yuval-hazaz** [comment]
@mshidlov please add the info here so @MoFoGo can create a doc

**Comment by MoFoGo** [comment]
Resloved
