### ISSUE TITLE
Internal server error when pushing changes to github

### ISSUE THREAD

**Issue by Brainchild13** [amplication/amplication#2550]
Hi I was trying out the application to see if i can use it for development, but I am unable to push changes to github despite syncing my account and creating a repo. I have tried several times and different ways, but none of the changes I have made are reflected on github. any suggestions

**Comment by yuval-hazaz** [comment]
Thanks @Brainchild13 
Can you please provide more details? 
Are you getting an error?

**Comment by Brainchild13** [comment]
yes i get an internal server error whenever i try to run the build or push the code to github

**Comment by yuval-hazaz** [comment]
@Brainchild13 sorry for the late response. 
Do you see the error in the code generation step or any other step? can you share a screenshot? 
Also, please share your app ID (from the URL) so we can check the logs for errors

**Comment by souravjain540** [comment]
Hello @Brainchild13 👋 

Can you please share the required details?

We will like to help you in using Amplication.
