### ISSUE TITLE
🐛 Bug Report: GitHub repos list is missing repositories

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2551]
### What happened?

The Github repos list only shows 30 repos and not all the repos of the user. 
With the previous implementation of the GitHub OAuth app, we could not run a search on the server-side so we only returned the top 30 repos but we also sorted the list on the server-side by creation date so the user at least can find the repo they just created.

In the current implementation with GitHub App we should check whether we can run a search on the server-side (on GitHub API) - if so, we should implement a search. 
If not, we should consider adding pagination.

In any case, to make sure most users are not affected we must sort the list of repos by the creation or last update date. Since most if not all users will search for the repo they just created for their app. 

### What you expected to happen

We should sort the list of repos by the last update date

### How to reproduce

use an organization or an account with more then 30 repos and open the repo selection page

**Comment by jainpawan21** [comment]
As Github API supports all these query parameters, So all requirements can be implemented
<img width="604" alt="Screenshot 2022-05-21 at 5 19 26 PM" src="https://user-images.githubusercontent.com/39362422/169650330-a354d47a-926c-4aaf-9d75-b52553bba534.png">

 Do we need a design update to work on this?

**Comment by yuval-hazaz** [comment]
@jainpawan21, no need for a design to start working on it. 
fee free to implement the pagination and @alexbass86 will review and suggested fixes after you finish

Thanks for your continuous support!

**Comment by jainpawan21** [comment]
Hi @yuval-hazaz ,
What options I should give users to change and what options I should hard code?
1. sort
2. direction
3. per_page
4. page
