### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by bogere** [amplication/amplication#2560]
### What happened?

Failed  completely to install some nodejs modules that are needed for the amplication app to run successfully  whether running `npm run dev ` for development purposes or running the` docker-compose up -d or  sudo docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d`  to test the application.
All nodejs modules are installed successfully until this last part which has failed completely whether in development or production mode.
```
Step 17/32 : RUN npm run bootstrap -- --loglevel=${NPM_LOG_LEVEL} --scope @amplication/server --scope @amplication/client --include-dependencies
 ---> Running in 959a759ce7c0

> bootstrap
> lerna bootstrap "--loglevel=notice" "--scope" "@amplication/server" "--scope" "@amplication/client" "--include-dependencies"

lerna notice cli v4.0.0
lerna notice filter including ["@amplication/server","@amplication/client"]
lerna notice filter excluding ["admin-template","server-template"]
lerna notice filter including dependencies
lerna WARN bootstrap Installing local packages that do not match filters from registry
lerna ERR! npm install --no-save exited 1 in '@amplication/container-builder'
lerna ERR! npm install --no-save stderr:
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-05T14_31_56_030Z-debug.log
lerna ERR! npm install --no-save exited 1 in '@amplication/container-builder'
lerna WARN complete Waiting for 6 child processes to exit. CTRL-C to exit immediately.
ERROR: Service 'app' failed to build : The command '/bin/sh -c npm run bootstrap -- --loglevel=${NPM_LOG_LEVEL} --scope @amplication/server --scope @amplication/client --include-dependencies' returned a non-zero code: 1
```

### What you expected to happen

I expected the whole installation process to complete sucessfully but it seems some nodejs packages are missing from your registry and therefore i cannot complete the set up process..
I expect my application to run successfully whether on the linux machine for development or sucessfully in the docker container but that last step of `ERROR: Service 'app' failed to build : The command '/bin/sh -c npm run bootstrap -- --loglevel=${NPM_LOG_LEVEL} --scope @amplication/server --scope @amplication/client --include-dependencies' returned a non-zero code: 1`

### How to reproduce

For development purposes , run 
```
npm install
npm run setup:dev
```
Then  also you can run the production mode or development mode for the docker compose file.
`sudo docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d` or just docker-compose up -d can reproduce the error.

### Amplication version

master branch

### Environment

Node version: 14.17.1
NPM version : 6.14.13
Docker version: Docker version 20.10.2, build 20.10.2-0ubuntu1~20.10.1
Cloud provider : None ( iam using kubuntu desktop ( variant of ubuntu desktop)
OS Details :  Linux.
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
Linux otye-#71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@tupe12334 please review

**Comment by souravjain540** [comment]
@tupe12334  is it still relevant?

**Comment by yuval-hazaz** [comment]
This was resolved already and we can close it
