### ISSUE TITLE
🐛 Bug Report: Incorrect text in GitHub Sync app

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2567]
### What happened?

The marked text Is incorrect: 
 
<img width="354" alt="Screenshot 2022-04-11 150231" src="https://user-images.githubusercontent.com/96979533/162735617-95a0b5f9-10a2-4cb2-9b1a-eac522a55613.png">

### What you expected to happen

It should say **Only selected repositories**

### How to reproduce

Run Github sync app

**Comment by molaycule** [comment]
Hi @MoFoGo, this looks like it from GitHub. See attached image from GitHub Doc. From more information see this link -> https://docs.github.com/en/get-started/customizing-your-github-workflow/purchasing-and-installing-apps-in-github-marketplace/installing-an-app-in-your-personal-account
![marketplace-select-repo-field](https://user-images.githubusercontent.com/20028628/162907690-7192e2c8-e058-407b-88b5-e67960a0f0be.png)

**Comment by tupe12334** [comment]
@MoFoGo this text is not in our control, it's a GitHub issue
