### ISSUE TITLE
Disable amplication sandbox deployment

### ISSUE THREAD

**Issue by KayhanB** [amplication/amplication#2574]
I think sandbox deployment of amplication must be optional. in my case i don't need to amplication sandbox  deployment because i handling all pull requests in my CI/CD pipeline. so I think we need such a development in order to use energy more efficiently.

**Comment by yuval-hazaz** [comment]
Thanks for this suggestion
It sounds very reasonable 
We are working on a few new configurations and this definitely should be included

**Comment by yuval-hazaz** [comment]
Since we removed the sandbox deployment so we can close this issue
