### ISSUE TITLE
🐛 Bug Report: Wrong Color on the notification message for "Small screen."

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2584]
### What happened?

![image](https://user-images.githubusercontent.com/96179897/163420208-c8153d55-b4a2-44ae-bb77-cfa842d61d06.png)

We should change the text color to #FFFFFF. Currently, it's hard to see the message.

### What you expected to happen

The message when the screen is too small should be clear and readable 

### How to reproduce

just shrink the screen width

### Amplication version

0.11.2

### Environment

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by molaycule** [comment]
Hi @alexbass86 can I work on this?

**Comment by yuval-hazaz** [comment]
@molaycule go ahead! 
thanks
