### ISSUE TITLE
🐛 Bug Report: Wrong trash icon placement at the field list screen.

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2585]
### What happened?

![image](https://user-images.githubusercontent.com/96179897/163422582-fb510c09-5c72-4900-b143-3da8e62bc5a6.png)

The delete icon should be on top, the same as in other places, such as the app list.
![image](https://user-images.githubusercontent.com/96179897/163421797-f181b01f-3821-4fa8-99e3-5fd2bca4b86c.png)

### What you expected to happen

To keep everything in our system consistent, we should always place the delete (trash icon) on the top right corner.

### How to reproduce

Go to the field list.

### Amplication version

0.11.2

### Environment

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by rolwin100** [comment]
@alexbass86 can I take this up

**Comment by alexbass86** [comment]
@rolwin100 Sure, thank you for the contribution :)
