### ISSUE TITLE
create `@amplication/logger`

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2593]
Create a shared library for logging and update the services to use the shared library:
* `@amplication/server`
* `@amplication/git-pull-service`
* `@amplication/git-webhook-service`
* `@amplication/git-pull-request-service`

**Comment by tupe12334** [comment]
- [ ] Create the new lib
- [ ] Moving the use to the new lib
- [ ] Remove old deps

**Comment by arielweinberger** [comment]
Closing this. I've created a spec and run it through with @tupe12334, will create a separate issue with details.
