### ISSUE TITLE
`@amplication/client` - App Overview Page

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2594]
Create a new app overview page. this page will be the default page after a new app was created or when an app is selected on the workspace apps list page.

The page [figma](https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=387%3A3699)

Please add the relevant components in the design system.

![image](https://user-images.githubusercontent.com/91742238/163736863-fbe703ea-8028-4d66-a511-6f906f1be867.png)

**Comment by rolwin100** [comment]
@mshidlov can I and take up this feature.

**Comment by CKanishka** [comment]
> @mshidlov can I take up this feature.

Let me know if I can help you in this feature, I am interested

**Comment by rolwin100** [comment]
@mshidlov Can I and @CKanishka work on this together.

**Comment by molaycule** [comment]
> @mshidlov Can I and @CKanishka work on this together.

Hi @rolwin100 can I pair program with you and @CKanishka on this if it gets assigned.

**Comment by rolwin100** [comment]
@molaycule it may become difficult to coordinate for us me and @CKanishka work together as colleagues so it's easy for us to work on. Will let you know if something else comes up.

**Comment by molaycule** [comment]
@rolwin100 Alright, that's fine. Please keep tabs with me. Thanks.

**Comment by rolwin100** [comment]
@yuval-hazaz can you please help me with the updates on this feature so we can start on this.

**Comment by yuval-hazaz** [comment]
@alexbass86 can you please create a public link to the design on Figma?

**Comment by alexbass86** [comment]
> @alexbass86 can you please create a public link to the design on Figma?

@yuval-hazaz I updated Matan "Figma link" with the correct one 
@rolwin100 please use this link
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=387%3A3699
