### ISSUE TITLE
🐛 Bug Report: In-app settings, all screens should be in same structure

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2597]
### What happened?

On some pages, we have a different inner page layout. To be consistent and allow our users to have smoother interaction, we need to make sure we won't have any strange jumps between the section, for example:
**App Settings** here we have an inner padding 
![image](https://user-images.githubusercontent.com/96179897/163811488-30533201-d18c-4e60-9596-6e8a6d06f3c6.png)

While in DB Settings, we dont have any padding
![image](https://user-images.githubusercontent.com/96179897/163811694-21788492-299b-4d07-8be9-74287a7b4eab.png)

The problematic screen currently is DB Settings

### What you expected to happen

We need to make sure all pages in the settings have the same pending as in "App Settings"

### How to reproduce

Just go to App Settings

### Amplication version

0.11.2

### Environment

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by molaycule** [comment]
@alexbass86 can I submit a PR?

**Comment by souravjain540** [comment]
Assigned @molaycule, let us know if you need some help :)

best of luck!

**Comment by molaycule** [comment]
Hi @souravjain540 thanks. I just submitted a PR that might close this issue.
