### ISSUE TITLE
🐛 Bug Report: Unused code in WorkspaceLayout.tsx

### ISSUE THREAD

**Issue by rolwin100** [amplication/amplication#2599]
### What happened?

The graphql query used in line number 90 is not used anywhere can we please remove it if it is not used anywhere.

### What you expected to happen

Please remove line 90 in the file ` https://github.com/amplication/amplication/blob/master/packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx` if it is not used.

### How to reproduce

Please check `WorkspaceLayout.tsx` in the Project

**Comment by CKanishka** [comment]
Can I take this up? @rolwin100

**Comment by rolwin100** [comment]
@CKanishka sure

**Comment by yuval-hazaz** [comment]
@CKanishka I assigned it to you.
you can go ahead.
thanks
