### ISSUE TITLE
Old Screenshots and Text 

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#2600]
### Describe the issue with documentation

1. Old UI screenshot (create an entity, project entity, create the name field, create roles, entity permissions, field permissions, commit changes, task field, pending changes, GitHub repo, get application source code, preview app)
2. Node 14 -> Node 16.13.1 (LTS)
3. preview app -> open in sandbox

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MoFoGo** [comment]
@souravjain540 I don't think this is relevant anymore. Am closing the issue
