### ISSUE TITLE
Add New Micro-Services to Helm

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2601]
We have to create new charts for 3 new services and update the server chart as well.

This update should include creating claims and volumes based on EFS.

- [x] #2605
- [x] #2606
- [x] #2607
- [x] #2608

**Comment by mshidlov** [comment]
@tupe12334 @morhag90 @abrl91 
Please comment for each service what is the expected environment variables and secrets.

**Comment by morhag90** [comment]
@mshidlov=>  For the @amplication/git-push-webhook-service : 
KAFKA_BROKER_IP_ENV_KEY = localhost:9092,localhost:9090
WEBHOOKS_SECRET_KEY = [your webhooks secret key]
KAFKA_REPOSITORY_PUSH_QUEUE = repositoryPush_created

**Comment by abrl91** [comment]
git-pull-service:
```
// for db connection
POSTGRESQL_USER=admin
POSTGRESQL_PASSWORD=admin
POSTGRESQL_PORT=5432
POSTGRESQL_URL=postgres://admin:admin@localhost:5432
COMPOSE_PROJECT_NAME=amplication-git-pull-service

// kafka connection
KAFKA_BROKERS=["localhost:9092"]
KAFKA_CONSUMER_GROUP=git-pull-event
KAFKA_CLIENT_ID=repository-pull
KAFKA_TOPIC="pull.event"

// configurations
NODE_ENV=developement
STORAGE_PATH=
MAX_SNAPSHOTS=
GIT_DEFAULT_ORIGIN_NAME=origin

// github integration
GITHUB_APP_APP_ID=
GITHUB_APP_PRIVATE_KEY=
```

**Comment by mshidlov** [comment]
> @mshidlov=> For the @amplication/git-push-webhook-service : KAFKA_BROKER_IP_ENV_KEY = localhost:9092,localhost:9090 WEBHOOKS_SECRET_KEY = [your webhooks secret key] KAFKA_REPOSITORY_PUSH_QUEUE = repositoryPush_created

@morhag90 what about GH app id, GH app private key, Postgres, etc....

please separate between environments that are public and once that are privates (secrets)

**Comment by tupe12334** [comment]
git pull request and server
```
KAFKA_BROKER_URL_VAR="localhost:9092"
BASE_BUILDS_FOLDER="/Users/ofekgabay/Documents/"

```

**Comment by mshidlov** [comment]
the branch containing the new services release/0.13.0

**Comment by mshidlov** [comment]
![Blank diagram (4)](https://user-images.githubusercontent.com/91742238/168459523-7f89855e-0442-437f-bfd3-ae521837d12a.png)
