### ISSUE TITLE
Need to update the guid for developers environment

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2602]
@MoFoGo => need to update also the guid for developers environment

_Originally posted by @morhag90 in https://github.com/amplication/docs/pull/135#pullrequestreview-941898398_

**Comment by MoFoGo** [comment]
Update https://docs.amplication.com/docs/connect-server-to-github

**Comment by MortensenC** [comment]
I can take this one

**Comment by souravjain540** [comment]
@MoFoGo please assign if available

**Comment by yuval-hazaz** [comment]
> I can take this one

Assigned to you! thanks @MortensenC
