### ISSUE TITLE
create permissions interceptor to handle the permissions 

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2613]
### Feature description

We are handling the permissions now in a way that makes the route handlers massive and less readable.
By creating a permissions interceptor, we can handle the permissions stuff outside the function body and manipulate the returned value according to the user's permission right before sending the result to the client.

https://docs.nestjs.com/interceptors

![image](https://user-images.githubusercontent.com/39680385/164460958-2eb77dbe-fed6-4bbf-b3d0-6630b084f136.png)

### Use case

By using a permission interceptor, we would not only achieve cleaner architecture but also could handle public routes in the feature easily.

As a first step, we will implement a filter result interceptor which would be responsible to read and search operations in REST and Query operations in graphql.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tupe12334** [comment]
@abrl91 Many thanks for posting this image, I learned a lot from it ❤️.
