### ISSUE TITLE
Docs: Troubleshooting Guide for Installation 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2620]
### Describe the issue with documentation

The users require more information about common errors and resolutions for the setup process. 

### How to solve the problem

Create an Installation and setup troubleshooting article to include in the docs.
Incorporate input from the community and core team.

**Comment by MoFoGo** [comment]
See the thread on Discord:

https://discordapp.com/channels/757179260417867879/967072827087937656

**Comment by abrl91** [comment]
First, I think we should separate it into two sections:
1. errors and resolutions for Amplication setup
2. errors and resolutions for generated app

We can divide each section into errors that refer to setups and errors that refer to incorrect use. 
(for instance, missing the documentation guide and forgetting to run `npm run docker:db` and, as a result getting errors from Prisma.

From what I experienced, most of the troubles on Amplication were around 
`npm run setup:dev`
and the solution (at most) was the environment setup such as node version, npm version, and typescript installed globally.

Another trouble was with docker (on the generated app and Amplication itself).

**Comment by MoFoGo** [comment]
Resolved PR Troubleshooting-new-section #142
