### ISSUE TITLE
🐛 Bug Report: The search field is too big in the commit screen

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2629]
### What happened?

Currently, this is how it looks
![image](https://user-images.githubusercontent.com/96179897/164986318-d8172b21-7002-4b44-a7a9-67c5246b9ccd.png)

While it should look the same on all screens
![image](https://user-images.githubusercontent.com/96179897/164986345-e4a80884-3515-401e-b995-28d475c873e9.png)

### What you expected to happen

Every component that we use more than one time should look the same on all pages

### How to reproduce

Go to the commit screen

### Amplication version

0.11.2

### Environment

.

**Comment by souravjain540** [comment]
hey @alexbass86, can I work on this>

**Comment by souravjain540** [comment]
submitted a PR, hope that solves what required @alexbass86 :)
