### ISSUE TITLE
🐛 Bug Report: Create App Screen - Wrong spacing and missing hover effect

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2635]
### What happened?

**The space on this page is not correct, and This is how it currently looks.**
![image](https://user-images.githubusercontent.com/96179897/165262425-67d17092-f53f-4b19-9c81-f8f1b255a56a.png)

**It should look like this.**
![B](https://user-images.githubusercontent.com/96179897/165262662-b5661d3b-8842-44c2-9729-32dcf247bf90.png)

Link for the OG design, where you can also find the correct spacing setting.
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=16%3A3154

Also, on hover, we miss a transition effect. currently, the drop-shadow appears suddenly while it should have a transition effect.
You can find example here:
https://www.figma.com/proto/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?page-id=16%3A3154&node-id=163%3A4044&viewport=401%2C48%2C0.24&scaling=min-zoom&starting-point-node-id=163%3A4044

### What you expected to happen

Spaces & Hover effect should be the same as it is in the design.

### How to reproduce

Click on the "new app" button.

### Amplication version

0.11.2

### Environment

.

**Comment by jainpawan21** [comment]
Hi @alexbass86 
You mean drop-down by hovered state background gif?
What is the exact transition/animation it should have?

**Comment by alexbass86** [comment]
> Hi @alexbass86 You mean drop-down by hovered state background gif? What is the exact transition/animation it should have?

transition ease in 650ms
transition ease out 650ms

**Comment by jainpawan21** [comment]
What do you mean by drop-down?

**Comment by jainpawan21** [comment]
Can you please assign this to me?

**Comment by alexbass86** [comment]
> Can you please assign this to me?

Good luck, and thank you for your time :)
