### ISSUE TITLE
Create `@amplication/code-store-service` - generated code access API

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2639]
create a new service that will give access to the generated code. 
the service should include two APIs:
* **list:** lists the contents of the current app-commit directory.
* **concatenate:** returns the content of a file.

The service is public and can be accessed by the outside world, as such it will include the JWT authorization layer and will check resources access permissions.

the authorization flow should be:
1. verify the JWT access-token
2. send resource access permissions validation message over Kafka topic `authorization.command.can-access-build.0`
3. accept permissions validation reply over Kafka reply topic.

Issue sub-tasks:
- [x]  Create `@amplication/code-store-service` with Amplication
- [x]  Add storage functionality to `@amplication/code-store-service`
- [x]  Create authorization flow in `@amplication/code-store-service`  
- [x]  Add build authorization consumer to `@amplication/server` 

Issue physical design:

LIST API REQUEST:
```
HTTP GET storage/[app-id]/[commit-id]/list?path=packages%2Fserver?per_page=10&page=0
requiered: app-id, commit-id
optional: 
	path - default to root folder
	per_page - default to 20
	page - default to 0
headers:
	Authorized
```
LIST API RESPONSE:
```
content-type: application/json
body: [
  {
     "type": "folder""name": "src"
  },
  {
    "type": "file""name": "package.json"
  }
]
```

CONCATENATE API REQUEST:
```

HTTP GET storage/[app-id]/[commit-id]/concatenate?path=packages%2Fserver%2Fpackage.json
requiered: app-id, commit-id, path
headers:
	Authorized
```
CONCATENATE API RESPONSE:
```
content-type: text/plain
```

![Blank diagram - Page 3](https://user-images.githubusercontent.com/91742238/165378145-0bd60bde-1466-438d-80f8-acaa555303cc.png)

**Comment by yuval-hazaz** [comment]
@mshidlov what is the origin of the word CONCATENATE for the API? is that something common for this type of API? I am not sure if that is a typo or by design?

**Comment by yuval-hazaz** [comment]
@mshidlov are we naming this service storage-api or code-store?
