### ISSUE TITLE
🐛 Bug Report: Sync with GitHub - The dropdown has Unnecessary padding. 

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2643]
### What happened?

This is how it currently looks.
![image](https://user-images.githubusercontent.com/96179897/165519349-69c7262c-fc39-4808-acdc-500f48792e23.png)

and this is how it is supposed to look.
![image](https://user-images.githubusercontent.com/96179897/165519499-2a9b7dcc-25c8-4a56-bb4c-5eb2db32deca.png)

We also need to make sure the text is in the center of the profile pic & arrow icon.
**Bad**
![image](https://user-images.githubusercontent.com/96179897/165519705-dafd5b41-1882-477e-ada0-d54f24684e66.png)

**Good**
![image](https://user-images.githubusercontent.com/96179897/165519727-7ee7ef1c-c49f-41ac-9d35-40a3366a7333.png)

### What you expected to happen

No padding for the drop-down and profile, name, arrow icon aligned 

### How to reproduce

Go to Sync with GitHub screen

### Amplication version

0.12.5

### Environment

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jainpawan21** [comment]
@alexbass86 I worked on one issue related to this drop down in this [PR](https://github.com/amplication/amplication/pull/2531).
I missed this. Can you assign this to me, I will fix this
