### ISSUE TITLE
Code view => new page: client 

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#2665]
### Feature description

In order to show the source code of the app (commits/builds) we need to develop new page : "code view" . 
This page will be a new tab in the app and will contain the following options:

1. connect to Github account
2. choose one of the last 5 commits 
3. Files tree
4. Show for each file the source code in a new tab

Implementation: 

- [ ]  code-view-window (create new component)
    - navigate
    - [ ]  Side-Bar-container (create new component)
    - close/open
        - [ ]  Commits-Dropdown (create new component)
            - get builds
        - [ ]  files-container (create new component)
            - [ ]  Search
            - [ ]  file-component (create new component)
                - get file
            - get files
    - [ ]  Files-component (tabs)
        - [ ]  File-container

### Use case

In order to show the source code of the app (commits/builds) we need to develop new page : "code view" .

**Comment by alexbass86** [comment]
Hi @morhag90 @mshidlov 
Here is the Figma file for the code view feature. If you have any questions feel free to ask
good luck
[Figma](https://www.figma.com/file/a9AGIkvVQ5vqPHB6MHlsZ3/Overview-Screen-%26-Code-view?node-id=762%3A13415)

<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2Fa9AGIkvVQ5vqPHB6MHlsZ3%2FOverview-Screen-%2526-Code-view%3Fnode-id%3D762%253A13049" allowfullscreen></iframe>
