### ISSUE TITLE
🐛 Bug Report: when all the methods are public, there are unused imports of interceptors

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2695]
### What happened?

Unused imports of interceptors when all the methods on controllers and resolvers are public.

### What you expected to happen

imports should be added only if there is a use on interceptors

### How to reproduce

generate a sample app
declare Order entity permissions to be Public in all the actions

### Amplication version

0.12.7

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tupe12334** [comment]
Please check https://ts-morph.com/details/source-files#organizing-imports It will do all the hard work for you.

**Comment by abrl91** [comment]
> Please check https://ts-morph.com/details/source-files#organizing-imports It will do all the hard work for you.
Thank you @tupe12334
