### ISSUE TITLE
[Docs] Minimum system requirements to run project

### ISSUE THREAD

**Issue by jainpawan21** [amplication/amplication#2697]
### Describe the issue with documentation

Minimum system requirements should be mentioned in docs to run the project in the development/local environment

**Comment by MoFoGo** [comment]
@tupe12334  I need the system requirements for the Amplication and for the generated app. 

Currently this is what is documented in the [Server ReadMe](https://github.com/amplication/amplication/blob/master/packages/amplication-server/README.md) 

Development
💡 Before you begin, make sure you have all the below installed:

[Node.js v14 or above](https://nodejs.org/en/download/)
[npm v7 or above](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/)
[Docker](https://docs.docker.com/desktop/)
[Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git/)

**Comment by yuval-hazaz** [comment]
@tupe12334 please provide @MoFoGo  with the details to resolve this issue. 

@MoFoGo please open 2 separate issues - one for the readme file in this repo and another one to update the docs on amplication/docs

**Comment by MoFoGo** [comment]
> @tupe12334 please provide @MoFoGo with the details to resolve this issue.
> 
> @MoFoGo please open 2 separate issues - one for the readme file in this repo and another one to update the docs on amplication/docs

@yuval-hazaz , @suryaraj1 @suryaraj1 -  According to @tupe12334, the info as it is currently in [Server ReadMe](https://github.com/amplication/amplication/blob/master/packages/amplication-server/README.md) is correct for both Server and generated app (Node.js v14 and npm v7).  

I will open an issue to include this in the docs and in the root ReadMe.

**Comment by MoFoGo** [comment]
> @tupe12334 please provide @MoFoGo with the details to resolve this issue.
> 
> @MoFoGo please open 2 separate issues - one for the readme file in this repo and another one to update the docs on amplication/docs

@yuval-hazaz , @suryaraj1 @suryaraj1 -  A @tupe12334 . The info as it is currently in [Server ReadMe](https://github.com/amplication/amplication/blob/master/packages/amplication-server/README.md) is correct for both Server and generated app (Node.js v14 and npm v7).  

I will open an issue to include this in the docs and in the root ReadMe.

**Comment by yuval-hazaz** [comment]
ok, so if all good we can close the issue
