### ISSUE TITLE
Screen Update - Overview Screen & Settings Screen

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2711]
### Feature description

What changed:
**Overview update**
We removed the side menu from the left side from now on the app settings will have their own screen and we added an icon for fast navigation.
![overview main](https://user-images.githubusercontent.com/96179897/167582257-34032dcd-1b66-46dd-b5ba-bf6b9d43d0e5.png)

**Setting Screen**
Settings are moving to their own screen and removing the "Overview" link on the side menu, and we also removed the top banner for a cleaner experience. The fields are now 2 in a row.
![DB Settings](https://user-images.githubusercontent.com/96179897/167582325-ce917251-e49b-4e48-ae2d-e8438fe6e074.png)

**[Figma File](https://www.figma.com/file/PRTEQUaefMZLLyoWooeTpw/Screen-Update---Overview-Screen-%26-Settings-Screen?node-id=572%3A3378)**

### Use case

Reduce the number of items in the overview screen and create a more focused flow by adding fast navigation to the setting at the side menu.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by codeNitesh** [comment]
Hi @souravjain540 ,
Can you please assign this issue to me?

Thanks :)

**Comment by kinb98** [comment]
Hi can I work on this ?

**Comment by souravjain540** [comment]
> Hi can I work on this ?

Just assigned you another issue

**Comment by souravjain540** [comment]
@rolwin100 any updates on this issue?

**Comment by yuval-hazaz** [comment]
@morhag90 you can take this task and implement it together with the app settings changes you are working on. 
please send a separate PR for this that use this branch as base https://github.com/amplication/amplication/pull/2839
