### ISSUE TITLE
Side menu update - Reduce the size of the icon from 32px to 24px

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2712]
### Feature description

Due to the need to have more space on our side menu, we decided to change the size of the icons from 32px to 24px, We also changed the state colors.

**[Figma file](https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=532%3A6541)**

### Use case

To have more space on the side menu

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
Details in the Figma link (also provided above by Alex)
[Figma file](https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=532%3A6541)


<img width="1162" alt="image" src="https://user-images.githubusercontent.com/43705455/168462371-d01fc3b4-2f60-4fbc-9302-693a681a3e9b.png">

**Comment by garvitrai013** [comment]
Is this issue assigned to anyone? If not I'd like to take it

**Comment by ShreyaPrasad1209** [comment]
Hi can I take up this issue?

**Comment by souravjain540** [comment]
> Is this issue assigned to anyone? If not I'd like to take it

Hello @garvitrai013  👋🏻

I am assigning you this issue! 

Have a good time working on it. Limited Edition Amplication SWAG are waiting for your PR 😉

If you need any help just reply to me. We are more than happy to help you in your first PR to Amplication 💜

**Comment by souravjain540** [comment]
> Hi can I take up this issue?

Hello @ShreyaPrasad1209, assigned you the other one :)

**Comment by garvitrai013** [comment]
Thank you Sourav 💙

**Comment by uday03meh** [comment]
Is this issue solved?

**Comment by souravjain540** [comment]
> Is this issue solved?

He is working on it.

You can take #2711

**Comment by garvitrai013** [comment]
I ran the dev setup command (`npm run setup:dev`) in the directory after cloning it & it failed at 2nd stage (client build)

Its related to webpack. I tried installing it locally & also linking it with global webpack and the error is still there.

`
> setup:dev
> ts-node ./script/setup.ts

info: Welcome to Amplication installer!
info: This script will help you easily set up a running amplication server

info: Starting step 1/6
info: Starting Bootstrap
info: Finish Bootstrap

info: Starting step 2/6
info: Starting Client build
info: Finish Client build
Error: Command failed: npm run build -- --scope @amplication/client --include-dependencies
lerna notice cli v4.0.0
lerna notice filter including "@amplication/client"
lerna notice filter excluding ["server-template","admin-template"]
lerna notice filter including dependencies
lerna info filter [ '@amplication/client', '!server-template', '!admin-template' ]
lerna info Executing command in 3 packages: "npm run build"
lerna info run Ran npm script 'build' in '@amplication/data' in 8.2s:
lerna info run Ran npm script 'build' in '@amplication/design-system' in 11.0s:
lerna ERR! npm run build exited 1 in '@amplication/client'
lerna ERR! npm run build stdout:

> @amplication/client@0.12.7 build
> react-app-rewired build

lerna ERR! npm run build stderr:
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './webpack4/file-watcher-api.js'
Require stack:
- D:\Programs\amplication\amplication\packages\amplication-client\node_modules\html-webpack-plugin\lib\file-watcher-api.js
- D:\Programs\amplication\amplication\packages\amplication-client\node_modules\html-webpack-plugin\lib\cached-child-compiler.js
- D:\Programs\amplication\amplication\packages\amplication-client\node_modules\html-webpack-plugin\index.js
- D:\Programs\amplication\amplication\packages\amplication-client\node_modules\react-scripts\config\webpack.config.js
- D:\Programs\amplication\amplication\packages\amplication-client\node_modules\react-app-rewired\scripts\build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Programs\amplication\amplication\packages\amplication-client\node_modules\html-webpack-plugin\lib\file-watcher-api.js:12:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Programs\\amplication\\amplication\\packages\\amplication-client\\node_modules\\html-webpack-plugin\\lib\\file-watcher-api.js',
    'D:\\Programs\\amplication\\amplication\\packages\\amplication-client\\node_modules\\html-webpack-plugin\\lib\\cached-child-compiler.js',
    'D:\\Programs\\amplication\\amplication\\packages\\amplication-client\\node_modules\\html-webpack-plugin\\index.js',
    'D:\\Programs\\amplication\\amplication\\packages\\amplication-client\\node_modules\\react-scripts\\config\\webpack.config.js',
    'D:\\Programs\\amplication\\amplication\\packages\\amplication-client\\node_modules\\react-app-rewired\\scripts\\build.js'
  ]
}
lerna ERR! npm run build exited 1 in '@amplication/client'

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)`

**Comment by souravjain540** [comment]
Hello @garvitrai013 

Please join our discord and ask this in support channel.

One of our team member will help you on priority!

https://discord.gg/qPVPzRvJ

**Comment by souravjain540** [comment]
Hi @garvitrai013 , are you working on this issue?

Can we help in some way?

**Comment by garvitrai013** [comment]
I'm busy with another project currently, will take me lil longer

**Comment by yuval-hazaz** [comment]
@garvitrai013 thanks for taking this,
For now, I will assign someone else to move forward with it. 
if you want to take on other tasks, just let me know

**Comment by souravjain540** [comment]
@uday03meh do you want to work on this issue?

**Comment by aryans1319** [comment]
I would like to work on this issue! @souravjain540

**Comment by souravjain540** [comment]
> I would like to work on this issue! @souravjain540 
> 
> 

Contact me on Discord if you got any issue :) (as we did already)

**Comment by aryans1319** [comment]
Ya, sure :)

**Comment by souravjain540** [comment]
Are you working on it? @aryans1319

**Comment by AayKaay** [comment]
Hi @souravjain540 I would like to take this issue if no one is working on it. Thanks

**Comment by souravjain540** [comment]
> Hi @souravjain540 I would like to take this issue if no one is working on it. Thanks

@AayKaay you are a first time contributor. Right?

**Comment by AayKaay** [comment]
Thank you for assigning this to me. I have started working on this, and sure ill message you if I want any help. Thanks

**Comment by AayKaay** [comment]
hi @souravjain540 I submitted a PR. Please assign a reviewer. Thanks
