### ISSUE TITLE
Workspace dropdown update

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2713]
### Feature description

We are doing a few minor updates to make the workspace selection area more visible.

![Dropdown](https://user-images.githubusercontent.com/96179897/167599979-0feea67b-64e7-42c3-94e9-04227497932d.png)

**[Figma File](https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=534%3A7128)**

### Use case

Currently, the select area feels a bit disconnected. Also, the design is not looking good at the moment, were fixing it :)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
the required changes are detailed in Figma in this link [Figma File](https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=534%3A7128)

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/43705455/168783596-d74057e5-c8ce-4ae0-9bd3-c8b45c16fb01.png">

**Comment by codeNitesh** [comment]
Hi @souravjain540 @yuval-hazaz ,
Can you please assign this issue to me?

Thanks :)

**Comment by souravjain540** [comment]
> Hi @souravjain540 @yuval-hazaz , Can you please assign this issue to me?
> 
> Thanks :)

Hello @codeNitesh  👋🏻

I am assigning you this issue! 

Have a good time working on it. Limited Edition Amplication SWAG are waiting for your PR 😉

If you need any help just reply to me. We are more than happy to help you in your first PR to Amplication 💜

**Comment by codeNitesh** [comment]
hey @souravjain540
I am facing issue while setting up project on my local environment.
The error is related to nodejs version. I installed the required version, but still issue persist. I checked issues section here on this project, but all the discuss related to set up seems not good and productive. I think it is quite important to provide doc with possible bugs and their solutions.
Also, can you please help me with this bug?

Thanks :)

**Comment by souravjain540** [comment]
Hello @codeNitesh 👋 

Can you join our discord server and ask the query in Support channel for a fast resolution?

invite: https://amplication.com/discord

**Comment by souravjain540** [comment]
Hi @codeNitesh 👋 

Any updates? Can we help you in some way?

**Comment by yuval-hazaz** [comment]
hi @codeNitesh let us know if you need any further assistant 🙏

**Comment by codeNitesh** [comment]
Hi @yuval-hazaz 
I am almost done with issue. Will push the code by eod.

**Comment by souravjain540** [comment]
Amazing @codeNitesh 👍

**Comment by souravjain540** [comment]
Any updates @codeNitesh ?

**Comment by codeNitesh** [comment]
Hey @souravjain540 
I have raised query on discord server more than 24 hours ago.
But havan't received any support on the issue yet.

**Comment by souravjain540** [comment]
> Hey @souravjain540 I have raised query on discord server more than 24 hours ago. But havan't received any support on the issue yet.

Sorry for late reply. We've replied you there, please check!
