### ISSUE TITLE
🐛 Bug Report: Entities - Remove the divider line between the buttons

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2720]
### What happened?

Remove the divider line between the buttons
![image](https://user-images.githubusercontent.com/96179897/167807133-e1843b3d-e424-488a-9951-5a45d2882cc5.png)

This is how it should look.
![image](https://user-images.githubusercontent.com/96179897/167806969-850de690-6801-40e1-abe3-71a79d9ed1fc.png)

### What you expected to happen

No divider lines

### How to reproduce

Go to Entities and then Permissions

### Amplication version

0.12.5

### Environment

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@souravjain540 please split to 2 separate issues

**Comment by pawan521** [comment]
If no one assigned on this issue.I would love to contribute

**Comment by souravjain540** [comment]
> If no one assigned on this issue.I would love to contribute

You've just been assigned with #2735 :)

**Comment by sonali-dudekula** [comment]
Hi @souravjain540 , i would love to contribute
If in case no one assigned, will you please assign this issue to me

**Comment by souravjain540** [comment]
> Hi @souravjain540 , i would love to contribute If in case no one assigned, will you please assign this issue to me

Hello @sonali-dudekula  👋🏻

I am assigning you this issue! 

Have a good time working on it. Limited Edition Amplication SWAG are waiting for your PR 😉

If you need any help just reply to me. We are more than happy to help you in your first PR to Amplication 💜

**Comment by sonali-dudekula** [comment]
Hey @souravjain540 will you please provide me the exact file location?

**Comment by alexbass86** [comment]
> Hey @souravjain540 will you please provide me the exact file location?

Hi, here is the Figma link
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=571%3A7981
thanks for your contribution :)
