### ISSUE TITLE
🐛 Bug Report: Entities - Add button need padding

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2730]
### What happened?

The add button doesn't have space between the options on granular. Please make sure it has 12px padding. The text following to add button should be 14px, and the selection filter should have total round corners.
![image](https://user-images.githubusercontent.com/96179897/168022873-9ae7ae2e-6a3e-4cad-89ce-77ce9367ad97.png)

### What you expected to happen

We should have padding between the button and the options.

### How to reproduce

Go to the entity page in the permissions section

### Amplication version

0.12.5

### Environment

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
I am working on this issue.

**Comment by souravjain540** [comment]
Hi @alexbass86 @tupe12334 @mshidlov 

I've done the padding and text font size change but I am unable to locate the selection filter button in the code.

Can you give me the path of file where it exists?

**Comment by tupe12334** [comment]
@souravjain540 This is the path to the select button `packages/amplication-client/src/Permissions/EntityPermissionFields.tsx`

**Comment by alexbass86** [comment]
@souravjain540 @tupe12334 any update?

**Comment by alexbass86** [comment]
@souravjain540 @tupe12334 please give an update.

**Comment by tupe12334** [comment]
I think @souravjain540 will know, he is assigned to this issue

**Comment by alexbass86** [comment]
@souravjain540 any update
