### ISSUE TITLE
Docs: Create a System Requirements section in the Amplication/ReadMe 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2731]
### Describe the issue with documentation

The system requirments are currently documented only in the [Application server ReadMe](https://github.com/amplication/amplication/blob/master/packages/amplication-server/README.md)

Users often miss this information, so we need to make the information more accessible.

### How to solve the problem

Include **System Requirements** section in the Amplication/ReadMe.md 

The system requirements section should be split into two sub-sections:
- Amplication Server
- Generated App

The current information in the [Application server ReadMe](https://github.com/amplication/amplication/blob/master/packages/amplication-server/README.md) is correct and applies to both Amplication Server and Generated App. 

Related issue: Docs: Create a System Requirements section in the Amplication/Docs #2732

---

**Comment by GaneshSonarSD** [comment]
can i take this @souravjain540

**Comment by souravjain540** [comment]
> can i take this @souravjain540

Hello @GaneshSonarSD  👋🏻

I am assigning you this issue! 

Have a good time working on it. Limited Edition Amplication SWAG are waiting for your PR 😉

If you need any help just reply to me. We are more than happy to help you in your first PR to Amplication 💜

**Comment by MoFoGo** [comment]
Hi @GaneshSonarSD - The Generated app contains exactly the same system requirements as for the Amplication Server. Even so, you should write these as two different sections, so it is clearer for the user.

**Comment by GaneshSonarSD** [comment]
okay thanks @MoFoGo

**Comment by souravjain540** [comment]
Hi @MoFoGo, can you please approve the PR?

**Comment by yuval-hazaz** [comment]
where is the PR?

**Comment by GaneshSonarSD** [comment]
https://github.com/amplication/amplication/pull/2817


check this one PR

**Comment by GaneshSonarSD** [comment]
@yuval-hazaz @MoFoGo @souravjain540

**Comment by souravjain540** [comment]
Thanks for your PR @GaneshSonarSD ❤️
