### ISSUE TITLE
🐛 Bug Report: Entities - Multi selection button bad corner radius

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#2733]
### What happened?

Currently, its 0px corner radius and its suppose to be 4px
![image](https://user-images.githubusercontent.com/53312820/168470482-9301dd10-2937-46fb-a356-5d977f1270b5.png)

### What you expected to happen

The corner radius should be 4px

### How to reproduce

Go to Entities and then Permissions

**Comment by pawan521** [comment]
Can you assign this issue to me

**Comment by Sumanth077** [comment]
Hello @souravjain540 can I take up this issue?

**Comment by souravjain540** [comment]
> Hello @souravjain540 can I take up this issue?

Hello @Sumanth077  👋🏻

I am assigning you this issue! 

Have a good time working on it. Limited Edition Amplication SWAG are waiting for your PR 😉

If you need any help just reply to me. We are more than happy to help you in your first PR to Amplication 💜

**Comment by Sumanth077** [comment]
@souravjain540 It would be great if you can provide the exact file location.
Thank you

**Comment by souravjain540** [comment]
@alexbass86 can you provide him the exact file location?

**Comment by alexbass86** [comment]
> @souravjain540 It would be great if you can provide the exact file location. Thank you

Hi, here is the Figma link
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=571%3A7981
thanks for your contribution :)

**Comment by souravjain540** [comment]
Hi @Sumanth077 , are you working on this issue?

Can we help in some way?

**Comment by Sumanth077** [comment]
Hi @souravjain540 Thank you for asking, currently working on it, and will make a PR Soon

**Comment by souravjain540** [comment]
Thanks for the update!

**Comment by souravjain540** [comment]
Hey @Sumanth077 👋 

Do you need any help from us?

**Comment by Sumanth077** [comment]
Hi @souravjain540 I am facing some issues, will try to ask in Discord Channel.

**Comment by souravjain540** [comment]
> Hi @souravjain540 I am facing some issues, will try to ask in Discord Channel.

Please do! We are more than happy to help you.

**Comment by souravjain540** [comment]
> Is this issue still open? 
> 
> 

Yes

**Comment by souravjain540** [comment]
@Sumanth077 so you're not working on this issue now?

**Comment by msquare-2** [comment]
Hey,
Can I try for this bug?

**Comment by souravjain540** [comment]
sure @msquare-2!

join our discord if you need any help :)

**Comment by msquare-2** [comment]
I've joined, 
Need to set up locally. Is there any documentation for it?

**Comment by souravjain540** [comment]
any updates @msquare-2 ?

**Comment by msquare-2** [comment]
My lapi was not feeling well(My system got corrupted)!

I've restored it now, will update you by today...

**Comment by souravjain540** [comment]
Thanks @msquare-2

**Comment by souravjain540** [comment]
@msquare-2 are you working on it?

**Comment by ParkourKarthik** [comment]
Could you assign this to me?

**Comment by alexbass86** [comment]
@souravjain540, any update regarding this issue?

**Comment by CoderCatcher** [comment]
Hello @souravjain540  can you assign me this issue

**Comment by CoderCatcher** [comment]
hello @souravjain540  can you assign me this issue

**Comment by souravjain540** [comment]
sure @CoderCatcher
