### ISSUE TITLE
🐛 Bug Report: Import lodash as a single library(client)

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#2734]
### What happened?

Currently, we import each lodash function separately.
Example from client:
"lodash.debounce": "4.0.8",
"lodash.keyby": "4.6.0",
"lodash.omit": "4.5.0",

### What you expected to happen

It's better to import lodash as a whole library.
Expected import:
"lodash": "4.17.20",

### How to reproduce

Import lodash as a single library in amplication client

**Comment by ganganimaulik** [comment]
Can you assign me this issue?

**Comment by souravjain540** [comment]
> Can you assign me this issue?

Hello @ganganimaulik  👋🏻

I am assigning you this issue! 

Have a good time working on it. Limited Edition Amplication SWAG is waiting for your PR 😉

If you need any help just reply to me. We are more than happy to help you in your first PR to Amplication 💜
