### ISSUE TITLE
🐛 Bug Report: Import lodash as a single library(server)

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#2735]
### What happened?

We are currently importing each lodash function separately.

### What you expected to happen

Import whole lodash library

### How to reproduce

Import lodash as a single library in server

**Comment by souravjain540** [comment]
> Can I contribute on this issue?

Hello @pawan521  👋🏻

I am assigning you this issue! 

Have a good time working on it. Limited Edition Amplication SWAG are waiting for your PR 😉

If you need any help just reply to me. We are more than happy to help you in your first PR to Amplication 💜

**Comment by pawan521** [comment]
hey @souravjain540 can you guide me to setup the project.

**Comment by souravjain540** [comment]
You can join our discord server: https://amplication.com/discord 

There is a support section specially to help on priority.

see you there!

**Comment by souravjain540** [comment]
> It is showing invalid invite

https://discord.gg/y2YuAese

**Comment by souravjain540** [comment]
Hi @pawan521, are you working on this issue?

**Comment by pawan521** [comment]
Where I have to add lodash ?
there are lots of files on the server

**Comment by yuval-hazaz** [comment]
@pawan521 please have a look at this PR https://github.com/amplication/amplication/pull/2806
you need to do the same for this folder https://github.com/amplication/amplication/tree/master/packages/amplication-server

**Comment by pawan521** [comment]
hey @yuval-hazaz I have seen the PR but in Server there is only file containing lodash Library(test -> gql-auth-mocks.ts).I made some changes on it.

**Comment by yuval-hazaz** [comment]
@Vipul2504 I can see all these dependencies on the package.json

![image](https://user-images.githubusercontent.com/43705455/171561943-5fbca914-01d2-447a-8074-c29f60305d05.png)

**Comment by souravjain540** [comment]
Hi @Vipul2504 are you working on this issue or I can assign it to someone else?

**Comment by Vipul2504** [comment]
I am Working on it. I need some help to resolve this issue

**Comment by souravjain540** [comment]
> I am Working on it. I need some help to resolve this issue
> 
> 
> 
> 

Please tell us in discord
