### ISSUE TITLE
🐛 Bug Report: Import lodash as a single library(dsg)

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#2736]
### What happened?

Currently, we import each lodash function separately.

### What you expected to happen

Import whole library

### How to reproduce

Import lodash as a single library in data service generator

**Comment by ShreyaPrasad1209** [comment]
Hey can I take up this issue?

**Comment by souravjain540** [comment]
> Hey can I take up this issue?

Hello @ShreyaPrasad1209  👋🏻

I am assigning you this issue! 

Have a good time working on it. Limited Edition Amplication SWAG is waiting for your PR 😉

If you need any help just reply to me. We are more than happy to help you in your first PR to Amplication 💜

**Comment by ShreyaPrasad1209** [comment]
@souravjain540 why do you need to import the whole library? Isn't it better to import specific functions that are needed so that we don't make the application unnecessarily heavy?

**Comment by yuval-hazaz** [comment]
The differences are too small to impact. We use it server side so also no impact on page load.
The cost of maintaining multiple packages is bigger then the cost of the size

**Comment by souravjain540** [comment]
Hi @ShreyaPrasad1209 , are you working on this issue?

Can we help in some way?

**Comment by vipulkunwar000** [comment]
> The differences are too small to impact. We use it server side so also no impact on page load. The cost of maintaining multiple packages is bigger then the cost of the size

Do you use multiple servers?
