### ISSUE TITLE
Dozen Issues for First Timers 🧢 

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#2737]
### Feature description

Hello contributors 👋

As proud members of the open-source community, we inspire developers to contribute to open-source projects 💜

To help you get started we have found a **Dozen issues** for first-time contributors, that can be a great way to fire-start your journey of the open-source contribution.

By giving back to the community, you’re also getting a chance to win cool **limited-edition** swag.

For each PR that will get merged by a new contributor, we will reward each one of them with our **unique** Amplication cap and stickers!

 

⚠️ The rules are simple:

- This activity applies only to the issues listed as “DIFT”
- Only new contributors to Amplication are entitled to receive a cap and stickers.
- Each new contributor can solve up to (1) one issue and can get up to (1) one cap and (1) one pack of stickers.
- Only the person assigned by Team Amplication will be considered a valid contributor
- This activity is on a “first come first serve” basis

**CAMPAIGN START DATE: Tuesday, May 17th**

# Issues 💯

| Issue                                                                                                                                | Description                                                           |Status                                                           |
| ------------------------------------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |------------------------------------------------- |
| <a href="https://github.com/amplication/amplication/issues/2736"><img src="https://img.shields.io/badge/2736%20-bug-green.svg"/></a> | Import lodash as a single library(dsg) . | Assigned|
| <a href="https://github.com/amplication/amplication/issues/2735"><img src="https://img.shields.io/badge/2735%20-bug-green.svg"/></a> | Import lodash as a single library(server) .|Assigned|
| <a href="https://github.com/amplication/amplication/issues/2734"><img src="https://img.shields.io/badge/2734%20-bug-green.svg"/></a> | Import lodash as a single library(client). |Assigned|
| <a href="https://github.com/amplication/amplication/issues/2712"><img src="https://img.shields.io/badge/2712%20-feat-blue.svg"/></a> | Side menu update - Reduce the size of the icon from 32px to 24px . |Assigned|
| <a href="https://github.com/amplication/amplication/issues/2733"><img src="https://img.shields.io/badge/2733%20-bug-green.svg"/></a> | Entities - Multi selection button bad corner radius |Assigned|
| <a href="https://github.com/amplication/amplication/issues/2731"><img src="https://img.shields.io/badge/2731%20-bug-green.svg"/></a> | DOCS: Create a System Requirements section in the Amplication/ReadMe. |Assigned|
| <a href="https://github.com/amplication/amplication/issues/2720"><img src="https://img.shields.io/badge/2720%20-bug-green.svg"/></a> | Entities - Remove the divider line between the buttons.|Assigned|
| <a href="https://github.com/amplication/amplication/issues/2713"><img src="https://img.shields.io/badge/2713%20-feat-blue.svg"/></a> | Workspace dropdown update.|Assigned|
| <a href="https://github.com/amplication/amplication/issues/2711"><img src="https://img.shields.io/badge/2711%20-feat-blue.svg"/></a> | Screen Update - Overview Screen & Settings Screen.|Assigned|
| <a href="https://github.com/amplication/amplication/issues/2192"><img src="https://img.shields.io/badge/2192%20-feat-blue.svg"/></a> | Add Health Check(s) to `@amplication/server`.|Available|
| <a href="https://github.com/amplication/amplication/issues/2059"><img src="https://img.shields.io/badge/2059%20-feat-blue.svg"/></a> | Notify a user when the deployment to sandbox compeleted.|Assigned|
| <a href="https://github.com/amplication/amplication/issues/1811"><img src="https://img.shields.io/badge/1811%20-feat-blue.svg"/></a> | Amplication CLI - Support AuthProvider.|Available|

**Comment by p1kalys** [comment]
Hi @souravjain540, Any issue is still pending? I would like to contribute to this project. It looks great.
Thanks in advance.
