### ISSUE TITLE
Docs: Update Sync Amplication Server with GitHub 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2742]
### Describe the issue with documentation

GitHub sync with dev environment is not updated. 

### How to solve the problem

Update the article:
https://docs.amplication.com/docs/connect-server-to-github

**Comment by MoFoGo** [comment]
> Hey @MoFoGo I would like to contribute. If it is unassigned, can you please assign this to me?

Best of luck with this @aparna2071.  Let me know if you need more info.

**Comment by aparna2071** [comment]
Thanks @MoFoGo

**Comment by aparna2071** [comment]
Hi @MoFoGo 

On https://docs.amplication.com/docs/connect-server-to-github, in the important Info section, it is mentioned that :
When using the hosted service on https://app.amplication.com/, the integration is pre-configured and you just need to follow [this guide](https://docs.amplication.com/docs/sync-with-github) to sync your application with GitHub.

This guide shows the required steps to sync Amplication app with GitHub, so can you please brief what exactly needs to be updated?

**Comment by abrl91** [comment]
> Hi @MoFoGo
> 
> On https://docs.amplication.com/docs/connect-server-to-github, in the important Info section, it is mentioned that : When using the hosted service on https://app.amplication.com/, the integration is pre-configured and you just need to follow [this guide](https://docs.amplication.com/docs/sync-with-github) to sync your application with GitHub.
> 
> This guide shows the required steps to sync Amplication app with GitHub, so can you please brief what exactly needs to be updated?

Hi @aparna2071 
You need to update the env variable on the docs.
The variables on the docs are wrong
![image](https://user-images.githubusercontent.com/39680385/169640965-137133d9-c086-437e-bc7c-d1e18f7fd385.png)

If you open `packages/amplication-server/.env`
you will see those variables:

```
GITHUB_APP_CLIENT_SECRET = [use-secret-manage]
GITHUB_APP_CLIENT_ID = [github-app-client-id]
GITHUB_APP_APP_ID = [github-app-app-id]
GITHUB_APP_PRIVATE_KEY = [github-app-private-key]
GITHUB_APP_INSTALLATION_URL = [github-app-installation-url]
```
So all you need to do is replace the env variables on the docs with those env variables

**Comment by aparna2071** [comment]
Ok thanks @abrl91 for helping

**Comment by aparna2071** [comment]
Done the necessary changes.
PR opened: https://github.com/amplication/docs/pull/144

**Comment by MoFoGo** [comment]
Thanks for your contribution @aparna2071
