### ISSUE TITLE
Docs: Describe Public Endpoints feature. 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2744]
### Describe the issue with documentation

The docs do not yet include description of the Public Endpoints 

### How to solve the problem

Create an article describing public endpoint.

See https://github.com/amplication/amplication/releases/tag/v0.12.7 for information

**Comment by yuval-hazaz** [comment]
@MoFoGo also, we need to update screenshots and content related to the permissions in articles like these 
https://docs.amplication.com/docs/first-app
https://docs.amplication.com/docs/how-to/how%20to/set-access-permissions

**Comment by MoFoGo** [comment]
Resolved
