### ISSUE TITLE
🐛 Bug Report: The back button is not working properly

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2746]
### What happened?

When you click on the "back" button, it takes us to a broken page

### What you expected to happen

This should take us to the last visited page

### How to reproduce

Just click on the "back" button from the commit screen

### Amplication version

0.12.5

### Environment

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mshidlov** [comment]
Hey @alexbass86 Thank you for reporting this issue. can you please elaborate on which back button and where? (in which page)
If you can add screen shots it can be much helpful.

**Comment by alexbass86** [comment]
> Hey @alexbass86 Thank you for reporting this issue. can you please elaborate on which back button and where? (in which page) If you can add screen shots it can be much helpful.

I saw now it has been fixed you can close the issue thanks
