### ISSUE TITLE
Login using Github error

### ISSUE THREAD

**Issue by liketoeatcheese** [amplication/amplication#2760]
Ola, 

I got this issue when trying to log in with Github (I think there's only one way to log in): `Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 9).` I think it did reach the Github server as I authenticated it to use my credentials, and it showed the error after that.

Looking forward to trying out the app :) Looks promising!

**Comment by yuval-hazaz** [comment]
Thanks @liketoeatcheese 
We migrated the database yesterday from GCP to AWS. I assume we need to adjust the connection limit setting.

we will review soon. Thanks for reporting 💜

**Comment by yuval-hazaz** [comment]
The issue is now resolved, 
thanks for reporting
