### ISSUE TITLE
Code zip file unavailable

### ISSUE THREAD

**Issue by liketoeatcheese** [amplication/amplication#2761]
Heya,

I tried to download the zip file, and when I opened it, the error popped up with the message: "Window cannot open the folder. *file name.zip* is invalid."

This button to download it is located at the build time screen. I pressed build id, and next to the "Generate Code" section, there was a small download icon to download it.

**Comment by mshidlov** [comment]
Thank you @liketoeatcheese for reporting I'm looking on it now

**Comment by souravjain540** [comment]
@mshidlov i think this is solved now?
