### ISSUE TITLE
🐛 Bug Report: Missing description for `auth` command in @amplication/cli

### ISSUE THREAD

**Issue by devblin** [amplication/amplication#2767]
### What happened?
There is missing description for `auth` command in amplication-cli.
![amplication-cli](https://user-images.githubusercontent.com/55559527/169446148-fd82e446-400e-4a46-acf5-b3828e341d27.png)

### What you expected to happen

There must be description for `auth` command in CLI such as ` 'authenticates CLI using API token generated in amplication server UI'`

### How to reproduce

Just run installed amplication-cli:`amp`

### Amplication version

0.1.4

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
Hi @devblin 

Can you please join our discord server. There is a support channel there for priority support to such errors.

We would love to help you.

Invite: https://discord.gg/y2YuAese

**Comment by souravjain540** [comment]
Hi @devblin

Did you get the help?

**Comment by jainpawan21** [comment]
Yes, you are right, description is missing for this command.

**Comment by devblin** [comment]
> Hi @devblin
> 
> Did you get the help?

@souravjain540 Hey, actually I don't think so its major issue to get support about, its just a missing description for a command in @amplication/cli, if engineering team allows, I can make PR for the same 👍🏽.

**Comment by souravjain540** [comment]
sure @abrl91 @tupe12334 please help!

**Comment by yuval-hazaz** [comment]
@devblin I will assign you. Please go ahead and make a PR
