### ISSUE TITLE
docs: incorrect links in https://docs.amplication.com/docs/community/handling-a-new-issue

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2770]
### Describe the issue with documentation

the doc at https://docs.amplication.com/docs/community/handling-a-new-issue is using incorrect links to external pages instead of internal links to the sections on the page

> The Maintainers update the Status and Label as the project progresses, as described in the [Set Status](https://www.notion.so/Issue-Handling-Workflow-6c135be0a2cf491eaa5acada15bf83f4) and [Apply Labels](https://www.notion.so/Issue-Handling-Workflow-6c135be0a2cf491eaa5acada15bf83f4) sections below.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/43705455/169644200-fae3673f-17ae-40c1-9d5d-9bb979462df8.png">

### How to solve the problem

replace the links to point the internal section on the page

**Comment by jainpawan21** [comment]
Hi @yuval-hazaz ,
I just created a [PR](https://github.com/amplication/docs/pull/145) to fix this.
