### ISSUE TITLE
CD: Add secret on deployment

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2773]
To prevent accidental deployments, we want to introduce a **confirmation mechanism** to our CD flow. This will prevent us from accidentally deploying to the wrong environment.

The mechanism is similar to how danger zones work in AWS, GitHub etc.

Currently, the AWS CD trigger looks like this:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/4976416/177746222-1c661936-e47a-4f49-9251-e161acac0fd4.png">

We would like to insert an additional text field saying `Confirm environment name`.
Then, as the first step of the pipeline, we should check if `confirm environment name === target environment name`. If true, we continue the pipeline. If not, we exit and print `Confirmation name does not match target environment name`.

**Comment by arielweinberger** [comment]
I've edited the original issue. It's good to go @mshidlov @shaharblanksela
