### ISSUE TITLE
prisma was denied access on the database postgres

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2778]
### Overview

`npm run setup:dev` failed on step 6 with the following message:
![image](https://user-images.githubusercontent.com/39680385/169704282-06d84a42-b554-4fb8-bca5-c8272d9d1e57.png)

### Symptoms

Access to DB was denied while trying to start DB.
Docker is running

### Cause

This error and other errors like that (about accessing DB) is usually caused by another Postgres process that runs on the same port (5432)

### Resolution

stop the other process that runs on port 5432 or change the port on Amplication generated app

### Tags

prisma, postgrest, db

### Related Discord Threads

https://discord.com/channels/757179260417867879/973588400915509388

**Comment by MoFoGo** [comment]
Hi @abrl91.  What is the correct term here: postgres, postgREST, or postgreSQL ?

**Comment by MoFoGo** [comment]
Resolved Troubleshooting-new-section #142
