### ISSUE TITLE
Adding custom DTOs to a generated app

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2779]
### Overview

Sometimes our users have use-cases where they need other DTOs that are supported by Prisma but not generated by us.
In these cases, the user should add his own custom DTO to the project. The question is WHERE? (and also maybe HOW)

### Symptoms

For example. Prisma supports filtering on Enum values, but we are not. 

### Cause

Go to the entity service, to the relevant method (for example `findMany`), and drill down into your desired dto by clicking on Prisma types.

### Resolution

In a generated app, inside each entity there is a `base` folder.
Add `dtos` folder next to the base folder and add your custom dtos inside that folder.

### Tags

graphql, prisma, dto

### Related Discord Threads

https://discord.com/channels/757179260417867879/971573610143690805

**Comment by MoFoGo** [comment]
See duplicate  #2812
