### ISSUE TITLE
Selective code generation app settings

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2780]
Add to app settings the ability to enable\disable code generation parts.

Add the ability to enable\disable:
* GraphQL API
* REST API
* Admin UI 

And adding new settings page to control the code generation.

**please note**
1. when GraphQL is disabled Admin UI should be disabled as well. Admin UI works with GraphQL and won't function when GraphQL is disabled.
2. In the figma you have folders locations inputs and root files section. this part still needs a discussion and is currently out of scope.

**issue tasks:**
- [ ] enable\disable GraphQL API code generation
- [ ] enable\disable REST API code generation
- [ ] enable\disable Admin UI code generation
- [ ] Add App settings icon in the icons side bar
- [ ] Add `API & Admin UI` settings to App settings side bat

![image](https://user-images.githubusercontent.com/91742238/169751226-82ba16a6-40de-403b-86fa-ea877a3dd721.png)

[figma](https://www.figma.com/file/51lgCrEN988c9pBs9uxdqT/Product---App-Settings?node-id=836%3A18964)

**Comment by MoFoGo** [comment]
Creating doc update for this feature.
