### ISSUE TITLE
🐛 Bug Report: Dynamically generated date in tests

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2784]
### What happened?

In the test `packages/amplication-server/src/core/workspace/workspace.resolver.spec.ts` We use `new Date()` instead of declaring a NOW variable.
This makes the test depend on outside data and may fall like in this example: https://github.com/amplication/amplication/runs/6536268805?check_suite_focus=true

### What you expected to happen

We need to declare a static time variable.

### How to reproduce

not relevant

### Amplication version

0.12.8

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
Hi @tupe12334 👋 

Do we want here to use `Date.now()` instead of `new Date()`

**Comment by Mohsin533** [comment]
F:\Bootstrap5\css\img\nature.jpg

**Comment by tupe12334** [comment]
Hi @souravjain540 We can use both, but the better way is Date.now() for readability.

**Comment by yuval-hazaz** [comment]
@tupe12334 @souravjain540 please have a look at this example 
https://github.com/amplication/amplication/blob/2e6a2df94774b8d13dd318f9e62bce1fa26c73eb/packages/amplication-server/src/core/account/account.service.spec.ts#L96

**Comment by moulibrota-das** [comment]
Hi, can I work in this issue?

**Comment by souravjain540** [comment]
> Hi, can I work in this issue?

Sure @moulibrota-das. Assigned you

Best of luck. Do tell me if any help needed.

**Comment by moulibrota-das** [comment]
Just Using Date.now() will only return number of milliseconds.
We can pass Date.now() to new Date() for a date object.
How about that?

`const timeNow = new Date(Date.now());`

**Comment by souravjain540** [comment]
> Just Using Date.now() will only return number of milliseconds.
> 
> We can pass Date.now() to new Date() for a date object.
> 
> How about that?
> 
> 
> 
> `const timeNow = new Date(Date.now());`

@yuval-hazaz

**Comment by yuval-hazaz** [comment]
> @tupe12334 @souravjain540 please have a look at this example
> 
> https://github.com/amplication/amplication/blob/2e6a2df94774b8d13dd318f9e62bce1fa26c73eb/packages/amplication-server/src/core/account/account.service.spec.ts#L96

@tupe12334 @souravjain540 @moulibrota-das did you see my comment above? 
why aren't you using `expect.any(Date)`?

**Comment by tupe12334** [comment]
@moulibrota-das I saw what @yuval-hazaz wrote and it's better than what we wrote so let's go with the example of @yuval-hazaz , do you need any help to implement that?

**Comment by moulibrota-das** [comment]
@tupe12334 Ok I will try to implement that.

**Comment by moulibrota-das** [comment]
@tupe12334 can you review this PR

**Comment by moulibrota-das** [comment]
Hey @tupe12334 can you please review this PR
