### ISSUE TITLE
🐛 Bug Report: unnecessary hover effect on permissions button

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2805]
### What happened?

There is an unnecessary hover effect on the permission buttons

https://user-images.githubusercontent.com/39680385/170278390-168fb0fa-232b-43d1-930d-a5677da77131.mov

 

### What you expected to happen

remove the hover effect

### How to reproduce

on the entities page, chose an entity and then click on the permissions tab. Hover the permissions type button

### Amplication version

0.12.8

**Comment by Selt0** [comment]
Can I work on this issue? I can change the hover to a different color or I can remove it completely.

**Comment by souravjain540** [comment]
> Can I work on this issue? I can change the hover to a different color or I can remove it completely.

Sure, you can work on this.

I think completely remove. 

@abrl91 will confirm

**Comment by yuval-hazaz** [comment]
before moving forward we better hear what @alexbass86 think about it
