### ISSUE TITLE
sample mobile app development with full stack as an example

### ISSUE THREAD

**Issue by devopstoday11** [amplication/amplication#2808]
### Feature description

Could your team please develop a sample mobile app with react-native frontend and nodejs as backend using Amplication? Backend microservices (APIs, gRPC, GraphQL, etc.) should be running on Kubernetes with API gateway as the traffic entry point plus a load-balancer, and use SaaS DB like Datastax Cassandra or Crunchy Postgresql SaaS. 
It would be a really good example for beginners to adopt Amplication for the mobile development using node.js.

**Comment by devopstoday11** [comment]
@yuval-hazaz  - please let us know when your team planning on providing an example like above.

**Comment by yuval-hazaz** [comment]
hi @devopstoday11
we are always encouraging the community to share sample use cases using Amplication and we would love to see an example built for a mobile app. 

currently, we do not have the resources to work on such an example, but we are open to getting help from the community. 

I will leave this request open and flag it for help from the community in case anyone can help with it

**Comment by TAKANOME-DEV** [comment]
Hi there, I don't master react native but I would like to help with this sample app. Let me know if there is something I can do to help

**Comment by yuval-hazaz** [comment]
hi @TAKANOME-DEV Thanks for your suggestion. 
I think that we can use any type of demo app, it can be responsive web for mobile, or native. it can also be just a web application. 

Do you have any good ideas for a sample application?

**Comment by TAKANOME-DEV** [comment]
Not really 😅 I was just looking a way to contribute.
But what about an e-commerce mobile app. I saw you made a [sample e-commerce](https://github.com/amplication/e-commerece-sample) app.
Can we use amplication for backend and react native for frontend??

**Comment by yuval-hazaz** [comment]
@TAKANOME-DEV 
Yes, that would be a very good example

**Comment by TAKANOME-DEV** [comment]
So would you create a repo for that??

**Comment by yuval-hazaz** [comment]
I created a new repo here and gave you write permissions
https://github.com/amplication/sample-mobile-app

let me know if you have a cool name for the project and I can rename the repo

also, feel free to reach out on our discord server for any help you need
https://amplication.com/discord

**Comment by TAKANOME-DEV** [comment]
Ok cool I'm trying to think about the look and feel of the app and then I cloned the sample-web-app but I get the following error:

![amplication](https://user-images.githubusercontent.com/79809121/171227010-05b6066c-ce53-47fe-98f8-6998fc853c2c.png)

Do you have any idea or example that I can use to get started??

**Comment by yuval-hazaz** [comment]
@TAKANOME-DEV sorry for the late response. 
Usually it is best to look for support on our Discord channel where the core team and community and more responsive for ongoing support 

https://amplication.com/discord

**Comment by aaaaayushh** [comment]
Hi, is this up for grabs? Would love to work on it

**Comment by TAKANOME-DEV** [comment]
Hello @aaaaayushh we have already started one with React Native and TypeScript. You can check it out [here](https://github.com/amplication/sample-mobile-app)

**Comment by lokeswaran-aj** [comment]
Hi, @yuval-hazaz I think @TAKANOME-DEV is not working on this feature. So can I give it a try? Can you give me permission to write in the sample app repository?

**Comment by TAKANOME-DEV** [comment]
Hey @lokeswaran-aj, thanks for your interest in working on this feature.

Sorry everyone for not being active lately :sweat:

I'm having issues running react-native right now but I'm looking forward to contributing to it again :rocket:

**Comment by lokeswaran-aj** [comment]
@TAKANOME-DEV I did not get you. So you are not gonna work on this app right now, are you?

**Comment by TAKANOME-DEV** [comment]
Sorry for not being clear.
> So you are not gonna work on this app right now, are you?
>
No, I can't work on it right now. Feel free to continue where I left it.

**Comment by lokeswaran-aj** [comment]
@yuval-hazaz Can you give me write permission for [this](https://github.com/amplication/sample-mobile-app) repository?

**Comment by yuval-hazaz** [comment]
@lokeswaran-aj you should now have permissions
thanks for your help!

**Comment by lokeswaran-aj** [comment]
> @lokeswaran-aj you should now have permissions thanks for your help!

Yes, Thank you.

**Comment by lokeswaran-aj** [comment]
@yuval-hazaz
I have created a Todo app similar to [React todo](https://docs.amplication.com/tutorials/react-todos/) but for mobile using react native.

Please feel free to review the code and suggest any changes.
[https://github.com/amplication/sample-mobile-app](https://github.com/amplication/sample-mobile-app)
Attached demo video in the readme

**Comment by yuval-hazaz** [comment]
I just noticed this ticket is still open.
Great work @lokeswaran-aj 
we will include links to this demo in our docs
sorry it took us so much time to response, somehow we overlooked it
