### ISSUE TITLE
Add a guide on how to add custom dto

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2812]
### Describe the issue with documentation

Our users sometimes have use-cases where they need DTOs that are supported by Prisma but not generated by Amplication.
In these cases, the users should add their own custom DTO to the project. This article answers the question WHERE and HOW? 
For example, Prisma supports filtering on Enum values, but Amplication does not.

### How to solve the problem

Generate an app that uses Enum type for one or more of its entities field.
Add the code to make it possible to filter on enum and describe how you did it.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MoFoGo** [comment]
@abrl91 - Is this still relevant?

**Comment by abrl91** [comment]
fixed by https://github.com/amplication/docs/pull/180
