### ISSUE TITLE
🐛 Bug Report: internal server error while trying to create a user with a username that already exisits

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2814]
### What happened?

on create user, when I try to create a user with a username that already exists, I get an internal server error

### What you expected to happen

I expect to get something like  409 and a message that a user with the requested username already exists
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses

![image](https://user-images.githubusercontent.com/39680385/170814937-7d5682dd-99c9-4e85-b647-c4ca67afc113.png)

### How to reproduce

generate an app and make a post request to create a user

### Amplication version

0.12.8

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abrl91** [comment]
we can add a custom validation decorator and use it on the username property 
![image](https://user-images.githubusercontent.com/39680385/170830833-e3323fb9-6a1d-45c8-ba03-ce82cc08ea07.png)
(a screenshot from a generated app -  User.ts)
https://github.com/typestack/class-validator#custom-validation-decorators

**Comment by yuval-hazaz** [comment]
@abrl91 I think a decorator would not be the best solution for this problem. 
It feels that a local validation in the service code before creating the user would be more appropriate. It is part of the logic of the function

**Comment by shubhwip** [comment]
Can i be assigned to this :) ?

**Comment by souravjain540** [comment]
> Can i be assigned to this please :) ?

sure! @shubhwip 

Join our discord if you need any help :)

**Comment by shubhwip** [comment]
@yuval-hazaz @abrl91 I am thinking of below approach
- Adding a new error type in errors.ts for `ConflictException`
- Adding validation in `CREATE_ENTITY_FUNCTION` in `controller.base.template.ts`
  - Validation would be to put a check on finding resource based on unique specified attributes of model
  - If we find any resource matching one of the unique define field of model, we will throw conflict exception.

**Comment by shubhwip** [comment]
[@yuval-hazaz](https://github.com/yuval-hazaz) [@abrl91](https://github.com/abrl91) I am thinking of below approach
Adding a new error type in errors.ts for ConflictException
Adding validation in CREATE_ENTITY_FUNCTION in controller.base.template.ts
    * Validation would be to put a check on finding resource based on unique specified attributes of model before creating new resource.
    * If we find any resource matching one of the unique define field of model, we will throw conflict exception.
—
Or if we don't use amplication data generator for user then we can put validation in user service directly but i think we are using amplication data generator for user model.
—
Or Prisma Client can throw unique constraint violation error and we can catch and wrap it inside `CREATE_ENTITY_FUNCTION` up as BAD Request.
https://www.prisma.io/docs/reference/api-reference/error-reference#p2002

**Comment by souravjain540** [comment]
@yuval-hazaz @abrl91 please reply to him.

**Comment by abrl91** [comment]
> https://www.prisma.io/docs/reference/api-reference/error-reference#p2002

I think the last solution is preferable, but with `409  conflict` HTTP error code
