### ISSUE TITLE
🐛 Bug Report: Build commit message on GitHub has wrong link

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2821]
### What happened?

The link in the GitHub pull request back to amplication commit is broken.
it pointing to `server.mplication.com` instead of `app.amplication.com`.
![image](https://user-images.githubusercontent.com/91742238/170853393-7276d27d-1fa0-4816-8f0c-ae5e8bccef6e.png)

### What you expected to happen

That the link in the pull request will take me to amplication commit

### How to reproduce

1. connect app to GitHub repository
2. do changes in amplication app
3. commit & build new changes
4. go to the App GitHub repository created pull request
5. try to click the link in the pull request message

### Amplication version

0.12.8

### Environment

Amplication Cloud

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tupe12334** [comment]
Duplication of #2983
