### ISSUE TITLE
helm: add support for application level routing

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2855]
Add support for charts to use same domain with HTTP path routing.

to support this use case we need:
- [x] Add path value in the helm charts base ingress rules
- [x] Add to helm charts base ingress annotations path manipulation annotation.

this issue is blocking issue: #2729

**Comment by mshidlov** [comment]
@shaharblanksela

**Comment by shaharblanksela** [comment]
Done on release/0.13.1.
