### ISSUE TITLE
amp auth Error: Could not authorize user

### ISSUE THREAD

**Issue by edgarbrignoni** [amplication/amplication#2865]
$ amp config
AMP_CURRENT_APP=undefined
AMP_CURRENT_ENTITY=undefined
AMP_CURRENT_FIELD=undefined
AMP_SERVER_URL=https://app.amplication.com/
AMP_OUTPUT_FORMAT=undefined

**Comment by souravjain540** [comment]
what's the exact issue @edgarbrignoni?

can you explain?

**Comment by edgarbrignoni** [comment]
1. First I install amplication cli
$ npm install -g @amplication/cli
2. Check the version
$ amp --version
3. Verify the default AMP_SERVER_URL is set correctly using amp config
https://app.amplication.com/
4. Create an API Token on the website for My App project
API tokens are used to authenticate requests to Amplication API, specifically it is required to use Amplication CLI.
Tokens are valid for 30 days from creation or last use, so that the 30 day expiration automatically refreshes with each API call.
5. Run the amp auth command with my token
$ amp auth TOKEN
Then I get the error:
 ›   Error: Could not authorize user

**Comment by souravjain540** [comment]
can you join our discord server for priority support? 

Link: https://amplication.com/discord

**Comment by sinxwal** [comment]
Same problem here. 
the solution is "instead of https://app.amplication.com/ you should use https://server.amplication.com/"

**Comment by edgarbrignoni** [comment]
Thanks @sinxwal and @souravjain540 for both of your support, I was able to fix the issue by changing the uri.

**Comment by yuval-hazaz** [comment]
I reopened this issue since we need to update the default URL in the CLI with the updated URL.
also, we should update the docs.

**Comment by GreenMachine01** [comment]
@MoFoGo @MichaelSolati @yuval-hazaz Do we still need to do something here?
