### ISSUE TITLE
🐛 Bug Report: Logout button doesn't show when browser height is reduced or browser has more than 100% zoom level

### ISSUE THREAD

**Issue by molaycule** [amplication/amplication#2866]
### What happened?

When the browser height is reduced or the browser window has a zoom level greater than 100% the logout button on the sidebar doesn't show when the sidebar menu overflows.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/20028628/172001485-845a86fb-e200-43dc-b42c-d1140f1f2353.png">
Logout button not showing in the sidebar, see screenshot above

### What you expected to happen

The sidebar menu should be scrollable when the sidebar menu items overflow to accommodate for a responsive sidebar design.

### How to reproduce

Select an app to work on, let all current sidebar menus show, increase the browser zoom level using `ctrl +` until the sidebar overflows, or reduce the browser window's height.

### Amplication version

0.12.7

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
Hi @alexbass86 @barshimi 

Please review the PR.

**Comment by souravjain540** [comment]
Thanks for another contribution @molaycule 💜
