### ISSUE TITLE
User `admin` was denied access on the database `postgres.public`

### ISSUE THREAD

**Issue by 1mike12** [amplication/amplication#2872]
### What happened?

get an error running step 4 of the [dev environment instructions. ](https://docs.amplication.com/docs/getting-started/dev-env)

`npm run db:init` fails with 

```sh
> @my-app/server@ db:init /Users/me/WebstormProjects/openworkspaces/server
> run-s "db:migrate-save -- --name 'initial version'" db:migrate-up seed


> @my-app/server@ db:migrate-save /Users/me/WebstormProjects/openworkspaces/server
> prisma migrate dev "--name" "initial version"

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "postgres": PostgreSQL database "postgres", schema "public" at "localhost:5432"

Error: P1010: User `admin` was denied access on the database `postgres.public`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @my-app/server@ db:migrate-save: `prisma migrate dev "--name" "initial version"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @my-app/server@ db:migrate-save script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2022-06-06T13_08_03_386Z-debug.log
ERROR: "db:migrate-save -- --name 'initial version'" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @my-app/server@ db:init: `run-s "db:migrate-save -- --name 'initial version'" db:migrate-up seed`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @my-app/server@ db:init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2022-06-06T13_08_03_437Z-debug.log

```

### What you expected to happen

command to work

### How to reproduce

download a generated project and try to run step 4 of the init documentation

`npm run db:init`

### Environment

node v14.18.2
npm 6.14.15
Docker version 20.10.11, build dea9396 
mac os12

**Comment by yuval-hazaz** [comment]
@1mike12 thanks for reporting.
It sounds like a setup issue (maybe docker is not running, or port is busy...)

can you please join our discord channel to get support ?
https://amplication.com/discord

**Comment by souravjain540** [comment]
@1mike12 please join our discord for priority support :)

**Comment by 1mike12** [comment]
just an update for anyone coming across this, this was caused by having a local postgres installation. I had both brew and chocolatey installations of postgres installed on the host machine, which means the default port 5432 was already taken up. So I think the error is the admin user not existing in the totally different psql environment. 

Stop the host postgres or uninstall it
