### ISSUE TITLE
Docs: Searchable Fields

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2874]
### Describe the issue with documentation

The searchable flage  is not mentioned in the API docs.

### How to solve the problem

Add a note about the searchable flag in the API Filtering article.

**Comment by MoFoGo** [comment]
See PR: 

[searchable-flag-update #153](https://github.com/amplication/docs/pull/153#:~:text=searchable%2Dflag%2Dupdate%20%23153)

**Comment by GreenMachine01** [comment]
@MoFoGo is this still an issue or can it be closed?
