### ISSUE TITLE
Docs: Add a description of JSON data type

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2875]
### Describe the issue with documentation

The docs are missing a  description of JSON data type

### How to solve the problem

Update the [Creating a New Entity Field](https://docs.amplication.com/docs/how-to/create-entity-field/) article to include more info about JSON

**Comment by MoFoGo** [comment]
Relates to PR:

Update-entity-fields #154

**Comment by souravjain540** [comment]
@veera6513 sure!

Join our discord for any support in making PR to solving the issue

**Comment by souravjain540** [comment]
@veera6513 any updates?

**Comment by veera6513** [comment]
Actually I had some personal work...I will try complete by tomorrow.

**Comment by souravjain540** [comment]
@veera6513 are you working on this?

If not, can I assign it to someone else?

**Comment by ParkourKarthik** [comment]
I would like to pick this up.

**Comment by souravjain540** [comment]
> I would like to pick this up.

Only first time contributors can participate in this :)

**Comment by Abhay5855** [comment]
I can take this issue can you assign it to me

**Comment by souravjain540** [comment]
> I can take this issue can you assign it to me

Sure

**Comment by Abhay5855** [comment]
cloned the repo and started working on it thank you

**Comment by prakhar-198** [comment]
Hey! if the issue is still not fixed..Please can you assign me..I'll fix it! @souravjain540

**Comment by yuval-hazaz** [comment]
@Abhay5855 please let us know if you need any help with that

**Comment by Abhay5855** [comment]
@yuval-hazaz  yes sure
