### ISSUE TITLE
🐛 Bug Report: Amplication TopBar Tabs overflow, horizontal scroll is missing

### ISSUE THREAD

**Issue by baptistesx** [amplication/amplication#2892]
### What happened?

When many tabs (entities...) are opened on the TopBar, horizontal scroll is missing, we cannot click on hidden tabs.

### What you expected to happen

Horizontal tabs to scroll

### How to reproduce

Open many entities tabs (reduce your window width to make them overflow if necessary).

### Amplication version

app.amplication.com (production)

**Comment by souravjain540** [comment]
Hi @baptistesx 
Thank you so much for taking time and reporting the issue.

@alexbass86 and @barshimi will look into it.

Would you like to make a PR?

**Comment by souravjain540** [comment]
Hi @baptistesx. Are yo working on it?

**Comment by yniks** [comment]
Hey @baptistesx, If you haven't started working on this. Would you mind  if create a pull request for this ?

**Comment by yuval-hazaz** [comment]
Before we move forward with a fix, we better get the UI from @alexbass86 
There are several options here on how to resolve that - two examples

1. use smaller tabs with just an icon just like chrome
2. add a "right arrow' on the right and "let arrow" on the left to scroll

@alexbass86 can you please provide the design?

**Comment by alexbass86** [comment]
Since the latest UI change, we don't support tabs, so this issue is irrelevant.
