### ISSUE TITLE
Dynamic code generation: specify generated code file path

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2894]
Add the ability to specify the generated code folder path, for generated server and generated admin-ui. 
This change will help to integrate Amplication-generated code with a non-empty repository.

This ability should be added to `settings/API & Admin UI` configurations as shown in issue: #2780.
![image](https://user-images.githubusercontent.com/43705455/174834447-2cdfddfe-f8a4-4e24-a5c5-29ed8c4165e0.png)

**Comment by yuval-hazaz** [comment]
@mshidlov @barshimi please note that we need to support placeholders for the service name so the user can use a fixed template for all services without settings it manually for each service
