### ISSUE TITLE
🐛 Bug Report: Push changes to GitHub fails

### ISSUE THREAD

**Issue by sinxwal** [amplication/amplication#2916]
### What happened?

I am getting error "Push changes to GitHub" each time i try new build. The build and deploy successfully completes.
The full log looks like this
`(Info) Starting to push changes to GitHub.`
`(Info) Push changes to GitHub failed`
`(Info) TypeError: Cannot destructure property 'url' of 'response' as it is null.`

I think error comes from queue.service.ts, from function
```
sendCreateGitPullRequest(
    data: SendPullRequestArgs
  ): Promise<SendPullRequestResponse | null> {
    return new Promise(res => {
      this.kafkaService
        .send(this.generatePullRequestTopic, data)
        .subscribe((response: ResultMessage<SendPullRequestResponse>) => {
          try {
            const validClass = plainToClass(
              SendPullRequestResponse,
              response.value
            );
            res(validClass);
          } catch (error) {
            res(null); <-- promise resolves null.
          }
        });
    });
  }
```
and finally execution fails here

```
            const response = await this.queueService.sendCreateGitPullRequest({
              gitOrganizationName: appRepository.gitOrganization.name,
              gitRepositoryName: appRepository.name,
              amplicationAppId: app.id,
              gitProvider: EnumGitProvider.Github,
              installationId: appRepository.gitOrganization.installationId,
              newBuildId: build.id,
              oldBuildId,
              commit: {
                base: 'main',
                head: `amplication-build-${build.id}`,
                body: `Amplication build # ${build.id}.
                Commit message: ${commit.message}
                ${url}
                `,
                title: commitMessage
              }
            });
            const { url: prUrl } = response; <--  TypeError
```

### What you expected to happen

The expected behaviour is that each commit creates Pull request in the connected github repo.

### How to reproduce

Just create new account with sample app and connect any not empty repository. 

### Amplication version

current app.amplication.com

### Environment

MacOs Chome Version 102.0.5005.61

**Comment by sinxwal** [comment]
no luck( Can you check my current app logs? cl4eiwry479765101hn76sigger

**Comment by mshidlov** [comment]
@sinxwal thank you for your precise catch. I'm updating the code that will not send a generic message but will write the fail reason.

**Comment by sinxwal** [comment]
@mshidlov  After this PR type error is gone. Hoverer pr itself is not created. 
The error message is "Error: Failed creating pull request, reason: [object Object]". 
Can we get the error message here?

**Comment by yuval-hazaz** [comment]
@tupe12334 @mshidlov @abrl91 @arielweinberger this is the second report of this issue, in addition to the discussion on the Discord support channel
Please give issue a priority and let's make sure we find the root cause and fix it

**Comment by matthewadams** [comment]
FWIW I was trying to push to an empty github repo that I created while playing with Amplication for the first time.  I cloned it locally, then `git checkout branch main && touch .bang && git add . && git commit -m 'bang'` then pushed.
