### ISSUE TITLE
setup dev completed successfully 💪 what now?

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2931]
### Describe the issue with documentation

After running `npm run setup:dev` we have a docker container with kafka and database.
Now, in order to run a specific service, we need to navigate to its path in the terminal and run the start command 
`npm run start` / `npm run start:debug`

BUT - we must make sure that we fill out all the necessary environment variables.
For example, the build will fail without this env variable and a valid path: `BASE_BUILDS_FOLDER=[path-to-local-folder]`, and sync with GitHub will fail without Github's env variables...

Another important note to mention is that in order to make sure Kafka client is connected, the user needs to open
`localhost:8080` on the browser or click here (docker-desktop):
![Screen Shot 2022-06-15 at 17 22 45](https://user-images.githubusercontent.com/39680385/173851627-de59f885-ea9a-4bd7-95a9-399015ffd9d9.png)

In the following screenshot, we can see the green dot and that we have a broker
![Screen Shot 2022-06-15 at 17 21 45](https://user-images.githubusercontent.com/39680385/173851871-0bbc124f-5641-4c49-9339-a425a61ab72c.png)

### How to solve the problem

write a doc that will contain:
- The env variables of each service and how to fill them
- Note the user that he needs to make sure that Kafka UI is running (green dot)

**Comment by MoFoGo** [comment]
@abrl91 where can I find the env variables of each service?
