### ISSUE TITLE
CD: part of the pods in the private dev environments are nol loading the secrets

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#2935]
When running AWS-CD GitHub action the secrets are created and deployed to the correct namespace on the correct EKS cluster.

part of the secrets are loaded differently, they got labels that the rest doesn't and they are empty. 

![image](https://user-images.githubusercontent.com/91742238/174008040-2b03f4fb-61b7-4b10-bd7c-b32c2a7c5fd8.png)
![image](https://user-images.githubusercontent.com/91742238/174008127-ca9df3f4-0700-4d50-a9a4-05a0fb34de80.png)

see branch: `test/dev`

**Comment by shaharblanksela** [comment]
Fixed. 
The problem was that 2 sources tried to apply secret resources. 
1. On step 'create-secrets' in the cd-aws pipeline.
2. On the deployment of the services charts.
This cause a conflict, the solution is to remove unnecessary secrets.
