### ISSUE TITLE
Release notes 0.13.1 - breaking changes

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2946]
### Describe the issue with documentation

Link to the relevant PR: https://github.com/amplication/amplication/pull/2928

## amplication-server, amplication-prisma-db, amplication-git-push-webhooks-service, amplication-git-pull-service
- database credentials have changed and so the DB-connection URL
- in addition, the connection URL to the DB is now including the `SERVICE_DB_NAME` env variable at the end

For this reason, after pulling release `0.13.1` you need to clean your existing containers, volumes, and images:

kill old running docker containers:
```bash
docker container ls
docker container rm -f [list-of-containers-id]
```
clean volumes from the old version:
```bash
docker container prune
docker volume prune
```

Then, in the root amplication folder run:
```
npm run docker:dev
```
This command will run a new docker container consisting of Kafka and DB

---

## mportant note for working with amplication-server, amplication-git-pull-request-service, amplication-git-pull-service, amplication-storage-gateway
For those services to function as expected, you need to fill the value of the following env file

```bash
# BASE_BUILDS_FOLDER 
BASE_BUILDS_FOLDER=[path-to-local-folder] //  example:  /Users/myname/tempFolder
```
---

## Connection to Kafka and troubleshooting: 

Another important note to mention is that in order to make sure Kafka client is connected, the user needs to open
localhost:8080 on the browser or click here (docker-desktop):

![image](https://user-images.githubusercontent.com/39680385/174475399-f0e9e52b-77e9-4787-95e6-fe7dec6dd44c.png)

In the following screenshot, we can see the green dot and that we have a broker
![image](https://user-images.githubusercontent.com/39680385/174475408-6690f7a3-db26-42e5-a8b3-45419f6a0569.png)

## Running amplication in local environment:
After completing all mentioned above

amplication-server:
```bash
npm run start:debug
```
amplication-client:
```bash
npm run start:debug
```
amplication-storage-gateway (for the builds and code view):
```bash
npm run start:debug
```

amplication-git-pull-request-service (for pull request):
```bash
npm run start:debug
```

### How to solve the problem

Mention all of this in the release notes of version 0.13.1

### additional notes
Another related issue for new users: https://github.com/amplication/amplication/issues/2931

**Comment by yuval-hazaz** [comment]
@abrl91 what is status of this task?

**Comment by overbit** [comment]
This is completed, right @abrl91  @MoFoGo. Please close it if it was
