### ISSUE TITLE
🐛 Bug Report: Github button style

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2953]
### What happened?

The connect to github button in not all the way to the end
<img width="1624" alt="Screen Shot 2022-06-20 at 17 12 46" src="https://user-images.githubusercontent.com/61761153/174620937-1e379808-e841-4a6b-aaa1-43986fa39cb5.png">

### What you expected to happen

not relevant

### How to reproduce

not relevant

### Amplication version

0.13.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by moulibrota-das** [comment]
@tupe12334  Does the "Connect to GitHub" button need to be just above the divider line with much lower bottom margin?

**Comment by tupe12334** [comment]
@moulibrota-das  @alexbass86 Will know

**Comment by tupe12334** [comment]
@yuval-hazaz I talk with Alex on the phone and he said that its not by design
