### ISSUE TITLE
🐛 Bug Report: Missing error log

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2957]
### What happened?

In the file ```packages/amplication-git-pull-request-service/src/core/pull-request/pull-request.controller.ts``` we catch an error and return an answer to Kafka but we don't log the error to the console

### What you expected to happen

log the catch error to the console

### How to reproduce

not relevant

### Amplication version

0.13.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Vipul2504** [comment]
Hello, Can I contribute to this issue?

**Comment by tupe12334** [comment]
@Vipul2504 Of course! go head

**Comment by Vipul2504** [comment]
Thanks @tupe12334
