### ISSUE TITLE
Docs: Correct server link to  https://server.amplication.com/

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2960]
### Describe the issue with documentation

Following the recent redeployment we use seperate subdomains for client and server. This is not yet documented. 

### How to solve the problem

Go through the docs and wherever relevant, change  **https://app.amplication.com/**  to **https://server.amplication.com/**

**Comment by code-with-onye** [comment]
Hello👋, have these issue be fix, because I can help

**Comment by yuval-hazaz** [comment]
@MoFoGo is this one still open?

**Comment by yuval-hazaz** [comment]
@MoFoGo ?

**Comment by yuval-hazaz** [comment]
@MoFoGo the description above is not correct. We should not change the URL in all places automatically
