### ISSUE TITLE
Project Infrastructure Refactoring

### ISSUE THREAD

**Issue by barshimi** [amplication/amplication#2961]
### Feature description

This issue is part of new project. product wise we're changing the way we address the services structure. structure root will be workspace and it will have several projects. Each project will have the same configuration as app.
This issue will be mainly around Amplication client and specially client structure. the aim is to change structure to support this product change.

- [x] #2989
- [x] #3059
- [x] #2990
- [x] #3259
- [ ] Create app footer.
- [x] Create context/hook to communicate between header/footer to main page container.
- [x] #3258

**Comment by yuval-hazaz** [comment]
@barshimi before you create a context to communicate between the header and the page, please have a look at this method we are already using and see if it will make sense to keep using it 
https://github.com/amplication/amplication/blob/master/packages/amplication-client/src/util/teleporter.ts
