### ISSUE TITLE
🐛 Bug Report: invite a member to workspace leads to the wrong link

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2964]
### What happened?

the link to the initiation leads to a wrong link:
![image](https://user-images.githubusercontent.com/39680385/175230500-dc82ff4c-c39a-42b5-8d5d-261651db4db6.png)

link to the Discord thread: https://discord.com/channels/757179260417867879/988847696607600690

### What you expected to happen

the link should lead to login and connect to the workspace 

### How to reproduce

send an invite to a member

### Amplication version

0.13.1

**Comment by pratikgl** [comment]
Hii @souravjain540. Can I work on this issue?

**Comment by souravjain540** [comment]
> Hii @souravjain540. Can I work on this issue?

Sure! @pratikgl 

Join our discord if you need any help in solving this. :)

**Comment by tupe12334** [comment]
Hi @pratikgl The problem is rooted in the `packages/amplication-server/src/core/mail/mail.service.ts` file, the HOST var is pointing to the server url and not the client url in the env CLIENT_HOST

**Comment by souravjain540** [comment]
any updates @pratikgl ?

**Comment by pratikgl** [comment]
Hey @souravjain540 I was waiting for @tupe12334 follow up on Discord. I had few doubts on the changes.

**Comment by pratikgl** [comment]
I got the resolution and will raise the PR my morning.
