### ISSUE TITLE
Simplifying environment variables

### ISSUE THREAD

**Issue by MichaelSolati** [amplication/amplication#2969]
### Feature description

In a few of our packages we have an environment variable called `BASE_BUILDS_FOLDER` or `STORAGE_PATH`, both of which are set to `[path-to-local-folder]`.

It's recommended in the packages' README that users set it to a folder in the users' home folder (`/Users/myusername/temp`) but if the `.env` isn't modified a folder called `[path-to-local-folder]` is added to the packages' folder and is not git ignored.

This feels like an unnecessary and confusing step.

I suggest that we assign the folders to something specific, like `.base_builds_temp` or `.storage_temp`, and git ignore those folders. This simplifies the setup, removes potential confusion, and still allows for developers to move the temp files to somewhere else if they want.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@MichaelSolati i like the idea

**Comment by arielweinberger** [comment]
I'm glad you are suggesting this @MichaelSolati. Last week I suggested the same on a call with @abrl91. This is a very common practice and I support this change.

Essentially I see two uses for dotfolders:
1. Temporary things that should be invisible to the user and gitignored (as you suggest here).
2. Configuration files that are critical for operation, still invisible to the user (think `.git`).

For future proofing, I suggest that we use `.amplication_temp` as a folder name for anything temporary and gitignored. This will allow us, if needed, to introduce something like `.amplication` or `.amplicationrc` for project-specific configuration without facing conflicts.

**Comment by MichaelSolati** [comment]
@arielweinberger awesome, I'll start work on this on Monday and then let you and engineering review it and give me feedback.

**Comment by tupe12334** [comment]
@yuval-hazaz @arielweinberger @abrl91 @mshidlov @MichaelSolati In the following the Discord discussion, I think that is a good idea! just to make sure, you all talk about putting this folder inside the Amplication root folder right?
