### ISSUE TITLE
docs: incorrect class name in the description

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#2972]
### Describe the issue with documentation

![image](https://user-images.githubusercontent.com/43705455/175813336-5e2d4722-b8ab-4061-a0dc-80f93c9d2bb0.png)

### How to solve the problem

update the text in the description

**Comment by akash-mohanto** [comment]
I want to work on this issue...but not getting how to do it...please suggest some ways..as in what exactly it is asking??

**Comment by souravjain540** [comment]
> I want to work on this issue...but not getting how to do it...please suggest some ways..as in what exactly it is asking??

@MoFoGo can you help?

**Comment by akash-mohanto** [comment]
Yes...if it is possible from my side I will definitely do it..

**Comment by souravjain540** [comment]
> Hello, can I get this task assigned to me ?, it's pretty simple ig we just have to update the description

Assigned

**Comment by KlausMikhaelson** [comment]
Hello @souravjain540 I renamed that text in description and I can checked it locally on my device as well but I am facing an issue while pushing it i.e. remote: ```
Permission to amplication/docs.git denied to KlausMikhaelson.
fatal: unable to access 'https://github.com/amplication/docs.git/': The requested URL returned error: 403
```
it's my first time in open source can I get some help in it please

**Comment by souravjain540** [comment]
> Hello @souravjain540 I renamed that text in description and I checked it locally on my device as well but I am facing an issue while pushing it i.e. 
> 
> remote: Permission to amplication/docs.git denied to KlausMikhaelson.
> 
> fatal: unable to access 'https://github.com/amplication/docs.git/': The requested URL returned error: 403
> 
> 
> 
> it's my first time in open source can I get some help in it please 

Join our discord. I will help you.

But for only this issue I recommend you to follow contribution.md file.

This is happening because you have not forked and clone the repo but you have directly clone the repo and trying to push changes into it.

Please follow contributions.md steps and you will be all set.

**Comment by KlausMikhaelson** [comment]
Okay thank you got it !
