### ISSUE TITLE
Docs: Update the "Your first App"  article with updated screenshots 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2977]
### Describe the issue with documentation

Some of the screens in the "Your first application" article are out of date.

### How to solve the problem

Replace the screens with the latest version

**Comment by MoFoGo** [comment]
Hi @KlausMikhaelson. You should wait until release 0.13.2 before doing this (due in the next few days) as there will be additional changes to the screens (such as the Sandbox button being removed).

**Comment by KlausMikhaelson** [comment]
@MoFoGo Yeah will wait for that, thank you !

**Comment by KlausMikhaelson** [comment]
@MoFoGo Hey I have updated the images can you check it out ? https://github.com/amplication/docs/pull/172#issue-1296209833

**Comment by MoFoGo** [comment]
No longer relevant
