### ISSUE TITLE
Docs: Create a plan and template for an FAQ section on the Amplication website

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2979]
### Describe the issue with documentation

We do not currently have an FAQ section. Many of the inquiries we frequently receive from users and potential users, via Discord and Intercom, could be answered with an FAQ. 

### How to solve the problem

1. Collect a list of potential questions (from Intercom and Discord) 
2. Create a format/template
3. Decide where to place the FAQs (Docs or own page on Website)

**Comment by KlausMikhaelson** [comment]
@MoFoGo Hey has it  been assigned to someone? if not than would like to work on it

**Comment by yuval-hazaz** [comment]
@KlausMikhaelson @Prajnaprabhu3 thanks for suggesting your help 💜
we already have a process in place to work on this issue as a team effort with all stakeholders, so we will pass this time

**Comment by KlausMikhaelson** [comment]
@yuval-hazaz Okay !

**Comment by Prajnaprabhu3** [comment]
@yuval-hazaz yes alright.

**Comment by MoFoGo** [comment]
PR new-faq #179
