### ISSUE TITLE
🐛 Bug Report: forgot to files

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2987]
### What happened?

When we merge #2900 we forgot to delete the files ```packages/amplication-data-service-generator/src/version.ts``` and ```packages/amplication-data-service-generator/scripts/update-version.ts```

### What you expected to happen

Those files is no longer relevant That

### How to reproduce

not relevant

### Amplication version

0.13.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
I think the information about the version of the DSG is important and we should still reflect it somehow to the user. 
We should keep the version on the DSG and think about how to pass it back to the server or the logs
