### ISSUE TITLE
Change App structure. divide main page to three sections. header, footer and main content.

### ISSUE THREAD

**Issue by barshimi** [amplication/amplication#2990]

**Comment by KlausMikhaelson** [comment]
@barshimi Hey I do have experience with full stack development but it's my first time contributing to open source and I can do this for sure, can you please assign me this task ?

**Comment by yuval-hazaz** [comment]
@barshimi is already working on a massive change in the client to build a better structure including the new Project hierarchy, and the new header and footer.

@KlausMikhaelson we would love to help you with your first contribution. if you see any other task that you would like to work on, let us know and we will do our best to assign it to you.

**Comment by KlausMikhaelson** [comment]
@barshimi thank you, btw I made my first pr in open source today in the docs repo !
yeah I will be looking for more tasks today so will ask you! Thank you !

**Comment by arielweinberger** [comment]
Fixed in #3059
