### ISSUE TITLE
🐛 Bug Report: Generating an unwanted file

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3018]
### What happened?

When we generate a new service resource we anciently generate a ```server/package-lock.json.bak``` file

### What you expected to happen

This file don't needs to be there

### How to reproduce

generate a new service resource and check the path

### Amplication version

0.13.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
so the solution is to delete this file @tupe12334, right?

**Comment by tupe12334** [comment]
Yes @souravjain540

**Comment by yuval-hazaz** [comment]
this was fixed in 0.14.0
