### ISSUE TITLE
🐛 Bug Report: Getting wrong swagger UI

### ISSUE THREAD

**Issue by Manjit2003** [amplication/amplication#3026]
### What happened?

When running the app in a sandbox environment, I am not getting the correct swagger UI

### What you expected to happen

I should have got the swagger with the implication logo and custom CSS, though I am getting the default Swagger UI

### How to reproduce

Just run the app in the sandbox and head to the swagger

### Amplication version

Latest

**Comment by souravjain540** [comment]
Hi @Manjit2003 I saw you opened a support request in discord so closing this one :)

**Comment by yuval-hazaz** [comment]
@souravjain540 this is a bug, so I will re-open

**Comment by abrl91** [comment]
> Although sandbox is no longer being used, we should still test whether the Swagger UI in the dev env is running with the correct CSS file
> 
> @abrl91 can you please test and confirm whether we should close the issue or keep it open to be resolved?

yes!

**Comment by abrl91** [comment]
@yuval-hazaz @Manjit2003 
I ran it locally, LGTM

![image](https://user-images.githubusercontent.com/39680385/179961773-dae12d90-6ffc-4a3f-9665-9a1ed9bf25ce.png)

**Comment by yuval-hazaz** [comment]
cool, thanks. so we can close it
