### ISSUE TITLE
🐛 Bug Report: after the sandbox removal, we need a new design for the apps list page

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3033]
### What happened?

We need a new design for the apps list page
![image](https://user-images.githubusercontent.com/39680385/177557282-915b432d-bb41-4c7a-8ac2-dbe9e388e777.png)

and for the commits page
![image](https://user-images.githubusercontent.com/39680385/177559490-12665756-0a5c-484b-86e5-9db865bff7be.png)

### What you expected to happen

As we have only one step now (the code generation), we need to change the design of this page

### How to reproduce

open Amplication [app.amplication.com](https://app.amplication.com/)
you will see it on the apps list page and the commits page

### Amplication version

0.14.0

**Comment by yuval-hazaz** [comment]
@alexbass86 this should be included in your designs as part of the new project hierarchy. 
also, I think we should also show the details on the connection with GitHub (name of repo, last sync) 
please track this as part of the bigger picture, and I will close this issue

**Comment by alexbass86** [comment]
https://www.figma.com/file/Kff8xqeUk3luHmSbwsS9hF/%E2%9C%85--%233033---Update-design---App?node-id=836%3A18964 please use this  @yuval-hazaz @abrl91
