### ISSUE TITLE
🐛 Bug Report: sandbox removal - new design for build page

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3034]
### What happened?

![image](https://user-images.githubusercontent.com/39680385/177558611-115891e0-8281-442b-b75a-cccf772c8b1f.png)

### What you expected to happen

As we have only one step now (the code generation), we need to change the design of this page

### How to reproduce

open Amplication
create new app
Click on the build number button

### Amplication version

0.14.0

**Comment by alexbass86** [comment]
@abrl91 part of the new design already sent privately

**Comment by yuval-hazaz** [comment]
@abrl91 please note that we also have the step for sync with GitHub
