### ISSUE TITLE
🐛 Bug Report: Quit clobbering my .gitignore

### ISSUE THREAD

**Issue by matthewadams** [amplication/amplication#3038]
### What happened?

I want my `.gitignore` under my control, and should be a "gen once" file, not a "gen always" file.  I keep losing my changes when Amplication submits PRs containing updated `.gitignore` files.

### What you expected to happen

Don't make changes to `.gitignore` files.

### How to reproduce

Manually edit your `.gitignore` file, then accept a new PR from Amplication & see your manual changes go bye-bye.

### Amplication version

0.14.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@tupe12334 please look into it.

**Comment by tupe12334** [comment]
@matthewadams You are talking here on a specific file but we are working on a more complete solution that will overwrite your files on on a change from Amplication side

**Comment by yuval-hazaz** [comment]
I created a feature request for a more generic approach including the .gitignore file
#3051 
I will close this issue as duplicate so we can track progress on a single issue

**Comment by yuval-hazaz** [comment]
duplicate of #3051
