### ISSUE TITLE
Display Amplication version on UI

### ISSUE THREAD

**Issue by matthewadams** [amplication/amplication#3039]
### Feature description

Bug reports ask for the Amplication version, which is not readily available on the UI.  Please add an "About" section in the lower left of the UI that includes the version string that Amplication is running so that I can copy & paste it when filing issues.

### Use case

Need the Amplication version when filing a bug report.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@yuval-hazaz please see this

**Comment by yuval-hazaz** [comment]
I agree with @matthewadams 
@alexbass86 can you please have a look at this and suggest a place to add the version number on screen

**Comment by matthewadams** [comment]
...might be nice to have a copy icon next to it, or if you click on it it copies the version string to the clipboard...

**Comment by yuval-hazaz** [comment]
This should be included in the new layout after @barshimi completes the implementation 

The version number should be fetched from the server or can be generated on the client on build time like we do here:
https://github.com/amplication/amplication/blob/master/packages/amplication-data-service-generator/scripts/update-version.ts

@arielweinberger what is the best practice here?

**Comment by alexbass86** [comment]
@yuval-hazaz, Any update regarding this feature?

**Comment by yuval-hazaz** [comment]
Thanks for the reminder @alexbass86 . The new layout is now live and we can work on this. 

@arielweinberger what do you think about the source of the version number? should we fetch from the server or should we use local value in the client?
