### ISSUE TITLE
Docs: Custom code/controller action - incorrect path 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3040]
### Describe the issue with documentation

Damir — Today at 7:56 PM
There is an error here: https://docs.amplication.com/docs/custom-code/controller-action/

This path is invalid:
import * as basicAuthGuard from "../auth/basicAuth.guard";

Should be:
import * as basicAuthGuard from "../auth/basic/basicAuth.guard";

Import is not used so it can be removed as well. 
yuvalhazaz — Today at 8:43 PM

### How to solve the problem

Make the updates as described above

**Comment by Saksham-13** [comment]
Hey, this is my first time interacting with Amplication community, this looks like a good first issue, can I be assigned to it.

**Comment by yuval-hazaz** [comment]
hi @Saksham-13 
thanks for your support. 
@MoFoGo was away in the last few days and should be back soon. 
If I am not mistaken, this issue was fixed already, although I don't see the related PR. 

I will leave it for @MoFoGo to check that and assign you if it is still available.
