### ISSUE TITLE
Create custom environment example

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#3041]
Create a custom development environment. this will be an example PR for Amplication team for creating their personal development environments.

The example will include a doc that will go over the creation steps:
1. Creating GitHub apps for GitHub integration
2. Creating helm values file
3. Adding the new environment (namespace) to our CI
4. creating environment secrets

**Comment by arielweinberger** [comment]
@mshidlov Can you please add a description?

**Comment by yuval-hazaz** [comment]
@mshidlov should this still be open?

**Comment by mshidlov** [comment]
> @mshidlov should this still be open?

Yes this is ready to be merged
