### ISSUE TITLE
⭐️ Feature: Service Creation Wizard

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3043]
## Problem Statement
We want to provide new users with a smooth way to create a new service. This will be done via a wizard which serves two purposes:

1. Is very easy to use and comes with great defaults
2. Reveals the powers and customizability of Amplication

## Proposed Work
- Create a new **Service Creation Wizard** to achieve this.
- Temporarily, we will replace “Service” with “App” from a copy point of view.
- CSV import functionality is removed.

## Spec
- [Figma Design](https://www.figma.com/file/tDWS41YWDpGdTaRXpj7jWE/APP---Create-Wizard?node-id=788%3A10784) (owned by @alexbass86)
- [Notion Spec](https://www.notion.so/amplication/Service-Creation-Wizard-e8828881c3a54755a28baee4abea167b)
- By default, in the **APIs & Admin UI** section, we should enable all toggles.
- By default, in the **Sample Entities** section, "None" will be selected.

## Subtasks
- [x] #3044 
- [x] #3045 
- [ ] #3046

**Comment by alexbass86** [comment]
@arielweinberger @morhag90 done
