### ISSUE TITLE
🗒 Task: Copy & language review

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3046]
We need to determine the appropriate copy for the [Figma design](https://www.figma.com/file/tDWS41YWDpGdTaRXpj7jWE/APP---Create-Wizard?node-id=1178%3A5809).

More specifically, the "Lorem ipsum dolor sit amet" part.

**Comment by MoFoGo** [comment]
@arielweinberger @morhag90 @yuval-hazaz 

These are some suggestions for the wizard page text, for your consideration. 



# Option 1

Amplication Resource Creation Wizard

### Let’s start building your app

Select which components to include in your app and whether to use sample entities 

# Option 2

Amplication Resource Creation Wizard

### What components do you want in your app?

# Option 3

Amplication Resource Creation Wizard

### Select the components to include in your app

Choose from the following:  GraphQL, REST API (with Swagger UI), and Admin UI (requires GraphQL).  Also, you can choose to work with sample entities.



![image](https://user-images.githubusercontent.com/96979533/179403915-bc62e6f7-8245-46b3-837a-aa8b42b4785d.png)

**Comment by yuval-hazaz** [comment]
The terms are not accurate - both resource and app should be "service" in this example
Resource is a generic term for different types - in this case a "service"
App is the previous term for "service"

Let’s start building your service
Select which components to include in your service and whether to use sample entities

**Comment by morhag90** [comment]
@arielweinberger @yuval-hazaz @MoFoGo Do we have a a decision about the content?

**Comment by arielweinberger** [comment]
I don't have a preference for any of those. #1 seems more playful and less complicated to me, so I'll vote for that one.

I think this is also the one Yuval copy-pasted at the end of his comment.

**Comment by yuval-hazaz** [comment]
@MoFoGo please provide @morhag90 with the final version based on the comments above

**Comment by MoFoGo** [comment]
@morhag90 have you got this? This is the version to be used:

#


#### Amplication Resource Creation Wizard

## Let’s start building your app

#### Select which components to include in your app and whether to use sample entities

**Comment by GreenMachine01** [comment]
@MoFoGo is this item still in progress or can be closed?

**Comment by arielweinberger** [comment]
@GreenMachine01 It is already implemented. Let's close this.
