### ISSUE TITLE
Make a Readme for Amplication Organization

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#3052]
### Feature description

Currently we don't have any readme for the amplication organization.

There should be a readme that tell users about amplication and should contains logo and screenshots(if required) to make it look nice.

**Comment by AnujSsStw** [comment]
hey can I create one? if yes assign me!

**Comment by souravjain540** [comment]
Hello @AnujSsStw sure!, assigned :)

@MoFoGo please help him if needed.

**Comment by AnujSsStw** [comment]
@MoFoGo and @souravjain540 any suggestions?

<img width="960" alt="yes2" src="https://user-images.githubusercontent.com/92370865/178254187-4e07fe8b-6c72-4858-9d6c-a6149816d1b9.PNG">
<img width="960" alt="yes" src="https://user-images.githubusercontent.com/92370865/178254193-86e7764e-23f8-49d6-ac99-46a8bb0d7306.PNG">

**Comment by souravjain540** [comment]
Thank you so much for your PR @AnujSsStw!

@MoFoGo is currently on off, once he is back he will review this.

**Comment by abrl91** [comment]
resolved by https://github.com/amplication/.github/pull/2
