### ISSUE TITLE
🐛 Bug Report: Do not include field "roles" in UserUpdateInput

### ISSUE THREAD

**Issue by matthewadams** [amplication/amplication#3054]
### What happened?

The generator includes `roles` in the generated `UserUpdateInput`.  This doesn't make sense, because that field should not be editable.  This issue is related to https://github.com/amplication/amplication/issues/3053.

### What you expected to happen

The generator shouldn't include `roles` in the `UserUpdateInput` class.

### How to reproduce

Use Amplication.

### Amplication version

0.14.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@matthewadams why do you think this field should not be included in the user record? 
The idea is that different users can be assigned to different roles by the admin so they can have a different set of permissions

**Comment by matthewadams** [comment]
It's fine for a `User` entity to have a `roles` field, but it shouldn't be editable, otherwise a `User` could give themselves additional roles.  This issue relates to https://github.com/amplication/amplication/issues/3053.

**Comment by yuval-hazaz** [comment]
so, that depends on the permissions of the user. If the user has a role that allows them to update the "roles" field so so it is ok.

**Comment by matthewadams** [comment]
@yuval-hazaz IMHO, that implies the notion of self-promotion.  It seems like an awkward justification to me.  You're essentially saying that "a user is permitted to change their roles", which is almost never true in real applications.  There are usually business rules that dictate when, say, a `teller` can become a `branchManager`, and only `branchManager`s can promote a `teller` (by adding the `branchManager` to the `User`'s `roles`.

**Comment by yuval-hazaz** [comment]
The way I look at it, usually there is a specific role that can set the permissions of users in the system. e.g. "permissions manager", "security manager", or even "admin"

**Comment by matthewadams** [comment]
Yes, @yuval-hazaz.  I would argue that the generator, by default, should generate roles `user` & `admin` by default (for single-tenant applications) and should generate `user`, `admin` & `superadmin` for multi-tenant applications.  In the latter case, `admin`s would be an admin of the tenant, whereas `superadmin` would be for adminstrators across all tenants.  However, that feature merits its own issue so as not to cloud this one.

**Comment by yuval-hazaz** [comment]
Thanks @matthewadams 
I will leave #3060 open to track the different built-in roles needed. 
I will close this issue, as we leave the design of the roles management as it is, where the different roles as predefined, but the roles assignment is done on run time by users who can assign roles
