### ISSUE TITLE
new project sreen

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3057]
### Feature description

create the new project sidebar: create a project, view project, and view projects

related issues: #2782 and #3077

- [x] #3111
- [x] #3112
- [x] #3117
- [x] #3118
- [x] #3122

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by muhsinkamil** [comment]
Hey @abrl91, Anything left to pick up on this ? ( Sorry, little late, I guess ? )

**Comment by abrl91** [comment]
> Hey @abrl91, Anything left to pick up on this ? ( Sorry, little late, I guess ? )

No, everything is done here. Sorry

**Comment by abrl91** [comment]
All issues have been resolved
