### ISSUE TITLE
⭐️ Feature: ProjectConfiguration resource ProjectConfigurationSettings block

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3058]
## Problem Statement

We want to give the project entity the power of the dynamic block entity including the track, commit and history

## Proposed Work

1. Add a resource type ProjectConfiguration
2. Add block type ProjectConfigurationSettings

The hierarchy of the data is:
### Project
the project entity that holds all the resources @abrl91 
generate when the user creates one.

### ProjectConfiguration
the resource that holds the data of the project.

### ProjectConfigurationSettings
the block that holds the trackable and committable data of the project 

### Notes
- The ProjectConfiguration and ProjectConfigurationSettings auto-generate with the generation of a new project and undeletable

**Comment by abrl91** [comment]
> @tupe12334 What's the status update on this? #3085 has been merged.

Yes. it was merged into https://github.com/amplication/amplication/issues/3132
