### ISSUE TITLE
🚀Enable to choose default valuse on field

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3063]
### Feature description

An ability, on the UI, next to (almost) every field, may not entity related field, an option to set a default value.

### Use case

For example, for Product, the field "In stock" is boolean and it would be helpful to set a default value to true for example.

![image](https://user-images.githubusercontent.com/39680385/178147604-cfd97498-aad8-4783-b998-f0144d944f2d.png)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@abrl91 this looks like a duplicate of #1045

**Comment by abrl91** [comment]
duplicated
