### ISSUE TITLE
🐛 Bug Report: Github connect button - Wrong Width & Padding

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3066]
### What happened?

![image](https://user-images.githubusercontent.com/96179897/178148812-387a42f9-c83e-4753-a442-277eaf9571d0.png)

We need to ensure that the button width of "Connect to GitHub" is precisely like the dropdown. Please make sure the padding on the button & dropdown 12px and not 16px.

### What you expected to happen

Connect to GitHub Button width should be the same as a dropdown.

### How to reproduce

Create a new app and go to code view without connecting to GitHub.

### Amplication version

0.14.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@alexbass86 can I take it for campaign?

**Comment by alexbass86** [comment]
@tupe12334 it's now with the proper width. The problem is that the look of this button is different from the original design, please make sure the border line is in the current color, and the icon needs to be in the center. 
It's just floating there. Hight of the button is also different from the original design.

Bad
![image](https://user-images.githubusercontent.com/96179897/185073804-3ac0df0e-e81b-4ca5-a40c-73598f793f7e.png)

Good
![image](https://user-images.githubusercontent.com/96179897/185073830-58fb374e-98fc-4fef-b567-87d714d78f72.png)

Figma
https://www.figma.com/file/a9AGIkvVQ5vqPHB6MHlsZ3/%232665---View-Code?node-id=762%3A13049

**Comment by alexbass86** [comment]
@tupe12334 any update?

**Comment by tupe12334** [comment]
@alexbass86 We no longer have this button in our system, so I close this issue.
