### ISSUE TITLE
custom controller - mention that the decorators must be copied

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3075]
### Describe the issue with documentation

when the user adds custom code to the root controller of an entity, even though this method calls the `super()' class. method, all the decorators of this method must be copied from the base class.
The example on the docs shows that, but it preferable to mention it also with words

https://docs.amplication.com/docs/custom-code/controller-action/

### How to solve the problem

add a sentence that emphasizes that the decorators must be copied, although the use of `super()`

**Comment by MoFoGo** [comment]
@abrl91 see PR https://github.com/amplication/docs/pull/176
