### ISSUE TITLE
Support generators for different architectures and technologies

### ISSUE THREAD

**Issue by matthewadams** [amplication/amplication#3087]
### Feature description

Allow me to generate state-based (current implementation), CQRS, or other architectural styles given my entity model.

### Use case

I'm a big fan of the CQRS architecture, something that Nest.js supports out of the box.  Allow me to specify that the code generator should generate one of several different system architectures.  The current, state-based architecture is a fine default, but also allow me to specify a Nest.js-based CQRS architecture.  Bonus points for allowing me to select one of many different generators, essentially making libraries or plugins out of generators.

I think this will require separating the metadata of a project from the generator, so that the metadata is independent of the generators, and the generators use the metadata to generate whichever flavor of application is desired.  There could be different generators not only within the Nest.js space, but also generators for, say, Spring Boot with Java or Kotlin, Laravel, Ruby on Rails, or literally any other architecture or technology.  Note that architecture is orthogonal to the desired technology, meaning you could generate CQRS or state-based, or any other architecture for any technology for which there is a generator that accepts Amplication-compliant metadata.  Target technologies could inclue Spring Boot + Kotlin, Spring Boot + Java, Nest.js + Typescript, Laravel, Ruby on Rails, Akka + Java, Akka + Kotlin, and so on.  Kind of the Grand Unification Theory of Reentrant/Customizable Application Generators.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

_Note: had several beverages before entering this issue.  I know it's a big, pie-in-the-sky request, but, hey, let's know where we're going, right? 😊_

**Comment by souravjain540** [comment]
@yuval-hazaz
