### ISSUE TITLE
Add build logs polling functionality

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#3109]
The build flow is updated to be async instead of sync process. when amplication client triggers a build the API returns with the build ID without waiting for the process to be completed as it use to. To support the change and keep the build page showing logs as they arrive, we need to create a new endpoint in the amplication server to support log retrieval, and client-side functionality to consume incoming logs.

**Comment by mshidlov** [comment]
@EugeneTseitlin please check in earlier versions to 0.14.0 we had this functionality in the sandbox deployment

**Comment by EugeneTseitlin** [comment]
@mshidlov @arielweinberger It seems to be irrelevant. Should I just close the issue?

**Comment by mshidlov** [comment]
@EugeneTseitlin do you implement that functionality?

**Comment by yuval-hazaz** [comment]
This is handled differently as part of the DSG separation. 
closing
