### ISSUE TITLE
Docs: 031 Redirects 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3128]
### Describe the issue with documentation

See attached file from line 8 to line 28
We need to fix the links as described – from the current value as described in column C to the new value in column D
[amplication - redirects to be replaced.xlsx](https://github.com/amplication/amplication/files/9127110/amplication.-.redirects.to.be.replaced.xlsx)

**Comment by Shubh28698** [comment]
Hi @MoFoGo ,

I am getting little confused here. Can you give me an example of where to edit the links. (means in which location)

**Comment by MoFoGo** [comment]
@Shubh28698 - this has been fixed. Thanks for your interest.

**Comment by Shubh28698** [comment]
> @Shubh28698 - this has been fixed. Thanks for your interest. 

Any other issue you would like me to work on?
