### ISSUE TITLE
🐛 Bug Report: Focus effect is missing on create new repository model

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3188]
### What happened?

In sync with GitHub page, when clicking on `create repository` button there is no focus effect on the input.

https://user-images.githubusercontent.com/39680385/180040116-c77130ef-c1fa-4292-9fc7-5212a18db39e.mov

### What you expected to happen

I expect that when I click on this button, the state of the input will be in focus.

### How to reproduce

See on the attached video

### Amplication version

0.14.4

**Comment by moulibrota-das** [comment]
Hi @abrl91, I would like to work on this issue can you assign me?

**Comment by abrl91** [comment]
> Hi @abrl91, I would like to work on this issue can you assign me?

Done 😄 good luck!

**Comment by abrl91** [comment]
Hey @moulibrota-das are you working on this issue?

**Comment by moulibrota-das** [comment]
@abrl91 I have still not started working on it.

**Comment by munyoudoum** [comment]
would like to try this if you don't mind 😄

**Comment by souravjain540** [comment]
sure @munyoudoum!

Join our discord if you need any help :)
