### ISSUE TITLE
🐛 Bug Report: Generated App - broken links to GraphQL playground and Swagger 

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3189]
### What happened?

After setting up the dev environment of the generated app and navigating to `localhost:3001`, clicking on `continue` is not working for GraphQL and Swagger. The button redirects to the wrong URL

https://user-images.githubusercontent.com/39680385/180044206-77264eee-c8e0-4ecd-8330-4be329bf6f4b.mov

### What you expected to happen

Those links should redirect to `localhost:3000/graphql` and `loacalhost:3000/api`

### How to reproduce

Run your generated app locally:
https://docs.amplication.com/docs/getting-started/dev-env/#step-2---install-packages-from-npm-for-the-server

Then open your browser on `localhost:3001`

### Amplication version

0.14.4

**Comment by KlausMikhaelson** [comment]
Hey @abrl91 I would like to work on it, can you assign it to me ?

**Comment by abrl91** [comment]
> Hey @abrl91 I would like to work on it, can you assign it to me ?

Go for it :)

**Comment by KlausMikhaelson** [comment]
Hey @abrl91 Ig I am not able to figure out how we have to make those changes so if anyone does know about that than please go ahead

**Comment by abrl91** [comment]
> Hey @abrl91 Ig I am not able to figure out how we have to make those changes so if anyone does know about that than please go ahead

@KlausMikhaelson 
Would you like our help with that?

**Comment by KlausMikhaelson** [comment]
@abrl91 yeah would love that can I text you on discord ?

**Comment by abrl91** [comment]
@KlausMikhaelson  for sure 😃

**Comment by tupe12334** [comment]
This has been fixed in #3354
