### ISSUE TITLE
🐛 Bug Report: Generated App - the icons on the login page are not loaded

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3190]
### What happened?

The icons on the login page of the generated app are not loaded

![Screen Shot 2022-07-20 at 20 08 12](https://user-images.githubusercontent.com/39680385/180064274-a7cf1ad2-befd-4da8-82e5-6d29f88f9063.png)

### What you expected to happen

I expect to see the icons and not the value of `alt` attribute.

### How to reproduce

Run your generated app locally:
https://docs.amplication.com/docs/getting-started/dev-env/#step-2---install-packages-from-npm-for-the-server

Then open your browser on `localhost:3001`

### Amplication version

0.14.4

**Comment by muhsinkamil** [comment]
@abrl91 Can I take this issue. 
Pls assign to me :)

**Comment by abrl91** [comment]
> @abrl91 Can I take this issue. Pls assign to me :)

done :)

**Comment by muhsinkamil** [comment]
Hey @abrl91, 
Seems like, this is an issue with hosted assets path: 

- https://amplication.com/assets/graphql.png
- https://amplication.com/assets/react-admin.png
- https://amplication.com/assets/restapi.png

Is the hosted path changed ? Or Can I know how we can access this ?

**Comment by abrl91** [comment]
> Hey @abrl91, Seems like, this is an issue with hosted assets path:
> 
> * https://amplication.com/assets/graphql.png
> * https://amplication.com/assets/react-admin.png
> * https://amplication.com/assets/restapi.png
> 
> Is the hosted path changed ? Or Can I know how we can access this ?

@yuval-hazaz ?

**Comment by souravjain540** [comment]
@yuval-hazaz please update

**Comment by yuval-hazaz** [comment]
It is better to include the files in the generated app instead of linking to an external assets

Look for the files in the old fepo of our website 
https://github.com/amplication/site

**Comment by GreenMachine01** [comment]
@abrl91 please check if this was already fixed.
