### ISSUE TITLE
🐛 Bug Report: It is creating PR towards 'main' branch not the default branch

### ISSUE THREAD

**Issue by kwinyyyc** [amplication/amplication#3192]
### What happened?

After build, Amplication is creating PR towards 'main' branch not the default branch, if there is no 'main' branch a PR won't be created

### What you expected to happen

The PR is created targeting to merge into the default branch

### How to reproduce

Click rebuild and trigger the PR creation

**Comment by arielweinberger** [comment]
@yuval-hazaz This seems like a very important one to fix. A lot of projects currently use `master`.

@kwinyyyc Thanks for reporting - we'll pick this up ASAP.
