### ISSUE TITLE
🐛 Bug Report: Generated App - `@prisma/client` is installed in the dev dependencies instead of in the dependencies

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3201]
### What happened?

In the `package.json` of the generated app, `@prisma/client` is installed by mistake as a dev dependency

### What you expected to happen

`@prisma/client` should be installed as a regular dependency and not a dev dependency

### How to reproduce

Generate an app and look at the `package.json` file

### Amplication version

0.14.5

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by arielweinberger** [comment]
Fixed at #3202
