### ISSUE TITLE
⭐️ Unified Logging - `@amplication/nest-logger-module`

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3209]
# Unified Logging
## Introduction
We need a standard logging solution that is easy to consume in our back-end microservices, as a TypeScript package called `@amplication/nest-logger-module`. This should be an abstraction, and not require work with underlying logger solutions.

This solution must support structured logging, which enables us to perform robust and effective queries on Kibana.

## Requirements
- The logger is easily consumable in our monorepo as `@amplication/nest-logger-module`
- Must support the following log levels: `DEBUG` (3), `INFO` (2), `WARN` (1), `ERROR` (0). We can make `INFO` the default.
- Log level should be configurable when importing the module. Default value should be `INFO`.
- Logs are sent in as [Structured Logs](https://www.sumologic.com/glossary/structured-logging/#:~:text=Structured%20logging%20is%20the%20practice,data%20sets%20rather%20than%20text.)
- Local development logs are pretty-printed so they are easy for developers to work with. This should not be done for production logs.
- A detailed `README.md` with an example of how to consume the library.
- This library abstracts whatever technology it uses behind the scenes, such as `nest-winston` etc. Consumers should not have to import Winston-specific modules or types.
- Logs format supports the ELK stack (Elastic, Logstash, Kibana) 

### Logger Library
As originally started at #2616 we will utilize `nest-winston` and create a wrapper around it.

### Structued Logs
The structured JSON should support the following fields:
- timestamp.
- level (`DEBUG`, `INFO`, `WARN`, `ERROR`).
- message (string, required): Human readable log message.
- context (object, optional, defaults `{}`): Useful context related to the process in which the log was produced.
- service (string, required): Identifies the service that produced the log.

## API - NestJS Module
This should be a NestJS module that is easy to consume into microservices.
```ts
// x.module.ts
import { AmplicationLoggerModule } from "@amplication/nest-logger-module";

@Module({
  imports: [
    AmplicationLoggerModule.forRoot({ service: 'amplication-server' });
  ]
})

// x.service.ts
import { AMPLICATION_LOGGER_PROVIDER, Logger } from '@amplication/nest-logger-module';

export class SomeService {
  constructor(@Inject(AMPLICATION_LOGGER_PROVIDER) private readonly logger: Logger) { }
}
```

## Tasks

- [ ] New amplication nest-logger-module
- [ ] Update the existing package to the new logger package

## Next Steps
Finishing this task will allow us to enhance our monitoring and observability capabilities (tackled in separate issues):
- Use robust querying capabilities on Kibana via Logz.io.
- Implement distributed tracing across our microservices and identify points of failure.

**Comment by arielweinberger** [comment]
@tupe12334 Is everything clear on your end? Let me know if you need to go through this spec or if you're good to go.

**Comment by arielweinberger** [comment]
Added

**Comment by tupe12334** [comment]
> @tupe12334 Is everything clear on your end? Let me know if you need to go through this spec or if you're good to go.

Yes the spec is clear and I started to work on that
