### ISSUE TITLE
Update sign-up route to new create service wizard 

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#3215]
### Feature description

A new page was added : create service wizard, this page replace the existing create app page. 
Now, we need to change the route, so  after sign-up to it will route to create service wizard. 

### Use case

After user sign-up, route to create service wizard page.

**Comment by souravjain540** [comment]
is this issue in progress? @morhag90

**Comment by morhag90** [comment]
@souravjain540  yes :)
