### ISSUE TITLE
⭐️ Adding `.amplicationignore`

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3222]
There is a problem today with making a new Amplication pr without overwriting the existing work of users.
We want to add .ampignore file in the root folder, and block overwrite in those files

## Implementation
- We will use a `.amplicationignore` file to define the files to ignore.
- We will use the roto `.amplication/*` folder to save the ignored files on codegen - in this case `.amplication/ignored/[commit-id]`

**Comment by yuval-hazaz** [comment]
This fix is a temporary and undocumented fix to allow advanced users more manual control of the code sync with GitHub. 
The .ampignore file should work like .gitignore, and .dockerignore files where each line describes a separate rule using GLOB pattern matching. 
We should not support at this stage the option for a negative rule (to exclude files from an ignored folder, for example)


The implementation of the .ampignore file has a side effect that will prevent the developers from knowing if the ignored file was updated or not in the commit. 
To work around it, I suggest that we will push all the ignored files to a new folder under .ampignored/[commit-id]/ 
This will allow the developer to manually compare the ignored files and take any changes from them if they want to. 

@arielweinberger @mshidlov @tupe12334 @abrl91 please add your thoughts and comments

**Comment by arielweinberger** [comment]
Sounds good. Two questions:
1. Not sure about naming. `.ampignore` is shorter and neater, but `.amplicationignore` is more accurate.

2. Did we check if there is an open-source package that handles glob patterns gitignore-style to handle this for us?

**Comment by tupe12334** [comment]
After discussion with @yuval-hazaz We decided that the expected behavior is that the file will be generated even if its on .amplicationIgnore if it does not exist but will not be on the pr if it already exists.
So the .amplicationignore file is ignored for overwrite

**Comment by arielweinberger** [comment]
With regards to the ignored folders with commit ID reference, let's take advantage of the plan in #2997 

Let's create an `.amplication` folder, and under that, use an `ignored` folder. Using a common `.amplication` folder for all of our "Amplication managed" code stuff will be scalable and won't pollute the project filesystem.
