### ISSUE TITLE
🐛 Bug Report: hubspot integration is incorrect

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3227]
### What happened?

This is the current code to identify users in packages/amplication-client/src/util/analytics.ts
_hsq.push(["identify"], { user: userId, ...props });

But, the props object should be in the second position in the array and not as the second prop of the function external to the array as it is right now. 

also, we are using the property "user," but according to the docs, it is better to send the property id with the User ID

### What you expected to happen

This is the correct code:

_hsq.push(["identify", { id: userId, ...props }]);

### How to reproduce

n/a

**Comment by arielweinberger** [comment]
Fixed in #3228
