### ISSUE TITLE
🐛 Bug Report: `npm run bootstrap` is failing on `@nestjs/passport` peer dependency

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3230]
### What happened?

We updated `@nestjs/passport` version to `8.2.2` on `amplication-data-service-generation` but now npm run bootstrap is failing inconsistency because of this dependency on other packages: `storage-gateway` and `server`.

### What you expected to happen

`npm run bootstrap` should be completed successfully.

### How to reproduce

clone amplication
```
cd amplication
npm i
npm run bootstrap
```

### Amplication version

0.14.6

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by arielweinberger** [comment]
Fixed in #3231
