### ISSUE TITLE
Delete kubectl commands through deploy.yaml 

### ISSUE THREAD

**Issue by shaharblanksela** [amplication/amplication#3237]
### Feature description

Working only with argocd commands to able to get fully sync on the cluster.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GreenMachine01** [comment]
@mshidlov @arielweinberger 
Do we need this item?
Please explain it

**Comment by yuval-hazaz** [comment]
@shaharblanksela

**Comment by shaharblanksela** [comment]
Not relevant anymore.
