### ISSUE TITLE
delete-namespaces pipeline - add new developers namespaces + confirmation step

### ISSUE THREAD

**Issue by shaharblanksela** [amplication/amplication#3239]
### Feature description

Adding more developers namespaces & Adding validation for deletion by confirm the namespace to delete.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GreenMachine01** [comment]
@mshidlov @arielweinberger 
Do we need this item?
Please explain it

**Comment by yuval-hazaz** [comment]
I dont think we need it, but @arielweinberger or @shaharblanksela can cofirm

**Comment by shaharblanksela** [comment]
Already been added to the pipeline.
