### ISSUE TITLE
Update `amplication/cli` queries according to the new hierarchy 

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3244]
### Feature description

Update `amplication/cli` queries according to the new hierarchy: Workspace => Project => resource

### Use case

Queries that need to be updated:
- getResources: add `projectId` to the query
- createResource: add  `projectId` to the mutation

**Comment by souravjain540** [comment]
@abrl91 please use labels

**Comment by jainpawan21** [comment]
Can I work on this?

**Comment by abrl91** [comment]
> Can I work on this?

Good luck 😃

**Comment by Saman555** [comment]
Can I work on this issue???

**Comment by souravjain540** [comment]
@Saman555 assigned.

**Comment by souravjain540** [comment]
@Saman555 please update otherwise i have to assign it to someone else

**Comment by martinez-hugo** [comment]
Hi ! Can I work on this issue ?

**Comment by abrl91** [comment]
This issue is stale. We need to decide weather we want to delete the cli or create a new issue describing all the deficiencies of the cli

@mulygottlieb @GreenMachine01
