### ISSUE TITLE
Update new routes components after route refactor

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#3246]
### Feature description

After routes refactor, we need to update all routes props and ensure everything works as expected.

- [x] #3253
- [x] #3255

### Use case

Every route in the system will open the right page

**Comment by muhsinkamil** [comment]
@morhag90 @abrl91 Can I help with this ? Or you already working on it ?

**Comment by morhag90** [comment]
Hi @muhsinkamil we already working on this issue. 
Thank you :)
