### ISSUE TITLE
Research Branch Strategy (GitHub Sync)

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3247]
# The Ask
We need to figure out how we utilize GitHub to improve our ability to manage custom code/syncing with GitHub, using a smart branching strategy. If this proves successful, we believe this will help us avoid conflicts. Once resolving a conflict once, it theoretically should not occur again.

To be more specific, we want to investigate the feasibility of using an Amplication-specific branch, for example `amplication`, which will act as a base branch for all Amplication PRs.

We assume that by performing this split of branches (e.g. `master` and `amplication`) early on, as soon as the app is generated, and continuing adding custom code to `master` (without ever rebasing `master` into `amplication`), we will avoid conflicts related to users' custom code.

This is an initial research task that will evolve into a wider feature design.

# Open Questions
- How to prevent the user from deleting this `amplication` branch?
- How to prevent rebasing `master` into `amplication` which will compromise this method?
- When merging from `amplication` into `master`, how do we make sure we don't perform a rebase towards `amplication`? This is often suggested by GitHub.
- What happens when there is an actual conflict that needs to be resolved? How can the user resolve it without rebasing?
- If problems arise from the previous question, is it worth restricting the `amplication` branch, so it can only be merged by an Amplication API (this is a bit farther)?
- What's the impact if somehow there is a rebase of `master` into `amplication`?
- Is it worth that we use a dynamic branch that is created on the fly from a specific commit in the history (which is the first commit by Amplication)?

**Comment by GreenMachine01** [comment]
Was done as part of https://github.com/amplication/amplication/issues/3751
