### ISSUE TITLE
Connect Amplication server to GitHub

### ISSUE THREAD

**Issue by doudoubean** [amplication/amplication#3249]
### Describe the issue with documentation

When using the hosted service on https://app.amplication.com/, the integration is pre-configured and you just need to follow [this guide](https://docs.amplication.com/docs/sync-with-github/) to sync your application with GitHub. Can you provide much more detailed configuration doc about your pre-configured? When I run a local Amplication server based on your  doc, but that does not   
succeed.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mshidlov** [comment]
We have a [doc](https://docs.amplication.com/docs/connect-server-to-github/) that explains the server setup but it has issues @MoFoGo please contact @tupe12334 and update the doc.
