### ISSUE TITLE
🐛 Bug Report: New UI -  Popup for changes

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3250]
### What happened?

We added a new toggle to support "[Private repo selection](https://github.com/amplication/amplication/pull/2851)" on the edit popup to have more consistent behavior each time we have this type of popup. I redesigned it to make sure it will support future additions such as toggles, buttons, text, etc...
Also, this new design is now aligned with our refreshed app visual language.

[Figma file](https://www.figma.com/file/8Q9kB3b29FCh9ttVmOHm9u/%232851---Private-repo---Popup?node-id=1601%3A5670)

![180787480-f7cdf226-0c04-4ad6-af9c-f993d84a2617](https://user-images.githubusercontent.com/96179897/181477137-6486ed8d-3645-4f7a-9b76-0091a1e8186e.png)

### What you expected to happen

We need to make sure our popup for "[Private repo selection](https://github.com/amplication/amplication/pull/2851)" and other popup are aligned with the new design.

### How to reproduce

Go to sync with GitHub tab and click on create a repository.

### Amplication version

0.14.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by arielweinberger** [comment]
Removing the 0.15.0 from this one. @souravjain540 I think we could let the community pick this up.

**Comment by aakankshadhurandhar** [comment]
@souravjain540 Can you please assign me this issue?

**Comment by souravjain540** [comment]
done @aakankshadhurandhar

**Comment by aaaaayushh** [comment]
Hi is this issue up for grabs?
