### ISSUE TITLE
Amplication folder icon

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3251]
As one of the most installed icon themes in VSCode [Material Icon Theme](https://github.com/PKief/vscode-material-icon-theme) doesn't have the Amplication logo for the .amplication folder.
I think that we need to create the icon as I mention in https://github.com/PKief/vscode-material-icon-theme/issues/1628 issue

**Comment by arielweinberger** [comment]
I suggest adding an icon for `.amplicationignore` as well.

**Comment by yuval-hazaz** [comment]
@tupe12334 I think this is a good idea
@alexbass86 this one for you

**Comment by tupe12334** [comment]
@alexbass86 Be aware that there is a standard for this UI lib
https://github.com/PKief/vscode-material-icon-theme/blob/main/images/folderIcons.png

**Comment by alexbass86** [comment]
> @alexbass86 Be aware that there is a standard for this UI lib https://github.com/PKief/vscode-material-icon-theme/blob/main/images/folderIcons.png
From what I saw, this is a standard SVG icon, the color of the folder is decided on the developer side, right? Please forward me more info regarding this task.

**Comment by tupe12334** [comment]
@alexbass86 https://github.com/PKief/vscode-material-icon-theme/blob/main/CONTRIBUTING.md#add-new-icons
I don't see any think about color change in there tutorial.

**Comment by alexbass86** [comment]
@tupe12334 p
