### ISSUE TITLE
update login and signup routes

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3255]
Update login and signup routes to work with the new implementation of our routes

**Comment by abrl91** [comment]
`login` and `signup` routes are working.
According to `routesUtil` file, if the user is authenticated, it redirects to `/`. The problem is that the new routes and layouts `/` leads to nowhere. 
To fix it we need to change the `/` to `/:currentWorkspaceId/currentProjectId`

![image](https://user-images.githubusercontent.com/39680385/181722878-e4f0e50a-ef83-4731-85f2-82f3d84a5bfd.png)

**Comment by barshimi** [comment]
it's not true... `/` leads you to App.tsx. there you have a check for getting the current workspace if the user is authenticated, if not it redirect the user to `/login`. lets talk about it

**Comment by abrl91** [comment]
> it's not true... `/` leads you to App.tsx. there you have a check for getting the current workspace if the user is authenticated, if not it redirect the user to `/login`. lets talk about it

Yes. I saw this. but I think we should cover the case that a user navigates through the URL to `/login` or `/signup` while he/she authenticated

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/3257
