### ISSUE TITLE
🐛 Bug Report: When creating a new workspace it redirects to `/workspaceId` but the UI is broken

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3260]
### What happened?

 When creating a new workspace it redirects to `/workspaceId` but not to `/currentWorkspaceId/currentProjectId`
 It seems the request is not creating a new project automatically as the project list is empty: 
 
![image](https://user-images.githubusercontent.com/39680385/182018241-9f655493-2375-42c5-b93e-a1f7460b03f4.png)

https://user-images.githubusercontent.com/39680385/185851011-6fdadb11-4260-4a9f-af1b-247edf233d51.mov

### What you expected to happen

I expect to be redirected to `/currentWorkspaceId/currentProjectId` and see the project list sidebar with the newly created project selected

### How to reproduce

Create a new workspace 

### Amplication version

0.15.0

**Comment by morhag90** [comment]
@abrl91  Can we close this issue?

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/3554
