### ISSUE TITLE
🐛 Bug Report: Inconsistency between the autogenerated project and creating a new project

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3261]
### What happened?

When a user signs up, a new workspace with an autogenerated project is created with an auto-generated service.

![image](https://user-images.githubusercontent.com/39680385/182019807-cb3b3778-611b-4df3-9034-6a2bd2a3af44.png)

When a user creates a project manually, he gets a project with `Project Configuration`

![image](https://user-images.githubusercontent.com/39680385/182019971-63ade013-310f-4e92-ac19-033238bdda34.png)

### What you expected to happen

I expect that on every project creation, automatically or manually, `Project Configuration` will be created automatically

### How to reproduce

Signup and then create a new project. You will see that the autogenerated project that you get doesn't have `Project Configuration` and the one that you create manually has the `Project Configuration`.

### Amplication version

0.15.0

**Comment by souravjain540** [comment]
@abrl91 labels?
