### ISSUE TITLE
🐛 Bug Report: Missing $schema property for our prettier rc files

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3268]
### What happened?

In our .prettierrc files we dont have a $schema property that provide meta about this file, it will be nice to add this to all of our .prettierrc files like in this example
https://github.com/azz/prettier-config/blob/master/index.json

### What you expected to happen

not relevant

### How to reproduce

not relevant

### Amplication version

0.14.9

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Vipul2504** [comment]
Hello @tupe12334 Can I contribute to this issue?

**Comment by tupe12334** [comment]
Of course, go a head @Vipul2504

**Comment by Vipul2504** [comment]
yes, thank you. I have to write the above template in a given path?

**Comment by arielweinberger** [comment]
@Vipul2504 Hey, will you be able to finish this in the next two days? Otherwise we'd like to hand it over to the community for our new campaign.

**Comment by Vipul2504** [comment]
Hey @arielweinberger I will complete today itself

**Comment by Rutam21** [comment]
@arielweinberger @tupe12334 As this issue seems to be stale till now, please assign it to me so that I can raise a PR for this at the earliest. Thanks.

**Comment by yuval-hazaz** [comment]
go ahead @Rutam21 
thanks
