### ISSUE TITLE
Upgrade Lerna to version `5.x`

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3272]
### Feature description

In the future, we plan to migrate to a next-generation monorepo technology (Nx or Turborepo).

Whatever tool we choose, we will most likely choose a gradual migration strategy. As an intermediate step, we need to migrate to Lerna `5.x`. Aside from being much faster (incorporating the same Nx caching strategy), Lerna 5 can integrate with both Nx and Turborepo, which will assist us in future migration.

## Resources
- [Lerna 5.1 — New website, new guides, new Lerna example repo, distributed caching support and speed!](https://blog.nrwl.io/lerna-5-1-new-website-new-guides-new-lerna-example-repo-distributed-caching-support-and-speed-64d66410bec7)
- [How Lerna just got 10x faster!
](https://blog.nrwl.io/lerna-used-to-walk-now-it-can-fly-eab7a0fe7700)

### Use case
N/A

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by arielweinberger** [comment]
Fixed in #3273

**Comment by tupe12334** [comment]
@mshidlov Can you please provide the CI action that crashed?

**Comment by arielweinberger** [comment]
Reopening as this one seems to be tricky. Reverted again.

**Comment by LinboLen** [comment]
Nx, please. can create nx setup pull request first. maybe I can help migrate to nx.

**Comment by GreenMachine01** [comment]
@mshidlov @arielweinberger 
Do we need this item?
Please explain it

**Comment by yuval-hazaz** [comment]
we can close this. @arielweinberger is working on another initiative to migrate to nx
