### ISSUE TITLE
🧹 Convert `src/` imports to be relative

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3313]
# Description
Very often, I see imports that start with `/src`. This is bad for two reasons:

1. This is inconsistent. Some imports are relative, and some are not.
2. It is a bad practice. The concept of an `src` folder is not something our code should care about.

Go over our codebase and modify the `/src` imports to be relative.

The affected packages:
- `packages/amplication-server`
- `ee/packages/amplication-git-push-webhook-service`
- `packages/amplication-git-pull-request-service`

 # Subtasks
- [x] #3314
- [x] #3316
- [x] #3315

**Comment by yuval-hazaz** [comment]
@souravjain540 the two sub-issues here can be used for the next DIFT

**Comment by ParkourKarthik** [comment]
:wave: @arielweinberger I picked up the issue #3314 to work on it. But I believe that using absolute imports would be nicer for imports where there are deeply nested folder hierarchy. And the current structure already makes use of it in essential places. Regarding the dependency over the concept of `src` folder, we can still make use of `paths` in the `tsconfig.config` for alias if required. Below are some of the reference articles that could be of use.

https://javascript.plainenglish.io/why-and-how-to-use-absolute-imports-in-react-d5b52f24d53c
https://hackernoon.com/react-pro-tip-use-absolute-imports-for-better-readability-and-easy-refactoring-2ad5c7f2f957

Sorry for jumping in :sweat_smile:  , but I thought this could be discussed for a better outcome :innocent: .

**Comment by yuval-hazaz** [comment]
Thanks @ParkourKarthik, for sharing the links. 
We will review it soon

**Comment by souravjain540** [comment]
@arielweinberger please see if you can help @ParkourKarthik

**Comment by martinez-hugo** [comment]
Hi ! Can I work on these issues ?

**Comment by overbit** [comment]
@martinez-hugo sorry but this issue was already completed.
