### ISSUE TITLE
🧹 Fix: `amplication-server` uses absolute `/src` imports, should be relative instead

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3314]
### What happened?

More context can be found in #3313 

### What you expected to happen

Convert `/src` imports to be relative

**Comment by ParkourKarthik** [comment]
Picking up this issue.

**Comment by yuval-hazaz** [comment]
@ParkourKarthik, thanks for your support!
This issue is already assigned, so please wait for @souravjain540 to confirm before you spend your time on it

**Comment by souravjain540** [comment]
@ParkourKarthik, you're contributing to amplication for the first time. Right?

**Comment by ParkourKarthik** [comment]
Yes, @souravjain540 , this is my first time contributing to`amplification`. But have been a fan for a while.

I have opened up a conversation on #3313 as I had a difference in opinion.

**Comment by souravjain540** [comment]
I am assigning you this issue. Do contact me after submitting your PR for some cool SWAG ;)

**Comment by Rutam21** [comment]
@souravjain540 If this still needs a PR, I am up for it.

**Comment by souravjain540** [comment]
> @souravjain540 If this still needs a PR, I am up for it.

Assigned. :)

**Comment by Rutam21** [comment]
@souravjain540 I have gone through the `amplication-server` folder and it seems that the files are already using relative imports within them. There are no changes required and this issue can be closed.

**Comment by Rutam21** [comment]
@yuval-hazaz @arielweinberger Please check my findings in above comments and feel free to close this issue once confirmed.

**Comment by arielweinberger** [comment]
That is correct, @Rutam21 - thanks for the heads up! Closing.
