### ISSUE TITLE
Amplication Server Fails to Start due to Zero Kafka Brokers

### ISSUE THREAD

**Issue by shubhrjain** [amplication/amplication#3350]
### Overview

Install all the required dependencies, run the necessary scripts and init a Docker-based Postgres server.
```
npm install
npm run setup:dev
npm run start
```

Now when we run the amplification server using below command
Go to .../packages/amplication-server and execute the following command:
```
npm run start
```

Amplification server fails to start.

### Symptoms

We see errors like in amplification server logs
```
[Nest] 91870  - 08/04/2022, 12:51:21 PM   ERROR [ServerKafka] ERROR [BrokerPool] Closed connection {"timestamp":"2022-08-04T07:21:21.759Z","logger":"kafkajs","retryCount":0,"retryTime":289}
```

Additionally you can go and check the amplification kafka ui and no brokers will be there
http://localhost:8080/ui/clusters/local/brokers

### Cause

Kafka broker not setup properly.

### Resolution

To kill old running docker containers:
```
docker container ls
docker container rm -f [list-of-containers-id]
```
To clean your existing containers, volumes, and images, run:
```
docker container prune
docker volume prune
```
In the root Amplication folder run:
```
npm run docker:dev
```

### Tags

kafka, amplification-server

### Related Discord Threads

https://discord.com/channels/757179260417867879/781089015548870695/1004655668311117985

**Comment by yuval-hazaz** [comment]
@mshidlov please have a look at this one

**Comment by mshidlov** [comment]
@yuval-hazaz @MoFoGo 
This is important troubleshooting to document. 

In the case that Kafka is unavailable restarting the Kafka containers should solve the issue.

To do so you can run:
`docker-compose -f docker-compose.dev.yaml down`
and then:
`docker-compose -f docker-compose.dev.yaml up`

Wait for the containers to finish loading and look for the running broker in the Kafka UI.

The Discord thread in this issue has a good walkthrough done by @abrl91.
And you can find more information [here](https://github.com/amplication/amplication/releases/tag/v0.13.1).

@MoFoGo let me know if you need further assistance.

**Comment by yuval-hazaz** [comment]
Thanks @mshidlov 
please have a look at this issue I opened yesterday - is it related?
https://github.com/amplication/amplication/issues/3369

**Comment by westlag114** [comment]
Excuse me.
I am facing the same problem.
Is there any progress on this issue?

**Comment by overbit** [comment]
This was fixed. 
Now we also have an additional script to clean up the local dev environment status:`npm run docker:dev:cleanup`
