### ISSUE TITLE
Devlopment Environment Setup Prerequisite Missing

### ISSUE THREAD

**Issue by shubhwip** [amplication/amplication#3357]
### Describe the issue with documentation

There should be step in prerequisite to make sure user has docker daemon running before starting `npm run setup:dev`.
Now on Main [README](https://github.com/amplication/amplication/blob/master/README.md#system-requirements) file there is mention of docker as prequisite and should be installed.
However i jumped directly to [contributing](https://github.com/amplication/amplication/blob/master/CONTRIBUTING.md#step-3-prepare-the-development-environment) page and followed the steps and which led to below errors.
```
✖ Command failed: npm run docker:dev
The SERVICE_DB_NAME variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory
```

### How to solve the problem

We should add some prerequisite steps in [contributing](https://github.com/amplication/amplication/blob/master/CONTRIBUTING.md#step-3-prepare-the-development-environment) page to make sure people don't face this issue further.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@MoFoGo this one should go to you

**Comment by JatinRanka** [comment]
I'm trying to set up the codebase in local to contribute an issue, but unable to because of the missing env variable.

Till the document is updated, @MoFoGo can you please share the steps to get a `SERVICE_DB_NAME` here in the comments?

**Comment by shubhwip** [comment]
@JatinRanka This error happened for me just because my docker daemon was not running. So before you start the `amplication` build process you should make sure your docker is started fine.

@yuval-hazaz I have submitted the PR as others are facing the issue as well :). Hope it is okay.
