### ISSUE TITLE
🐛 Bug Report: cannot read property `authProvider` of undefined error occurs  when creating a new resource in a project

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3360]
### What happened?

Cannot read property `authProvider` of undefined error occurs when creating a new resource in a manually created project.
This error does not occur when we create a new resource in the auto-generated project

https://user-images.githubusercontent.com/39680385/183033057-24405bd5-dfa0-4a72-8d28-42500a2c96da.mov

.

### What you expected to happen

I expect no errors at all

### How to reproduce

- After signup, you have an auto-generated project. Create a resource for this project, and you won't see errors. 
- Create a new project and then a new resource for this project. You will see the error

### Amplication version

0.15.0

**Comment by abrl91** [comment]
I think it's related to the project configuration setting.

https://user-images.githubusercontent.com/39680385/183250047-8bd37bed-5f77-4643-a6ab-41d11fe5d45d.mov

**Comment by GreenMachine01** [comment]
@abrl91 is this item still relevant?

**Comment by yuval-hazaz** [comment]
no, we can close it
