### ISSUE TITLE
🐛 Bug Report: wrong URL in invitations

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3361]
### What happened?

When a user gets an invitation via email, the invite URL is incorrect 
The URL starts with server.amplication instead of app.amplication 

https://app.amplication.com/login?invitation=[code]

### What you expected to happen

The URL should be 
https://server.amplication.com/login?invitation=[code]

### How to reproduce

send an inviation 

### Amplication version

0.14.10

**Comment by shubhwip** [comment]
Inside `What you expected to happen` Expected URL should be [https://app.amplication.com/login?invitation=[code]](https://app.amplication.com/login?invitation=%5Bcode%5D) :) ?

**Comment by toukirkhan** [comment]
@yuval-hazaz can you tell me where is the action or automation for the same and please assign it to me?

**Comment by yuval-hazaz** [comment]
closing as duplicate of https://github.com/amplication/amplication/issues/2964

**Comment by yuval-hazaz** [comment]
@toukirkhan thanks for your support. I closed this issue as a duplicate, and it was already resolved. Please let us know if you want to work on any other issue
