### ISSUE TITLE
🐛 Bug Report: Amplication server does not show an error on startup when kafka is down

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3369]
### What happened?

When you run amplication-server while Kafka is down, the console does not show any error, although the server did not load successfully. 

The last message in the console is about "BuildModule dependencies initialized" and nothing else

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/43705455/183243957-495bd015-5a45-4132-a220-eaa39ab8213b.png">

This is the console with the rest of the messages when Kafka is running 

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/43705455/183243936-417025e8-812c-411f-aad0-fa6a1a4c365a.png">

### What you expected to happen

the user should see a message describing that Kafka is down

### How to reproduce

run amplication-server while Kafka is down

### Amplication version

0.14.10

**Comment by yuval-hazaz** [comment]
@tupe12334 can you please have a look at this

**Comment by EugeneTseitlin** [comment]
can't reproduce.
