### ISSUE TITLE
Docs: Review Deploy a Docker Container article 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3391]
### Describe the issue with documentation

@arielweinberger, @mshidlov, please review the  exisiting article, to make sure that it is  up to date and relevant 

(https://docs.amplication.com/docs/deploy/#deploy-a-docker-container)

### How to solve the problem

Review article.  Approve or request updates.

**Comment by overbit** [comment]
The article is out of sync with the current amplication. We do not support Download of code anymore so we will need to update with github instructions.

The section _Deploy a Docker container_ should be renamed in running a docker container locally and we will need to add a section to deploy a container with generic instruction to build, push and run a new container in a cloud provider.

@MoFoGo

**Comment by yuval-hazaz** [comment]
@GreenMachine01 this document requires a serious revamping
We need to assign it to the team ASAP for a rewrite

**Comment by GreenMachine01** [comment]
@arielweinberger @levivannoort I assigned this item to you.
Please talk to Moshe and help him finalize this doc

**Comment by overbit** [comment]
Documentation looks up to date now. The only minor feedback is regarding the case where our users storing their services in a monorepo git repository. In this case, we might want to mention to run `docker-compose up` from within the service folder they want to run.
