### ISSUE TITLE
Docs: Review - Deploy Amplication to a Kubernetes cluster using Helm 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3393]
### Describe the issue with documentation

@arielweinberger, @mshidlov, please review the existing article, to make sure that it is up to date and relevant

[Deploy Amplication to a Kubernetes cluster using Helm](https://docs.amplication.com/docs/helm-chart/)

### How to solve the problem

Review article. Approve or request updates.

**Comment by overbit** [comment]
The article is now out of sync with the actual amplication project.

**Comment by yuval-hazaz** [comment]
The doc is not available from the menu for a couple of months already
I deleted it completely now in PR https://github.com/amplication/docs/pull/229
