### ISSUE TITLE
Refactor `amplication-git-service` to use `@amplication/nest-logger-module`

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3396]
# Description
We have recently created a new package, `@amplication/nest-logger-module`, to be used as the exclusive logging library in our NestJS microservices.

Existing services use the Winston logger module. In this task you will need to replace that with the new Amplication logger module for the `packages/amplication-git-service` service.

# Useful information
Take a look at the [`README.md`](https://github.com/amplication/amplication/tree/master/packages/amplication-nest-logger-module) file of the logger module for information on how to consume it.

You can see a sample pull request [here](https://github.com/amplication/amplication/pull/3285).

**Comment by ShrutiMishra-2002** [comment]
@souravjain540 please assign me this issue

**Comment by souravjain540** [comment]
sure @ShrutiMishra-2002 

join our discord for any help

**Comment by souravjain540** [comment]
@ShrutiMishra-2002 If you are not working on this then should I assign it to someone else?

**Comment by khuongduy354** [comment]
> @ShrutiMishra-2002 If you are not working on this then should I assign it to someone else?

is this issue assigned ?

**Comment by souravjain540** [comment]
> > @ShrutiMishra-2002 If you are not working on this then should I assign it to someone else?
> 
> is this issue assigned ?

I can assign it to you, if you want to work.

**Comment by khuongduy354** [comment]
> > > @ShrutiMishra-2002 If you are not working on this then should I assign it to someone else?
> > 
> > 
> > is this issue assigned ?
> 
> I can assign it to you, if you want to work.

yes, please assign me.

**Comment by souravjain540** [comment]
> > > > @ShrutiMishra-2002 If you are not working on this then should I assign it to someone else?
> 
> > > 
> 
> > > 
> 
> > > is this issue assigned ?
> 
> > 
> 
> > I can assign it to you, if you want to work.
> 
> 
> 
> yes, please assign me.

Done. Let me know if I can help you on anyway

**Comment by khuongduy354** [comment]
> work

Sorry, I think you should i assign this to someone else. I have so much troubles setting up.

**Comment by ahlavorato** [comment]
@souravjain540, I'm looking forward to helping the community, could I be assigned to it?

**Comment by souravjain540** [comment]
@ahlavorato  let us know if you need any help
