### ISSUE TITLE
Refactor `amplication-server` to use `@amplication/nest-logger-module`

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3397]
# Description
We have recently created a new package, `@amplication/nest-logger-module`, to be used as the exclusive logging library in our NestJS microservices.

Existing services use the Winston logger module. In this task you will need to replace that with the new Amplication logger module for the `packages/amplication-server` service.

# Useful information
Take a look at the [`README.md`](https://github.com/amplication/amplication/tree/master/packages/amplication-nest-logger-module) file of the logger module for information on how to consume it.

You can see a sample pull request [here](https://github.com/amplication/amplication/pull/3285).

**Comment by ParkourKarthik** [comment]
Would love to pick this up, let me know if it can be assigned.

**Comment by souravjain540** [comment]
Hi @ParkourKarthik, do you want to work on it?
You will get exclusive swag if PR get merged :)

**Comment by ParkourKarthik** [comment]
> Hi @ParkourKarthik, do you want to work on it?
> You will get exclusive swag if PR get merged :)

Yes, I would like to pick this up

**Comment by souravjain540** [comment]
Sure @ParkourKarthik !

Join our discord, if you need any help :)

**Comment by souravjain540** [comment]
any updates @ParkourKarthik?

**Comment by ParkourKarthik** [comment]
I'm having some trouble after running the application locally. Seeking help from the #support channel in discord. Meanwhile I can make the changes and create a PR.

**Comment by souravjain540** [comment]
your email @ParkourKarthik ?

**Comment by ParkourKarthik** [comment]
> your email @ParkourKarthik ?

parkourkarthik@gmail.com

**Comment by ahlavorato** [comment]
Could I work on it?

**Comment by arielweinberger** [comment]
Apologies @ahlavorato but we already have a PR for this.
