### ISSUE TITLE
⭐️ Select GitHub Repository Search Functionality

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3402]
### Feature description

Currently, when selecting a GitHub repo, there is no easy way to filter the results. I usually end up using my browser's built-in search functionality (Ctrl/CMD + F). I find it to be an annoying friction point.

It would be great to implement a search box of some sort that filters out the results.

Here is the design for the new repository selection modal:
![image](https://user-images.githubusercontent.com/4976416/183876058-a273f1e8-f50a-4649-b8fd-b94fe9f56a8a.png)

![image](https://user-images.githubusercontent.com/4976416/183876201-67c8f416-c8ef-4af5-a252-288977215b88.png)

We will implement the simplest filtering capability on the front-end only.

### Use case

Every time a user needs to select a repo and has more than a few, this happens.

**Comment by arielweinberger** [comment]
Can you please produce a design for this? Once done, we will make this a community issue. Thanks ❤️

**Comment by b4s36t4** [comment]
Can we implement using this client side fuzzy search with basic search input?

**Comment by alexbass86** [comment]
@arielweinberger, something like that can work :)

**Select window:**

![Select with search](https://user-images.githubusercontent.com/96179897/183875200-66efcf99-7e49-4248-abd7-956f9e3f0385.png)

**Filter using the search:**

![Select with type](https://user-images.githubusercontent.com/96179897/183875232-3eec0d46-0a0c-4336-b80e-bbab82f1e866.png)

**Comment by arielweinberger** [comment]
@b4s36t4 This will be a simple client-side based filter, no fancy server side for now.

**Comment by b4s36t4** [comment]
@arielweinberger got it. Can I work on this if that's possible?

**Comment by ItayElgazar** [comment]
Can take it :)

**Comment by arielweinberger** [comment]
@b4s36t4 Sure, go ahead and take it. @souravjain540 Let's support @b4s36t4 with this.

**Comment by b4s36t4** [comment]
@arielweinberger Any document on how to integrate github authentication? I'm stuck here.
<img width="1428" alt="Screenshot 2022-08-10 at 6 49 20 PM" src="https://user-images.githubusercontent.com/59088937/183911518-3227edec-0f87-42bb-a4ca-946b5973734f.png">

**Comment by arielweinberger** [comment]
Does this help?
https://docs.amplication.com/docs/connect-server-to-github/#step-1--create-a-new-github-app

**Comment by b4s36t4** [comment]
@arielweinberger , the doc you have given is for OAuth part, but this part is installing app into github to retrieve the repos of users. Includes these keys all I think.
<img width="660" alt="Screenshot 2022-08-10 at 8 25 17 PM" src="https://user-images.githubusercontent.com/59088937/183936302-778eeb46-8d07-45a2-9602-14c318dfadd3.png">
,

**Comment by arielweinberger** [comment]
Can you send me a message on Discord please? I will try to assist you remotely. I can share some material with you that is not yet public.

**Comment by arielweinberger** [comment]
@b4s36t4 After discussing with the team, we realized that this feature is not ready to be implemented. Aside from the missing documentation on how to set up the GitHub App, the GitHub API itself has some limitation on how many items you can fetch from their API. We will close this issue for now. Apologies!
