### ISSUE TITLE
Docs: Document Plugins - UI

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3407]
### Describe the issue with documentation

Plugin are being introduced into Amplication. 
This is a major feature that must be documented. 

### How to solve the problem

Write doc articles for the plugins.

**Comment by muxmind** [comment]
How to start contributing

**Comment by MoFoGo** [comment]
> How to start contributing

Hi @muxmind. Thanks for your interest in contributing to this issue. However, this is a new feature that is still in development, so the Amplication core team will be handling the documentation for this.

**Comment by MoFoGo** [comment]
This task relates to the Add-ons that we be available from the marketplace in the Amplication UI. 

It will describe how to use an add-on that has already been created and has been placed in the marketplace. 

The documentation to explain to developers how to develop and integrate a Plug is described in a seperate issue.

**Comment by muxmind** [comment]
Thank you for your reply.

I am new to open source

It will be helpful if you can point me to any issue where I can contribute 

Thanks again
