### ISSUE TITLE
🐛 Bug Report: Typo in the OverviewTile file (Next JS)

### ISSUE THREAD

**Issue by regisBafutwabo** [amplication/amplication#3424]
### What happened?

It says Next JS as you can see on the picture but I think it should be Nest JS
<img width="593" alt="Screen Shot 2022-08-13 at 10 19 50 AM" src="https://user-images.githubusercontent.com/10329294/184463208-908dbe2d-0e72-4ba7-8236-df0025b7c557.png">

### What you expected to happen

it should say Nest JS instead of Next JS

### How to reproduce

Go to the dashboard of your app, and you will see it in the Overview section

### Amplication version

0.14.12

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
Thanks for your contribution @regisBafutwabo!

This issue comes under TIFT campaign! You're eligible for a t-shirt and a pack of stickers ❤️

**Comment by regisBafutwabo** [comment]
Oh nice how do I get them?

**Comment by Vipul2504** [comment]
the issue is open?

**Comment by souravjain540** [comment]
> Oh nice how do I get them?

i will contact you after the end of campaign
