### ISSUE TITLE
🐛 Bug Report: New project popup - New UI

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3426]
### What happened?

We need to update our "new project" popup to be aligned with the latest design.

This is the current design:
![image](https://user-images.githubusercontent.com/96179897/184532577-4efbd126-ecad-442e-8abe-8465838a2b09.png)

This is the new design:
![new workspace](https://user-images.githubusercontent.com/96179897/184532716-5a1c9c58-1809-4e08-9b2e-aa47966412ba.png)

Public Figma:
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=830%3A9673

### What you expected to happen

Update the current popup to be aligned with the new design

### How to reproduce

Create new project in v15

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@rolwin100 There was a mixup, and it seems like @EugeneTseitlin fixed this issue as part of the other efforts 

Thanks for your support. Let me know if you want to be assigned to another issue

**Comment by rolwin100** [comment]
pls assign another issue. This seems fixed.

**Comment by alexbass86** [comment]
@EugeneTseitlin From my point of view, this fix is approved.

**Comment by morhag90** [comment]
@EugeneTseitlin Can we close this issue?
