### ISSUE TITLE
🐛 Bug Report: Top nav - The fast navigation indicator is not working correctly.

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3428]
### What happened?

When we are on the main project screen, the project name indicator should be highlighted with white, and the service selection dropdown should be "Resource List" and not "project configuration."

Bad:
![image](https://user-images.githubusercontent.com/96179897/184543554-88b3f5e2-24bb-4350-aff7-cf7a80cfad90.png)

How is it supposed to be:
![image](https://user-images.githubusercontent.com/96179897/184543710-e988f000-0b7b-4a66-879a-d7b7ffe205c0.png)

### What you expected to happen

When we are on the main project screen, the "project name" should be highlighted with white, and the dropdown needs to be in its default state, "Resource list."

### How to reproduce

Go to main screen in v15

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by EugeneTseitlin** [comment]
Change hover on project and resource links

**Comment by alexbass86** [comment]
@EugeneTseitlin approved

**Comment by morhag90** [comment]
@EugeneTseitlin Can we close this issue?
