### ISSUE TITLE
🐛 Bug Report: Top nav - Search icon have wrong inner padding

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3429]
### What happened?

Wrong padding between icons, text in the top menu - Need to be 12px

How it looks now:
![image](https://user-images.githubusercontent.com/96179897/184543911-7312d36f-41de-448a-97d7-f05d28ebf7e8.png)

How is it supposed to be:
![image](https://user-images.githubusercontent.com/96179897/184543924-700d67c2-4494-4569-ad69-85303553db03.png)

### What you expected to happen

The search icon needs to be in the center and have a padding of 12px on the left and right 

### How to reproduce

Top nav in v15

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by EugeneTseitlin** [comment]
Every icon should be 20px: search, user profile, disconnect.

**Comment by alexbass86** [comment]
@EugeneTseitlin  Search icon is still 16px. Please align all the icons on top menu to be 20px, thanks

**Comment by morhag90** [comment]
@EugeneTseitlin Can we close this issue?
