### ISSUE TITLE
🐛 Bug Report: Top nav - Missing hover effect

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3430]
### What happened?

On hover, the text color should change to white.

![image](https://user-images.githubusercontent.com/96179897/184544676-0f32a4cd-15a6-4de0-ae58-e062503fb265.png)

### What you expected to happen

When we hover over the menu links, we need to change the text color to white.

### How to reproduce

Just hover on top of one of the links in the top nav

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by EugeneTseitlin** [comment]
I propose to implement a component that would check if it's link is the same as a current pathname and would become highlighted if so. This component should be integrated in header in right and possibly in middle part.
@barshimi @abrl91 @morhag90 What do you think about that?
