### ISSUE TITLE
🐛 Bug Report: Workspace dropdown - Visual issues

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3433]
### What happened?

The workspace dropdown should look precisely as it is in Figma.

Bad:
![image](https://user-images.githubusercontent.com/96179897/184545294-faaf77ba-933b-40aa-9081-98d2e1d65201.png)

How is it supposed to be:

![12341](https://user-images.githubusercontent.com/96179897/184545319-929a5abe-a08b-4e5d-ab29-ff09aad03250.png)

Figma:
https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=1094%3A12880

Creating a new workspace button should be exactly like it's in the design system. 
This button should be the text variant button from the design system

### What you expected to happen

We need to ensure the workspace selection drop-down is precisely as it is in the original design.

### How to reproduce

Click on the workspace selection dropdown.

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by EugeneTseitlin** [comment]
I fixed icon position, but icon size is incorrect. Image doesn't take the whole space of provided container. It's related to icon component implementation: providing image via font and managing sizes with font size.
Regarding "Create new workspace" font weight - amp-button class set it to 500 with important. I think it's not wise override it with more specific selector and important, some constructive and consistent should be provided instead.
@barshimi @alexbass86 @morhag90 @abrl91 You are welcome to share your opinion.
