### ISSUE TITLE
🐛 Bug Report: Left nav - Wrong icon size

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3434]
### What happened?

The icons in the setting section are super tiny. All icons across this side nav should be 16px and taken from icomoon.

Bad:
![image](https://user-images.githubusercontent.com/96179897/184545925-a0c371af-6960-4f3d-9559-83d36194f0da.png)

How is it supposed to be:
![image](https://user-images.githubusercontent.com/96179897/184546002-85ce4018-f9f6-453d-9918-3b9800acda9f.png)

Figma
https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=10%3A1624

### What you expected to happen

Please make sure the icon size is 16px.

### How to reproduce

Go to the settings screen in v15.

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by alexbass86** [comment]
@EugeneTseitlin From my point of view, this fix is approved.

**Comment by morhag90** [comment]
@EugeneTseitlin Can we close this issue?
