### ISSUE TITLE
🐛 Bug Report: Main section - wrong padding between the search & divider

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3435]
### What happened?

The wrong padding between the search bar to the divider should be 16px.

Bad:
![image](https://user-images.githubusercontent.com/96179897/184546207-c4974905-abe3-410f-b4f7-e23fe856e212.png)

How is it supposed to be:
![image](https://user-images.githubusercontent.com/96179897/184546218-62645cad-2dfc-4cf9-8d52-d8022858ba6f.png)

### What you expected to happen

We have a 16px padding between all components.

### How to reproduce

Go to the main project screen in v15.

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by morhag90** [comment]
@tupe12334  Can you give us an update, please?
