### ISSUE TITLE
🐛 Bug Report: Resource component - UI issues

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3437]
### What happened?

The resource component looks different from the design. Please ensure it's exactly as it is in the design.

Bad:
![image](https://user-images.githubusercontent.com/96179897/184546408-9da9f3d0-fdc6-4f6f-9e31-2a6714a3b8f7.png)

How is it supposed to be:

![entity_card](https://user-images.githubusercontent.com/96179897/184546428-c199e8d9-5c60-4c26-a456-28e5db2ca8c1.png)

### What you expected to happen

The component should look precisely as it's in our design system.

Figma:
https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=17%3A1510

### How to reproduce

Go to the main project screen and create a service.

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by alexbass86** [comment]
@EugeneTseitlin @tupe12334 I don't see any change.

**Comment by tupe12334** [comment]
@alexbass86 The pr didnt merge yet

**Comment by morhag90** [comment]
@tupe12334 can we close this issue?

**Comment by tupe12334** [comment]
@morhag90 Yes

**Comment by alexbass86** [comment]
@tupe12334 @morhag90 Are you sure that this has been fixed with the design values? From what I see, the hover is different than the design...
