### ISSUE TITLE
🐛 Bug Report: Service - Left nav bad background color

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3438]
### What happened?

Wrong bg color for the menu, missing divider line.

Bad:
![image](https://user-images.githubusercontent.com/96179897/184546605-0552e264-5b9a-434e-84b0-475ae0981d8f.png)

How is it supposed to be:
![image](https://user-images.githubusercontent.com/96179897/184546690-e2ed5a4b-b49c-48df-b879-7ebf1f7beb8b.png)

### What you expected to happen

Background color = #22273C
Divider line color = #373D57

### How to reproduce

Click on any resource in v15.

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by msquare-2** [comment]
Hey,
Can I try to fix this?

**Comment by EugeneTseitlin** [comment]
> Hey, Can I try to fix this?

Sorry, I haven't noticed your message before. We are glad to get a contribution from a community. Just pick another one. Thanks.
