### ISSUE TITLE
🐛 Bug Report: Amplication v15 - UX/UI QA

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3441]
### What happened?

Here is the collection of all issues related to v15, which has been approved by @yuval-hazaz to be fixed before the official release, @arielweinberger LETS's MAKE THIS HAPPEN 👑. 

**Project screen - Top nav**
- [x] #3428
- [x] #3429
- [x] #3430
- [x] #3431

**Project screen - Left nav**
- [x] #3066
- [x] #3426
- [x] #3434
- [x] #3433
- [x] #3432
- [x] #3479
- [x] #3485

**Project screen - Main section (middle)**
- [x] #3437
- [x] #3435

**Project Settings - Overview section**
- [x] #2712
- [x] #3438
- [x] #3479

**Wizard** 
- [x] #3440
- [x] #3471
- [x] #3472 

**Project screen - Commit** 
- [x] #3501
- [x] #3510

**More:**
- [ ] Settings screen - Both workspace settings and workspace members look bad, and please make sure it looks like in Figma [Figma Link](https://www.figma.com/file/AKcZ9rk6QDMponJrQVDCDC/%232961%2C-%233057---New-Project?node-id=836%3A18964)
- [ ] Please make sure the left side menu icon sizes been changed also in v15 from 32px to 24px.
- [ ] When clicking on the workspace dropdown, we have a strange loading icon. Let's try to load the data before the app loading, so this won't happen.

### What you expected to happen

All fixes will be ready for the v15 release.

### How to reproduce

More info can be found on the issue's page.

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by EugeneTseitlin** [comment]
@arielweinberger I propose to close this issue despite that there are action items that we not completed. The product moved further, most probably the are fixed in other issues.
