### ISSUE TITLE
UX: Improve text on "Sync with GitHub" screen

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3443]
### Describe the issue with documentation

The explanatory text on the Sync with GitHub screen is not easy to understand. 

![image](https://user-images.githubusercontent.com/96979533/184548229-4aae0ded-85a5-4b2e-b43e-593b05f99abd.png)

### How to solve the problem

The explanation can be improved by:

1. Using shorter sentences. 
2.  Using clear language. For example, "Connect to Github to..." would probably be  easier to understand than the current "Enable sync with GitHub to..."
3. Being clear about actions and consequences. For example, "If you connect to GitHub, every time you commit your changes..."

NOTE: The above examples are for guidance only. Please use whatever phrasing you think best.

**Comment by MoFoGo** [comment]
Please replace the existing text with the following:

**If you connect to GitHub, every time you commit your changes, it automatically pushes your generated code and creates a Pull Request in your GitHub repository.**

**Comment by Sreekar-Tammana** [comment]
Can I get assigned to this issue?

**Comment by Ayush7614** [comment]
Intrested in working on this

**Comment by souravjain540** [comment]
Sure @Sreekar-Tammana , assigned.

Join our discord to get any help in solving this issue!

**Comment by souravjain540** [comment]
> Intrested in working on this

Please take another one

**Comment by Sreekar-Tammana** [comment]
> Sure @Sreekar-Tammana , assigned.
> 
> Join our discord to get any help in solving this issue!

Thank you Sourav, will start working on this.
