### ISSUE TITLE
UX: Improve text on the API Tokens page

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3444]
### Describe the issue with documentation

The explanatory text on the API Tokens page can be improved: 

![image](https://user-images.githubusercontent.com/96979533/184549110-8cbea831-224a-4cce-a1b3-14a4bd485561.png)

### How to solve the problem

The text should be corrected for grammar and split into shorter, easier-to-understand sentences.

**Comment by MoFoGo** [comment]
Please replace the text with the following:

**API tokens are used to authenticate requests to the Amplication API. They are specifically required for Amplication CLI. 
Tokens are valid for 30 days following creation or last use. The 30 day expiration period automatically refreshes with each API.**

**Comment by juno-w** [comment]
Hi, PR created https://github.com/amplication/amplication/pull/3484

**Comment by souravjain540** [comment]
Thank you @juno-w !
SUPER FAST!
