### ISSUE TITLE
UX: Add descriptive text to the General Settings page

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3445]
### Describe the issue with documentation

The General Settings page should have a brief explanation of what the user does on that page. 

![image](https://user-images.githubusercontent.com/96979533/184550492-a5d6e62c-d1a2-43bd-a567-2fca71c2ee7f.png)

### How to solve the problem

Add a sentence or two to say what the user can configure on this page. The fields may seem self-explanatory, but the user should be able to see the purpose of the page without having to scan down.

**Comment by MoFoGo** [comment]
Please insert the following text under the heading:

Enter a name and description for your app, and select a color.

**Comment by pinkelephant4** [comment]
can I be assigned this issue?

**Comment by Sreekar-Tammana** [comment]
Can I work on in this issue?

**Comment by souravjain540** [comment]
Hi @pinkelephant4, sure! assigned. Join our discord for any support!

**Comment by souravjain540** [comment]
> Can I work on in this issue?

please take another issue!

**Comment by Sreekar-Tammana** [comment]
> > Can I work on in this issue?
> 
> please take another issue!

Sure, no problem

**Comment by souravjain540** [comment]
hi @pinkelephant4 👋 

are you working on this issue? can we help you?

**Comment by pinkelephant4** [comment]
> hi @pinkelephant4 👋
> 
> are you working on this issue? can we help you?

yes i'm working on it. Can you guide me to where i can find the file to make the changes in?

**Comment by souravjain540** [comment]
> General Settings

`amplication/packages/amplication-client/src/Application/ApplicationForm.tsx` @pinkelephant4
