### ISSUE TITLE
UX: Add description text  to the Workspace page 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3455]
### Describe the issue with documentation

The [Workspace Settings](https://app.amplication.com/workspace/settings) page and the [Workspace Members ](https://app.amplication.com/workspace/members)page  do not have any explanatory text 

### How to solve the problem

Add a short explanation of Workspace Settings and Workspace Members.

Tip: read this [article ](https://docs.amplication.com/docs/getting-started/getting-started/workspace/)for an explanation of the functionality.

**Comment by MoFoGo** [comment]
Please enter the following text under the title on the Workplace Settings page:

**Workspaces help you manage your projects by enabling selected team members to work on specific apps.**

**Comment by Pritam0077** [comment]
can I work on this issue?

**Comment by souravjain540** [comment]
> can I work on this issue?

I think you have contributed to amplication previously as well?

**Comment by Pritam0077** [comment]
no

**Comment by souravjain540** [comment]
Okay, assigned @Pritam0077 

Join our discord, if you need any help in solving this :)

**Comment by Pritam0077** [comment]
ok thnx
