### ISSUE TITLE
UX:  Correct Authentication Method  text

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3456]
### Describe the issue with documentation

The following phrase is can be improved

![image](https://user-images.githubusercontent.com/96979533/184647999-91548a1c-af95-413c-ac94-0a33a18d3e92.png)

### How to solve the problem

Rewrite avoiding the passive text.

Tip: Passive text is not recommended in UI texts (or documentation) if it can be avoided.

**Comment by MoFoGo** [comment]
Replace with the following text:

**Select which authentication method you want to use in the generated app**

**Comment by souravjain540** [comment]
@ SergeWilfried I saw this is your first contribution to Amplication.

Thank you so much for contributing, this issue comes under TIFT campaign and you're eligible to get a t-shirt and a pack of stickers from us.

Just make sure the PR is merged :)

**Comment by Rutam21** [comment]
@souravjain540 If it's still not resolved, I can submit a PR.
