### ISSUE TITLE
Docs: Add description of Relation to Entity settings 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3459]
### Describe the issue with documentation

In the [Create Entity Field](https://docs.amplication.com/docs/how-to/create-entity-field/) article, there is no description for selecting the Relation to Entity settings. 
The following dialogue box needs to be included:
![image](https://user-images.githubusercontent.com/96979533/184667485-b8b9fa7d-c423-4526-965f-5ed584d31c73.png)

- 

### How to solve the problem

Update the [Create Entity Field](https://docs.amplication.com/docs/how-to/create-entity-field/) article

**Comment by varghesejose2020** [comment]
I would like work on this issie

**Comment by souravjain540** [comment]
@varghesejose2020 sure! 
Join our discord for any help needed :)
