### ISSUE TITLE
UX: Improve description of  Entities feature in the Dashboard

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3460]
### Describe the issue with documentation

Try and think of a better way of describing the Entities feature in the Dashboard:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/96979533/184670180-addfca06-3b97-4902-b20e-abdc269217c4.png">

### How to solve the problem

You can check out the docs for inspiration. 

https://docs.amplication.com/docs/first-app/#step-3---add-entity-fields

https://docs.amplication.com/docs/how-to/create-entity-field/

**Comment by MoFoGo** [comment]
Please replace with the following text:

**Use Amplication's simple and intuitive user interface to define your data model.**

**Comment by Himanxu1** [comment]
I want to work on this issue . Assign this to me.

**Comment by souravjain540** [comment]
Sure @Himanxu1 !

Join our discord for any support you need :)

**Comment by Himanxu1** [comment]
I have already joined !
 assign this to me

**Comment by Himanxu1** [comment]
Where is this component ?
