### ISSUE TITLE
UX: Correct text on sign-in page 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3461]
### Describe the issue with documentation

The marked text should be corrected for grammar (Check for periods and commas).

<img width="608" alt="image" src="https://user-images.githubusercontent.com/96979533/184674800-7ee38968-a4d9-484f-a65b-1dd2519a4df3.png">

### How to solve the problem

Review and enhance the text.

**Comment by MoFoGo** [comment]
Please replace with the following text:

**Amplication is currently in beta. However, your generated apps are production ready. Every app generated by the Amplication platform contains production-ready, open-source components and packages. We include only those that are popular, documented, secured and supported.  
Read more about our stack here.**

**Comment by aakankshadhurandhar** [comment]
Hello Can you assign me this issue ?

**Comment by Himanxu1** [comment]
I want to work on this issue?

**Comment by pinkelephant4** [comment]
Can I be assigned this issue?

**Comment by souravjain540** [comment]
Hi @aakankshadhurandhar, sure! If you need any help please join our discord :)

**Comment by souravjain540** [comment]
> I want to work on this issue?

you can take another issue

**Comment by souravjain540** [comment]
> Can I be assigned this issue?


you can take another issue

**Comment by Sreekar-Tammana** [comment]
Hey there, please consider me working on this issue.

**Comment by souravjain540** [comment]
@Sreekar-Tammana there are plenty of similar issue, please take one before someone else take it.

I am sorry but Akansha asked this one first
