### ISSUE TITLE
🐛 Bug Report: Helm deployment template

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#3466]
### What happened?

Helm deployment template always include secrets:
`          - secretRef:
              name: '{{ .Values.name }}'`
There are services that don't have secrets, so they are failing to run because of that.

### What you expected to happen

Secrets should be optional for deployment. Introduce some condition for that. 

### How to reproduce

see it in master branch

**Comment by shubhwip** [comment]
Can i be please assigned to this :) ?
