### ISSUE TITLE
🐛 Bug Report: Circle badge - Wrong icon size

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3471]
### What happened?

Our circle badge has the wrong icon size, so please align it with the design system.

Wrong size in component:
![image](https://user-images.githubusercontent.com/96179897/184887826-6daa197b-2534-42c6-9a18-10c016490e7c.png)

Wrong size in the wizard:
![image](https://user-images.githubusercontent.com/96179897/184887982-b9abe418-9154-41d0-b38b-f089db248b19.png)

### What you expected to happen

Please make sure it's exactly like in the design system.
Each circle size has its icon size.
![image](https://user-images.githubusercontent.com/96179897/184889017-5d5abef3-05da-4de8-a2d7-5600066b3580.png)

Figma:
https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=8%3A443

### How to reproduce

Go to the screens that include this badge, no matter the circle size, the icon inside of this badge has the wrong size.

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by morhag90** [comment]
@tupe12334, @EugeneTseitlin Can you give us an update about this issue? 
Thanks 

@alexbass86

**Comment by morhag90** [comment]
@tupe12334 @EugeneTseitlin  I fixed the icon in service wizard on another branch
