### ISSUE TITLE
Implement a `@amplication/kafka-proxy` service to process messages from Kafka to S3

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3491]
### Feature description

This is an enterprise feature.

This service needs to subscribe to a SQS queue and forward messages to a specific Kafka topic.

The service should accept at least the following environment variables:
- `SOURCE_SQS_QUEUE_ARN`: The source SQS queue to read messages from
- `TARGET_KAFKA_TOPIC`: The target Kafka topic to proxy messages to
- `KAFKA_BROKERS`: A comma-separated string representing the Kafka broker URLs.

**Comment by EugeneTseitlin** [comment]
@arielweinberger I think we can close this issue as irrelevant. What do you think?
