### ISSUE TITLE
🐛 Bug Report: Commit page crashing

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3508]
### What happened?

When you enter the commit page of a resource, the page crashes with

<img width="1512" alt="Screen Shot 2022-08-18 at 12 08 05" src="https://user-images.githubusercontent.com/61761153/185379295-f0301baa-ec36-4c16-91cc-17d1330437aa.png">

### What you expected to happen

Its needs to show the commit of the resource

### How to reproduce

In v 0.15.0
Generate an resource and enter the commits page of the resource, it will crash

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by CoderOO7** [comment]
Assign that issue to me. I would like to work on that

**Comment by CoderOO7** [comment]
Hi I have checked that thing it's working fine for me. I checked the code in master branch for that **CommonList** component. Their is no variable named **currentProject**. 

![image](https://user-images.githubusercontent.com/67546884/185707619-48e0b01f-45e5-4af0-9b6d-ba14cc096961.png)

**Comment by tupe12334** [comment]
@CoderOO7 Please check the release/0.15.0 branch

**Comment by abrl91** [comment]
@yuval-hazaz fixed it by removing this link from the resource page, as there is no direct connection between commit and resource from v0.15.0
