### ISSUE TITLE
🐛 Bug Report: Commit - Left menu icons

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3510]
### What happened?

We don't have a commit screen per resource. Instead, from v15, it's a project-level commit & code view.
Please remove the link to code view & commit from the service left menus.

Bad
![image](https://user-images.githubusercontent.com/96179897/185435165-fea30720-1e80-4a91-b868-6613de2e0e40.png)

### What you expected to happen

No "view code" or "commit" links on the left menu in each service.
The only way is by clicking on the drop-down on the top nav bar.

### How to reproduce

Go into a resource on v15.

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Himanxu1** [comment]
I can work on this issue . Assign it to me .

**Comment by tupe12334** [comment]
@Himanxu1 go head, i assigned you

**Comment by Himanxu1** [comment]
So have to make changes in release v15 ??
