### ISSUE TITLE
🐛 Bug Report: wrong variable type 

### ISSUE THREAD

**Issue by pratikgl** [amplication/amplication#3511]
### What happened?

In `amplication/amplication/blob/master/packages/amplication-server/src/core/mail/mail.service.ts#L17` the type of var `IS_EMAIL_DEPLOYMENT_NOTIFICATION` is a `String`

### What you expected to happen

The variable type is `string` instead of a `boolean`. This might lead to some unexpected results.

### How to reproduce

https://github.com/amplication/amplication/blob/master/packages/amplication-server/src/core/mail/mail.service.ts#L17

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Himanxu1** [comment]
I want to work  on this issue seems it easy . Assign it to me.
