### ISSUE TITLE
🐛 Bug Report: Apps should be App when count is 1

### ISSUE THREAD

**Issue by Shubhdeep12** [amplication/amplication#3516]
### What happened?

While displaying the count of apps on platform. The word **_Apps_** should be **_App_** when there is 1 app.

### What you expected to happen

It should follow this rule -> 
0 Apps
1 App
(n>1) Apps

### How to reproduce

[Video](https://share.vidyard.com/watch/mNXsBbJP9WKsQgvHSVEfVY?)

### Amplication version

0.14.12

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Shubhdeep12** [comment]
If team wants to fix, I can take this.

**Comment by souravjain540** [comment]
We can accept this issue @yuval-hazaz?

**Comment by yuval-hazaz** [comment]
Please review this issue again against the new UI in v0.15 (released to prod already), If this issue is still relevant, please include a screenshot and you can go ahead and fix it

**Comment by Shubhdeep12** [comment]
Yes @yuval-hazaz
Checked the above issue in the current build, seems like it is not handled.
here is the screenshot - 
![image](https://user-images.githubusercontent.com/43654389/193399954-3c2e6d64-23d1-4801-b0fc-b96013e01512.png)

Raised PR with changes - https://github.com/amplication/amplication/pull/3997
It would be great if you review it.
Thanks.
