### ISSUE TITLE
🐛 Bug Report: Theme issue, color for options is not correct in Light mode.

### ISSUE THREAD

**Issue by Shubhdeep12** [amplication/amplication#3517]
### What happened?

UI theme issue.

### What you expected to happen

On changing theme from dark to light mode, the color of options doesn't feel correct.

### How to reproduce

![image](https://user-images.githubusercontent.com/43654389/185642765-ac3af630-68c9-4e96-832e-ea68e8e27903.png)
[video](https://share.vidyard.com/watch/Cw8vjWcC2MF1pbrLZrNAJJ?)

### Amplication version

0.14.12

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Shubhdeep12** [comment]
If team thinks this to be a valid issue. 
Please provide the designs for the options.
I would love to fix this.

**Comment by yuval-hazaz** [comment]
hi @Shubhdeep12 thanks for reporting this
After looking into the usage statistics we decided to remove the light theme. So, starting v 0.15.0 which should be released soon the light theme is removed

**Comment by yuval-hazaz** [comment]
I will close this issue since it is not relevant any longer

**Comment by Shubhdeep12** [comment]
Oh, Got it. 
Thanks for confirming @yuval-hazaz
