### ISSUE TITLE
🐛 Bug Report: App settings Theme switching issue

### ISSUE THREAD

**Issue by Shubhdeep12** [amplication/amplication#3518]
### What happened?

UI theme issue

### What you expected to happen

Color of text is not changing on changing theme.

### **Light theme**
![image](https://user-images.githubusercontent.com/43654389/185644817-0f69df57-db0a-458e-862d-ec2f0cc37380.png)
![image](https://user-images.githubusercontent.com/43654389/185644908-736e61e8-3fe0-46e2-8575-625bf8263916.png)

### **Dark theme**
![image](https://user-images.githubusercontent.com/43654389/185645001-c3b17aa6-0103-4afb-bf1f-1f14ec83f987.png)
![image](https://user-images.githubusercontent.com/43654389/185645058-cea5cf7f-7cfe-468e-950a-1ba3602af967.png)

### How to reproduce

[video](https://share.vidyard.com/watch/ucSQKqioMjEAoHQXbCSGnu?)

### Amplication version

0.14.12

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Shubhdeep12** [comment]
If Amplication team think this a  valid issue.
I would love to fix this.

**Comment by rolwin100** [comment]
can u take this up @Shubhdeep12

**Comment by Shubhdeep12** [comment]
Yes sure @rolwin100

**Comment by Shubhdeep12** [comment]
Since, we are moving away with themes and just sticking to light theme.
Do we need this? @yuval-hazaz 
FYI @rolwin100  @souravjain540

**Comment by yuval-hazaz** [comment]
Thanks everyone, 
in the last release, we removed the light theme, so we do not need to handle this any longer. I will close the issue
