### ISSUE TITLE
Settings should display selected App color

### ISSUE THREAD

**Issue by Shubhdeep12** [amplication/amplication#3519]
### Feature description

In App settings, platform should indicated selected color.
![image](https://user-images.githubusercontent.com/43654389/185646086-7d8f1370-b99b-4aba-b230-7a30d4cee1a8.png)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Shubhdeep12** [comment]
I would love to add this.
Let me know once this is added in TO-do list.

**Comment by alexbass86** [comment]
We removed the ability to change color. From v15, we will have dedicated color for each service in the system.

@tupe12334 please make sure the color selection feature will be removed asap.

**Comment by yuval-hazaz** [comment]
Thanks @alexbass86 , you are correct.

It will require some changes on the API also - do not change the DB schema, please.

@Shubhdeep12 can you handle that?

**Comment by tupe12334** [comment]
@Shubhdeep12 and @yuval-hazaz, I will take it because @alexbass86 requested to solve that ASAP

**Comment by Shubhdeep12** [comment]
Sure @tupe12334 . Please go ahead.

**Comment by tupe12334** [comment]
I elaborated more on that in #3622
