### ISSUE TITLE
🐛 Bug Report: Change Entities to Entity if number is 1.

### ISSUE THREAD

**Issue by Himanxu1** [amplication/amplication#3522]
### What happened?

It should be Entity when the number is 1 .
if number > 1 == entities 

![amplication3](https://user-images.githubusercontent.com/80101755/185728264-2ab05bba-5dae-415d-808f-93c0beba0235.PNG)

### What you expected to happen

Just change the entities to entity is the number is 1 .

### How to reproduce

for reference use this file 

https://github.com/amplication/amplication/blob/master/packages/amplication-client/src/Application/EntitiesTile.tsx

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
Thanks for reporting the issue :)

**Comment by Himanxu1** [comment]
Assign this to me !⚡

**Comment by aaaaayushh** [comment]
Hello, if this is still up for grabs, can I work on it?

**Comment by shehabadel** [comment]
@souravjain540 Can I work on this issue?

**Comment by souravjain540** [comment]
Done @shehabadel

**Comment by yuval-hazaz** [comment]
This issue was already resolved in https://github.com/amplication/amplication/pull/3997

**Comment by yuval-hazaz** [comment]
@shehabadel please have a look at this list and let us know if you want to work on another issue
https://github.com/amplication/amplication/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee
