### ISSUE TITLE
🐛 Bug Report: Customizable files are overwritten when you change server path and admin ui path settings

### ISSUE THREAD

**Issue by krai500** [amplication/amplication#3530]
### What happened?

Customizable files are overwritten 
when you change server path and admin ui path settings

### What you expected to happen

Customizable files should not be overwritten

### How to reproduce

1.  Sync with GitHub
2.  Go to `App settings` > `Base Directories`
3.  Set `Server Path` to  `packages/server`
4.  Set `Admin UI Path` to  `packages/admin`
5.  Rebuild and merge code to main branch
6.  Make change in Customizable files and push to main branch
7.  Rebuild again you will see the code are overwrited

**Comment by yuval-hazaz** [comment]
Thanks! It sounds like an important issue. We will look into it soon
