### ISSUE TITLE
🐛 Bug Report: Workspace navigation should show the current item as selected 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3531]
### What happened?

When selecting a resource (service) in the workspace navigation, it shows the service name as the currently selected item. 

for example:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/43705455/185762713-5488a6c5-78bf-49a6-a36b-bedb55336f51.png">

but, when the current page is "Commits", or "Code View", or "Project Configuration" - the navigation shows the test "Resource List" instead of the current item. 
for example:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/43705455/185762774-5fd02c32-361f-405e-a99c-6dc6366e95ef.png">

### What you expected to happen

The navigation element should always show the selected item 

### How to reproduce

see scrrenshot above

### Amplication version

0.15.0

**Comment by abrl91** [comment]
duplicate #3555 Fixed by https://github.com/amplication/amplication/pull/3547
