### ISSUE TITLE
🐛 Bug Report: Unable to fetch and select last github repo when total no of repo exceeds 35 in count

### ISSUE THREAD

**Issue by heisenbergwasuncertain** [amplication/amplication#3535]
### What happened?

i had more than 40 repos in my profile and when i created a repo for amplication project that was last by alphabetical order it wasn't able to fetch and there isn't any search option to find that by name!

### What you expected to happen

It'll be able to fetch more than where it is limited right now or should have a  search option for that

### How to reproduce

just create a repo by name starting with last alphabets and you must have more than 35 repos active!

### Amplication version

latest

**Comment by souravjain540** [comment]
Duplicate of https://github.com/amplication/amplication/issues/2551
