### ISSUE TITLE
🐛 Bug Report: Show The Selected Resource after each selection or refresh

### ISSUE THREAD

**Issue by barshimi** [amplication/amplication#3544]
### What happened?

When choosing new resource or project entities (like: comments, settings etc) the dropdown title should be updated accordingly.  

### What you expected to happen

set the right resource after each selection at application header

### How to reproduce

choose different resource under resource dropdown

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/3547
