### ISSUE TITLE
🐛 Bug Report: Delete resource does not clear the pending changes

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3545]
### What happened?

Delete resource does not clear the pending changes

### What you expected to happen

When a user deletes a resource immediately after creating, the pending changes should be cleared it

### How to reproduce

- create a resource
- see the pending changes
- delete the resource
- see that the pending changes are still there

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GreenMachine01** [comment]
Closed duplicate of https://github.com/amplication/amplication/issues/4017
