### ISSUE TITLE
Hover effect on the links of header

### ISSUE THREAD

**Issue by Himanxu1** [amplication/amplication#3578]
### Feature description

It would look great if we make the links more attractive . for this we have to add a hover effect on the links in header.

Here is the SS.

![feature1](https://user-images.githubusercontent.com/80101755/186329775-e41ee183-755c-42d7-9b5e-e83ecbf53cab.PNG)

### Use case

User Experience

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
which link are you talking about? @Himanxu1

**Comment by Himanxu1** [comment]
Links on the Header of the website like Docs , features .
They don't have any hover effect .

**Comment by souravjain540** [comment]
I would confirm it first with @alexbass86, if we want it or not?

**Comment by alexbass86** [comment]
@souravjain540 Yes, please add the hover effect on the link at the menu. 
The text should turn white on hover/selection.

**Comment by Himanxu1** [comment]
okay

**Comment by Himanxu1** [comment]
@souravjain540  Assign this to me .
In which directory code is present related to navbar?

**Comment by souravjain540** [comment]
> @souravjain540 Assign this to me . In which directory code is present related to navbar?
assigned
path: components/Header/Menu/index.jsx

**Comment by Himanxu1** [comment]
done
