### ISSUE TITLE
Updating the Contact us 

### ISSUE THREAD

**Issue by lavakush07** [amplication/amplication#3581]
- Instead of the long [contact@amplication.com](mailto:contact@amplication.com) we can add emoji of the mail (📧) with the link embedded in it .

**Comment by lavakush07** [comment]
- Can you Assign me this issue to work on .

**Comment by souravjain540** [comment]
Hi @lavakush07, thanks for the suggestion. Let me confirm with @alexbass86 and @yuval-hazaz if we want to do this or not.

**Comment by yuval-hazaz** [comment]
which page are we talking about? is that for the website footer?

**Comment by lavakush07** [comment]
![Screenshot 2022-08-24 163836](https://user-images.githubusercontent.com/70131581/186604481-0f9888bd-4330-4f7d-bbf1-1e31085427f2.png) 
- Yeah Exactly **website footer**.

**Comment by yuval-hazaz** [comment]
Thanks, it is ok the way it is right now with the address visible ,
I will close this issue
