### ISSUE TITLE
🐛 Bug Report: Commit empty state is missing

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3582]
### What happened?

Empty state for the commit list looks bad
![image](https://user-images.githubusercontent.com/43705455/186596148-88ffd9a6-ad7c-4010-b8b1-8cd056c727c1.png)

### What you expected to happen

show a proper empty list message with the empty state graphics 

### How to reproduce

create a new project and go to the commits page

### Amplication version

0.15.0

**Comment by yuval-hazaz** [comment]
@alexbass86 please prepare a mock

**Comment by alexbass86** [comment]
Please use this empty state.
https://www.figma.com/file/1BN7FXfK6trj6xsvHLSnk6/%233582%2C-%233583---view-empty-state?node-id=1704%3A3057

![Commit empty state](https://user-images.githubusercontent.com/96179897/188854183-393a7a5a-7211-428b-a8ef-d971667943e6.png)

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/3761
