### ISSUE TITLE
🐛 Bug Report: Code view empty state is missing 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3583]
### What happened?

the code view page looks bad before the first commit 

![image](https://user-images.githubusercontent.com/43705455/186610292-653b1001-f839-4ad1-8305-55a34d09e878.png)

### What you expected to happen

Show a message to the user that says:

"in this page you can see the code of your services after you commit your changes" 

@MoFoGo please rephrase as needed

@alexbass86 please prepare the design

### How to reproduce

open code view page before making the first commit

### Amplication version

0.15.0

**Comment by tupe12334** [comment]
Duplication of #3582

**Comment by alexbass86** [comment]
Please use this design for the empty state
https://www.figma.com/file/1BN7FXfK6trj6xsvHLSnk6/%233582%2C-%233583---view-empty-state?node-id=836%3A18964
also, please make sure the dropdown fields are disabled with the text "none" in the `commit-selector-item__title`

![Project - view code](https://user-images.githubusercontent.com/96179897/188853598-d715f41f-3f2b-4df0-9f3f-32cf9971d67e.png)

**Comment by abrl91** [comment]
> 



> Duplication of #3582

@tupe12334 this is not the same issue. One is for the code view page and the other is for the commits page
