### ISSUE TITLE
 🐛 Bug Report: Last sync value is incorrect

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3585]
### What happened?

When you sync to GitHub and look at the Last sync value in the client, it's not right.

<img width="460" alt="Screen Shot 2022-08-25 at 10 57 49" src="https://user-images.githubusercontent.com/61761153/186611037-fd8e7da7-f74a-43a3-a349-505b821374fb.png">

This happened before the first build
### What you expected to happen

Show the correct time

### How to reproduce

Generate a resource and connect to GitHub

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by muhsinkamil** [comment]
Hey @tupe12334 I can look this up

**Comment by tupe12334** [comment]
Yes of course @muhsinkamil

**Comment by prakhar-198** [comment]
Hey ! @muhsinkamil Please can you guide or brief me about how to fix the issue?

**Comment by yuval-hazaz** [comment]
@prakhar-198 have a look at this file packages/amplication-client/src/Resource/git/AppGitStatusPanel.tsx
you need to display "never" instead of the date

**Comment by FroostyCodes** [comment]
Hi @yuval-hazaz @souravjain540 Can I work on it?

**Comment by TheLearneer** [comment]
Hi there 👋 
Any updates on here, if not I would love to work on it 🙇

**Comment by abrl91** [comment]
> Update AppGitStatusPanel.tsx #4217

I left a comment in the issue's conversation. Let's give him another 2 days. Otherwise, we'll assign you

**Comment by TheLearneer** [comment]
Hi @abrl91 👋 
Don't mind me bumping it up 😅

**Comment by abrl91** [comment]
@TheLearneer I assigned you 😃

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4272
