### ISSUE TITLE
🐛 Bug Report: Text over flow in commit selector

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3586]
### What happened?

The commit selector in the code, view page is overflow

<img width="427" alt="Screen Shot 2022-08-22 at 17 46 54" src="https://user-images.githubusercontent.com/61761153/186614798-0344ccb0-9c43-45d0-a99d-6060d0511989.png">
<img width="419" alt="Screen Shot 2022-08-25 at 10 56 02" src="https://user-images.githubusercontent.com/61761153/186614802-9008390c-4972-4343-b729-c70992bdb63f.png">

### What you expected to happen

not relevant

### How to reproduce

not relevant

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/3594
