### ISSUE TITLE
🐛 Bug Report: Header menu wrong indication

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3587]
### What happened?

The menu shows a V next to an item even tho we are not in the item context
<img width="948" alt="Screen Shot 2022-08-25 at 10 58 42" src="https://user-images.githubusercontent.com/61761153/186616299-5ab6720a-05c7-47e2-891c-8bb02890cb97.png">

### What you expected to happen

The V needs to show only in the resource context

### How to reproduce

not relevant

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by morhag90** [comment]
We solved it in another issue, ew limited the chars number : 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/97830649/188847340-6f94c26d-b711-48ad-a8b5-74fc01aa988a.png">
