### ISSUE TITLE
Project configuration "name" should change the project name

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3595]
### Feature description

The `name` field in the `settings` tab in the Project Configuration should change the Project name and not the resource name 

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/43705455/186851396-7b3e140a-f33b-40c2-b338-8f2212a6e4c5.png">

### Use case

When the user wants to change the name of the project, they should go into the project configuration and change the name in the settings tab

**Comment by jainpawan21** [comment]
Hi Yuval, I have figured out the root cause
Can you please assign this to me?

**Comment by EugeneTseitlin** [comment]
@jainpawan21 Go for it.
