### ISSUE TITLE
As User - I want to see a better design for the profile

### ISSUE THREAD

**Issue by Himanxu1** [amplication/amplication#3596]
**Overview:**
The current profile page looks awkward with the UI on the side and without ability to go back (Close the profile).
![bug1](https://user-images.githubusercontent.com/80101755/187018134-af8387ea-74d5-40de-9e98-9c246c7ba377.PNG)

**New Design:**
https://github.com/amplication/amplication/issues/3596#issuecomment-1229457534

**Comment by yuval-hazaz** [comment]
@alexbass86 please prepare a design

**Comment by alexbass86** [comment]
We decided to go with a popup here, the design link.
https://www.figma.com/file/5sHyIRe07OTZgclArq7y3i/%232430---User-profile?node-id=111%3A6742

No changes
![No changes](https://user-images.githubusercontent.com/96179897/187076388-56e76220-0e38-49d6-9b58-d4a8b1cde561.png)

With changes
![With changes](https://user-images.githubusercontent.com/96179897/187076394-2602d16f-2dc2-40e8-8324-013e1c99f6b5.png)

**Comment by alexbass86** [comment]
@yuval-hazaz can we try and push this to the upcoming release?

**Comment by KushalRaut** [comment]
Hi @yuval-hazaz 
Can I work on this issue if it is not being worked on currently

**Comment by Ahtritus** [comment]
@TheLearneer  Could you assign this to me if no one's working on it?

**Comment by abrl91** [comment]
> @TheLearneer Could you assign this to me if no one's working on it?

I assigned you

**Comment by Ahtritus** [comment]
> > @TheLearneer Could you assign this to me if no one's working on it?
> 
> I assigned you

Thanks! Also, should the design be similar to the one discussed above with a pop-up or do we keep the Profile page and update the styling there, as discussed in #4224 ?

**Comment by abrl91** [comment]
> > > @TheLearneer Could you assign this to me if no one's working on it?
> > 
> > 
> > I assigned you
> 
> Thanks! Also, should the design be similar to the one discussed above with a pop-up or do we keep the Profile page and update the styling there, as discussed in #4224 ?

This design: https://github.com/amplication/amplication/issues/3596#issuecomment-1229457534

**Comment by Ahtritus** [comment]
Got it

**Comment by GreenMachine01** [comment]
@Ahtritus any updates?

**Comment by jaysoni-ash42** [comment]
@GreenMachine01  can i work on this issue ?

**Comment by GreenMachine01** [comment]
@jaysoni-ash42 assigned to you :) good luck!

**Comment by jaysoni-ash42** [comment]
@GreenMachine01  not able to access figma design can you approve the access

**Comment by GreenMachine01** [comment]
@alexbass86 please allow access to the Figma file to @jaysoni-ash42

**Comment by jaysoni-ash42** [comment]
@alexbass86  any updates on access for figma design ?

**Comment by alexbass86** [comment]
@jaysoni-ash42  Hi, please use this link. Thank you so much for the contribution :)
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1425%3A19040&t=90EjYt2wYx6Ncklb-1
