### ISSUE TITLE
🐛 Bug Report: Last commit label is empty after generating a new resource

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3597]
### What happened?

After creating a new resource, the last commit label is empty.
 
<img width="843" alt="Screen Shot 2022-08-27 at 12 38 56" src="https://user-images.githubusercontent.com/39680385/187024717-b9bd9480-3182-451f-8492-11a837557c0e.png">

### What you expected to happen

When there is no last commit, we shouldn't show the label
@alexbass86  @yuval-hazaz am I correct?

### How to reproduce

Create a new resource and see the result

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by alexbass86** [comment]
@abrl91 let's just write "no commits yet" @MoFoGo, what is the best copy for this case?
![entity_card](https://user-images.githubusercontent.com/96179897/187076301-9f03120f-9862-4380-b761-969534a5bfa1.png)

**Comment by tupe12334** [comment]
@alexbass86 Can you please provide a link to this Figma design?

**Comment by abrl91** [comment]
> @alexbass86 Can you please provide a link to this Figma design?
it looks like the same font and color as the service description

ןא
