### ISSUE TITLE
🐛 Bug Report: The links to project configuration settings and service settings on pending changes lead to an empty page

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3598]
### What happened?

The links to project configuration settings and service settings on pending changes lead to an empty page.

https://user-images.githubusercontent.com/39680385/187026333-c505b202-5f65-4be9-b571-d5cc1ff7f352.mov

### What you expected to happen

those links should lead to the project settings page and service settings page

### How to reproduce

Create a new service , you will see in the pending changes the links, click on them and see the result 

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Himanxu1** [comment]
assign this to me .
