### ISSUE TITLE
🐛 Bug Report: Sync with GitHub selector - `chevron_down` icon position is not permanent

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3601]
### What happened?

Sync with GitHub selector - `chevron_down` icon position is not permanent
<img width="695" alt="Screen Shot 2022-08-27 at 21 46 03" src="https://user-images.githubusercontent.com/39680385/187044242-72d82153-1994-4354-a5f9-a9216d600435.png">
<img width="692" alt="Screen Shot 2022-08-27 at 21 47 05" src="https://user-images.githubusercontent.com/39680385/187044243-d7fd68a2-c4ea-4dcb-a4ad-3588f1069518.png">

### What you expected to happen

I expect the icon to be located at the same place no matter how long the text is

### How to reproduce

- go to sync with GitHub page
- select two organizations with different names and make sure one is longer than another

### Amplication version

0.15.0

**Comment by orlandoortegajr** [comment]
Hi @abrl91 👋, I found a solution to this issue and submitted a PR for it. Let me know what you think 😃
