### ISSUE TITLE
🐛 Bug Report: Sync with GitHub selector is not aligned with the design

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3604]
### What happened?

Sync with GitHub selector is not aligned with the design: 
- The `hr` should be thinner and lighter.

<img width="344" alt="Screen Shot 2022-08-27 at 22 02 53" src="https://user-images.githubusercontent.com/39680385/187045649-5ca64734-edad-43e7-b163-1191ddd0e9b1.png">

### What you expected to happen

It should look as follows:

```
border: $border-black5;
```

### How to reproduce

Go to sync with GitHub page and open the sector. If you are not synced yet, click on connect with GitHub button

### Amplication version

0.15.0

**Comment by abrl91** [comment]
@alexbass86 should we provide a link to Figma?

**Comment by Himanxu1** [comment]
Assign this to me

**Comment by abrl91** [comment]
> Assign this to me

Done

**Comment by westlag114** [comment]
Is someone still working on this issue? If not, I'm willing to pick it up
@yuval-hazaz
