### ISSUE TITLE
🐛 Bug Report: Commit card - Update components view

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3610]
### What happened?

We figured out that the current look and behavior of the commit card aren't working as we thought it would work, and currently, it's not clear enough where the action buttons are and what is the next step in the user flow. 

**Old** - we have three action buttons here (icon, changes, view log)
It's tough to understand that this is clickable, and it's different from other look-a-like components where the whole card is clickable.
![123](https://user-images.githubusercontent.com/96179897/187074512-c081f126-9240-40af-b7b3-709697c557f8.png)

**New** - the whole card is now clickable and works exactly like the resource card and other look-a-like cards. We will be redirected to the view log screen by clicking on the card.
![commit_card](https://user-images.githubusercontent.com/96179897/188451815-70539170-f6b9-4a36-b53c-86a41201ff88.png)

Figma:
https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=1307%3A13971

### What you expected to happen

We need to be consistent with other components in the system.

### How to reproduce

Go to the commit screen.

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@alexbass86 can you please update the screenshot with the recent changes as we discussed?

**Comment by alexbass86** [comment]
@arielweinberger let's try to push this change to 15.2

**Comment by yuval-hazaz** [comment]
@alexbass86 I am missing a link to the resource in the new design. Did we remove this on purpose?

**Comment by abrl91** [comment]
> @alexbass86 I am missing a link to the resource in the new design. Did we remove this on purpose?

the commit card is the link to the resource

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/3760
