### ISSUE TITLE
Adding & improving links in the README header

### ISSUE THREAD

**Issue by Prajnaprabhu3** [amplication/amplication#3615]
#### I was going through the README and felt the links to Docs and Twitter could be changed a bit. And additional links can be  added

![image](https://user-images.githubusercontent.com/74554892/187089937-9c9d20f8-218f-4de5-ba06-2861a69336a4.png)

### Use case

![image](https://user-images.githubusercontent.com/74554892/187090212-2f916571-79fc-409c-909b-36b504cd74a2.png)
 
### <p align="center" size="300px"> or </p>

![image](https://user-images.githubusercontent.com/74554892/187090272-a295739f-aca5-40f8-a21c-93697f4db727.png)

### <p align="center" size="300px"> or </p>

![image](https://user-images.githubusercontent.com/74554892/187090426-76d9e13a-14b9-454b-b292-678106c478da.png)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by arielweinberger** [comment]
I actually like your suggestion quite a bit. Feel free to submit a PR!

I personally liked #2 (bullet points) in between most.

@yuval-hazaz What do you think?

**Comment by souravjain540** [comment]
I liked the first one

**Comment by Prajnaprabhu3** [comment]
should I go with 1st or 2nd ?

**Comment by yuval-hazaz** [comment]
I also vote for 1 - with pipes |

**Comment by souravjain540** [comment]
> I also vote for 1 - with pipes |

@Prajnaprabhu3 go with number 1

**Comment by Prajnaprabhu3** [comment]
will submit a PR by eod
