### ISSUE TITLE
🐛 Bug Report: Pending changes panel -hover on the bottom buttons

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#3617]
### What happened?

Hover state on the compare and discard changes icons are in the bottom of the button, we can't see it unless i scroll down, it should be above the icon.
<img width="240" alt="Screen Shot 2022-08-29 at 11 02 14" src="https://user-images.githubusercontent.com/8940907/187154223-74227a1c-36e0-4e60-924d-efa9d6a6ca06.png">

### What you expected to happen

should be above the icon so we can see it.

### How to reproduce

.

### Amplication version

0.15.0

**Comment by souravjain540** [comment]
@arielweinberger @alexbass86  have a look

**Comment by alexbass86** [comment]
Thanks, @MatanForU , you're right. This is a bug, and the tooltip should appear on top of the icon without affecting the whole container. Also, we currently have two scroll bars without any reason. Please make sure to hide them if there is no need for them. And ensure the color of the scroll bar is aligned with the design.

**Comment by arielweinberger** [comment]
@yuval-hazaz Please prioritize

**Comment by yuval-hazaz** [comment]
yes, please go ahead and fix it

**Comment by alexbass86** [comment]
> @alexbass86 please approve this UI, this bug is not relevant any more

I closed it. From what I see, its already been fixed
