### ISSUE TITLE
Custom user color removal

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3622]
We need to remove the option from the user of selecting a custom color for a resource.
From now on, the color will be selected by the resource type.
![Screen Shot 2022-08-29 at 13 58 13](https://user-images.githubusercontent.com/61761153/187186436-d91b433c-2406-42c1-a11b-1c7a9b45598b.png)
This change effecting the client, server, dtos, and the DB

**Comment by morhag90** [comment]
@tupe12334  can we close this issue?
