### ISSUE TITLE
Unused `ApplicationBadge` component

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3624]
We have the `client/src/Resource/ApplicationBadge.tsx` component but it is not in use. We can remove it.

**Comment by Himanxu1** [comment]
Assign this to me .
in version 0.15.1 ??

**Comment by tupe12334** [comment]
Yes @Himanxu1, it's 0.15.1, have a good luck

**Comment by Himanxu1** [comment]
I also have to delete the css file ?? @tupe12334

**Comment by tupe12334** [comment]
@abrl91 Are you agreeing with this issue, I want to know before someone is merging the PRs

**Comment by abrl91** [comment]
> src/Resource/ApplicationBadge.tsx

approved
