### ISSUE TITLE
Update Build creation time at Commit page

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#3635]
![image](https://user-images.githubusercontent.com/6080188/187476375-68accf34-44be-4d27-85c5-aa5ce8852a1e.png)
Currently add to queue task and generation are shown with zero duration time. These durations should greater than zero.

**Comment by yuval-hazaz** [comment]
@EugeneTseitlin please add details and assign to a project

**Comment by yuval-hazaz** [comment]
@EugeneTseitlin wasn't that fixed already?

**Comment by EugeneTseitlin** [comment]
@EugeneTseitlin Yep, it was fixed.
