### ISSUE TITLE
🐛 Bug Report: Commit page - Wrong padding between selection

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3638]
### What happened?

Wrong padding between selections in our commit screen. 
Let's ensure we have a padding of 8px between each commit selection.

Bad:
![image](https://user-images.githubusercontent.com/96179897/187361738-79e2711d-0396-44e0-ba09-8517a8b9af04.png)

How it should be:
![image](https://user-images.githubusercontent.com/96179897/187361821-6219e081-30a4-4c48-bfdb-300170f25437.png)

Also, please make sure that the profile and text have 8px padding
![image](https://user-images.githubusercontent.com/96179897/187362005-fec5d24d-61bd-4738-9e56-29c702c1adf6.png)

### What you expected to happen

Same padding values as in the design

### How to reproduce

Go to the commit screen.

### Amplication version

0.15.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Plan
Go to "CommitList" component which is located at "amplication/packages/amplication-client/src/VersionControl/CommitList.tsx"
Align component and subcomponents styles according to design
Here is the design:
https://www.figma.com/file/71Ut91hFxC7cpLbJQQMsgP/%233141---Project-Commit-Flow?node-id=836%3A18964&t=U9JtPFH17ehqH0BX-1

Plan was written by @EugeneTseitlin

**Comment by abrl91** [comment]
Moved to "reopen" due to a bug in the sidebar on each page that we use the sidebar. It should be wider


![Image](https://user-images.githubusercontent.com/39680385/217226238-b0957233-60ca-4b08-ac19-0f68691163ec.png)




![Image](https://user-images.githubusercontent.com/39680385/217226367-17244419-d617-4a3b-9fd2-c121009db166.png)

**Comment by overbit** [comment]
## Tests result report (for PR #5145)

### Scenarios
	
1. Scenario description: Login and browse on difference pages
	 Status: 🟥  `FAILED`
	 Proof of execution:  Tested on Firefox and Safari
	 `Sandbox` 
	 <img width="1273" alt="Screenshot 2023-02-07 at 16 49 05" src="https://user-images.githubusercontent.com/2861984/217310370-aa81a50d-be3b-4d50-b7de-4e9ca8d385b5.png">
	 
	 
	 `Production` 
	 <img width="1274" alt="Screenshot 2023-02-07 at 16 48 48" src="https://user-images.githubusercontent.com/2861984/217310325-505924a9-07f1-4c29-91fd-62bbf0508cc6.png">

**Comment by levivannoort** [comment]
As can be seen in the screenshot provided by Daniele, on the project settings/resources the box also touches the right side and the add resource button also has this same behaviour on both Firefox and Safari.

**Comment by levivannoort** [comment]
I've previously opened an issue about this: #5022
