### ISSUE TITLE
🐛 Bug Report: Top menu fast nav - Wrong padding, font-weight, dropdown

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3641]
### What happened?

The current look and behavior of our "Top menu fast nav" look different than the original design. Please align it.

**Wrong padding, font weight:**
![image](https://user-images.githubusercontent.com/96179897/187372674-39a3f135-9676-44bd-a6c0-e485e1b6f267.png)

**How it should look:**
![image](https://user-images.githubusercontent.com/96179897/187372727-534fd845-f49f-433c-8f7e-0bb5b02132db.png)

**Bad drop-down look:**
![image](https://user-images.githubusercontent.com/96179897/187373175-69224e3c-3206-48ba-bf16-6ea1a6b456e4.png)

**How it should look:**
![image](https://user-images.githubusercontent.com/96179897/187373816-86f8c65b-ac65-450b-9bfc-c007ba3486fc.png)

**Some values for help:**
Inner padding is 8px
![image](https://user-images.githubusercontent.com/96179897/187374074-9f6e2a00-c1b7-455c-9938-013b924c01cd.png)

**Padding between the selection is 4px**
![image](https://user-images.githubusercontent.com/96179897/187374163-d4194152-0768-462d-a3dd-f6aba49c7c26.png)

The border color is #515873
Bg color is #22273C

All of the colors and states you can find here:
https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=1346%3A15368
![select-service](https://user-images.githubusercontent.com/96179897/187374540-39ed1085-f5c2-4924-a5d2-347e0a93563d.png)

Please also make sure the drop-down has the proper drop shadow values.

### What you expected to happen

The dropdown should be aligned with the design.

### How to reproduce

Just click on the select resource on top of fast navigation.

### Amplication version

0.15.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
i am also adding this 
![image](https://user-images.githubusercontent.com/43705455/188563719-1617f4c0-1f4f-440c-9fa3-36c28a74218c.png)

when the list is long - there is no scroll, and all the items are pushed closer to each other

**Comment by yuval-hazaz** [comment]
### What happened?

The current look and behavior of our "Top menu fast nav" look different than the original design. Please align it.



Inner padding is 8px
![image](https://user-images.githubusercontent.com/96179897/187374074-9f6e2a00-c1b7-455c-9938-013b924c01cd.png)

**Padding between the selection is 4px**
![image](https://user-images.githubusercontent.com/96179897/187374163-d4194152-0768-462d-a3dd-f6aba49c7c26.png)

The border color is #515873
Bg color is #22273C

All of the colors and states you can find here:
https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=1346%3A15368
![select-service](https://user-images.githubusercontent.com/96179897/187374540-39ed1085-f5c2-4924-a5d2-347e0a93563d.png)

Please also make sure the drop-down has the proper drop shadow values.

### What you expected to happen

The dropdown should be aligned with the design.

### How to reproduce

Just click on the select resource on top of fast navigation.

### Amplication version

0.15.1

### Environment

_No response_

### Are you willing to submit PR?

Yes I am willing to submit a PR!
