### ISSUE TITLE
Improve GitHub App Docs

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3642]
There are currently two issues with our GitHub Apps.

1. The [Connect Amplication server to GitHub](https://docs.amplication.com/docs/connect-server-to-github/) documentation page has semantic errors. It uses the terminology `GitHub App` but it is actually related to `OAuth App`. Please fix that.
2. The [Sync with GitHub](https://docs.amplication.com/docs/sync-with-github/) documentation page only shows how to sync. We need a **separate article in our documentation** called `Creating a GitHub App` that explains how to create this app, with detailed screenshots explaining the access needed and webhooks to toggle etc.

**Comment by GreenMachine01** [comment]
@arielweinberger 
Do we need this item?

**Comment by yuval-hazaz** [comment]
yes, there is an open PR about this in the docs repo
