### ISSUE TITLE
🐛 Bug Report: Button - Not aligned with the new design

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3644]
### What happened?

We must align all our buttons in the system to our new visual language.

This is how it currently looks:
![image](https://user-images.githubusercontent.com/96179897/187409335-039b439c-45ae-4dab-8c83-c8efc9a6f8ff.png)

![image](https://user-images.githubusercontent.com/96179897/187409376-84fdf87e-3de1-49f9-adcb-5954c189923c.png)

![image](https://user-images.githubusercontent.com/96179897/187409436-008622e5-0af6-468f-a558-4b119870acc4.png)

![image](https://user-images.githubusercontent.com/96179897/187409472-9bb509c1-8281-4efd-86dc-f12ddc70a411.png)

And this is how it spouse to look:
![Group 1](https://user-images.githubusercontent.com/96179897/187409808-3f640859-5a7b-4e68-84b0-1a67fa344dad.png)

**Figma**
https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=1246%3A13116

### What you expected to happen

All our buttons in the system should be aligned with the new design.

### How to reproduce

Everywhere in the system.

### Amplication version

0.15.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by alexbass86** [comment]
> Hey @alexbass86 can i take up this issue please?

Sure! :) good luck

**Comment by punithnayak** [comment]
Hey @alexbass86  can I get the Figma access https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=1246%3A13116 
Email:npunith125@gmail.com

**Comment by alexbass86** [comment]
@punithnayak please use this public link
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?type=design&node-id=0%3A1&t=CebFIWDGs00foQuK-1

**Comment by yuval-hazaz** [comment]
This was already handled in the ui/v2
