### ISSUE TITLE
Adding the resource name to the PR title

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3648]
### Feature description

When you press the build and Amplication opens your PRs, we need to add an identifier to the title of the PR.
Now its looks like `Amplication build hko72mr9`
We need to change that.
@yuval-hazaz Please comment below as the product want do you want to change it to.

**Comment by yuval-hazaz** [comment]
We are working on several changes in this area, including a single PR for all resources.
I will close this issue for now, and if needed once we complete working on the branching strategy we will review again
