### ISSUE TITLE
🐛 Bug Report: Project configuration - UI Problems (Padding, icon, height, text color, text size)

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3649]
### What happened?

We need to ensure all pages in our system have the same padding values to prevent strange visual jumps and inconsistency.

**Bad:**
![image](https://user-images.githubusercontent.com/96179897/187437473-06ad251b-ec35-4dc1-9308-4736427486ab.png)

**How it spouse to be:**
![2  Project Settings](https://user-images.githubusercontent.com/96179897/187437934-1d92a64d-c4c2-4a81-aedd-7aabd46af56b.png)

**More:**
![image](https://user-images.githubusercontent.com/96179897/187438029-887c4dea-333e-4697-9986-1eb6f7e85f34.png)

**Values:**

- padding 16px everywhere
- profile pic has the project settings official icon, not text
- both icon and title text #2C3249 color not white
- the official color of project settings is not red but yellow
- sync with GitHub button should be the same as other buttons and not full width
- top banner now 140px, it need to be 180px

### What you expected to happen

The overview screen needs to be aligned with the design.

### How to reproduce

Go to the project configuration screen.

### Amplication version

0.15.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@alexbass86 can you please check if this is still relevant?

**Comment by alexbass86** [comment]
All good @yuval-hazaz
