### ISSUE TITLE
🐛 Bug Report: Generated app `SERVER_PORT` and `PORT` env variables used inconsistently

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3652]
### What happened?

# The Problem
Currently, in a generated app's `.env` file, we have an environment variable called `SERVER_PORT`. This is inconsistent with the `PORT` environment variable expected by the server. Basically, there is no easy way to change the server port via `.env`. Instead it has to be manually changed in the `main.ts` file.

# Proposed Solution
We need to be consistent.

1. Modify the name of this `.env` variable to `PORT`
2. Use this name in `docker-compose.yml`

# Acceptance Criteria
I should be able to modify the port in `.env` and have it reflected automatically in the generated app (so the server will use that port). This will also be picked up by `docker-compose.yml`. `Dockerfile` is currently out of scope for this.

### Amplication version

0.15

**Comment by arielweinberger** [comment]
@yuval-hazaz Please prioritize

**Comment by alinehaxkar** [comment]
Could I work on it?

**Comment by alinehaxkar** [comment]
Could I work on it?

**Comment by yuval-hazaz** [comment]
hi @alinehaxkar 
I assigned it to you. let us know if you need any help. 
please note, that the fix is needed in the generated code, so it requires to change the code in "./packages/amplication-data-service-generator"

**Comment by ahlavorato** [comment]
Hello, I already create a pr with my person account. Thanks for being open

**Comment by alinehaxkar** [comment]
Hello, I already create a pr with my person account. Thanks for being open

**Comment by ahlavorato** [comment]
Hello if you want to closed it, is already merged =)
