### ISSUE TITLE
🐛 Bug Report: Resource card - UI Problems

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3653]
### What happened?

We have some minor problems with our current resource card.

1. Name - we should only support 50 characters.
2. Description - We should support only 180 characters. 
3. Hover - on hover, the divider disappears. Please align both states with the design.
4. Badge - The badge becomes broken if the name has two rows. This probably will not happen when we disable the amount of character we allow in the name of the components, but please make sure it's not happening.
5. No commit - the message when we don't have any commit is too close to the title "last commit" please add space of 8px.

Figma
https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=17%3A1510

Example
![entity_card](https://user-images.githubusercontent.com/96179897/187441893-a91c1f34-0691-4e3a-863a-bd4550a47c46.png)

### What you expected to happen

The look and behavior of the component should be exactly like it's on the design system.

### How to reproduce

On the main screen, just create a resource.

### Amplication version

0.15.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@alexbass86 

> * Name - we should only support 50 characters.

Why? is that just for UI purposes, or is there any other reason? I don't want to block the user for no reason. I understand we can limit the length of the name and should not allow any length, but why 50? 
For example, we are using today a service called "amplication-git-pull-request-service" - 36 chars. 50 is too little, in my opinion. 
The limit should include all extreme scenarios. Also, we can easily assume that if no one really needs more than 50 chars, so no one will use more than 50 chars... so why should we add the limit?

> * Description - We should support only 180 characters.
Same as above. 
For example - this is a real description of our blog service. 229 chars
<img width="885" alt="image" src="https://user-images.githubusercontent.com/43705455/187754235-13b8c1cb-a5f2-4c34-b9e1-8de21b43632f.png">


Also, to make sure we can move forward with the items we agree on, and keep the conversation going on other items - please make sure you open a separate issue for each fix needed.

**Comment by alexbass86** [comment]
> @alexbass86
> 
> > * Name - we should only support 50 characters.
> 
> Why? is that just for UI purposes, or is there any other reason? I don't want to block the user for no reason. I understand we can limit the length of the name and should not allow any length, but why 50? For example, we are using today a service called "amplication-git-pull-request-service" - 36 chars. 50 is too little, in my opinion. The limit should include all extreme scenarios. Also, we can easily assume that if no one really needs more than 50 chars, so no one will use more than 50 chars... so why should we add the limit?
> 
> > * Description - We should support only 180 characters.
> >   Same as above.
> >   For example - this is a real description of our blog service. 229 chars
> 
> <img alt="image" width="885" src="https://user-images.githubusercontent.com/43705455/187754235-13b8c1cb-a5f2-4c34-b9e1-8de21b43632f.png">
> 
> Also, to make sure we can move forward with the items we agree on, and keep the conversation going on other items - please make sure you open a separate issue for each fix needed.

@yuval-hazaz Okay, so let's allow them to write as many characters they wish, but hide it with the "show more" button this way, we don't mess up with the UI yet still allow them the freedom to write how many characters they need.

Something like
![Group 1698](https://user-images.githubusercontent.com/96179897/187839471-0219a9fe-a4a1-4062-be6d-036f21f0cecc.png)
 that

**Comment by yuval-hazaz** [comment]
ok, thanks @alexbass86 
I will move to "ready for dev"

**Comment by akshitarora921** [comment]
Hi @barshimi, Are you working on this?

**Comment by wiseaidev** [comment]
Hey @yuval-hazaz. I want to work on this issue. However, the only thing that I can tell has been changed from the original ticket is the following bullet point:

> Description - We should support only 180 characters.

And should be replaced with:

> Description - We should implement a `show more/less` functionality for a string length > 180 characters.

**Comment by yuval-hazaz** [comment]
@wiseaidev thanks for pointing this out.
I am adding @alexbass86 to review, and I suggest opening a new issue with exact instructions just on the parts that are missing, and also adding access to the figma file. 

@wiseaidev, Alex should be back from an holiday on Tuesday, so please be patient

**Comment by alexbass86** [comment]
> Hey @yuval-hazaz. I want to work on this issue. However, the only thing that I can tell has been changed from the original ticket is the following bullet point:
> 
> > Description - We should support only 180 characters.
> 
> And should be replaced with:
> 
> > Description - We should implement a `show more/less` functionality for a string length > 180 characters.
> 
> Edit: The Figma link is not working:
> 
> ![Screenshot from 2022-10-12 15-49-44](https://user-images.githubusercontent.com/62179149/195347074-16431bfc-45f0-46ef-889c-6ddd5507050a.png)
> 
> My guess is either the file was deleted, or an internal team is handling the issue, and outsiders need perms to access this file.

Thank you for your contribution. Here is the working link.
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1117%3A14242

**Comment by evansnguyen** [comment]
Hi @alexbass86 
Can I work on this issue please 👀

**Comment by yuval-hazaz** [comment]
@evansnguyen thanks! assigned to you

**Comment by abrl91** [comment]
@barshimi please link you PR to this issue

**Comment by overbit** [comment]
@tupe12334, review / fix if possible by the end of 6/02/23. Otherwise move to next sprint

**Comment by souravjain540** [comment]
@GreenMachine01 please confirm if this still exists or not

**Comment by GreenMachine01** [comment]
@alexbass86 please review what still needs to be fixed and update the ticket

**Comment by alexbass86** [comment]
> @alexbass86 please review what still needs to be fixed and update the ticket
where can i see this fixes?

**Comment by GreenMachine01** [comment]
@alexbass86 there are no fixes. since a lot of time passed they are asking if all the issues you reported are still relevant.

**Comment by yuval-hazaz** [comment]
@GreenMachine01 @alexbass86 I suggest to close this issue and open multiple small issues in case there are still gaps

**Comment by yuval-hazaz** [comment]
closing due to inctivity
