### ISSUE TITLE
🐛 Bug Report: Workspace settings/members - UI Issues + Bugs

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3654]
### What happened?

When we go to Workspace settings/members, we should see the commit component currently. It looks broken, so please ensure this page is aligned with the design.

**Bad**
![screencapture-app-amplication-ckx7g7jcr210491bs6y595a5d1-settings-2022-08-30-16_32_56](https://user-images.githubusercontent.com/96179897/187450627-4deca5bc-8b32-4b78-a4d8-7b9cc9af265a.png)

![screencapture-app-amplication-ckx7g7jcr210491bs6y595a5d1-members-2022-08-30-16_33_06](https://user-images.githubusercontent.com/96179897/187450648-cc218e6a-4259-419d-ad27-476cb69b978c.png)

How is it supposed to look
![Members Settings](https://user-images.githubusercontent.com/96179897/187451768-1eb609ec-a922-4b54-a903-f3d7220e7a2f.png)

![Workspace Settings](https://user-images.githubusercontent.com/96179897/187451772-d353380b-825d-453a-8646-3cb3a768fde3.png)

Figma
https://www.figma.com/file/AKcZ9rk6QDMponJrQVDCDC/%232961%2C-%233057---New-Project?node-id=836%3A18964

### What you expected to happen

Both pages should look the same as the design.

### How to reproduce

Go to Workspace settings/members.

### Amplication version

0.15.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@alexbass86 can you please check if this is still relevant, and if it is please explain what is needed

**Comment by roopeshsn** [comment]
I would like to work on this issue, @souravjain540!

**Comment by souravjain540** [comment]
@roopeshsn assigned you another issue

**Comment by prasadfirame** [comment]
Is this assigned to anyone?,i would like to work on this issue

**Comment by souravjain540** [comment]
@prasadfirame sure!

Let us know if you need any help in solving this issue. Join our discord, team would love to help :)

**Comment by souravjain540** [comment]
@prasadfirame any updates?

**Comment by prasadfirame** [comment]
yeah ,just give me some time i was busy ,will work on this issue today,will let you know..:)

**Comment by prasadfirame** [comment]
hey i'm sry,my pc is pretty old ,i tried running amplication on my pc but im getting so many error's ,thank you for giving me this opportunity ,plz assign this to someone else..

**Comment by souravjain540** [comment]
@sambhavgupta0705 any updates?

**Comment by sambhavgupta0705** [comment]
Sorry busy with my exams for now

**Comment by devXprite** [comment]
Hii @souravjain540 I would like to work on this issue.

**Comment by devrajosc** [comment]
@souravjain540 I would like to solve this issue.

**Comment by souravjain540** [comment]
assigned @devrajosc :)

**Comment by abrl91** [comment]
passed QA ✅

Before accepting the invitation:
https://github.com/amplication/private-issues/issues/2

After accepting the invitation:
![Image](https://github.com/amplication/amplication/assets/39680385/32f67043-32d3-4c3f-88f4-a1678065c941)
