### ISSUE TITLE
🐛 Bug Report: Admin UI base directory setting visible even if Admin UI is disabled

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3655]
### What happened?

I don't expect to see the Admin UI area in the Base Directory setting if it is disabled.
<img width="760" alt="Screenshot 2022-08-30 at 15 49 12" src="https://user-images.githubusercontent.com/4976416/187454453-06cb9ac8-db31-4609-a05d-95ab850ec714.png">

### Amplication version

0.15

**Comment by jainpawan21** [comment]
it is disabled but visible in this condition:-
<img width="447" alt="Screenshot 2022-09-03 at 7 04 13 PM" src="https://user-images.githubusercontent.com/39362422/188272835-ced4b2f8-0acd-48d1-be08-1da6bb19af40.png">
 
and
 
visible and editable in this condition
<img width="447" alt="Screenshot 2022-09-03 at 7 02 45 PM" src="https://user-images.githubusercontent.com/39362422/188272766-5bc00ec2-6a47-4887-b4ea-39f8d77d2de6.png">

what should happen in both the conditions?

**Comment by arielweinberger** [comment]
Hey @jainpawan21 I think you are mixing it with a different screen. What you demonstrated is by design - our Admin UI relies on a GraphQL API to function.

With regards to my original issue, my expectation is that if the Admin UI is switched off, I won't see the option to set its base directory at all.

**Comment by arielweinberger** [comment]
@souravjain540 I've set the "good first issue" label to this one, I think it could be good for a seasoned community member to pick up.

**Comment by rakshitgondwal** [comment]
Hey @arielweinberger !!
Can I try taking upon this issue?
