### ISSUE TITLE
🐛 Bug Report: when trying to exit 'create new workspace' it shows a typo error 

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#3657]
### What happened?

When clicking the X it shows a typo error and the icon is not aligned to the center
<img width="605" alt="Screen Shot 2022-08-30 at 17 34 36" src="https://user-images.githubusercontent.com/8940907/187466006-c92b2dd0-2e00-4fd7-8771-184f0309f780.png">

### What you expected to happen

it shouldn't show it

### How to reproduce

.

### Amplication version

0.15.2

### Plan 
Go to "NewWorkspace" which is located at "amplication/packages/amplication-client/src/Workspaces/NewWorkspace.tsx"
Here is the method that should be used in order to inject server side error to the form:
https://formik.org/docs/api/formik#seterrors-fields--field-string-string---void

Plan was written by @EugeneTseitlin

**Comment by souravjain540** [comment]
@alexbass86 please accept/reject this

**Comment by alexbass86** [comment]
> ### What happened?
> When clicking the X it shows a typo error and the icon is not aligned to the center <img alt="Screen Shot 2022-08-30 at 17 34 36" width="605" src="https://user-images.githubusercontent.com/8940907/187466006-c92b2dd0-2e00-4fd7-8771-184f0309f780.png">
> 
> ### What you expected to happen
> it shouldn't show it
> 
> ### How to reproduce
> .
> 
> ### Amplication version
> 0.15.2
> 
> ### Environment
> _No response_
> 
> ### Are you willing to submit PR?
> _No response_

You are right, and it's a bug.

**Comment by Himanxu1** [comment]
assign this to me. @yuval-hazaz

**Comment by Himanxu1** [comment]
should I have to made a PR on release/0.15.3 ?
@souravjain540

**Comment by souravjain540** [comment]
@GreenMachine01 this is fixed
