### ISSUE TITLE
Pull request embedded link is broken

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3659]
The link we put inside the PR message is not pointing anymore to the Resource page, it's broken.

https://user-images.githubusercontent.com/61761153/187476917-5855ed38-a2fa-4f2b-a6ed-c6d6b66cff63.mov

**Comment by b4s36t4** [comment]
@tupe12334 can you list the steps to reproduce this issue?

**Comment by tupe12334** [comment]
> @tupe12334 can you list the steps to reproduce this issue?

@b4s36t4  You need to generate a resource on Amplication and connect the resource to your GitHub, after that, press build and open the pull request on the connected Git repository
