### ISSUE TITLE
🐛 Bug Report: Get started button is not working properly

### ISSUE THREAD

**Issue by Himanxu1** [amplication/amplication#3661]
### What happened?

https://user-images.githubusercontent.com/80101755/187576177-3cf097c7-9265-4d06-8fdc-c392a4f3cde1.mp4

### What you expected to happen

Should be working properly

### How to reproduce

Just go to the website and click get started

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@alexbass86 please review this

**Comment by Himanxu1** [comment]
@souravjain540  Hey i think the button is working now ! but i don't know why it is not working at that time .
Should I close this issue?

**Comment by yuval-hazaz** [comment]
yes, let's close this. thanks
