### ISSUE TITLE
🐛 Bug Report: Hover problem on component

### ISSUE THREAD

**Issue by Himanxu1** [amplication/amplication#3663]
### What happened?

https://user-images.githubusercontent.com/80101755/187594865-72f72911-5b93-43cc-aa27-b997dd649ed9.mp4

### What you expected to happen

Should be working properly

### How to reproduce

see above

**Comment by MatanForU** [comment]
duplicated #3617

**Comment by Himanxu1** [comment]
Should I delete this issue ?

**Comment by yuval-hazaz** [comment]
Thanks, I will close as duplicate
