### ISSUE TITLE
🐛 Bug Report: Build status doesn't indicate the correct status when the resource is synced with GitHub

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3679]
### What happened?

 Build status doesn't indicate the correct status when the resource is synced with GitHub.
The build status represents only the status of the code generation step and not the status of the 'push to GitHub' step.
As a result, when a service is synced with GitHub, the user doesn't get an indication if the 'push to GitHub' step fails.

### What you expected to happen

1. I expect the build status to represent the state of the whole steps, meaning that if one/more steps fail, the build status icon should be `X` and not `V`

2. On the commit page, the status of the build of each commit should indicate the result of the whole services' build, meaning that if we have 5 services and only one service's build failed, the icon on the commit should be `X`

![Screen Shot 2022-09-01 at 13 07 40](https://user-images.githubusercontent.com/39680385/187889425-2cda81a3-6d86-4fd4-af89-f0a2e997fc83.png)

### How to reproduce

- create an empty repository on GitHub
- create a resource
- synced with GitHub
- connect to the newly empty repository
- click on commit & build
- go to the commits page
- see the build status icon on the relevant service
- go to its build page and see that the push to the GitHub page failed (`X`) but the status icon of the build is `V`
- go back to commits page and see on the left that the status of the whole commit's builds is also `V`

### Amplication version

0.15.2

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/3876

**Comment by arielweinberger** [comment]
@abrl91 and @morhag90 please test this :)
