### ISSUE TITLE
🐛 Bug Report: right sidebar is going right on delete key press

### ISSUE THREAD

**Issue by jainpawan21** [amplication/amplication#3685]
### What happened?

When a user try to edit code by pressing backspace/delete button, a warning is shown but right side bar is moving right with every key press.

https://user-images.githubusercontent.com/39362422/188128675-371970b5-21d5-480e-8a67-2cdde69578f8.mov

### What you expected to happen

It should not move

### How to reproduce

Go to code view page of any project
click on any file
now try to edit the file using backspace/delete key

### Amplication version

0.15.2

**Comment by arielweinberger** [comment]
@yuval-hazaz Please prioritize

**Comment by yuval-hazaz** [comment]
thanks, obvisouly we need to fix this, but it has a small impact so priority is low. 
if it is a quick win, let's go for it

**Comment by evansnguyen** [comment]
Hi @yuval-hazaz 
Can I work on this issue?

**Comment by yuval-hazaz** [comment]
sure, thanks

**Comment by evansnguyen** [comment]
Hi @jainpawan21,
Can you please confirm if this bug is still present, or has it been resolved?
I can't reproduce the bug
here is my record when trying to reproduce the bug on version 1.1.2: https://www.loom.com/share/a271420bb9e84022964c7335f6055cff

**Comment by yuval-hazaz** [comment]
@evansnguyen I also can't reproduce 
I will close this issue as probably it was fixed since it was initially reported
