### ISSUE TITLE
Image in the docs should be rotated.

### ISSUE THREAD

**Issue by SaadAnsari17** [amplication/amplication#3690]
### Describe the issue with documentation

The middle div image(Nestjs) makes it harder to read the contents inside it
![image](https://user-images.githubusercontent.com/94478736/188155774-aaf81cca-1e03-4878-9e35-0bbb829e4904.png)

### How to solve the problem

The middle div image(Nestjs) should be rotated in order to make it easily readable.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by arielweinberger** [comment]
@alexbass86 What do you think?

**Comment by souravjain540** [comment]
> @alexbass86 @MoFoGo What do you think?

please update.

**Comment by souravjain540** [comment]
> > @alexbass86 @MoFoGo What do you think?
> 
> please give an update.

**Comment by yuval-hazaz** [comment]
the issue was added to the docs backlog. 
@MoFoGo and @alexbass86 will review and will decide how to move forward.

**Comment by MoFoGo** [comment]
@alexbass86  - I agree it would be clearer if the text was horizontal. Low priority.

**Comment by alexbass86** [comment]
For now, I rotated you the original img.

![dark mode](https://user-images.githubusercontent.com/96179897/189890676-708d886d-3925-4dc7-9ae1-30458f38a12e.png)

**Comment by MoFoGo** [comment]
Done
