### ISSUE TITLE
🐛 Bug Report: Pending Changes component is using the wrong value for resourceId

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3704]
### What happened?

The PendingChange component is expecting to receive the resource ID, but instead, the value of Project ID is provided. 

![image](https://user-images.githubusercontent.com/43705455/188299601-65d9c2a1-37a9-4a1f-831c-37a1e758083f.png)

### What you expected to happen

the PendingChange component is also getting the change object which includes the resource ID, so we need to remove this param completely 

### How to reproduce

see packages/amplication-client/src/VersionControl/PendingChanges.tsx

### Amplication version

0.15.3

**Comment by KlausMikhaelson** [comment]
Hello @yuval-hazaz can I work on this ?

**Comment by yuval-hazaz** [comment]
closed in #3705
