### ISSUE TITLE
🐛 Bug Report: Last Commit Animation

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#3711]
### What happened?

![image](https://user-images.githubusercontent.com/6080188/188318852-1d2b7528-437f-47db-8844-c0f109369c07.png)

Animation during build process looks weird.

### What you expected to happen

This gray block should not be there.

### How to reproduce

Go to Commit Page and press Build button.

### Amplication version

0.15.3

**Comment by b4s36t4** [comment]
Made changes can someone please review it.
