### ISSUE TITLE
Feature Request: Display Entity name in Entity view

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3717]
### Feature description

Currently, when browsing an Entity in the Amplication UI, I cannot see which entity I am browsing.
I expect the entity name to be clearly visible in the page, perhaps as a heading or title.

![Screenshot 2022-09-05 at 13 00 29](https://user-images.githubusercontent.com/4976416/188434527-dd731736-ed82-42cc-843c-2fd0be834346.png)

**Comment by alexbass86** [comment]
@arielweinberger Correct me if I'm wrong, but you're saying that when you select an entity type in the dropbox after that, it does not show the icon & the text is grey, so it kind of disappears in the overall UI, correct?

**Comment by alexbass86** [comment]
@EugeneTseitlin 
please use this design
https://www.figma.com/file/smoEIQ7W2EaTBiBqL4qAok/%233717---Display-Entity-name-in-Entity-view?node-id=0%3A1

![Topic Setting](https://user-images.githubusercontent.com/96179897/188641854-704ffe76-7688-472a-adb3-147cb52070fd.png)

**Comment by yuval-hazaz** [comment]
I merged the current PR.

@alexbass86 please complete the design for how it looks in the rest of the tabs - current design only include a small title with the entity name and a bigger one with the name of the tab - but how does it look for example in the main "General Settings" tab ? I don't think the big title should be using the tab nama, instead is should be the entity name

Let me now what you think
