### ISSUE TITLE
🐛 Bug Report: Divider UI problem

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3719]
### What happened?

Some of the dividers in our system are built from a square and not a line, making the line look a lot thicker than it should be.

**Example:**
![11](https://user-images.githubusercontent.com/96179897/188449630-8b4224ba-fe79-4f73-bde2-01b7f69a4170.png)

Please also make sure the color is #2C3249

### What you expected to happen

Divider line should be 1px, color #2C3249

### How to reproduce

Everywhere where we have a divider

### Amplication version

0.15.3

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by manisha6700** [comment]
Yes I am willing to submit a PR!
