### ISSUE TITLE
Docs: Update "Your first application" to "Your First Project

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3725]
### Describe the issue with documentation

The article does not reflect the new structure of Projects> Resources

https://docs.amplication.com/docs/first-app/

### How to solve the problem

Rewrite the description in accordance with the new Project workflow

**Comment by rolwin100** [comment]
I'm willing to take this up. @MoFoGo @yuval-hazaz

**Comment by MoFoGo** [comment]
Done
