### ISSUE TITLE
🐛 Bug Report: Some Text is not Visible on Amplication UI

### ISSUE THREAD

**Issue by shubhwip** [amplication/amplication#3744]
### What happened?

There are some texts which are highly invisible and can't be seen easily. For e.g. in the screenshot below
-  Amplication Logo at the top left corner
- `Pending Changes` text at the right top
-  `Go to View Code` text at bottom right
<img width="1440" alt="Screenshot 2022-09-07 at 10 19 13 PM" src="https://user-images.githubusercontent.com/23444368/188935165-546a020d-ad84-40d7-9390-f129da516185.png">

### What you expected to happen

Text color should be slightly darker to be visible.

### How to reproduce

Go to Amplication UI 
Go to View Code Screen
Look at the text blocks i mentioned in the `What happened Section`.

### Amplication version

0.16.0

### Environment

Node Version : v14.20.0
NPM : 8.15.1
Docker : Docker version 20.10.17, build 100c701
Browser : Chrome
Environment : Local

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@shubhwip thanks for reporting
we removed the light theme recently, but if I understand correctly your setup is still set on "light" which is a bug.

Team, we need to make sure we do not use the Theme settings from the local storage and always use the Dark theme

**Comment by rolwin100** [comment]
@yuval-hazaz I think I can take this up

**Comment by rolwin100** [comment]
Probably we can write a hook to remove the theme setting in local storage if present. on the app load.

**Comment by rolwin100** [comment]
We can have this hook for few months and later remove it.

**Comment by yuval-hazaz** [comment]
Instead of adding a new hook, we can update the code in packages/amplication-client/src/Layout/ThemeProvider.tsx 

use this code with a hard-coded value 

```typeScript
useEffect(() => {
    //const nextThemeClass = `amp-theme-${currentTheme}`;
    const nextThemeClass = `amp-theme-dark`;
    document.body.classList.add(nextThemeClass);
  }, [currentTheme]);
```
