### ISSUE TITLE
⭐️ Validate Topic Name

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3762]
### Feature description

When creating a message broker topic, the user is requested to select a name for the topic. 
This name is used in the code and the actual Kafka topic (or other brokers in the future). 

Currently, we use the <NameField/> component, which enforces a specific regex on the input.

For Topics, there is a need for a different type of validation. 

1. Create a new component, `<TopicNameField />` based on the existing `<NameField />`. This will be used as the actual topic name input when creating a topic.
2. The validation rule should allow the following characters: `0-9 a-z . _ -` (lowercase only).
3. Ensure back-end validation using the same regex.
4. Instead of the current camelCase conversion (`account created` -> `accountCreated`), we need this `<TopicNameField/>` component to be converted to a kafka-friendly topic name. So `account created` would become `account.created`. Ensure lowercase.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/43705455/189472089-e6fe7460-6ae7-4859-81b9-66b1fe4bdf0f.png">

**Comment by arielweinberger** [comment]
@yuval-hazaz @EugeneTseitlin following a quick chat with Eugene, I've updated the issue with specific requirements.
