### ISSUE TITLE
⭐️ Message Broker Creation Wizard 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3763]
### Feature description

We need to update the design of `./packages/amplication-client/src/Resource/create-message-broker/CreateMessageBroker.tsx`

See design from Figma below
Please ask @MoFoGo for updated text

![image](https://user-images.githubusercontent.com/43705455/189472149-0cc37663-ff4b-44f7-b31c-e1b687b27188.png)

**Comment by yuval-hazaz** [comment]
@MoFoGo we need text for this page please

**Comment by MoFoGo** [comment]
@EugeneTseitlin - do you need more from me regarding this task, or can we close it?

**Comment by yuval-hazaz** [comment]
@MoFoGo I added this task to your backlog yesterday since we need text for this page. Did you provide the text already?

**Comment by MoFoGo** [comment]
![image](https://user-images.githubusercontent.com/96979533/190886090-069de1af-508f-423b-bbcb-67d869d62b94.png)

**Comment by MoFoGo** [comment]
This is the text I provided.
