### ISSUE TITLE
🧩 Add a  plugin for postgreSQL

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3768]
### Feature description

Currently, we generate code with PostgreSQL as the database. 
To allow support for using other types of databases like mySQL and MongoDB, we first need to extract the logic that generates the code needed to use Postgres to a plugin. 

Once we have the plugin structure in place, we will be able to create more plugins to support other DBs. 

As a results of this task, the output of the DSG should not change. We expect the exact same code to be generated - just by using a plugin instead of the default behavior of the DSG. 

We can keep the default behavior in place, so when no plugin is being used, PostgreSQL will still be used.

**Comment by abrl91** [comment]
fixed by https://github.com/amplication/plugins/pull/1

**Comment by abrl91** [comment]
fixed by https://github.com/amplication/plugins/pull/1

**Comment by GreenMachine01** [comment]
Approved By:
Amit
