### ISSUE TITLE
🧩 Add a plugin for mySQL

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3769]
### Feature description

Following the completion of #3768 , we want to add a new plugin to support code generation with mySQL instead of PostgreSQL. 

The output of the generated code should include a docker file for mySQL, and a Prisma generator for mySQL. 

Also, due to some limitation of mySQL, the plugin should validate the list of entity fields and throw an error when the user tries to generate code for "Multi Select Option Set"

**Comment by arielweinberger** [comment]
test

**Comment by GreenMachine01** [comment]
Approved By:
Amit
