### ISSUE TITLE
🐛 Bug Report: JSON field on user entity generates incorrect default value in the seed script

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3781]
### What happened?

When using a JSON field on the User entity, the seed script uses the value "false" in the admin record. 
This value causes an error when accessing the record in the API

### The generated code
The extenededProperties field is of type JSON
![image](https://user-images.githubusercontent.com/43705455/189581723-12b0f42c-5b16-4dd4-ae13-89c9efbf5847.png)

### The error
![image](https://user-images.githubusercontent.com/43705455/189581948-b8a8fb9f-4248-4c64-a8c4-552ffa08a295.png)

### What you expected to happen

instead of the value "false" we should an empty json object 

### How to reproduce

create a field of type JSON on the User entity

### Amplication version

0.17.0

**Comment by b4s36t4** [comment]
@yuval-hazaz how can we create empty json using `builder.objectExpression` I found we need to pass some properites to it. Would it be ok if we can include some dummy JSON data as a default value instead of empty object?!

**Comment by b4s36t4** [comment]
Like this.
<img width="403" alt="Screenshot 2022-09-13 at 2 40 27 AM" src="https://user-images.githubusercontent.com/59088937/189759337-aaffab72-e0fe-4e14-9ff1-59a806a28273.png">

**Comment by yuval-hazaz** [comment]
I assume you are working on it, so I assigned you. 
Let me know if that is ok

**Comment by b4s36t4** [comment]
Sure.

**Comment by b4s36t4** [comment]
@yuval-hazaz Created PR for this, please have a look.
