### ISSUE TITLE
🐛 Bug Report: Error "JSONObject cannot represent non-object value" in React-Admin UI

### ISSUE THREAD

**Issue by vincenzodomina** [amplication/amplication#3827]
### What happened?

Similar to Issue #1321 i got an error in the React-Admin UI with a JSON field in my schema saying "JSONObject cannot represent non-object value"

I managed to work around this by changing the files:
- all Occurrences of GraphQLJSONObject to GraphQLJSON (e.g. in base/MyEntity.ts)
- schema.graphql: all Occurrences of JSONObject are changed to JSON automatically by db:init

of course no solution because these are generated files, but then i think the generator should create JSON types instead of JSONObject types to not restrict the use of non-objects?

### What you expected to happen

I expected that an Array of strings would be accepted, as that is valid json. After selecting "json" type in Amplication UI i expected that not only JSON Object are allowed.

### How to reproduce

- Create a schema in Amplication UI with at least one json type field
- Compile project
- Seed some test data with json data with array of strings e.g. ["test1", "test2"]
- Open React-Admin and navigate to schema
- UI Error notification saying: "JSONObject cannot represent non-object value"

### Amplication version

0.16.0

### Environment

OS Details (Mac): macOS Monterey 12.6

**Comment by arielweinberger** [comment]
Please adjust the title to be descriptive.

**Comment by vincenzodomina** [comment]
It looks like this has been solved in the recent updates, the Amplication building process is not creating GraphQLJSONObject anymore but GraphQLJSON for json fields.

Comparing my used 0.16.0 with the current 1.0.2 and searching for"GraphQLJSON" found me these lines:

[...ages/amplication-data-service-generator/src/server/resource/dto/graphql-type-json.util.ts](https://github.com/amplication/amplication/compare/v0.16.0...v1.0.2#diff-325db818b79a01b1dd82fc3cd87369c5c0507192b7d60f884e74e084030dfc0c)
@@ -1,4 +1,4 @@
import { builders } from "ast-types";

export const GRAPHQL_TYPE_JSON_MODULE = "graphql-type-json";
- export const GRAPHQL_JSON_OBJECT_ID = builders.identifier("GraphQLJSONObject");
+ export const GRAPHQL_JSON_ID = builders.identifier("GraphQLJSON");
