### ISSUE TITLE
🐛 Bug Report: Build for Message Broker fails

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3829]
### What happened?

When triggering a commit on a project that includes a message broker an error appears on the build log of the message broker

![image](https://user-images.githubusercontent.com/43705455/190368073-a9dea120-7885-49b4-bdee-de49785e2a98.png)

![image](https://user-images.githubusercontent.com/43705455/190368140-6c7b3a40-1885-439a-a5db-4473f526c376.png)

### What you expected to happen

The DSG should know how to handle a build process for a message broker. in the current stage the DSG identity that the resource is a message broker and do nothing - instead of throwing an error

The DSG can add a log message "No code to generate for a message broker" 

### How to reproduce

create a project witha message broker and click on commit

### Amplication version

0.17.0

**Comment by GreenMachine01** [comment]
Approved By:
Ariel
Amit
Shimi
