### ISSUE TITLE
Plugin: Add eventParams to the After event

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3847]
### Feature description

All after event get two parameters - dsgContext, and modules. 

```typeScript
 after?: (
      dsgContext: DsgContext,
      modules: CreateAdminModulesParams["after"]
    ) => Module[];
```

We should also pass the eventParams to the "after" event since it may include data that will help the plugin developer. 

### Use case

for example, the developer should know which entity is current being used in the "AfterCreateController" event - this data is available in the eventParams in the "before" event - but it should also be available in the "after" event.

**Comment by GreenMachine01** [comment]
Approved By:
Shimi
Yuval
