### ISSUE TITLE
🐛 Bug Report: Service Connection page UI issues

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3852]
### What happened?

the service connections page includes sevreal issues that need to be addressed:

1. the description of the message broker is currently hard-coded - "description about message broker and topic"
2. The green/ yellow dot is misplaced
3. The content of the cards in the list of topics needs to be aliged with Figma

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/43705455/190869122-842b8bfe-bdab-4b83-9f60-9f00031169a8.png">

### What you expected to happen

see above

### How to reproduce

see above

**Comment by GreenMachine01** [comment]
@alexbass86 can you approve we can proceed with this item?

**Comment by alexbass86** [comment]
@GreenMachine01 I think we are good, we still will need to work more on these screens to make sure it's aligned with the original design, but for now, that looks good enough for the release :)

**Comment by GreenMachine01** [comment]
@alexbass86 please approve its proper on prod

**Comment by alexbass86** [comment]
> @alexbass86 please approve its proper on prod

Looks the same in prod, approved :)
