### ISSUE TITLE
Clean up `PostgreSQL` from env variables and docker-compose files

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3856]
### Feature description

As we extract the `PostgreSQL` implementation and logic to separate functions (events) and use a default plugin installation of `db-postgres: https://github.com/amplication/plugins/tree/master/plugins/db-postgres
we can remove the default env variables, and the DB implementation and env variables are the docker-compose files.
Regarding the Prisma schema data-source: 
We decided to leave it AS-IS
```
export const DATA_SOURCE: PrismaDataSource = {
  name: "postgres",
  provider: "PostgreSQL",
  urlEnv: "POSTGRESQL_URL",
};
```

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/3857

**Comment by GreenMachine01** [comment]
Approved By:
Ariel & Amit
