### ISSUE TITLE
🐛 Bug Report: User profile - returning back show empty screen

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3860]
### What happened?

When you click on the profile
![image](https://user-images.githubusercontent.com/96179897/190889986-9a8e03af-9a65-4153-9b44-1e9cf1869ab2.png)

We enter the profile screen, but when I want to return and click on the back button on the browser, it lands us on the blank white screen.

### What you expected to happen

Return to the last visited screen.

### How to reproduce

Click on profile and then try to return back.

### Amplication version

0.17.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
closing this issue since we are rebuilding the profile page in a modal
