### ISSUE TITLE
🐛 Bug Report: Blog is down

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#3862]
![Image](https://user-images.githubusercontent.com/112330500/190892107-6a804a13-6e22-40cc-95eb-594cb0af5f4a.png)

**Comment by arielweinberger** [comment]
Fixed. [Here is the hotfix commit](https://github.com/amplication/amplication-site/commit/aa44a99158ecb3f9d3a6964c22a2d9b462021556).
It was apparently needed to include the API url in both `NEXT_PUBLIC_API_URL` and `NEXT_PRIVATE_BLOG_SERVER_URL` env variable.
