### ISSUE TITLE
🐛 Bug Report: Description is missing in Message Broker Service List page

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#3863]
### What happened?

Description is missing in Message Broker Service List page

![image](https://user-images.githubusercontent.com/6080188/190894821-ef6d2458-adc1-4977-ac0f-8a66efe87948.png)

### What you expected to happen

Proper text that actually explains the meaning of the page.

### How to reproduce

0.17.0

**Comment by MoFoGo** [comment]
My suggestion:

Services associated with this message broker

**Comment by MoFoGo** [comment]
@EugeneTseitlin - is there other information that should be included (for example, if there is a significance to the order)

**Comment by EugeneTseitlin** [comment]
> @EugeneTseitlin - is there other information that should be included (for example, if there is a significance to the order)

No, there is no meaning to the order.
