### ISSUE TITLE
🐛 Bug Report: Amplication HELM - amplication auto scaler is set to minimum 12 in the chart

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#3871]
### What happened?

I deployed a personal environment and there were 12 amplication-server pods running.

the auto scaler minimum is set to 12 and affects all environments. this value should be set only in production, the correct place should be the values prod file and not the chart itself.

### What you expected to happen

I expected that only one amplication server pod will be up

### How to reproduce

deploy amplication to any environment

### Amplication version

0.16.x

**Comment by arielweinberger** [comment]
@shaharblanksela Please fix ASAP
