### ISSUE TITLE
🐛 Bug Report: Create Entity modal keeps appearing after creating an entity

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3873]
### What happened?

The Create Entity modal keeps showing up when entering the Entities page, after creating an entity.

### What you expected to happen

I expect just to be able to see the list of entities, without the modal.

### How to reproduce

- Go to a service
- Create an entity
- Go back to the Entities view
- The modal is still open

https://user-images.githubusercontent.com/4976416/190913120-de28513d-84c7-4c6b-816d-5ed7ec6bb8a9.mp4

### Amplication version

0.17.0

**Comment by arielweinberger** [comment]
Tested on Next and works properly.

**Comment by abrl91** [comment]
fixed by 3873-bug-report-create-entity-modal-keeps-appearing-after-creating-an-entity
