### ISSUE TITLE
🐛 Bug Report: On back to homepage the rotating MKT text is not shown

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#3886]
**Steps to reproduce:**

1. Navigate to one of the tabs on the homepage
2. Return to the homepage

**Expected:**

![Image](https://user-images.githubusercontent.com/112330500/190968783-9e839887-68bc-4d32-8463-c9a472b3806a.png)

**Actual:**

![Image](https://user-images.githubusercontent.com/112330500/190968542-22252cd7-cca5-4695-a550-80874a109a5a.png)

**Comment by AyushK-101** [comment]
I would like to work on this

**Comment by yuval-hazaz** [comment]
@AyushK-101 please let us know once you are done with the other issue that is already assigned to you

**Comment by OmiCoding** [comment]
If this hasn't been assigned to anyone yet, I would like to work on this if you don't mind.

**Comment by yuval-hazaz** [comment]
Thanks for your support.
I assigned you

**Comment by OmiCoding** [comment]
No problem, and thank you! I should have a solution soon!

**Comment by OmiCoding** [comment]
Let me know if everything looks good!

**Comment by GreenMachine01** [comment]
@OmiCoding Thanks!
We will update you soon.
