### ISSUE TITLE
DSG: Add more events

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#3887]
- [x] research/mapping - outcome is list of events that need to be added
- [ ] Create an issue/subtask for each event 
events:
- [x] #4138
- [x] #4136
- [ ] createControllerSpecModule
- [ ] createSwagger
- [ ] createSeedModule
- [ ] createMessageBrokerInternal
- [ ] createGrantsModule
- [ ] createManifestModule
- [ ] createIndexHTMLModule
- [ ] createDTOModules
- [ ] createEnumRolesModule
- [ ] createRolesModule
- [ ] createEntityComponentModule
- [ ] createAppModule (admin-ui)
- [ ] createAdminDotEnv (admin-ui)
- [ ] createServerAppModule (not include in DSG - only code-gen-types)

* All names should be change if the function is not returning nest.js module.

**Comment by yuval-hazaz** [comment]
Create Resolver
Create Entity Module

**Comment by barshimi** [comment]
Those two events had been added. if there are no new events to this task, please close it

**Comment by barshimi** [comment]
I updated all the events at DSG that is not accessible to plugin

**Comment by abrl91** [comment]
@GreenMachine01 
We already have `CreateDotEnvModule` - it actually called `CreateServerDotEnv`.
What we do need to add is `CreateAdminDotEnv`

Another important note
Have a look at this issue: https://github.com/amplication/amplication/issues/4158
We don't want to use the suffix `Module` at the end of the event name where it's NOT a NestJS module.
For example `createAppModule` is NestJS module, therefore the event name makes sense and is not confusing.
`createGrantsModule` - I know that the grants file is `JSON` so I'm pretty sure that the right name for this event is `CreateGrants`

**Comment by abrl91** [comment]
Actually, we also have `CreateServerAppModule` which I think is equivalent to `createAppModule`

**Comment by yuval-hazaz** [comment]
we can start with a few of the main events and then add more events as needed when working on plugins. 

for example, these 3 look as a good place to start but this is just a suggestion, @arielweinberger will know better 

createControllerSpec
 createSwagger
 createSeed

**Comment by GreenMachine01** [comment]
@yuval-hazaz @arielweinberger 
I opened issues for:
#4291 
#4293 
#4293 

I am marking this item as done.

@arielweinberger let me know if additional events from the list should be added to DSG
