### ISSUE TITLE
🐛 Bug Report:  Topics page -  a change of a topic is not reflected in the list nor is it saved after a refresh

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3889]
### What happened?

  Topics page -  a change of a topic is not reflected in the list nor is it saved after a refresh

https://user-images.githubusercontent.com/39680385/190980544-ba4f0a50-52dc-4985-b1df-e1283c5597f7.mov

### What you expected to happen

I expect that the new name will be updated in the topic list (on the left) and that the renaming will not be discarded after a refresh

### How to reproduce

- create a boker
- go to its page
- click on the topic icon on the left
- create a topic
- rename
- refresh

### Amplication version

0.17.0

**Comment by tupe12334** [comment]
My speculation is that the data not updating because of #3890 , this bug blocks it from sending a network update, so the data is not updated

**Comment by tupe12334** [comment]
Has closed by #3904
