### ISSUE TITLE
🐛 Bug Report: Topics Page - error message appears with no reason 

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3890]
### What happened?

Topics Page - error message appears with no reason: 
1. although I named my topic as it should, I got an error message.
2. I think this error message needs some proofreading by @MoFoGo 
3. @alexbass86  the style is not aligned with our styles for error messages.

![Screen Shot 2022-09-19 at 11 34 01](https://user-images.githubusercontent.com/39680385/190981651-8f200d46-e744-402a-b143-6da89fb16b2e.png)

### What you expected to happen

I don't expect to see the error message because I used the structure it asks for

### How to reproduce

- create a boker
- go to its page
- click on the topic icon on the left
- create a topic
- try to rename it
- see the error

### Amplication version

0.17.0

**Comment by GreenMachine01** [comment]
@abrl91 does the feature keep working or once you get the error you are blocked from proceeding?

**Comment by tupe12334** [comment]
Will close by #3904
