### ISSUE TITLE
🐛 Bug Report: Miss place scroll bar in the commit page

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3891]
The horizontal scroll bar in the commit page is on the entire page contact, but we need it to show only on the logs section
<img width="1342" alt="Screen Shot 2022-09-19 at 11 51 58" src="https://user-images.githubusercontent.com/61761153/190982177-a765f8a3-860d-46bf-b88b-6cd124ab6396.png">

The page contact needs to be responsive to fit the screen

**Comment by b4s36t4** [comment]
@tupe12334 can I work on this?!

**Comment by tupe12334** [comment]
@GreenMachine01 Can you please assign @b4s36t4 ?

**Comment by yuval-hazaz** [comment]
This issue is open for contribution

**Comment by KushalRaut** [comment]
Hi @yuval-hazaz 
Can I work on this issue if it is not being currently worked on?

**Comment by yuval-hazaz** [comment]
@arielweinberger is this issue still open? can we assign @KushalRaut ?

**Comment by tupe12334** [comment]
@yuval-hazaz Yes, this bug is still relevant

**Comment by yuval-hazaz** [comment]
thanks @tupe12334 
@KushalRaut  in case you are still interested let me know and I will assign this issue to you

**Comment by evansnguyen** [comment]
Hi @yuval-hazaz 
Can I work on this issue?

**Comment by tupe12334** [comment]
Hi @evansnguyen I assigned you, good luck
