### ISSUE TITLE
🐛 Bug Report: Message Broker page - the first topic is not selected

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3893]
### What happened?

![image](https://user-images.githubusercontent.com/39680385/190986188-2f2b71f3-e318-4e77-88dc-25508e9db3b2.png)

### What you expected to happen

I expect that if I have a broker in the project and I go  a service page, the first one will be selected

### How to reproduce

- create a service
- create a broker
- go to broker page and add topics
- go to the service page and click on the broker icon on the left
- see that the first broker is not selected

### Amplication version

0.17.0

**Comment by GreenMachine01** [comment]
Tested and approved by Erez
