### ISSUE TITLE
🐛 Bug Report: Topics Page -  missing the empty state

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3894]
### What happened?

Topics Page - missing the empty state

![image](https://user-images.githubusercontent.com/39680385/190987781-704d7e42-a629-48e6-b4de-10e5d213d871.png)

### What you expected to happen

I expect to see the empty state image + text

### How to reproduce

Create a broker, go to its page and click on the topics icon on the left

### Amplication version

0.17.0

**Comment by GreenMachine01** [comment]
@alexbass86 can I see the empty state example?

**Comment by AyushK-101** [comment]
I would like to work on this

**Comment by AyushK-101** [comment]
I would like to work on this

**Comment by yuval-hazaz** [comment]
g0od luck @AyushK-101

**Comment by carefreeav09** [comment]
Can you assign this to me?

**Comment by AyushK-101** [comment]
Can't find the time to do it, unassign-ing myself

**Comment by abrl91** [comment]
@carefreeav09 I assigned you. Good luck!

**Comment by abrl91** [comment]
@carefreeav09 Sorry, I have to close this issue, we decided to auto-generate a topic when a message broker is created. Therefore, this issue is irrelevant. 
I can assign you to this issue: https://github.com/amplication/amplication/issues/3896

**Comment by abrl91** [comment]
@carefreeav09 just comment in the issue https://github.com/amplication/amplication/issues/3896
