### ISSUE TITLE
🐛 Bug Report: Not align with style button in new project modal

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3895]
The button in the create new project modal is not aligning with the design spec by @alexbass86 

# The wanted design
![New Project](https://user-images.githubusercontent.com/61761153/190988156-8d7a5f80-d0f7-433b-aeca-26eab79a6a1c.png)

# The existing design
https://user-images.githubusercontent.com/61761153/190987201-c32826c8-e59b-4f64-857f-720b09f7bb88.mov

**Comment by KlausMikhaelson** [comment]
Hey @tupe12334 can I work on this issue ?

**Comment by tupe12334** [comment]
@GreenMachine01 Can you assign @KlausMikhaelson

**Comment by GreenMachine01** [comment]
@KlausMikhaelson Hey, Do you still want to work on this item?

**Comment by KlausMikhaelson** [comment]
Hey @GreenMachine01 just give me today will create a pr before the eod

**Comment by souravjain540** [comment]
Waiting for PR, Satyam :)

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4267

**Comment by GreenMachine01** [comment]
Confirmed fix.


![Image](https://user-images.githubusercontent.com/112330500/201518711-f43d78c1-23ce-4af2-a9e6-d32ba0b68dee.png)
