### ISSUE TITLE
🐛 Bug Report: "Bouncy" resources while navigating between projects

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3897]
### What happened?

 "Bouncy" resources while navigating between projects.
It happens on the first time only or after a refresh.

https://user-images.githubusercontent.com/39680385/190991550-25ff4d98-053c-43ac-b0fc-851871eb31c1.mov

### What you expected to happen

I expect smooth navigation or a loader.

### How to reproduce

Make sure you have more than one project with resources and navigate between them.

### Amplication version

0.17.0

**Comment by GreenMachine01** [comment]
@alexbass86 please describe what is expected.

**Comment by alexbass86** [comment]
@GreenMachine01 Please use the simple loader animation while we navigate between the projects. 
https://app.lottiefiles.com/share/159cb0bb-5b16-4aa7-a3e5-aa35df2e8007

**Comment by abrl91** [comment]
> #3921

yes

**Comment by abrl91** [comment]
fixed by #3921
