### ISSUE TITLE
🐛 Bug Report: Auth plugin generates files at the root level rather than inside `server`

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3898]
### What happened?

I have used the Auth plugin and noticed that the code is generated in the repo's root folder.
This happens with both JWT and Basic auth plugins.

<img width="628" alt="Screenshot 2022-09-19 at 12 07 23" src="https://user-images.githubusercontent.com/4976416/190996187-3c1e5ba6-7fff-4707-adf5-d083ed6fdb8c.png">

### What you expected to happen

I expect the auth module to generate auth related files in the appropriate folder.

### How to reproduce

- Create a Server resource
- Install the Auth plugin
- Build

### Amplication version

1.0.0

**Comment by GreenMachine01** [comment]
@abrl91 @barshimi please review and decide who can take this one.

**Comment by GreenMachine01** [comment]
Please check also other Auth Plugins

**Comment by abrl91** [comment]
I am on it

**Comment by arielweinberger** [comment]
Tested both JWT and Basic auth plugins, fixed!

**Comment by arielweinberger** [comment]
Tested both JWT and Basic auth plugins, fixed!
