### ISSUE TITLE
🐛 Bug Report: When a plugin is installed and the operation fails there is no indication in the client

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3911]
### What happened?

 When a plugin is installed and the operation fails there is no indication in the client

### What you expected to happen

I expect to see an error mesage 

### Amplication version

0.17.0

**Comment by barshimi** [comment]
@yuval-hazaz do we have a design/product reference to this bug ?

**Comment by yuval-hazaz** [comment]
assiging to @GreenMachine01

**Comment by GreenMachine01** [comment]
@yuval-hazaz @barshimi 
Design and text instructions were added to the issue.

**Comment by GreenMachine01** [comment]
We will close this issue as currently there is a notification from the server in case of an error.
Will open a new issue to improve overall UI of errors.
