### ISSUE TITLE
🐛 Bug Report: Generated app with PostgreSQL database errors on NPM start

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3912]
When generating a new app on version 1, and following the Local Development instructions in the generated `README.md`, I am getting the following error:

![Image](https://user-images.githubusercontent.com/4976416/191063024-44f1a727-d3b6-4cb1-88c8-525ce0a76c33.png)

I checked with an app generated in v0.16.0 and this does not happen, which makes me feel pretty confident about the facrt that this was introduced very recently. @abrl91 will also test to validate.

**Comment by abrl91** [comment]
cannot reproduce
```
cd server
npm i
npm run docker:db
npm run prisma generate
npm run db:init
npm run start
```
![image](https://user-images.githubusercontent.com/39680385/191065891-fae6b500-2bc7-4b00-bfdc-076511a89f6a.png)

**Comment by arielweinberger** [comment]
Let's close this. If this comes up again, we'll tackle it.
