### ISSUE TITLE
🐛 Bug Report: 'Commit update' status is not updated

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#3927]
When click commit the spinner start rolling but when the call finish the spinner is not replaced with check icon

**Comment by b4s36t4** [comment]
@GreenMachine01 https://github.com/amplication/amplication/pull/3921 PR for that, can you check that solves the same or not?

**Comment by abrl91** [comment]
> @GreenMachine01 #3919 PR for that, can you check that solves the same or not?

Thank you @b4s36t4 I will check

**Comment by abrl91** [comment]
duplicated #3908
