### ISSUE TITLE
🐛 Bug Report: Dropdown - Inconsistant look and behavior, not alligned with the design

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3929]
### What happened?

We need to ensure the dropdown looks and behaves the same everywhere in our system. 
Let's make sure we align them with the design.

Screen 1 - Project Configuration (sync with GitHub)
![image](https://user-images.githubusercontent.com/96179897/191229587-7f3017dd-f6f1-4185-a37d-d52f5dd3563e.png)

Screen 2 - Service (sync with GitHub)
![image](https://user-images.githubusercontent.com/96179897/191230058-74e077a3-f1bf-498a-a186-d48b7599b883.png)

Screen 3 - Message broker (Connection at service)
![image](https://user-images.githubusercontent.com/96179897/191230255-a665ba91-8e1d-43d1-9e7d-e598665e78ba.png)

Screen 4 - Entities (Field settings)
![image](https://user-images.githubusercontent.com/96179897/191230553-1248dd14-8a8d-4487-a486-4642e0f270ae.png)

Design can be found here (Field Dropdown):
https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=1084%3A12156

### What you expected to happen

All these drop-downs should look and behave the same except for the addition of the icon before the text if needed, but the dropdown menu, effect, and style should be the same.

### How to reproduce

Go into the screen mentioned to see the problem.

### Amplication version

1.0.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Keshraf** [comment]
Hello @alexbass86 , is this issue resolved?

**Comment by souravjain540** [comment]
@arielweinberger @alexbass86 can @Keshraf work on this?

**Comment by Keshraf** [comment]
> @arielweinberger @alexbass86 can @Keshraf work on this?

Can I?

**Comment by yuval-hazaz** [comment]
@Keshraf yes please go ahead

**Comment by cshel16** [comment]
HI, can I help with this?

**Comment by yuval-hazaz** [comment]
@cshel16 I assigned it to you. good luck

**Comment by EugeneTseitlin** [comment]
One of the components should be taken as a base and used in every place. It's style should be adjusted to design.

**Comment by olalekanteeblaze** [comment]
@yuval-hazaz @Keshraf @alexbass86 I'll like to work on this. the figma link is not public. I've requested access to it

**Comment by lokeswaran-aj** [comment]
Hi, @alexbass86 I have setup the app locally, and when I click the `Connect to GitHub` button it opens a popup with the address `localhost:3001/[GITHUB_APP_INSTALLATION_URL]` In the readme, it says to replace with the URL of your GitHub app. Do I have to create any app on GitHub? can you provide some docs links?

**Comment by lokeswaran-aj** [comment]
@alexbass86 Can I work this issue? I can fix this.

Please give me access to the figma design.

**Comment by alexbass86** [comment]
@GreenMachine01 please review before i post the public link

**Comment by GreenMachine01** [comment]
@EugeneTseitlin can this item be worked on by the community?

**Comment by EugeneTseitlin** [comment]
@GreenMachine01 I think it's better to leave it for the team

**Comment by GreenMachine01** [comment]
@lokeswaran-aj We will need to fix this item internally. Thanks for the offer. I hope you can find other items to contribute to :)
@alexbass86 - FYI

**Comment by GreenMachine01** [comment]
This item will be fixed by a bigger initiative of the design system.

**Comment by lokeswaran-aj** [comment]
@GreenMachine01  yeah sure, but I was able to fix this issue just by passing width attributes to the SelectMenu components. But its fine, it seems to be something else.
