### ISSUE TITLE
🐛 Bug Report: Missing scrollbar in long list

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3930]
### What happened?

We need an option to scroll when the list gets longer than our screen view in these sections.

Entities
![image](https://user-images.githubusercontent.com/96179897/191233154-6b5aa6c9-75ea-4288-9674-35b66a1d9045.png)

Inside an entity
![image](https://user-images.githubusercontent.com/96179897/191233312-b166a3e1-f2b8-4054-a22e-b445a844c680.png)

Roles
![image](https://user-images.githubusercontent.com/96179897/191233426-44dac591-f664-498f-bf8e-4cbebec21427.png)

Service (Connection - message broker)
![image](https://user-images.githubusercontent.com/96179897/191233696-1d455aba-ab20-481f-bd9a-4c16bf0ee024.png)

Commit list
![image](https://user-images.githubusercontent.com/96179897/191233799-a6319bb0-ce57-4597-b9f4-9d1ef6067328.png)

Topic
![image](https://user-images.githubusercontent.com/96179897/191234034-24a77ea4-f002-4fc8-b0b0-be7fe3176dcb.png)

View Code:

![Image](https://user-images.githubusercontent.com/112330500/193443540-858c1517-55f6-4cae-b811-2c433f654eb3.png)

And probably everywhere in the system where we have addable objects.

### What you expected to happen

We need to have the option to scroll a list when it becomes too long.

### How to reproduce

Just add multiple objects to all the screens I mentioned.

### Amplication version

1.0.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GreenMachine01** [comment]
@alexbass86 please add reference to proper design examples

**Comment by GreenMachine01** [comment]
Duplicates partially - https://github.com/amplication/amplication/issues/3869
More information can be found in the #3869 ticket

**Comment by alexbass86** [comment]
> @alexbass86 please add reference to proper design examples

Please use the same scroll bar we have on the main project screen (project list)
![image](https://user-images.githubusercontent.com/96179897/191251558-05ff76e7-a0df-4843-9033-b367dbb2b110.png)

**Comment by abrl91** [comment]
and also on the code view page


https://user-images.githubusercontent.com/39680385/191847410-4c79bbf5-21e2-482f-8780-b2e54309c56b.mov

**Comment by GreenMachine01** [comment]
Rejected..no scroll within an entity and UI shows outside the frame


![Image](https://user-images.githubusercontent.com/112330500/193442807-04432616-1bf9-41cf-b851-a0bf18e1ca27.png)

**Comment by arielweinberger** [comment]
Can confirm the original issue was fixed. 


![Image](https://user-images.githubusercontent.com/4976416/193446375-bf1d387b-c984-4344-892d-da16388225ef.png)


Ideally the scrollbar will only be implemented to the code explorer, not the selector sections. But I think this is good to go live with.
