### ISSUE TITLE
🐛 Bug Report: Message broker - UI Issues

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3932]
### What happened?

In message broker, we have an empty state currently It's aligned to the top, and Please make it in the center of the container.
Also, we need to ensure our title and subtext are consistent and look precisely like it's in the design and other places in the system.

![image](https://user-images.githubusercontent.com/96179897/191235155-8efe860c-e126-419a-8638-a8ae0704284a.png)

### What you expected to happen

Empty state img should be in the center, and we need to have proper space between the title and subtext.
Please make sure to align it with the latest design found here.
https://www.figma.com/file/GLTbBuQoYvwas6XsCMHnqd/%23none---Resources?node-id=1877%3A11798

### How to reproduce

Go to the message broker.

### Amplication version

1.0.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Azanul** [comment]
I'd like to work on this

**Comment by yuval-hazaz** [comment]
thanks @Azanul 
I assigned the issue to you

**Comment by yuval-hazaz** [comment]
The header is already fixed, so just the empty state position

**Comment by Azanul** [comment]
@alexbass86 can I use sass arguement to alter empty state height?

**Comment by Azanul** [comment]
@yuval-hazaz @alexbass86 I can't see the design in figma. Could you please post an image here.

**Comment by Azanul** [comment]
@alexbass86  This is resolved

**Comment by GreenMachine01** [comment]
@alexbass86 can I close this item?

**Comment by barshimi** [comment]
this bug is already fixed

![Image](https://user-images.githubusercontent.com/4712526/206910166-1e02b68d-33c9-4c19-8838-85fc8107c268.png)

**Comment by alexbass86** [comment]
Awosome

**Comment by Azanul** [comment]
@alexbass86 You reopened it again 😆
