### ISSUE TITLE
🐛 Bug Report: Side menu - bad padding between options

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3933]
### What happened?

Please make sure we have proper padding in the side menu. It needs to be 8px between each selection button.

![image](https://user-images.githubusercontent.com/96179897/191253100-4a32850f-a968-4f74-a36d-149bdb29a949.png)

This is also happening on these screens; please ensure it is fixed everywhere.

- [ ] Project Configuration - General Settings
- [ ] My message broker - General Settings
- [ ] Entities - Fields

### What you expected to happen

8px padding between each element in the side menu.

### How to reproduce

Visit the pages mentioned above.

### Amplication version

1.0.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by morhag90** [comment]
@alexbass86 it seems its already fixed:


![Image](https://user-images.githubusercontent.com/97830649/191764664-734cdd05-e1d8-48f1-8120-40597e980b59.png)


please confirm 
Thanks.

**Comment by alexbass86** [comment]
> @alexbass86 it seems its already fixed:
> 
> ![Image](https://user-images.githubusercontent.com/97830649/191764664-734cdd05-e1d8-48f1-8120-40597e980b59.png)
> 
> please confirm Thanks.

Don't see these changes..

**Comment by morhag90** [comment]
@alexbass86 doesn't work on prod yet, but I see it is working on master branch. 
Do you have a personal working environment?

**Comment by morhag90** [comment]
@alexbass86, please recheck it in the staging environment; looks good there.

**Comment by alexbass86** [comment]
> @alexbass86, please recheck it in the staging environment; looks good there.
@morhag90 in entities it's still not fixed

![image](https://user-images.githubusercontent.com/96179897/192784807-bab2d353-a21c-4a2a-8d29-06a999a4b01a.png)

**Comment by GreenMachine01** [comment]
@arielweinberger @morhag90 
on Stage...


![Image](https://user-images.githubusercontent.com/112330500/193046252-3d544537-4039-4567-b532-8e225a1fcd60.png)

Moving it back to "To Do"

**Comment by Santhusha-bit** [comment]
Can you assign this to me?

**Comment by yuval-hazaz** [comment]
@Santhusha-bit the issue is now assigned to you
good luck

**Comment by codersrepo** [comment]
I would like to work on this . Can you assign this to me?

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4206
