### ISSUE TITLE
🐛 Bug Report: Service, Entities card - wrong on hover effect

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3935]
### What happened?

When you hover this card, we have the wrong effect, and please make sure the colors are exactly like it's in the design.
Design - https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=1082%3A12193

background: #373D57;
border: 1px solid #444B66;
border-radius: 8px;

Also, please make sure the divider color changes.
![entity_card](https://user-images.githubusercontent.com/96179897/191258194-dbf69dbc-19ce-4970-af55-e960a237ec38.png)

### What you expected to happen

On hover should be aligned with the design.

### How to reproduce

Hover on top of Service, entities card to see the effect.

### Amplication version

1.0.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by davidtaing** [comment]
Hi Alex,
Can I please work on this issue?

Thanks!

**Comment by yuval-hazaz** [comment]
> Hi Alex, Can I please work on this issue?
> 
> Thanks!

yes, go ahead
