### ISSUE TITLE
🐛 Bug Report: Add resource - UI Issues

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3936]
### What happened?

Currently, the add resource button & dropdown with the elements inside look different from the design. Let's align it.
Design - https://www.figma.com/file/9vQeA4a87RBsyCViJTh13W/Design-System?node-id=2024%3A18957

How it spoused to look
![Project - Main Screen](https://user-images.githubusercontent.com/96179897/191259397-e771739e-f46b-4d84-8164-ea08db4ca148.png)

### What you expected to happen

The UI needs to be aligned with the design.

### How to reproduce

Click on the add resource button on the main project screen.

### Amplication version

1.0.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ykhokhaneshiya** [comment]
@alexbass86 , Can I work on this task?

**Comment by yuval-hazaz** [comment]
@meetwithyash thanks, but this issue can be closed since the UI was fixed already.
