### ISSUE TITLE
🐛 Bug Report: Commit - Last commit section text break

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3937]
### What happened?

By clicking on the "Rebuild" button, the text on the last commit section breaks into two rows without any reason. 
Let's make sure if it breaks, the message is below the Commit ID.

![image](https://user-images.githubusercontent.com/96179897/191296715-e0f58780-c099-437d-8a4e-e4c4b79f6500.png)

### What you expected to happen

The commit message needs to be below the commit id.

### How to reproduce

Click rebuild on the commit side component.

### Amplication version

1.0.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ykhokhaneshiya** [comment]
@alexbass86 , Can I work on this issue?

**Comment by abrl91** [comment]
> @alexbass86 , Can I work on this issue?

@meetwithyash Do you still want to work on this issue?

**Comment by michizhou** [comment]
@abrl91 If @meetwithyash isn't working on this issue, can I work on it?

**Comment by meetwithyash** [comment]
I am not working on this, it is open.

**Comment by abrl91** [comment]
> @abrl91 If @meetwithyash isn't working on this issue, can I work on it?

I assigned you. Gook luck!

**Comment by chaiwattsw** [comment]
Any update ? if not I would like to take
