### ISSUE TITLE
🐛 Bug Report: @ts-ignore comments in the Auth plugins

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#3939]
### What happened?

We have @ts-ignore statements generated as a part of the code generated by the Auth plugins. This is against best practices and we got a few complaints from community members about this following v1.

### What you expected to happen

Remove the `@ts-ignore` statements from all generated code, and fix the root cause if needed.

### How to reproduce

Produce code with the Auth plugins and inspect.

**Comment by arielweinberger** [comment]
I still see `@ts-ignore` comments in the generated code.


![Image](https://user-images.githubusercontent.com/4976416/201533676-6adbb6ec-1166-409f-b240-7b22821be662.png)

**Comment by abrl91** [comment]
> I still see `@ts-ignore` comments in the generated code.
> 
> ![Image](https://user-images.githubusercontent.com/4976416/201533676-6adbb6ec-1166-409f-b240-7b22821be662.png)

These are not related to the auth plugins @arielweinberger
