### ISSUE TITLE
Docs: remove download button from docs

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3944]
### Describe the issue with documentation

The user must now sync with GitHub to get the code. There is no longer a download button. 

### How to solve the problem

Review all the docs and update.

**Comment by GreenMachine01** [comment]
@MoFoGo The fix here is to change just the flow. Developer can still download his code via GitHub instead of via Amplication

**Comment by the-kaushal-agrawal** [comment]
pls assign this issue to me

**Comment by souravjain540** [comment]
@the-kaushal-agrawal assigned

**Comment by KushalRaut** [comment]
Hi @yuval-hazaz 
Can I work on this issue if it is not being currently worked on?

**Comment by yuval-hazaz** [comment]
@MoFoGo @souravjain540 please reply to @KushalRaut

**Comment by souravjain540** [comment]
> Hi @yuval-hazaz 
> 
> Can I work on this issue if it is not being currently worked on?

Sure.  @KushalRaut  assigned

**Comment by MoFoGo** [comment]
@KushalRaut - are you still intending to work on this issue?

**Comment by arielweinberger** [comment]
@MoFoGo The download functionality has been removed from everywhere, so I suggest that we pick this up internally and ensure documentation is up to date. This is now up in production.

**Comment by yuval-hazaz** [comment]
agree
@arielweinberger @MoFoGo is over booked with the plugin docs. Do you have someone to invest a couple of hours in updating the docs and send a PR to @MoFoGo ?

**Comment by GreenMachine01** [comment]
@arielweinberger @yuval-hazaz @MoFoGo I will assign this item to @EugeneTseitlin and we will take it as part of the sprint
