### ISSUE TITLE
🐛 Bug Report: When a plugin event fails, there is no indication of a failure

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3954]
### What happened?

When a plugin event fails, there is no indication of a failure.

For example, when a user installs the MySQL plugin, and on one of the entities, he has a field with the `MultiSelectOptionSet` type. Prisma's MyQL provider doesn't support an array of primitives. Therefore the plugin event fails, **but** there is no indication of a failure on the build page, as the plugin wrapper function doesn't handle these kind of errors

![Screen Shot 2022-09-24 at 21 19 42](https://user-images.githubusercontent.com/39680385/192137736-15a0333d-6620-4624-b3db-2eead05df2bc.png)

### What you expected to happen

I expect the build to fail

### How to reproduce

 - create a project with a service
 - install the MySQL plugin on this service
 - create a field type `MultiSelectOptionSet` on of the entities
 - Click on build

### Amplication version

next

**Comment by yuval-hazaz** [comment]
We should keep handling excpetions from the plugins, and not break the process. But, we should add the following:
1. Show the messages from exceptions as errors in the log
2. Allow the plugin developer to ask to stop the generation process when needed. Add a new function on the DsgContext
```
context.abortGeneration(reason: string)
```
when used, the DSG will show the reason as a message on the log (as an error) and will abort the entire process and quit

**Comment by barshimi** [comment]
in order to get the specific error the plugin developer should add error messages. the plugin wrapper can't understand what failed the process.

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4405
