### ISSUE TITLE
🐛 Bug Report: Popup cannot be closed - UI Issues

### ISSUE THREAD

**Issue by omer3020** [amplication/amplication#3956]
### What happened?

Whenever you try to create a project whose name already exists, the small tooltip message never disappears

![image](https://user-images.githubusercontent.com/45441211/192144310-6fd9492b-2744-43b8-b518-65b25f23498c.png)

### What you expected to happen

After a few seconds, the tooltip should disappear.

### How to reproduce

1.Add a new project to workspace
2.Add a new project with the same name to the workspace

**Comment by souravjain540** [comment]
@alexbass86  please confirm this issue.

**Comment by souravjain540** [comment]
Thank you so much for reporting the issue @omer3020!

**Comment by arielweinberger** [comment]
I've marked this issue as a `good first issue`. Community members wishing to contribute, you're most welcome!

**Comment by Martande8055** [comment]
hello, can you assign this issue to me

**Comment by souravjain540** [comment]
Assigned @Martande8055 

Let us know if you need any help :)

**Comment by Martande8055** [comment]
if I am in need, I will definitely ask for your help, thank you. thank you for offering help. I will let you know :)

**Comment by mohitshende** [comment]
Hello , I would like to work on this. Could you please assign this issue to me?

**Comment by mohitshende** [comment]
Hello , I would like to work on this. Could you please assign this issue to me?

**Comment by mohitshende** [comment]
@souravjain540 I tried to fix this according to @arielweinberger comment on PR #3989 . But as I tried to set the error message from API response to the formik errors. The error message is not rendered first time when I try to submit, but it renders when I click the submit button second time. I made the following changes to the code.
<img width="718" alt="Screenshot 2022-10-31 at 11 21 59 AM" src="https://user-images.githubusercontent.com/54403334/198941102-d6297df3-8ac8-487c-9a3e-f5c588cce623.png">

**Comment by yuval-hazaz** [comment]
@arielweinberger @souravjain540 can you help @mohitshende ?

**Comment by GreenMachine01** [comment]
@souravjain540 @yuval-hazaz @arielweinberger @mohitshende 
I went over this bug and I don't think we are approaching it correctly from the solution standpoint.
I followed the steps to reproduce and was able to close the pop-up via the X.
As a general UX rule, we shouldn't close pop-ups automatically to users after they haven't reacted for X seconds.

I think the issue with this bug is that the error message is not clear enough in the UI.
Closing this bug.

**Comment by GreenMachine01** [comment]
@yuval-hazaz @mohitshende @souravjain540
I want to take this bug with our UX/UI designer and then we will have a proper definition of the way to communicate the error message and allow the user to continue

**Comment by EugeneTseitlin** [comment]
Thanks for the contribution!

**Comment by abrl91** [comment]
@EugeneTseitlin  it still doesn't work


https://user-images.githubusercontent.com/39680385/216175132-3f617e64-708f-40a5-a76b-dc0034646034.mov

**Comment by abrl91** [comment]
There was a problem with the deployment. The issue was resolved
