### ISSUE TITLE
🐛 Bug Report: Generated app - admin-ui `npm install` failed

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3958]
### What happened?

Generated app - admin-ui `npm install` failed.

![image](https://user-images.githubusercontent.com/39680385/192148032-99a3c298-21a8-482a-bf66-886ba50806d4.png)

### What you expected to happen

I expect `npm install` to finish successfully.

### How to reproduce

-  create a project with a resource and download the code/clone from GitHub
- open with your IDE
- `cd admin-ui && npm i`

### Amplication version

1.0.0

**Comment by GreenMachine01** [comment]
doesnt reproduce
