### ISSUE TITLE
🐛 DSG: Plugin Event `CreatePackageJson` should be renamed to `CreateServerPackageJson`

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3959]
### What happened?

The name of the event that runs on the server creation is called CreatePackageJson, instead, it should be named 'CreateServerPackageJson'

Soon we will need to add a similar event for the Admin-UI, and it should be called `CreateAdminPackageJson`

### What you expected to happen

the name of the event should be CreateServerPackageJson

### How to reproduce

go to packages/amplication-code-gen-types/src/plugins-types.ts

### Amplication version

1.0.0

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4135
