### ISSUE TITLE
DSG: Add event 'PrepareContext'

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3960]
### Feature description

The file create-data-service-impl.ts includes many preparation steps, and the current code is too cluttered.
To resolve that, we should refactor the files to extract all the preparation steps to a separate file.

**Comment by barshimi** [comment]
it is a great idea... I suggest we change the methodology by adding a queue of functions and configuration runner. It will clear all clutter' give us the ability to run DSG in a dynamic way and in variety of settings
