### ISSUE TITLE
🐛 Bug Report: Static Images for Admin UI Missing

### ISSUE THREAD

**Issue by shubhwip** [amplication/amplication#3963]
### What happened?

If you start and open generated application's admin ui server then you will see images missing.
`http://localhost:3001/#/login`

<img width="1440" alt="Screenshot 2022-09-26 at 10 22 34 PM" src="https://user-images.githubusercontent.com/23444368/192335878-271a277c-e76a-405d-b021-c9aa0f6ea959.png">

### What you expected to happen

There should be correct images.
I looked at the current URL of the images and they are wrong as there is nothing on those links

https://amplication.com/assets/graphql.png
https://amplication.com/assets/react-admin.png

### How to reproduce

Generate a new app.
Start the server and admin ui
Access http://localhost:3001/#/login

### Amplication version

0.1.0

### Environment

Node Version : v14.20.0
NPM : 8.15.1
Docker : Docker version 20.10.17, build 100c701
Browser : Chrome
Environment : Local
OS : MacOS M1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@tupe12334 can you confirm?

**Comment by tupe12334** [comment]
Hi @souravjain540 , @shubhwip is absolutely right.

**Comment by souravjain540** [comment]
@shubhwip would you like to work on this issue?

**Comment by souravjain540** [comment]
@yuval-hazaz can you help here

**Comment by yuval-hazaz** [comment]
@shubhwip you can find the original images in this repo
https://github.com/amplication/site/tree/master/assets

please download the relevant images and include them in the generated code as static files

**Comment by yuval-hazaz** [comment]
this issue was fixed by adding the missing files in the original URLs
we need to fix #4040 separately
