### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by rabebb** [amplication/amplication#3993]
### Feature description

add customized error messages to base api. like http exception filter but more specific. for example, in create a user when there's a duplicate unique element, it returns "500 internal server error" and in the terminal it returns "unique constraint failed on the  field x". so instead i will be able to display the specific error without having to create a custom api.

thank you

**Comment by souravjain540** [comment]
Thanks for your suggestion. 

@yuval-hazaz @arielweinberger your thoughts?

**Comment by alhaxkar** [comment]
@souravjain540  I'm looking forward to helping the community, Could I take a look on it?

**Comment by yuval-hazaz** [comment]
Thanks for you suggestion, we will look at this soon

**Comment by Ruchika30** [comment]
I can look into it . Can this be assigned to me ? @yuval-hazaz @souravjain540

**Comment by yuval-hazaz** [comment]
This is a duplicate of https://github.com/amplication/amplication/issues/2814 
There is already a PR in progress https://github.com/amplication/amplication/pull/3536
