### ISSUE TITLE
Plugins: Settings

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3998]
Enable plugin developer to collect settings from the user. 
The values of the settings will be passed to the plugin developer from the DSG to be able to make decisions in the plugin based on the values provided by the user. 

https://www.figma.com/file/M1pqmkFKOw2DIm3wU0fB7h/Concept---Plugin-settings---View-Code?node-id=1136%3A6535

**Comment by alexbass86** [comment]
@barshimi @yuval-hazaz, here the link
https://www.figma.com/file/M1pqmkFKOw2DIm3wU0fB7h/Concept---Plugin-settings---View-Code?node-id=788%3A10784&t=lgt3SlU7zi7tvyyS-1

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/3999
