### ISSUE TITLE
DB migrations process and best practices

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4]
we need to set a process on how to use prisma migrations. 
Too often we have conflicts and need to hack around it. 
There are probably best practices that can help us.
We should also think of how to use it later down the road on production to update live DBs.

@iddan if you have any input please share

**Comment by tabuckner** [comment]
have you guys heard of https://github.com/liquibase/liquibase? there's even a node wrapper here https://www.npmjs.com/package/liquibase. 

This tool is used internally by a similar project, https://www.jhipster.tech/

**Comment by yuval-hazaz** [comment]
Thanks @tabuckner . 
Since this issue was opened, Prisma released the Prisma migrate as production-ready, so probably it should be the right tool to move forward with. 
https://www.prisma.io/blog/prisma-migrate-ga-b5eno5g08d0b 
I will also look into liquibase - it looks interesting
