### ISSUE TITLE
🐛 Bug Report: UI issue - Select field's input text is unreadable with current text color

### ISSUE THREAD

**Issue by Manethpak** [amplication/amplication#4001]
### What happened?

<img width="352" alt="Screen Shot 2022-10-01 at 12 07 54 PM" src="https://user-images.githubusercontent.com/58499300/193395776-dbedf2d3-57a1-4941-8108-0cb0253eacb5.png">

The text color for the select field is currently barely readable when I tried to search for a datatype, I have to guess what I'm typing most of the type when I try to search for a specific data type.

### What you expected to happen

A more readable text color.

### How to reproduce

None

### Amplication version

1.0.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@alexbass86 please check if this is valid issue. @Manethpak will make a PR :)

**Comment by JavaVista** [comment]
Hi, can I be assign to this for the hacktoberfest?

**Comment by souravjain540** [comment]
@arielweinberger need your attention to confirm this issue

**Comment by yuval-hazaz** [comment]
@souravjain540 I agree this should be fixed. The color of the text while typing should be the same as the color of the text when viewing a selected item 
![image](https://user-images.githubusercontent.com/43705455/194243812-fbce1937-42b6-4e63-9a87-71d94e44cdff.png)

**Comment by yuval-hazaz** [comment]
> I want to work on this

you can go ahead and work on this

**Comment by KushalRaut** [comment]
Hi @yuval-hazaz 
 Can I work on this issue if it isn't being worked on?

**Comment by souravjain540** [comment]
Assigned @KushalRaut

**Comment by Aadarsh805** [comment]
This issue has been fixed and should be closed

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4227
