### ISSUE TITLE
Docs: Improve README

### ISSUE THREAD

**Issue by Manethpak** [amplication/amplication#4002]
### Describe the issue with documentation

There are some minor issues on the README which I would like to make some improvisation on 

- Current Version on README is incorrect since amplication has already released version 1.0.1 but it still showing 1.0.0
- On the Version section this line `The feature set is listed above in the README file.` seem a bit odd.
- Create bug report and Submit feature request take user to the blank issue page instead of the issue template provided by the amplication team 

### How to solve the problem

My improvisation would be

- Change Version to 1.0.1
- Instead of this `The feature set is listed above in the README file.`, I would change it to `The feature set is listed above in the Features section` with attach link for better user navigation and experience
- Change the current link for Create bug report and Submit feature request to their corresponding issue template provided. 

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
Would love to have a PR from you @Manethpak .

Assigned :)
