### ISSUE TITLE
⭐️ Plugin Versions

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4004]
See - https://www.notion.so/amplication/Plugin-Versions-78aba86264af493a82b41ede0702cd59

### Feature description

Allow the developer of a plugin to publish multiple versions of a plugin. 
Allow a user to select which version of the plugin to be used. 

### Design
https://www.figma.com/file/VUJTnJdplrOahG8kPZ6RRa/%234004---Plugin-Versioning?node-id=1136%3A6535&t=KprM63Tps4019rq0-1

**Comment by barshimi** [comment]
the only thing that we didn't add is the version of the installed plugin on plugin catalog page. it was removed by us when I worked on this task. should we add it ?

**Comment by abrl91** [comment]
I can't test it because the plugin version dropdown is not working

**Comment by abrl91** [comment]
## Tests Results:
1. choosing a version from the dropdown list and save - passed ✅

![Image](https://user-images.githubusercontent.com/39680385/217292192-c622d3c8-7282-4302-a355-dcb72000140e.png)

2. build the app with the requested version - passed ✅

![Image](https://user-images.githubusercontent.com/39680385/217292483-45eb5ab7-b39c-4a9d-8dd4-cd2d896eaffd.png)
