### ISSUE TITLE
Advocacy: Write a blog post about Amplication

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#4006]
We always promote non and low-code contributions to Amplication.

In this issue you have to write a blog post or article about the experience of using Amplication or make a tutorial that about any project using Amplication.

**The blog must include unique content based on your experience and not just a copy-paste from other blogs or Amplication web site.** 

This article should be published on any platform of your choice(for example, Medium, Dev. to, Hashnode, etc.).

You have to create a PR by making a new file(in which there is link to that article) in `tutorials` folder.

This contribution will count as **Two contributions** to the Amplication Hacktoberfest campaign.

**Comment by Rabeet8** [comment]
Hey Sourav,

Can you assign this task to me for Hacktoberfest? I will write the blog on Hashnode.

Here is the link to my Hashnode profile.
https://syedrabeet.hashnode.dev/

Let me know how many words of blogs you want.

**Comment by ilovetensor** [comment]
Hi, can i work on this ... I would love to write an article on Medium.

**Comment by souravjain540** [comment]
> Hi, can i work on this ... I would love to write an article on Medium.

@ilovetensor  feel free to write an blog and raise a PR.

**Comment by ilovetensor** [comment]
I think I can submit it without being assigned to this issue

**Comment by ilovetensor** [comment]
Waiting for 1 approved review in pull request ...

**Comment by BajajAyush** [comment]
hey I have created a blog post pr no- #4081 
@yuval-hazaz

**Comment by Pragya2056** [comment]
@souravjain540 
I have created a link to my blog with a added file according to the rules. 
The PR is #4228 
Please review it.

**Comment by Abubakrce19** [comment]
#4220 
Done and approved.
Ready to merge

**Comment by Abubakrce19** [comment]
> Hi could I be assigned to work on this ?

No need to get assigned.
Start working on it.
This is open for all.
Thank you
(i am not from amplication team)
