### ISSUE TITLE
🐛 Bug Report: "Git Repository is empty" error message is not actionable

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#4010]
### What happened?

When generating a new app with an empty git repository (no README.md), the build fails with a `Git Repository is empty` message.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/4976416/193446633-7291db01-d803-4be5-9b0b-274a05e6fbed.png">

### What you expected to happen

I expect a more actionable error message.

Please improve this error message to:
```
... reason: Git repository is empty. To fix this, commit a README.md file and re-build.
```

### How to reproduce

Reproducing this is difficult and requires setting up GitHub Apps and OAuth Apps. For this reason, we recommend you simply lookup the Amplication repo for the current error message and simply change the text. We will test it for you.

### Amplication version

1.0.0

**Comment by AM1TB** [comment]
@arielweinberger please help with testing the changes for this fix as part of PR #4026.

**Comment by arielweinberger** [comment]
Fixed in #4026

**Comment by yuval-hazaz** [comment]
@arielweinberger 
I am re-opening this issue since I think the current fix is not perfect. 
The new text with the suggestion will appear for every type of error that will return from GitHub and not only for empty repos

**Comment by yuval-hazaz** [comment]
This issue is open for contribution

**Comment by chirag-ghosh** [comment]
I can help

**Comment by yuval-hazaz** [comment]
Thanks, I assigned it to you. Feel free to reach out if you want to discuss the solution or for any questions

**Comment by chirag-ghosh** [comment]
This is what I came up with. Do you have a better alternative or any particular coding practice that's followed here @yuval-hazaz ?

**Comment by yuval-hazaz** [comment]
that is great, thanks
