### ISSUE TITLE
Enhancement: Make field error messages more user-friendly

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#4012]
### Feature description

Currently, when trying to rename a service/project and inserting an empty value, the error looks like this:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/4976416/193446880-b636f1a6-73e3-4818-84a1-56c2fc3664cf.png">

While the error message is clear, I believe it can be more professional and user friendly. 
- First of all, "NOT" being capitalized comes across agressive.
- Secondly, error messages commonly say _what is expected_ rather than _what is wrong_.
 
Instead of `must NOT have fewer than 2 characters` the message should be `Must be at least 2 characters long`.

If you can, please go through the repo and apply this change wherever applicable (a simple search of "must NOT" in our repo reveals a few more occurences).

We would happily help you with error messages if needed.

**Comment by souravjain540** [comment]
> Hi @arielweinberger I would like to work on this issue

Assigned. Let us know if you need any help.

**Comment by ilovetensor** [comment]
Hi, can i work on this issue ?

**Comment by kVarunkk** [comment]
Hi, I want to work on this issue but I'm unable to find the frontend(React) part of Amplication. It would be great if someone could guide me regarding the path!

**Comment by Github-Emmi** [comment]
I would love to know what is behind the frontend and backend of this project so I can apply for contribution

**Comment by souravjain540** [comment]
Are you working on this issue @su-mit?

**Comment by souravjain540** [comment]
> Hi, I want to work on this issue but I'm unable to find the frontend(React) part of Amplication. It would be great if someone could guide me regarding the path!

hi @kVarunkk its `packages/amplication-client/src/Resource/ResourceForm.tsx`

assigning it to you.

**Comment by kVarunkk** [comment]
> > Hi, I want to work on this issue but I'm unable to find the frontend(React) part of Amplication. It would be great if someone could guide me regarding the path!
> 
> hi @kVarunkk its `packages/amplication-client/src/Resource/ResourceForm.tsx`
> 
> assigning it to you.

Thanks, @souravjain540 
I'll get back to you in couple of days

**Comment by kVarunkk** [comment]
Hey @souravjain540, I tried a lot but can't find where the error message is located
I could not find anything like ```must NOT have fewer than 2 characters``` in the repo
It would be great if you could guide me
Thanks!

**Comment by yuval-hazaz** [comment]
@kVarunkk thanks for your support.
This issue is a little bit thicker than just replacing strings. 

We are using ajv (https://github.com/ajv-validator/ajv) for JSON schema validation - and the error messages that are shown on the UI are the default messages returned from ajv. 

In order to show custom messages, we need to use a library like ajv-errors (https://github.com/ajv-validator/ajv-errors) 

If you want to keep working on this issue, I suggest that you choose a single location to start with and send a PR to approve thee initial design before you implement more places. 

If you prefer to work on another issue, let us know and we will be happy to find another issue for you

**Comment by kVarunkk** [comment]
Hey @yuval-hazaz, thanks for the reply! You can assign this issue to some other person as it would take me some time to study about ajv as I'm completely new to this concept

**Comment by plopez26DPU** [comment]
I am willing to give it a shot. Could you assign me?

**Comment by TheLearneer** [comment]
Hi there 👋 
I would like to work on this issue 🙌

**Comment by Ahtritus** [comment]
Hi @yuval-hazaz @souravjain540 Could you please assign this to me? I would like to take this up.

**Comment by souravjain540** [comment]
> Hi @yuval-hazaz @souravjain540 Could you please assign this to me? I would like to take this up.

sure!

**Comment by Ahtritus** [comment]
Hey, while going through the app, I found out a couple other places with the same error. 

Workspace Settings -> Workspace name
<img width="605" alt="image" src="https://user-images.githubusercontent.com/53258966/196966782-0bdd5979-a1cd-473a-9e88-7b6868345b50.png">

User Profile -> First and Last Name
<img width="316" alt="image" src="https://user-images.githubusercontent.com/53258966/196967158-14884a60-cb15-4686-99e4-26be2b9a9ba7.png">

Shall I raise an issue for these as well or shall I fix them all in this same PR?

**Comment by Ahtritus** [comment]
> Hey, while going through the app, I found out a couple other places with the same error.
> 
> Workspace Settings -> Workspace name <img alt="image" width="605" src="https://user-images.githubusercontent.com/53258966/196966782-0bdd5979-a1cd-473a-9e88-7b6868345b50.png">
> 
> User Profile -> First and Last Name <img alt="image" width="316" src="https://user-images.githubusercontent.com/53258966/196967158-14884a60-cb15-4686-99e4-26be2b9a9ba7.png">
> 
> Shall I raise an issue for these as well or shall I fix them all in this same PR?
> 
> @souravjain540

Alright, seems like the issue description does mention to get all the messages fixed in the repo, although its not just a simple global search.

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4215
