### ISSUE TITLE
🐛 Bug Report: Spacing is incorrect in the "Connections" view for a Service

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#4013]
### What happened?

The spacing in the Connections view of a Service is off. The heading and the description are tight against each over.

<img width="634" alt="Screenshot 2022-10-02 at 11 16 34" src="https://user-images.githubusercontent.com/4976416/193447093-88cba6fa-1e77-4bd9-baec-aaed8f2c56b1.png">

### What you expected to happen

There should be a 12px spacing between the heading and the description.

### How to reproduce

1. Create a Service
2. Enter the Service
3. Click the "Connections" button on the left sidenav

### Amplication version

1.0.0

**Comment by aryanxsri** [comment]
hiii  ariel, im looking for a way in into open source and stuff that's how i actually came up to your issue, so can I contribute and help you in your project??

**Comment by arielweinberger** [comment]
Absolutely

**Comment by aryanxsri** [comment]
you'll assign the issue to first right before I start working on it??

**Comment by arielweinberger** [comment]
I'm not on my computer at the moment, feel free to start. @souravjain540 can assign retroactively.

**Comment by souravjain540** [comment]
Assigned @aryanxsri. Let us know if any help needed :)

**Comment by aryanxsri** [comment]
okiee thenks

**Comment by adnanhashmi09** [comment]
I would like to work on this issue. Please assign it to me. :)

**Comment by souravjain540** [comment]
Assigned @adnanhashmi09. Let us know if you need any help :)

**Comment by ilovetensor** [comment]
Can I work on this issue?

**Comment by adnanhashmi09** [comment]
Hey @souravjain540 I have created a PR for this issue. Please review it. :)
