### ISSUE TITLE
Plugin: Create Debugger/Tester for Plugin Developer

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4014]
Tool for plugin developer to allow 

1. Testing the plugin (Debugging)
2. The ability to run plugins in an environment that mimics the real DSG environment

**Comment by arielweinberger** [comment]
This is tightly related to running DSG in-cluster and dynamically installing NPM plugins. I'd say, these two should be at a ready state before we start thinking about a debugger/tester experience.
