### ISSUE TITLE
Topic naming validation message is not consistent with our styleguide

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#4015]
### Feature description

Topic name validation is not consistent with how we do validation at Amplication.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/4976416/193447359-0944ea46-769e-495b-bc47-244d5ca91fda.png">

Notice the tooltip/popover.

### Use case

This is what error messages should look like:
![image](https://user-images.githubusercontent.com/4976416/193447380-6a6ed7b0-09ca-4115-b367-571e89f37e34.png)

You can see the code for this in the Project Settings or Service Settings view.

**Comment by Asmit2952** [comment]
Hey @arielweinberger I can work on this issue.

**Comment by arielweinberger** [comment]
@Asmit2952 Go ahead! Let us know if you need our assistance.

**Comment by wiseaidev** [comment]
Another easy one. Oh wait, it is assigned! Good luck!

**Comment by yuval-hazaz** [comment]
hi @Asmit2952 I just saw that @wiseaidev 's  work on another issue would also resolve this issue 
This is the PR that handles the other issue
https://github.com/amplication/amplication/pull/4078

Sorry if you already spent time working on this. 
I will unassign you and will assign the @wiseaidev

**Comment by yuval-hazaz** [comment]
@Asmit2952 let me know if you see anything else that you want to work on and I would love to assign it to you

**Comment by Asmit2952** [comment]
> @Asmit2952 let me know if you see anything else that you want to work on and I would love to assign it to you

Hey @yuval-hazaz I was going to make a PR today. But no problem, I'll be happy to work on another issue. Can you assign me any beginner friendly issue related to docs or frontend? I'll be happy to work on it.

**Comment by yuval-hazaz** [comment]
@Asmit2952 I created a new issue that may fit your needs. 
https://github.com/amplication/amplication/issues/4083
please comment on the issue and I will assign it to you

**Comment by wiseaidev** [comment]
This ticket is fixed in [pull/4084](https://github.com/amplication/amplication/pull/4084) which is merged into the `next` branch in [pull/4084](https://github.com/amplication/amplication/pull/4126) by @barshimi.
