### ISSUE TITLE
🐛 Bug Report: Pending Changes doesn't update after deleting a Service

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4017]
### What happened?

There are pending changes that should not exist:
![image](https://user-images.githubusercontent.com/6080188/193447867-4b6d3c8d-dad0-4ed4-8ed8-e925a7b78dd8.png)

### What you expected to happen

Create service
Remove service
See that pending changes still applied for the project

### How to reproduce

v1.0.1

**Comment by saloni137** [comment]
@EugeneTseitlin I would like to work on this issue.

**Comment by GreenMachine01** [comment]
@saloni137 Assigned to you. Good Luck!

**Comment by souravjain540** [comment]
any updates @saloni137

**Comment by GreenMachine01** [comment]
@souravjain540 I see no progress with the item so allowing new contributors to take it on.

**Comment by yuval-hazaz** [comment]
@GreenMachine01 I think that @abrl91 started to work on something in this area before and may have some insight on the depth of efforts that are needed. 
I think we should keep this item internally until we have a clear definition of the proposed solution (it should be more then just hiding the items, we need to have a server-side behavior that will close the pending changes or other things around it)

**Comment by abrl91** [comment]
@GreenMachine01 @yuval-hazaz 
I Agree. The "issue" with the pending changes has come up several times already in different areas (message broker, roles, project configuration, etc.) and we have to define the desired behavior for each

**Comment by arielweinberger** [comment]
Tested on Next and seems to be fixed.

**Comment by abrl91** [comment]
fixed by https://github.com/amplication/amplication/pull/4928
