### ISSUE TITLE
Ability to remove Topics

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#4018]
### Feature description

Currently, we are only able to create topics but not remove them. This is an essential feature.

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/4976416/193447920-d7f26498-6746-467c-a6f3-bdf8485de2f6.png">

### Requirements:

- Allow the user to delete a Topic
- if the topic is not connected to any (receiver/sender) entity it can just be deleted
- If the topic being deleted is currently connected to any service (receiver/sender) show the user a warning before actually deleting the topic
    - "Are you sure?" notification design will be provided
    - if the user cancels the request he is returned to the page without deleting the topic
    - if the user approves the request the topic is deleted

Notice - any existing services connected to the topic will lose the connection configuration once the topic is deleted.

### Design
https://www.figma.com/file/ZYExoG89CFPibfoQHq4gpB/%234018---Topic---Are-you-sure%3F?node-id=1136%3A6535&t=Wd47IWspGq2ZJVl6-1

### How to Demo:
**Scenario 1 - Without dependancy**
1. Create a new topic
2. Delete the topic
3. The topic is deleted

**Scenario 2 - With dependancy**
1. Create a new topic
2. Connect the topic to several services
3. Try to delete the topic
4. Get an "Are you sure ?" notification with info on connected services
5. cancel the request
6. Verify the topic wasnt deleted
7. Try to delete the topic
4. Get an "Are you sure ?" notification with info on connected services
5. approve the request
6. The topic is deleted
7. All connections configured for the topic are deleted

**Comment by arielweinberger** [comment]
@yuval-hazaz Is this something the community can pick up?

**Comment by b4s36t4** [comment]
Can I pick this?

**Comment by yuval-hazaz** [comment]
@b4s36t4 I assigned to you. 
good luck

**Comment by b4s36t4** [comment]
Hey, @yuval-hazaz. Any design where to put the delete icon etc?

**Comment by MichaelSolati** [comment]
I would suggest it should look like a property on an entity.

![Screenshot_20221006-135300.png](https://user-images.githubusercontent.com/11811422/194416505-152f2d8c-5cf2-413b-84ed-38b429263d5e.png)

**Comment by yuval-hazaz** [comment]
I agree with @MichaelSolati

**Comment by abrl91** [comment]
fixed by https://github.com/amplication/amplication/pull/4353
