### ISSUE TITLE
🐛 Bug Report: Pending change is missing when create Message Broker

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4021]
### What happened?

![image](https://user-images.githubusercontent.com/6080188/193448119-4d81883a-e0a8-41bf-90be-ed6f2939f025.png)
Pending change is missing when create Message Broker

### What you expected to happen

Add Message Broker
See pending changes related to Message Broker

### How to reproduce

Create Message Broker

### Amplication version

v1.0.1

**Comment by Azanul** [comment]
I'd like to work on this

**Comment by abrl91** [comment]
@GreenMachine01 @yuval-hazaz 
Is there any chance that this behavior is by design? 

https://user-images.githubusercontent.com/39680385/196955279-40f6791f-a527-4a39-aecb-94dde5114f97.mov

**Comment by GreenMachine01** [comment]
We decided to address this bug by adding a default topic when creating a new Message Broker. Canceling this bug and opening a new issue.
