### ISSUE TITLE
🐛 Bug Report: Build stuck and empty screen shown when going to build logs

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4023]
### What happened?

Build process stuck and there is no option to open logs.
https://user-images.githubusercontent.com/6080188/193451257-dd571645-4302-45ef-8103-efcd0e85364e.mp4
On build id click logs should be opened.
![image](https://user-images.githubusercontent.com/6080188/193452659-24245986-d70b-4d60-91ad-e9f0af9434cf.png)

### What you expected to happen

Log screen should appear.

### How to reproduce

Repeat steps from video.

### Amplication version

v1.0.1

**Comment by arielweinberger** [comment]
Can confirm this is happening only with in-progress builds.

Possibly related to this PR: https://github.com/amplication/amplication/pull/3942
