### ISSUE TITLE
🐛 Bug Report: Can't run generated app with docker compose

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4027]
### What happened?

![image](https://user-images.githubusercontent.com/6080188/193458794-dcafc9c8-8182-4253-abf2-d2cce54758b5.png)
Docker compose up fails because it expects to have package-lock which is not created during code generation.

### What you expected to happen

Not to fail.

### How to reproduce

Generate app.
Try to run it with docker compose up.

### Amplication version

v1.0.1

**Comment by shubhwip** [comment]
Hey Can I work on this ?

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4191
