### ISSUE TITLE
🐛 Bug Report: Generation of app with message broker stuck

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4028]
### What happened?

Generation of app with message broker stuck
![image](https://user-images.githubusercontent.com/6080188/193460938-01b7e6ee-edb1-427b-8aff-d4fb0d7fcffc.png)

### What you expected to happen

Application should be generated.

### How to reproduce

Create message broker and topic.
Create two services with kafka plugin and connection to message broker and topic.
Build the app.

### Amplication version

v1.0.1

**Comment by Azanul** [comment]
I'd like to work on this

**Comment by GreenMachine01** [comment]
@EugeneTseitlin is this still relevant?
