### ISSUE TITLE
🐛 Bug Report: Service doesn't connect to Kafka 

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4029]
### What happened?

![image](https://user-images.githubusercontent.com/6080188/193461947-e9c2e9c4-c3cf-4827-abfb-784f73823524.png)
Service doesn't connect to Kafka despite it's connected to topic.

### What you expected to happen

Service should connect to Kafka by default.

### How to reproduce

Create message broker and topic.
Create service with connection to message broker and topic.
Generate app.
Run service.

### Amplication version

v1.0.1

**Comment by shubhwip** [comment]
Hey Can I work on this ?

**Comment by gmmkmtgk** [comment]
Hey Can I work on this ?

**Comment by yuval-hazaz** [comment]
@shubhwip & @gmmkmtgk thanks for your interest in working on this issue.

@EugeneTseitlin can you please provide more details on this issue and whether it is open for contribution or is it already in progress?
