### ISSUE TITLE
Remove unused/unnecessary env vars inside the helm-chart

### ISSUE THREAD

**Issue by shaharblanksela** [amplication/amplication#4030]
### Feature description

Part of my task is to remove unnecessary/unused environment variables. I noticed that there are some variables whose usage can be changed as a default value and thus save them from being written on the helm chart.
such as in 'amplication server':
```
    NODE_ENV: "production"
    GRAPHQL_DEBUG: "0"
    PLAYGROUND_ENABLE: "0"
    BCRYPT_SALT_OR_ROUNDS: "10"
    CORS_ENABLE: "1"
```

### Use case

Reorganization of environment variables and code cleanup.

**Comment by arielweinberger** [comment]
I would not remove NODE_ENV from the list because it is very commonly used in Node apps and it's important on the chart.

The rest are OK to remove imo.

**Comment by shaharblanksela** [comment]
Will be added inside the 'amplication-manifests' repo.
