### ISSUE TITLE
Advocacy: Twitter Thread and Linkedin Post talking about Amplication.

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#4031]
In this issue, you have to write on both platforms:

- One Twitter Thread
- One Linkedin Post

Talking about your experience using Amplication or contributing to Amplication.

The content must provide some value to the community.

You have to tag Amplication on both platforms.

Linkedin: https://www.linkedin.com/company/67730467
Twitter: https://www.twitter.com/amplication

You have to create a file in PR with a link to both of your posts in the `tutorials` folder.

**Comment by Asmit2952** [comment]
Can anyone work on this?

**Comment by souravjain540** [comment]
> Can anyone work on this?

yes.

**Comment by Terieyenike** [comment]
Is anyone working on this yet?

**Comment by KlausMikhaelson** [comment]
@Terieyenike ig even you can post it and will get counted as a pr

**Comment by ankushgupta365** [comment]
Hey, @souravjain540 can you assign this to me ?

**Comment by KlausMikhaelson** [comment]
Hey @ankushgupta365 you can just create the posts and make the pr, this issue doesn't need to get assigned

**Comment by BajajAyush** [comment]
Created PR #4087 with links to social media posts
