### ISSUE TITLE
User Interview: 30 mins chat about your experience or feedback about Amplication with someone from team

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#4033]
This issue is open to every user of Amplication. 

You have to join a 30-minute call with someone from the Amplication team and provide your valuable feedback. 

To contribute to this issue, you have first to fill out the given form: https://forms.gle/Bjmnh8vMrwY8fxmc6

After this, we will filter out and schedule a call, and after a successful call, we will tell you how to make a PR for the contribution.

NOTE: We will filter out the entries, our time is limited so please fill it if and only if you are using Amplication or you have valuable feedback for us( positive or negative).

This issue will give you **2 points** in the Amplication Hacktoberfest campaign.

**Comment by Github-Emmi** [comment]
How can I know I'm using Amplication? I want to fill the form

**Comment by anchal-gupta** [comment]
Hey @souravjain540 , I have filled out the form and looking forward to get in touch with someone from your team.

**Comment by yuval-hazaz** [comment]
Thanks @anchal-gupta we will be in touch soon.

**Comment by Gingaaa** [comment]
Hey I have worked on around 7-8 company based project, but never countribute to open source this is my first time can you assign me this task.
