### ISSUE TITLE
`@amplication/code-gen-types` needs to be ignored from `lerna version` and versioned independently

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#4034]
### Feature description

We do not want this package to stick to the Amplication versioning system. It should strictly follow Semantic Versioning independently.

**Comment by barshimi** [comment]
I think the best way to treat this package is to remove it from lerna and publish it only as npm public package.

**Comment by arielweinberger** [comment]
Still needed, but in the context of Nx.

**Comment by arielweinberger** [comment]
Closed in favor of #4343 after Nx migration.
