### ISSUE TITLE
🐛 Bug Report: Title of home page of webite

### ISSUE THREAD

**Issue by akshitarora921** [amplication/amplication#4037]
### What happened?

Website https://amplication.com/ title is currently "Node.js App Development: Open Source Platform | Amplication"

### What you expected to happen

Page title should be "Amplication | Node.js App Development: Open Source Platform"

### How to reproduce

Open [https://amplication.com/](https://amplication.com/) and check the title in the browser tab
<img width="1904" alt="Screenshot 2022-10-03 at 7 41 16 PM" src="https://user-images.githubusercontent.com/11087313/193599824-2c5ee653-3be9-4bb0-b5f7-594d3895e1ba.png">

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by lmssr** [comment]
Hello, can I work on this Issue ?

**Comment by akshitarora921** [comment]
Hi @lmssr, Thank you for showing the interest. This issue is not yet confirmed. Happy Hacking 🎸

**Comment by ArmanChand** [comment]
Hi @akshitarora921 , can i take this up

**Comment by souravjain540** [comment]
This is something related to SEO. I am not sure we want to change it or not. Views? @yuval-hazaz

**Comment by akshitarora921** [comment]
Hi @souravjain540,
As we are using the same keywords, I think It will not impact the SEO.

**Comment by souravjain540** [comment]
> Hi @souravjain540,
> As we are using the same keywords, I think It will not impact the SEO.

Then why should we change that?

**Comment by akshitarora921** [comment]
@souravjain540,As it is the home page, I feel it should say brand name first.

**Comment by souravjain540** [comment]
I think this change is not bringing any value, but let's wait for @yuval-hazaz opinion.

**Comment by ArmanChand** [comment]
> I think this change is not bringing any value, but let's wait for @yuval-hazaz opinion.

yes @souravjain540 , waiting for your call

**Comment by Priyanshu-Singh-1** [comment]
I am interested in this issue. Can I work on it @akshitarora921 ?

**Comment by AshwiniDR1802** [comment]
Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@akshitarora921 thanks for suggesting that. 
Our SEO team is working on the content of the website. I don't see a reason to make this change.

Thanks for your support, and please keep up the excellent work
