### ISSUE TITLE
Hacktoberfest 2022 🚀 

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#4039]
# Amplication Hacktoberfest 2022 🎃

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/53312820/193637465-5309ced1-9ac7-4759-b731-0289affe57f7.png)

Hello contributors 👋

As proud members of the open-source community, we inspire developers to contribute to open-source projects, and what's better than the month of open source, Hacktoberfest?💜

To help you get started, we have plenty of issues for open-source contributors. 

By giving back to the community, you’re also getting a chance to win cool **limited-edition** swag.

# Prizes 🚀

We've built a UI for you to track how many contributions you've made and what prizes you'll be eligible for.

[Check out your progress here](https://amplication-hacktoberfest.web.app/).

1. Contributors making one to two valid pull requests will get an **exclusive sticker sheet**.
2. Contributors making three or more valid pull requests will get a choice between **exclusive coffee mug or a T-Shirt**.

# Issues

You can find the issues [here](https://www.github.com/amplication/amplication/issues)

Some of the issues will be counted as 2 contributions to our campaign. Make sure to read the description.

# Rules ⚠:

- This activity applies to all of the issues in `amplication\amplication.`
- Only the person assigned by Team Amplication will be considered a valid contributor
- You can also open new issues, but that has to be accepted by someone from Team Amplication to be considered as a valid issue.
- Every contribution that is made between October 1, 2022, to October 31, 2022, in any time zone will be considered a valid contribution.
- We will allow you to complete the reviews or feedback our team gave until November 7, 2022.
- This activity is on a “first come first serve” basis.
- Any participant can get only one swag. No stacking of SWAG is allowed.
- The SWAG is in limited quantity.

**Comment by kVarunkk** [comment]
Hi @souravjain540, can I open issues regarding documentation errors? And will they be considered for swags?

**Comment by ilovetensor** [comment]
how i can get these swags as now i have contributed 2 points?

**Comment by souravjain540** [comment]
> how i can get these swags as now i have contributed 2 points?

We will contact everyone after the end of Hacktoberfest ❤️

**Comment by mathagician** [comment]
created one PR for this https://github.com/amplication/amplication/pull/4232
Please review

**Comment by BajajAyush** [comment]
> > how i can get these swags as now i have contributed 2 points?
> 
> We will contact everyone after the end of Hacktoberfest ❤️

Will we be emailed regarding this?

**Comment by souravjain540** [comment]
> > > how i can get these swags as now i have contributed 2 points?
> > 
> > 
> > We will contact everyone after the end of Hacktoberfest ❤️
> 
> Will we be emailed regarding this?

yes!
