### ISSUE TITLE
🐛 Bug Report: Pending changes list is not updated when switching projects

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4043]
### What happened?

When you view a project with pending changes, then switch the another project without pending changes, the list of pending changes is still showing the items from the previous project

in this screenshot, we can see changes on a service called "my service-1" while the current project does not include this service 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/43705455/193749669-597acb30-0935-41e6-a2c9-6fd252455bdb.png">

### What you expected to happen

The list of pending changes should be updated and show the changes of the current project, even when there are no changes in the newly selected project 

### How to reproduce

Open a project and make some changes (for example, created a service).
Before committing the changes, go to the Project List page, and select a new project. 

assuming there are no pending changes in the newly selected project, the list of pending changes still shows the items from the previous project. 

make a change in the new project (example, create a new service), and see how the list is now updated with the relevant changes. 

### Amplication version

1.0.2

**Comment by Jyotiraditya24** [comment]
this issue is same as #4024 right? would like to work on it

**Comment by souravjain540** [comment]
assigned @Jyotiraditya24 . let us know if you need any help.

**Comment by Jyotiraditya24** [comment]
could I get the path of file ? @souravjain540

**Comment by yuval-hazaz** [comment]
@Jyotiraditya24 the pending changes list is managed here
packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts

**Comment by souravjain540** [comment]
any update @Jyotiraditya24

**Comment by TheLearneer** [comment]
Hi @yuval-hazaz @souravjain540 👋 
I would love to work on it 🙇

**Comment by souravjain540** [comment]
assigned :)
