### ISSUE TITLE
🚀 Feature: Allow users to delete a project

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4044]
### Feature description

- Add a new delete button on the Project Configuration item

![image](https://user-images.githubusercontent.com/43705455/193750590-69e1ce4a-a6fa-4b57-90b3-a4e52d82ef48.png)

- When clicked, show the user a warning with a confirmation button "This action cannot be undone. This will permanently delete the project and all its resources. Are you sure you want to continue?"

<img width="726" alt="image" src="https://user-images.githubusercontent.com/43705455/193750859-adce6ac2-1fee-43c8-a7e3-1f36c99f8e2d.png">

- On the server side, use soft delete (there is already a "deletedAt" field). Copy the behavior from resource.service.ts

### Use case

The user wants to delete a project

**Comment by ilovetensor** [comment]
Hi can i work on this issue ?

**Comment by souravjain540** [comment]
Sure @ilovetensor . let us know if you need any help.

**Comment by Github-Emmi** [comment]
Can I work on this? I think I can achieve this with the knowledge I have in Django.

**Comment by MuhammadJufri** [comment]
I think i can do this,
Can you assign this issue to me please?

**Comment by yuval-hazaz** [comment]
This issue is already assigned, thanks all

**Comment by MichaelSolati** [comment]
@ilovetensor do you have any updates or progress on this feature?

**Comment by Github-Emmi** [comment]
No

**Comment by KlausMikhaelson** [comment]
@souravjain540 if it's available now than can I work on it ?

**Comment by MichaelSolati** [comment]
@Github-Emmi do you wanna take a stab at this issue?

We're going to go in order of people who asked to handle this issue.

**Comment by MichaelSolati** [comment]
@KlausMikhaelson do you wanna take this issue?

**Comment by MichaelSolati** [comment]
Or @MuhammadJufri, would you like to take this issue.

I'll assign it to whomever asks for it next.

**Comment by KlausMikhaelson** [comment]
@MichaelSolati yeah would like to take this issue if it is available

**Comment by KlausMikhaelson** [comment]
Thanks will start working on it ! @MichaelSolati

**Comment by MuhammadJufri** [comment]
> Or @MuhammadJufri, would you like to take this issue.
> 
> I'll assign it to whomever asks for it next.

Yes, Sure

**Comment by MichaelSolati** [comment]
@KlausMikhaelson do you have any updates on this feature?

**Comment by KlausMikhaelson** [comment]
@MichaelSolati was facing some issues so have asked in the server in the #support channel can you please help me out there ?

**Comment by MichaelSolati** [comment]
@KlausMikhaelson are you NeilBohr on discord? (If not then what is your username on discord?)

**Comment by KlausMikhaelson** [comment]
Hey @MichaelSolati my username is @Klausss#7531 I have setted up amplication multiple times in my local device but dk why I am getting errors this time please check it out

**Comment by SayyidMuhammad878** [comment]
> Hey @MichaelSolati my username is @klausss#7531 I have setted up amplication multiple times in my local device but dk why I am getting errors this time please check it out

Earlier I also received many errors maybe you can try to install typescript globally using npm install -g typescript and then try to install docker and then keep your docker running and then write npm run setup:dev in the amplication folder

**Comment by SayyidMuhammad878** [comment]
After doing that maybe you don't receive any more errors

**Comment by KlausMikhaelson** [comment]
Okay trying that right away ! @SayyidMuhammad878

**Comment by KlausMikhaelson** [comment]
Hey I just reinstalled docker after uninstalling it and it's working now lol, so I am working on the issue and will create the pr asap !

**Comment by GreenMachine01** [comment]
@KlausMikhaelson Hi, Any updates on this item?

**Comment by EugeneTseitlin** [comment]
This functionality was already tested in https://github.com/amplication/amplication/issues/5453
