### ISSUE TITLE
[DOCS] : Wrong link to the emoji in README file 

### ISSUE THREAD

**Issue by shashankbhatgs** [amplication/amplication#4048]
### Describe the issue with documentation

At the bottom of the README file,  under ` Contributors ✨` it is written that
`Thanks goes to these wonderful people (emoji key):` 

There should have been an emoji instead of [emoji key](https://allcontributors.org/docs/en/emoji-key) text which links to the root of `Emoji Key table` 

Link where this issue can be found: https://github.com/amplication/amplication#contributors-

Image: 

![emoji](https://user-images.githubusercontent.com/76593166/193789632-73a7306d-e3a8-4b78-bef0-58af1af3f5d8.png)

### How to solve the problem

I think I would like to add the corresponding emoji which needs to go there instead of [emoji key](https://allcontributors.org/docs/en/emoji-key) text

I would also want to know what emoji should belong there.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MrKrishnaAgarwal** [comment]
I want to work @shashankbhatgs

**Comment by shashankbhatgs** [comment]
hey, @MrKrishnaAgarwal I'm not a maintainer and waiting for someone to assign me, I'm working on it, sorry.

**Comment by yashjain1974** [comment]
Hey I want to resolve this issue.

**Comment by ShreejaMehta** [comment]
Hello! 
I would like to work on this issue.

**Comment by ayrotideysarkar** [comment]
Hello I can add the correct emojis also I can rephrase sentences, 
Can you assign me this?

**Comment by souravjain540** [comment]
I think `emoji-key` here points out that it will be redirected to the emoji-key table used by all-contributors and replacing it with any emoji is not a good idea.

**Comment by ayrotideysarkar** [comment]
But I think it's not looking good.. And the issue description it is written
to add corresponding emoji instead of emoji text

**Comment by shashankbhatgs** [comment]
> I think `emoji-key` here points out that it will be redirected to the emoji-key table used by all-contributors and replacing it with any emoji is not a good idea.

okay, so close this issue?

**Comment by ayrotideysarkar** [comment]
if you can assign me this one i can try to rephrase sentence and can add an
emoji

**Comment by ayrotideysarkar** [comment]
@shashankbhatgs okay but how to contact them?

**Comment by MichaelSolati** [comment]
Closing the issue as it seems as if @souravjain540 said it was not a good idea. However, Saurav, if you want to reopen this feel free.
