### ISSUE TITLE
Scroll to Top Button

### ISSUE THREAD

**Issue by Anikalp1** [amplication/amplication#4056]
### Feature description

**_I will be adding a scroll to top button on main web page._** 

### Use case

Adding a scroll to top button is necessary, as scrolling up a down again and again, irritates users. And decreases focus of user on content, so to overcome this problem, I want to add a scroll to button.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@GreenMachine01 @alexbass86 do we need it?

**Comment by Anikalp1** [comment]
@souravjain540 Assign me this, after discussing.
