### ISSUE TITLE
Add Layout Component to the website

### ISSUE THREAD

**Issue by akshitarora921** [amplication/amplication#4057]
### Feature description

I have observed that we are using `<Header/>`, `<Footer/>` and `<Background/>` components in all the pages. So the idea is to create a Layout component and use it. 
[Reference Link](https://nextjs.org/docs/basic-features/layouts)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by joanjeremiah** [comment]
Yes I am willing to submit a PR! Kindly assign this issue to me.

**Comment by MichaelSolati** [comment]
I think this would be an interesting/smart enhancement. @akshitarora921 I'll assign it to you.

**Comment by MuhammadJufri** [comment]
Can you assign this issue to me please?

**Comment by akshitarora921** [comment]
Hi @MuhammadJufri,
Thank you for showing the interest but I am working on it.
