### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by anchal-gupta** [amplication/amplication#4059]
### Feature description

Push notifications are small, pop-up messages sent to a user's device that appear even when the app isn't open. I am willing to integrate Push Notifications for Chrome & Firefox browser by which you can communicte to users about news, events and annoucements. 
If you are interested in adding this feature to your project, I can go ahead and share some of the best notification providers that are available for free and on which I have already worked on. 

### Use case

Pop Ups to those users who have subscribed for notification updates.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MichaelSolati** [comment]
On what product would this be implemented on, and what benefit do you see this providing said product?

**Comment by yuval-hazaz** [comment]
Thanks for suggesting it. 
For now, push notifications for amplication.com are not needed. 
We have a separate initiative for notification infrastructure for the app that includes events, templates and more. 
I will close this issue. 
Thanks for your support
