### ISSUE TITLE
🐛 Bug Report: Error when creating a record with a relation type

### ISSUE THREAD

**Issue by JohnnyDeeee** [amplication/amplication#4074]
### What happened?

When i try to create a record, through the admin-ui, which references another record i get the following error from the API

![image](https://user-images.githubusercontent.com/9005496/194416108-dbbfa990-d928-4c0c-9ba9-92e247ab67fa.png)

```
Variable "$data" got invalid value { amount: 22 }; Field "gameItem" of required type "GameItemWhereUniqueInput!" was not provided.
```

It looks like the admin-ui doesn't send the "gameItem" and "logType" fields:

```
{
    "operationName": "createLogEntry",
    "variables": {
        "data": {
            "amount": 22
        }
    },
    "query": "mutation createLogEntry($data: LogEntryCreateInput!) {\n  data: createLogEntry(data: $data) {\n    amount\n    createdAt\n    gameItem {\n      id\n      __typename\n    }\n    id\n    logType {\n      id\n      __typename\n    }\n    silver\n    updatedAt\n    __typename\n  }\n}\n"
}
```

This is the configuration for those 2 fields

![image](https://user-images.githubusercontent.com/9005496/194416184-3e8bf078-040a-453f-a6b9-4eea70d92f88.png)
![image](https://user-images.githubusercontent.com/9005496/194416475-fafa022d-414b-42c9-a4e4-53ab09002bac.png)

### What you expected to happen

That i can create a record which references other records

### How to reproduce

1. Create new project
2. Make 3 entities: LogEntry, GameItem, LogType
3. LogEntry has to reference both GameItem and LogType in 2 separate fields
4. Start project (server + admin ui)
5. Create a GameItem record
6. Create a LogType record
7. Try to create a LogEntry record which references both GameItem record and LogType record
8. Notice the error

### Amplication version

Where can i find the version? I used https://app.amplication.com/

### Environment

Node version: `v16.17.0`
NPM version: `8.15.0`
Docker version: `Docker version 17.09.0-ce, build afdb6d4`
OS Details (Linux): 
```
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Linux REDACTED 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yuval-hazaz** [comment]
@JohnnyDeeee thanks for reporting this.
I noticed that the relation in the UI is configured as "1-to-1", I suspect this is the trigger for the issue. 

To validate that assumption, can you please change the relation settings to "1-to-many" and try again?

It will help us focus when working to resolve the issue

**Comment by souravjain540** [comment]
hi @JohnnyDeeee, any updates?

**Comment by JohnnyDeeee** [comment]
Sorry about the late reply, but i've been very busy with work and i have actually moved away from my personal project (that was using this library). You can close this issue as i am unable to give any more details.

**Comment by souravjain540** [comment]
perfectly okay, let us know how we can help you whenever needed.
