### ISSUE TITLE
🐛 Bug Report: No padding in Roadmap section in mobile view

### ISSUE THREAD

**Issue by akshitarora921** [amplication/amplication#4075]
### What happened?

No padding in roadmap section in mobile view.
<img width="487" alt="image" src="https://user-images.githubusercontent.com/11087313/194594297-09927e35-edf3-4489-942e-0cac5fc2e207.png">

### What you expected to happen

There should be some padding.

### How to reproduce

Open https://amplication.com/ in mobile view and scroll down to roadmap section.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AshwiniDR1802** [comment]
Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@akshitarora921 thanks for suggesting this. 
I have assigned you, please go ahead

**Comment by 05him** [comment]
i also wanna do this but looks like this is already done

**Comment by yuval-hazaz** [comment]
the issue is already assigned
