### ISSUE TITLE
🐛 Bug Report: Tags on Blog page are not rendered properly in Mobile view

### ISSUE THREAD

**Issue by akshitarora921** [amplication/amplication#4076]
### What happened?

Issue with tags
- Height is not proper
- Tags are not wrapped

<img width="426" alt="image" src="https://user-images.githubusercontent.com/11087313/194596483-c75f91f2-ad37-4b10-99cf-8498ece236de.png">

### What you expected to happen

- Tags height should change based upon data
- Tags should wrap

### How to reproduce

Open blogs page in mobile view.
https://amplication.com/blog

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by CursedRock17** [comment]
@akshitarora921 I would like to take this issue if possible.

**Comment by MuhammadJufri** [comment]
I think I can do this
Can you assign this issue to me please?

**Comment by yuval-hazaz** [comment]
Thanks all.
before we move forward with a fix, I would love @alexbass86 to propose the design with the expected results

**Comment by MuhammadJufri** [comment]
Okay thanks

**Comment by 05him** [comment]
mai i also get a chance to work on this, i need to imply the css ive learned

**Comment by MuhammadJufri** [comment]
Can I ask a question please, 
where is the blog file? 

Thanks

**Comment by yuval-hazaz** [comment]
https://github.com/amplication/amplication-site

**Comment by MuhammadJufri** [comment]
Thanks!

**Comment by akshitarora921** [comment]
@yuval-hazaz @alexbass86 
Love to hear your opinion, I think `margin-top` and `flex-wrap` will do the job!
![image](https://user-images.githubusercontent.com/11087313/194753325-7c803465-aacb-43a0-b7da-e24ecfd55c62.png)

**Comment by MuhammadJufri** [comment]
I've fixed this issue 
Please merge [my pull request](https://github.com/amplication/amplication-site/pull/231)

**Comment by akshitarora921** [comment]
@MuhammadJufri, the issue is not assigned to you and I have already asked to assign me.

**Comment by yuval-hazaz** [comment]
We are still waiting for response from @alexbass86 . There is an holiday in Israel do it may take some time. Until then, we will not accept PRs, and also according to our policy, please wait to be assigned to an issue before sending a PR.
I appreciate the help from you guys, it is amazing. To be fare with everyone, we must follow the guidelines 

Thanks 💜

**Comment by MuhammadJufri** [comment]
> @MuhammadJufri, the issue is not assigned to you and I have already asked to assign me.

Oh, Sorry I didn't know

**Comment by akshitarora921** [comment]
@yuval-hazaz @alexbass86 Any update on this?

**Comment by souravjain540** [comment]
@alexbass86 please update

**Comment by alexbass86** [comment]
> @yuval-hazaz @alexbass86 Love to hear your opinion, I think `margin-top` and `flex-wrap` will do the job! ![image](https://user-images.githubusercontent.com/11087313/194753325-7c803465-aacb-43a0-b7da-e24ecfd55c62.png)

Great solution!
Please ensure that the padding between the tags & title/text is like in the example.
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1117%3A13861

**Comment by MichaelSolati** [comment]
Fixed by amplication/amplication-site#231
