### ISSUE TITLE
Automatically add the contributers images in readme file and make it more beautifull

### ISSUE THREAD

**Issue by Ankurrawat-12** [amplication/amplication#4079]
### Feature description

it will automatically add the images of the contributes to the readme file.

### Are you willing to submit PR?
Yes
_No response_

**Comment by Beast71421** [comment]
can I have this issue, I would like to work on it.

**Comment by yuval-hazaz** [comment]
Hi @Beast71421 we would love to do that. 
Before we move forward, can you please describe the solution you have in mind - or send us a link to a similar solution/workflow?

**Comment by Beast71421** [comment]
![image](https://user-images.githubusercontent.com/78417225/194696108-b8a19882-afaa-4966-a958-6b67420e3ddc.png)
this will be the outcome of the solution that I have in mind and it will automatically update the contributed image's in readme file

**Comment by MuhammadJufri** [comment]
Can you assign this issue to me please?

**Comment by Beast71421** [comment]
@yuval-hazaz can I have this issue now? and can you also add hecktober fest label : )

**Comment by 05him** [comment]
I would love to solve this issue, and you will like my work too

**Comment by yuval-hazaz** [comment]
The idea of auto-generating the image of all contributors is great, but we need to consider the impact.
Right now, we are following the [all-contributors](https://github.com/all-contributors/all-contributors) specification, where all types of contributors get credit for things like ideas, bugs, docs, and so on.

There is a problem with manually updating the list right now, but replacing it with the solution you suggest is not good enough.

If we can get an automatic workflow to update the README when needed, it will be better.

I am adding @MichaelSolati to the conversation to see if he can think of a process to automate it.

**Comment by Beast71421** [comment]
ok thanks for the suggestion @yuval-hazaz

**Comment by yuval-hazaz** [comment]
> @yuval-hazaz this will include every contributors image

I understand, but only contributors who created PR

**Comment by Beast71421** [comment]
yup, but thanks for the feedback on my issue, I really appreciate it

**Comment by wiseaidev** [comment]
`all-contributors` already has [a bot](https://github.com/all-contributors/app) for this. Just invoke on a PR or issue:

```sh
@all-contributors please add @wiseaidev for code
```

**Comment by yuval-hazaz** [comment]
Yep, the problem was that we needed to remember to do that with every PR, issue, etc... 
if we can do it automatically at least for PRs, that will be one step forward, then we just need to remember to do it for issues 

any ideas?

**Comment by yuval-hazaz** [comment]
also, the changes in the README are also hard to track.. 
look at this example from the PR that was just created by the BOT

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/43705455/194724293-3f741651-e6f7-4733-aaba-7a47545b4774.png">

somehow it changed the total number from 80 to 57 
also there are many other changes in the PR https://github.com/amplication/amplication/pull/4085/files

**Comment by wiseaidev** [comment]
Ah, now I see what's wrong. That would be a good thing to resolve/automate.

**Comment by yuval-hazaz** [comment]
already fixed
