### ISSUE TITLE
Docs: Plugin Events Article - Create Server Package Json Event 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4094]
### Describe the issue with documentation

The Plugin docs need to include a description of Events.

## (The following can be used as an example of how to document the other Events: )

# Create Server Package Json Event

## Description

Create the `package.json` file of the service

## Event name:
`CreateServerPackageJson`

## Event Params

```tsx
export interface CreateServerPackageJsonParams extends EventParams {
  updateProperties: { [key: string]: any }[];
```

### updateProperties
An array of objects represents the additional properties the user wants to add to the `package.json file`, such as dependencies, scripts, etc.

Example: 

```ts
  beforeUpdateJson(
    context: DsgContext,
    eventParams: CreateServerPackageJsonParams
  ): CreateServerPackageJsonParams {
    const myValues = [{
      dependencies: {
        "@nestjs/microservices": "8.2.3",
        kafkajs: "2.2.0",
      },
    }];
    const newValues = merge(eventParams.updateValues, myValues);

    return { ...eventParams, updateValues: newValues };
  }
```

**Comment by abrl91** [comment]
@MoFoGo I updated the description, please review
@yuval-hazaz I updated it based on the change I will make after you approve this PR: https://github.com/amplication/amplication/pull/4131

**Comment by abhijeet007rocks8** [comment]
@yuval-hazaz Can you provide some references that i can consider for working on this issue ?

**Comment by yuval-hazaz** [comment]
@abhijeet007rocks8 this is a draft for documentation for the plugin system. No work is currently needed on this issue

**Comment by MoFoGo** [comment]
Transferred to docs
