### ISSUE TITLE
Docs: Plugin Events Article - CreateEntityService

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4097]
### Describe the issue with documentation

This event needs to be included in the docs. 

### How to solve the problem

Create an article describing the Plugin Event. 

### The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

### For reference, the Plugin Events tree is shown here:

https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Entity Service

## Description

Creates the service of an entity

## Event Name:
`CreateEntityService`

## Event Params

```tsx
export interface CreateEntityServiceParams extends EventParams {
  entityName: string;
  templateMapping: { [key: string]: any };
  passwordFields: EntityField[];
  serviceId: namedTypes.Identifier;
  serviceBaseId: namedTypes.Identifier;
  template: namedTypes.File;
}
```

### entityName

### templateMapping

### passwordFields

### serviceId

### serviceId

### template

**Comment by MoFoGo** [comment]
@MoFoGo (note to self) - See this comment. The content above had been transferred to docs, but make sure this is acted upon: 

@MoFoGo this parameter and the previous parameter are commonly used in a lot of events. we should create a separate document that explains about this process and the options of how to manipulate these parameters. 
We should also use a common language to describe these parameters for all events.
