### ISSUE TITLE
Docs: Plugin Events Article - CreateEntityServiceBase

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4099]
### Describe the issue with documentation

This Plugin Event needs to be included in the docs.

### How to solve the problem

Create an article describing the Plugin Event.

## The following can be used as examples for the documentation.
https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

## For reference, the Plugin Events tree is shown here:
https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Entity Service Base

## Description

Creates the base service of an entity

## Event Name:
`CreateEntityServiceBase`

## Event Params

```tsx
export interface CreateEntityServiceBaseParams extends EventParams {
  entityName: string;
  entity: Entity;
  templateMapping: { [key: string]: any };
  passwordFields: EntityField[];
  serviceId: namedTypes.Identifier;
  serviceBaseId: namedTypes.Identifier;
  delegateId: namedTypes.Identifier;
  template: namedTypes.File;
}
```

### entityName

### entity

### templateMapping

### passwordFields

### serviceId

### ### serviceId

### delegateId

### template

**Comment by MoFoGo** [comment]
Transferred to docs

**Comment by MoFoGo** [comment]
@yuval-hazaz Who can provide input for delegateId ?

**Comment by yuval-hazaz** [comment]
delegateId - The identifier of the Prisma class used to access the entity data
