### ISSUE TITLE
Docs: Plugin Events Article - CreateEntityController

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4100]
### Describe the issue with documentation

This event needs to be included in the docs.

### How to solve the problem

Create an article describing the Plugin Event.

## The following can be used as examples for the documentation.
https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

## For reference, the Plugin Events tree is shown here:
https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Entity Controller

## Description

Creates the controller of an entity

## Event Name:
`CreateEntityController`

## Event Params

```tsx
export interface CreateEntityControllerParams extends EventParams {
  templatePath: string;
  entityName: string;
  entityServiceModule: string;
  templateMapping: { [key: string]: any };
  controllerBaseId: namedTypes.Identifier;
  serviceId: namedTypes.Identifier;
}
```

### templatePath

### entityName

### entityServiceModule

### templateMapping

### controllerBaseId

### serviceId

**Comment by MoFoGo** [comment]
Transferred to docs

**Comment by yuval-hazaz** [comment]
@MoFoGo can we close this issue and all the other similar ones?
