### ISSUE TITLE
Docs: Plugin Events Article - CreateEntityControllerBase

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4102]
### Describe the issue with documentation

This event needs to be included in the docs.

### How to solve the problem

Create an article describing the Plugin Event. 

### The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

### For reference, the Plugin Events tree is shown here:

https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Entity Controller Base

## Description

Creates the base controller of an entity

## Event Name:
`CreateEntityControllerBase`

## Event Params

```tsx
export interface CreateEntityControllerBaseParams extends EventParams {
  baseTemplatePath: string;
  entity: Entity;
  entityName: string;
  entityType: string;
  entityServiceModule: string;
  templateMapping: { [key: string]: any };
  controllerBaseId: namedTypes.Identifier;
  serviceId: namedTypes.Identifier;
}
```

### baseTemplatePath

### entity

### entityName

### entityType

### entityServiceModule

### templateMapping

### controllerBaseId

### serviceId

**Comment by MoFoGo** [comment]
Transferred to docs

**Comment by MoFoGo** [comment]
Require entityServiceModule input

**Comment by MoFoGo** [comment]
Require content for entityServiceModule

**Comment by yuval-hazaz** [comment]
@abrl91 can you help @MoFoGo with the missing parts?
