### ISSUE TITLE
Docs: Plugin Events Article - CreateMessageBroker

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4104]
### Describe the issue with documentation

This event needs to be included in the docs. 

### How to solve the problem

Create an article describing the Plugin Event. 

### The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

### For reference, the Plugin Events tree is shown here:

https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
@yuval-hazaz @MoFoGo please review

**Comment by yuval-hazaz** [comment]
see my comments on https://github.com/amplication/amplication/issues/4109

**Comment by MoFoGo** [comment]
Moved to docs
