### ISSUE TITLE
 Docs: Plugin Events Article -  CreateMessageBrokerClientOptionsFactory

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4105]
### Describe the issue with documentation

This event needs to be included in the docs.

### How to solve the problem

Create an article describing the Plugin Event.

NOTE: Create the content here in this GitHub issue.
The following can be used as examples for the documentation.
https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

For reference, the Plugin Events tree is shown here:
https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Message Broker Client Options Factory

## Description

Creates the client options of the message broker

## Event Name:
`CreateMessageBrokerClientOptionsFactory`

## Event Params
There are no additional params to this event

```ts
export interface CreateMessageBrokerClientOptionsFactoryParams extends EventParams {}
```

Example:
```ts
  async afterCreateMessageBrokerClientOptionsFactory(
    context: DsgContext,
    eventParams: CreateMessageBrokerClientOptionsFactoryParams
  ): Promise<Module[]> {
    const { serverDirectories } = context;
    const filePath = resolve(staticDirectory, "generateKafkaClientOptions.ts");
    const file = await readFile(filePath, "utf8");
    const generateFileName = "generateKafkaClientOptions.ts";

    const path = join(
      serverDirectories.messageBrokerDirectory,
      generateFileName
    );

    return [
      {
        code: file,
        path,
      },
    ];
  }
```

**Comment by abrl91** [comment]
@yuval-hazaz @MoFoGo please review

**Comment by yuval-hazaz** [comment]
see my comments on https://github.com/amplication/amplication/issues/4109

**Comment by MoFoGo** [comment]
Moved to docs
