### ISSUE TITLE
Docs: Plugin Events Article - CreateMessageBrokerNestJSModule

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4106]
### Describe the issue with documentation

This event needs to be included in the docs.

### How to solve the problem

Create an article describing the Plugin Event. 

## The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

## For reference, the Plugin Events tree is shown here:

https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Message Broker NestJS Module

## Description

Creates the NestJS of the message broker

## Event Name:
`CreateMessageBrokerNestJSModule`

## Event Params
There are no additional params to this event

```ts
export interface CreateMessageBrokerNestJSModuleParams extends EventParams {}
```

Example:
```ts
  async afterCreateMessageBrokerNestJSModule(
    context: DsgContext,
    eventParams: CreateMessageBrokerNestJSModuleParams
  ) {
    const filePath = resolve(staticDirectory, "kafka.module.ts");

    const { serverDirectories } = context;
    const { messageBrokerDirectory } = serverDirectories;
    const file = await readFile(filePath, "utf8");
    const generateFileName = "kafka.module.ts";

    this.moduleFile = {
      code: file,
      path: join(messageBrokerDirectory, generateFileName),
    };
    return [this.moduleFile];
  }
```

**Comment by abrl91** [comment]
@MoFoGo @yuval-hazaz please review

**Comment by yuval-hazaz** [comment]
see my comments on https://github.com/amplication/amplication/issues/4109

**Comment by MoFoGo** [comment]
Transferred to docs
