### ISSUE TITLE
Docs: Plugin Events Article - CreateMessageBrokerService

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4107]
### Describe the issue with documentation

This event needs to be included in the docs. 

### How to solve the problem

Create an article describing the Plugin Event. 

### The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

### For reference, the Plugin Events tree is shown here:

https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Message Broker Service

## Description

Creates the service of the Kafka message broker

## Event Name:
`CreateMessageBrokerService`

## Event Params
There are no additional params to this event
```ts
export interface CreateMessageBrokerServiceParams extends EventParams {}
```

Example:
```ts
async afterCreateMessageBrokerService(
    context: DsgContext,
    eventParams: CreateMessageBrokerServiceParams
  ): Promise<Module[]> {
    const { serverDirectories } = context;
    const { messageBrokerDirectory } = serverDirectories;
    const filePath = resolve(staticDirectory, `kafka.service.ts`);

    const file = await readFile(filePath, "utf8");
    const generateFileName = `kafka.service.ts`;

    const path = join(messageBrokerDirectory, generateFileName);
    return [{ code: file, path }];
  }
```

**Comment by abrl91** [comment]
@yuval-hazaz @MoFoGo please review

**Comment by yuval-hazaz** [comment]
see my comments on https://github.com/amplication/amplication/issues/4109
