### ISSUE TITLE
Docs: Plugin Events Article - CreateMessageBrokerServiceBase

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4108]
### Describe the issue with documentation

This event needs to be included in the docs. 

### How to solve the problem

Create an article describing the Plugin Event. 

### The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

### For reference, the Plugin Events tree is shown here:

https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Message Broker Service Base

## Description

Creates the message broker service base

## Event Name:
`CreateMessageBrokerServiceBase`

## Event Params
There are no additional params to this event
```ts
export interface CreateMessageBrokerServiceBaseParams extends EventParams {}
```

Example:
```ts
  async afterCreateMessageBrokerServiceBase(
    context: DsgContext,
    eventParams: CreateMessageBrokerServiceBaseParams
  ): Promise<Module[]> {
    const { serverDirectories } = context;
    const { messageBrokerDirectory } = serverDirectories;
    const filePath = resolve(staticDirectory, `kafka.service.base.ts`);

    const file = await readFile(filePath, "utf8");
    const generateFileName = `kafka.service.base.ts`;

    const path = join(messageBrokerDirectory, "base", generateFileName);
    return [{ code: file, path }];
  }
```

**Comment by abrl91** [comment]
@MoFoGo @yuval-hazaz please review

**Comment by yuval-hazaz** [comment]
see my comments on #4109

**Comment by MoFoGo** [comment]
Transferred to docs
