### ISSUE TITLE
Docs: Plugin Events Article - CreateMessageBrokerTopicsEnum

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4109]
### Describe the issue with documentation

This event needs to be included in the docs. 

### How to solve the problem

Create an article describing the Plugin Event. 

### The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

### For reference, the Plugin Events tree is shown here:

https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Message Broker Topic Enum

## Description

Creates the message Broker topics enum

## Event Name:
`CreateMessageBrokerTopicsEnum`

## Event Params
There are no additional params to this event
```tsx
export interface CreateMessageBrokerTopicsEnumParams extends EventParams {}
```

**Comment by abrl91** [comment]
@MoFoGo @yuval-hazaz, please review. 
There is no example of using this event. The Kafka plugin is not using it.

**Comment by yuval-hazaz** [comment]
@tupe12334 please add details on this events - please explain when the data is taken from (context) and what is the results of this event (in the plugin)

**Comment by yuval-hazaz** [comment]
we should also explain that this event does NOTHING by default and it is only handled by plugins

**Comment by MoFoGo** [comment]
@tupe12334 please provide the information as requested by @yuval-hazaz above

**Comment by MoFoGo** [comment]
Updated. See PR
