### ISSUE TITLE
Docs: Plugin Events Article - CreateServerDotEnv

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4111]
### Describe the issue with documentation

This event needs to be included in the docs. 

### How to solve the problem

Create an article describing the Plugin Event. 

### The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

### For reference, the Plugin Events tree is shown here:

https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Server DotEnv

## Description

Creates the server's `.env` file

## Event Name:
`CreateServerDotEnv`

## Event Params

```ts
export interface CreateServerDotEnvParams extends EventParams {
  envVariables: VariableDictionary;
}
```

```ts
export type VariableDictionary = {
  [variable: string]: string;
}[];
```

### envVariables
An Array of objects represent the key - the env param, and the value - the value of the event params

**Example**

```ts
export const envVariables: VariableDictionary = [
  { DB_USER: "${dbUser}" },
  { DB_PASSWORD: "${dbPassword}" },
  { DB_PORT: "${dbPort}" },
  {
    DB_URL: "mysql://${dbUser}:${dbPassword}@${dbHost}:${dbPort}${dbName}",
  },
];

beforeCreateServerDotEnv(
    context: DsgContext,
    eventParams: CreateServerDotEnvParams
  ) {
    eventParams.envVariables = [...eventParams.envVariables, ...envVariables];

    return eventParams;
  }
```

**Comment by abrl91** [comment]
@yuval-hazaz @MoFoGo please review

**Comment by yuval-hazaz** [comment]
@abrl91 well done! 
I think we can add more details about the placeholders in the values like "${dbUser}"

**Comment by abrl91** [comment]
> @abrl91 well done! I think we can add more details about the placeholders in the values like "${dbUser}"

Done. I guess you didn't mean for me to explain how it happens in DSG. And about the two last sentences - we may want to apply the solution we made in the plugins as a default behavior (?)

**Comment by MoFoGo** [comment]
I'm now transferring this to docs.
