### ISSUE TITLE
Docs: Plugin Events Article - CreateServerDockerComposeDB

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4112]
### Describe the issue with documentation

This event needs to be included in the docs. 

### How to solve the problem

Create an article describing the Plugin Event. 

### The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

### For reference, the Plugin Events tree is shown here:

https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Server Docker Compose DB

## Description

Creates the `docker-compose.db.yml` file of the service

## Event Name:
`CreateServerDockerComposeDB`

## Event Params

```tsx
export interface CreateServerDockerComposeDBParams extends EventParams {
    fileContent: string;
    updateProperties: {[key: string]: any;}[];
    outputFileName: string;
}
```

### fileContent

The default content of the file as a string. If needed, the value can be parsed as an object using a YAML utility. 

In most cases, there is no need to manipulate the property directly. Instead, use the `updatePropeties` param

### updateProperties

An array that accepts any object that will be merged into the docker-compose file.

The object will be deeply merged into the previous state of the file. 

multiple plugins can add objects into this array, and they will be merged by the order of execution of the plugins

**Example**
Unlike the example of `CreateServerDockerCompose` https://github.com/amplication/amplication/issues/4095, in this example, it makes more sense to replace the whole file. The reason for that is that in a `docker-compose.db.yml` file you usually take the DB image from Docker Hub and you want to replace the whole file's content.

The way to do it is by using the `before` lifecycle event and in the body of the function **skip** the default behavior:
`context.utils.skipDefaultBehavior = true`.

```ts
beforeCreateServerDockerComposeDB(
    context: DsgContext,
    eventParams: CreateServerDockerComposeDBParams
  ) {
    context.utils.skipDefaultBehavior = true;
    return eventParams;
  }
```

 As a result the`CreateServerDockerComposeDB` is not running and you would have to provide your logic in the `after` lifecycle event.
For that, you need to provide the path to your `docker-compose.db.yml` and set the path in which you want the `docker-compose.db.yml` will be generated.

```ts
  async afterCreateServerDockerComposeDB(context: DsgContext) {
    const staticPath = resolve(__dirname, "../static");
    const staticsFiles = await context.utils.importStaticModules(
      staticPath,
      context.serverDirectories.baseDirectory
    );

    return staticsFiles;
  }
```

### outputFileName

The file name of the docker-compose file, the default value is `docker-compose.yml` 

It is recommended not to change the file name unless specifically required and the impact is understood.

**Comment by abrl91** [comment]
@MoFoGo @yuval-hazaz please review

**Comment by yuval-hazaz** [comment]
@abrl91 I updated the outputFileName to docker-compose.db.yml
please review

**Comment by abrl91** [comment]
> @abrl91 I updated the outputFileName to docker-compose.db.yml please review

Yep. Side effect of copy&paste 😅

**Comment by MoFoGo** [comment]
Will now move to the docs and include in PR.
