### ISSUE TITLE
Docs: Plugin Events Article - CreateAdminModules

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4113]
### Describe the issue with documentation

This event needs to be included in the docs.

### How to solve the problem

Create an article describing the Plugin Event. 

## The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

## For reference, the Plugin Events tree is shown here:

https://www.notion.so/amplication/Plugins-Events-bbb45d7062c64c5ba5dcfba3fa0bcb4b

**Comment by abrl91** [comment]
# Create Admin Modules

## Description

Creates the Admin UI

## Event Name:
`CreateAdminModule`

## Event Params
This event doesn't have unique event params

```tsx
export interface CreateAdminModulesParams extends EventParams {}
```

**Example**
There is no relevant example yet

**Comment by abrl91** [comment]
@yuval-hazaz isn't it preferable to rename all the events that contain the suffix `modules` before writing the docs?

**Comment by yuval-hazaz** [comment]
yes, we need to do that 
It will be very easy to update the docs, but it will be much more complicated to update the plugins as we move forward. 
so, let do it ASAP.  I  will open an issue

**Comment by yuval-hazaz** [comment]
I created this issue https://github.com/amplication/amplication/issues/4158
