### ISSUE TITLE
Docs: Update FAQs with Microservices and Plugins 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4114]
### Describe the issue with documentation

The FAQs do not include descriptions of Microservices and Plugins 

### How to solve the problem

Add Microservices and Plugins to the FAQs article

**Comment by imjaglan** [comment]
I would like to contribute on this issue, can you please assign me this

**Comment by ShabanaNaik** [comment]
_@MoFoGo_ I would like to contribute to this.
Please let us know if this issue is open for others to contribute and can be added as a Hactoberfest event.

**Comment by Souvik2024** [comment]
Hey, @MoFoGo , I would like to contribute to this issue. Could you please assign me this?

**Comment by souravjain540** [comment]
@imjaglan assigned it to you!

**Comment by prakhar-198** [comment]
Hey! if the issue is still not fixed..Please can you assign me..I'll fix it! @souravjain540

**Comment by DEBOBANI** [comment]
@MoFoGo, I would like to contribute to this issue. Can you please assign this to me?

**Comment by souravjain540** [comment]
@imjaglan are you working on this or I will assign it to someone else.

**Comment by souravjain540** [comment]
Assigning it to @ShabanaNaik

**Comment by ShabanaNaik** [comment]
> Assigning it to @ShabanaNaik

Thank you for the opportunity. 
I would like to know if you have any additional info regarding the FAQ ?

**Comment by yuval-hazaz** [comment]
@ShabanaNaik you probably need to wait for @MoFoGo to provide you with the content.

**Comment by ShabanaNaik** [comment]
> @ShabanaNaik you probably need to wait for @MoFoGo to provide you with the content.

Okay 👍👍. But other than that are there any other docs I should look into? Right now I am reading through what is already present on your website and here at GitHub.

**Comment by yuval-hazaz** [comment]
see this https://docs.amplication.com/docs/faqs/faqs/faqs/

**Comment by ShabanaNaik** [comment]
I have already gone through the FAQ. But I will go through them once again and compare the questions with what I have learnt so far about the application and let you know.

**Comment by Ratheshan03** [comment]
@souravjain540 , @yuval-hazaz , can I work on this issue since there's no new updates recently.

**Comment by MoFoGo** [comment]
@ShabanaNaik - are you still interested in working on this?

**Comment by ShabanaNaik** [comment]
@MoFoGo  Yes. By tomorrow i will make a pr .

**Comment by ShabanaNaik** [comment]
I have a draft of the questions i think should be added. Before i make a pull request should i get them verified from you ?

**Comment by ShabanaNaik** [comment]
Updated FAQ's with Microservices and plugins #209
