### ISSUE TITLE
Change the type of Kafka brokers env variable

### ISSUE THREAD

**Issue by shaharblanksela** [amplication/amplication#4116]
### Feature description

Change KAFKA_BROKERS env variable from 'list' to 'string' type.
This change will do inside:

- [x] All Helm-chart values files where KAFKA_BROKERS is written.
- [x] The code itself.

### Use case

As part of the helm-charts improvement, the environment variable 'KAFKA_BROKERS' will be changed to string type, so that in the future we can pass the variable as a reference and not manually.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Vipul2504** [comment]
Hello, do I need to just change the data type list to string? or anything I have to do please let me know

**Comment by yuval-hazaz** [comment]
@Vipul2504 thanks for your support. 
This issue is already handled by the core team
