### ISSUE TITLE
🐛 Bug Report: Inconsistent event name - all event names should start with a capital letter

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4147]
### What happened?

Inconsistent event name - all event names should start with a capital letter

### What you expected to happen

```ts
export enum EventNames {
  CreateEntityController = "CreateEntityController",
  CreateEntityControllerBase = "CreateEntityControllerBase",
  CreateAuthModules = "createAuthModules",                    <= should be CreateAuthModules
  CreateAdminModules = "createAdminModules",                  <= should be CreateAdminModules
  CreateServer = "CreateServer",
  CreateServerAppModule = "CreateServerAppModule",
  CreateServerDotEnv = "CreateServerDotEnv",
  ...
}
```

### How to reproduce

go to `packages/amplication-code-gen-types/src/plugins-types.ts` lines 62-63

### Amplication version

1.0.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by cack195** [comment]
is this issue resolved?
If not, I would like to work on this issue.

**Comment by octopols** [comment]
> is this issue resolved? If not, I would like to work on this issue.

I just checked the repo, it looks like it's resolved.

**Comment by cack195** [comment]
Oh ok
Cool then
