### ISSUE TITLE
Prevent autogeneration from nested routes from relation fields without touching the base folders

### ISSUE THREAD

**Issue by vincenzodomina** [amplication/amplication#4150]
### Feature description

Prevent autogeneration from "nested" routes from relation fields without touching the base folders

### Use case

How do I best prevent unused routes from being generated or at least "unexpose" to the API documentation without touching the base folders? 

For now I only delete the controller methods everytime i merge an amplication PR, but that feels like there should be a better way.

For example:
I added a field "created_users" to my user entity with relation to the user entity itself, so that i can save the users that this "admin" user has created. But I don't want additional routes from being generated or at least not to expose the additional generated routes for "created_users" in my API spec:

![image](https://user-images.githubusercontent.com/54762917/195564875-221291d3-96ce-4451-83a5-932911c2ffb1.png)

Thanks for all your great work!

Support from @abrl91 for a current approach:
- if you do need the REST routes but you just don't want the all CRUD operations you can turn it off on every entity: go to the entity page (for example: Order), there you will find a tab called 'permissions' where you can turn off which operation you want
- you can also set the methods as private and then use the .amplicationignore to make sure we will not override your code the next time you sync your code with Amplication 
https://docs.amplication.com/docs/custom-code/managing-custom-files/

**Comment by fumblehool** [comment]
Hello @vincenzodomina I would love to work on this issue.
Can you please assign me this issue if nobody is currently working on it.
Thanks :)

**Comment by souravjain540** [comment]
Hi @vincenzodomina, thank you so much for making this feature request.

Please validate this issue @yuval-hazaz @abrl91 and @fumblehool will like to work on it.

**Comment by abrl91** [comment]
LGTM. The product needs to prioritize the task

**Comment by yuval-hazaz** [comment]
@vincenzodomina thanks for opening this feature request. I can understand the need and gree that we should look into implementing this behaviour out of the box. 

@fumblehool thanks for your interest to work on this issue, but we first need to decide on a design to the solution. 
We may want to add some configuration per field, or maybe create a new page to manage all the routes, or we may come up with a third solution.

@GreenMachine01 and the product team will take it from here to create the design.

**Comment by yuval-hazaz** [comment]
This feature is now available in the API tab, where the developer can enable and disable specific endpoints

@vincenzodomina thanks for the sending the request

**Comment by vincenzodomina** [comment]
Great work, thank you 🙏
