### ISSUE TITLE
🐛 Bug Report: wrong color of the horizontal line when having a hover on the resource card 

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4152]
### What happened?

wrong color of the horizontal line when having a hover on the resource card 

https://user-images.githubusercontent.com/39680385/195786208-86ffacf8-d90e-4cf4-b6e1-a4afc356607c.mov

### What you expected to happen

I expect it to behave like on the commits page

### How to reproduce

see in the video

### Amplication version

1.0.2

**Comment by SaumyaBhushan** [comment]
I want to work on this issue Can you please guide me How can I make the required changes?

**Comment by abrl91** [comment]
> I want to work on this issue Can you please guide me How can I make the required changes?

You can take a look at the commits page and see how it was implemented there. Let me know if you need more help

**Comment by HeyItsShubhamKale** [comment]
Hey ,can you assign this issue to me, I'd like to work on it

**Comment by yuval-hazaz** [comment]
This issue was resolved in https://github.com/amplication/amplication/pull/4086 so we can close it 
Thanks @HeyItsShubhamKale for your support. please let us know if you want to work on any other issue

**Comment by HeyItsShubhamKale** [comment]
Ok great!

**Comment by HeyItsShubhamKale** [comment]
Yes I would love to work on other issues,can you assign me some

**Comment by yuval-hazaz** [comment]
@HeyItsShubhamKale have a look at this query, and comment on any issue you can work on
https://github.com/amplication/amplication/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee
