### ISSUE TITLE
Docs: update screenshots

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4153]
### Describe the issue with documentation

There are a couple of pages where the screenshots are out of date:
- The generated service: the Admin screenshot
- Create your first service: the "App Overview" page is now the "Service Overview," and the side menu looks different (in all steps, the screenshot should be updated)
- Run your service on a development environment: 
   - step 1: there is no sandbox and docker container
   - step 7: the admin-ui screenshot

### How to solve the problem

Take screenshots and update the docs

**Comment by A-Scratchy** [comment]
I would like to work on this if it's available please :-)

**Comment by abrl91** [comment]
@A-Scratchy I assigned you. Good luck 😃

**Comment by utkershrajvenshi** [comment]
Hi @abrl91 . Can I work on this one too?

**Comment by ShivamAgarwal-code** [comment]
Can I work on this too?

**Comment by A-Scratchy** [comment]
@abrl91 what branch would you like the PR to target??

**Comment by abrl91** [comment]
> @abrl91 what branch would you like the PR to target??

`next`

**Comment by A-Scratchy** [comment]
PR submitted https://github.com/amplication/docs/pull/204

Thanks :-)

**Comment by yuval-hazaz** [comment]
@A-Scratchy thhanks for your support.
you can see a preview of the updated version here https://deploy-preview-204--xenodochial-knuth-724ea9.netlify.app/docs/first-app/

@MoFoGo will review the PR soon and will merge it once approved

**Comment by HeyItsShubhamKale** [comment]
@yuval-hazaz I would like to work on this issue there are some screenshots missing!

**Comment by yuval-hazaz** [comment]
this is already handled. 
if there are other missing screenshots, please open a new issue with the details and I will assign it to you
thanks

**Comment by RayotiKar** [comment]
I'd like to work on it if it's available please :).

**Comment by abrl91** [comment]
> I'd like to work on it if it's available, please let me know asap.

already handled
