### ISSUE TITLE
🐛 Bug Report: remove the word `Module` from event names 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4158]
### What happened?

We currently use the word Module for some events in a confusing way. 
In the event `CreateEntityModule` we actually create the NestJS module for the entity - so the name is relevant.

but, in the event `CreateAuthModules` the name is confusing, and we should not use the word Module in the event name

>note: the word Module is used in the DSG to describe a generated file - but we should not expose that to the events because it will be too confusing 

### What you expected to happen

rename the following events:

- CreateAuthModules -> CreateServerAuth
- CreateAdminModules -> CreateAdminUI

Also note that the string value for these two events is written with a lower case "c" and it should be upper case like all other events.

When making these changes, we need to update the plugins that already using these events. 

```diff
export enum EventNames {
  CreateEntityController = "CreateEntityController",
  CreateEntityControllerBase = "CreateEntityControllerBase",
- CreateAuthModules = "createAuthModules",
- CreateAdminModules = "createAdminModules",
+ CreateServerAuth = "CreateServerAuth",
+ CreateAdminUI = "CreateAdminUI",
  CreateServer = "CreateServer",
  CreateServerAppModule = "CreateServerAppModule",
  CreateServerDotEnv = "CreateServerDotEnv",
  CreateMessageBroker = "CreateMessageBroker",
  CreateMessageBrokerTopicsEnum = "CreateMessageBrokerTopicsEnum",
  CreateMessageBrokerNestJSModule = "CreateMessageBrokerNestJSModule",
  CreateMessageBrokerClientOptionsFactory = "CreateMessageBrokerClientOptionsFactory",
  CreateMessageBrokerService = "CreateMessageBrokerService",
  CreateMessageBrokerServiceBase = "CreateMessageBrokerServiceBase",
  CreateEntityService = "CreateEntityService",
  CreateEntityServiceBase = "CreateEntityServiceBase",
  CreateServerDockerCompose = "CreateServerDockerCompose",
  CreateServerDockerComposeDB = "CreateServerDockerComposeDB",
  CreatePrismaSchema = "CreatePrismaSchema",
  CreateServerPackageJson = "CreateServerPackageJson",
  CreateEntityModule = "CreateEntityModule",
  CreateEntityModuleBase = "CreateEntityModuleBase",
}
```

### How to reproduce

n/a

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4161
