### ISSUE TITLE
Add `prettierrc` file in `amplication-site` repo

### ISSUE THREAD

**Issue by akshitarora921** [amplication/amplication#4160]
### Feature description

Add prettier config file. So that It is easy to collaborate.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Khushal-ag** [comment]
yes i am willing to submit a PR

**Comment by MichaelSolati** [comment]
Valid issue but I'm a little too opinionated on this and would want to handle this myself.
