### ISSUE TITLE
🐛 Bug Report: npm audit reports Dicer vulnerabilty 

### ISSUE THREAD

**Issue by DanielMenke** [amplication/amplication#4162]
### What happened?

just installed the dependencies for my first amplification build and was greeted with this message for 
`npm audit`

`
dicer  *
Severity: high
Crash in HeaderParser in dicer - https://github.com/advisories/GHSA-wm7h-9275-46v2
fix available via `npm audit fix --force`
Will install @nestjs/core@7.5.5, which is a breaking change
node_modules/dicer
  busboy  <=0.3.1
  Depends on vulnerable versions of dicer
  node_modules/busboy
    multer  <=2.0.0-rc.3
    Depends on vulnerable versions of busboy
    node_modules/multer
      @nestjs/platform-express  *
      Depends on vulnerable versions of @nestjs/core
      Depends on vulnerable versions of multer
      node_modules/@nestjs/platform-express
        @nestjs/core  >=7.6.0-next.1
        Depends on vulnerable versions of @nestjs/platform-express
        node_modules/@nestjs/core
          @nestjs/graphql  >=8.0.0
          Depends on vulnerable versions of @nestjs/core
          node_modules/@nestjs/graphql
          @nestjs/swagger  >=5.0.9
          Depends on vulnerable versions of @nestjs/core
          node_modules/@nestjs/swagger
          @nestjs/testing  >=7.6.0-next.1
          Depends on vulnerable versions of @nestjs/core
          Depends on vulnerable versions of @nestjs/platform-express
          node_modules/@nestjs/testing
        nestjs-prisma  0.13.0-dev.0 - 0.18.0
        Depends on vulnerable versions of @nestjs/platform-express
        node_modules/nestjs-prisma`
       
This is the advisory page on github: https://github.com/advisories/GHSA-wm7h-9275-46v2

### What you expected to happen

That amplification uses a nest-version without known vulnerabilities

### How to reproduce

run npm audit in a fresh build 

### Environment

Node version: 16.13.0
NPM version: 8.19.2

**Comment by yuval-hazaz** [comment]
thanks @DanielMenke for reporting this issue
can you share a link to a repo with the generated code so we can try to reproduce the error?

**Comment by DanielMenke** [comment]
@yuval-hazaz https://github.com/DanielMenke/recep

I did not modify anything, so this might occur with every newly built project

**Comment by yuval-hazaz** [comment]
@abrl91 can you please have a look at this and share your findings?

**Comment by abrl91** [comment]
> @abrl91 can you please have a look at this and share your findings?

Sure. I'll check that.

**Comment by abrl91** [comment]
related issue: https://github.com/amplication/amplication/issues/4204

**Comment by souravjain540** [comment]
@abrl91 if this issue is similar can we close?

**Comment by abrl91** [comment]
@souravjain540 similar, don't close it yet

**Comment by abrl91** [comment]
Can't reproduce this error.
Regarding the `npm audit` error - duplicate of #4204
