### ISSUE TITLE
Link to Code of Conduct broken

### ISSUE THREAD

**Issue by MichaelSolati** [amplication/amplication#4164]
### Describe the issue with documentation

The link to the code of conduct on [`docs/contributing/`](https://docs.amplication.com/docs/contributing/#code-of-conduct) is broken.

It should point to here => https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md

### How to solve the problem

Update the link to https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md

**Comment by akshitarora921** [comment]
Can I take this @MichaelSolati

**Comment by souravjain540** [comment]
> Can I take this @MichaelSolati 
> 
> 

Yes, assigned:)
