### ISSUE TITLE
🐛 Bug Report: Navbar menu does not collapse after clicking in Mobile

### ISSUE THREAD

**Issue by devXprite** [amplication/amplication#4174]
### What happened?

Navbar menu does not collapse after clicking nav links.  This means that the menu remains expanded and therefore covers the content.

https://user-images.githubusercontent.com/80192140/196086064-ca9754a8-2bed-4a97-aa1b-deab65982fad.mp4

### What you expected to happen

https://user-images.githubusercontent.com/80192140/196085806-a2925c40-22cb-4ff6-8f45-c3af20f2b3d2.mp4

### How to reproduce

1. Open https://amplication.com in mobile
2. Open NavBar and click on any link

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MichaelSolati** [comment]
Moving forward @devXprite, please wait for a member of the team to accept the issue and assign it to you.
