### ISSUE TITLE
🐛 Bug Report: Navbar Y-axis Overflow

### ISSUE THREAD

**Issue by devXprite** [amplication/amplication#4175]
### What happened?

https://user-images.githubusercontent.com/80192140/196122223-bff6ebd9-248f-4860-8f69-e71ab5a3a962.mp4

### What you expected to happen

There should be no scrollbar in NavBar.

### How to reproduce

 1. Open http://amplication.com/
 2. Click on any link in nav bar if it works fine then click again.

### Amplication version

v1.0.2

### Environment

**user-agent:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
**Browser:** Chrome
**OS:** Parrot OS (Linux)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@MichaelSolati please validate this issue

**Comment by Sarveshk76** [comment]
Can I work on it? It appears when we click on features and pricing

**Comment by devXprite** [comment]
> Can I work on it? It appears when we click on features and pricing

NO actually appears in every even click and i think it's because of transition.
