### ISSUE TITLE
Adding Resolver

### ISSUE THREAD

**Issue by 0xSebin** [amplication/amplication#4178]
### Feature description

Adding a resolver would be really useful.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
can you elaborate the feature?

**Comment by yuval-hazaz** [comment]
@0xSebin this issue is missing enough details so we will not be able to handle it. 
please feel free to open a new issue with more details 
I will close this issue for now
