### ISSUE TITLE
🐛 Bug Report: Docker build fails with Cloud Build: Error: When using COPY ... must end with a /

### ISSUE THREAD

**Issue by vincenzodomina** [amplication/amplication#4188]
### What happened?

Using Cloud build the Docker build process fails with the following error:

Step 17/19 : COPY --from=base /app/tsconfig* .
When using COPY with more than one source file, the destination must be a directory and end with a /
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1

This issue is related to https://github.com/amplication/amplication/issues/3914

I could find the solution explained [in this Stackoverflow thread](https://stackoverflow.com/questions/53650492/when-using-copy-with-more-than-one-source-file-the-destination-must-be-a-direct)

Adding a slash in the end worked for me to not fail the build.
So the proposed solution is to generate a Dockerfile with
`COPY --from=base /app/tsconfig* ./`
instead of
`COPY --from=base /app/tsconfig* .`

### What you expected to happen

The Docker build should not fail

### How to reproduce

- Setup a Cloud Build trigger connection with the github repo used for the amplication generated app
- commit a change to main branch (essentially run the command: docker build .)

### Amplication version

1.0.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
thanks for the PR @vincenzodomina 

team will review it soon

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4189
