### ISSUE TITLE
🐛Bug Report: Scroller shows up on the Login button after navigating between tabs

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4200]
**Description:**
A scroll bar shows up over the login button after I navigated between tabs

**Actual:**
![Image](https://user-images.githubusercontent.com/112330500/196736732-d4eefbe8-0fd9-4f9c-abaa-dd929e9adb0f.png)

**Expected:**
No scroll bar over the button

**Comment by OmiCoding** [comment]
Hey I would like to work on this issue.

**Comment by abrl91** [comment]
> Hey I would like to work on this issue.

I assigned you. Gook luck!

**Comment by OmiCoding** [comment]
I believe someone worked on this bug in issue #4175, and the pull request amplication/amplication-site#244
