### ISSUE TITLE
🐛 Bug Report: JWT plugin installation - unexpected behavior

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4201]
### What happened?

JWT plugin installation - unexpected behavior: when a user installs the JWT plugin the PR looks as follows:

![Screen Shot 2022-10-19 at 18 46 15](https://user-images.githubusercontent.com/39680385/196741039-7105ffbe-776d-4670-b678-4383ef887a04.png)

### What you expected to happen

Given that the default auth strategy is using JWT, the only change that I expect is the swagger version.
The order of the import in `server/src/auth/base/token.service.base.ts` should be the same, as well as the absence of  the `ts-ignore` comments (should not be generated in the first place)

### How to reproduce

- generate an app
- sync with GitHub
- create and merge the pull request
- go to Amplication dashboard and install the JWT plugin
- click on build
- see the new pull request

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abrl91** [comment]
When we install the `base-auth` plugin, the `ts-ignore` comment is added in `server/src/tests/auth/jwt/jwt.strategy.spec.ts`
![image](https://user-images.githubusercontent.com/39680385/196756637-b1e41b0d-6afd-46d8-84eb-e99e34c36601.png)

**Comment by arielweinberger** [comment]
Tested it and confirming it was fixed:


![Image](https://user-images.githubusercontent.com/4976416/201533622-7a7e9fe4-6a1d-43bc-9053-7b7523a9566d.png)
