### ISSUE TITLE
🐛 Bug Report: `CommitListItem` - width and padding problems

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4211]
### What happened?

1. The padding on hover (the first item) and the selected item (the 4th item) should have the same width
2. the padding-right should be smaller
3. gap/padding/margin between the commit items
 
![Screen Shot 2022-10-20 at 10 30 23](https://user-images.githubusercontent.com/39680385/196936278-685bca75-ff91-4508-8970-cbca494f87c1.png)

### What you expected to happen

It should look like in entity page - the fields list
Example on this issue: https://github.com/amplication/amplication/issues/3933 

### How to reproduce

create a project with a service
click on build and go to the commits page
click on build again to see the hover effect and width differences 

### Amplication version

1.0.3

**Comment by vickywane** [comment]
Hi, 

I can fix this

**Comment by abrl91** [comment]
> Hi,
> 
> I can fix this

First come first served 😃 
I assigned you

**Comment by vickywane** [comment]
I'm working on this.

**Comment by chaiwattsw** [comment]
any update on this issue? if not I would like to take

**Comment by souravjain540** [comment]
@vickywane  any updates or can I assign it to @chaiwattsw

**Comment by vickywane** [comment]
No updates. 

I couldnt setup the system locally.

**Comment by aadrshkashyp** [comment]
No, Fix yet ..Let me handle this

**Comment by abrl91** [comment]
@chaiwattsw are you working on this issue?

**Comment by abrl91** [comment]
> No, Fix yet ..Let me handle this

@aadrshkashyp I'll assign you if @chaiwattsw is not working on this issue

**Comment by chaiwattsw** [comment]
Yep im working on it will send PR today

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4271
