### ISSUE TITLE
🐛 Bug Report: Missing gap between commit

### ISSUE THREAD

**Issue by TheLearneer** [amplication/amplication#4213]
### What happened?

The commit list is missing gap between two items when one is selected and the one just around it is hovered.

<img width="275" alt="Screen Shot 2022-10-20 at 6 23 44 PM" src="https://user-images.githubusercontent.com/23402178/196950721-cf074871-99f3-42c6-8cec-e211abd55378.png">

### What you expected to happen

There should be a gap of `8px` as most of the other items in other list have.

### How to reproduce

- Goto Amplication app
- Select a project
- Check commit list

### Amplication version

Latest web

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abrl91** [comment]
hey, @TheLearneer thank you but it is duplicated. See this isse #4211

**Comment by TheLearneer** [comment]
Ahh my bad, didn't realize it 🙇
