### ISSUE TITLE
🐛 Bug Report: Pending Changes doesn't update after deleting a Message Broker

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4214]
**Steps to Reproduce:**
1. Create a new Message Broker
2. Create a topic within the message broker
3. Delete the Message Broker via the Project Settings Page

**Expected:**
The Pending Changes area is updated and no longer shows the Message Broker Section

**Actual:**
The Message Broker with the created Topic are still shown in the Pending Changes area

**Comment by abrl91** [comment]
I think we already have this issue: https://github.com/amplication/amplication/issues/4154

**Comment by GreenMachine01** [comment]
@abrl91 thanks. yes, they are partially duplicate of one another.
I'll remove Scenario #2

**Comment by arielweinberger** [comment]
Confirming this has been fixed.
