### ISSUE TITLE
As User - I want a new Message Broker to have a Default Topic already set up for me

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4216]
**Overview:**
Similar to Services we want a new Message Broker to include an automatically generated default topic as we expect it will help developers to understand how to use it and save some steps which the developer will always do if he wants to use a Message Broker.

**Design Example:**

![Image](https://user-images.githubusercontent.com/112330500/196984306-e4868504-e6ae-460c-9b24-3f9b11c78215.png)

**Requirements:**

- [ ] When a new Message Broker is created add an auto-generated topic
    - [ ] Topic Display Name - "Topic 1"
    - [ ] Topic Name - "topic.1"
    - [ ] Topic Description - "An automatically created topic to be used with the Message Broker"

**Comment by ageddesi** [comment]
Hi, I would like to take this on if you will have me :) 👍

**Comment by Ahtritus** [comment]
Hey @GreenMachine01 I would like to work on this, could you please assign it to me?

**Comment by GreenMachine01** [comment]
@souravjain540 @arielweinberger please see if this item can be done by the community. if yes, we have @Ahtritus that wants to do it.

**Comment by GreenMachine01** [comment]
@Ahtritus assigned to you. Good luck!

**Comment by Ahtritus** [comment]
@GreenMachine01  The default value for Display Name - "Topic 1" is violating the pattern. The help text mentions `Name must only contain letters, numbers, dash, underscore or dot.` I'm changing it to "Topic_1"

**Comment by GreenMachine01** [comment]
@Ahtritus Let's go with "Topic1" for the Display Name
You can fix the issue you found within this ticket.

**Comment by GreenMachine01** [comment]
@arielweinberger why does a display name field have a restriction on using spaces in the text?

**Comment by Ahtritus** [comment]
I had a couple of observations with the current behavior and wanted to clarify them. Currently, when a user adds a new topic, the name they add is prefilled into the `Display Name` and `Name` and we get to see that when we open the topic. 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/53258966/197974673-27242cad-4bf2-462a-8f71-48f4daddd22f.png">


As per the issue created here, I understand that we don't want to have the `Name` and `Display Name` to be what they created the topic with but a default "**Topic1**". In this case, if the user doesn't change the default "Topic1" display name, they won't be able to create a new topic as it would say `"Another record with the same key already exist (resourceId, displayName)"`.
<img width="613" alt="image" src="https://user-images.githubusercontent.com/53258966/197976114-28ddf095-702b-4ace-b4e1-e77f051c6f9f.png">


Is this the expected behavior?
@GreenMachine01

**Comment by GreenMachine01** [comment]
@Ahtritus  think there was some confusion here so I'll try to explain what is expected. (I deleted some of my previous comments as I see they are not needed)

Currently, when you create a Message Broker and go to the "Topics" page you will have 0 Topics and you can start creating new ones in the input box.

![image](https://user-images.githubusercontent.com/112330500/197978077-a8569535-80ef-4e0c-825c-6969774eb956.png)

All this ticket is requesting is that instead of having 0 Topics the user will start with one Topic auto-created.
This "default" created topic should be set up with the values as requested in the issue description above.

This means that when a user creates a Message Broker and goes to the "Topics" page he should see this...
![image](https://user-images.githubusercontent.com/112330500/197979052-0238e25e-8250-4173-a5c2-294e23f227ea.png)

**Comment by Ahtritus** [comment]
> @Ahtritus think there was some confusion here so I'll try to explain what is expected. (I deleted some of my previous comments as I see they are not needed)
> 
> Currently, when you create a Message Broker and go to the "Topics" page you will have 0 Topics and you can start creating new ones in the input box.
> 
> ![image](https://user-images.githubusercontent.com/112330500/197978077-a8569535-80ef-4e0c-825c-6969774eb956.png)
> 
> All this ticket is requesting is that instead of having 0 Topics the user will start with one Topic auto-created. This "default" created topic should be set up with the values as requested in the issue description above.
> 
> This means that when a user creates a Message Broker and goes to the "Topics" page he should see this... ![image](https://user-images.githubusercontent.com/112330500/197979052-0238e25e-8250-4173-a5c2-294e23f227ea.png)

Got it, I had understood it a bit differently. Thanks for the clarification

**Comment by GreenMachine01** [comment]
See comments from Yuval on the PR to be implemented on the server side

**Comment by GreenMachine01** [comment]
@yuval-hazaz @abrl91 Why are we changing what was requested? if there is a technical reason please let me know.
This is the request:
![image](https://user-images.githubusercontent.com/112330500/208290875-08162721-2034-469c-8772-fa9799155dc2.png)

**Comment by yuval-hazaz** [comment]
> @yuval-hazaz @abrl91 Why are we changing what was requested? if there is a technical reason please let me know.

@GreenMachine01 I didn't notice that initially. The discussion about the change was whether to use the resource name or not in the topic name. 
We finally decided not to use it, just like you requested. But the name we used is closer to the format we expect the user to use with dot notations and version number `topic.sample.v1`

**Comment by GreenMachine01** [comment]
@yuval-hazaz ok. keep the name as you suggested :)
