### ISSUE TITLE
Enhancement: Workspace Header, without the User-Profile icon, should be visible in Profile Page

### ISSUE THREAD

**Issue by Ahtritus** [amplication/amplication#4225]
### Feature description

Currently, there is no Workspace Header present in the Profile Page. The only way a user can navigate out of the page is to click on the back button of the browser or type in the URL manually. If the workspace header was present, then it would be easier for the user to navigate.

### Use case

The result, along with the styling changes raised in issue #4224, would result in the Profile Page looking something like this.

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/53258966/197272803-676fd683-2336-4ee4-8726-5e14607d757d.png">

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Ahtritus** [comment]
@souravjain540 @yuval-hazaz Could you please assign this to me and I'll raise the PR?

**Comment by abrl91** [comment]
@alexbass86 @GreenMachine01

**Comment by abrl91** [comment]
@Ahtritus
Thank you for your suggestion. The product team will review it.

**Comment by abrl91** [comment]
@Ahtritus as the design of the user profile is a modal, this issue is not relevant.
See issue: https://github.com/amplication/amplication/issues/3596 (I assigned you to the issue)
