### ISSUE TITLE
Discord Button in Readme 

### ISSUE THREAD

**Issue by Anubhavdevv** [amplication/amplication#4226]
### Describe the issue with documentation

In the Readme file Discord button is there for joining the discord community of amplification clicking that it did not open in the new tab it opens in only the tab only so the user who clicks on it directly redirect to the invite screen but due to that the GitHub got closed and the user had to search again for the repository so the discord button should be open in new tab

### How to solve the problem

By targeting the value to the new page

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Anubhavdevv** [comment]
Kindly assign this issue to me !

**Comment by abrl91** [comment]
> Kindly assign this issue to me !

Good luck :)

**Comment by Anubhavdevv** [comment]
Thank You it would be great if you could assign it to me under Hacktoberfest Label !

**Comment by Dojeto** [comment]
@Anubhavdevv hey, can you please give this chance to me it will help me a lot :)

**Comment by ridays2001** [comment]
Is anyone working on this?

**Comment by abrl91** [comment]
> Is anyone working on this?

yes. @Dojeto is working on this issue

**Comment by Dojeto** [comment]
Hey @abrl91 I was trying to solve this issue, I google about it and I found that GitHub doesn't allow to change a default target behavior
GitHub has two types of markdown processors GFM and KRANDOWN.
Krandown supports changing default target behavior but, we can't use it in a README.MD.
This is what is got to know by doing this research, maybe there is no way to solve this issue, or perhaps I failed to figure it out :)

**Comment by ridays2001** [comment]
Here's a hint for you - GitHub markdown processor also supports HTML.

**Comment by Dojeto** [comment]
> Here's a hint for you - GitHub markdown processor also supports HTML.

@ridays2001 ik that, i tried target="_blank" but it's not working kindly if you know another way then help me :)

**Comment by DynamiteC** [comment]
@abrl91 @joebowbeer @Anubhavdevv @ridays2001 @Dojeto GFM would never support target="_blank" due to security reasons. [Since 2012 ](https://github.com/mojombo/github-flavored-markdown/issues/28) people are trying to add that but github wont allow.

**Comment by abrl91** [comment]
Thank you @DynamiteC

**Comment by abrl91** [comment]
> @Anubhavdevv please assign this to me. I shall give it a try and submit it 1 hour

@mathagician I assigned you

**Comment by developerSuranjan** [comment]
@abrl91 kindly assign this to me :)

**Comment by souravjain540** [comment]
> @abrl91 kindly assign this to me :)

@mathagician is working on it.

**Comment by weblearner07** [comment]
Please assign me this issue , I can work on it.

**Comment by Aashutoshbro** [comment]
I would like to do the task

**Comment by souravjain540** [comment]
@mathagician are you working on this?

**Comment by yuval-hazaz** [comment]
@weblearner07 please let us know if you made any progress or not. 
I dont think we can fix this issue, and if this is the case we can keep it the way it is right now and close this issue

**Comment by Spid3rrr** [comment]
It seems this feature is intentionally disabled in Github Markdown to avoid security flaws.

**Comment by aaaaayushh** [comment]
Would it not be better to instead copy the discord link to the user's clipboard and show them the same in a toast or something similar instead of redirecting them to discord? If this feature seems feasible I would love to work on it.

**Comment by souravjain540** [comment]
> Would it not be better to instead copy the discord link to the user's clipboard and show them the same in a toast or something similar instead of redirecting them to discord? If this feature seems feasible I would love to work on it.

I think better option is to redirect them not just copying the link.

**Comment by aaaaayushh** [comment]
Yes but github markdown doesn't allow opening a link in a new tab right? Opening discord and closing github seems like it would be a little annoying for the user

**Comment by rielAsh24** [comment]
Hey! I'm interested in working on this issue and would like to request that you assign it to me.

**Comment by msboffl** [comment]
Hi, Could you please assign this to me, i will work

**Comment by VaibhavTalkhande** [comment]
Hey can I you assigned this issue to me
I want to work on it

**Comment by NehaL-8** [comment]
Hii I would like to resolve this.

**Comment by yuval-hazaz** [comment]
Closing since the requested behavior is not supported by GitHub
