### ISSUE TITLE
Removing GCP environment variables from code

### ISSUE THREAD

**Issue by shaharblanksela** [amplication/amplication#4230]
### Feature description

As part of refactoring the helm charts, I came across unnecessary variables that are no longer needed, such as inside amplication-server: 

    #GCP - APPS Builder
    DEFAULT_DISK: 
    LOCAL_DISK_ROOT: 
    CONTAINER_BUILDER_DEFAULT: 
    GCS_BUCKET:

    #GCP - APPS Deployer
    DEPLOYER_DEFAULT: gcp

    GCP_APPS_PROJECT_ID: 
    GCP_APPS_REGION: 
    GCP_APPS_TERRAFORM_STATE_BUCKET: 
    GCP_APPS_DATABASE_INSTANCE: 
    GCP_APPS_DOMAIN: 

    DOCKER_HOST: 
----

### Use case

The goal is to remove the unnecessary env vars first from the code and then inside the helm chart. 
Currently, the helm chart needs these variables for the application to run.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by samarth777** [comment]
can you assign this to me

**Comment by yuval-hazaz** [comment]
@arielweinberger is this issue open to the community?

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4455
