### ISSUE TITLE
Update the instruction text on the Service Dashboard

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4231]
![Image](https://user-images.githubusercontent.com/112330500/197544879-637a02cc-2786-4bdc-b66a-ae8f5d358ecd.png)

**Overview:**
We no longer want to support the ability to download the code directly from the Amplication platform. So to improve onboarding we need to update our instruction text and remove mentioning "download the code"

**Requirements:**

- Update the text marked by the red box
     - New text - "Your Amplication-generated resource is ready. We created it using amazing open-source technologies. Push the auto-generated code to GitHub and take it to the moon with your coding skills."

**Comment by Abubakrce19** [comment]
Please assign me this, I can do this!
Thank you!!
@GreenMachine01

**Comment by GreenMachine01** [comment]
@abrl91 @souravjain540 FYI. please assign if the community can do it.

**Comment by GreenMachine01** [comment]
@Abubakrce19 assigned to you. Thanks!

**Comment by mathagician** [comment]
I would like to take the issue. Please assign this to me. I shall give it now.

**Comment by Abubakrce19** [comment]
> @Abubakrce19 assigned to you. Thanks!
Already Started working!

Thank you

**Comment by mathagician** [comment]
PR created https://github.com/amplication/amplication/pull/4232

**Comment by Abubakrce19** [comment]
@GreenMachine01 
PR created #4233
Please review it.
Thank you!!

**Comment by Abubakrce19** [comment]
@GreenMachine01 
Please merge #4233 so we can close this issue.
Thank you!!

**Comment by GreenMachine01** [comment]
@abrl91 FYI

**Comment by GreenMachine01** [comment]
Confirmed fix.


![Image](https://user-images.githubusercontent.com/112330500/201518834-6dd8bb80-2e4c-416d-8b41-45051eba6be7.png)
