### ISSUE TITLE
🐛 Bug Report: Page cuts off when clicking on roadmap nav link

### ISSUE THREAD

**Issue by OmiCoding** [amplication/amplication#4237]
### What happened?

I noticed when I clicked on the roadmap navigation link it causes the page to get cut off at the top when scrolling back up, or clicking on the logo link. This happens when resolution width size is greater than 991px.

![frontend-issue-1](https://user-images.githubusercontent.com/43274676/197651025-62ec2ac5-a34a-4ddc-aa56-11a18cbddda0.PNG)

Footer is extended much more than it's supposed to be.

![frontend-issue-2](https://user-images.githubusercontent.com/43274676/197651147-74dffbba-e607-4fb5-af23-714b70dc84a5.PNG)

Going to a different section listed in the navbar also shows this issue.

![frontend-issue-3](https://user-images.githubusercontent.com/43274676/197651471-3cba05d2-b2d1-4bf4-b655-af6b56626b2b.PNG)

### What you expected to happen

I expect the top not to be cut off.

![image](https://user-images.githubusercontent.com/43274676/197651710-891090c0-cad8-4d4d-b353-0f5edb846883.png)

The footer not to be extended out.

![expected-01](https://user-images.githubusercontent.com/43274676/197652028-8dd2081e-309c-4bd2-97aa-205a19257724.PNG)

### How to reproduce

Either on Chrome or Firefox, your browser width should be greater than 991px. Click on the roadmap link from either the `home`, `features`, `priceing`, `team`, and `blog` routes.

### Amplication version

v1.0.3

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@abrl91 please review the issue and attached PR.

Thanks @OmiCoding for reporting the issue
