### ISSUE TITLE
🐛 Bug Report: Button.scss doesn't exist

### ISSUE THREAD

**Issue by KlausMikhaelson** [amplication/amplication#4244]
### What happened?

In the path `amplication\packages\amplication-design-system\dist\components\Button\Button.d.ts` on the 4th line i.e. `import "./Button.scss";` this imported file doesn't exist

<img width="367" alt="image" src="https://user-images.githubusercontent.com/100528412/197759530-d4cbcaf6-347e-4511-8add-6ca93351e006.png">

### What you expected to happen

maybe redirect to the file if there was any 

### How to reproduce

just navigate to the path above and than do a `ctrl + click` 

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@abrl91  please validate the issue/

**Comment by abrl91** [comment]
@souravjain540 @KlausMikhaelson 
This is in the dist folder, meaning it is after the code is compiled (`npm run build`).
You can't change the code in the dist file and open a PR with this change. It won't work.
 
We know that something is wrong with this package and the team is working on fixing the issues.
