### ISSUE TITLE
Refactor `amplication-git-pull-service` to follow our coding conventions

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4259]
Aligned `amplication-git-pull-service` with code conventions
documents:
[Module & Folder Structure](https://www.notion.so/amplication/Module-Folder-Structure-e9393fbe2be54cefa1739c35faec6c24)
[File & Declaration Naming](https://www.notion.so/amplication/File-Declaration-Naming-666afe407ff14ed6aa54bcd3dead45a8)

**Comment by MAX-786** [comment]
hey @abrl91 , I would like to contribute to this project can you assign this to me?

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4263
