### ISSUE TITLE
🐛 Bug Report: Roadmap Heading Misaligned on 606-767 screen width.

### ISSUE THREAD

**Issue by ShaneMaglangit** [amplication/amplication#4268]
### What happened?

The roadmap heading is misaligned on screen width >606 and <767.

![image](https://user-images.githubusercontent.com/53674742/198210222-a80e64ca-c10e-44bf-9bb2-aa057f4d7dc7.png)

### What you expected to happen

Ideally, it should remain consistently aligned with the other elements.

![image](https://user-images.githubusercontent.com/53674742/198210165-4290baf6-7448-4777-8f0e-1e49f39b0c3f.png)

### How to reproduce

Open the landing page with a screen width of 606-767.

### Amplication version

Latest

### Environment

Browser: Chrome
OS: Windows

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ShaneMaglangit** [comment]
@MichaelSolati Hey, here is the PR for https://github.com/amplication/amplication-site/pull/234

**Comment by souravjain540** [comment]
<img width="1000" alt="Screenshot 2022-10-28 at 11 13 41 AM" src="https://user-images.githubusercontent.com/53312820/198511883-0a190436-6214-4939-bf31-759dd297003b.png">
I can't see this misalignment?

**Comment by ShaneMaglangit** [comment]
> <img alt="Screenshot 2022-10-28 at 11 13 41 AM" width="1000" src="https://user-images.githubusercontent.com/53312820/198511883-0a190436-6214-4939-bf31-759dd297003b.png">
> 
> I can't see this misalignment?

I don't think you're viewing it within the specified width range. At 606-767, you should definitely have the hamburger menu instead of the full navbar.

**Comment by MichaelSolati** [comment]
fixed by amplication/amplication-site#234
