### ISSUE TITLE
Add Description of Routes and Entity properties to the REST-API Documentation

### ISSUE THREAD

**Issue by vincenzodomina** [amplication/amplication#4278]
### Feature description

Add the Description of Routes and Entity properties to the REST-API Documentation (which are entered in the Amplication-UI) automatically with the Amplication build

### Use case

I as a developer want to see the descriptions of the Routes ant entity properties in the REST-API document.

With @swagger.ApiBody() these can be autogenerated when fed with the entered Text from the UI.

[See References and examples](https://stackoverflow.com/a/70215322/14014558)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@arielweinberger please validate this issue and @vincenzodomina will like to submit a PR :)

**Comment by yuval-hazaz** [comment]
@vincenzodomina I like that and I think it should be easy to implement using a new plugin that will add the relevant description to each of the endpoints 

@GreenMachine01 let's add this as an idea to a plugin

I think I would like to take this as a personal project to test the plugin's infrastructure and docs, so I will assign myself and let's hope I will find the time soon :-)

**Comment by GreenMachine01** [comment]
@yuval-hazaz @vincenzodomina Created this request as a new idea for a plugin - https://github.com/amplication/amplication/issues/4322

**Comment by yuval-hazaz** [comment]
hi @kiptoomm thanks for checking up on it.
Unfortunately, I didn't start working on it.

Is that something you are waiting for?

**Comment by kiptoomm** [comment]
> 

@yuval-hazaz yessir, i was hoping to see this feature ASAP so i don't have to manually describe my entity fields on the swagger docs

**Comment by yuval-hazaz** [comment]
Thanks for sharing @kiptoomm 
we will see how we can include this in one of the next sprints.

**Comment by EugeneTseitlin** [comment]
@barshimi Please, assign PR to the issue.

**Comment by yuval-hazaz** [comment]
@barshimi this item passed review, but in order to proceed we need to publish it to npm add to the catalog
