### ISSUE TITLE
🐛 Bug Report: When you have 2 Message Brokers and you activate the second one within a service the display changes to show the first message broker

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4283]
**Description:**
When attempting to activate the Message Broker on the bottom of the list the display is automatically changed to show the Message Broker at the top of the list.

![Image](https://user-images.githubusercontent.com/112330500/198888656-25d13797-4dce-4cc5-a819-78e046fccf0f.png)

After turning the Message Broker ON the display is changed to show the first message broker

![Image](https://user-images.githubusercontent.com/112330500/198888686-5afca818-6c65-468a-adef-78ec927f02d1.png)

Notice - the same problem exists when you turn off the Message Broker
Notice - the same problem exists when you make a change in the 'message pattern' within a topic

**Steps to Reproduce:**

1. Create a project
2. Create a service within the project
3. Create a message broker within the project - "Broker1"
4. Create several dummy topics within "Broker1"
5. Create another message broker within the project - "Broker2"
6. Create several dummy topics within "Broker2"
7. Go to the service page and to the 'Connections' area
8. Select the message broker which is at the bottom of the list
9. Notice you are now viewing the message broker and the topics within it
10. Click on the activation toggle

**Actual:**
The display is changed to show the message broker at the top of the list

**Expected:**
The display remains on the currently selected message broker

**Comment by GreenMachine01** [comment]
@arielweinberger I am guessing this is an item that is easy to fix and can be done by the community?

**Comment by Deco90** [comment]
Hi, can I work on this issue?

**Comment by abrl91** [comment]
@Deco90 Yes. I assigned you. Good luck!

**Comment by souravjain540** [comment]
Hi @Deco90, do you need any help in solving this issue?

**Comment by GreenMachine01** [comment]
@Deco90 the issue is not resolved. I just tested it.

**Comment by Deco90** [comment]
Hi,
I’m try to fix this bug. It will take a more few day, if I struggled with
this issue, I’ll send here a comment.
Thanks
