### ISSUE TITLE
🐛 Bug Report: Cannot sign in with github.

### ISSUE THREAD

**Issue by 1stcall** [amplication/amplication#4299]
### What happened?

Tried to sign in from https://app.amplication.com/login and was unable.
{"statusCode":404,"message":"Cannot GET /login/?error=Failed%20to%20obtain%20access%20token","error":"Not Found"} was returned.

### What you expected to happen

Sign in.

### How to reproduce

Attemp to sign in.

### Amplication version

web

**Comment by arielweinberger** [comment]
Hey, thanks for reporting this. I just tried logging in and managed to do that with no issues.

Are you able to record your screen so we see what exactly you're facing?

Thanks!

**Comment by 1stcall** [comment]
See attached

https://user-images.githubusercontent.com/12874669/199294489-e811f811-60a5-4316-9372-43de4c4ef445.mp4

**Comment by 1stcall** [comment]
Just signed in fine using Microsoft Edge.  Must be a Firefox thing.
