### ISSUE TITLE
User initials are empty when using GitHub signin

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#430]
When a user signs in with a Github account, the user badge is not showing any letters.

1. Go to app.amplication.com
2. Click on "Sign in with Github"
3. See the user badge on the top right corner - an empty circle is showing.

**Expected behavior**
The user initials are expected to show in the badge

**Comment by yuval-hazaz** [comment]
Currently, we only fetching the user's email address from Github.
As a temporary fix we should save the user's email address in the firstName field (in addition to the email field).

As a permanent fix, we should either fetch more details from GitHub (check if any additional scopes are required) or show the badge info based on the email address when first name and last name are empty

**Comment by iddan** [comment]
We are able to receive the user name with the `read:user` GitHub scope. As pointed out [in stackoverflow](https://stackoverflow.com/a/55434352) there is an issue with parsing first name and last name from the GitHub name. I suggest after login with GitHub we will ask for first name and last name or even better drop the requirement for first name and last name altogether in favour of a username to match the GitHub experience.

**Comment by iddan** [comment]
Also, we can use GitHub's profile picture to display instead of initials. So the name won't be required at all for displaying purposes.
