### ISSUE TITLE
🐛 Bug Report: Error pushing to git after removing entity

### ISSUE THREAD

**Issue by TheDistanceHQ** [amplication/amplication#4315]
### What happened?

I have an entity which was bound to another via a relationship. I forgot to remove the reference property before I committed, which caused an initial compilation error. 

However I have now removed that erroneous property but the commit process is now failing with an ambiguous error message during the commit to Github stage

>  Error: Failed creating pull request, reason: The expression evaluated to a falsy value:
>   (0, assert_1.default)((0, fs_1.existsSync)(buildPath))

I'm not sure how to debug this further. This is for project: cla0t8jwn70570101mcuzju2m7e

N.B. You cannot copy errors from the error log in Chrome, I had to grab that from the source code

### What you expected to happen

Commit to git should work without issue

### How to reproduce

1. I created an entity
2. Added a relationship to it on another entity
3. Committed
4. Deleted entity (forgetting to delete related field)
5. Committed (error during commit to amplication)
6. Deleted relationship
7. Commited (error during commit to github)

### Amplication version

Latest as of message date (couldnt find version no)

**Comment by GreenMachine01** [comment]
@TheDistanceHQ I tried to follow your steps and after deleting the problematic relationship the commit worked well.
Please try again.

![image](https://user-images.githubusercontent.com/112330500/200163457-682f6323-b397-463d-9506-b18dd558a56d.png)

In any case, your bug makes it clear that we should:
1. Let you copy text from the code view window - I opened an issue for this request https://github.com/amplication/amplication/issues/4318
2. Warn and automatically delete problematic relations when deleting an entity - I opened an issue for this request https://github.com/amplication/amplication/issues/4319

**Comment by GreenMachine01** [comment]
was completed.
