### ISSUE TITLE
Allow the user to copy text from the code frame

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4318]
![Image](https://user-images.githubusercontent.com/112330500/200163258-4ac02dd6-fff5-44f1-bd2b-a8dc308ff25e.png)

A user should be able to copy text from the code frame

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4337

**Comment by GreenMachine01** [comment]
Confirmed fix.
