### ISSUE TITLE
When deleting an entity show "are you sure" notification if entity is linked to other entities

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4319]
**Overview:**
it is possible for a service to have 2 entities linked to each other. 
![image](https://user-images.githubusercontent.com/112330500/200163838-145e1d4c-9791-4db7-8e00-09ba504bc157.png)
if we delete one of the entities we will get an error when trying to build and commit.
The source of the error is that the entity that remains still has a relation to the entity that has been deleted.

**Requirements:**
1. When deleting an entity that has relations to other entities show the user an "Are you sure?" pop-up with relevant information.
2. if the user decides to cancel the entity deletion close the "are you sure" popup - no additional action is needed
3. if the user decides to continue with the entity deletion all fields that have a relation to the entity being deleted should be automatically deleted from the remaining entities

**Text Instructions for "Are you sure":**
Title - "Delete '[entity name]'"

Body - "Are you sure you want to delete this entity?
             This will also delete the related fields: 
             [field name] ('[entity name]')"

![Image](https://user-images.githubusercontent.com/112330500/202900341-6c9a64de-4bf1-4b7a-b0b1-9e28765d217e.png)

https://www.figma.com/file/wBcRAckCdHNCT3zUIOlK59/%234319---Entities%E2%80%A8---Are-you-sure%3F?node-id=1136%3A6535&t=nV5vuxsWj10YoT6k-1

**Comment by tupe12334** [comment]
UPDATE:
As the one who takes this task, I split it into 3 sub-tasks as mentioned in the requirements section.
I will open for every one of them a separated PR.

**Comment by tupe12334** [comment]
Hi @GreenMachine01 please contact @alexbass86 and let me know when there is a final design for the alert structure.
The data logic is already finished.

**Comment by GreenMachine01** [comment]
@tupe12334 this seems wrong...


![Image](https://user-images.githubusercontent.com/112330500/205862757-22fdbd8e-764b-43e3-9765-92b93a238cde.png)

**Comment by tupe12334** [comment]
You are right, I missed the whit text color, I regard the border; we agreed that this will be a separated task.
