### ISSUE TITLE
As Product - I need BI events on the Message Broker

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4320]
**Overview:**
In order to understand the usage and importance of the Message Broker for our users we need to implement some BI events that will allow us to create reports and perform analysis on the feature usage.

**Requirements:**
1. Implement the BI events according to - https://www.notion.so/amplication/Message-Broker-BI-f0a2caea355440879f37c20eb0c171f3

Events:
- [x] create a message broker from the menu
- [x] create a message broker with the wizard
- [x] click on the back button
- [x] connecting a topic within a service + what message pattern was used
- [x] create topics
- [x] use the filter search for topics
- [x] click the Topic Page within the Message Broker area (tile)
- [x] click the Services Page within the Message Broker area (tile)
- [x] click the Topic Page within the Message Broker area (left menu)
- [x] click the Services Page within the Message Broker area (left menu)
- [x] click the Settings Page within the Message Broker area (left menu)
- [x] change the topic ‘display name’
- [x] changes the topic ‘name’
- [x] changes the topic ‘description'

Error handling:
- [x] count how many times message broker creation failed + reason
- [x]  count how many times topic creation failed + reason

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4351
