### ISSUE TITLE
🐛Bug Report: 'Discard Changes' action doesn't cancel new entities or plugins installed

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4334]
**Steps to reproduce:**
1. Create a new service
2. Create several new entities
3. Install several plugins
4. Click on the discard changes CTA

**Expected:**

1. New entities are deleted
2. Plugins show as not installed

**Actual:**

1. New entities remain on the list
2. Plugins are shown as "installed"

**Comment by arielweinberger** [comment]
The specs described in this issue have been tested and the solution works properly. I found a different issue while testing this, for which I have created the following task: #4990
