### ISSUE TITLE
Add format pre-commit hook

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#4341]
In order to make sure that all our code is formatted every time it will be great to add a pre-commit hook
For more info https://prettier.io/docs/en/precommit.html

**Comment by bitethecode** [comment]
Hello Tupe! @tupe12334 I like to take this one to contribute for the first time. Could you assign this to me?

**Comment by bitethecode** [comment]
Thanks!

**Comment by GreenMachine01** [comment]
@bitethecode any updates?

**Comment by bitethecode** [comment]
@GreenMachine01 Sorry, I was out for vacations. I should be able to create a pull request this week!

**Comment by GreenMachine01** [comment]
@bitethecode Awesome! Much appreciated!

**Comment by tupe12334** [comment]
@bitethecode you are right; it is already in place and closed by https://github.com/amplication/amplication/pull/4393
