### ISSUE TITLE
🐛 Bug Report: Separated DSG attempts to build Message Broker resource type

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#4342]
### What happened?

When building a message broker, the build request gets to the message broker and the DSG is failing to build with an error.

We expect the build to be successful when a Message is involved.

This breaks every Message Broken build.

### What you expected to happen

-

### How to reproduce

-

**Comment by yuval-hazaz** [comment]
I think this is not happening any longer. @arielweinberger please confirm or provide more details to reproduce

**Comment by overbit** [comment]
This has been fixed and it is no longer reproducible
