### ISSUE TITLE
🐛 Bug Report: unnecessary change in PR when no changes in the generated code 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4360]
### What happened?

When rebuilding a service with no changes, the new PR is generated with a single change in the swagger file which is not required.  

![image](https://user-images.githubusercontent.com/43705455/201606609-d2e9bc14-04ee-4281-96b6-b0b7a59d8127.png)

### What you expected to happen

The code should not change 

### How to reproduce

create a second PR after merging the first one without making any changes 

### Amplication version

1.0.2

### Plan 
Go to amplication/libs/data-service-generator/src/server/swagger/create-swagger.ts
In function createSwagger() provide a proper VERSION parameter
Set version to amplication version or to static version 1.0.0 if obtaining amplication version is not possible

Plan written by @EugeneTseitlin

**Comment by yuval-hazaz** [comment]
We need to test when will happen if we will try to create a PR with no changes and what will be the experience from the user side both in Amplication and in GitHub

**Comment by abrl91** [comment]
passed QA ✅

simple git strategy:
a commit with no changes
![Image](https://github.com/amplication/amplication/assets/39680385/e9459020-7ec2-4bbe-bbae-80b988f79e88)

smart git strategy:
just a comment, no commit, no changes


![Image](https://github.com/amplication/amplication/assets/39680385/12273604-46c6-4af9-b679-243149bf1f5d)
