### ISSUE TITLE
COPY package-lock.json in Dockerfile

### ISSUE THREAD

**Issue by vincenzodomina** [amplication/amplication#4368]
### Feature description

Should we add

`COPY package*.json ./`

to the Dockerfile

### Use case

instead of just adding the package.json also copying the package-lock.json file avoids unexpected errors/ behaviour when deploying your docker container compared to your local environment.

See explanations here:
[Stackoverflow thread 1](https://stackoverflow.com/questions/65234362/should-i-copy-package-lock-json-to-the-container-image-in-dockerfile)
And eventually additional use of `npm ci`
[Stackoverflow thread 1](https://stackoverflow.com/questions/63835731/why-does-package-lock-json-causes-a-failure-in-a-docker-container-build-when/64014814#64014814)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@arielweinberger @overbit would you please review this request ?

**Comment by overbit** [comment]
@vincenzodomina thanks for raising this out. It is indeed a valid point. 
As we are about to release a repository refactoring in favour of nx, I'd suggest to wait a couple of days before working on a PR since there might be major changes to the Dockerfiles.

**Comment by overbit** [comment]
@vincenzodomina if you are still up for it, now it's a good time to review the current state of art and potentially raise a PR if you are still up to it.

**Comment by vincenzodomina** [comment]
Sure!
