### ISSUE TITLE
⭐️ Plugin API

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4369]
**Overview:**
Plugin API is aware of the available Amplication plugins, their versions and compatibility, and serves available plugins to the client for display.
The API will read the accepted Plugins from the Catalog on GitHub (Following the practice by Nuxt.js)

![Image](https://user-images.githubusercontent.com/112330500/203304752-5dac9d88-086f-429e-bae7-675cb36b3314.png)

API should return this data for each plugin

**Requirements:**

** Use Amplication to generate the Plugin API **

1. Create a new "Plugin API" service
2. the service reads the plugin catalog from GitHub https://github.com/amplication/plugin-catalog
3. The Plugin API enriches the catalog with data from npm (versions + settings) 
    a. The settings are managed as a file in the package (each version has it own settings)
4. All the data is saved in a local DB, so it can be sent to the client without reading everything from GH + NPM from scratch
5. Think about how and when to update the data on the Plugin API (every x minutes, hooks from GH, hooks from npm, etc)
6. Idealy, we want to use GraphQL for the Plugin API - we need to check how to connect to multiple GQL sources from the client (without things like federation etc.)

FUTURE: In addition, we need to save flags and additional data on the plugins and versions (etc., number of installations, deprecated versions, deleted versions)

**Comment by abrl91** [comment]
The list of plugin indeed coming from the API


![Image](https://user-images.githubusercontent.com/39680385/217252599-9107b86a-e612-447e-aa56-7f9104d8c22c.png)
