### ISSUE TITLE
🌟Plugin events - cleanup suffix `module` where not needed

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4371]
### description

To avoid confusion between NestJS terminology for the word `module` and the current implementation of the DSG for the word: `module`, we need to delete this suffix in places where we don't create a NestJS module.
For example `CreateServerAppModule` indeed creates the `app.module.ts` for the server, but in functions like:
`createResourceModules`, `createServiceModules`, `createControllerModules` (on the DSG, not as a plugin event), the word `module` refers to files and it can cause confusion.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@abrl91 from looking at the latest file in `next` I don't see events that are left with the word `Module` besides where needed

![image](https://user-images.githubusercontent.com/43705455/202107642-cc71198e-a7f1-480c-9041-9a7cb963d758.png)

**Comment by abrl91** [comment]
> @abrl91 from looking at the latest file in `next` I don't see events that are left with the word `Module` besides where needed
> 
> ![image](https://user-images.githubusercontent.com/43705455/202107642-cc71198e-a7f1-480c-9041-9a7cb963d758.png)

Right, and that's why I mentioned that these names are on the DSG. I know that this is an inner implementation, and as a plugin creator, it shouldn't confuse me. But it can confuse us and potential contributors while implementing new events

**Comment by yuval-hazaz** [comment]
Ok, so in that case, we should look at it from a much bigger perspective because we use Modules in many places in the code beside the functions name - including the list of files on the DSGContext, which is still called Modules. 

Maybe we need a bigger refactoring.
