### ISSUE TITLE
Git hooks that run code format and lint

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4384]
### Feature description

It would be nice to have these two hooks to ensure that we don't forget to format code before commit. Otherwise CI fails and make you format code, commit and push again, but it's time consuming. I've forgot about it so many times, and I've also seen others commits with description "format code", which means I'm not the only one. This improvement is going to save us a lot of time.

**Comment by bitethecode** [comment]
@EugeneTseitlin Could you assign this to me? it sounds interesting to me

**Comment by overbit** [comment]
Sorry but we already had a PR merged. Next time @bitethecode!

**Comment by overbit** [comment]
@EugeneTseitlin can we address this comment with another PR ?https://github.com/amplication/amplication/pull/4393#issuecomment-1328891334
