### ISSUE TITLE
Docs: Plugin Events Article - Create Entity Resolver 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4385]
### Describe the issue with documentation

This event needs to be included in the docs.

### How to solve the problem

Create an article describing the Plugin Event. 

### The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

**Comment by abrl91** [comment]
# Create Entity Resolver

## Description

Creates the resolver of an entity

## Event Name:
`CreateEntityResolver`

## Event Params

```ts
export interface CreateEntityResolverParams extends EventParams {
  template: namedTypes.File;
  entityName: string;
  entityServiceModule: string;
  serviceId: namedTypes.Identifier;
  resolverBaseId: namedTypes.Identifier;
  templateMapping: { [key: string]: any };
}
```

### entityName
The name of the entity for which we are generating the resolver 

### template
A template file that is used to generate the resolver
This is the default template that is used for this event.
https://github.com/amplication/amplication/blob/master/packages/amplication-data-service-generator/src/server/resource/resolver/resolver.template.ts

You can manipulate or replace the template with a new template in your plugin. 

### templateMapping
An object with values that are available in the interpolation process of the template.  
This default object with the available parameters can be found here 
https://github.com/amplication/amplication/blob/master/packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts#L88

You can manipulate the object by adding new values, or replacing existing values that will be used in the template when creating the resolver file. 

### entityServiceModule
The path to the entity service module

### servicId
The Identifier of the service that is used as the class name. e.g. CustomerService

### resolverBaseId
The Identifier of the base resolver that is used as the class name. e.g. CustomerServiceBase

**Comment by MoFoGo** [comment]
Transferred to docs
