### ISSUE TITLE
Docs: Plugin Events Article - Create Entity Resolver Base

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4386]
### Describe the issue with documentation

This event needs to be included in the docs.

### How to solve the problem

Create an article describing the Plugin Event. 

### The following can be used as examples for the documentation. 

https://github.com/amplication/amplication/issues/4095

https://github.com/amplication/amplication/issues/4094

**Comment by abrl91** [comment]
# Create Entity Resolver Base

## Description

Creates the base resolver of an entity

## Event Name:
`CreateEntityResolverBase`

## Event Params

```ts
export interface CreateEntityResolverBaseParams extends EventParams {
  template: namedTypes.File;
  entityName: string;
  entityType: string;
  entityServiceModule: string;
  entity: Entity;
  serviceId: namedTypes.Identifier;
  resolverBaseId: namedTypes.Identifier;
  createArgs: NamedClassDeclaration | undefined;
  updateArgs: NamedClassDeclaration | undefined;
  createMutationId: namedTypes.Identifier;
  updateMutationId: namedTypes.Identifier;
  templateMapping: { [key: string]: any };
}
```
### entity
The entity for which we are generating the base resolver 

### entityType
The type of the entity for which we are generating the base resolver 

### entityName
The name of the entity for which we are generating the base resolver 

### template
A template file that is used to generate the base resolver
This is the default template that is used for this event.
https://github.com/amplication/amplication/blob/master/packages/amplication-data-service-generator/src/server/resource/resolver/resolver.base.template.ts

You can manipulate or replace the template with a new template in your plugin. 

### templateMapping
An object with values that are available in the interpolation process of the template.  
This default object with the available parameters can be found here 
https://github.com/amplication/amplication/blob/master/packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts#L88

You can manipulate the object by adding new values, or replacing existing values that will be used in the template when creating the base resolver file. 

### servicId
The Identifier of the service that is used as the class name. e.g. CustomerService

### resolverBaseId
The Identifier of the base resolver is used as the class name. e.g. CustomerServiceBase

### createArgs
  
### updateArgs
  
### createMutationId
  
### updateMutationId

**Comment by abrl91** [comment]
@barshimi 
can you please fill out the last 4 event params?
can you also explain why in this case (as opposed to the controller) we need the `createArgs` and `updataArgs`?
What are `createMutationId ` and `updateMutationId `?

**Comment by barshimi** [comment]
createMutationId - is identifier build by ast-type for a specific action. in that case create mutation id
updateMutationId - same here for update
createArgs - arguments that is coming from DTO entity for create process
updateArgs - same here for update
can you also explain why in this case (as opposed to the controller) we need the createArgs and updataArgs? - it was part of the original function, so I don't know why
