### ISSUE TITLE
Inconsistent slugs  

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#4398]
### Describe the issue with documentation

Some of the pages in the documentation are served behind slugs that are not properly formatted and generally not following the overall slug definitions.

i.e. https://docs.amplication.com/api/api/generated-api-sorting/ 
has a duplicated `api` that should be removed

or https://docs.amplication.com/getting-started/getting-started/phone-home/

### How to solve the problem

Review all slugs and fix any redundant repetition in the slug.
Create redirects to avoid affecting SEO

**Comment by Chirag8023** [comment]
this issue is sorted , I guess !
