### ISSUE TITLE
As User - I want to be automatically moved to the "commit" page when I click to build my pending changes

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4404]
**As User - I want to be automatically moved to the "commit" page when I click to build my pending changes so that I understand what's going on with my build**

### Feature description

It was reported by users that after they click on "Commit" (or "Rebuild" in case there are no changes), they lose orientation of what they should do next. 

In most cases (when connected to GitHub), the user would like to go to the Pull Request in GitHub. But mainly and especially for new users, they need to get an indication on what is going on. 

Right now, we have the "Last Build" panel on the bottom right corner of the screen with a "Loading" animation but based on users' feedback, it is not clear enough. 

**Requirements:**
 
1. After a user click on "commit" he should be sent to the "Commits" page, with the current commit selected, showing the list of builds that are running. 

Future - We should add more information to the user on the commit page with either a link to the new PR or CTA tp connect to GitHub in case they are not connected. (currently, the link to the PR is only from the small icon and it is not clear enough)

**Comment by yuval-hazaz** [comment]
@GreenMachine01 can you please look at this and let me know what you think? 

@amplication/amplication please feel free to jump in and add your thoughts and/ or suggestions

**Comment by GreenMachine01** [comment]
@yuval-hazaz We think it will be best to do the same thing each time you build. Having a smart decision tree makes it harder to implement and harder for the user to understand the difference.

So we suggest doing the following:
When a user clicks to build we automatically open the "Commits" page, with the current commit selected, showing the list of builds that are running.
Also, we will improve the available actions on the page for the user as you suggested.
