### ISSUE TITLE
🐛 Bug Report: No default route

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#4424]
### What happened?

When changing the path in the url to something that doesn't exist, the application will load a blank page.

### What you expected to happen

I would expect that when you try to visit something that doesn't exist it would route to the home page or a custom error page.

### How to reproduce

When you visit the following url you run into this issue: "application url/example-path-that-doesnt-exist"

https://app.amplication.com/example-subpath-that-doesnt-exist

If the url contains a sub-path the routing does use the sub path as the default route: "application-url/subpath-uuid/example-subpath-that-doesnt-exist"

### Amplication version

v1.1.0

**Comment by arnabsen1729** [comment]
Would like to work on this issue.

**Comment by souravjain540** [comment]
@arnabsen1729 assigned. let me know if you need any help :)

**Comment by harshit-senpai** [comment]
would love to work on this

**Comment by arnabsen1729** [comment]
@souravjain540 Ya it seems like the logic to redirect to 404 page if none of the routes match is already in place

https://github.com/amplication/amplication/blob/45a6a45eb0181c74fa35ecf68ea6b702416b6929/packages/amplication-client/src/routes/routesUtil.tsx#L108

But, will try to setup the client locally and debug the issue. Just let me know if I am looking at the right directory "application-client"

**Comment by souravjain540** [comment]
@levivannoort please confirm

**Comment by arnabsen1729** [comment]
@souravjain540 Sorry, I started my work but couldn't complete it due to other commitments. It might take a couple of weeks now.

**Comment by vasu-1** [comment]
Can You assign this issue to me?

**Comment by anshgoyalevil** [comment]
@souravjain540 Could you please assign me this issue. I would love to resolve it.

**Comment by souravjain540** [comment]
@anshgoyalevil assigned

**Comment by overbit** [comment]
As per https://github.com/amplication/amplication/pull/6378#issuecomment-1609086405 we are closing this issue as we are not going to fix the behaviour now.
