### ISSUE TITLE
DSG Readme: Replace reference to Lerner with Nx

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4436]
### Describe the issue with documentation

The DSG Readme still includes references to  Lerna:

Generated Application Dependency Management
Add a dependency to the server template
npx lerna add --scope server-template $NAME_OF_DEPENDENCY
Add a dependency to the client template
npx lerna add --scope admin-template $NAME_OF_DEPENDENCY
:

https://github.com/amplication/amplication/blob/master/packages/amplication-data-service-generator/README.md

### How to solve the problem

Update with the relevant info for Nx

**Comment by overbit** [comment]
Completed
