### ISSUE TITLE
Ability to control which endpoints are created with a service

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4439]

**Comment by bitethecode** [comment]
Can I take this?

**Comment by GreenMachine01** [comment]
@bitethecode Thanks for requesting to work on this item. I am checking internally if we can assign it to you.

**Comment by GreenMachine01** [comment]
@bitethecode thank you for your interest. we need to plan how we want to implement this feature so for now it is on hold.

**Comment by bitethecode** [comment]
@GreenMachine01 Sounds good. Let me know when it's ready!

**Comment by yuval-hazaz** [comment]
already part of the actions module
