### ISSUE TITLE
Plugthon: As Developer I want to remove unnecessary files from the build (ie. MacOs ._file and DS_store​)

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4449]
Can be done as part of https://github.com/amplication/amplication/issues/4448

Add the filtering as part of the util library

**Comment by barshimi** [comment]
it wont be part of #4448 because this check will be part of the writ file loop. before writing files to generated folder it will check the file extension.

**Comment by EugeneTseitlin** [comment]
@barshimi Please, create PR and connect it to the issue if you've finished.
