### ISSUE TITLE
Plugin: Prettier

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4451]
**Acceptance criteria:**
Plugin can be used by users
Has Documentation
static setup (not dynamic)

Generating an app using Prettier should result in a prettier config present in the generated code.
Make sure formatting works.

- prettier should be installed (included in packag.ejson)
- npm script `format` should work
- prettier config should be present in the generated repo

**Comment by GreenMachine01** [comment]
@EugeneTseitlin I moved it back to "to do" please see feedback from @abrl91

**Comment by abrl91** [comment]
typo in `dist_modules` (instead of node_modules)
![image](https://user-images.githubusercontent.com/39680385/210264978-c74adde1-b48e-437a-af49-fae12ad6e849.png)

**Comment by abrl91** [comment]
The plugin works. I created an issue for this bug https://github.com/amplication/amplication/issues/4848
