### ISSUE TITLE
As a NEW User - I want to see a good example for an app created with Amplication

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4453]
**As a NEW User - I want to see a good example of an app created with Amplication so that I can understand the potential of working with Amplication.**

suggestion - Show a mono-repo with multiple apps

**Requirements:**

- Create an app with X, Y, Z
- Once the new app is ready, replace the existing "sample app" on Github - https://github.com/amplication/sample-app

**Comment by GreenMachine01** [comment]
@yuval-hazaz Please add details for the sample app we want to show to new users.

**Comment by abrl91** [comment]
I have a blocker:
Yuval sent me an invitation to the Amplication workspace, but I can't see the workspace when I click on the invitation link. We may need to check if this is a bug or a specific problem with my production environment, as I have a workspace named: Amplication[with-space] 😄

Regarding the example app, let's create a project with:
- two services
- one service with admin UI and graphQL (e-commerce service) + Postgres plugin + Kafka plugin + JWT plugin
- one service with REST and without admin UI (a service with user entity and some custom entities) + MySQL plugin + Kafka plugin + basic auth plugin
- one message broker for each service
- use paths:
  - apps/ecommerce-service
  - apps/ecommerce-admin
  - apps/myservice

**Comment by yuval-hazaz** [comment]
@abrl91 let's check this one together to better understand the issue. It is also important to make sure the invitation feature is not broken

**Comment by abrl91** [comment]
I created an issue for the blocker:
https://github.com/amplication/amplication/issues/4535
