### ISSUE TITLE
As User - I want to be able to quickly change my service name

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4457]
**As User - I want to be able to quickly change my service name (without going to settings) so that it is convenient for me.**

**Requirements:**

- When a user hovers with the mouse over the top banner on the service dashboard we show a small pencil icon next to the service name
- when the pencil icon is clicked the user is able to update the service name
- Handle errors when the name is not valid

![Image](https://user-images.githubusercontent.com/112330500/204146906-e45bea8c-3542-4436-9b05-886cee524b68.png)

**Design:**
https://www.figma.com/file/xNUDscEZpkpVfBFaclSKnl/%230000---Updating-project-name---1-step?node-id=1136%3A6535&t=FsuGzGCBtBmYrOd2-1

**Acceptance Criteria:**

- A user can directly change the service name via the service dashboard

**Comment by Deco90** [comment]
I’ll take this issue

**Comment by abrl91** [comment]
@alexbass86  can you please provide a link for Figma that community members can have access to?

**Comment by alexbass86** [comment]
Hi here the public link:
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1202%3A14117&t=vcUYLiJtTNvRKQiV-1

Good luck.

**Comment by GreenMachine01** [comment]
@Deco90 great. thanks!

**Comment by GreenMachine01** [comment]
@Deco90 Hey, Any updates?

**Comment by Deco90** [comment]
Hi, sorry. I have no news about this ticket.
And I don’t have time on the next two weeks to fix it. If its high priority
you can pass it. Sorry about it

**Comment by mahi072** [comment]
I want to work on this issue, please assign me this.

**Comment by GreenMachine01** [comment]
@mahi072 assigned to you. thank you and good luck!

**Comment by Spid3rrr** [comment]
Any updates on this ticket ?

**Comment by GreenMachine01** [comment]
@Spid3rrr we are currently already progressing with this item. thanks for showing interest in working on it. I hope you will find other items to contribute to.

**Comment by GreenMachine01** [comment]
we are missing the edit icon

**Comment by lokeswaran-aj** [comment]
Hi, @GreenMachine01 Thanks for the feedback. I created this [PR](https://github.com/amplication/amplication/pull/5462) and 

- edit icon -> I was following this [figma](https://github.com/amplication/amplication/issues/4559#issuecomment-1340950830) in the project name issue and there was no edit icon. Let me know if you would like to have the edit icon.
- Text jump -> I believe you are saying when the error message appears. And I fixed it with a tooltip.  And I m not sure if we can change the color of `Error:` in `Error: unsupported character`

- Success icon color -> It is `#31C587` only i.e. ` --positive-default` variable.

https://user-images.githubusercontent.com/74011196/225969223-9be63c6e-3a47-4b87-a8d0-ea72c0094a64.mov

**Comment by overbit** [comment]
## Test result
`PASSED` ✅ 

https://jam.dev/c/008509a8-69c1-4fe2-86e4-392144e6a2df

**Comment by GreenMachine01** [comment]
@overbit It is also expected that the BG banner changes its color on hover to be lighter.
@alexbass86 please provide instructions on what needs to happen.

**Comment by GreenMachine01** [comment]
@alexbass86 please review the design for this item.

**Comment by lokeswaran-aj** [comment]
@GreenMachine01  sure, I will work on it. Clarify me one thing, if a user hovers on service name, edit icon should appear and user moves the cursor to edit icon and click it to edit. Am I right?

**Comment by GreenMachine01** [comment]
@lokeswaran-aj if the user just hovers over any point of the banner it highlights the banner and the edit icon shows up.
clicking the edit icon allows the name to be edited

**Comment by GreenMachine01** [comment]
@lokeswaran-aj agreed. we can keep it.

**Comment by lokeswaran-aj** [comment]
Cool, then no need for edit icon, we still need the banner color to brighten while hovering, right?

**Comment by GreenMachine01** [comment]
@lokeswaran-aj I still want the edit icon as it tells the user what he can do. it will not be intuitive for users to expect to change the name just by clicking the text. please add the edit icon and clicking it will be the same as clicking the name.

**Comment by lokeswaran-aj** [comment]
@GreenMachine01 here is the [pr](https://github.com/amplication/amplication/pull/5573)
