### ISSUE TITLE
Types mapping factory

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#4458]
We need to support developers with a way to translate a typescript type (number, string, null, undefined, etc...) to js class (Number, String, null, Array, etc...) and vice versa.

**Comment by yuval-hazaz** [comment]
@tupe12334 I didnt understand the need
can you please add details and some use cases ?

**Comment by tupe12334** [comment]
@yuval-hazaz  We want to have a mapping between typescript types like lowercase number string etc.. to the js representation like Number String etc... with that, we can use one function to get both of them, like in the case of UUID and incremental, we used two switch cases

**Comment by yuval-hazaz** [comment]
Sorry - I still don't understand. 
is that something generic that can be used everywhere? or is it for a specific use case? is that something we will use in the platform or something that should be provided in the generated code? 
If that something generic and not directly related to Amplication - is there a package that can do that?
