### ISSUE TITLE
🐛 Bug Report: In Service Wizard screen Support Widget hides "Create Service" button  

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4462]
### What happened?

![image](https://user-images.githubusercontent.com/6080188/204155190-12477c91-879c-449a-b914-c35984fd8949.png)
Support Widget hides most of the button.

### What you expected to happen

At least an option to remove the widget, but I think we can find a better place for it.

### How to reproduce

Try to create a service.

**Comment by yuval-hazaz** [comment]
The intercom chat was added to app.amplication.com by mistake and was removed after a few minutes - so we can close this issue
