### ISSUE TITLE
🐛 Bug Report: Git Pull Service and Server can't start

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4463]
### What happened?

Here are the logs:
/app/node_modules/@amplication/prisma-clients/amplication-git-pull-service/runtime/index.js:30092
      throw new PrismaClientInitializationError(errorText, this.config.clientVersion);
            ^

PrismaClientInitializationError: Query engine library for current platform "debian-openssl-1.1.x" could not be found.
You incorrectly pinned it to debian-openssl-1.1.x

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/app/node_modules/@amplication/prisma-clients/amplication-git-pull-service/runtime/libquery_engine-debian-openssl-1.1.x.so.node")

Seems like an issue with base image or/and installing appropriate package.
I think it happens because we build services on CI environment and then copy result to our own image. We should specify CI runner image too.

### What you expected to happen

Service should run.

### How to reproduce

Next envrivoment,

**Comment by EugeneTseitlin** [comment]
In order to solve and avoid these types of issues we need to run install and build steps in the same image that we use for running our services.
https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

**Comment by GreenMachine01** [comment]
@EugeneTseitlin still relevant?

**Comment by overbit** [comment]
Closed due to missing recent reports
