### ISSUE TITLE
Add Builds page to Left Menu and Service Overview

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4469]
### Feature description

![image](https://user-images.githubusercontent.com/6080188/204317221-8909cd60-9497-4660-b8f3-cc73a95b8285.png)
Today in order to get to the previous builds we have to go to click on last commit ID. I think having page "Builds" would be more intuitive and straightforward.

**Comment by yuval-hazaz** [comment]
@EugeneTseitlin the builds page is at the project level, and all the current items in the menu are for the service level. 
Currently, the builds (commits) and code view are part of the project navigation menu on the top bar. 

I agree we should think about a solution - it might be that the side menu is the answer but I am not sure about it.

@alexbass86 @GreenMachine01 what do you think?

**Comment by GreenMachine01** [comment]
@EugeneTseitlin @yuval-hazaz @alexbass86 
I think it definitely makes sense to add the "Commit" page to the project settings.
I suggest thinking about where is appropriate to have access to this page. (Alex let's discuss it)

**Comment by aarushisoni** [comment]
Hi,
Have you discussed where the changes are to be made? 
I would like to work on this issue. Please assign me this issue.

**Comment by GreenMachine01** [comment]
@aarushisoni we didn't tackle this item yet. We were busy with other priorities.
I will update you here when we have the defined solution. Thanks!

**Comment by GreenMachine01** [comment]
Was solved by our new UI
