### ISSUE TITLE
🐛 Bug Report: Code View is not showing the code

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4485]
### What happened?

after a user clicks on build, navigates to code-view and click to view on of the files it show the following screen:

![image](https://user-images.githubusercontent.com/39680385/204513185-56d37afe-7b30-4a62-9415-7750a3c28847.png)

### What you expected to happen

I expect to see the code

### How to reproduce

- generate a service
- click on the build buttton
- wait for the build process to finish
- navigate to code-view
- choose a file
- see that there is no code

### Amplication version

next

**Comment by EugeneTseitlin** [comment]
I see that file content has been received, but not rendered properly. It's a client app issue.
![image](https://user-images.githubusercontent.com/6080188/204518304-458dcc9c-3591-4d5d-ba8d-4beaf1011612.png)
