### ISSUE TITLE
As Dev - I want to automatically deploy a new version of the DSG on deploy action

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4486]
As a developer, I want to add automation to the deployment process to ensure that a new version of the DSG is automatically deployed when the Next branch is deployed to the Next environment.

**Requirements:**
1. Identify the current process for deploying the DSG to the next environment.
2. Develop a process for automatically checking if the sha of the DSG has changed since the last deployment.
3. If the sha has changed, automatically deploy the new version of the DSG with the new image version.
4. If the sha has not changed, do not deploy the DSG and continue with the rest of the deployment process.
5. Test the automated deployment process in a staging environment to ensure that it is working correctly and is not impacting other aspects of the deployment process.
6. Monitor the deployment process and address any issues or bugs that are identified.
7. Document the automated deployment process and ensure that it is easily accessible to other members of the development team.

**Comment by overbit** [comment]
Completed
