### ISSUE TITLE
As Dev - I want to get familiar and understand the work left to deliver the Github sync epic

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4490]
Epic - https://github.com/amplication/amplication/issues/3751

Taking over the GitHub Sync project requires understanding all the work that has been done and all the work that remins to be completed.
As part of this User Story the developer should catch up so that we can properly plan the next steps.

**Comment by overbit** [comment]
- [ ] #4590
- [ ] #4591
- [ ] #4592
- [ ] #4593
- [ ] #4594
- [Define a Kafka strategy](https://github.com/orgs/amplication/projects/6/views/6?filterQuery=no%3Asprint+status%3ATodo+refactor+kafka)
