### ISSUE TITLE
amplication/site: config prettier-plugin-tailwindcss

### ISSUE THREAD

**Issue by Pranay-Tej** [amplication/amplication#4495]
This [official plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) works along with prettier to sort the class names on format.

- This will keep the tailwind class order consistent across the amplication/site codebase
- I am willing to submit a PR

**Comment by souravjain540** [comment]
@MichaelSolati  please look into this.

**Comment by MichaelSolati** [comment]
I'd be interested in this, @Pranay-Tej I'll assign you to this.
