### ISSUE TITLE
Services without Authentication module (UI)

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4497]
**As User - I want to be able to set up my service without Authentication module (in the generated app) so that it can run without authentication and authorization (UI)**

**Overview:**
Some developers will want the service to not have any users set up.
This might be useful when you need background services that don't expose endpoints to end users so there is no need for authentication and authorization
This also might be useful when you need a Public API.

**Requirements:**

- Add a toggle on the 'Authentication' Tab within the service settings
    - Text for the toggle - "Enable Authentication"
![image](https://user-images.githubusercontent.com/112330500/203761780-405c1206-1bdc-4a82-867b-8c31a476fc34.png)
- When authentication is turned off we need to remove the Authentication module from the service
    - Show "are you sure" pop-up
    - Allow the user to also remove the 'User' **entity** (Can use a checkbox)
    - Allow the user to also remove the 'User' **role** (Can use a checkbox)
    - **We do not support Admin UI for now**
- When authentication is turned on we need to add the Authentication module to the service
    - add the 'User' **entity** if not already exist
    - add the 'User' **role** if not already exist
 
**Phase II:**
As part of our support of importing DB schemes we might need to have a mapping configuration to connect: 
1. The User **entity** as we know it to how its defined in the Prisma schema
2. The User **role** as we know it to how its defined in the Prisma schema

**Comment by EugeneTseitlin** [comment]
@GreenMachine01 Why does this issue have two assignees? Who should implement that?

**Comment by GreenMachine01** [comment]
@EugeneTseitlin You are the lead.
Shimi said he will assist you if needed.

**Comment by EugeneTseitlin** [comment]
@GreenMachine01 I think it was already implemented and this issue has to be closed.
