### ISSUE TITLE
As Dev - I want to change our strategy of working with multiple Prisma clients

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4513]
### Feature description

Change our strategy of working with multiple Prisma clients in the same repository. This will allow to support easily monorepo and polyrepo configurations.

#### current approach

We are creating  `@amplication/prisma-clients` folder in the root node modules. Inside this folder we store all our prisma-clients: 

- prisma-db
```
generator client {
  provider      = "prisma-client-js"
  output        = "../../../node_modules/@amplication/prisma-clients/amplication-prisma-db"
  binaryTargets = ["native", "debian-openssl-1.1.x", "linux-arm64-openssl-1.1.x"]
}
```
- git-pull-service
```
generator client {
  provider = "prisma-client-js"
  output   = "../../../../node_modules/@amplication/prisma-clients/amplication-git-pull-service"
}
```
- plugin-api (a new service)
```
generator client {
  provider = "prisma-client-js"
  output   = "../../../../node_modules/@amplication/prisma-clients/amplication-plugin-api"
}
```

#### Suggested approach
: not using the `node_modules`, but a local prisma-client 
Since generated prisma clients are always relative to the project in charge of the generation we will need to enforce this boundary to avoid any unknown sharing of clients.

In order to do so, we should always generate clients within the project folder boundaries like:
```
generator client {
  provider = "prisma-client-js"
  output   = "../src/generated-prisma-client"
}
```
This new folder generated within the project will also need to be added to `.gitignore`. 

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by barshimi** [comment]
I like this approach, but I'm not sure it will go hand  to hand with NX best practices. @tupe12334 shared with me a solution that is on PR waiting to be merged on NX repo. maybe we need to explore that as well before going forward.
