### ISSUE TITLE
🐛 Bug Report: Amplication data service generator 

### ISSUE THREAD

**Issue by MichaelSolati** [amplication/amplication#4524]
### What happened?

During a fresh install of amplication, during `npm run setup:dev`, `packages/amplication-data-service-generator/src/admin/create-dotenv.ts` is failing. Specifically, the `replacePlaceholdersInCode` function expected arguments has a type mismatch with its second argument `appInfo.settings`.

Additionally here's a fun log...

![image](https://user-images.githubusercontent.com/11811422/205458557-b182bf6f-c359-46d9-ae32-643502fdc365.png)

First reported here => https://discord.com/channels/757179260417867879/781089015548870695/1047957466819854376

### What you expected to happen

Setup dev should work

### How to reproduce

fresh clone of the repo and go through the local dev steps

**Comment by yuval-hazaz** [comment]
@GreenMachine01 please assign someone to look at this today

**Comment by EugeneTseitlin** [comment]
@morhag90 Please, connect PR or branch if you already finished the implementation.
