### ISSUE TITLE
Docs: Update the URL for the Roadmap

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#4526]
### Describe the issue with documentation

The link to the roadmap in https://docs.amplication.com/about/roadmap/ is not correct

### How to solve the problem

Change the link to: 

https://github.com/orgs/amplication/projects/11/views/1

**Comment by yuval-hazaz** [comment]
@Aadarsh805, thanks for suggesting to help. 
This issue was already handled by @MoFoGo
