### ISSUE TITLE
As User - I want to see a pricing page within the platform

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4527]
As User - I want to see a pricing page within the platform so that I can understand the differences between the plans and upgrade my workspace plan

Ability to initiate workspace upgrade via the pricing page
use Stigg.io for building the pricing page

**Design:**
https://www.figma.com/file/REUaAG2f5EkgyghHMvACxd/Concept----Paywall?node-id=836%3A18964&t=ndj7JrlNH4sm9vnH-1

**Comment by barshimi** [comment]
do we have a design ? what is the scope of this task ?

**Comment by GreenMachine01** [comment]
https://www.figma.com/file/REUaAG2f5EkgyghHMvACxd/Concept----Paywall?node-id=836%3A18964&t=ndj7JrlNH4sm9vnH-1

**Comment by abrl91** [comment]
@EugeneTseitlin can you assign the PR to this issue?
