### ISSUE TITLE
As User - I want to know I went over my workspace plan limits

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4528]
![Image](https://user-images.githubusercontent.com/112330500/206133832-6d792ab8-593d-4ba3-aa76-827623b777ac.png)

**Design:**
https://www.figma.com/file/REUaAG2f5EkgyghHMvACxd/Concept----Paywall?node-id=2027%3A5701&t=ndj7JrlNH4sm9vnH-1

**Comment by barshimi** [comment]
did we implement the server to support this ?

**Comment by GreenMachine01** [comment]
@barshimi talk to Eugene
I think it throws an error at the moment.
