### ISSUE TITLE
🐛 Bug Report: Invite member to workspace errors in staging

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#4534]
### What happened?

Currently, the feature to invite a new member to the workspace errors with an internal server error in the staging environment. 
This should not happen.

### What you expected to happen

The invitation process will succeed

### How to reproduce

In the staging environment:

1. Click on Workspace Members
2. Invite a new member
3. Observe the error returned
4. Refresh the page and observe the new member in pending mode.

### Amplication version

1.1.1

**Comment by GreenMachine01** [comment]
@overbit is this still happening?

**Comment by yuval-hazaz** [comment]
it was fixed
