### ISSUE TITLE
As Dev - I want to research the ability to quickly step in our users shoes

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4550]
**Overview:**
When we get complaints from users we might need to recreate the scenario the user is experiencing or depend on getting feedback from the user.
This dependency on gathering information from the user wastes time.
We want to be able to quickly duplicate the setup the user is using so we can test it on our side without needing the user to be involved besides giving the identifier for his account.

**Requirements:**
Research possible solutions and come with an agreed upon strategy

- [ ] #4625

**Comment by EugeneTseitlin** [comment]
https://www.notion.so/amplication/How-to-catch-production-issues-e52a0ef3a8c24f889106914de9ec7d76

**Comment by EugeneTseitlin** [comment]
@yuval-hazaz @overbit @levivannoort Please, review

**Comment by EugeneTseitlin** [comment]
- [ ] Replicate production database

**Comment by levivannoort** [comment]
**Observability perspective**:

Extensive logging, tracing and analytics can accurately appoint to the problem. Everything can be tracked: action order, input data, results. Privacy concerns are applied to this solution also. But there is a unique benefit - proper analytics can help to detect the problem even without user knowing and reporting about that.  

issue: https://github.com/amplication/amplication-infrastructure-next/issues/47
