### ISSUE TITLE
As Dev - I want to research how to improve our deployment process

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4551]
**Overview:**
Over the past several deployments to prod we seem to be spending tremendous efforts and encountering new problems each time.
We need to rethink the process and find a good way to simplify and stabilize the deployment so we can count on it when we plan to release.

**Comment by overbit** [comment]
Review structure of ci pipelines into

- ci ( PR and push to master) [ lint + test + build ] 
- release (on push to master / next) [ dockerize + deploy ]

**Comment by levivannoort** [comment]
I agree on the afore mentioned structuring of pipelines and the attached branching strategy.
