### ISSUE TITLE
As User - I want to be able to quickly change my project name

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4559]
**As User - I want to be able to quickly change my project name (without going to settings) so that it is convenient for me.**

**Requirements:**

- When a user hovers with the mouse over the top banner on the project settings dashboard we show a small pencil icon next to the project name
- when the pencil icon is clicked the user is able to update the project name
- Handle errors when the name is not valid

**Design:**

![Image](https://user-images.githubusercontent.com/112330500/206192878-d153a451-0ebd-46f1-802f-3e37763144cb.png)

https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1202%3A14117&t=ifZe9OaSGGDz5D7M-1

**Acceptance Criteria:**

- A user can directly change the project name via the project settings dashboard

**Comment by GreenMachine01** [comment]
@Deco90 you might want to pick also this item as you are doing the same task in a different place.

**Comment by bitethecode** [comment]
@alexbass86 I'm not sure this is open for anyone to pick up or already someone is taking. If not, I want to contribute to it!

**Comment by GreenMachine01** [comment]
@bitethecode assigned to you. good luck!

**Comment by bitethecode** [comment]
@GreenMachine01 While I was trying to setup for the development, I wasn't able to run migrations... 

I followed the setup instructions but I'm seeing these errors.
![Screen Shot 2022-12-14 at 3 13 50 PM](https://user-images.githubusercontent.com/92326584/207715412-14cf0cef-923f-4586-98e6-cef9cfecba13.png)

![Screen Shot 2022-12-14 at 3 12 15 PM](https://user-images.githubusercontent.com/92326584/207715002-4a84fcdf-636e-4277-b1c9-a39ff6855bfb.png)

Any insight would be much appreciated!

**Comment by GreenMachine01** [comment]
@abrl91 can you assist?

**Comment by abrl91** [comment]
I couldn't reproduce the second error. I think we have an open issue related to this: https://github.com/amplication/amplication/issues/4637
We will solve it in a couple of days

**Comment by bitethecode** [comment]
@abrl91 sounds good to me. Thanks!

**Comment by bitethecode** [comment]
@GreenMachine01 @abrl91 Any updates on this issue? I still can't start working on it due to this.. :(

**Comment by yuval-hazaz** [comment]
@bitethecode can you please ask for help on the support channel on Discord? it will be easier to track the progress over there to help you solve the issue http://amplication.com/discord

**Comment by abrl91** [comment]
> @GreenMachine01 @abrl91 Any updates on this issue? I still can't start working on it due to this.. :(

please work on branch next and pull the latest changes. remove the docker container and run it again

**Comment by bitethecode** [comment]
@abrl91 I will try that soon!

**Comment by GreenMachine01** [comment]
@bitethecode Hey, Any updates?

**Comment by bitethecode** [comment]
The suggestion by @abrl91 was not working at least on my machine. The set up for dev is so frustrating so I decided to withdraw this.

**Comment by abrl91** [comment]
@bitethecode can you reclone the repo and start over? Ignore the error about the root in the db

**Comment by jaysoni-ash42** [comment]
@GreenMachine01  can i work on this issue?

**Comment by a-loke** [comment]
Hi, I can see this issue is still unfixed. I can think of two ways to fix this issue.
1. Use state name `isEditable` with a boolean value that changes on clicking the service name. Based on the `isEditable` value show normal text or a form
2. Use formik or form directly with value as the service name. (not sure if this is the right way, but I got this idea from Project Configuration)
3. Please suggest if you have another way of implementing it in mind
Can someone guide me on the right way to implement this?

**Comment by yuval-hazaz** [comment]
I think you can use both - use isEditable to change the field state, and use formik to submit the data to the server

**Comment by a-loke** [comment]
Hi, do you want to be able to change only the project name or the service name, or both? The issue says the Project name but in the Figma design, it looks like the service name

**Comment by a-loke** [comment]
Hi, Need a small help understanding the FORM_SCHEMA

```
const { AT_LEAST_TWO_CHARARCTERS, NO_SYMBOLS_ERROR } = validationErrorMessages;
const FORM_SCHEMA = {
  required: ["name"],
  properties: {
    name: {
      type: "string",
      minLength: 2,
      pattern: "^[a-zA-Z0-9]+$",
    },
  },
  errorMessage: {
    properties: {
      name: AT_LEAST_TWO_CHARARCTERS,
    },
  },
};
```
In the above schema, I have added a pattern condition, but I am not able to add more than one error message. Can someone help me here?  FYI, I have `NO_SYMBOL_ERROR` text from `validationErrorMessages`

**Comment by GreenMachine01** [comment]
@lokeswaran-aj we have a different User Story to handle changing the service name.
https://github.com/amplication/amplication/issues/4457

**Comment by lokeswaran-aj** [comment]
@GreenMachine01  I have raised a PR that allows users to change both Project and service names. Do you want me to update the code to check if it is a project name? Becoz, for #4457 I just have to remove the check. Or let the code be same?

**Comment by GreenMachine01** [comment]
@lokeswaran-aj you can just mention that your PR takes care of both stories #4559 & #4457

**Comment by lokeswaran-aj** [comment]
@GreenMachine01 Done👍

**Comment by GreenMachine01** [comment]
@lokeswaran-aj 
we are missing the edit icon
I also noticed the text jumps a bit when I click to edit it.

**Comment by overbit** [comment]
@alexbass86 can you check if any additional info / feedback is needed?
