### ISSUE TITLE
As User - I want to see a better commit message when I don't provide one myself

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4561]
As User - I want to see a better commit message when I don't provide one myself so that I get some value from the message

![Image](https://user-images.githubusercontent.com/112330500/204293577-9eaec1b2-c393-46ab-a5f6-53a362426b5f.png)

**Overview:**
Today when the user doesn't provide a "commit message" we will show a default value of "No commit message" for each such commit on the commit page. this default message adds no value to the user.

We want to improve the default message so that at least some minimal value is provided for the user.

**Requirements:**
1. When the user doesn't provide a "commit message" we will show "Commit - [id of the commit]"
2. Show only the last 8 characters of the commit id

**Comment by asharonbaltazar** [comment]
Hey, @GreenMachine01, can I try taking a shot at this? Seems like a good first issue for a newcomer!

**Comment by GreenMachine01** [comment]
Hey @asharonbaltazar  Awesome. I assigned the ticket to you. Good luck! :)

**Comment by GreenMachine01** [comment]
@tupe12334 Can you assist?

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4587

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4587
