### ISSUE TITLE
As Dev - I want to research supporting Bitbucket as a Git provider

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4563]
https://bitbucket.org/

**Research:**
**Allow login via Bitbucket**
Allow selecting the git provider on the project/service level
**Allow syncing code to Bitbucket**
Updating messaging and icons wherever relevant

![Image](https://user-images.githubusercontent.com/112330500/205922947-80cd03f2-76c9-4335-a2b3-f55bb7952166.png)

![Image](https://user-images.githubusercontent.com/112330500/205923063-b1be2513-73ed-4af7-91de-51ac554ddd4c.png)

**Comment by overbit** [comment]
It might be a good idea to spike the differences in the terminology and data models between the 3 big players before coming up with a proper model design. 
Have a look at the terminology comparison and check if there is some common groud between the 3
https://about.gitlab.com/blog/2017/09/11/comparing-confusing-terms-in-github-bitbucket-and-gitlab/

**Comment by abrl91** [comment]
Link to the Notion document: https://www.notion.so/amplication/Comparison-between-version-control-platforms-GitHub-GitLab-Bitbucket-f3c1e3ce216845fd96bc7182165f5eb7
