### ISSUE TITLE
As Dev - I want to improve our deployment process

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4579]
**Depends on:**
- [x] https://github.com/amplication/amplication/issues/4551
- [x] #4903
- [ ]  #4966

In order to improve deployment cycle experience and optimisation, we will need to review and define a strategy that will reduce friction in development and deployment to different environments.

The outcome of this card is to :

1. produce a document with a design of how the new flow will be
2. showcase to the team the new plan to gather feedback
3. raise additional issues to make the design reality

- [ ] Implement new strategy

**Comment by overbit** [comment]
Strategic solution has been explained here
https://github.com/amplication/amplication-infrastructure-next/issues/54
