### ISSUE TITLE
🐛 Bug Report: Not found page/state is missing in Client

### ISSUE THREAD

**Issue by katrieltsepelevish** [amplication/amplication#4601]
### What happened?

On editing the URL of the browser and trying to get into a page that does not exist instead of presenting a Not found page, a blue screen is shown.

### What you expected to happen

To see a Not Found page or to have any indication that the page is missing.

### How to reproduce

Launch up the Amplication Client in development mode and manually insert it into the URL: `http://localhost:3001/fsdfsdfsdf`
You'll be redirected to an empty page and only the background will be presented.

### Amplication version

1.1.1

### Environment

branch: next

**Comment by souravjain540** [comment]
@abrl91 please help here

**Comment by goingdust** [comment]
I should have a fix for this today! I'm just writing some tests for it now

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4657
