### ISSUE TITLE
🐛 Bug Report: npm run setup:dev fails on latest Node LTS (v18)

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#4603]
### What happened?

Following the README instructions for running amplication locally, `npm run setup:dev` fails on latest Node LTS (v18) due to out of date supported engines in packages.json.

### What you expected to happen

The local configuration will run on Nodejs v18+

### How to reproduce

Checkout the repo, and follow the instructions here [Getting started with local development](https://github.com/amplication/amplication#getting-started-with-local-development)

### Amplication version

1.1.1

**Comment by yuval-hazaz** [comment]
can we close this issue now?
