### ISSUE TITLE
🐛 Bug Report: Missing User type in generated code

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4609]
### What happened?

[11:51:45 AM] Starting compilation in watch mode...

src/auth/UserInfo.ts:2:22 - error TS2307: Cannot find module '../user/base/user' or its corresponding type declarations.

2 import { User } from "../user/base/user";
                       ~~~~~~~~~~~~~~~~~~~

[11:51:48 AM] Found 1 error. Watching for file changes.

### What you expected to happen

server running without errors

### How to reproduce

generate application without plugins
cd server
npm install
npm run docker:db
npm run prisma:generate
npm run db:init
npm run start:debug
see the error

### Amplication version

_No response_

### Environment

_No response_

### Are you willing to submit PR?

_No response_

**Comment by EugeneTseitlin** [comment]
in server > src > auth > UserInfo
import { User } from "../user/base/User";

file **U**ser exists, but the first letter is capital
src > user > base > **U**ser

**Comment by MoeMamdouh** [comment]
face the same issue, any related updates?  @EugeneTseitlin  @yuval-hazaz
