### ISSUE TITLE
☂️ As Dev - I want to change the Prisma client strategy in the DSG

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4613]
- [x] create Prisma module and service in the DSG
- [x] use the Prisma module in the root `app.module.ts` 
- [x] use the Prisma service in the entity services
- [x] update the prisma client in `schema.prisma` with the output property
- [x] update nestjs-cli
- [x] update import form `type-fest`

**Comment by GreenMachine01** [comment]
@abrl91 can we close this epic?

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4626Fixed by https://github.com/amplication/amplication/pull/4626Fixed by https://github.com/amplication/amplication/pull/4626
