### ISSUE TITLE
As Dev - I want to add meta data and plugins version to dsg logs

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#4624]
In the DSG running log we can add a list of all the used plugins and there versions

**Comment by yuval-hazaz** [comment]
that is a good idea! 
@GreenMachine01 please add to the backlog

**Comment by arielweinberger** [comment]
I cannot see these logs with plgin versions.

In this example I have two plugins - PostgreSQL and Prettier. Tested on Next.



![Image](https://user-images.githubusercontent.com/4976416/212938742-6cff0c10-823f-436c-8549-75898bdf3b2b.png)

**Comment by overbit** [comment]
# QA passed

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/2861984/214791814-2696f182-b597-4f5d-b490-11d0a5a4ed5e.png">
