### ISSUE TITLE
🐛 Bug Report: dashboard plugins page disappeared 

### ISSUE THREAD

**Issue by barshimi** [amplication/amplication#4631]
### What happened?

This is a non consistent bug. when click the plugin icon it collapse the application. This happened to me twice, but I couldn't reproduced it every time.

### What you expected to happen

I expect the page to load without collapse the application or without the need to refresh the page

### How to reproduce

Hard to say, I'll keep looking for a way to reproduce it

### Amplication version

1.1.2

### Environment

Browser: Chrome Version 108.0.5359.98 on macbook pro

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by endalk200** [comment]
I want to take on this issue if it is not taken.

**Comment by 01PrathamS** [comment]
heyaa, i'm interested to solve this issue

**Comment by souravjain540** [comment]
@shubham-singh-748  would you like to take this issue?

**Comment by souravjain540** [comment]
@shubham-singh-748 sure, let me know if you need any help!

**Comment by shubham-singh-748** [comment]
can you please elaborate the problem, i'm new in open-source, but will try my best to solve this....

**Comment by souravjain540** [comment]
> can you please elaborate the problem, i'm new in open-source, but will try my best to solve this....

according to description, there is a bug in the code due to which when user clicks plugin button, sometimes application collapses.

You have to run the local environment and then find the bug and solve it

**Comment by shubham-singh-748** [comment]
> > can you please elaborate the problem, I'm new in open-source, but will try my best to solve this....
> 
> according to description, there is a bug in the code due to which when user clicks plugin button, sometimes application collapses.
> 
> You have to run the local environment and then find the bug and solve it

Okay got it, thanks for it Saurav.

**Comment by souravjain540** [comment]
@shubham-singh-748  please open a support ticket in our discord

**Comment by shubham-singh-748** [comment]
> @shubham-singh-748 please open a support ticket in our discord

alright.....

**Comment by sreyahsri** [comment]
I'm interested to solve this issue

**Comment by sreyahsri** [comment]
@souravjain540

**Comment by yuval-hazaz** [comment]
not relevant after the recent changes on the UI
