### ISSUE TITLE
graphQL Error wrapper for generating error

### ISSUE THREAD

**Issue by barshimi** [amplication/amplication#4638]
### Feature description

In order to change the generated error that being send to client it needs to invoke the GraphQLError as:
```
throw new GraphQLError('You are not authorized to perform this action.', null,
      null,
      null,
      null,
      null, { extensions: {
        code: 'SOMETHING_BAD_HAPPENED ????????',
        http: {
          status: 300,
        },
      }});
```
I suggest to expose util function that let you send the parameters you want to change:
```
throw foramtedGraphQLError({
  message: 'You are not authorized to perform this action.',
  code: 'SOMETHING_BAD_HAPPENED ????????'',
  status: 300
})
```
### Use case

able to convert error to fit your own needs.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by overbit** [comment]
We should be aligned with Apollo server best practices. Have a look here  https://www.apollographql.com/docs/apollo-server/data/errors/ to see how creating custom errros

**Comment by yuval-hazaz** [comment]
closing as a duplicate of #4636
