### ISSUE TITLE
🐛 Bug Report: 'findUniqueOrThrow' does not exist

### ISSUE THREAD

**Issue by alonram** [amplication/amplication#4641]
### What happened?

Generated code compilation error. I created one-to-many parent-child entities each has a unique identifier field beside the default ID (not sure if it's related to the bug). [Parent].service.base fails to compile the async find[Childs] method.

See attached screenshot of the error
SProduct = Parent
SVariant = Child

**![findUniqueOrThrow](https://user-images.githubusercontent.com/40050499/207395651-c3564e64-e6bb-4e3b-8b91-fa70565c2eb8.png)**

**schema.prisma**
model SProduct {
  createdAt         DateTime   @default(now())
  id                String     @id @default(cuid())
  sProductShopifyId String     @unique
  sVariants         SVariant[]
  updatedAt         DateTime   @updatedAt
}

model SVariant {
  createdAt         DateTime  @default(now())
  id                String    @id @default(cuid())
  sProduct          SProduct  @relation(fields: [sProductId], references: [id])
  sProductId        String
  sProductShopifyId String
  sVariantShopifyId String    @unique
  updatedAt         DateTime  @updatedAt
}

### What you expected to happen

To compile :)

### How to reproduce

I think any parent-child entities relation will cause the error. Will be happy to attach full schema if you need

### Amplication version

1.1.1

### Environment

Node 14.15.0
NPM 7.0.11
Windows Locally

**Comment by souravjain540** [comment]
@abrl91  please look into it.

**Comment by abrl91** [comment]
@alonram did you run `npm run prisma:generat` after merging the new changes?

**Comment by alonram** [comment]
Yes I did. 
Everything else works fine, only this error.

**Comment by abrl91** [comment]
@alonram are you a member of our Discord server? Let's have a meeting there. I tried to reproduce the error but I couldn't.

**Comment by abrl91** [comment]
The issue was resolved after:
- upgrade the node version (node version > 16)
- run `npm install`
- run `npm run prisma:generate`
