### ISSUE TITLE
🐛 Bug Report: Wrong design for project name error

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4652]
In the settings page of a project when you get an error the position of the 'i' is wrong.
The 'i' should be within the input field

**Actual:**

![Image](https://user-images.githubusercontent.com/112330500/207645463-4f83e47d-ef01-4a41-8c92-64424ae33cfa.png)

**Expected:**

![Image](https://user-images.githubusercontent.com/112330500/207645632-28eb7c48-96ef-4b9f-af06-c5e1f87c7ea5.png)

**Plan:**
Make sure that TextField component is used with proper prperties. 
Make sure TextField uses styles only from design system for it's own implementation. Only positioning in a layout should be in amplication client project.
Remove/change styles in client project that affects TextField implementation.
Verify that TextField looks the same in every place where it used.

**Comment by Aadarsh805** [comment]
I'm working on it

**Comment by yuval-hazaz** [comment]
Reopen the issue following #4961

**Comment by GreenMachine01** [comment]
@sajdakabir assigned to you. good luck!

**Comment by gitstart** [comment]
@GreenMachine01 There is a PR here [https://github.com/amplication/amplication/pull/5091](https://github.com/amplication/amplication/pull/5091). You can have a look at it. Thanks

**Comment by sajdakabir** [comment]
@GreenMachine01 can you please review my PR
