### ISSUE TITLE
🐛 Bug Report: admin UI error when choosing id type `auto-increment`: type `string | number` is not assignable to type `string`

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4655]
### What happened?

Compilation error on the admin-ui when choosing id type `auto-increment`: type `string | number` is not assignable to type `string`
![image](https://user-images.githubusercontent.com/39680385/207672017-aacd1223-21cf-4bfe-a031-a5bedd5c8c68.png)

![image](https://user-images.githubusercontent.com/39680385/207672534-c4a2a3f7-a4b3-448b-9543-1ffbf0e693ef.png)

### What you expected to happen

to compile successfully

### How to reproduce

Create an order service with Id type auto-increment for customer or any entity

### Amplication version

1.1.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@GreenMachine01 please include this bug in the coming spring

**Comment by GreenMachine01** [comment]
@yuval-hazaz 

@abrl91 Already took it into the current sprint and fixed it.
