### ISSUE TITLE
create auth-core plugin

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4671]
Create `auth-core` plugin that implements the auth logic that was removed from the DSG
- [x] environment variables for JWT
- [x] package.json - missing npm packages
- [x] entity module
- [x] entity controller
- [x] entity resolver
- [x] entity service
- [x] resource service - password logic
- [x] static auth files + static test auth files
- [x] user info
- [x] token payload interface
- [x] interceptors (static files)
- [x] basic token
- [x] jwt token
- [x] token service
- [x] guards
- [x] grants
- [x] seed
- [x] constants for tests

**Comment by overbit** [comment]
@abrl91 @morhag90  is this still open?
