### ISSUE TITLE
🐛 Bug Report: generated server with auto-increment id: compilation error regarding the `parentId` 

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4677]
### What happened?

Argument of type `number` is not assignable to parameter of type `string`
![image](https://user-images.githubusercontent.com/39680385/208264731-f9d35a12-370f-4b12-a996-2ba0913e6f0c.png)

### What you expected to happen

No compilation errors

### How to reproduce

Create a service with one-to-many relations where the id type of the "many" is `auto-increment`

### Amplication version

1.1.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by arielweinberger** [comment]
To test this, make sure you have a "one to many" relation in a generated app. One of the relations needs to have an auto incrementing ID.

Creating entities should result in no errors and the ID to be auto incremented.
