### ISSUE TITLE
🐛 Bug Report: Mongo DB plugin doesn't generate prisma schema correctly 

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#4681]
### What happened?

After generating a service with the mongo DB plugin, the Prisma schema has errors. 

### What you expected to happen

Prisma schema will be format correctly. 

### How to reproduce

Create a service and build code.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abrl91** [comment]
1. when installing the prettier plugin, build, commit and merge, and then install the MongoDB plugin, the `package.json` is replaced and the `` of the prettier is removed
2. when running `prisma:push` we get this error:
```
Error: MongoDB error
Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: localhost:5432, Type: Unknown, Error: unexpected end of file }, ] }
   0: migration_core::state::SchemaPush
             at migration-engine/core/src/state.rs:381
```

I ran first in the server directory:
```
npm i
npm run docker:db
npm run prisma:generate
```

**Comment by EugeneTseitlin** [comment]
Here is an error that I receive when trying to run server in generated app:
/home/eugene/development/amplication-mongo/server/node_modules/@prisma/client/runtime/index.js:30355
          throw new PrismaClientInitializationError(error2.message, this.config.clientVersion, error2.error_code);
                ^
Error: error: Environment variable not found: DB_URL.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("DB_URL")
   | 

Validation Error Count: 1
    at LibraryEngine.loadEngine (/home/eugene/development/amplication-mongo/server/node_modules/@prisma/client/runtime/index.js:30355:17)
    at LibraryEngine.instantiateLibrary (/home/eugene/development/amplication-mongo/server/node_modules/@prisma/client/runtime/index.js:30286:5)

Please, provide steps for testing this plugin, it seems that it requires some configuration from a user.

**Comment by EugeneTseitlin** [comment]
Nothing has changed, I experience the same issue. 
@morhag90 Please, try to test it in sandbox before moving to Ready for QA.

**Comment by morhag90** [comment]
@EugeneTseitlin, I already tested it before returning it to your check. 
Did you try a new service or use the same one?
