### ISSUE TITLE
🐛 Bug Report: Deploy to next fails consistently

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#4699]
### What happened?

Deployments to `next` environment fails due to missing chart version:

https://github.com/amplication/amplication/actions/runs/3739375863/jobs/6346683171

### What you expected to happen

NA

### How to reproduce

Commit against `next` branch will auto start the deploy pipeline that will fail.

**Comment by levivannoort** [comment]
The latest few changes have been succesfull in getting the next environment to deploy consistently again. We need to look into apply the changes to the other environments aswell.
