### ISSUE TITLE
🐛 Bug Report: Amplication Server cannot find Prisma models  blocking local development

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4704]
Following a change we made a few weeks ago, where Prisma clients are generated relative to amplication-prisma-db, this started happening.

After some research it turns out that the solution is to generate the Prisma client in each service's folder.

This only affects amplication-server and ee/amplication-git-push-webhook-service.

Fixing this will unblock the errors faced during local development and does not require an immediate release.

**Comment by tupe12334** [comment]
Duplication of https://github.com/amplication/amplication/issues/4637
