### ISSUE TITLE
🐛 Bug Report: Missing static files from generated code

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#4733]
When we generate a service from a blank, static file like `tsconfig.base.ts` are missing.

**Comment by abrl91** [comment]
In a branch before moving the DSG to libs it works as expected
You can see that in the generated/server we have, for example the `tsconfig.json`, `.gitignore` and other static files
<img width="268" alt="image" src="https://user-images.githubusercontent.com/39680385/209161157-08917f3d-c00b-4847-9ad6-4897b731fba4.png">

**Comment by yuval-hazaz** [comment]
@GreenMachine01 we need to assign someone to test this before the next release
