### ISSUE TITLE
🐛 Bug Report: File not found in DSG

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4750]
### What happened?

There is an error during code generation process:

node:internal/modules/cjs/loader:1029
  throw err;
  ^

Error: Cannot find module './create-dotenv.template.env'
Require stack:
- /workspace/packages/amplication-data-service-generator-runner/node_modules/@amplication/data-service-generator/src/admin/create-dotenv.js
- /workspace/packages/amplication-data-service-generator-runner/node_modules/@amplication/data-service-generator/src/admin/create-admin.js
- /workspace/packages/amplication-data-service-generator-runner/node_modules/@amplication/data-service-generator/src/create-data-service.js
- /workspace/packages/amplication-data-service-generator-runner/node_modules/@amplication/data-service-generator/src/index.js
- /workspace/packages/amplication-data-service-generator-runner/src/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at Object.<anonymous> (/workspace/packages/amplication-data-service-generator-runner/node_modules/@amplication/data-service-generator/src/admin/create-dotenv.js:7:30)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Module.load (node:internal/modules/cjs/loader:1068:32)

### What you expected to happen

DSG has to produce code

### How to reproduce

this specific log is taken from next, but the error happens in DSG, so it can be run in other env or locally in order to reproduce the issue.

**Comment by levivannoort** [comment]
I have locally pulled the images (current and a previous one) and can confirme that the file is indeed not present in the newer image.

**Comment by levivannoort** [comment]
older image (sha: sha-b386d3f)
![image](https://user-images.githubusercontent.com/73097785/209799212-c1cd65aa-1846-49c5-903a-0ac2b4461eed.png)

current image (sha: sha-3806ba8)
![image](https://user-images.githubusercontent.com/73097785/209799324-cf1627e2-6511-488a-b9eb-9c1ea3c4a212.png)
