### ISSUE TITLE
As PO - I want to change "Community" plan texts to "Free"

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4762]
![Image](https://user-images.githubusercontent.com/112330500/209981300-49773fb8-f56c-477f-a24e-5bb68ce65f54.png)

**Comment by yuval-hazaz** [comment]
@EugeneTseitlin please note the styling @alexbass86 added in the latest version, with a different color for each plan 

<img width="371" alt="image" src="https://user-images.githubusercontent.com/43705455/210045800-804dec03-5998-4647-9fe9-382bb7c9e9ad.png">
