### ISSUE TITLE
As User - I want to be able to select the workspace I want to upgrade in the pricing page within the application

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4772]
![Image](https://user-images.githubusercontent.com/112330500/210176716-469f897a-85ea-4d49-8e9b-f1dc795918f2.png)

Design - https://www.figma.com/file/REUaAG2f5EkgyghHMvACxd/Concept----Paywall?node-id=2223%3A15294&t=oJdAJiitbsvucMw2-1

**Comment by abrl91** [comment]
fixed by  #4791
