### ISSUE TITLE
As User - I want to see how Amplication supports open source project in the pricing page

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4773]
![Image](https://user-images.githubusercontent.com/112330500/210176810-d5344bcc-a092-44c9-9eed-aca6a6250b84.png)

**Design** - https://www.figma.com/file/REUaAG2f5EkgyghHMvACxd/Concept----Paywall?node-id=2223%3A15294&t=oJdAJiitbsvucMw2-1

**Requirements:**
1. Add the "Open source" section to the pricing page according to the design example
2. Clicking on the CTA should allow the user to send an email to Yuval
3. Set the email subject to "Pro plan for Open Source project"

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4797
