### ISSUE TITLE
As User - I want my workspace name and background color to reflect the plan activated on it

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4774]
![Image](https://user-images.githubusercontent.com/112330500/210178801-b831fe28-bcfe-4851-870f-d21b7c65b8b3.png)

**Design** - https://www.figma.com/file/REUaAG2f5EkgyghHMvACxd/Concept----Paywall?node-id=836%3A18964&t=oJdAJiitbsvucMw2-1

**Requirements:**
1. Plan text color needs to match the color of the plan
2. Workspace icon background color needs to match the color of the plan

### Plan 
Each Subscription type should be associated with corresponding css class
Set color for each of these classes  
Take colors from design that is linked to the issue

Plan is written by @EugeneTseitlin

**Comment by GreenMachine01** [comment]
@EugeneTseitlin Check to do it via entitlement in Stigg

**Comment by EugeneTseitlin** [comment]
@GreenMachine01 What exactly do you want to manage via Stigg? Obtain plan status  and decide about a color in client? Manage color via Stigg?

**Comment by GreenMachine01** [comment]
@yuval-hazaz @EugeneTseitlin Please discuss how to implement this between you.
I don't have a preference to use Stigg for this or not. I think it is overkill to use Stigg for the colors and I would just do the logic on our side based on the plan of the workspace.
