### ISSUE TITLE
🐛 Bug Report: Billing period is written twice

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4790]
### What happened?

![image](https://user-images.githubusercontent.com/6080188/210248403-7782ab75-90b7-4f5f-b0eb-c2f431fdb945.png)

### What you expected to happen

it should be written once

### How to reproduce

branch epic/paywall

**Comment by gyancodes** [comment]
Hey, I want to work on this issue.

**Comment by GreenMachine01** [comment]
Cant reproduce.
