### ISSUE TITLE
As User - I want to see a footer for the pricing page within the app

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4816]
![Image](https://user-images.githubusercontent.com/112330500/210568454-57923182-ad09-4315-b339-3ce1d48837df.png)

**Design** - https://www.figma.com/file/REUaAG2f5EkgyghHMvACxd/Concept----Paywall?node-id=836%3A18964&t=BX5dEZix0iKQFgMy-1

**Requirements:**
1. Link to our terms of service page - opens in a new tab
2.  Link to our privacy policy page - opens in a new tab
3. copyright year needs to be the same as it is on our website. (2023)

**Comment by morhag90** [comment]
@EugeneTseitlin The privacy policy link redirects to broken page. (404).
