### ISSUE TITLE
🐛Bug Report: Upgrade button design not as requested

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4821]
### Plan
Go to "WorkspaceHeader" component at "amplication/packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx"
Button with className={`${CLASS_NAME}__upgrade__btn`} should obtain styles specified in the design
Changes should be specific to this use case, button in design system should not be changed
Here is the link to design:
https://www.figma.com/file/REUaAG2f5EkgyghHMvACxd/Concept----Paywall?node-id=836%3A18964&t=nVbS2L8uM0ZPI2IT-1

Plan was written by @EugeneTseitlin

**Comment by GreenMachine01** [comment]
![Image](https://user-images.githubusercontent.com/112330500/210548194-0833be01-66bf-4fd7-84b3-6b1a2a378725.png)


![Image](https://user-images.githubusercontent.com/112330500/210548221-e4f161a9-3be2-4aeb-8a0f-c80357788932.png)

**Comment by jaysoni-ash42** [comment]
@GreenMachine01  is there any design file for this change would like to work on this issue.

**Comment by GreenMachine01** [comment]
@alexbass86 please assist with the design for the button.

**Comment by GreenMachine01** [comment]
@jaysoni-ash42 I will check if you can take the item as it might be bigger than just fixing the button design.
@EugeneTseitlin can this ticket be handled by the community?

**Comment by EugeneTseitlin** [comment]
> @jaysoni-ash42 I will check if you can take the item as it might be bigger than just fixing the button design. @EugeneTseitlin can this ticket be handled by the community?

@GreenMachine01 Possibly, but this button is supposed to be a part of the design system, we have to do some preparations in order to make our development process clear and straightforward. Otherwise I might receive PR not with what we expected. Let's discuss a contributor experience separately.

**Comment by EugeneTseitlin** [comment]
It was decided to solve this issue by Amplication team.
