### ISSUE TITLE
🐛 Bug Report:  pull-request:  Github create three throw an error. 

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#4840]
### What happened?

 Pull-request service throws an error when using smart strategy. 

### What you expected to happen

Build work properly, and PR will create on Github. 

### How to reproduce

Get a pro license and try to build changes. 

### Amplication version

1.2.0

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4839
