### ISSUE TITLE
🐛 Bug Report: "Current Plan" text color doesn't match the current plan

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4842]
![Image](https://user-images.githubusercontent.com/112330500/210604006-e96910c2-02ac-4b40-908c-60a39d30a52d.png)

**Solution:**
**add the following CSS to the page:**

.stigg-plan-offering-container:nth-child(1).stigg-current-plan
  .stigg-plan-header::before {
  color: #a787ff !important;
}

.stigg-plan-offering-container:nth-child(2).stigg-current-plan
  .stigg-plan-header::before {
  color: #20a4f3 !important;
}

.stigg-plan-offering-container:nth-child(3).stigg-current-plan
  .stigg-plan-header::before {
  color: #31c587 !important;
}

**Comment by abrl91** [comment]
passed QA ✅ 


![Image](https://user-images.githubusercontent.com/39680385/228252646-bd4da85d-7c9b-4c65-9025-3a9143d4370a.png)
