### ISSUE TITLE
🐛 Bug Report: Scroll is missing in workspace selector on Purchase page

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4855]
### What happened?

![image](https://user-images.githubusercontent.com/6080188/211193843-4039cba6-5365-48a0-bef7-3e199f0b9471.png)

### What you expected to happen

To see scroll

### How to reproduce

Go to purchase page, select workspace

**Comment by GreenMachine01** [comment]
for now, we dont have the workspace selector so closing this bug.
