### ISSUE TITLE
As User - I want to see "Under Maintenance" page while the app is down

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4867]
![Image](https://user-images.githubusercontent.com/112330500/211255537-28d51b90-af87-4403-9786-8b119be22599.png)

**Design** - https://www.figma.com/file/QdyOBRPvSs1JkJ0VxV26pY/Under-maintenance-page?node-id=836%3A18964&t=dN8eqIzDxuePjnuz-1

**Requirements:**

1. Create a static "Under Maintenance" page that we will use to send users to when they try to login when we want to do maintenance work

**Comment by GreenMachine01** [comment]
@levivannoort you used the page without problems?

**Comment by levivannoort** [comment]
I did use the page itself without problems, I however ran into a small issue when running the container which didnt have any redirects on other paths than the root itself (was an nginx container with default configuration). So I guess I will open anotehr ticket for future usage of the maintenance page, in that way we can close this ticket as the page itself was used without a problem.

**Comment by levivannoort** [comment]
https://github.com/amplication/amplication-infrastructure-next/issues/66

**Comment by levivannoort** [comment]
@GreenMachine01 please confirm if the issue can be closed.
