### ISSUE TITLE
As User - I want to see appropriate page description on the browser tab for the pricing page

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4892]
![Image](https://user-images.githubusercontent.com/112330500/211544802-def42992-0382-4ea6-bd93-72b07dcc068c.png)

1. On the pricing page within the app - Set the text on the tab to "Amplication | Pricing & Plans"

**Comment by Spid3rrr** [comment]
I can take this if it's available !

**Comment by gyancodes** [comment]
@GreenMachine01 Can I work on this issue

**Comment by GreenMachine01** [comment]
@Spid3rrr assigned to you. thank you and good luck!

**Comment by GreenMachine01** [comment]
@gyancodes if it will remain open I will move it to you next.

**Comment by Spid3rrr** [comment]
Thanks ! I'll get to it !

**Comment by sajdakabir** [comment]
Hey, @GreenMachine01 is anyone working on this issue?

**Comment by GreenMachine01** [comment]
@sajdakabir ill check.
@Spid3rrr any progress on this ticket?

**Comment by Spid3rrr** [comment]
Waiting on feedback for pull request atm

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by EugeneTseitlin** [comment]
Was tested at sandbox environment
![image](https://user-images.githubusercontent.com/6080188/219432188-5ee08f09-8c18-4780-a409-9bff46a059bd.png)
