### ISSUE TITLE
Update local environment to use latest kafka components

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#4893]
### Feature description

Currently we are running locally 2 kafka components of different versions:

- `confluentinc/cp-zookeeper:5.2.4`
- `confluentinc/cp-kafka:5.3.1`

We should update them to the latest `7.3.1` version that will bring alongside new features and performance improvements a version that is closer to our staging and production environments.

### Acceptance Criteria
First case
* *Given* an amplication contributor
* *When* starts the amplication local dev environment through `npm run docker:dev`
* *Then* the amplication local environment starts successfully and the server can connect to Kafka

Additional case
* *Given* an amplication contributor
* *When* runs `npm run docker:dev:cleanup`
* *Then* the amplication local enviroment has successfully torn down

**Comment by tupe12334** [comment]
Just a note to take the CPU support into account, we use an M1 processor
