### ISSUE TITLE
🐛 Bug Report: Wrong User ID used with tracking for the "WorkspacePlanUpgradeRequest"event

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4914]
**Actual:**
The workspace id is sent as the user id

**Expected:**
The user id is sent as the user id

**Comment by abrl91** [comment]
@barshimi please linked the PR to this issue, and not the branch

**Comment by arielweinberger** [comment]
Not sure how to test this. I tried looking at the user ID sent to Hotjar in the Network tab of my browser, and it does not seem to match with the real user ID in the JSON Web Token.

It would be good to get a better description for what to test exactly.
