### ISSUE TITLE
🐛 Bug Report: Blog SSL Certificate is not valid

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4930]
### What happened?

![image](https://user-images.githubusercontent.com/6080188/212061882-38e6f2c9-7be0-406b-9beb-17ab176baf2f.png)

### What you expected to happen

well, it has to be valid :)

### How to reproduce

visit https://blog.amplication.com/

**Comment by GreenMachine01** [comment]
This URL is not used
