### ISSUE TITLE
🐛 Bug Report: youtube social media icon behind chat support. user cant click on it.

### ISSUE THREAD

**Issue by shyamtawli** [amplication/amplication#4935]
### What happened?

Front End Issue - User cant click on youtube icon behind the chat support pop up.
![image](https://user-images.githubusercontent.com/112330500/214552699-c7376225-d307-42ef-9e45-2efeb3ee5cf5.png)

### What you expected to happen

can move pop up little bit upper. so user can click on it.

### How to reproduce

NA

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by aarushisoni** [comment]
Hi, is this issue still open?
I want to work on this issue; please assign me to this.

**Comment by shyamtawli** [comment]
Hey @souravjain540 I am willing to take it. Please assign me

**Comment by shyamtawli** [comment]
I think its already have been fixed. So I am closing the Issue.

**Comment by ijoeljohn** [comment]
can i take it

**Comment by shyamtawli** [comment]
@ijoeljohn It's Closed .
