### ISSUE TITLE
🐛 Bug Report: Can't run server in local dev env when billing is not configured

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4939]
### What happened?

When I run my local env without configuration stigg I get an error 
I tried to set the env variable `BILLING_ENABLED=false` but it didn't help

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/43705455/212392413-28a109f7-d517-4755-b325-72f9af626839.png">

### What you expected to happen

The server should run successfully without billing enabled 

### How to reproduce

run the server locally using `npx nx serve amplication-server`

### Amplication version

1.2.2

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/4941
