### ISSUE TITLE
Refactor DSG code structure

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#4943]
In order to improve DevEx, the DSG library should be refactored so it would not need to be built and push as NPM package.

Potential steps needed:
- [x] Merge DSG library _back_ into DSG runner project and delete `lib/amplication-data-service-generator`
- [x] Delete/obsolete any dsg npm packages created after the release of the new version of DSG runner.

_Good to have_
- [x] _Migrate DSG runner to fully integrate with Nx._

These changes should not affect infrastructure.

### Acceptance Criteria / Testing scenarios

Scenario 1. local development 
* *Given* a contributor running amplication locally
* *When* it runs dsg jobs locally through the local runner
* *Then* the code generation process completes successfully

Scenario 2. amplication cloud environment 
* *Given* a user using the amplication platform
* *When* it clicks the `Rebuild` button
* *Then* the code generation process completes successfully and it is possible to see the Git_Reference as DSG_VERSION in the logs.

Unblock #4895

**Comment by abrl91** [comment]
Passed QA:
In the sandbox env:


![Image](https://user-images.githubusercontent.com/39680385/219015812-9fed5db0-4f2f-4840-a89e-619100c4cc88.png)


Locally:


![Image](https://user-images.githubusercontent.com/39680385/219017764-1d18dbaa-de7c-4aff-a200-27ca4119ce68.png)
