### ISSUE TITLE
🐛 Bug Report: Sync with GitHub fails 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4953]
### What happened?

When creating a new build, after the code generation completes, the sync with GitHub failes with the following messages
```
The expression evaluated to a falsy value:
  (0, assert_1.default)((0, fs_1.existsSync)(buildPath))
```

![image](https://user-images.githubusercontent.com/43705455/212527864-ad752ee1-3940-4076-a2f5-ed5fc0433785.png)

### What you expected to happen

Sync to complete successfully 

### How to reproduce

This is not steady and happened on a few projects, both free and pro - as far as I can tell it only happened to me on a project with multiple services

**Comment by tupe12334** [comment]
From my understanding is something about race conditions between writing the file and trying to read them from the file system

**Comment by tupe12334** [comment]
After testing, I found that the code crash in the code: https://github.com/amplication/amplication/blob/bb4ec39c771a3196f45bbd3e083acbd062fcef29/packages/amplication-git-pull-request-service/src/diff/diff.service.ts#L93
