### ISSUE TITLE
🐛 Bug Report: workspace list is taking a lot of time to load

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4956]
### What happened?

When opening the workspace selector, it may take a lot of time to load the list, especially when there are multiple workspaces in the list. 
This happened because we fetch the subscription data from Stigg for each item in the list separately 

### What you expected to happen

data subscription data should be saved locally and should not be fetched from Stigg 

### How to reproduce

open workspace selector

**Comment by jaysoni-ash42** [comment]
@yuval-hazaz  the request is not hitting the stigg api end point instead it is amplication server graphql endpoint
should i add a local storage cache for this issue? Need to add the local stoarge cache i on parent component where we need to make a request and also compare the old cache data to updated if it is stale.
<img width="394" alt="Screen Shot 2023-02-07 at 14 59 53" src="https://user-images.githubusercontent.com/68722497/217202339-54a9426e-b4ae-413a-b2a4-0daa2224d880.png">

**Comment by EugeneTseitlin** [comment]
@jaysoni-ash42 Please, ask to assign an issue to you before starting working on it. It's better to avoid the situation when two people are working on the same issue parallelly without knowing about that.

**Comment by EugeneTseitlin** [comment]
**Deployment**
1. Execute prisma migration
2. Add webhook in Stigg with 4 events: "subscription.created", "subscription.canceled", "subscription.expired", "subscription.updated". URL: {{server-base-url}}/subscriptions/updateStatus
Here is an example:
![image](https://user-images.githubusercontent.com/6080188/218460014-bdae7547-1a78-4eb8-b5d7-7b638ea9a02a.png)

**Comment by EugeneTseitlin** [comment]
Further steps: https://github.com/amplication/amplication/issues/5191

**Comment by levivannoort** [comment]
Deployment update:

- [ ] Migration if included should be run automatically on startup (it is part of the init container).
- [ ] Add webhook for each of the application environments.
- [ ] Add secret (`stigg_webhook_secret`) to each of the vault path's:
  - Add secret which is an output on the creation of the webhook to hashicorp vault
  - Add secret to environment variables by using the hashicorp vault path

**Comment by abrl91** [comment]
passed:


https://user-images.githubusercontent.com/39680385/219014724-e5324098-93a9-4fe2-b133-3c7cddef41b7.mov
