### ISSUE TITLE
Change on the default behaviour of class-validator

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#4958]
Lately some developers encounter a problem that blocks the server communication with the error:
```
{
  "errors": [
    {
      "message": "Bad Request Exception",
      "extensions": {
        "code": "BAD_USER_INPUT",
        "response": {
          "statusCode": 400,
          "message": [
            "an unknown value was passed to the validate function"
          ],
          "error": "Bad Request"
        }
      }
    }
  ],
  "data": null
}
```

The error came from a the PR: https://github.com/amplication/amplication/pull/4923
In the commit https://github.com/typestack/class-validator/commit/607ef61c36f8641b9dc0908a5b773fbc4fdae4e1

**Comment by arielweinberger** [comment]
This one is hard to reproduce, but since this was reported by the class-validator community and they fixed it, I think it's safe to call this QA approved.
