### ISSUE TITLE
🐛 Bug Report: Text fields look wrong throughout the system

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#4961]
### What happened?

Following this PR https://github.com/amplication/amplication/pull/4756/files some text fields look wrong 
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/43705455/212559440-18eed513-979b-476e-a364-d1daed6b1c94.png">

### What you expected to happen

should look as designed 

### How to reproduce

n/a

**Comment by pratik-codes** [comment]
If no one is working on this can you assign this to me ill take a look

**Comment by sagnik3788** [comment]
is this issue solved @souravjain540 if not can i work on it
