### ISSUE TITLE
As Dev - I want to research how to create a Plugin that adds Terraform to AWS

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4963]
Research what the plugin for Terraform code generation in regards to the AWS cloud provider should entail.

This execution after the research is dependent on being able to provide parameters to the installed plugin. This should be present before starting development.

**Comment by levivannoort** [comment]
From a DevOps Engineer/Infrastructure/Deployment point of view there should be several things very clear before developing the plugin:

- How big is the scope of the terraform code around the project? This could for example only be the service that is used to actually hosting the artifacts or do we generate everything around the platform itself (e.g., vpc, sg, ecr, et cetera)?
- We need to determine the platform that will host the artifacts, also is this a choice (i.e. eks, ec2, ecs, et cetera) or do we provide a single way to generate the terraform code?
- If we provide the terraform code to actually host the application shouldn't we also provide the pipeline to be able to build the artifact and ship it to either AWS ECR (here we run into the problem that we need the terraform code for the ecr to be present aswell) or GitHub Packages > can we have a dependency on another plugin lets say Github Actions?
- How do you we go about versioning the terraform resources that we generate? Also do we only use resources themself and 'reinvent' the wheel or do generate code that calls modules? Also how do we go about update the users generate plugin code, do we ourself from time-to-time decide on specific versions to use that we test?

**Comment by levivannoort** [comment]
@GreenMachine01 Above i provided some additional context regarding the research, but I was wondering if there already is an issue for the option to use parameters/options when interacting with plugins?

**Comment by overbit** [comment]
Additionally we should think if we want to offer to deploy as container or lambda with lambda adapters

**Comment by levivannoort** [comment]
This has since been implemented through the use of various plugins.
