### ISSUE TITLE
As Dev - I want to see an end to end recording of creating a plugin

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4964]
Select a plugin build it from scratch and record the entire process end to end with commentary
**business logic should not be included**

**Comment by barshimi** [comment]
https://amplic-my.sharepoint.com/personal/shimi_amplication_com/Documents/Recordings/recordeing%20plugin%20creation-20230201_150025-Meeting%20Recording.mp4?web=1

https://amplic-my.sharepoint.com/:v:/r/personal/shimi_amplication_com/Documents/Recordings/recordeing%20plugin%20creation-20230201_153420-Meeting%20Recording.mp4?csf=1&web=1

https://amplic-my.sharepoint.com/:v:/r/personal/shimi_amplication_com/Documents/Recordings/recordeing%20plugin%20creation-20230201_154141-Meeting%20Recording.mp4?csf=1&web=1
