### ISSUE TITLE
As Dev - I want a new automated deployment process for production 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#4966]
As part of the migration to the new infrastructure, we implemented a new set of workflows as part of #4903.

This issue is about implementing the missing part of automating the deployment to production environment.
The new workflow should follow the strategic (_FUTURE_) design: https://miro.com/app/board/uXjVP7TJ5LI=/

**Comment by levivannoort** [comment]
@overbit created a quick setup for how i think the pipeline should look, could you please give your thoughts before I continue with it.

https://github.com/levivannoort/amplication-fork/commit/07d5216415e04145ed4666b648ce2711f14f935e#diff-84dff8d1094ca39c02ac0e48d951ca22f4da29c76b50ae517f5bd2d50f94c2f6

**Comment by overbit** [comment]
It looks good to me. We will need to add an additional job that will handle the Nx affected logic and pass the projects to the matrix I assume.

**Comment by levivannoort** [comment]
Added a pull request for this issue, it however requires changes on pull request #5021 and it being merged!

**Comment by levivannoort** [comment]
When doing the release this week, we need to check if it fully works.
