### ISSUE TITLE
As User - I want to feel the purchase flow is starting "immediately" after I click the upgrade CTA in the pricing page

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4967]
**Overview**:
Currently when the user clicks to upgrade the plan on the pricing page there is a small delay until the Stripe checkout opens up.
The user might feel his click didn't work and get frustrated and potentially lead to rage clicks on the CTA.

We want to improve the experience for the user + prevent additional clicks on the CTA while the checkout process is initiating via Stigg.

**Requirements:**
1. When the user clicks the CTA we immediately darken the screen and show a loader with a message until the checkout process starts.
2. We need to make sure the user is not stuck in this state so lets make sure the notification is closed after [X time] and record this issue in our logs/events so we can track and understand what happened.

![Image](https://user-images.githubusercontent.com/112330500/212727750-7fd88940-489b-4b38-9867-23b71ed1c60c.png)

**Plan:**
- [ ] Create modal component with loader. Base Modal component exists in design system, Purchase Page can taken as an example.
- [ ] Trigger modal on `purchaseSubscription` request. 

Plan is written by @EugeneTseitlin

**Comment by EugeneTseitlin** [comment]
Here is how implementation looks like:
https://user-images.githubusercontent.com/6080188/215321097-5994060e-80d1-4937-9efb-775d53fefa2a.mp4

**Comment by abrl91** [comment]
@EugeneTseitlin  I tested it and didn't see the popup

**Comment by abrl91** [comment]
There was a problem with the deployment. The issue was resolved
