### ISSUE TITLE
Server: Record to delete does not exist in deleteEntityPermissionField

### ISSUE THREAD

**Issue by iddan** [amplication/amplication#497]
**Describe the bug**
In production, an error was thrown from prisma that a record does not exist when resolving mutation deleteEntityPermissionField.
GraphQL Query:
```graphql
mutation deleteEntityPermissionField($fieldPermanentId: String!, $entityId: String!, $action: EnumEntityAction!) {
      deleteEntityPermissionField(where: {action: $action, fieldPermanentId: $fieldPermanentId, entityId: $entityId}) {
        id
    fieldPermanentId
    __typename
  }
}
```
Stack trace:
```
Error: Query interpretation error. Error for binding '0': RecordNotFound(\"Record to delete does not exist.\")
    at PrismaClientFetcher.request (/packages/amplication-server/node_modules/@prisma/client/runtime/index.js:1:228283)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Internal log link: https://console.cloud.google.com/logs/query;pinnedLogId=2020-09-24T14:22:37.295206Z%2F5f6cabad000481262d3728f4;query=resource.type%20%3D%20%22cloud_run_revision%22%0Aresource.labels.service_name%20%3D%20%22cloudrun-srv%22%0Aresource.labels.location%20%3D%20%22us-east1%22%0A%20severity%3E%3DDEFAULT%20error%0A%20%20%22Query%20interpretation%20error%22%0A;timeRange=P7D?project=amplication-production

**Comment by yuval-hazaz** [comment]
The function deleteEntityPermissionField is already running a FindMany based on the given parameters before it runs the DELETE command.

In case the record does not exist, an error is thrown and the DELETE command is not executed.
I can imagine that the error in the log may happen in a race condition of two identical requests to delete the same field, where both the first and second requests find the specific record but then only the first request successfully delete the record and the second request is failing with the above error.

@GalCegla would you please add a test to validate that the correct Error is thrown in case invalid parameters are provided

```
const permissionField = await this.prisma.entityPermissionField.findMany({
      where: {
        permission: {
          entityVersion: {
            entityId: args.where.entityId,
            versionNumber: CURRENT_VERSION_NUMBER
          },
          action: args.where.action
        },
        fieldPermanentId: args.where.fieldPermanentId
      }
    });

    if (isEmpty(permissionField)) {
      throw new Error(`Record not found`);
    }

    const id = permissionField[0].id;

    return this.prisma.entityPermissionField.delete({
      where: {
        id: id
      },
      include: {
        field: true
      }
    });
```

**Comment by GalCegla** [comment]
Sure thing!

**Comment by GalCegla** [comment]
@yuval-hazaz  where is this function?

> ```
> const permissionField = await this.prisma.entityPermissionField.findMany({
>       where: {
>         permission: {
>           entityVersion: {
>             entityId: args.where.entityId,
>             versionNumber: CURRENT_VERSION_NUMBER
>           },
>           action: args.where.action
>         },
>         fieldPermanentId: args.where.fieldPermanentId
>       }
>     });
> 
>     if (isEmpty(permissionField)) {
>       throw new Error(`Record not found`);
>     }
> 
>     const id = permissionField[0].id;
> 
>     return this.prisma.entityPermissionField.delete({
>       where: {
>         id: id
>       },
>       include: {
>         field: true
>       }
>     });
> ```

**Comment by yuval-hazaz** [comment]
> @yuval-hazaz where is this function?
> 
> > ```
> > const permissionField = await this.prisma.entityPermissionField.findMany({
> >       where: {
> >         permission: {
> >           entityVersion: {
> >             entityId: args.where.entityId,
> >             versionNumber: CURRENT_VERSION_NUMBER
> >           },
> >           action: args.where.action
> >         },
> >         fieldPermanentId: args.where.fieldPermanentId
> >       }
> >     });
> > 
> >     if (isEmpty(permissionField)) {
> >       throw new Error(`Record not found`);
> >     }
> > 
> >     const id = permissionField[0].id;
> > 
> >     return this.prisma.entityPermissionField.delete({
> >       where: {
> >         id: id
> >       },
> >       include: {
> >         field: true
> >       }
> >     });
> > ```

in entity.service.ts
