### ISSUE TITLE
🐛 Bug Report: The log message is not as requested when sync to Git fails because of missing the readme file

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4976]
Today when the sync to Github fails since the repo doesn't have a readme file the user is not clear on what he needs to do to fix the issue.
We want to make it easier to the user to understand what he needs to do to fix the issue so that he completes the sync to Git ASAP.

This issue was already fixed by - https://github.com/amplication/amplication/pull/4088/commits/9b7e2e0a1cf203e9c2bf52930974dd42f760687b

Need to see why it stopped working properly + add automatic tests to avoid it in the future

![Image](https://user-images.githubusercontent.com/112330500/212724243-23265235-795d-4feb-8ff9-01464ae081b8.png)

Plan:
In git pull server find the request to GitHub 
when receive "Empty Repo" error, send failure message with error code and description to kafka.

Plan written by @EugeneTseitlin

**Comment by EugeneTseitlin** [comment]
Automation tests should be a separate task.

**Comment by GreenMachine01** [comment]
We now support empty repos.
