### ISSUE TITLE
🐛 Bug Report: The new strategy with the plugin with webpack caused a strange behavior in the db-plugin

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4992]
### What happened?

The new strategy with the plugin with webpack caused a strange behavior in the db-plugin.
After we updated the DSG to use the latest version of the plugin (1.2.0), the prisma schema is generated in the following way:

```
datasource postgres {
  provider = postgresql
  url      = [object Object]
}
```

instead of:

```
datasource postgres {
  provider = postgresql
  url      =  env(DB_URL)
}
```

### What you expected to happen

The prisma schema should not change

### How to reproduce

run the snapshot test while your `@amplication/plugin-db-postgres` version in the DSG is `1.2.0`

**Comment by overbit** [comment]
Related to #4997
