### ISSUE TITLE
As Dev - I want to make sure plugin API works well end to end

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#4998]
1. replace the static plugins list with the dynamic list
2. add Yaml files for the plugin catalog - done
3. Set the dropdown versions in the client - done

## Tests Results:
1. choosing a version from the dropdown list and save - passed ✅

![Image](https://user-images.githubusercontent.com/39680385/217292192-c622d3c8-7282-4302-a355-dcb72000140e.png)

2. build the app with the requested version - passed ✅

![Image](https://user-images.githubusercontent.com/39680385/217292483-45eb5ab7-b39c-4a9d-8dd4-cd2d896eaffd.png)

**Comment by abrl91** [comment]
The version dropdown doesn't work


https://user-images.githubusercontent.com/39680385/217249801-56bbc05e-cd4b-4841-8db3-542767637fef.mov

**Comment by barshimi** [comment]
it merged to next, so I'll open a new branch

**Comment by abrl91** [comment]
@barshimi 
now I'm getting this error
![image](https://user-images.githubusercontent.com/39680385/217280209-d2b70090-f547-4733-b1b1-c77f24d5ba7d.png)
