### ISSUE TITLE
🐛 Bug Report: Dynamic Installation: the plugin version that is installed is not the requested version but the latest version from npm

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5003]
### What happened?

Dynamic Installation: the version that is installed is not the version that we provide, but the latest version from npm

When we provide the following object to the `input.json` file in `amplication-data-service-generator-ruuner`, the Postgers version that get installed is the latest version npm and not the version that we asked for
```
"pluginInstallations": [
    {
      "npm": "@amplication/plugin-db-postgres",
      "enabled": true,
      "version": "1.1.7",
      "pluginId": "db-postgres"
    }
  ]
```
`amplication_modules`:

![image](https://user-images.githubusercontent.com/39680385/213161023-d73d8516-ca83-4cc8-a53f-349d0a01c7c8.png)

### What you expected to happen

I expect to see in amplication_modules the version that I asked for

### How to reproduce

copy this object at the bottom of the `input.json` file in `ampliation-data-service-generator-runner`

```
"pluginInstallations": [
    {
      "npm": "@amplication/plugin-db-postgres",
      "enabled": true,
      "version": "1.1.7",
      "pluginId": "db-postgres"
    }
  ]
```

and then run `npx nx generate-local-code amplication-data-service-generator-runner`
you will see that in `amplication_modules/package.json` you got the latest version of the plugin.

**Comment by tupe12334** [comment]
This issue is from the line https://github.com/amplication/amplication/blob/6f1534b133a170f679f0b57dff89c39bfa849345/packages/amplication-data-service-generator-runner/src/utils/Tarball.ts#L30
