### ISSUE TITLE
As User - I want to use a new "Help" menu in the top bar

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5007]
![Image](https://user-images.githubusercontent.com/112330500/211553494-d7c79f61-1a29-4339-82a3-189c04b08ad5.png)

**Design** - https://www.figma.com/file/dVFO687AHmy2JyxQMSuJIx/HubSpot-chat-within-the-app?node-id=836%3A18964&t=tf5OIU85JiDmYuCq-1

**Requirements:**
1. Add "Help" CTA that opens a menu in the top panel
3. Move the "Docs" link to be under the new "Help" menu
4. Move the "Contact Us" link to be under the new "Help" menu
5. Add "Technical Support" link that will open the proper channel on Discord - https://discord.com/channels/757179260417867879/1063337571184279582

**Comment by aarushisoni** [comment]
Hi, is this issue still open?
I want to work on this issue; please assign me to this.

**Comment by GreenMachine01** [comment]
@aarushisoni assigned to you. good luck. if you don't have access to the design, let me know.

**Comment by aarushisoni** [comment]
> @aarushisoni assigned to you. good luck. If you don't have access to the design, let me know.

Thank you for assigning me this issue. Can you please provide me access to this design link?

**Comment by GreenMachine01** [comment]
@alexbass86 please see above.

**Comment by aarushisoni** [comment]
> @aarushisoni assigned to you. good luck. if you don't have access to the design, let me know.

Hi! Can you please tell me in which file I need to make changes?

**Comment by GreenMachine01** [comment]
@EugeneTseitlin can you please assist?

**Comment by jaysoni-ash42** [comment]
@EugeneTseitlin  can i work on this issue?

**Comment by jaysoni-ash42** [comment]
@GreenMachine01  can i have the design access ?

**Comment by souravjain540** [comment]
> @GreenMachine01  can i have the design access ?
> 
> 

Sure. @alexbass86 please do

**Comment by alexbass86** [comment]
> > @GreenMachine01  can i have the design access ?
> 
> Sure. @alexbass86 please do

https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1509%3A22444&t=B1RR7JUqgIUud0pp-1

Please use this public link, thank you for your contribution.

**Comment by GreenMachine01** [comment]
@alexbass86 please review.
looks good to me.



![Image](https://user-images.githubusercontent.com/112330500/225385854-210411a6-96d8-404e-9354-46ce70d17ddf.png)

**Comment by alexbass86** [comment]
> @alexbass86 please review. looks good to me.
> 
> ![Image](https://user-images.githubusercontent.com/112330500/225385854-210411a6-96d8-404e-9354-46ce70d17ddf.png)

Looks good to me also, approved.
