### ISSUE TITLE
Create component for each step, these component should accept input from user and validate it.

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5017]
Existing components:
 
- CreateServiceWizard: 
   1. clean logic for creating a new resource
   2. remove CreateServiceWizardForm component to a new component that will handle generation settings page. 
   3.  Design the welcome page
   4. check what flow we need to trigger according to query param.
   5. navigate to the new component: createServiceName. 

New components:

- createServiceName 
- CreateServiceWizardFooter
- AuthWithGit 
- CreateGithubSync
- CreateGenerationSettings 
- CreateServiceAuthentication 
- CreateServiceCodeGeneration
- CreateServiceNextSteps

**Comment by overbit** [comment]
Tasks already added as part of #5015
