### ISSUE TITLE
Deleting Applications

### ISSUE THREAD

**Issue by iddan** [amplication/amplication#502]
**Is your feature request related to a problem? Please describe.**
Once I create an application I can not delete it

**Describe the solution you'd like**
I would like to add in the settings page of the application a delete button

**Comment by yuval-hazaz** [comment]
We should allow a user to recover a deleted app.
Also, the settings page currently contains just the roles list and should be restructured to allow more functionlity
As it does not impact the users who can always create new apps, I think we can tag this with low priority

**Comment by yenicelik** [comment]
duplicate: https://github.com/amplication/amplication/issues/1389
