### ISSUE TITLE
Vulnerability: SQL Injection and Cross-site Scripting in class-validator

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#5020]
Vulnerability scanning provided an alert for a vulnerability for a package that is used in one of the components: 

- https://github.com/amplication/amplication/security/code-scanning/74
- https://github.com/amplication/amplication/security/code-scanning/75

A package bump should suffice, we need to check if the affected component still runs after the version bump.

This issue blocked by: #5370

**Comment by tupe12334** [comment]
Has been fixed in https://github.com/amplication/amplication/pull/4923

**Comment by overbit** [comment]
this is not actually fixed since we have dependencies that rely on the vulnerable version

https://github.com/amplication/amplication/security/dependabot/638

**Comment by tupe12334** [comment]
@overbit Can you elabarate? I can't find any dependency on class-validator lower than 14

**Comment by overbit** [comment]
@tupe12334  check the package-lock files we currently have in master.

https://raw.githubusercontent.com/amplication/amplication/master/package-lock.json



![Image](https://user-images.githubusercontent.com/2861984/214789885-1c2f8d60-9b43-40bf-9359-3470a375449f.png)

**Comment by tupe12334** [comment]
@overbit we need to update @nestjs/graphql to 10.X.X by this: https://docs.nestjs.com/graphql/migration-guide manual first

**Comment by tupe12334** [comment]
And update the @nestjs/swagger package

**Comment by overbit** [comment]
Then we cannot complete this issue. We need to prioritize that work since it has been reported by community as well and it is a critical https://discord.com/channels/757179260417867879/1068895399089278996/1068895399089278996

**Comment by overbit** [comment]
@tupe12334 please review if this is now completed after updating Nestjs to v9+ and move to passed QA if positive
