### ISSUE TITLE
🐛 Bug Report: UI borders on the project view arent respected the same across different browsers

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#5022]
### What happened?

The UI borders of the services/brokers on the project page arent respected the same way across different browsers, example of this issue with chrome (same experience on firefox) on the top and safari on the bottom.

![image](https://user-images.githubusercontent.com/73097785/213466620-838b6e71-81a7-4c86-8d84-7a2f7ba30ae8.png)

The root cause of this is scrollbar-gutter in different browsers.
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter
In Chrome it works just fine. Same, of cause, in Edge.
In Safari scrollbar-gutter doesn't work because of a well-known issue: 
https://bugs.webkit.org/show_bug.cgi?id=167335 
In FF for Windows v109.0.1 it works, but in FF for Mac v109.0.1 it does not.
No issue about this was found.
 
### What you expected to happen

That the UI looks the same across different browsers.

### How to reproduce

Open app.amplication.com on different browsers

### Amplication version

v1.2.2

**Comment by levivannoort** [comment]
The workspace overview on the left hand side now also has touching borders

**Comment by gitatractivo** [comment]
Hi, I would like to work on this issue. Could you please assign it to me if it hasn't already been assigned to someone else?

**Comment by souravjain540** [comment]
> gitatractivo

@gitatractivo sure, let us know if you need some help

**Comment by hamzatrq** [comment]
Hi @souravjain540 if not assigned let me do it.

**Comment by gitatractivo** [comment]
PR done, I hope the format is correct.

**Comment by GreenMachine01** [comment]
@alexbass86 please qa this item.

**Comment by alexbass86** [comment]
> @alexbass86 please qa this item.

Excellent work, @gitatractivo thanks. Approved on my side.

**Comment by souravjain540** [comment]
@gitatractivo please share your email with me on discord.
