### ISSUE TITLE
🐛 Bug Report: cannot start the client without a stigg api key

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#5027]
### What happened?

I cannot run the client on a local dev env without a client API key for stigg

### What you expected to happen

include a default client API key in the .env for the client application.
This is a public key that anyway available on the client application and it is not a secret. 
Adding a default test key will allow the core team and any contributor to use the client without any obstacles on local dev env.

### How to reproduce

start the client

**Comment by GreenMachine01** [comment]
Duplicate of https://github.com/amplication/amplication/issues/4940
