### ISSUE TITLE
🔧 As Dev - I want to fix incorrect function name

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5031]
In the file `packages/amplication-build-manager/src/build-runner/build-runner.controller.ts` there is function that called `onCreatePRRequest` but the event is `CODE_GENERATION_REQUEST_TOPIC` that trigger on code generation request not on pull-request request

**Comment by GreenMachine01** [comment]
@tupe12334 this sounds like a quick fix. if you want you can fix it sometime as a bonus.

**Comment by lokeswaran-aj** [comment]
@GreenMachine01 Here is my PR to fix this issue #5329 Please review and merge it.

Thanks!

**Comment by GreenMachine01** [comment]
@lokeswaran-aj thank you for the help!
@tupe12334 please check it out.
