### ISSUE TITLE
As Dev - I want to refactor git sync and strategy to support multiple Git providers

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5050]
Refactor git sync and strategy to support multiple providers, and not only GitHub

**Comment by overbit** [comment]
# Test results:

Passed ✅  

Tests scenarios:
- ✅  Connect with GitHub and create a new repository
  ![Image](https://user-images.githubusercontent.com/2861984/216390385-295da27c-7922-49fb-a2fb-d95960ca0d4e.png)

- ✅   Build a new service and push to GitHub  
![Image](https://user-images.githubusercontent.com/2861984/216390777-f8319878-9d93-400b-afe5-04f5c0f61b02.png)
