### ISSUE TITLE
🐛 Bug Report: Internal Server Error when selecting GitHub repo

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5054]
### What happened?

![image](https://user-images.githubusercontent.com/6080188/214275262-5849ae88-6e85-4d19-9dd7-641c8927c7ff.png)
I'm getting internals server error when open "select repository" window.

### What you expected to happen

List should show repositories instead of error.

### How to reproduce

Go to project configuration
Go to Connect to GitHub page
Click select repository button

### Amplication version

1.2.3

### Environment

production

**Comment by GreenMachine01** [comment]
@EugeneTseitlin I couldn't reproduce it.

**Comment by abrl91** [comment]
me neither. Maybe something is wrong with you GH organization sync 
![image](https://user-images.githubusercontent.com/39680385/214683141-e9bf1aa8-06ac-4abd-ac3a-5453b62b6e23.png)

**Comment by EugeneTseitlin** [comment]
Related issue #4957
