### ISSUE TITLE
🐛 Bug Report: relation diagram doesn't appear when setting a field from type lookup (related entity)

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5058]
### What happened?

The relation diagram doesn't appear when setting a field from type lookup (related entity)

https://user-images.githubusercontent.com/39680385/214300530-5938c368-b06f-4834-961c-766e2dc4e1bd.mov

### What you expected to happen

When I set a field from type related entity, the respective diagram (from the selected radio button) should appear

### How to reproduce

See in the screen recording

**Comment by EugeneTseitlin** [comment]
Thanks for the contribution!
