### ISSUE TITLE
As a Dev - I want to have a clean docker desktop after running DSG locally

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5084]
### Feature description

Currently, the `local-dsg-runner` will create a `dsg` container for every build and leave it exited.
I'd like to have the option to auto-remove the container from the DockerDesktop (Docker Engine) that can be enabled and disabled in case I need the completed container there for further investigation.

### Acceptance Criteria

* *Given* a contributor
* *When* it runs dsg jobs locally through the local runner
* *Then* its docker desktop dashboard shows only the dsg job container for during its execution, removing it automatically at the end of the code generation

### Are you willing to submit PR?

Yes

**Comment by EugeneTseitlin** [comment]
@overbit I assume that you were working on this issue. If so, please, set yourself as assignee.
