### ISSUE TITLE
🐛 Bug Report: Loading animation is flickering

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5099]
### What happened?

https://user-images.githubusercontent.com/6080188/215755699-5f674223-e3a8-4989-ab4a-bd76a805995b.mp4

Sometimes loading animation in flickering. 
In some cases we can see that screen start rendering in the middle of the screen and then jumps up. 
Sometimes we can see at first "planet" loader, then small spinner loader, and then empty state in project. So, we have 3 loaders in one page.

### What you expected to happen

Loading should just disappear. There should be only one loader.

### How to reproduce

Run amplication client.
Refresh multiple times.
Issue is con consistent, so many retries may be required.

**Comment by theVJagrawal** [comment]
Can I work on this issue? I am pretty new to open source stuff

**Comment by EugeneTseitlin** [comment]
@alexbass86 please, share your opinion about proper UX.

**Comment by overbit** [comment]
## Tests result report (for PR #)

### Scenarios
	
1. Scenario description: hot reload on multiple pages
	 Status: `PASSED` 
	 Proof of execution: 

https://user-images.githubusercontent.com/2861984/221556740-62a4ced4-137b-48df-a381-95f9fc5d7293.mov
