### ISSUE TITLE
As Dev - I want to review plugin build recordings and open bugs or requests on the issues found

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5107]
Based on recordings available here https://github.com/amplication/amplication/issues/4964. Open new issues for each of the problem reported.

**Comment by EugeneTseitlin** [comment]
Here are the issues than were opened based on the recording:
https://github.com/amplication/amplication/issues/5130
https://github.com/amplication/amplication/issues/5124
https://github.com/amplication/amplication/issues/5123
https://github.com/amplication/amplication/issues/5122

**Comment by barshimi** [comment]
#5122 is fixed already

**Comment by barshimi** [comment]
I would also add issue related to debug plugin and set template as a stand alone repo to cloned

**Comment by EugeneTseitlin** [comment]
> I would also add issue related to debug plugin and set template as a stand alone repo to cloned

What about it? What should be improved?

**Comment by barshimi** [comment]
lets add an issue about local debug plugins
create a stand alone repo for the template

**Comment by overbit** [comment]
@GreenMachine01  let's review the issues created by @EugeneTseitlin and close this issue

**Comment by barshimi** [comment]
yes, we did
