### ISSUE TITLE
As Contributor - I want to improve the DSG application naming 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5116]
## Descrition

Currently, `amplication-data-service-generator-runner` project doesn't follow the naming convention that disallows the `amplication-` prefix from a project name since it is redundant.

To be compliant with the convention, we will need to rename `amplication-data-service-generator-runner` into `data-service-generator`.

> 1. Do we want to change the name of the package to data-service-generator (without "runner")? Or maybe, did you leave the name of the package as it is to avoid any impact on the deployment?
> 2. How do we plan to merge this PR with @morhag90's PR for no-auth?
>
>_Originally posted by @yuval-hazaz in https://github.com/amplication/amplication/issues/5086#issuecomment-1413240663_

## Tech Notes

Since our infrastructure is based on application naming, we will need to create / update the following as part of this task:
- [ ] update the Dockerfile to COPY the newly named `dist` folder 
- [x] create a new AWS ECR called `amplication-data-service-generator` in the **operation** AWS account
- [ ] create a new manifest for the "new" application by duplicating the current `amplication-data-service-generator-runner` + update the sensor references to the new images repository:
    - [ ] https://github.com/amplication/amplication-manifests/pull/44
- [ ] ...

**Comment by levivannoort** [comment]
@overbit I think all the work is done on the issue above, I have added the infrastructure related pull-request. These need to be merged in the following order:
- staging: after merge to master the pr can be merged.
- production: after a release on amplication/amplication the pr can be merged.
- clean-up: after succesful release, undraft PR and merge to remove old application
