### ISSUE TITLE
🐛 Bug Report: The event for a successful upgrade is not showing up on Amplitude

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5118]
A user upgraded his account but I am not seeing the event "WorkspacePlanUpgradeCompleted" on Amplitude
Event should be issued based on event that arrived from Stigg
WorkspacePlanUpgradeRequest and WorkspacePlanDowngradeRequest event should stay

### Plan
Go to amplication-server -> subscription.controller.ts
Add event tracker to updateStatus method for "subscription.created" and "subscription.updated" events types

Plan is written by @EugeneTseitlin

**Comment by yuval-hazaz** [comment]
see comment on https://github.com/amplication/amplication/issues/5364

**Comment by EugeneTseitlin** [comment]
> see comment on #5364

commented there too
