### ISSUE TITLE
As User - I want to be able to use private plugins

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5121]
As a plugin developer, I want to mark a plugin as private and specify the organization that has access to it, so that it is only available to members of that organization.

**Overview:**
Our users will want to have private plugins. plugins that are available only to them.

**Figma** - 

**Requirements:**

1. Plugin developer is able to mark a plugin he develops as private
2. Plugin developer is able to specify the organization that has access to the plugin (we need to think about this one)
3. Plugin is marked as "Private" in the UI and is visually distinguishable from public plugins.
4. Private plugins should have a dedicated area in the UI for the user to quickly view and use his org private plugins
5. Only members of the specified organization can see and use private plugins.

**Comment by barshimi** [comment]
I would split this task to two:
* add private key to plugin and use it on DSG
* add permission to plugins

**Comment by yuval-hazaz** [comment]
The way I see it - 
1. Enterprise organization has an extra button on the plugin page, "Add Private Plugin".
2. The user will have a setting page in which he can upload the plugin and set the plugins properties (see this file for the list of properties we currently use in the catalog https://github.com/amplication/plugin-catalog/blob/master/plugins/db-mongo.yml)
3. The plugin will be uploaded and saved in Amplication storage (not in npm)
4. The plugin will be available for all projects and services of the workspace 
5. Users will be able to use the plugin usually like all other public plugins
6. The private plugins will indicate that they are "private."

**Comment by EugeneTseitlin** [comment]
Here is my suggestion:
Integrate support of private npm registry by Amplication. There are many of them: [AWS CodeArtifact](https://aws.amazon.com/blogs/devops/publishing-private-npm-packages-aws-codeartifact/), [JFrog NPM Registry](https://www.jfrog.com/confluence/display/JFROG/npm+Registry), [Verdaccio](https://verdaccio.org/), [Sonatype](https://help.sonatype.com/repomanager3/nexus-repository-administration/formats/npm-registry). But a special attention I would pay to [GitHub Packages](https://docs.github.com/en/packages). We're already tightly integrated with GitHub, we already ask for read-write access permissions, so this functionality can be added easier. 
**Pros:**
1. **No maintenance.** The main advantage of it is that Amplication won't store users' artifact and manage them. Keeping such a data on our side would include version management, access management, persistent storage. It's a lot of maintenance work. 
2. **User experience** Users won't have to manually upload versions every time. Most probably users already use private npm registry, so integration would just provide a nice user experience.
**Cons**
1. **Repository incompatibility.** Not every repository works the same way, so it may cause us to spend an additional time for integration of different systems.
