### ISSUE TITLE
Extract the amplication branch creation logic from the provider to the service

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5129]

**Comment by abrl91** [comment]
The PR was merged into an umbrella branch and no to the next branch, so this issue cannot be tested

**Comment by overbit** [comment]
@tupe12334 is there any feasible way to test this issue?

**Comment by EugeneTseitlin** [comment]
@tupe12334 How should it be tested? Is it refactoring? Does it mean that everything just should work as before?

**Comment by tupe12334** [comment]
There isnt a way to test it, just when the umbrula branch merges, making sure that the functionality works properly.
