### ISSUE TITLE
🐛 Bug Report: Plugin api not working because of useGlobalPipes configuration

### ISSUE THREAD

**Issue by barshimi** [amplication/amplication#5134]
### What happened?

Plugin api not working because of useGlobalPipes configuration

### What you expected to happen

getting error on API requests

### How to reproduce

add forbidUnknownValues: false to useGlobalPipes

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by overbit** [comment]
## Tests result report (for PR #)

### Scenarios
	
1. Scenario description: making graphql requests to plugin api returns data
	 Status: `PASSED` 
	 Proof of execution: 

![Image](https://user-images.githubusercontent.com/2861984/219598419-53076c92-189a-495d-95c1-8f0352b7d7ce.png)
