### ISSUE TITLE
🐛 Bug Report: Warnings about exports in client logs

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5139]
### What happened?

WARNING in ../amplication-design-system/src/index.ts 46:0-104
export 'Props' (reexported as 'FullScreenLoaderProps') was not found in './components/Loader/FullScreenLoader' (possible exports: FullScreenLoader)

WARNING in ../amplication-design-system/src/index.ts 47:0-89
export 'Props' (reexported as 'LoaderProps') was not found in './components/Loader/Loader' (possible exports: AnimationType, Loader)

### What you expected to happen

These warning should not appear.

### How to reproduce

run client and see the logs.

**Comment by morhag90** [comment]
PAASED QA:
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/97830649/221810107-315ac15e-bb93-4b99-b0d7-7fabaf03dde5.png">
