### ISSUE TITLE
🐛 Bug Report: Warning in client logs caused by Profile Form component

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5141]
### What happened?

WARNING in ./src/Profile/ProfileForm.scss (../../node_modules/@nrwl/webpack/src/utils/webpack/plugins/raw-css-loader.js!../../node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[5].use[2]!../../node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[5].use[3]!./src/Profile/ProfileForm.scss)
Module Warning (from ../../node_modules/postcss-loader/dist/cjs.js):
Warning

(57:3) autoprefixer: end value has mixed support, consider using flex-end instead

### What you expected to happen

Warning should not appear.

### How to reproduce

run client locally and see the logs.

**Comment by olalekanteeblaze** [comment]
@EugeneTseitlin I'll like to work on this

**Comment by olalekanteeblaze** [comment]
@EugeneTseitlin there is no ProfileForm.scss in the codebase. How can I find this?

**Comment by GreenMachine01** [comment]
@EugeneTseitlin can this item be fixed by the community? please see question above.

**Comment by souravjain540** [comment]
@olalekanteeblaze  would you like to take this issue. This issue comes under TIFT campaign and can reward you some cool swag :)

**Comment by Jyotiraditya24** [comment]
hey, could I take up this issue?

**Comment by souravjain540** [comment]
@Jyotiraditya24 sure!

Join our discord for any help, try to solve it as early as possible, team would love to help :)

Link: [https://amplication.com/discord](https://amplication.com/discord)

**Comment by Jyotiraditya24** [comment]
fixed the little bug , i will make PR soon 
should the pull request have a format?

**Comment by souravjain540** [comment]
> fixed the little bug , i will make PR soon 
> 
> should the pull request have a format?
> 
> 
> 
> 

It's mentioned in contributing.md

**Comment by Jyotiraditya24** [comment]
Pull Request is done ,I hope everything is in correct order

**Comment by abrl91** [comment]
passed QA ✅ 


![Image](https://user-images.githubusercontent.com/39680385/225611827-63f34a76-504e-481b-8901-f5ea3407ee39.png)

**Comment by souravjain540** [comment]
@Jyotiraditya24 please share your email with me on Discord(for swags) :)
