### ISSUE TITLE
As Dev - I want to add unit tests to amplication-build-manager package

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5147]
### Feature description

In order to facilitate future refactoring, we will need to add unit tests to cover logic defined in `amplication-build-manager`.
Since in this issue, we are not defining the use case / requirements to test, the tests should cover the most run code branches like:
- `build-runner.service.ts`
- `build-runner.controller.ts`
- `build-logger.controller.ts`

**Comment by prdalai** [comment]
I want to take this if it's available

**Comment by souravjain540** [comment]
@prdalai sure. Let me know if you need any help

**Comment by shubham-singh-748** [comment]
hey is this issue is still available, if yes then i would happy to contribute

**Comment by souravjain540** [comment]
@prdalai any updates?

**Comment by souravjain540** [comment]
> @overbit @souravjain540 May I have this issue assigned to me?  
> 
> I would like to provide MR.

Assigned :)

**Comment by ognjenjevremovic** [comment]
Tests have been provided for the most run code branches, like mentioned in the issue, as part of PR #6053 🚀 .
