### ISSUE TITLE
As Dev - I want to add unit tests for amplication-storage-gateway

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5148]
### Feature description

In order to facilitate future refactoring, we will need to add unit tests to cover logic defined in `amplication-storage-gateway`.
Since in this issue, we are not defining the use case/requirements to test, the tests should cover the most run code branches like:

storage.service.ts
codeAccessGuard.guard.ts

**Comment by 01PrathamS** [comment]
I wanted to take on this issue if not taken

**Comment by souravjain540** [comment]
@01PrathamS sure. Let me know if you need any help

**Comment by shubham-singh-748** [comment]
hey is anyone working on this, if not then i will feel grateful to work on this...

**Comment by PrinceTayal** [comment]
@souravjain540 I would like to work on this issue please

**Comment by 01PrathamS** [comment]
> @01PrathamS sure. Let me know if you need any help

Sorry, Saurav I can't figure out how to make this, I read  contributors guide and get help from chatgpt it shows code, but how do i do it?

**Comment by souravjain540** [comment]
@PrinceTayal  would you like to do it?

**Comment by vickywane** [comment]
Hi @souravjain540 

I'll like to take this up. 
What's the expected timeframe to finish it up?

**Comment by souravjain540** [comment]
@vickywane assigned :)

**Comment by souravjain540** [comment]
@vickywane any updates?

**Comment by vickywane** [comment]
Hello @souravjain540 

I am almost done with this. 
I'll finish it up within a little more time. 

:)

**Comment by souravjain540** [comment]
@vickywane any updates on this? can we help?

**Comment by byt3h3ad** [comment]
I can help with this, if I can get an example of what and how it is to be done :D

**Comment by ognjenjevremovic** [comment]
Hey @overbit, may I take this issue and provide PR?
I would like to contribute with unit tests for both `storage.service.ts` and `codeAccessGuard.guard.ts` 🚀 .

**Comment by byt3h3ad** [comment]
hey @ognjenjevremovic you can take up #5147 if it's alright with you.

**Comment by souravjain540** [comment]
@ognjenjevremovic you still want to work on it?

**Comment by ognjenjevremovic** [comment]
Hey @souravjain540, yes feel free to assign the issue to me 🙂.

**Comment by ognjenjevremovic** [comment]
Tests have been provided as part of #6361 🙂.

**Comment by sreyahsri** [comment]
hey @souravjain540 please assign me to this issue
