### ISSUE TITLE
failed to save changes on plugin settings changes

### ISSUE THREAD

**Issue by barshimi** [amplication/amplication#5149]
@barshimi 
now I'm getting this error after clicking on save
![image](https://user-images.githubusercontent.com/39680385/217280209-d2b70090-f547-4733-b1b1-c77f24d5ba7d.png)

_Originally posted by @abrl91 in https://github.com/amplication/amplication/issues/4998#issuecomment-1420912968_

**Comment by overbit** [comment]
@barshimi can we add a slightly more descriptive description please?

**Comment by barshimi** [comment]
when user change plugin version and press save, the process fail. this page should contain changes in settings and plugin version. I fixed this issue
