### ISSUE TITLE
🐛 Bug Report: wrong space in the entity field names

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5165]
### What happened?

Wrong space in the entity field names

![image](https://user-images.githubusercontent.com/39680385/217809669-223818c9-37ad-4a2d-8ab4-0b6b7eb9e9ad.png)

### What you expected to happen

@alexbass86 can you please add screenshots and link to the design on Figma

### How to reproduce

project > service > entities > User > look at the fields

### Amplication version

next (1.2.4)

**Comment by abrl91** [comment]
@alexbass86 can you please add screenshots and link to the design on Figma (don't forget to make the link accessible for the community)

**Comment by abrl91** [comment]
> I am interested in this. Let me know what the final design should look like. Thanks!

I assigned you. 
I think you can take the design from production https://app.amplication.com 
Be aware that this bug is in branch `next` so checkout to this branch and from that branch to your branch.
After that, follow the readme file.
Good luck!

**Comment by kushalnl7** [comment]
Okay @GreenMachine01

**Comment by abrl91** [comment]
passed QA in all pages - ✅

example:

![Image](https://user-images.githubusercontent.com/39680385/220070619-a661eb58-c79e-4192-93c4-ca44eed6bbfe.png)

**Comment by alexbass86** [comment]
> passed QA in all pages - ✅
> 
> example:
> 
> ![Image](https://user-images.githubusercontent.com/39680385/220070619-a661eb58-c79e-4192-93c4-ca44eed6bbfe.png)

Love it! Approved on my side as well
