### ISSUE TITLE
🐛 Bug Report: GitHub connection issue

### ISSUE THREAD

**Issue by mihailShumilov** [amplication/amplication#5189]
### What happened?

I have tried deploy at local env amplication.
all works except github connection and pull request

### What you expected to happen

I expect that github connection would work

### How to reproduce

https://www.youtube.com/watch?v=rFbG8hV4jb8

https://www.youtube.com/watch?v=n3X0SGYxnkE

### Amplication version

1.2.3

### Environment

Node v16.13.0
NPM 8.1.0
Docker version 20.10.17, build 100c701
OS MacOS 13.2 (22D49) (M1 pro)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GreenMachine01** [comment]
@abrl91 can you look into this?

**Comment by overbit** [comment]
Hi @mihailShumilov, did you follow our docs when you configured your github app? 
https://docs.amplication.com/running-amplication-platform/connect-server-to-github/

**Comment by overbit** [comment]
@mihailShumilov sorry, after reviewing the documentation we realized that it was not up to date. 
I've raised a PR about it and you can use the configs there right now until we release the update to our docs.amplication.com website.
