### ISSUE TITLE
As Dev - I want to have git installed on the `git-pull-request-service`

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5198]
Because we work with a local clone of the repository we need to have the git engine installed on the container

**Comment by levivannoort** [comment]
This issue is two fold, we need to a versioned pinned package of `git`. This needs to be added to the current Dockerfiles but also the the ones that will replace the current once starting next sprint (pr: https://github.com/amplication/amplication/pull/5065).

**Comment by levivannoort** [comment]
Updated the status, @tupe12334 can you please let me know if the addition to the dockerfile now lets you do the things you want from the source code side?

**Comment by tupe12334** [comment]
@levivannoort I still didn't got there, but i will update you

**Comment by EugeneTseitlin** [comment]
Didn't pass QA.
In sandbox environment current image version of git pull service is:
439403303254.dkr.ecr.us-east-1.amazonaws.com/amplication-git-pull-request-service@sha256:8737fe951d98ba32379d98d7f3996b2d9937a0c3acd2c1665599afe7a9edc50f
Here is an output from git version:
`<<K9s-Shell>> Pod: sandbox/git-pull-request-service-559684bff6-s878k | Container: git-pull-request-service 
/app # git -v
sh: git: not found` 
@levivannoort Please, make sure that change actually works and deployed to sandbox.

**Comment by levivannoort** [comment]
@EugeneTseitlin you're right, it was merged into an umbrella branch, so thats why it isnt present on sandbox. I specifically ready for QA as it should be QA'ed by Ofek. But that is confusing for anyone else that tries to pick up the ticket. Sorry for the confusion and time wasted.
