### ISSUE TITLE
📖 Documentation: Auth-core Plugin 

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#5209]
### Description (What is it?)

This plugin will add all the basic modules required for authentication to the service. 
Without this plugin installed, there will be no authentication to the service. 
This plugin must be installed with one of the following plugins: 
1. auth-basic
2. auth-jwt 

### Use Case (Why does the user need it?)

The user will need this plugin to create a service with authentication, roles, and permissions (not public ones).

### Issue URL

https://github.com/amplication/amplication/issues/4431

### Pull Request URL

https://github.com/amplication/amplication/pull/5206

### How it works (How does the user use it?)

The plugin shows on the plugin list of each service. 
Go to service => click on the plugin icon (right side). 
Click install on the auth-core plugin and also install one of the following plugins:
auth-basic
auth-jwt 

Now you are ready to go!
Click on Build 
go to the created app and see the files generated with authentication. 

### Screenshots

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/97830649/218995112-8ad3c4f8-5db0-4407-b839-70ffda36ae5d.png">

### Code Samples

N/A

### Figma URL

N/A

### For the release notes:

The auth plugins are installed by default when a new service is created. 
Temporary, if you choose the uninstall auth plugins after pushing it to Github, the changes will not be reflected in the customizable files (files that are not in the base folder), and you will need to fix it manually.

You will get the following compilation errors:

![image](https://user-images.githubusercontent.com/39680385/220408154-748a1c71-a644-4d75-82a7-b0fedd4012eb.png)

- You have to remove imports from files that do not exist, for example: `../auth/gqlDefaultAuth.guard`
- You have to remove the `rolesBuilder` from the `super()` in the constructor (in each entity controller/resolver).

**Comment by MoFoGo** [comment]
@morhag90  What do you mean by "Temporary" in the following sentence:


**Temporary**, if you choose the uninstall auth plugins after pushing it to Github, the changes will not be reflected in some files, and you will need to fix it manuall

**Comment by morhag90** [comment]
@MoFoGo I mean that for now, this is the situation.
In the future version, we will change this behavior so that the user will no longer need to handle those files manually.

**Comment by MoFoGo** [comment]
This is resolved with PR https://github.com/amplication/docs/pull/243
