### ISSUE TITLE
🐛 Bug Report: README is not part of generated services in next

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5212]
### What happened?

Generating a new service or rebuilding an existing resource, will generate code that is missing the README.md files.

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/2861984/219045557-9016d09f-8866-4f84-b7a3-ce5a7a8bdd51.png">

### What you expected to happen

A README file per service will be present with instructions about how to run the service.

### How to reproduce

Run a build in sandbox environment

### Amplication version

1.2.4

**Comment by levivannoort** [comment]
## Tests result report (for PR #5219)

### Scenarios
	
1. Scenario description: Run the data service generator and expect a readme file for each of the generated services
	 Status: `PASSED`
	 Proof of execution: 
	 

<img width="1512" alt="Screenshot 2023-02-16 at 12 30 22" src="https://user-images.githubusercontent.com/73097785/219353460-b2fc74be-58b3-47b3-b7e3-939bf6faf11c.png">
