### ISSUE TITLE
🐛 Bug Report: `Continue to GitHub` button is clickable outside(above) the button

### ISSUE THREAD

**Issue by lokeswaran-aj** [amplication/amplication#5215]
### What happened?

The `Continue to Github` button has an extra margin-top so it is clickable in that margin area.

<img width="1496" alt="Screenshot 2023-02-16 at 12 13 46 PM" src="https://user-images.githubusercontent.com/74011196/219288692-f55b5297-099f-4779-8d38-f33db9bd7c49.png">

### What you expected to happen

The link should not be clickable outside the `Continue to GitHub` button

### How to reproduce

Go to [https://app.amplication.com/login](https://app.amplication.com/login). Click above the `Continue to Github` Button and you will be able to login.

### Amplication version

v1.2.3

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment]
@GreenMachine01 @alexbass86 please validate this issue

**Comment by GreenMachine01** [comment]
It should be fixed but its a low-priority bug so if someone from the community wants to tackle it would be great.

**Comment by gitstart** [comment]
@souravjain540  can i work on this issue?

**Comment by gitstart** [comment]
> It should be fixed but its a low-priority bug so if someone from the community wants to tackle it would be great.

@GreenMachine01  can you assign this to me ?

**Comment by GreenMachine01** [comment]
@gitstart amazing. assigned to you. thanks!

**Comment by souravjain540** [comment]
> @souravjain540  can i work on this issue?
> 
> 

For sure! Would love to have a talk with you and offer you some swag.

Can we talk? Are you on our discord?

**Comment by levivannoort** [comment]
Passed QA:



![Image](https://user-images.githubusercontent.com/73097785/223678610-18e2f050-e146-4f97-8690-eb9d5d9ca2e9.png)

**Comment by lokeswaran-aj** [comment]
Thank you @prakhar2407 for your contribution💖. Closing this issue.
