### ISSUE TITLE
🐛 Bug Report: Base directories of Message broker resource is throwing error

### ISSUE THREAD

**Issue by lokeswaran-aj** [amplication/amplication#5220]
### What happened?

When I tried to view the base directories of the Message broker resource, I could not view the directory. Instead, an error was thrown `Cannot return null for non-nullable field Query.projectConfigurationSettings` I m not sure if this error is intentional or a bug as this is the first time I created a message broker resource
<img width="1491" alt="Screenshot 2023-02-16 at 5 31 26 PM" src="https://user-images.githubusercontent.com/74011196/219360488-1138acb8-e6be-41d2-ab77-8a60ce551649.png">

### What you expected to happen

View the base directories of the message broker resource.

### How to reproduce

- create a message broker resource
- click on the `Settings` icon in the left bar
- click on the `Base directories`

### Amplication version

v1.2.3

### Environment

OS: macOS
Browser: Chrome

**Comment by kabhamo** [comment]
Hi @overbit , @lokeswaran-aj 
After reviewing the code, I believe I can fix the bug, I will be happy if you can assign the issue to me.
Thank you :)

**Comment by lokeswaran-aj** [comment]
Thanks @kabhamo But this issue was assigned to me last night only. Give me a day or two to work in this. If I cant fix it, I'll let you know

**Comment by kabhamo** [comment]
No problem, by the way, my PR is ready.
Waiting for an update from you @lokeswaran-aj.
have a good day 🚀

**Comment by lokeswaran-aj** [comment]
@kabhamo Sorry, please go ahead with your PR, I was confused with another issue. I created this issue for the community🤞

**Comment by kabhamo** [comment]
@lokeswaran-aj thanks for the update.

**Comment by kabhamo** [comment]
@overbit, please let me know if you are interested to assign this issue to me.
So I can create the PR.
have a good day

**Comment by souravjain540** [comment]
> @overbit, please let me know if you are interested to assign this issue to me.
> 
> So I can create the PR.
> 
> have a good day 

Assigned:) let us know if we can help in anything
