### ISSUE TITLE
🐛 Bug Report: Git smart strategy is used on valid FREE subcriptions

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5221]
### What happened?

As a FREE plan subscriber, when I trigger a new build and sync with GitHub, the smart git strategy is used instead of the basic strategy.

### What you expected to happen

Only users of subscription plans that are configured with the smart git strategy feature should be able to leverage the git smart pull request strategy

### How to reproduce

As a FREE plan user, trigger a build and observe the created PR in GitHub. 
The smart strategy will create a single static branch called `amplication` with one or more commits related to the generated resources.

### Amplication version

next

**Comment by overbit** [comment]
@morhag90 can you please add your testing results here? https://www.notion.so/amplication/Manual-Tests-Result-Report-7641b1a32bec4c5b8e857f6ef0763a06

**Comment by EugeneTseitlin** [comment]
Passed QA. PRs create a separate brach and not a commit in 'amplication' branch.


![Image](https://user-images.githubusercontent.com/6080188/219946231-eef45caf-2e95-4aa7-9eaa-49b76cf44098.png)
