### ISSUE TITLE
🐛 Bug Report:  Git smart Strategy failed for some services 

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#5224]
### What happened?

When I build code that contains four services and have a Pro license, I get the following error for 2 of the services: 

<img width="926" alt="image" src="https://user-images.githubusercontent.com/97830649/219433759-6a1d582c-d556-4578-a5d2-63308f249259.png">

<img width="819" alt="image" src="https://user-images.githubusercontent.com/97830649/219433929-e0047300-e48c-40f0-82dd-d6c3731e797e.png">

The other two are successfully pushed to Github. 

### What you expected to happen

All the services will successfully pass the Push changes to GitHub step. 

### How to reproduce

1. Upgrade your workspace to a Pro license (if you have already upgraded your workspace, there is no need for this step). 
2. Connect to a GitHub app => in the Project settings level. 
3. Choose a repository from your git organization. 
4. Make sure you have at least four services in your project. 
5. Click on the Rebuild button. 
6. Goto commits page and check the status of each of the services (the step that failed for some of the services is:  Push changes to GitHub). 

### Amplication version

1.2.3

**Comment by overbit** [comment]
The issue seems to be related to some race condition since it only appear to happen on build with several services

**Comment by overbit** [comment]
@GreenMachine01 this is not a blocker for the release since it happens already in production today



https://user-images.githubusercontent.com/2861984/219707829-8f095c5e-6ff0-4e5b-8759-53ea6134b4ec.mov

**Comment by overbit** [comment]
@EugeneTseitlin this issue might be related to a race condition in the pull request process

**Comment by EugeneTseitlin** [comment]
Confirm the issue:
![image](https://user-images.githubusercontent.com/6080188/220983227-6ca6b712-f841-4d4a-9600-f910661dcf49.png)
![image](https://user-images.githubusercontent.com/6080188/220983292-5346a7e7-7f7f-4f4c-939e-139c2dbb57dd.png)
