### ISSUE TITLE
🐛 Bug Report: server models are created in the wrong location

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5230]
### What happened?

When generating the graphql models, these are created in the wrong location (where the DSG used to be). 
This will cause the DSG to run with outdated version of models.ts 

### What you expected to happen

references to the old DSG lib should be updated to the new location

### How to reproduce

Run `npm run graphql-codegen` and observe the created files

### Amplication version

next

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MichaelSolati** [comment]
Heya, the graphql-codegen script is still being called by the setup:dev script. It should be removed from there as well I think.

**Comment by overbit** [comment]
Great point @MichaelSolati ! I've raised an issue https://github.com/amplication/amplication/issues/5249 and create a fix soon
