### ISSUE TITLE
As User - I want to see a different icon for the Auth core plugin

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5254]
![Image](https://user-images.githubusercontent.com/112330500/220656810-c3874091-1521-48b2-8f92-39f0a6e78eba.png)

![Image](https://user-images.githubusercontent.com/112330500/220657054-a1e1c92c-f2a8-49d9-b373-8c41ff58cfc3.png)

**Requirements:**
1. Change the icon used for the core auth plugin to the icon attached.

**Design** - https://app.asana.com/0/1203063034994255/1204003512683825/f

**Comment by ibrahiim** [comment]
Hello, i'm interested to take this issue. Can you guide me on which file to change ? Thank you !

**Comment by aaaaayushh** [comment]
Hello can this issue be assigned to me?

**Comment by GreenMachine01** [comment]
@ibrahiim assigned to you. good luck!
@EugeneTseitlin can you please assist?

**Comment by GreenMachine01** [comment]
@ibrahiim any updates?

**Comment by endalk200** [comment]
I want to take on this issue if it is not taken.

**Comment by souravjain540** [comment]
@endalk200  assigned another issue to you

**Comment by ankur0904** [comment]
I want to work on this issue.

**Comment by souravjain540** [comment]
@ankur0904  assigned this issue to you.

Please join our server for any help or support, team will love to help :)

link: [https://amplication.com/discord](https://amplication.com/discord)

**Comment by souravjain540** [comment]
hi @ankur0904 any updates on this?

**Comment by ankur0904** [comment]
@souravjain540 
I tried to setup the project on my machine locally but there was some error.
My operating system - Ubuntu 22.04.2, 
node version - v16.3.0 and 
npm version - 7.15.1 
I also tried the patch found in support channel 
[](https://github.com/amplication/amplication/issues/5330) but I am unable to apply the patch getting some error. I asked for help in #twenty-issues-for-first-timers as well as support channel in discord server.

**Comment by souravjain540** [comment]
@ankur0904 any updates on this issue?

**Comment by Sinisterchilll** [comment]
is this issue solved or still active?

**Comment by GreenMachine01** [comment]
@Sinisterchilll Yes, the issue is still open. want to take it?

**Comment by Sinisterchilll** [comment]
@GreenMachine01 sure!

**Comment by GreenMachine01** [comment]
@Sinisterchilll Great! Assigned to you. Good luck!

**Comment by Sinisterchilll** [comment]
@GreenMachine01 it's saying that I don't have access when clicking on the new design link.

**Comment by GreenMachine01** [comment]
@alexbass86 please provide @Sinisterchilll  with access to the design.

**Comment by GreenMachine01** [comment]
@Sinisterchilll all you need is actually in the description of the ticket.
you can download the icon image.

**Comment by morhag90** [comment]
Passed QA:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/97830649/234263655-9ccd3fad-115b-49d1-8bce-301e95eff7c2.png">

**Comment by morhag90** [comment]
<img width="929" alt="image" src="https://user-images.githubusercontent.com/97830649/234263794-2b57eed6-c266-4236-b521-441a416a74c6.png">
