### ISSUE TITLE
📖 Documentation: Connect Amplication server to GitHub doc doesn't provide instruction for git pull request service configuration

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5267]
### Description (What is it?)

https://docs.amplication.com/running-amplication-platform/connect-server-to-github/
This doc should describe the whole process of configuration of every service that is involved in integration with GitHub. However, configuration of git pull service is missing. As far as I know at least GITHUB_APP_APP_ID and GITHUB_APP_PRIVATE_KEY should be provided. Without that it's not possible to complete build process locally.

### Use Case (Why does the user need it?)

In order to make build locally.

### Issue URL

https://docs.amplication.com/running-amplication-platform/connect-server-to-github/

### How it works (How does the user use it?)

A user creates a build for a project.

### Screenshots

N/A

### Code Samples

N/A

### Figma URL

N/A

**Comment by Vipul2504** [comment]
Hey @souravjain540 can you assign me this
I would like to contribute on this

**Comment by souravjain540** [comment]
@Vipul2504 this campaign is only for first timers :)

you can contribute to any non TIFT issue.

**Comment by harshsingh32** [comment]
hi @souravjain540, I would like to contribute on this issue, can you assign this to me.

**Comment by souravjain540** [comment]
@harshsingh32 sure!

let me know if any help needed, you can join ours [discord](https://amplication.com/discord) for any support, team would love to help!

**Comment by harshsingh32** [comment]
I would like to know if in this issue I have to make some changes in the doc only

**Comment by souravjain540** [comment]
> I would like to know if in this issue I have to make some changes in the doc only

yes

**Comment by souravjain540** [comment]
@harshsingh32 any updates?

**Comment by harshsingh32** [comment]
@souravjain540  I have created a pull request on this issue(https://github.com/amplication/docs/pull/249#issue-1617072950). I have included instruction for pull request service configuration. Please suggest me if refinement is required.

**Comment by harshsingh32** [comment]
@souravjain540, PR is approved but it is not merged

**Comment by souravjain540** [comment]
> @souravjain540, PR is approved but it is not merged

it will get merged soon
