### ISSUE TITLE
📖 Documentation: Connect Amplication server to GitHub - missing permission

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5269]
### Description (What is it?)

https://docs.amplication.com/running-amplication-platform/connect-server-to-github/
Step 1.2 Enter the fields as follows:
Permissions > Repository permissions
Here PR permissions also should be added with access `Access: Read and Write`

Related issue: https://github.com/amplication/amplication/issues/5268

### Use Case (Why does the user need it?)

Git pull request service use this permission in order to receive PRs from repo and also create PRs.
https://github.com/amplication/amplication/issues/5268

### Issue URL

https://github.com/amplication/amplication/issues/5268

### How it works (How does the user use it?)

Use should specify permissions correctly so build would work.

### Screenshots

N/A

### Code Samples

N/A

### Figma URL

N/A

**Comment by souravjain540** [comment]
@Chirag8023 sure. join our discord for any help, team would love to help :)

**Comment by souravjain540** [comment]
@MoFoGo will review

**Comment by souravjain540** [comment]
@EugeneTseitlin will review
