### ISSUE TITLE
As Dev - I want to add Automated Tests for the new Smart Github sync

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5270]
As a developer, I want to add automated tests for the new Smart Github sync feature to ensure that it is functioning correctly and to catch any potential issues or bugs before they impact our users.

**Requirements:**

1. Create a test plan that includes all scenarios and edge cases related to the Smart Github sync feature.
2. Develop automated tests that cover all aspects of the Smart Github sync feature, including authentication, synchronization of repositories, pull requests, and issues, and handling of errors or unexpected behavior.
3. Run the automated tests in a staging environment to ensure that they are working correctly and covering all necessary scenarios.
4. Integrate the automated tests into our continuous integration/continuous deployment (CI/CD) pipeline to ensure that they are run automatically on each build.
5. Monitor the test results and address any failures or issues that are identified.
6. Update the automated tests as necessary to ensure that they continue to provide comprehensive coverage and accurately reflect the behavior of the Smart Github sync feature.
7. Document the automated tests and ensure that they are easily accessible to other members of the development team.

**Dev Notes:**
Add unit tests for:
git-utils
git-pull-request-service

**Comment by GreenMachine01** [comment]
@EugeneTseitlin & @overbit will sync and decide if we can close this ticket.
