### ISSUE TITLE
🐛 Bug Report: Standardize the logging of the data-service-generator

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#5283]
### What happened?

When building a service in Amplication the data-service-generator component provides the user with the approriate logging of what it is generating. 

![image](https://user-images.githubusercontent.com/73097785/221790470-e7fbc097-65a2-4963-8cb3-7e197a2b197a.png)

### What you expected to happen

I would expect that each of the logging rows is standardized in the way the row is capitalized (or not). My suggestion would be to only capitalize the start of the sentences and product names, i.e. GraphQL, GitHub, et cetera.

Things that are up for discussion: 
- Do also the lines that are about the plugins & dsg version include the triple dots after the sentence?
- Should first sentences of 'Push changes to GitHub' not include a period after the sentence?

### How to reproduce

Start a build for a project that has atleast one service and navigate to the build logs for that service.

### Amplication version

1.3.2

**Comment by levivannoort** [comment]
Some of the rows are dependent on the user's entity logic and can't be changed

**Comment by GreenMachine01** [comment]
@levivannoort 

> Should first sentences of 'Push changes to GitHub' not include a period after the sentence? 

No. it's not necessary.

**Comment by aryans1319** [comment]
I want to work on this can you assign it to me?

**Comment by souravjain540** [comment]
@aryans1319 sure!

Let us know if you need any help in solving this issue. Join our discord, team would love to help :)

**Comment by souravjain540** [comment]
@aryans1319 any updates?

**Comment by aryans1319** [comment]
Hey @souravjain540 was caught up with exams, will raise a pr by tommorow evening

**Comment by souravjain540** [comment]
@aryans1319 any updates?

**Comment by souravjain540** [comment]
@aryans1319 can i go ahead and assign it to someone else?

**Comment by jatinparmar96** [comment]
@souravjain540 I have created a PR for the fix. Could you please help me if with what other messages need to be standardized? I could only find two instances for fixes.

**Comment by levivannoort** [comment]
Hey @jatinparmar96 thanks for the contribution, I found a couple more messages we might want to change to lower case:

|Current|Desired|
| --- | --- |
|Installing Plugin|Installing plugin|
| Successfully Installed plugin | Successfully installed plugin |
|Running DSG Version | Running DSG version |
|Starting to push changes to GitHub.|Starting to push changes to GitHub|

**Comment by jatinparmar96** [comment]
@levivannoort  Thanks, I have updated my PR with these changes. Please have a look!
