### ISSUE TITLE
As User -  I want to easily populate Entities in the Service Creation Wizard using pre-built templates

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5284]
**Overview:**
The goal of this user story is to simplify the process of setting up a service for users by providing a variety of pre-built templates. These templates will be based on common use cases, such as CRM or social networks, and will include pre-defined entities and fields.

By offering pre-built templates, we can help new users understand the value of our platform more quickly, especially if the template matches their activities. This will also save users time and effort by eliminating the need to manually configure the service.

**Requirements:**
As a user, when creating a new service, I want the option to select a pre-built template to populate entities and fields within entities, in order to simplify and accelerate the setup process.

**Acceptance Criteria:**

1. The user must be able to select whether the service will use a DB or not during the creation process. (if we support service without DB)
2. If the user selects to create the service with a DB, a new page in the wizard will appear with the following options:
    a. Empty (Start from scratch) - The service will be created without entities.
    b. Use a template - Opens a new page with a list of templates
    c. Prisma schema - coming soon
3. Within the templates page the user must be able to select a template to apply to their service, which will pre-populate entities and fields.
4. The setup process for applying a template must be seamless for users, without any technical glitches or difficulties.
5. The user must be able to modify or delete entities and fields within entities as needed after the service is created.
6. The templates must be updated and maintained regularly to ensure their relevance and usefulness to users.

Figma - https://www.figma.com/file/fGHkvGfTxVm9P0RsVXYk9b/%23none---New-user-Onboarding-Flow-v2?node-id=2507%3A16382&t=nBhpZdEC825icPrP-1

**Comment by yuval-hazaz** [comment]
this is not relevant any longer
