### ISSUE TITLE
🐛 Bug Report: delete broker but not removing its connetions

### ISSUE THREAD

**Issue by barshimi** [amplication/amplication#5303]
### What happened?

when user remove/disabled broker resource' but not remove it's connection ID it fail the build. this happen because it looks for broker id' but the broker is disabled

### What you expected to happen

expect to remove all connections of removed resource

### How to reproduce

create service broker, add topics, connect those topics to services, remove the broker

**Comment by overbit** [comment]
Currently, we have 131 projects in production that may suffer from this issue.
```sql
SELECT "Resource"."projectId" FROM "public"."Resource" 
WHERE "resourceType" = 'MessageBroker' 
AND "deletedAt" IS NOT NULL
GROUP BY "Resource"."projectId"
```

**Comment by yuval-hazaz** [comment]
@abrl91 : 

https://user-images.githubusercontent.com/43705455/222469763-e1c97aab-1ecd-4019-816e-081a52938b7d.mov
