### ISSUE TITLE
Data Service Generator: Generated code wont compile

### ISSUE THREAD

**Issue by alonram** [amplication/amplication#531]
**Describe the bug**
After build, downloaded the code, npm I, npm start and I got the following compilation error

$ npm start

> @ start \Test\App005
> nest start

customer/customer.controller.ts:74:7 - error TS2322: Type '{ age?: number | undefined; dob?: Date | undefined; firstName: { connect: string; }; lastName?: string | undefined; serialNumber?: number | undefined; }' is not assignable to type 'CustomerCreateInput'.
  Types of property 'firstName' are incompatible.
    Type '{ connect: string; }' is not assignable to type 'string'.

74       data: convertDTOToPrismaFormat(data),
         ~~~~

  node_modules/.prisma/client/index.d.ts:1317:3
    1317   data: CustomerCreateInput
           ~~~~
    The expected type comes from property 'data' which is declared here on type 'CustomerCreateArgs'
user/user.controller.ts:74:7 - error TS2322: Type '{ username: { connect: string; }; password: { connect: string; }; roles: { set: string[]; }; firstName?: string | undefined; lastName?: string | undefined; }' is not assignable to type 'UserCreateInput'.
  Types of property 'username' are incompatible.
    Type '{ connect: string; }' is not assignable to type 'string'.

74       data: convertDTOToPrismaFormat(data),
         ~~~~

  node_modules/.prisma/client/index.d.ts:1744:3
    1744   data: UserCreateInput
           ~~~~
    The expected type comes from property 'data' which is declared here on type 'UserCreateArgs'

Found 2 error(s).

npm ERR! code ELIFECYCLE
with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     \AppData\Roaming\npm-cache\_logs\2020-09-30T07_57_52_777Z-debug.log

**Desktop (please complete the following information):**
 - OS: Windows 10
 
**Additional context**
[2020-09-30T07_57_52_777Z-debug.log](https://github.com/amplication/amplication/files/5306298/2020-09-30T07_57_52_777Z-debug.log)
[_generated-apps_ckfofnbda14650xs6rx2kvk07.zip](https://github.com/amplication/amplication/files/5306302/_generated-apps_ckfofnbda14650xs6rx2kvk07.zip)

**Comment by yuval-hazaz** [comment]
@iddan can we close this one?
