### ISSUE TITLE
🐛 Bug Report: UI borders on the commits view arent respected the same across different browsers

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#5317]
### What happened?

Similar to issue #5022 on atleast the firefox browser the UI borders have borders that touch each other which doesnt look great.

![Screenshot 2023-03-02 at 09 53 23](https://user-images.githubusercontent.com/73097785/222380491-28272489-4573-40c6-bb29-8b5e1f4b64db.png)

### What you expected to happen

That the borders wont touch.

### How to reproduce

Open app.amplication.com on a firefox webbrowser, navigate to the commits page (can also hit rebuild and you will be redirected), check the borders on the builds overview and middle-top-left the person that did the last commit.

### Amplication version

1.3.4

**Comment by levivannoort** [comment]
Same problem when you visit a build of a service, the window that displays the data service generator progress touches the right hand side that displays the diff of changes made.

**Comment by souravjain540** [comment]
Hi @endalk200, assigned this issue to you :) 

let us know if you need any help in this PR!

**Comment by GreenMachine01** [comment]
@alexbass86 please qa this item.

**Comment by alexbass86** [comment]
@endalk200 thanks for the contribution looks good! @GreenMachine01 approved on my side

**Comment by levivannoort** [comment]
Thanks for picking up the issue @endalk200, looks much better on firefox 🗿
