### ISSUE TITLE
🐛 Bug Report: BI event "PricingPageCTAClick" is not being triggered when it should

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5320]
**Expected:**
We have the event "PricingPageCTAClick" that should be triggered when a user clicks to upgrade/downgrade/contact his plan on the pricing page

**Actual:**
We do not see this event on the user in Amplitude

**Comment by tupe12334** [comment]
After testing, the error is caused because of the price property in the trackEvent function https://github.com/amplication/amplication/blob/1f51163c2b3fa13d3edb5a36a897ae6bdd4a2c9c/packages/amplication-client/src/Purchase/PurchasePage.tsx#L108

**Comment by EugeneTseitlin** [comment]
`PASSED`
![image](https://user-images.githubusercontent.com/6080188/223687596-85ef0d0f-e094-4ee9-9836-ad6f64baa75a.png)
