### ISSUE TITLE
🐛 Bug Report: Wrong UI - Resource drop down

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#5325]
### What happened?

The current look and behavior of the drop-down when we click the "Add new resource" button on the main screen are not aligned with the design.

**Current:**
![image](https://user-images.githubusercontent.com/96179897/222432236-9bcc32de-a8aa-4f32-a6b0-090aae941450.png)

**How it spouse to look:**
![image](https://user-images.githubusercontent.com/96179897/222432348-e8e9f475-d864-4001-98a5-0ffd64adc449.png)

**Public figma design to the correct UI:**
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1541%3A23755&t=RXKbz6nM6ffrjm4B-1

### What you expected to happen

Alligen the look and behavior to the original design.

### How to reproduce

It's on the main project screen.

### Amplication version

1.3.4

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by devXprite** [comment]
![am1](https://user-images.githubusercontent.com/80192140/224725185-8668e6f7-a1ec-4e33-bd63-5a2a3e93b493.png)

Please check out this design and suggest to me whether the mentioned changes are done or not.

And new design uses Lorem text in some places, and I am not sure what content should be used instead.

**Comment by souravjain540** [comment]
@alexbass86  @GreenMachine01 can you review it please?

**Comment by EugeneTseitlin** [comment]
> ![am1](https://user-images.githubusercontent.com/80192140/224725185-8668e6f7-a1ec-4e33-bd63-5a2a3e93b493.png)
> 
> Please check out this design and suggest to me whether the mentioned changes are done or not.
> 
> And new design uses Lorem text in some places, and I am not sure what content should be used instead.

@devXprite Please, attach your PR to the issue.

**Comment by alexbass86** [comment]
> @alexbass86 @GreenMachine01 can you review it, please?

Thanks for the contribution but unforchenatly, its not like the design. Please look at the corners, pointer, etc.
![image](https://user-images.githubusercontent.com/96179897/224988698-59d95b26-236a-4759-a422-ebb28adca251.png)
