### ISSUE TITLE
As User - I want to see updated design for the entities' fields list

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#5326]
### What happened?

We have a new and refreshed look for our entities filed list.

Old look:
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/96179897/222434399-bc9ea5c1-78e2-475a-bcd0-bb340fcd37db.png">

New look:
![Option 1](https://user-images.githubusercontent.com/96179897/222434486-6918f590-1984-4799-9449-a152f25ec6d0.png)

What changed:
Component - Font sizes & color, tags, icon size, overall component size.
Search bar - Now smaller

Public figma link for the UI
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1541%3A41290&t=RXKbz6nM6ffrjm4B-1

**Comment by lokeswaran-aj** [comment]
@GreenMachine01 I would like to contribute to this issue. Can you assign me to this issue?

**Comment by souravjain540** [comment]
> @GreenMachine01 I would like to contribute to this issue. Can you assign me to this issue?

Hi @lokeswaran-aj this issue is reserved for our upcoming campaign for first timers.

**Comment by souravjain540** [comment]
Assigned @lokeswaran-aj

**Comment by lokeswaran-aj** [comment]
@GreenMachine01 @alexbass86 Here is my PR to close this issue #5335 

Please review and merge or let me know if I have missed anything.

**Comment by GreenMachine01** [comment]
@lokeswaran-aj Thanks for the contribution!
@EugeneTseitlin please check the item.

**Comment by GreenMachine01** [comment]
@lokeswaran-aj  please take a look at the code review comments. assigned it back to you. thanks!

**Comment by lokeswaran-aj** [comment]
> @lokeswaran-aj please take a look at the code review comments. assigned it back to you. thanks!

Sorry for troubling you with many changes. But thanks, now I have changed everything you commented on. Please review once again and resolve the conversations.

**Comment by GreenMachine01** [comment]
@alexbass86  please review. looks good to me.


![Image](https://user-images.githubusercontent.com/112330500/225386819-3b9cb7a7-4533-4c15-8210-843b1b5f6216.png)

**Comment by alexbass86** [comment]
@lokeswaran-aj  looks FIRE! thank you for the contribution, @GreenMachine01 approved.
