### ISSUE TITLE
🐛 Bug Report: Sync with GitHub - UI Issues

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#5327]
### What happened?

The current screen is not aligned with the original design. 
A few things could be improved with the padding, icon size, and fonts.
Let's make sure it's exactly as in the Figma design.

Where the issues:
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/96179897/222437276-18fef21c-14d9-450f-8e6a-5f93b4f007f5.png">

Correct design:
1
![Service - GitHub sync a](https://user-images.githubusercontent.com/96179897/222437361-01db264a-abdc-4c5f-9093-c8493230be2e.png)

2
![Service - GitHub sync b](https://user-images.githubusercontent.com/96179897/222437382-2098dda5-f646-4785-99d8-828b67b088b8.png)

Public figma link
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1541%3A41873&t=RXKbz6nM6ffrjm4B-1

### What you expected to happen

Allign with the original design.Align

### How to reproduce

You can go to GitHub sync inside the resource screen.

### Amplication version

1.3.4

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by endalk200** [comment]
I want to take on this issue if it is not taken.

**Comment by souravjain540** [comment]
@endalk200  assigned another issue to you

**Comment by akshay-bharadva** [comment]
I would like to work on this issue.

**Comment by souravjain540** [comment]
@akshay-bharadva assigned this issue to you.

Please join our discord for any help or support needed in this PR, team will love to help :)

Link to discord: [https://amplication.com/discord](https://amplication.com/discord)

**Comment by akshay-bharadva** [comment]
@alexbass86 @souravjain540 

Can you check out this design and suggest to me whether I've mentioned design issues are solved or seem appropriate?

![image](https://user-images.githubusercontent.com/52954931/224496672-83472427-79e0-4f4e-acd9-973f726695ab.png)
