### ISSUE TITLE
📖 Documentation: Smart Git Strategy Documentation

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5328]
### Description (What is it?)

This document should describe how Smart Git Strategy is going to work. 
Here are some basic points that should be described:
1. Availability. This functionality is enabled for workspaces with Pro plan. Workspaces with Free plan are going to stay with Basic Git Strategy.
2. Functionality. SGS creates 'amplication' branch that is going to be used for creating new commits by pull request service. Also, only one PR is going to be opened at the same time.

Benefits:
1. The main benefit is that users won't have to resolve merge conflicts on every build. It's going to be much easier to work with amplication.

Limitations/Disclaimers:
1. Users should not remove 'amplication' branch from their repository. Otherwise 'amplication' branch will be recreated and the next PR will cause a merge conflict. After resolving merge conflict in the first PR user can work normally, second and further PRs won't create a conflict in the same area.  
2. Users should not modify 'amplication' branch, not by creating a new commit in 'amplication' branch, not by merging changes from others branches to 'amplication' branch. In case it happens, Amplication won't override/change/modify same areas as user changed. It may cause bugs and behavioral inconsistencies. In order to fix it user will have to delete 'amplication' branch and resolve merge conflict in the next PR. See details above.

Instructions:
TBD

### Use Case (Why does the user need it?)

User should know how to properly use Smart Git Strategy

### Issue URL

https://github.com/amplication/amplication/issues/5112

### How it works (How does the user use it?)

TBD

### Screenshots

N/A

### Code Samples

N/A

### Figma URL

N/A

**Comment by GreenMachine01** [comment]
@dericksozo I went over your proposal. I added some comments to the PR.
I think the focus of the section should be on how the smart git works and how it is different from the basic git sync.
I saw you did add all the info that was available in the Notion and the various GitHub tickets but I do feel the language can be improved a bit and not to copy paste from the developer.

**Comment by dericksozo** [comment]
Hi @GreenMachine01, thank you for the in-depth feedback on the Sync With GitHub page.

There will be 4 pages related to Git:

```
📁 How To
└📁 Sync With Git
  └📁 Sync with GitHub
  └📁 Sync with Bitbucket
  └📁 Smart Git Sync
  └📁 Basic Git Sync
```

I implemented your feedback for the Sync With GitHub page, but I'm moving this issue back into `In Progress` because it's about the Smart Git Sync page.

I'll create the Smart Git Sync page, re-create the pull request, and then ask for your feedback again.

**Comment by dericksozo** [comment]
This one is being taken care of in [#301](https://github.com/amplication/docs/pull/301).
