### ISSUE TITLE
🐛 Bug Report: 'PRISMA_CLIENT_OUTPUT_PATH' is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by SameedHasan** [amplication/amplication#5330]
I was trying to run amplication locally on windows 10 and got this error after running the command "npn run setup:dev" then i retried after running the command "npm i -g prisma" but was getting the same error.
![Screenshot (33)](https://user-images.githubusercontent.com/64144024/222636811-006c20cb-263a-4d1f-8f86-bc7d19939d46.png)

**Comment by SameedHasan** [comment]
I found the solution 
[amplication-prisma-generation.patch](https://github.com/amplication/amplication/files/10878398/amplication-prisma-generation.patch)

Step 1. download the patch file and add it into the amplication root folder
Step 2. run this command "git apply amplication-prisma-generation.patch"
Step 3. run this command "npm run setup:dev"
It will solve the issue.

**Comment by overbit** [comment]
I'm glad to hear that the patch worked for you @SameedHasan !

**Comment by SameedHasan** [comment]
> I'm glad to hear that the patch worked for you @SameedHasan! Only one feedback, could you please a Bug issue next time?

Sure
