### ISSUE TITLE
🐛 Bug Report: Error: P1000: Authentication failed against database server at `localhost`, the provided database credentials for `admin` are not valid.

### ISSUE THREAD

**Issue by SameedHasan** [amplication/amplication#5332]
### What happened?

after running the command "npm run db:migrate:deploy"  i am getting this error on windows as well as on linux.
![Screenshot (34)](https://user-images.githubusercontent.com/64144024/222688355-e7f58929-1f47-462d-92d4-22bb1884ea4b.png)
I tried to change the env variables from
POSTGRESQL_USER=admin
POSTGRESQL_PASSWORD=admin
POSTGRESQL_DB_NAME=amplication
to
POSTGRESQL_USER=amplication
POSTGRESQL_PASSWORD=amplication
POSTGRESQL_DB_NAME=amplication
as well but got the same errors 

### What you expected to happen

should not see these errors

### How to reproduce

just follow the local installation guide on windows and you will face the same problems

### Amplication version

1.3.4

### Environment

POSTGRESQL_USER=admin
POSTGRESQL_PASSWORD=admin
POSTGRESQL_DB_NAME=amplication

**Comment by GreenMachine01** [comment]
@SameedHasan Thanks! We will look into it.
@abrl91 FYI.

**Comment by abrl91** [comment]
@SameedHasan make sure you don't have another Postgres DB that runs on the same port

**Comment by SameedHasan** [comment]
> @SameedHasan make sure you don't have another Postgres DB that runs on the same port
@abrl91 I tried to change the port as well but still got the same errors

**Comment by StevenMcgrew** [comment]
I had Postgres DB running as a service on my machine, so I had to stop that one, and now it is working fine. Thanks @abrl91 .

**Comment by SameedHasan** [comment]
Steps to stop Postgres DB running as a service on machine.
1.Open a command prompt as administrator.
2.Type the following command to list all the services running on your machine:
 - On Windows: sc query
 - On Linux/MacOS: systemctl list-units --type=service
3.Find the Postgres service in the list. It may be named something like "postgresql", "postgres", or "pg".
4.Type the appropriate command to stop the service:
 - On Windows: net stop [service name]
 - On Linux/MacOS: sudo systemctl stop [service name]
Verify that the service has stopped by running the command in step 2 again and checking that the status of the Postgres service is "stopped".

then run the command  "npm run db:migrate:deploy" again.
