### ISSUE TITLE
As a user - I want that the plugin installation will be synchronize

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5336]
As I built a service in next I found out that the logs of the plugin installation success had come after the DSG process started.

The wanted behavior is that the logic will start only after the plugin is installed

![Screen Shot 2023-03-05 at 11 49 07](https://user-images.githubusercontent.com/61761153/222953355-24daf578-926a-4e63-9176-e2709ddd4d11.png)

**Comment by overbit** [comment]
Let's try to leverage the new nestjs kafka library for this

**Comment by GreenMachine01** [comment]
This item is waiting for further investigation by @tupe12334
