### ISSUE TITLE
As Plugin Dev - I want to know how to build plugins

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5340]
Moshe needs to have all information on building plugins as a contributor so that he can finish writing the guide for plugin developers.
https://docs.amplication.com/plugins/overview/

**Acceptance Criteria:**
1. All necessary information on building plugins should be provided to the documentation manager, including but not limited to the tools, technologies, and best practices for developing plugins.
2. The information should be presented in a clear, concise, and organized manner, so that the documentation manager can easily understand and utilize it.
3. Any dependencies or prerequisites for building plugins should also be clearly documented, including any required software or hardware.
4. The documentation manager should have access to any relevant code samples or templates to assist with writing the guide for plugin developers.
5. The guide should cover all aspects of plugin development, including setup, configuration, testing, and deployment.
6. The guide should be easy to follow and understand, even for users who are new to plugin development.

**Comment by abrl91** [comment]
@GreenMachine01 what about these:
1. [publish-plugin](https://docs.amplication.com/plugins/publish-plugin/)
2. [example-plugin](https://docs.amplication.com/plugins/example-plugin/)

**Comment by mulygottlieb** [comment]
@abrl91 the second link you added here (example-plugin) is a 404

**Comment by abrl91** [comment]
> @abrl91 the second link you added here (example-plugin) is a 404

That's because I changed the route. I fixed that
