### ISSUE TITLE
🐛 Bug Report: create camelcase Entity schema like in the other imports

### ISSUE THREAD

**Issue by vincenzodomina** [amplication/amplication#5348]
### What happened?

Autogenerated entity.resolver.base.ts code created typo error for entity dto with a entity name in camel case

- @graphql.Resolver(() => VariableCategory)
+ @graphql.Resolver(() => Variablecategory)    -> Typo in camelcase causes error

This does not happen for entity names only consiting of one word, this happended only to my only entity consisting of 2 words

### What you expected to happen

Should create camelcase Entity schema like in the other imports/filenames and not break

### How to reproduce

Any change in UI in recent version recompiles entity.resolver.base.ts

### Amplication version

1.3.5

**Comment by KlausMikhaelson** [comment]
Hey @vincenzodomina would like to work on this issue if it's still open !

**Comment by yuval-hazaz** [comment]
@vincenzodomina thanks for reporting it! 
we will look into it today.

@KlausMikhaelson Thanks for suggesting to work on it. 
I am happy to give that for you to handle, but I would love to make sure you are available to handle it ASAP. 
if not, we should assign it to the core team as it sounds like a high-impact issue in the code gen process

**Comment by KlausMikhaelson** [comment]
@yuval-hazaz I'm interning somewhere so my plan was to work on it during night but as it's a major issue that needs to address asap than I can look for other issues in the repo and try to contribute there !

**Comment by yuval-hazaz** [comment]
Perfect, thanks! 
We would love to assign other issues to you.
Thank you for you contributions 💜

**Comment by abrl91** [comment]
@yuval-hazaz @morhag90 
It's related to the auth-core plugin.
- I created a service with an entity with two words and without any other custom change.
- Push to GitHub and merge.
- Then uninstall (disable) the auth core plugin and the JWT plugin
![image](https://user-images.githubusercontent.com/39680385/223947042-51ac5ddf-97d1-4c3b-9aa2-6fe3f3d877b5.png)

- Got this diff:
![image](https://user-images.githubusercontent.com/39680385/223946983-df14ded2-11ec-4753-9210-23ecd2bfe148.png)

**Comment by yuval-hazaz** [comment]
@abrl91 good catch!
