### ISSUE TITLE
Update Nestjs to V9 and nestjs/graphql to v10

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5370]
- [x] Update Kafka event behavior

https://docs.nestjs.com/migration-guide#kafka-messageevent-handlers
- [x] #5397

 https://docs.nestjs.com/migration-guide#nestjsswagger-package
- [x] Update the graphql driver structure

https://docs.nestjs.com/graphql/migration-guide#introducing-driver-packages

### Blockers

- #5379

**Comment by abrl91** [comment]
@tupe12334 
the `@nestjs/core` is in version `9.3.9`


![Image](https://user-images.githubusercontent.com/39680385/225625674-120aaf10-8f57-4a90-83b2-869690c1173b.png)

**Comment by tupe12334** [comment]
@abrl91 This is the wanted version, the only 10 is graphql and jwt

**Comment by overbit** [comment]
I've updated the title to reflect the intention
