### ISSUE TITLE
As a dev I want to remove unused package `@apollo/gateway`

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5382]
The package `@apollo/gateway` is in the package.json file but not in our code files.

**Comment by Jyotiraditya24** [comment]
can I take up this issue?

**Comment by levivannoort** [comment]
This issue was already taken care of by @tupe12334, @Jyotiraditya24 labels that the community can contribute to have the label 'open to community', here is a link: https://github.com/amplication/amplication/labels/open%20to%20community

**Comment by abrl91** [comment]
passed QA ✅ 

It exists only as a peer dependency, but not in our core dependencies

![Image](https://user-images.githubusercontent.com/39680385/225626222-5957099e-aad8-47cd-a5ce-fe0f8fcc4419.png)
