### ISSUE TITLE
As User - I want to be able to manually remove the 'User' entity from the Service if I am not using Authentication

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5405]
[ Please see two prerequisite tasks before this one: #5851 and #5853 ]

As a User, I want to be able to manually remove the 'User' entity from the Service if I am not using Authentication

**Figma** - https://www.figma.com/file/wBcRAckCdHNCT3zUIOlK59/%234319---Entities%E2%80%A8---Are-you-sure%3F?node-id=2313%3A5131&t=xtJjDdpN3fXs7HDp-1

![Image](https://user-images.githubusercontent.com/112330500/233842331-2f9b362b-8818-461f-ab02-6b99e183612d.png)

**Acceptance Criteria:**
1. The User should be able to use a 'Delete' button to initiate the 'User' entity removal process. (like any other entity) if Authentication is not enabled on the service (NestJS Auth Module plugin)
2. The User should be presented with a confirmation message before the 'User' entity is deleted. 
    * This will be a different message since the entity is used for authentication - follow Figma design example
4. Upon confirmation, the 'User' entity should be deleted from the Service and all associated data should be removed.
5. There should be no special treatment or restrictions for removing the 'User' entity, and it should be treated the same as any other entity within the Service.
6. The removal of the 'User' entity should not affect any other functionality or permissions within the Service.
7. The User should be able to add the 'User' entity back into the Service if needed in the future.

**Relates to** - https://github.com/amplication/amplication/issues/5406

**Comment by GreenMachine01** [comment]
@yuval-hazaz when creating a new service without Auth selected do you think we should create the service without the 'User' entity?
I think that if we do that we will need to define a solution for when the user decides to manually add Auth to the service via the plugins

**Comment by GreenMachine01** [comment]
@morhag90 @yuval-hazaz I went over this item again and I see that I did request to allow deleting the User entity only if the plugin for Auth is not installed.
this might impact the effort estimate.

**Comment by GreenMachine01** [comment]
@morhag90 text for tooltip when the entity cant be deleted.

"This entity is currently in use by a plugin and cannot be deleted."

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/6aa6bc0e-b7e1-4125-97d8-cedd35a94d6f)

**Comment by mulygottlieb** [comment]
Moving this to passed QA, but @morhag90 please open another ticket for the tooltip when you cannot delete which is not implemented here
