### ISSUE TITLE
🐛 Bug Report: Generating Application keeps loading 

### ISSUE THREAD

**Issue by SameedHasan** [amplication/amplication#5419]
### What happened?

I am running amplication locally on Windows, and after clicking the 'rebuild' button, the build generation process starts. However, it keeps loading and there is no way to stop it, nor does it generate the output code. In the server's terminal, everything seems to be okay, as you can see in the second screenshot.
![Screenshot (40)](https://user-images.githubusercontent.com/64144024/224992312-3e9f6d24-b6f6-4e17-a54b-ae96ce729f28.png)
![Screenshot (39)](https://user-images.githubusercontent.com/64144024/224992369-11a552c7-ad34-4c16-a4a9-ba9150dd6cbb.png)

It's getting stuck on this 'Generating Application' process
![Screenshot (41)](https://user-images.githubusercontent.com/64144024/224992488-0fb1dd74-d0b2-4f73-81d2-a7bb08d58ad4.png)

Even after 5 hours, the application is still stuck on the 'Generating Application' process, and I'm unable to proceed with the next steps.
![Screenshot (42)](https://user-images.githubusercontent.com/64144024/225272560-f1e3cbc2-f6b3-423d-b827-7db98f1281c5.png)

### What you expected to happen

to generate an application with admin-ui and server folders

### How to reproduce

run amplication locally and add service then click on rebuild button and it keeps showing loading 

### Amplication version

1.3.4

**Comment by GreenMachine01** [comment]
@SameedHasan thanks. we will look into it.
@EugeneTseitlin please check if we have an issue

**Comment by EugeneTseitlin** [comment]
When running amplication locally on Windows using WSL2, local-data-service-generator-controller tries to make requests to `http://host.docker.internal:5010`, which is not accessible. It's a well-known issue that occurred after WSL2 moved from bridge to NAT network. 
You can read more about it here:
https://stackoverflow.com/questions/65327238/cant-connect-to-wsl2-localhost-server-from-wsl2-docker-container
https://github.com/microsoft/WSL/issues/4150

I advise to use port forwarding as a quick and straightforward solution. 
First obtain WSL IP with the following command:
wsl hostname -I
<WSL2IP>
Then proxy traffic to build manager that is running in WSL2:
netsh interface portproxy add v4tov4 listenport=5010 connectaddress=<WSL2IP> connectport=5010

There is also a script that can automate it:
https://github.com/microsoft/WSL/issues/4150#issuecomment-504209723
