### ISSUE TITLE
As User- I want to easily view and edit the plugin settings in the code view window

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5428]
**Overview:**
As a part of our ongoing efforts to improve the user experience within our application, we need to add a feature that automatically formats JSON data in a readable manner after the user clicks on the "Save" button.

**Current:**
![image](https://github.com/amplication/amplication/assets/112330500/bbb486b2-d5c5-4f33-92c6-24b9f1c1aae0)

**Requested:**
![image](https://github.com/amplication/amplication/assets/112330500/4dfa0840-a02e-4286-aed8-482e70c13a9d)

**Acceptance Criteria:**

1. After entering JSON data in the code viewer and clicking 'Save', the system automatically formats the JSON text to be more readable.
2. Any default settings will be shown in the prettified format when the user opens the settings of a plugin.

**Comment by GreenMachine01** [comment]
@tupe12334 
can you add an example of current versus expected?

**Comment by mulygottlieb** [comment]
@GreenMachine01, if you or @alexbass86 add a visual example of the required changes, we can open it for the community. But we need a clear example or explanation of the desired result to give it to someone.

**Comment by riju951** [comment]
Can you assign me this issue ?

**Comment by souravjain540** [comment]
@riju951 i assigned another issue to you. let someone other work on this :)

**Comment by iriteshmishra** [comment]
Assign me this issue

**Comment by souravjain540** [comment]
Assigned. Let me know if you need any help. @Saurav-Pant

**Comment by Saurav-Pant** [comment]
sure Thanks for this, when I  start working on this I will take help

**Comment by Saurav-Pant** [comment]
Can you please assist me in finding this file in the codebase? @souravjain540

**Comment by souravjain540** [comment]
@Saurav-Pant when can I expect a PR?

**Comment by Saurav-Pant** [comment]
I apologize for the delay. As a newcomer to Amplication, both as a user and a contributor, I am having difficulty understanding where I should make changes on the website. I kindly request your guidance in identifying the appropriate location for these changes.

**Comment by Pratyakshshiv** [comment]
can i work along side with @Saurav-Pant  on this @souravjain540 ?

**Comment by souravjain540** [comment]
@Saurav-Pant open a support ticket in discord, if you are okay I can assign it to @Pratyakshshiv as well.

**Comment by Saurav-Pant** [comment]
> @Saurav-Pant open a support ticket in discord, if you are okay I can assign it to @Pratyakshshiv as well.

Sure, assign it to @Pratyakshshiv as well

**Comment by techmannih** [comment]
hello @souravjain540 @GreenMachine01 ,
can you assign me ........ I want to handle of this issue..

**Comment by souravjain540** [comment]
> hello @souravjain540 @GreenMachine01 , can you assign me ........ I want to handle of this issue..

done

**Comment by techmannih** [comment]
hello @souravjain540 @GreenMachine01 

can you please mention its directory

> **Overview:** As a part of our ongoing efforts to improve the user experience within our application, we need to add a feature that automatically formats JSON data in a readable manner after the user clicks on the "Save" button.
> 
> **Current:** ![image](https://user-images.githubusercontent.com/112330500/244122234-bbb486b2-d5c5-4f33-92c6-24b9f1c1aae0.png)
> 
> **Requested:** ![image](https://user-images.githubusercontent.com/112330500/244122284-4dfa0840-a02e-4286-aed8-482e70c13a9d.png)
> 
> **Acceptance Criteria:**
> 
>     1. After entering JSON data in the code viewer and clicking 'Save', the system automatically formats the JSON text to be more readable.
> 
>     2. Any default settings will be shown in the prettified format when the user opens the settings of a plugin.

**Comment by Tjsingh01996** [comment]
@souravjain540 can you assign me

**Comment by Tjsingh01996** [comment]
@souravjain540 
here is pr : https://github.com/amplication/amplication/pull/6667
