### ISSUE TITLE
 File Upload Field Type

### ISSUE THREAD

**Issue by mihailShumilov** [amplication/amplication#5429]
**Feature description**
From my perspective file upload is one of standard features in app. As an example logo/avatar upload etc.
Ideally have option to store files like:

local
S3
Digital Ocean

**Use case**
Any option to file upload

**Are you willing to submit PR?**
No response

**Comment by endalk200** [comment]
Yes, this feature is very much needed. I want to take on the issue. I think we should start with local file upload support first then add the others as a plugin (Amazon s3 compatible object storage solutions and others).

**Comment by mihailShumilov** [comment]
I have started preparation for this
I can push my changes today, but I stuck on code generation phase
If that is possible to have a consult with someone from the core team - that would be great

**Comment by overbit** [comment]
@mihailShumilov let's jump on a call to better understand where you are at and how we can proceed here.

**Comment by mihailShumilov** [comment]
@overbit I'm open to call today

**Comment by GreenMachine01** [comment]
Will be done as part of - https://github.com/amplication/amplication/issues/5488
