### ISSUE TITLE
🐛 Bug Report: Build and commit is very slow

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5433]
**Overview:**
During demos and in general, Yuval reports a very slow process for syncing the code to GitHub.
We got recently similar complaints from users.
I also noticed a very slow process for doing the code build (without the sync to GitHub)

**Actual:**
The process of syncing the code to GitHub is very slow (can be a few minutes)
This happens for both initial sync of a new service and a follow up sync

![Image](https://user-images.githubusercontent.com/112330500/225317710-56913142-7289-4f95-8018-b9a71d0aafec.png)

**Expected:**
The process of syncing the code to GitHub is very fast - less than 20 seconds

**Comment by yuval-hazaz** [comment]
In addition to the fact that it may take a lot of time, the build build log shows multiple lines in the relevant step
![image](https://user-images.githubusercontent.com/43705455/225318091-04fd78dc-7b3b-408c-9199-555f401c7763.png)

**Comment by GreenMachine01** [comment]
couldn't re-produce the issue. closing for now.
