### ISSUE TITLE
🧪 As Dev - I want to increase our test coverage and add unit tests for the Bitbucket implementation

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5434]
As Dev, I want to add unit tests for the Bitbucket service in Git-Utils so that I can ensure that the service is functioning correctly and that any changes to the codebase do not break the service.

**Requirements:**

1. The unit tests should cover all the functionality of the Bitbucket service in Git-Utils, including creating repositories, pushing changes, and pulling changes.
2. The tests should be written in a way that allows for easy maintenance and updates as the Bitbucket API changes.
3. The tests should be run automatically as part of the CI/CD pipeline to ensure that any changes to the codebase do not break the Bitbucket service in Git-Utils.
4. The tests should generate a clear and concise report of their results, including any errors or failures, to aid in debugging.

**Dev Notes:**
Add unit tests for the bitbucket service in git-utils

**Comment by GreenMachine01** [comment]
@abrl91 please review and make changes if needed to this user story
