### ISSUE TITLE
🐛 Bug Report: RESTApi `GET` `entity/:id` for entities with AUTO_INCREMENT id types fail  

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5437]
### What happened?

For generated applications that have entities with Ids of type `AUTO_INCREMENT`, when making a GET request by id for those entities, the response is a 400 `id must be an integer number`

### What you expected to happen

The right entity to be returned

### How to reproduce

1. Generate a new service with at least one entity with Id of type `AUTO_INCREMENT`
2. Follow the readme for starting the server with docker-compose
3. perform a request to GET the entity by id like `http://localhost:3000/api/customers/1`
4. Observe the response
```
400 Bad Request
"id must be an integer number"
```

### Amplication version

1.4.2

**Comment by overbit** [comment]
A pro use has 35 entities with id of type AUTO_INCREMENT that might suffer of this issue.

**Comment by morhag90** [comment]
Passed QA:

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/97830649/234244246-1064efa8-55c1-425d-94f1-63be3a8f40d0.png">
