### ISSUE TITLE
As a User - I want to push my generated code to Bitbucket

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5440]
part of: #5261

### getFile
- [x] #5505

`/2.0/repositories/{workspace}/{repo_slug}/src/{branchName}/{path}`

[get file or directory content](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-source/#api-repositories-workspace-repo-slug-src-commit-path-get)

---

### createPullRequestFromFiles
- [x] #5614

The simple PR strategy is not supported on Bitbucket

---

### createCommit
- [x] #5506

`/2.0/repositories/{workspace}/{repo_slug}/commit/{commit}/comments`

[create comment for a commit](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-commits/#api-repositories-workspace-repo-slug-commit-commit-comments-post)

--- 

### getPullRequest + createPullRequest
- [x] #5654

---

### Branch 

- [x] #5526

- getBranch
`/2.0/repositories/{workspace}/{repo_slug}/refs/branches/{name}`

[get a branch](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-refs/#api-repositories-workspace-repo-slug-refs-branches-name-get)

- createBranch
`/2.0/repositories/{workspace}/{repo_slug}/refs/branches`

[create a branch](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-refs/#api-repositories-workspace-repo-slug-refs-branches-post)

---

### getFirstCommitOnBranch
- [x] #5520

---

### getCurrentUserCommitList
- [x] #5547

refactor from using te API to using git client

---

### getCloneUrl + getToken 

- [x] #5527

---

### commentOnPullRequest
- [x] #5543

`POST /2.0/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments`

[create a comment on PR](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-pullrequests/#api-repositories-workspace-repo-slug-pullrequests-pull-request-id-comments-post)

---

### Refactoring to leverage git cli instead of provider APIs
- [x] #5648

--- 

### Add support for repository group for providers that support this feature
- [ ] #5699 

--- 
### ⚠️  TODO ⚠️  

https://github.com/amplication/amplication/issues/5440#issuecomment-1497533085

--- 

### Things to test:
- amplicationignore

**Comment by abrl91** [comment]
@overbit  FYI

**Comment by overbit** [comment]
getGitGroups doesn't support pagination params and it will not work for users with more than 10 Bitbucket workspaces

**Comment by overbit** [comment]
BitBucket `getRepositories` doesn't respect pagination params and it will not work for users with more than 10 Bitbucket repositories in a group.

**Comment by overbit** [comment]
[Bad practice] Git Provider Interface has inconsistent pagination params.

Some methods work on `page`, `currentPage`, `pageSize` meanwhile others on `page` and `limit`. 
We should stick to the simpler definition of `page` and `limit` across the library
