### ISSUE TITLE
🐛 Bug Report: Project can't be deleted

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5455]
### What happened?

Project can't be deleted
https://jam.dev/c/842ce355-26a5-4fb0-907f-49325a279275

### What you expected to happen

Project should be deleted

### How to reproduce

Select existing project
Try to delete it

### Environment

sandbox

**Comment by overbit** [comment]
The issue seems to happen when we delete more than one project without refreshing the page.

https://jam.dev/c/a2912acf-1244-4c80-a394-4451d2c2fc00

**Comment by overbit** [comment]
Test passed ✅ 

https://jam.dev/c/f03598ec-0989-4a7f-a865-4444ce0eba1e
