### ISSUE TITLE
DX: Running local dev environment missing automation or scripts to run the different components

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#5476]
### Feature description

To run a local dev env, the developer needs to follow the instructions on the README and run each of the apps separately.
Also, it is not clear which apps are required or which app goes with which app.

This is the current section in the README.md
```
```bash
  # This will serve the Amplication Server in development mode
  npx nx serve amplication-server

  # This will serve the Amplication Client in development mode
  npx nx serve amplication-client
  ```
> ℹ️ **Please note that in order to be able to run the app's client properly, you need to `serve` both the server and client plus any additional component for specific functionalities:**
> - `npx nx serve amplication-client`
> - `npx nx serve amplication-server`
> 
> **To allow code generation**
> - `npx nx serve amplication-build-manager` 
> - `npx nx serve local-data-service-generator-controller`
> 
> **To allow git syncronisation with selected provider**
> - `npx nx serve amplication-git-pull-request-service` 
> - `npx nx serve local-data-service-generator-controller`<br> _check additional documentation in [local-data-service-generator-controller](https://github.com/amplication/amplication/blob/master/packages/local-data-service-generator-controller/README.md)_
> 
> **To allow source code visualisation**
> - `npx nx serve amplication-storage-gateway`
> 
> **To allow plugin settings configuration in client app**
> - `npx nx serve amplication-plugin-api`
>

```


### Use case

_No response_

### Are you willing to submit PR?

_No response_

**Comment by overbit** [comment]
## Test result

`FAILURE` ❌ 

Following the instruction causes the following error since we try to start the same component in different commands:
<img width="930" alt="image" src="https://user-images.githubusercontent.com/2861984/226693254-cae831de-acc9-4186-a363-f04a7d8f572a.png">
