### ISSUE TITLE
As a plugin developer - I want to have docs about the `.amplicationrc`

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5481]

**Comment by GreenMachine01** [comment]
@abrl91 FYI

**Comment by abrl91** [comment]
@mulygottlieb, what did we decide to to with it?

**Comment by mulygottlieb** [comment]
@abrl91 - I suggest that because @morhag90 is updating the .amplicationrc file as part of her current task, to either wait with this (put on hold) or even re-assign to Mor to create the relevant data in docs after she finishes with the changes to this file
