### ISSUE TITLE
As a plugin dev - I want to use the plugin installation settings and not the resource settings

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5484]

**Comment by abrl91** [comment]
passed QA


![Image](https://user-images.githubusercontent.com/39680385/226559596-f4634a12-8f93-4f4d-8f4d-b5caed7259bc.png)

**Comment by abrl91** [comment]
We have a problem with the `DB_URL` in the `server/.env` file
https://github.com/amit-amp/amit-test/pull/3/files#diff-851502e39b7ba2dbf4da21e578181c158ff8917752cefcae5996bd989915e25dR7



![Image](https://user-images.githubusercontent.com/39680385/226586159-e5b6031e-a5b4-4829-8c52-142a93a0aa37.png)

**Comment by abrl91** [comment]
passed


![Image](https://user-images.githubusercontent.com/39680385/226621547-c479d1fd-60dc-4709-8283-8a1313713b57.png)
