### ISSUE TITLE
🐛 Bug Report: Create new project button has wrong ui when disabled

### ISSUE THREAD

**Issue by serose99** [amplication/amplication#5492]
### What happened?

![create-new-project-issue](https://user-images.githubusercontent.com/12384859/226197004-129f6fd4-bdc7-47cc-b299-b119dd50b194.png)

With invalid input in the new project form, the create new project button still appears enabled. 

### What you expected to happen

![create-workspace](https://user-images.githubusercontent.com/12384859/226197037-b0838577-178c-41d5-bbac-9417eaa9d44a.png)

Should appear like the create-workspace popup where button is and looks disabled

### How to reproduce

1. Click the "+ Add New Project" button to open the popup
2. See that the button appears enabled but is in fact not 

### Amplication version

1.4.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abrl91** [comment]
Passed QA ✅ 



https://user-images.githubusercontent.com/39680385/228264073-5de444f3-13f0-4669-93b4-ff12294aecd3.mov
