### ISSUE TITLE
As User - I want the service wizard to populate for me the server and admin 'Base Directories'

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5495]
As User - I want the service wizard to populate for me the server and admin 'Base Directories' when I am selecting to use a monorepo.

![Image](https://user-images.githubusercontent.com/112330500/226311193-6d183d97-deaf-4f46-9907-e31475a27cd4.png)

**Requirements:**
1. The service creation wizard should have an input field for the user to enter a name for the main folder.
2. The default value for the main folder name should be "apps".
3. The input field for the main folder name should have a watermark displaying "./" before the name the user needs to fill.
4. When the user enters the main folder name, the server base directory should be generated as "./[main-folder]/[service-name]".
5. When the user enters the main folder name, the admin-ui base directory should be generated as "./[main-folder]/[service-name]-admin".
    * Notice the append of "-admin" at the end

**Comment by morhag90** [comment]
Passed QA: 
<img width="678" alt="image" src="https://user-images.githubusercontent.com/97830649/230769131-563a8e26-0c32-48e0-893c-736df1b5259f.png">

<img width="656" alt="image" src="https://user-images.githubusercontent.com/97830649/230769148-3e034a1b-d1bc-4287-b860-63361f7dc52f.png">
