### ISSUE TITLE
As New User - I don't want to go through the onboarding wizard if I was invited to join a workspace by a team-member.

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5496]
As a new user who has been invited to join a workspace by a team member, I want to skip the onboarding wizard so that I can access the workspace without any unnecessary steps.

**Requirements:**
1. When a new user is invited to join a workspace by a team member, they should be able to access the workspace directly without going through the onboarding wizard.
2. The invitation link should take the new user directly to the workspace.
3. If the new user somehow ends up on the onboarding wizard page, he should have the option to close the wizard via the "Close" CTA
4. When this user decides to create a service he should go through the regular service creation wizard and not the onboarding one.

**Comment by overbit** [comment]
Test result
 🟥 `FAILED` 
 
 https://jam.dev/c/38700d93-8c1e-422f-b1aa-e0fe49104640
