### ISSUE TITLE
As User - I want to use new UI for connecting to a git provider

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5513]
**Overview:**
As we are now supporting Bitbucket as an additional Git provider option, we need to make changes to the UI to support using the new provider with a seamless experience.

**Figma** - https://www.figma.com/file/EXpu3W16xQDQ6NnEpzQE9R/%23none---Supporting-more-Git-providers?node-id=2041%3A14924&t=snyREHPvdQKyqgFU-1

**Requirements:**

- Update the UI according to the Figma design example, including updating text and icons to support multiple Git providers.
- Add an option for connecting with Bitbucket
- After selecting the Git provider, redirect users to the authorization page for the selected provider to complete the connection process.
- After the connection has been established and the user provided access to the desired Git organization, allow the user to select the organization from a dropdown menu.
- Add an "Add New Org" option to the dropdown, which opens a new pop-up for the user to select which Git provider they want to connect to (GitHub or Bitbucket)
- add any new connected git organizations to the dropdown
- if a user selects to connect with Bitbucket let him set the desired workspace before selecting the repo he wants to work with
- the rest of the flow remains similar to as it is today with the new updated UI

**Acceptance Criteria:**

1. New git provider component is used both in the service creation wizard and in the service git provider tab

--- 

### To Do:
- [x] #5052
- [x] #5801
- [x] #5812

**Comment by overbit** [comment]
Available queries to achieve the requirements:


  gitOrganization(where: WhereUniqueInput!): GitOrganization!
  gitGroups(where: GitGroupInput!): PaginatedGitGroup!
  connectResourceGitRepository(data: ConnectGitRepositoryInput!): Resource!


Check the graphql schema for branch `5440-push-code-to-bitbucket` for more details.

![Image](https://user-images.githubusercontent.com/2861984/230437324-3ed7327a-c380-4697-b72a-8597a6ab3007.png)
![Image](https://user-images.githubusercontent.com/2861984/230436614-acae47c3-e423-43d1-a6a8-311654ccfad7.png)

**Comment by abrl91** [comment]
related issue: https://github.com/amplication/amplication/issues/5052

**Comment by abrl91** [comment]
Fixed by:
https://github.com/amplication/amplication/pull/5803 
https://github.com/amplication/amplication/pull/5804
https://github.com/amplication/amplication/pull/5890

**Comment by abrl91** [comment]
passed QA ✅ 


![Image](https://github.com/amplication/amplication/assets/39680385/9da38168-2782-4963-9847-b8875ee57faa)



![Image](https://github.com/amplication/amplication/assets/39680385/06a6ea80-4d38-45c3-8986-61fe6db5f4ca)
