### ISSUE TITLE
🐛 Bug Report: Override git provider settings doesn't work on a new workspace without prior Git connections

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5515]
![Image](https://user-images.githubusercontent.com/112330500/226653000-c8351fac-65ae-4d13-ae40-faf5af56377b.png)

**Steps to Reproduce:**
1. Create a new Workspace
2. Create a new project
3. Create a new service
4. go to the service git provider tab

**Expected:**
User can override the project settings and connect to his desired git provider and repo

**Actual:**
The override toggle doesn't change when clicked.

**Severity:**
 3 - Major

**Comment by Jyotiraditya24** [comment]
hey can I take up this issue?

**Comment by Jyotiraditya24** [comment]
Done 🚀
