### ISSUE TITLE
🐛 Bug Report: Error when saving plugin settings

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#5536]
### What happened?

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/43705455/227026691-eb4a2c98-f594-45b2-9ded-1061243ac994.png">

```
"Variable \"$data\" got invalid value { enabled: true, settings: { host: \"localhost\", port: 27017, user: \"admin\", password: \"admin\", dbName: \"my-db1\" } }; Field \"version\" of required type \"String!\" was not provided."
```

### What you expected to happen

settings should be saved 

### How to reproduce

create a new service
install mongo DB plugin
build code
go to the plugin settings page
change a value in the settings json 
click on save

see error

### Amplication version

1.4.2

**Comment by overbit** [comment]
Already an issue in production. It's not a blocker for v1.4.3

**Comment by morhag90** [comment]
Passed QA:

Default settings:

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/97830649/234037549-9fddf872-ada8-4396-ad21-6102d04405ad.png">
 

After save new settings: 

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/97830649/234037997-1097c1a9-490a-4fa8-adee-17bbe8cd6088.png">
