### ISSUE TITLE
Plugin settings should offer an option to select latest version

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5556]
### Feature description

Currently, when a plugin version is selected, we cannot revert to the latest version. 
It would be really beneficial to be able to select the latest version to take advantages of most up to date releases.

Plus, it would be ideal to have the `client` listing the plugin versions from the latest to the oldest.

The plugin settings will need to show the new latest option followed by the actual version within parentesis like in the following screenshots

<img width="919" alt="image" src="https://github.com/amplication/amplication/assets/2861984/8ba801f4-9113-4da3-8c7d-83f494770b68">

![image](https://github.com/amplication/amplication/assets/2861984/5904d335-78c1-46b8-a3a8-1838cc5c7503)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GreenMachine01** [comment]
@overbit it would be great if we also communicate the number of the latest version so the user can see if it was changed from the last time he checked.

**Comment by EugeneTseitlin** [comment]
@overbit @GreenMachine01 Development of this issue is blocked by the following issue: #5683
I think the issue has to be prioritized.

**Comment by overbit** [comment]
@GreenMachine01 shall we prioritise #5683  then? It's a blocker for this card

**Comment by overbit** [comment]
# Test result ✅ 

https://jam.dev/c/3c59e95a-c7ab-4c6a-8451-09e74f36c1b6

**Comment by GreenMachine01** [comment]
@overbit we discussed having the latest version also separate so the user can choose it and it will not update.
