### ISSUE TITLE
As a Dev - I want to make sure that the `git-organization-provider-properties` will not cause data loss if we will rerun it by mistake in the future 

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5561]
we have this migration script that we created for the last release `1.3.4`
`packages/amplication-server/migration-scripts/git-organization-provider-properties.ts`

We need to make sure that if for some reason and by mistake, someone runs it again, we will not lose data.

**Comment by overbit** [comment]
Moved in Prod since we already run the script
