### ISSUE TITLE
🐛 Bug Report: E2E Fails to find branch name

### ISSUE THREAD

**Issue by YAbargil** [amplication/amplication#5574]
### What happened?

If a non-worker's PR gets approved, The E2E check will not find the branch due to a fork.
upon forking the username attached to the branch's name.

E2E needs to add for non-worker's PR a prefix of the username and a column colon.
`{$username}:${branch_name}`

![image](https://user-images.githubusercontent.com/89596161/227759922-1d8e5cf4-20f7-407e-b201-e23b354ee509.png)

searching for branch `'fix/5515-fix-git-toggle-override' ` while need to check for `YAbargil:fix/5515-fix-git-toggle-override`.

### What you expected to happen

e2e to locate the branch name.

### How to reproduce

Check for approved PR by non-worker.

**Comment by overbit** [comment]
Potentially fixed by #5569
