### ISSUE TITLE
🔼 As a dev - I want to upgrade the prettier version

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5576]
Currently, we are working with a deprecated version of `prettier`.
We need to update it to the latest version and make sure nothing is breaking.

**Comment by Jyotiraditya24** [comment]
I have updated the packages is there any recommended way to see whether  somethings break or not?

**Comment by tupe12334** [comment]
@Jyotiraditya24 No, just rerun the format npm script to see if anything has changed

**Comment by souravjain540** [comment]
please link the PR here as well @Jyotiraditya24

**Comment by ognjenjevremovic** [comment]
May I take this one instead?

**Comment by souravjain540** [comment]
@GreenMachine01 is this issue still valid?

**Comment by akshay11298** [comment]
Hi, is this still an open issue? If yes, can I work on this?

**Comment by Sheersendu** [comment]
@souravjain540 I have updated prettier to v3.0.3(current version is 2.7.1 as shown in screenshot) locally, if the issue is still open, I can just create a PR right away!


![Image](https://github.com/amplication/amplication/assets/62256588/86b6c13b-eebc-44e6-af90-f3280c0cfc0f)

**Comment by martinez-hugo** [comment]
Hi ! Can I work on this issue ?
