### ISSUE TITLE
🤔 As a dev - I want to consider to remove the `stylus` and `stylus-loader` packages

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5604]
As part of https://github.com/amplication/amplication/pull/5589 i checked our code usage in `stylus` and `stylus-loader` I found out that we don't call them in our code.
We can remove them, but before that we need to make sure it's not impacting our design system and client.

**Comment by akshay-bharadva** [comment]
@souravjain540 I want to solve this issue.

**Comment by abrl91** [comment]
passed QA

![Image](https://github.com/amplication/amplication/assets/39680385/aa4056e8-f2eb-4ddf-bcb8-ff315cea16b9)
