### ISSUE TITLE
🐛 As a dev - I want to finish the remove of `nestjs-prisma` from generated code

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5615]
As of today, we still generate code with `nestjs-prisma` package in the `package.json` and we use the package in the `health.service.spec.ts` file.

When we will remove it we need to make sure we remove it from the `health.service.spec.ts` in the mongo plugin if it's still there.
@abrl91  Please provide more info if necessary.

**Comment by abrl91** [comment]
I think something went wrong when we merged mongo's PR. It needs to be removed and use our Prisma service, like Postgres and MySQL

**Comment by olalekanteeblaze** [comment]
Hi @abrl91 , does this require removing it from data-service-generator package?

**Comment by abrl91** [comment]
> Hi @abrl91 , does this require removing it from data-service-generator package?

yes
