### ISSUE TITLE
🐛 Bug Report:  duplicated logs in the DSG build log

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5627]
### What happened?

We are currently experiencing some duplicated logs in the DSG build log. This seems to be related to the server processing the DSG log events from Kafka twice

<img width="835" alt="image" src="https://user-images.githubusercontent.com/2861984/228763386-0aa57805-1da9-4a23-9074-33aba6109e20.png">

### What you expected to happen

Log kafka events should be processed only once by the server  

### How to reproduce

Run a multi-service build and observe the log of some of the services

### Amplication version

1.4.5

**Comment by EugeneTseitlin** [comment]
@overbit The issue doesn't occur in v1.5.4 when running build for project with 3 services:
![image](https://user-images.githubusercontent.com/6080188/235114629-bfe7f438-4cc8-4391-b3af-5280a65964c5.png)

Please, confirm that issue can't be reproduce, so I would be able to close it.

**Comment by EugeneTseitlin** [comment]
Not reproduced
