### ISSUE TITLE
Printing application successfully generated in the build log

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5635]
### Feature description

Currently, we don't print any final message in case of a successful build as shown here.

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/2861984/228856373-3c9789f0-8d69-4b2d-a75b-e2f85020c89e.png">

I'd love to see a final message in case of success stating that the app generation process finished successfully

**Comment by Aman1919** [comment]
I want to work on this

**Comment by souravjain540** [comment]
assigned to you @Aman1919

**Comment by ArslanYM** [comment]
@souravjain540 If there is no movement on this issue , Can I work on this?
