### ISSUE TITLE
🐛 Bug Report: Switches in General Settings screen doesn't work properly

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5637]
### What happened?

https://jam.dev/c/47a3dc9a-1949-4cf2-a42c-e795f7c7110d

At the beginning do not react on multiple clicks, then two blocks change state simultaneously.  

### What you expected to happen

Enable/disable should work on every click.

### How to reproduce

Try to create service
In General Settings screen try o change settings

**Comment by overbit** [comment]
The issue is: 
Clicking on the toggle, which has a mouseover animation, produces no actions. 
Clicking on the tile (that has NOT mouse-over animation) produces the toggle action 

https://jam.dev/c/6b0d7124-270a-4c73-a9a0-d595e9f8f96e
