### ISSUE TITLE
🐛 Bug Report: new onboarding wizard lets you enable plugins but does not provide default settings

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#5643]
### What happened?

When enabling a plugin - e.g., mongodb, mysql, postgresql, the default settings for the plugin arent created, and thus if the plugin doesnt provide default values through the code base, the plugin will cause an error when building the service.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/73097785/229084287-05d3601c-f9b6-4cb6-8512-a278627e3526.png)

### What you expected to happen

creation of default settings to provide user with a sense of what can be changed on the plugin level, and also prevent the build error

### How to reproduce

use new onboarding to create a service and select one of the plugins that uses settings - i.e., a database plugin, after the creation has been completed go to the plugin settings for that specific plugin + do a build of the service

### Amplication version

1.4.6 [sandbox]

**Comment by levivannoort** [comment]
#5644 has been added to make sure that if a user doesnt provide one of the required settings that it defaults back to the .amplicationrc.json

**Comment by morhag90** [comment]
Was fixed in another issue.
