### ISSUE TITLE
🐛 Bug Report: After creating a service build is not shown as running

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5646]
### What happened?

https://jam.dev/c/1d95f03d-e94c-4457-8c2c-5dc39d08c963

As you can see, after creating a service build is not shown as running, but if you click on rebuild, then you can see the initial commit also.

### What you expected to happen

After creating a service build should be shown as running.

### How to reproduce

Create a service
See that build in not shown

### Environment

sandbox

**Comment by yuval-hazaz** [comment]
If I am not mistaken - the design is that the build should not run at all on the service creation, and the user should be allowed to configure the service before clicking on "commit" - so the wizard ends without a commit - and the user should see the new service settings as pending 

@GreenMachine01 please confirm

**Comment by morhag90** [comment]
Passed QA:

<img width="1711" alt="image" src="https://user-images.githubusercontent.com/97830649/230768616-488c8cbc-735c-4a32-956d-22669f1dc23a.png">
