### ISSUE TITLE
As a Dev - I want to refactor some methods in the smart git strategy pull request flow to work with a git client library

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5648]
Related issue: https://github.com/amplication/amplication/issues/5440

## Refactor Smart Git strategy Pull Request Flow:
Converting some methods to work with a git client library - [Simple Git](https://www.npmjs.com/package/simple-git) instead of REST API / GraphQL

### Must be refactored
- createCommit #5653 

### Nice to have / can be refactored later as it's already working well with the REST approach:
- getBranch
- createBranch
- getFirstCommitOnBranch

---

### Methods that will still work with REST API / GraphQL:
- getPullRequest
- createPullRequest
- getFile
- getCloneUrl
- createPullRequestComment
- getToken
- getAmplicationBotIdentity

**Comment by overbit** [comment]
We are missing only this PR https://github.com/amplication/amplication/pull/5698
