### ISSUE TITLE
🐛 Bug Report: Create Service Wizard: despite that project is connected to a repo it's not selected for a new service

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5651]
### What happened?

https://jam.dev/c/793bd1fa-cf04-4206-ad66-212c5a417646

### What you expected to happen

Connected repo should appear in Repo Screen in Create Service Wizard

### How to reproduce

Connect Project to a repository
Try to create a new service
See that on Repo Screen in Create Service Wizard repository is not selected

**Comment by EugeneTseitlin** [comment]
It may be actually not a bug. It may be a feature :)
Now I've connected project and only then created a service. In this case I can see repository.
https://jam.dev/c/8e3681d3-dc2a-4dd7-8afd-fe4c82c0addc
If during first service creation project should not be connected to repository, then everything is fine.

**Comment by yuval-hazaz** [comment]
@EugeneTseitlin the behavior should be like this:
1. When creating the first service in the project - the settings should be saved at the project level 
2. When creating the following services, by default the service settings should be inherited from the project - and if a new repo is selected it needs to be saved as an override in the service level

**Comment by morhag90** [comment]
Passed QA:

New User: 

selected repo:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/97830649/230768581-30cf24a3-93a1-48dc-9109-511e5620fbd2.png">

Project settings: 

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/97830649/230768689-d7d19bb3-4334-46b3-a708-47be2c845edb.png">
 
Service settings: 

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/97830649/230768715-0b042ec7-ecfb-4516-b5d2-1d0422b1d290.png">


Existing User: 

<img width="862" alt="image" src="https://user-images.githubusercontent.com/97830649/230768758-5cb92df2-0566-4965-bf74-b5575485f90a.png">
