### ISSUE TITLE
🐛Bug Report: Mongo DB endpoints throw '500' errors

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5662]
This Mongo application just does not appear to work - some of the endpoints work, some get 500's - can't create users through the API but can through the generated UI.  The generated UI (which I get it is not the main thrust of this) marks fields as required when they are not, etc, etc.  I'm assuming these types of issues are because this is an initial Mongo release?  It seems like the Postgres implementation is in much better shape. 

https://amplic-my.sharepoint.com/:u:/g/personal/daniele_amplication_com/EYux1oYcazRJj-whTBdokxcB8XvpplfWb59rtftSzwZsjg?e=eB9b4E

**Comment by morhag90** [comment]
Deprecated bug.
Solved issues: 
#5607
#5437
