### ISSUE TITLE
🐛 Bug Report: New users are able to close the service wizard

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5670]
**Steps to Reproduce:**

1. Signup to Amplication as a new user
2. Follow the wizard to create a new service
3. Observe the top right side of the wizard

**Actual Result:**
The "Close" button is visible on the top right side of the wizard for new users creating their first service.

**Expected Result:**
The "Close" button should not be visible on the top right side of the wizard for new users creating their first service.

**Comment by morhag90** [comment]
Passed QA:  

No close button in onboarding process: 

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/97830649/230768499-83fce60a-1947-456b-8a69-acaade3f9989.png">
