### ISSUE TITLE
🐛 Bug Report: Onboarding process doesn't show build code and create git organzation. 

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#5678]
### What happened?

When i start the onboarding process, I don't see the option to create a new Git organization and the build code process. 

### What you expected to happen

I can connect to new Git organizations and see the code build process. 

### How to reproduce

Assign with a new User => Go over the onboarding process and try to create a service.
you will not see the "connect to git organization" and the code build process. 

### Amplication version

1.4.3

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GreenMachine01** [comment]
I saw the connect to Git and build process as a new user
