### ISSUE TITLE
As User - I want to know that Bitbucket is a premium feature

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5684]
**Overview:** 
The UI needs to inform users if Bitbucket is not available based on their workspace plan and provide them with a way to inquire about upgrading to an Enterprise plan.

**Use Stigg entitelments**

**Requirements:**
1. Create a new Stigg entitlement that controls if the user can commit code to BitBucket
2. If Bitbucket is not available based on the user's workspace plan entitlements, display a lock icon on the Bitbucket button
    -  When hovering over the Bitbucket button, display a tooltip that explains that the feature is only available to Enterprise Plans and includes a hyperlink to the pricing page.
3. If a user tries to build without having a valid Bitbucket entitlement show a notification (similar to having more than 3 services)

Figma - https://www.figma.com/file/EXpu3W16xQDQ6NnEpzQE9R/%23none---Supporting-more-Git-providers?node-id=2790%3A10113&t=msIVYTVziPGRtnlp-1

**Comment by GreenMachine01** [comment]
@EugeneTseitlin @barshimi @abrl91 

I created a new feature in Stigg for both Dev and Prod env - "feature-bitbucket"

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/5942

**Comment by abrl91** [comment]
passed QA ✅ 



![Image](https://github.com/amplication/amplication/assets/39680385/2862ee76-a6be-4886-ae32-859d3c01e807)
