### ISSUE TITLE
Git Provider Interface has inconsistent pagination params.

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5702]
[Bad practice] Git Provider Interface has inconsistent pagination params.

Some methods work on `page`, `currentPage`, `pageSize` meanwhile others on `page` and `limit`. 
We should stick to the simpler definition of `page` and `limit` across the library.

The same should be done for any graphql query in the server GraphQL schema

_Originally posted by @overbit in https://github.com/amplication/amplication/issues/5440#issuecomment-1497533085_

**Comment by morhag90** [comment]
Passed QA:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/97830649/234266147-80d84807-369f-489d-82a5-20dcc823b84e.png">

**Comment by abrl91** [comment]
@morhag90 this is still not in 'next'. The PR for this issue is in the umbrella branch of bitbucket. We will be able to QA it only after we will merge this umbrella branch into `next`

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/5797
