### ISSUE TITLE
Rework the bitbucket authentication flow, after the access token and refresh token are collected

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5707]
Rework the bitbucket authentication flow, after the access token and refresh token are collected. Right now, only the amplication-server is able to read this data, but other services need that too

_Originally posted by @overbit in https://github.com/amplication/amplication/issues/5440#issuecomment-1497533085_
            
Currently, the bitbucket flow won't work due to missing token along the way.

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/5708
