### ISSUE TITLE
🐛 Bug Report: New onboarding wizard - Failed GH sync attempts create services

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#5711]
### What happened?

n the wizard, I tried syncing to an empty repo (no readme.md), it failed (as expected), but it still created a service. I retried a few times (having it fail again since the repo is still empty) and eventually, it seems that each failure created a service: 
![Pasted Graphic 2](https://user-images.githubusercontent.com/1912933/230769420-28f0cd96-cf30-4a47-b164-34fd8d4f1182.png)

### What you expected to happen

If the GH sync fails, do not create more and more "ghost" repos on each failed build attempt

### How to reproduce

Start the service creation wizard, choose a complete empty repo, see the build fail to push to GH, and press "retry" a few times. Then go to the main UI (services list) and see many services created

### Amplication version

1.4.6

**Comment by mulygottlieb** [comment]
This also affects the "code view" where I see many services in the dropdown there and many "Initial commit" commits (although non succeeded)

**Comment by morhag90** [comment]
Passed QA:

After retry to build code:

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/97830649/230920635-11c235d6-49ee-4132-917b-752e1ebc06ee.png">
