### ISSUE TITLE
🐛 Bug Report: There is a "jump" before the onboarding wizard starts

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5712]
**Actual:**
After Signup the user sees our platform before the welcome screen is shown

**Expected:**
After Signup the user immediately sees the welcome screen

![Image](https://user-images.githubusercontent.com/112330500/230770129-c4232dae-227d-4ac0-8fde-94bb6310eb73.png)

**Comment by yuval-hazaz** [comment]
this one is no longer relevant
