### ISSUE TITLE
🐛 Bug Report: User sees an empty screen for a long time before the code build log is shown

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5714]
![Image](https://user-images.githubusercontent.com/112330500/230770707-02a4f8fa-15f7-49e5-a964-3c126d97a618.png)

**Expected:**
Show some kind of a loader until the code build log can be shown
Can use this...

![Image](https://user-images.githubusercontent.com/112330500/230772974-e23b7bda-d14e-443b-871d-fb20a1940253.png)

**Actual:**
User sees an empty page and doesn't know what to do

@alexbass86 please show what is expected.

**Comment by kipibass** [comment]
Let's make sure that the loader keeps rotating till the file log component appears

**Comment by alexbass86** [comment]
Let's make sure that the loader keeps rotating till the file log component appears
