### ISSUE TITLE
🐛 Bug Report: 'generate code' step title doesn't match the design

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5719]
**Expected:**

![Image](https://user-images.githubusercontent.com/112330500/230773245-67fb7f6d-6cc9-4f38-bfd8-a477367a24b3.png)

**Actual:**

![Image](https://user-images.githubusercontent.com/112330500/230773264-aa46a32b-5ece-4a06-aefc-5e50de88f49f.png)

**Comment by morhag90** [comment]
Passed QA:

<img width="1649" alt="image" src="https://user-images.githubusercontent.com/97830649/232316614-b548244d-7a3a-485c-9cd8-77bc1fad3317.png">
