### ISSUE TITLE
🐛 Bug Report: User feels like he is stuck when looking at the code build log in the onboarding wizard

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5720]
![Image](https://user-images.githubusercontent.com/112330500/230773823-0ad391c3-6c6a-49c3-a341-90fdeaec84dc.png)

**Expected:**

1. Log box size is constant and the same as in the design
2. When the logs are longer than can be seen the logs are auto scrolled to the bottom
3. The user is unable to scroll the log while we didn't finish the commit action
4. If there is an error then the user sees the scroll bar and can scroll the log to find/view the error message.

**Actual:**
1. Log box size starts small and grows as the logs are added
2. at some point the log box stops growing and the user doesn't see new logs that are being added at the bottom of the log

**Comment by mulygottlieb** [comment]
@tupe12334 please note that (3) - having the scroll bar visible at all times (not just hover) is the most important part here. Then (1) which is also an easy win.

Regarding (2) - auto scroll - unless it's really quick for you, you can drop this part for now and we can open another issue just for that (it will be a lower priority issue, not blocking the release today)

**Comment by GreenMachine01** [comment]
@yuval-hazaz @morhag90 @mulygottlieb @alexbass86 

Here is my proposed solution for the problem of user feeling he is stuck on the build log page.

1. Log box size is constant and the same as in the design
2. When the logs are longer than can be seen the logs are auto scrolled to the bottom
3. The user is unable to scroll the log while we didn't finish the commit action
4. If there is an error then the user sees the scroll bar and can scroll the log to find/view the error message.

**Comment by yuval-hazaz** [comment]
not relevant since we use onboarding with Jovu
