### ISSUE TITLE
🐛 Bug Report: Need to fix text in the git selection step in the onboarding wizard

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5721]
![Image](https://user-images.githubusercontent.com/112330500/230774030-dc1c0ded-7b00-4702-97ac-b901c7dbca30.png)

**Expected:**
"Git"

**Actual:**
"git"

**Comment by morhag90** [comment]
Passed QA:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/97830649/233294793-db722018-8b92-4203-9037-f25d4496dbc0.png">
