### ISSUE TITLE
🐛 Bug Report: Some events are sent multiple times in the onboarding wizard

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5726]
![Image](https://user-images.githubusercontent.com/112330500/230780812-1be70d85-681d-4cc3-b71f-7ba23938ea9c.png)

![Image](https://user-images.githubusercontent.com/112330500/230781155-e9f44bc8-5984-4116-a2b8-4e8505f57052.png)

See events for user - clg999j040000h801r1setpv8

**Comment by GreenMachine01** [comment]
I suspect "ViewServiceWizardStep_Name" is being sent with the wrong name

**Comment by GreenMachine01** [comment]
@morhag90 @yuval-hazaz @mulygottlieb 
I still see duplicate events

![Image](https://user-images.githubusercontent.com/112330500/230886661-a72129da-05cb-4ca1-a102-f25fb12c6ee9.png)

User - clgam4zet0000jh01hx0b6fwq

**Comment by GreenMachine01** [comment]
@morhag90 we need to add the proper milestone.

**Comment by morhag90** [comment]
@GreenMachine01 Done
