### ISSUE TITLE
🐛 Bug Report: in the Auth step of the onboarding the CTA text is not "Continue"

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5735]
![Image](https://user-images.githubusercontent.com/112330500/230795476-55a53375-b153-48c0-a621-fbdf5a6106d4.png)

**Expected:**
CTA text needs to be "Continue"

**Actual:**
CTA text is "Create Service"

**Comment by morhag90** [comment]
Passed QA:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/97830649/232315980-044ce5a2-d28d-4618-9db6-fd779f5cddac.png">
