### ISSUE TITLE
🐛 Bug Report: Wrong loader design used in the service creation wizard

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5737]
**Expected:**

![Image](https://user-images.githubusercontent.com/112330500/230795915-4116a808-dfe9-46e1-b287-952ec0fabe61.png)

**Actual:**

![Image](https://user-images.githubusercontent.com/112330500/230795955-0b438bdc-2a6e-40b6-8127-97436c9c0288.png)

**Comment by morhag90** [comment]
Passed QA:

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/97830649/232316192-0f8fbc8b-8637-4e95-9737-13365f7946f6.png">
