### ISSUE TITLE
🐛 Bug Report: "Close" not capped in the first letter + need to fix the design

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5740]
**Steps to Reproduce:**
1. Open the service creation wizard as a **returning** user

**Expected:**
text on the Close link to be "Close" + match the Figma design

![Image](https://user-images.githubusercontent.com/112330500/230796719-af00ddaf-b6f8-4ea6-a3af-d29e65db498b.png)

**Actual:**
text on the Close link is "close" and doesn't match the design

![Image](https://user-images.githubusercontent.com/112330500/230796534-3247c200-e3d1-470f-b918-82c26f69702e.png)

**Comment by morhag90** [comment]
Passed QA:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/97830649/232316362-fb5cd431-7030-45d0-839c-3d50de600123.png">
