### ISSUE TITLE
🐛 Bug Report: ServiceWizard_ServiceGenerated event is registered on the wrong accountId

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#5746]
### What happened?

ServiceWizard_ServiceGenerated event is registered on the wrong accountId

### What you expected to happen

instead of using userId, we need to use accountId

### How to reproduce

complete the wizard

**Comment by GreenMachine01** [comment]
QA Approved


![Image](https://user-images.githubusercontent.com/112330500/230898509-7cfb7bee-efcb-45d6-a5ea-f2735e92a81e.png)
