### ISSUE TITLE
As BA - I want to know how many users get an error during the code generation step in the service creation wizard

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5761]
As BA - I want to track the number of users who encounter an error during the code generation step in the service creation wizard, and to record their actions taken to address the issue ("try again" or "continue").

![Image](https://user-images.githubusercontent.com/112330500/233107240-52d5598e-469e-4019-97a5-04182b31ce2c.png)

**Description:** 
The aim of this user story is to add new BI events to track user errors during the code generation step in the service creation wizard. The BI event should help us track the number of users who encounter an error and the action taken when encountering an error such as "try again" or "close". This information will help us understand the common problems our users are facing and provide valuable feedback to the development team.

**Requirements:**

_Event#1:_
Event Name - ViewServiceWizardError
Description - When a user gets an error during the service creation wizard
Meta - 
  *Error Info: [the error message or id]
  *Category: Service Wizard
  *Wizard Type: <Onboarding/Create Service>

_Event#2:_
Event Name - ServiceWizardError_TryAgain
Description - When a user gets an error during the service creation wizard and clicks to 'try again'
Meta - 
    *Category: Service Wizard
    *Wizard Type: <Onboarding/Create Service>

_Event#3:_
Event Name - ServiceWizardError_Continue
Description - When a user gets an error during the service creation wizard and clicks to 'continue anyway'
Meta - 
    *Category: Service Wizard
    *Wizard Type: <Onboarding/Create Service>

**Acceptance Criteria:**
1. Events are triggered according to the requirements
2. The event should be recorded in a secure and reliable manner, to ensure that the data is accurate and cannot be tampered with.
3. Any errors or exceptions that occur during the event recording process should be logged and reported to the appropriate parties for resolution.
4. The event recording process should not impact the performance or stability of the system or other user workflows.
5. The event should comply with all relevant laws, regulations, and industry standards related to data privacy and security.

**Comment by GreenMachine01** [comment]
@yuval-hazaz we should consider how to handle such issues such as an empty repo...
Some options:
1. Prevent selection of empty repos
2. Notify the user so he can fix it (immediately after selecting an empty repo)
3. Let the user advance without committing the code (skipping the commit code step)
4. After getting the error getting information on how to solve it and retry

**Comment by barshimi** [comment]
what event would you like to get for first failure, try again and/or close ?
