### ISSUE TITLE
🐛 Bug Report: missing BI event 'ServiceWizardStep_Welcome_CTAClick' in the service creation wizard

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5774]
@yuval-hazaz This is also a reminder to look into why 'ServiceWizardStep_Welcome_CTAClick' stopped being triggered.
if needed ill open a proper bug.

**Comment by overbit** [comment]
## Test result

🔴  `FAILED`

A new user or current user creating a new service doesn't seem to be recorded in amplitude:




![Image](https://user-images.githubusercontent.com/2861984/234618263-2ec27b4b-e6dd-4602-bf5f-4f74addeac33.png)

Potentially related to AdBlocks
