### ISSUE TITLE
Better handling of the "empty git repo" error

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#5776]
### Feature description

Currently, many users face the "empty git repo" error. This seems like a significant friction in our onboarding process.
Today, we treat this error like any other build error, so the user just sees this at the end of the build log with a generic "oops something went wrong" message.

We should ideally identify this even before the build and clearly prompt the user to fix this in advance (perhaps even block the build until it's resolved if we know how to test it).
If this is not possible, we should at least catch this specific error in the build and treat it with a special treatment:

1. Give the user a clear message about the error being an empty git repo
2. Give the user clear instructions on how to fix it. Ideally, since we know the repo name and URL, we can output the set of git commands the user needs to run the create an empty (or with service name) README.md file and push it into the repo's master branch. In this way, the user can just copy-paste the commands we show into her terminal and this will take care of it.

Side note - perhaps we can augment our CLI to create a repo on your behalf (using your existing GH credentials in your terminal) and push a README.md file into it.

### Use case

Less friction for the user when starting with a new repo

**Comment by mulygottlieb** [comment]
Per an idea from @tupe12334 , we can use something similar the Enterprise strategy - identify that the repo is empty, and commit directly to master with an initial commit that adds a README with the service name.

**Comment by GreenMachine01** [comment]
We will tackle this problem via - https://github.com/amplication/amplication/issues/5782
