### ISSUE TITLE
As Maintainer - I want to have visibility of correlated requests across services 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5785]
### Feature description

At the moment, we are lacking any distributed tracing solution in our app. 
Amplication services should implement OpenTelemetry for trace collections and investigate a solution for Kafka tracing.

As OpenTelemetry extractor, we should consider AWS X-Ray or another tool. 

#### Tech notes

The initial implementation should focus on the `amplication-pull-request-service` to allow a better understanding of the performances of each logic block in the PR creation process

**Comment by mulygottlieb** [comment]
@overbit is this now done?
