### ISSUE TITLE
🐛 Bug Report: Unable to build service generated with MongoDB plugin

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5791]
### What happened?

Creating a service with mongodb plugin will generate a server application that fails to build due to malformed file(s) as shown in the app here:
https://github.com/overbit-work/microservices/blob/amplication/apps/service-b/src/health/base/health.service.base.ts

### What you expected to happen

The generated app is buildable and runnable without issues. 

### How to reproduce

1. create a new service
2. select the latest mongo db plugin
3. build the service
4. observe the generated code / try to build and run the generated server.

Alternatively, this is the input.json describing the build
[input.json.txt](https://github.com/amplication/amplication/files/11230315/input.json.txt)

### Amplication version

v1.5.0

**Comment by mulygottlieb** [comment]
This does not reproduce for me at all on production with two separate attempts.
