### ISSUE TITLE
🐛 Bug Report:  The "Home" remain even after we're not hovering on the amplication icon after clicking it

### ISSUE THREAD

**Issue by Chirag8023** [amplication/amplication#5792]
### What happened?

when I click on the amplication icon there's a tag appear says "Home", usually this should go away when I move away my cursor awy from the icon but it stays until I click somewhere on the screen.

![Screenshot (23)](https://user-images.githubusercontent.com/84070677/231890375-c666ae9e-3b7a-4044-903d-32c22c9cd940.png)

### What you expected to happen

when we click on the amplication icon on the top left corner, it shows us the tag "Home" while cursor is hovering on that icon and when we move away the cursor then the tag should also become disappear.

### How to reproduce

open the amplication app and just click on the amplication logo one the top left side of the screen. The tag "Home" will appear near the icon , now move away the mouse cursor from the icon. The tag "Home" will stay until we click somewhere on the screen.

### Amplication version

1.5.0

### Environment

Online app : app.amplication.com

**Comment by GreenMachine01** [comment]
I noticed the problem happens with other tooltips as well such as service tabs
![image](https://user-images.githubusercontent.com/112330500/234033981-a718073d-f784-4d32-ba6a-5a4f818c7d17.png)
