### ISSUE TITLE
🐛 Bug Report: Duplicate function name when using a self-relation property with the same name

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#5799]
### What happened?

The resolver class is generated with a duplicate function name when using a self-relation property with the same name of the entity in plural 

e.g. 
entity: employee
field: employees

the resovler includes two function called employees - one for findMany and another one for the relation 

<img width="770" alt="image" src="https://user-images.githubusercontent.com/43705455/232115103-e5514626-0c4a-417c-b0d7-694d6ffbec0b.png">

<img width="770" alt="image" src="https://user-images.githubusercontent.com/43705455/232115134-93ee645f-c526-48a7-8a4b-77233d26b378.png">

### What you expected to happen

avoid duplicate name

### How to reproduce

entity: employee
field: employees

### Amplication version

1.5.0

**Comment by overbit** [comment]
TEST PASSED 


![Image](https://user-images.githubusercontent.com/2861984/237050832-32e2704f-9de6-48d2-8f6a-5e7ad10de1cf.png)
