### ISSUE TITLE
Wizard input fields should be a form

### ISSUE THREAD

**Issue by MichaelSolati** [amplication/amplication#5818]
### Feature description

When selecting the name of a service, as well as setting the base directory, you can't just click enter after typing in the value you want to continue. I feel like you should be able to, it's more intuitive to be able to.

**Comment by jaysoni-ash42** [comment]
@MichaelSolati  can i work on this issue?

**Comment by jaysoni-ash42** [comment]
@MichaelSolati  you mean on hitting enter it should continue. are there other things that need to be consider?

**Comment by MichaelSolati** [comment]
Mostly, but like when you get to the database options, you should be able to click tab once to get to each db option, click enter to toggle it on, etc..

Hopefully this helps explain

https://www.loom.com/share/587e40d9660244c18e5140a918af4b69

**Comment by jaysoni-ash42** [comment]
@MichaelSolati  just a question for selecting the repository the Dialogs should also be controlled by the keyboard or just the service wizard configuration?

**Comment by MichaelSolati** [comment]
If it could be controlled by keyboard that would be awesome.

**Comment by jaysoni-ash42** [comment]
@MichaelSolati  would try that for the current feature i am able to do that for the underlying components for the services wizard  would pull up a pr and then we can procceed from there.

**Comment by MichaelSolati** [comment]
Sounds perfect, I'll assign it.
