### ISSUE TITLE
As BA - I want to know when a user starts to create a new service

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5832]
**Requirements:**
1. Server side event

Event:
Event Name - ServiceWizardStart
Description - This event is triggered when a user actively starts the flow of the service creation
Meta -
*Category: Service Wizard
*Wizard Type: <Onboarding/Create Service>

**Acceptance Criteria:**

1. Events are triggered according to the requirements
2. The event should be recorded in a secure and reliable manner, to ensure that the data is accurate and cannot be tampered with.
3. Any errors or exceptions that occur during the event recording process should be logged and reported to the appropriate parties for resolution.
4. The event recording process should not impact the performance or stability of the system or other user workflows.
5. The event should comply with all relevant laws, regulations, and industry standards related to data privacy and security.

**Comment by barshimi** [comment]
do we have event name for that ?

**Comment by GreenMachine01** [comment]
@barshimi I am waiting for feedback from Yuval on the exact trigger.

**Comment by barshimi** [comment]
ok, thanks

**Comment by GreenMachine01** [comment]
canceled
