### ISSUE TITLE
🐛 Bug Report: DSG otherResources contains wrong properties

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5838]
### What happened?

In the DSG context, when `otherResources` is populated, it gets populated with properties that should not be there like in the example here:

[messages.json.txt](https://github.com/amplication/amplication/files/11284531/messages.json.txt)
This message is the event from the CodeGenerationRequest topic.  

### What you expected to happen

`otherResources` to contain only relevant property for the resource described.properties

### How to reproduce

Build a new service and check the event emitted by the amplication-server into the code generation request topic.

### Amplication version

v1.5.2

**Severity**: Minor

**Comment by GreenMachine01** [comment]
@overbit whats the severity of the bug?

**Comment by overbit** [comment]
It needs a bit of triage but from the top of my head, I'd say a minor since there are not many users with massive projects

**Comment by mulygottlieb** [comment]
@overbit @abrl91 
Please see if this by itself can solve the issue with the large Kafka message on DB import with 300 entities. If it can - perhaps this is the easiest initial fix. In that case, we will move this issue into 'Todo' and handle it first. Perhaps it's a good idea to fix this anyway now that we plan on importing hundreds of entities.
@GreenMachine01  FYI
