### ISSUE TITLE
🐛 Bug Report: Kafka plugin is not working

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5844]
### What happened?

Kafka plugin is not currently working as described in the plugin documentation https://www.npmjs.com/package/@amplication/plugin-broker-kafka 
Moreover, building a service  with or without Kafka plugin generates currently the exact same code.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/2861984/233669452-fd122d79-14cc-44a1-9d5d-99455dd0c391.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/2861984/233669453-35aa21f8-8c9f-4dc6-adf9-de3cfd58b049.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/2861984/233669455-e950edc9-cf8d-4518-9a62-e6c7614551ee.png)

### What you expected to happen

Kafka plugin will generate additional files during the code generation

### How to reproduce

1. Create a service
2. Build it
3. Create a message broker
4. Connect the message broker to the service
5. install Kafka plugin
6. build again
7. Check the differences (NONE)

### Amplication version

v1.5.2

**Comment by tupe12334** [comment]
https://github.com/amplication-test/kafka-example/pull/1/files#diff-29740bacdc91a1dee535c0a4afe35bb593144377f8a28b9c558e36e50e4fe906

I don't get it, its work for me

**Comment by overbit** [comment]
Not an issue anymore
