### ISSUE TITLE
🐛 Bug Report: Wrong tooltip in the last commit sha

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5846]
### What happened?

Wrong tooltip in the last commit sha: when we have hover on the last commit sha, we see a tooltip saying "uninstall" 
![image](https://user-images.githubusercontent.com/39680385/233681718-0a5d0d41-fc50-4ba5-af95-345c0e034219.png)

### What you expected to happen

We don't need a tooltip there 

### How to reproduce

- create a service
- click on build
- see in the last commit section the commit sha
- hove on it

### Amplication version

1.5.2

**Comment by abrl91** [comment]
@GreenMachine01 
please confirm the content of the tooltip

**Comment by Himanxu1** [comment]
Assign this to me .Also mention the message

**Comment by GreenMachine01** [comment]
@alexbass86 do yo have example for what needs to be shown in the tooltip?

**Comment by alexbass86** [comment]
@GreenMachine01 We don't need a tool tip here, please remove

**Comment by jaysoni-ash42** [comment]
@Himanxu1  abrl91 can i work on this issue?

**Comment by abrl91** [comment]
@Himanxu1 are you still interested in working on this issue?
@jaysoni-ash42 let's wait for Himanxu1's response

**Comment by jaysoni-ash42** [comment]
@abrl91  since no reply from the @Himanxu1 can you assign this to me?

**Comment by souravjain540** [comment]
> @abrl91  since no reply from the @Himanxu1 can you assign this to me?

Let me know if you need any help.

**Comment by souravjain540** [comment]
@gitstart I appreciate your work and contributions to this project.

they are so valuable, and I want them to be more.

But it is not the best practice to make a PR for the issue which is assigned to someone else, and someone else is working on it.

I think we can connect on a call(let me know when we can do that), to discuss, how I can make your contributions more easy, without disturbing other community members.

I am very thankful for your contributions, and let's take it to another level together. hope you understand.

**Comment by abrl91** [comment]
passed QA


![Image](https://github.com/amplication/amplication/assets/39680385/aff947d7-6830-4100-8095-9288c7d1e2fd)

**Comment by abrl91** [comment]
closed by https://github.com/amplication/amplication/pull/5913
