### ISSUE TITLE
As a plugin developer - I want to separate the plugin user settings from plugin developer configuration

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#5851]
Today, our plugins have a settings object found at _.amplicationrc.json_ on the plugin root.
Today, this object has no hierarchy - all the settings are at the root level e.g. 
`{
    "host": "localhost",
    "port": 3306,
    "user": "root",
    "password": "admin",
    "dbName": "my-db"
}`

We want this object to separate the user-settings part (that appears in the plugin settings UI as of today), from other settings that the plugin developer wants to enforce that can relate to various Amplication concepts, e.g. things to do during plugin installation, or removal, or enforce prerequisites, etc.
For example:
`{
    "general settings" : 
    {
      "host": "localhost",
      "port": 3306,
      "user": "root",
      "password": "admin",
      "dbName": "my-db"
    },
    "system settings":
    {
      "require authentication entity": true
    }
}`

- [x] #5892
- [ ] #5871
- [ ] Deprecating all the plugins that are already using the current `.amplicationrc` format
- [ ] As a plugin dev - I want to have required plugins configuration in the `.amplicationrc` settings

**Comment by morhag90** [comment]
Passed QA:

<img width="736" alt="image" src="https://github.com/amplication/amplication/assets/97830649/ea4d9561-3c7f-4a71-9a44-59012e1c4d09">
