### ISSUE TITLE
As User - I want to be able to create a repo even if I am using a personal git account

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5854]
![Image](https://user-images.githubusercontent.com/112330500/234269196-15a62aa5-bd40-420c-bfc1-058fc0a58d56.png)

**Overview:**
Currently, if a user selects a "Personal" Git organization he will not see an option to "create" a repo within the git connection component.
This makes it difficult for users to create a new repo for testing out Amplication. (They need to manually go to the Git org and set it up)

**Requirements:** (Only relevant for GitHub)
1. Always show a "create repo" option even if the git org is personal
2. for personal org clicking the create repo CTA will open - "https://github.com/new?&owner=[owner name]" (in a new tab)
3. in the Repo selection pop-up add an option for creating a repo - always visible and the same logic as above

![Image](https://user-images.githubusercontent.com/112330500/234270160-abfaf7d2-f672-4b8f-88a4-f589ba317c5f.png)

**Figma** - https://www.figma.com/file/EXpu3W16xQDQ6NnEpzQE9R/%23none---Supporting-more-Git-providers?node-id=2041%3A14924&t=PvMmrA3CnvACj0Xp-1

**Comment by GreenMachine01** [comment]
@barshimi as part of this ticket please investigate if we can use Git as a solution instead of GitHub and if it will allow us to create a repo within Amplication for personal GitHub accounts.

**Comment by yuval-hazaz** [comment]
please use this URL https://github.com/new?&owner=[owner name]

**Comment by yuval-hazaz** [comment]
@GreenMachine01 I am waiting with this item until @barshimi completes the refactoring of the client so we will not create conflicts. 
BTW, in case @barshimi is still working on the refactoring it may be very easy for him to include this item as part of it

**Comment by morhag90** [comment]
Passed QA: 


https://github.com/amplication/amplication/assets/97830649/894585f0-d9b7-47a0-b35e-fdfe356a642b
