### ISSUE TITLE
[Security] Update `class-validator` to v0.14 on generated app

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5877]
The amplication generated application should be built with the latest version of `class-validator` to fix the vulnerability described here:  
https://github.com/amplication/amplication/security/dependabot/657
https://security.snyk.io/vuln/SNYK-JS-CLASSVALIDATOR-1730566

## Tech notes

Version 0.14 comes with a breaking change related to `forbidUnknownValues` option default value that has been swapped.
This will cause any generated Dto that is missing the validation metadata (validation decorators) to automatically fail.

⚠️ setting `forbidUnknownValues: false` **is not an acceptable solution** but instead we need to update the dto generation with the correct validator decorators like in the example below showing the current vs the future setup
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/2861984/234594854-42eca5bb-c812-409f-8d24-f519a97454da.png">

**Comment by ognjenjevremovic** [comment]
Hey @overbit, may you assign the issue to me please?  
I would like to give this one a go.

The scope of the issue should be related to `data-service-generator` only?

**Comment by overbit** [comment]
Yes, you are correct, the scope should be just related to the `data-service-generator`. 
Assigned! Good luck
