### ISSUE TITLE
Align design system library with the design in Figma

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5882]
### Feature description

Currently we have a drift between components/styles in design system library and the design in Figma.
Here is the list of components that has to be updated:

- [ ] Update **Button** component according to the design
- [ ] Update **Dropdown** component according to the design
- [ ] Update Sass **mixins for text** according to the design
- [ ] Update Sass **mixins for colors** according to the design
- [ ] Update **Input** component according to the design
- [ ] Update **Footer** component according to the design
- [ ] Create **Card** component according to the design
- [ ] Update **Code Browser** component according to the design

**Comment by olalekanteeblaze** [comment]
Can I work on this?

**Comment by mulygottlieb** [comment]
Hi @olalekanteeblaze,
Unfortunately, this issue is not an issue we are opening to the community. It involves some architecture decisions we need to take inside the core team.
Feel free to check out the "open to community" issues we have, or ask for issues on our Discord.
Sorry about that.
