### ISSUE TITLE
🐛 Bug Report: Link Open with GitHub is not working

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5903]
### What happened?

![image](https://user-images.githubusercontent.com/6080188/236143808-00bd45a0-5251-4317-b0a2-4312a6f683e9.png)
Open with GitHub is not working

### What you expected to happen

Link should redirect to GitHub website

### How to reproduce

open project page
click on the link "Open with GitHub"

### Amplication version

1.5.5

### Environment

production

**Comment by jobayer12** [comment]
@EugeneTseitlin I'm trying to generate this in the production environment. "Open with GitHub" is working properly. Has the issue already been resolved?

**Comment by GreenMachine01** [comment]
Cant reproduce.
