### ISSUE TITLE
🐛 Bug Report: Helm Chart Plugin will not install - getting JSON parse error

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#5932]
### What happened?

Testing on staging (1.5.5 - staging), and trying to install the Helm Charts plugin - I cannot install it (UI doesn't show any change after clicking 'Install'), and in the console I'm getting a JSON parse error:

`Uncaught SyntaxError: Expected double-quoted property name in JSON at position 238
    at JSON.parse (<anonymous>)
    at 4670.1e85fbc4b2dd6ac3.js:1:551
    at 196.3818474bd32c97ca.js:1:3679
    at 6146.7d9b696c59ff7e98.js:1:321
    at Object.Re (/vendor.b7970029369a67e1.js:102:1329244)
    at je (/vendor.b7970029369a67e1.js:102:1329398)
    at /vendor.b7970029369a67e1.js:102:1349280
    at Lr (/vendor.b7970029369a67e1.js:102:1349374)
    at Fr (/vendor.b7970029369a67e1.js:102:1349788)
    at /vendor.b7970029369a67e1.js:102:1355226
(`

Which seems to be related to this escaped JSON:
`"{\"root_level\":false,\"directory_name\":\"helm\",\"server\":{\"chart_version\":\"0.0.1\",\"application_version\":\"0.0.1\",\"repository\":\"ghcr.io/NAMESPACE/IMAGE_NAME\",\"tag\":\"latest\",\"host\":\"server.example.com\",\"port\":\"3000\"},\"admin_ui\":{\"enabled\":false,"`

### What you expected to happen

Plugin should install without errors

### How to reproduce

Go to staging and try to install the Helm Charts plugin

### Amplication version

1.5.5 (on staging towards 1.5.6)

**Comment by levivannoort** [comment]
This issue was specific to the staging environment, where the settings field in the `plugin-api` database were partially filled for the 0.0.1 and the 0.0.3 version. Parsing broken JSON from the database likely cause these errors.
