### ISSUE TITLE
🐛 Bug Report: Stigg webhook generate too many errors

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5941]
### What happened?

<img width="1120" alt="image" src="https://github.com/amplication/amplication/assets/2861984/4057c93f-f0e4-4266-b6d0-307a66fe4e0f">

### What you expected to happen

The platform should not fail

### How to reproduce

NA

### Amplication version

v1.5.7

**Comment by EugeneTseitlin** [comment]
Check for existing account and issue a warning when trying to create account more than once.
