### ISSUE TITLE
As a User - I want a plugin  that creates `.devcontainer.json` file to be able to use GitHub Codespaces

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#5962]
### Feature description

With the introduction of GitHub Codespaces, it can be super easy to start development directly in your webbrowser. But as our project structure can be opinionated we should create a `.devcontainer/devcontainer.json` file, containing instructions to start the codespace environment.

Documentation: https://github.com/features/codespaces

### Use case

After generating code, a user can start to further develop generated code directly after merging in the GitHub UI.

**Comment by levivannoort** [comment]
This addition to our plugin-catalog is also for adoption by a community member. Please do reach out on discord when you have any questions regarding development of plugins.

Also if you're wanting to tackle this issue, please let us know so we can provide you with any documentation that is needed.

**Comment by souravjain540** [comment]
@levivannoort i don't think it is good for first timers?

**Comment by levivannoort** [comment]
@souravjain540 I don't think so, it requires a bigger understanding of Amplication architecture and the work is to be done on `amplication/plugins` and `amplication/plugin-catalog`, not this repository.

**Comment by toukirkhan** [comment]
Can I work on this one? @souravjain540

**Comment by souravjain540** [comment]
@toukirkhan  assigned :) let me know if you need any help!

**Comment by toukirkhan** [comment]
sure!

**Comment by toukirkhan** [comment]
@souravjain540 can you suggest some documentation to help me with this issue?

**Comment by levivannoort** [comment]
We're currently running GitHub octernship, where one of the tasks is to build a simple plugin. This has some more information on how to approach creating a plugin - https://github.com/Amplication-Octernships/Amplication-Plugin-Task.

Other parts of the documentation site could be quite usefull aswell:
- [plugin creations](https://docs.amplication.com/plugins/how-to-create-plugin/)
- [plugin testing](https://docs.amplication.com/plugins/how-to-test-plugin/)
- [plugin publishing](https://docs.amplication.com/plugins/publish-plugin/)
- [plugin event types](https://docs.amplication.com/plugins/plugin-events/create-server/)

**Comment by toukirkhan** [comment]
Cool! @levivannoort thank you so much!

**Comment by toukirkhan** [comment]
@souravjain540 Hey! Yes, I have started working on the issue.

**Comment by souravjain540** [comment]
@toukirkhan when can I expect a PR?

**Comment by toukirkhan** [comment]
@souravjain540 Hi, I will try to raise a PR within the upcoming week.

**Comment by toukirkhan** [comment]
Update: Am working on the issue.

**Comment by TheLazron** [comment]
Hey @souravjain540! Can I work on this issue please

**Comment by souravjain540** [comment]
> Hey @souravjain540! Can I work on this issue please

assingned.

**Comment by TheLazron** [comment]
Hey @levivannoort, @souravjain540 is the devcontainer.json file only supposed to be created for the generated server or the admin-ui as well?


**On further note I was able to generate the required file for the generated server using the plugin.**
![image](https://github.com/amplication/amplication/assets/72215253/94006150-aedd-4a9d-8acc-228334fb2f99)


But as it was mentioned earlier in the issue that the work is to be done in the `amplication/plugins` and `amplication/plugin-catalog` and not this repository. So how am I supposed to proceede further with making a PR

**Comment by TheLazron** [comment]
@souravjain540 @levivannoort can I please get the required help

**Comment by levivannoort** [comment]
Hey @TheLazron, sorry for the late response, this went under the radar in my absence. Great job on getting the local-data-service-generator setup to work and being able to generate the required files/directories.

1. Regarding the question of whether to create it for generated server or both of the components, for now I think we can start with only the server, active development on de generated code is almost exclusively done on the server side.
2. Yes, the plugin itself can be created as a pull-request on the https://github.com/amplication/plugins, to be able to integrate it on the amplication, the plugin-api needs to be made aware of the plugin's existence, this can be done through a pull request on the https://github.com/amplication/plugin-catalog, point to a publish version of the npm package. Start with getting the plugin as a PR on the plugins repository and we'll go from there!

**Comment by TheLazron** [comment]
Thanks for getting back @levivannoort. I will make a PR to the referred repository asap, as I would have to look a bit into the contents for the ```devcontainer.json file```.

**Comment by Tjsingh01996** [comment]
@souravjain540 can you pls assign me this task

**Comment by souravjain540** [comment]
@TheLazron are you working on the issue?

**Comment by souravjain540** [comment]
@Tjsingh01996 assigned.

**Comment by levivannoort** [comment]
@Tjsingh01996 I unfortunately need to close this issue due to it being a duplicate of - https://github.com/amplication/amplication/issues/7012.
