### ISSUE TITLE
📖 Documentation: Syncing code to Bitbucket

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5964]
This document should describe how the sync to Bitbucket is going to work.
See PR for documentation - https://github.com/amplication/docs/pull/280

**Comment by GreenMachine01** [comment]
@abrl91 FYI

**Comment by dericksozo** [comment]
Hey @GreenMachine01 @abrl91 @mulygottlieb: If I'm understanding correctly, [PR #280](https://github.com/amplication/docs/pull/280) completely takes cares of this one?

**Comment by dericksozo** [comment]
Hey @GreenMachine01 I just created a new PR that addresses a few things and adds new content.
