### ISSUE TITLE
🐛 Bug Report: Open with Bitbucket link points to the wrong place

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5978]
### What happened?

https://jam.dev/c/6b4618d0-a80e-4a90-8072-e7f798e58c9c 

After a successful build and push, the open to bitbucket link in the footer open a wrong location (wrong workspace).

### What you expected to happen

The correct PR gets open

### How to reproduce

1. create a new service and connect it to bitbucket.
2. build 
3. click on the `Open with Bitbucket`

### Amplication version

next

**Comment by abrl91** [comment]
passed QA


https://github.com/amplication/amplication/assets/39680385/93cf325f-00c0-44e7-8d74-3d34ddaedc20

**Comment by abrl91** [comment]
![Image](https://github.com/amplication/amplication/assets/39680385/92ad862f-55d3-4c22-aaa3-4823be9c33d0)
