### ISSUE TITLE
🐛 Bug Report: Build page is missing the Push Changes to Bitbucket component

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5980]
### What happened?

When a resource / project is connected to Bitbucket the build page doesn't show the `Push Changes to Bitbucket component`.
All looks good for the case of GitHub connection.

GitHub
<img width="1192" alt="image" src="https://github.com/amplication/amplication/assets/2861984/fe56b1a0-b0cb-459f-bdec-71fd3825e348">

### What you expected to happen

There should not be differences apart from the provider details in the build page

### How to reproduce

Connect to bitbucket and build a service.

### Amplication version

next

**Comment by GreenMachine01** [comment]
cant reproduce by Amit
