### ISSUE TITLE
🐛 Bug Report: Push to Github fails with an error: `URL using bad/illegal format or missing URL`

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5983]
### What happened?

 Push to Github fails with an error, not only when the project contains services connected to Bitbucket and Github, but also when all the services in the project are connected to Github

It happens in a Free & Pro plan

![image](https://github.com/amplication/amplication/assets/39680385/497aa424-56ca-4e85-a1df-a8e1f2264a93)

![image](https://github.com/amplication/amplication/assets/39680385/3baae529-cfc2-4cba-acca-81045aa403ca)

### What you expected to happen

Push to GitHub should finish successfully

### How to reproduce

- create a service and connect it to GitHub
- click on the build button

### Amplication version

next

**Comment by abrl91** [comment]
@overbit 
https://stackoverflow.com/questions/67858153/url-using-bad-illegal-format-or-missing-url-when-publishing-branch
could it be related to the `push.autoSetupRemote=true`
![image](https://github.com/amplication/amplication/assets/39680385/cbc1151e-58fb-4001-89ab-0e8f7959f1ea)

**Comment by EugeneTseitlin** [comment]
I've tried to reproduce the issue according to the described steps, but haven't succeed:
https://jam.dev/c/76c48bf9-69a8-46a9-8447-7457ee7b3f45
Please, add more details or instruction about the reproduction.

**Comment by abrl91** [comment]
@EugeneTseitlin I noticed you tested it in prod. The bug is in sandbox

**Comment by abrl91** [comment]
passed QA


https://github.com/amplication/amplication/assets/39680385/16439d4a-c444-44f2-88b8-953299f2b3fa
