### ISSUE TITLE
As User -  I want to set custom attributes on the entity level

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5989]
As a user, I want to set custom attributes on the entity level in Amplication, so that I can better categorize and manage my entities according to my specific needs and workflows.

**Example:**
![image](https://github.com/amplication/amplication/assets/1912933/3c55689b-80ec-4578-9ba1-02a00363955c)

**Prisma Attributes and Functions:**
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#attributes
https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-attributes
https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#using-functions

**Requirements:**
1. **Custom Attributes on Entity Level**: Users should be able to define custom attributes for each entity. This could include a variety of data, such as metadata, validation rules, UI hints, etc. The system must ensure the integrity and validity of these attributes. The custom attributes should be stored persistently, and should not affect the normal functioning of the entity or its relationship with other entities.

2. **UI for Managing Entity-Level Custom Attributes**: A user-friendly UI should be provided for managing these custom attributes. The UI should enable users to add, remove, and modify custom attributes at the entity level. It should provide feedback on the validity of the attributes and any constraints that must be met. The UI should also display a summary of the custom attributes set for each entity.

3. **Persistence of Entity-Level Custom Attributes**: All entity-level custom attributes should be saved and persisted across sessions. The system should maintain the association between the custom attributes and their respective entities, even when these entities are modified.

4. **Documentation and Support for Entity-Level Custom Attributes**: Clear and concise documentation should be provided to guide users on how to use this feature. The documentation should include details on the types of custom attributes that can be set at the entity level, how to manage them via the UI, and any constraints or rules related to the custom attributes. Additionally, there should be in-app help or tooltips to guide users while using this feature.

**Comment by GreenMachine01** [comment]
Support free text field (not use a selection from a dropdown list)

**Comment by abrl91** [comment]
passed QA ✅ 
same comment as:
https://github.com/amplication/amplication/issues/5990#issuecomment-1560679331
