### ISSUE TITLE
As User - I want to easily understand how to select private or public repo when I create a new repo via Amplication

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5994]
![Image](https://user-images.githubusercontent.com/112330500/238192074-d6136ded-352f-401a-bd28-f11350e32600.png)

**Requirements:**

1. Set the text to always be "Public Repo"
2. If the toggle is ON - the selection of the user is public repo
3. If the toggle is OFF - the selection of the user is private repo
4. The default should be for the Public repo to be selected.

**Comment by jaysoni-ash42** [comment]
@GreenMachine01  can you assign this to me ? i want to work on this issue

**Comment by GreenMachine01** [comment]
thanks @jaysoni-ash42 
A team member is already finishing up with this item.

**Comment by morhag90** [comment]
Passed QA:



![Image](https://github.com/amplication/amplication/assets/97830649/4b5b4cda-9e5b-4027-8e8f-1712113a4aa8)
