### ISSUE TITLE
As PO - I want to improve the Bitbucket notification text

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5995]
![Image](https://github.com/amplication/amplication/assets/112330500/8506d9cf-9e5a-4484-be34-466a4a3ffe8e)

New text - "This feature requires an Enterprise plan.  For more information, Contact Us"

**Requirements:**
1. Update the text in the Bitbucket notification according to the design example above.
3. Change the CTA to open - https://amplication.com/contact-us (in a new tab)

**Comment by overbit** [comment]
# Test Result ✅
