### ISSUE TITLE
As PO- I want to improve the commit message the user gets in his git provider

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5997]
![Image](https://user-images.githubusercontent.com/112330500/238193225-a756da4f-3837-4596-b9c0-e04b4fa4a349.png)

**Comment by abrl91** [comment]
passed QA ✅ 

![Image](https://github.com/amplication/amplication/assets/39680385/6924d4b5-6c42-4271-84b5-52d3fa2918ad)



![Image](https://github.com/amplication/amplication/assets/39680385/0401b46a-95a7-4fa1-b64d-4d6d4d80a608)
