### ISSUE TITLE
🐛 Bug Report: Code generation fails when using MongoDB

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6006]
### What happened?

Code generation fails when using MongoDB. Getting the following error:
![image](https://github.com/amplication/amplication/assets/39680385/0b42f218-0141-4763-b2e0-51acbcc252e4)

### What you expected to happen

code generation should finish successfully

### How to reproduce

create a service with MongoDB as a DB

### Amplication version

1.5.8

**Comment by overbit** [comment]
It seems to related to just mongo plugin.. https://github.com/amplication/amplication/actions/runs/4982210814/jobs/8917585389?pr=6007

**Comment by overbit** [comment]
Fixed by re-releasing the master version. The issue was related to a buggy beta version published as `latest` tag instead of `beta`
