### ISSUE TITLE
🐛 Bug Report: Wrong text design in select git org dropdown

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6011]
**Actual:**

![Image](https://github.com/amplication/amplication/assets/112330500/a43e20b4-053a-4a37-b062-d69aff45f245)

**Design:**

![Image](https://github.com/amplication/amplication/assets/112330500/c24a50e7-2b45-4413-9edf-55591757db42)

**Comment by GreenMachine01** [comment]
@jaysoni-ash42 great. assigned to you. thank you!

**Comment by rielAsh24** [comment]
@GreenMachine01 Hey! I'd be glad to work on this issue. Would request to be assigned.

**Comment by GreenMachine01** [comment]
@rielAsh24 thanks. a community member already picked it up. if it becomes available I will check with you.

**Comment by GreenMachine01** [comment]
@yashp4858  thanks. a community member already picked it up. if it becomes available I will check with you.

**Comment by GreenMachine01** [comment]
@alexbass86 please add instructions on all the needed changes to make the drop-down fit the design requirements + add a link to the Figma.

**Comment by martinez-hugo** [comment]
Hello ! Does this issue is available to work on it ?

**Comment by GreenMachine01** [comment]
@souravjain540 FYI

**Comment by professorabhay** [comment]
Hey @souravjain540, If that issue is still not resolved then please assign it to me. I would like to contribute!

**Comment by souravjain540** [comment]
@martinez-hugo do you want to work on it?

**Comment by martinez-hugo** [comment]
Yes of course !

**Comment by souravjain540** [comment]
assigned. please make a PR :)

**Comment by martinez-hugo** [comment]
So just for checking there are just only one place to change this design ?

**Comment by martinez-hugo** [comment]
@souravjain540 this issue is already fix in fact because dropdown is designed like described in the top of issue
<img width="587" alt="Capture d’écran 2023-10-03 à 08 57 05" src="https://github.com/amplication/amplication/assets/121498803/ba2a11bd-5fff-4887-a951-5e620f585916">

**Comment by martinez-hugo** [comment]
That's done @souravjain540

**Comment by mulygottlieb** [comment]
Passed QA:
![image](https://github.com/amplication/amplication/assets/1912933/f10b15b1-be1b-4372-91ff-ebe2df4d4404)
