### ISSUE TITLE
As PO - I want to improve some of the design for the quick editing of the service and project name within the banner

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6024]
**Overview:**
We released recently a shortcut for users that want to update the service or project name where they can now do it directly from the banner that displays the names.
There are a few small UI improvements needed.

![Image](https://github.com/amplication/amplication/assets/112330500/1facffd2-414a-4f3b-9a90-4e095bb08570)

**Requirements:**

1. The edit/pencil icon should show up immediately as the user hovers over the banner (now it will show up only when the user hovers over the name)
2. When the edit icon is shown the name of the service/project shouldn't move --> the edit icon should just show up next to the text
3. The success and error icons should be closer to the text
4. the "Error:" text within the error tooltip should be red as in the design (#F85B6E)
5. Problematic texts in the name should be red as in the design (#F85B6E)

![Image](https://github.com/amplication/amplication/assets/112330500/391b62b8-2387-42c4-9830-7500387b5f80)

![Image](https://github.com/amplication/amplication/assets/112330500/1d9400c9-c18b-4b05-9852-4a2e44306e71)

**Comment by GreenMachine01** [comment]
@lokeswaran-aj wanna take this few fixes?

**Comment by yashp4858** [comment]
@GreenMachine01 Hey can I work on this issue.
if yes? than can I know the exact location of file where I can edit the code
I am beginner to open source

**Comment by GreenMachine01** [comment]
@souravjain540 please assign yashp4858.
I for some reason cant do it.

@EugeneTseitlin can you point him in the right direction?

**Comment by akshay-bharadva** [comment]
@souravjain540 I want to work on this.

**Comment by GreenMachine01** [comment]
@akshay-bharadva assigned it to you. good luck!

**Comment by GreenMachine01** [comment]
let's check the item without the highlight of the character functionality.

**Comment by Akshaybagai52** [comment]
Hey @GreenMachine01  if this issue still open can you assign it to me
Thanks

**Comment by GreenMachine01** [comment]
no longer relevant as we have a new UI.
