### ISSUE TITLE
As User - I want to be able to quickly restore the Amplication default user entity if it was deleted

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6028]
**Overview:**
We now allow users to delete the 'User' entity this might lead to users making a mistake and deleting the entity or just changing their minds. We want to allow users to quickly restore the User entity if it was deleted.

**Requirements:**

1. If 'User' entity doesn't exist in the service the user can create it like any other entity
2. When we see the user is requesting to create a 'User' entity we will show a notification to ask the user if he wants to use the default entity by Amplication or create his own version.
3. if the user selects to use the version by Amplication we will create the User entity with all the fields and setup like it is created when setting up a new service with Auth.

**Comment by mulygottlieb** [comment]
@GreenMachine01 please provide the relevant text for the user

**Comment by GreenMachine01** [comment]
Rough layout:
![image](https://github.com/amplication/amplication/assets/112330500/6f322793-fdcd-43cd-94b5-2f8dd9a0bbaa)

**Text:**
Restore 'User' Entity?
We've noticed you're creating a new 'User' entity. This entity is used by the Authentication plugin. Would you like to:

1. Restore the Default 'User' Entity - This will re-establish the original 'User' entity provided by Amplication, including all associated settings and functionalities.

2. Create a New 'User' Entity - This will create a fresh 'User' entity for you to customize as per your needs. Please note that this may require additional configuration for the Authentication plugin.

Please select your preferred option to continue. 

[Restore Default]    [Create New]

**Comment by mulygottlieb** [comment]
QA Passed:


![Image](https://github.com/amplication/amplication/assets/1912933/e01c0cfb-dc20-4a46-9eb3-09630a5cc79d)


and subsequently, the user is re-created:


![Image](https://github.com/amplication/amplication/assets/1912933/395a2850-ea7b-48ea-983a-65f4d5c08a56)

**Comment by mulygottlieb** [comment]
@morhag90 I am moving this to Passed QA, but please open another ticket for option 2 (custom user entity) to be handled as part of the "rename/mapping" task
