### ISSUE TITLE
🐛 Bug Report: UI/UX - Middle Window in the main screen Lacks Padding on the Right Side.

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#6029]
### What happened?

**Issue Summary:**
The app's main screen displays a middle window that needs to be appropriately padded on the right side. 

**Issue Details:**
When accessing the app's main screen, users encounter a middle window not adequately padded on the right side. 
As a result, the window's contents need to be positioned closer to the edge, causing an imbalance in the layout and reducing the overall aesthetic appeal.

![image](https://github.com/amplication/amplication/assets/96179897/f277d7a2-98d3-4901-a982-4b2800bf19a5)

### What you expected to happen

All sides should have a padding of 16px:
padding: 16px 16px 16px 16px;

### How to reproduce

In main project

### Amplication version

1.6.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jaysoni-ash42** [comment]
@alexbass86 i wan to work on this issue? but   when the scroll bar is shown it has an extra width of 16px so the total would be 32 pixel  without it would be 16px by default .  would that change resolve that issue

**Comment by yuval-hazaz** [comment]
@jaysoni-ash42 thanks for your help
The padding was looking fine in previous versions, so I would investigate what was changed recently and why and consider reverting the change

**Comment by GreenMachine01** [comment]
@mulygottlieb please decide who can take it.
@jaysoni-ash42 you want to take it?

**Comment by jaysoni-ash42** [comment]
@GreenMachine01  currently working on a different issue. plz assign it to somebody else thanks.

**Comment by mulygottlieb** [comment]
@GreenMachine01 let's open it for the community and wait for a community member that wants to take it. @souravjain540 FYI.

**Comment by abrl91** [comment]
passed QA ✅ 

https://github.com/amplication/amplication/assets/39680385/416257d2-f86c-47a6-aea3-cd1c369e29d9
