### ISSUE TITLE
🐛 Bug Report: UI/UX - Inconsistent Visual Values Across Popup Components

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#6030]
### What happened?

**Issue Summary:**
Popup boxes in the app, including alerts, selections, and others, must be more consistent in their alignment and design elements, such as padding and font size. These inconsistencies negatively impact the application's overall visual coherence and user experience.

**Issue Details:**
Users observe misalignment and design inconsistencies when encountering popup boxes within the app, such as alerts, selection repo, and similar elements. These inconsistencies manifest in various ways, including inadequate padding and variations in font size, among others. As a result, the visual harmony and user-friendliness of the app are compromised.

### What you expected to happen

To address this issue, it is crucial to establish and implement consistent visual values across all popups using our design system.

### How to reproduce

If you have a long list of repos, this bug will be visible.

### Amplication version

1.6.0

**Comment by EugeneTseitlin** [comment]
I think it's already mentioned in #5882
