### ISSUE TITLE
🐛 Bug Report: UI/UX - Long List Item in Left Side Menu Breaking Display

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#6031]
### What happened?

**Issue Summary:**
The left side menu in the app is experiencing display issues when a list item within it becomes too long. This results in a broken or disrupted display, impacting the visibility and usability of the menu.

**Issue Details:**
The display is disrupted and broken when the left side menu contains a list item with excessive length. This issue occurs when the list item's content exceeds the available space, causing it to overflow or wrap incorrectly within the menu. As a result, users may need help in reading and accessing the full content of the list item.

![image](https://github.com/amplication/amplication/assets/96179897/668b3c61-c512-43db-a1f1-1682e44eb4a4)

### What you expected to happen

We must ensure a proper working scroll even if the list becomes long while keeping the title sticky. Also, we must ensure that with each field added, even if the list is long, the focus is always on the add field.

### How to reproduce

By going into the entity section and clicking on an entity, and start adding fields.

### Amplication version

1.6.0

**Comment by morhag90** [comment]
@EugeneTseitlin @alexbass86 

1. The add field must be last in the list but not sticky to the button. 
2. When you add a new field, make sure that the focus is always on the last field added.

**Comment by EugeneTseitlin** [comment]
> @EugeneTseitlin @alexbass86
> 
> 1. The add field must be last in the list but not sticky to the button.
Which button? I can't see any in the list.
![image](https://github.com/amplication/amplication/assets/6080188/41880e72-90a2-4fbc-8edb-6b7c012c0db4)

> 2. When you add a new field, make sure that the focus is always on the last field added.
That's exactly how it works now in sandbox. Am I missing something?
https://jam.dev/c/a129e879-7e0c-48b0-854e-ce9c0f8bcab0

**Comment by alexbass86** [comment]
> > @EugeneTseitlin @alexbass86
> > 
> > 1. The add field must be last in the list but not sticky to the button.
> 
> Which button? I can't see any in the list. ![image](https://user-images.githubusercontent.com/6080188/239940086-41880e72-90a2-4fbc-8edb-6b7c012c0db4.png)
> 
> > 2. When you add a new field, make sure that the focus is always on the last field added.
> 
> That's exactly how it works now in sandbox. Am I missing something? https://jam.dev/c/a129e879-7e0c-48b0-854e-ce9c0f8bcab0

In the scenario where you have a lengthy field list, we have a couple of issues to address:

1. The title should not be scrollable. It should remain fixed in its position.
2. Whenever a new field is added, the focus should automatically shift to the final field, "add field." In case the list is extensive, the page should scroll down to the last item to ensure visibility.

**Comment by abrl91** [comment]
passed QA ✅ 


https://github.com/amplication/amplication/assets/39680385/4719749f-083c-40b9-9724-ca80130cb518
