### ISSUE TITLE
🐛 Bug Report: UI/UX - Broken Dropdown Appearance Misaligned with Figma Design

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#6034]
### What happened?

**Issue Details:**
The main dropdown component in the app does not match the original design as outlined in Figma. This discrepancy results in a broken appearance, where the dropdown's visual elements, such as layout, styling, or behavior, must align with the expected design specifications. Consequently, users may need help interacting with the dropdown and experience inconsistencies with the app's overall look and feel.

![image](https://github.com/amplication/amplication/assets/96179897/6cddb17a-b598-48de-a7c6-d64cda9027d6)

### What you expected to happen

By implementing these recommendations, the app can address the broken appearance of the main dropdown and restore its alignment with the original Figma design. This will enhance the visual consistency, functionality, and overall user experience, increasing user satisfaction and confidence in the app.

### How to reproduce

Just click on the middle dropdown menu.

![image](https://github.com/amplication/amplication/assets/96179897/3a9bc380-2b6f-47a4-a3ae-2aa37d6aab8f)

### Amplication version

1.6.0

**Comment by EugeneTseitlin** [comment]
This issue can be solved as part of #5882

**Comment by Akshaybagai52** [comment]
Hey @GreenMachine0 @EugeneTseitlin  if this issue is open can you assign to me 
Thanks

**Comment by GreenMachine01** [comment]
@alexbass86 can I close this item?

**Comment by alexbass86** [comment]
> @alexbass86 can I close this item?

yes please

**Comment by GreenMachine01** [comment]
no longer relevant.
