### ISSUE TITLE
🐛 Bug Report: UI/UX - Malfunctioning UI when no projects are listed

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#6047]
### What happened?

Currently, when no projects are listed, the UI malfunctions and exhibits unexpected behavior. This may include misaligned elements, overlapping content, or unresponsive buttons.

This issue is critical as it hinders the proper functioning of the application when no projects are available.

![image](https://github.com/amplication/amplication/assets/96179897/0577dd1d-7b99-4c3e-b345-d88702fdb0a4)

### What you expected to happen

When no projects are listed, the UI should gracefully handle this situation without causing any malfunctions. It should display a message or a placeholder indicating the absence of projects, ensuring the rest of the UI remains functional.

### How to reproduce

Delete all projects in the list.

### Amplication version

1.6.0

**Comment by roopeshsn** [comment]
Hi! I would like to work on this!

**Comment by souravjain540** [comment]
@roopeshsn  assigned. (be sure about this one :P ) let me know if you need any help

**Comment by roopeshsn** [comment]
> @roopeshsn assigned. (be sure about this one :P ) let me know if you need any help

Sure :)

**Comment by souravjain540** [comment]
@roopeshsn any updates?

**Comment by souravjain540** [comment]
@roopeshsn please reply otherwise I will go ahead and assign it to someone else

**Comment by roopeshsn** [comment]
Hi @alexbass86 @souravjain540! Here are the 4 issues I found in the UI,

1. The right sidebar is visible after a project is deleted, which is not intended.

https://github.com/amplication/amplication/assets/70762571/64d7478b-af75-44ae-9b2f-16c27eaa9300

2. The top breadcrumb component is also visible after a project is deleted, which is also not intended.

![top-breadcrumb-issue](https://github.com/amplication/amplication/assets/70762571/5210fe32-3184-4eaf-add1-168ebd9177da)

3. The "Create new workspace" button is overflowing when no projects are listed.

![overflowing-issue-button](https://github.com/amplication/amplication/assets/70762571/05973dc9-4532-4422-bbaf-767ea9fcabfe)

4. The buttons "Workspace Settings" and "Workspace Members" are not responsive.

Let me know if I miss out on any @alexbass86. I'll fix those issues ASAP @souravjain540 and I'll reach out to both of you if I need support.

**Comment by roopeshsn** [comment]
Hi! When a project is deleted then the `currentProject`variable defined in the `WorkspaceLayout` component (https://github.com/amplication/amplication/blob/b10f2d21ff6deef833a159563dbd06c7c5922e45/packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx#L55) should become undefined right? But, it is not. The variable become undefined when refreshing a page. This is not a desired behavior. Also, this is the reason for the visibility of breadcrumb and sidebar components even after the deletion. Could some one help with this?

**Comment by imSmaity** [comment]
@souravjain540 please assign this to me

**Comment by astitva0011** [comment]
i would like to work on this
assign me

**Comment by ptdatta** [comment]
@alexbass86  Can I work on it?

**Comment by GreenMachine01** [comment]
@ptdatta this item is currently on hold as we are working on a new UI for the platform.

**Comment by ptdatta** [comment]
@GreenMachine01 is your new UI has open issues I would love to contribute their.

**Comment by GreenMachine01** [comment]
@ptdatta they will be ready very soon for contributions.

**Comment by Sukhendu2002** [comment]
Hey @GreenMachine01, Can I work on this issue?

**Comment by GreenMachine01** [comment]
@Sukhendu2002 this item is currently on hold as we are working on a new UI for the platform.

**Comment by Sukhendu2002** [comment]
Ok

**Comment by souravjain540** [comment]
@GreenMachine01 please close this if not needed/

**Comment by yuval-hazaz** [comment]
not relevant after the recent chagnes in the UI
