### ISSUE TITLE
As Designer - I want to improve long project name impact on the UI

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#6048]
### What happened?

In our application, the user interface (UI) fails to handle long project names, causing the layout to break and negatively impacting the user experience. 

![image](https://github.com/amplication/amplication/assets/96179897/d4be9304-5a75-4018-9b31-95cc5e24bfee)

![image](https://github.com/amplication/amplication/assets/96179897/20283769-c8e5-4c23-9521-692c4f51b724)

![image](https://github.com/amplication/amplication/assets/96179897/bb8a70bd-233d-49b8-8672-a7aa3e1d9fa6)

**Requirements:**

1. Restrict the project name to a maximum of 60 characters. If the name exceeds this limit, show an appropriate error message to the user
2. Notice the name for a project is set when creating a new project but can also be changed within the project settings - need to handle both.

**Error Text** - "Name exceeds 60 characters. Please shorten it."

![image](https://github.com/amplication/amplication/assets/112330500/feaad16e-ed3f-40b0-9986-8081849793ee)

**Comment by jaysoni-ash42** [comment]
@alexbass86  i want to work on this issue? can you assign it to me ?

**Comment by GreenMachine01** [comment]
@alexbass86 Let's define the max length we want to accept. (and that also looks good in the design).
There is no need to invest in supporting something no real user will face.

so solving this bug will be just restricting the length the user can set for a project.

**Comment by jaysoni-ash42** [comment]
@GreenMachine01  i pulled up this pr  https://github.com/GitStartHQ/client-amplication/pull/59 for this issue as i can see the specifications have been changed just q question the change on validation should only be on form validation or the backend as well?

**Comment by GreenMachine01** [comment]
@jaysoni-ash42 I think client validation should be enough. 
@overbit agree?

**Comment by MutiatBash** [comment]
Hello…..is this issue still open to work on

**Comment by GreenMachine01** [comment]
@MutiatBash I see there is already an open PR for this item. I will notify you if we need assistance with it.

**Comment by auspy** [comment]
Is someone currently working on this? If not, I would be very happy to fix this bug. Pls assign the issue to me if possible. thx

**Comment by souravjain540** [comment]
@GreenMachine01 is this issue still relevant, if yes, can you assign it to @MutiatBash?

**Comment by GreenMachine01** [comment]
@MutiatBash assigned. good luck!
@souravjain540 FYI

**Comment by mulygottlieb** [comment]
Hi @MutiatBash ,
Is there any progress on this?

**Comment by Gingaaa** [comment]
Hey I have worked on around 7-8 company based project, but never countribute to open source this is my first time can you assign me this task.

**Comment by GreenMachine01** [comment]
@Gingaaa assigned to you. good luck!
@souravjain540 FYI

**Comment by Gingaaa** [comment]
Thanks.

**Comment by Gingaaa** [comment]
I will ping you with update code

**Comment by souravjain540** [comment]
@Gingaaa  lmk if you need any help

**Comment by souravjain540** [comment]
@GreenMachine01 this issue is already solved, if i am not wrong?

**Comment by yuval-hazaz** [comment]
not relevant after recent changes in the UI
