### ISSUE TITLE
🐛 Bug Report: page views are recorded twice in the app

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6050]
Relates to - https://github.com/amplication/amplication/issues/7261

![Image](https://github.com/amplication/amplication/assets/112330500/f5b8023b-1109-448f-ad98-6efa3ce7aeea)

There is a technical issue causing the page view event to be triggered twice. we need to investigate and fix these duplicate events.

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/user-attachments/assets/131de21f-c1e8-452c-8036-874e2ffeb9a4)
