### ISSUE TITLE
🐛 Bug Report: When creating a repo via amplication with space the code will not sync as in github it will be replaced with a dash

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6051]
**Expected:**
Enforce validation rules on repos created via Amplication so there won't be an issue with code sync

**Actual:**
User can create a repo name with "SPACE" and this will cause a problem with the code sync since GitHub will save the repo with a different name (without the SPACE)

**Comment by Liqingcathy** [comment]
Hi! I don't see a suitable good-first-issue or docs issue to pick up as a first-time contributor in Amplification. Can I work on this one?

**Comment by GreenMachine01** [comment]
@souravjain540 Please assist.

**Comment by souravjain540** [comment]
@Liqingcathy  this issue is for internal work, do you want to work on #6568 ?

**Comment by Liqingcathy** [comment]
@souravjain540 Sure! I would like to work on https://github.com/amplication/amplication/issues/6568.

**Comment by mulygottlieb** [comment]
Passed QA:

![Image](https://github.com/amplication/amplication/assets/1912933/3669920f-04f0-497f-81da-43a81a67d0df)


![Image](https://github.com/amplication/amplication/assets/1912933/6327a8e9-6af0-49ed-b484-236313809dd3)


![Image](https://github.com/amplication/amplication/assets/1912933/a79a6762-26e6-4701-98f9-fcc51ca1c167)
