### ISSUE TITLE
🐛 Bug Report: Smart git strategy - push changes to GitHub fails although it actually do create a commit or open a new pull request

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6062]
### What happened?

Push changes to GitHub step looks like it failed, although it did commit or create a pull request.
After creating a new pull request or adding a new commit to an existing pull request, at the beginning, it looks like everything is OK, but when we come back to Amplication, it seems like the pull request actually failed and we keep seeing logging on the build page.

On each build, we can see a different error:

![image](https://github.com/amplication/amplication/assets/39680385/3fa52362-f94b-4442-8dd5-7265967b3d21)

![image](https://github.com/amplication/amplication/assets/39680385/328ad017-09fe-4851-b097-9abdb1c917d9)

And sometimes it still looks like everything is OK but there are storage logs:

![image](https://github.com/amplication/amplication/assets/39680385/b0fc56b8-a173-444f-afa3-687a75161028)

In both cases (when it seems like it failed and when everything is looking OK), we keep getting a lot of comments without any commits to the open PR

### What you expected to happen

When push to GitHub fails, show in the UI that it failed, and not "success" and then "fail", while actually the user not only got the new Pull Request of commits,  but also keep getting comments from amplication to this PR

### How to reproduce

Create a service and, connect it to GitHub (using the smart git-sync), push changes, it happens quite often, but there is still a chance that you are lucky and it won't happen to you 🙃

### Amplication version

1.6.0

**Comment by overbit** [comment]
Possible causes to investigate:
- KafkaRetriableException
- Wrong Kafka consumer group configuration for `pull-request-service`
- `pull-request-service` eviction that would cause a new instance to pick up the event
   - eviction due to cpu / mem over limit
   - eviction due to ephemeral-storage  over limits

**Comment by overbit** [comment]
Still experiencing issues related to consumer group rebalancing
