### ISSUE TITLE
As User - I want clicking "View my code" during Onboarding to also move me to the next step of the wizard

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6094]
**Overview:**
This story involves updating the onboarding wizard to automatically transition the user to the next step after they've completed reviewing their code on GitHub. By leveraging browser tab focus events, we can detect when the user has returned to the application and guide them to the next step automatically.

**Requirements:**
1. Implement logic to detect when the application tab regains focus.
2. Develop a mechanism to automatically navigate the user to the next step of the onboarding wizard when the tab focus event is detected.

**Acceptance Criteria:**
1. When a user clicks to view their code on GitHub, they are instructed to return to the application tab after reviewing the code.
2. After the user has switched back to the application tab from GitHub, the application detects this tab focus event.
3. Upon detecting the tab focus event, the application automatically transitions the user to the next step in the onboarding wizard.
4. The entire process does not cause any disruptions or unexpected behavior in the user interface.

**Comment by pratik-codes** [comment]
Hey I would like to work on this can this be assigned to me?

**Comment by yuval-hazaz** [comment]
no relevant - closing
