### ISSUE TITLE
🐛 Bug Report: Commits page - "Load more..." button shouldn't appear if there are fewer than 21 commits

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6098]
### What happened?

The "Load more..." button shouldn't appear if there are fewer than 21 commits.

<img width="326" alt="image" src="https://github.com/amplication/amplication/assets/39680385/7b84f64b-660d-4d74-bb9c-c8655d9f89da">

### What you expected to happen

The max number of commits per page is 20, so the button should only be visible if there are more than 20 commits.

### How to reproduce

open the commits page of a service and view the commit list

### Amplication version

next

**Comment by abrl91** [comment]
@GreenMachine01 @alexbass86

**Comment by GreenMachine01** [comment]
@barshimi please fix this as part of the "load more" solution.

**Comment by officialkanav** [comment]
Can I fix this issue? I am new to open source.

**Comment by mulygottlieb** [comment]
Hi @officialkanav 
We are happy for your enthusiasm to contribute to open source, this is great!
This specific issue has a bit more complex underlying reason and would not be very easy to solve. I suggest you join our discord server if you're not already there, and take one of the issues we publish regularly for newcomers, under the channel "twenty-issues-for-first-timers".
Good luck!

**Comment by mulygottlieb** [comment]
@morhag90 @barshimi , since all new users will have less than 20 commits , this is potentially a bad initial experience. Not critical but if we do have a way to disable/hide the button if the initial commits that return are less than 20, that would be great. Having said that, it's not worth more than 2-3 hours of work so if the solution is more complex than that, let us know and we will de-prioritize.
FYI @GreenMachine01

**Comment by GreenMachine01** [comment]
@morhag90 @barshimi @mulygottlieb 
Clarification - its better to not show the button until you know you need to show it.

if we are not going to improve when its shown/hidden we should improve the design to make this button less noticeable.
@alexbass86 FYI

**Comment by morhag90** [comment]
Passed QA: 


https://github.com/amplication/amplication/assets/97830649/1d3bcb72-d986-46c9-b61d-9a4c7cf55d30

**Comment by GreenMachine01** [comment]
@morhag90 @mulygottlieb this doesnt look good.
![image](https://github.com/amplication/amplication/assets/112330500/d1913f16-4cc5-44d2-961f-722b569993a4)

@alexbass86 please suggest how it should look like in this case.

**Comment by alexbass86** [comment]
@GreenMachine01 @morhag90 
please use this button style
https://www.figma.com/file/osARayPfp0aRiETAc93x66/%23none---Commit-page-V3?type=design&node-id=2041%3A14924&t=4Fd9zCwNaEuG8hAX-1

![load disabled](https://github.com/amplication/amplication/assets/96179897/51b3e7d1-16d1-476f-84ed-33f616723b6d)

![load active](https://github.com/amplication/amplication/assets/96179897/318b497f-1be0-484a-b7bb-58f39c606b80)
