### ISSUE TITLE
🐛 Bug Report: Commit page shows in progress state regardless the build result

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6099]
### What happened?

https://jam.dev/c/f5df8232-1469-4234-9fc9-fe11316459d6

### What you expected to happen

The commit status to reflect the build status

### How to reproduce

In sandbox run a multi resource build that is connected with a GitProvider

### Amplication version

v1.6.5

**Comment by vasu-1** [comment]
I want to work on this issue!
Can you please assign this issue to me? @souravjain540

**Comment by souravjain540** [comment]
@vasu-1 assigned. Let me know if you need any help.

**Comment by souravjain540** [comment]
@vasu-1 is there any updates?

**Comment by vasu-1** [comment]
> @vasu-1 is there any updates?

Yep!! I'm working on the same!

**Comment by souravjain540** [comment]
@vasu-1 when can I expect a PR?

**Comment by vasu-1** [comment]
Hey @souravjain540 !
I'm trying to generate the same error but it's showing in building state only, it's running more than 10 mins!
Below is the screenshot.
It's just a sample service with mongoDB.

![image](https://github.com/amplication/amplication/assets/76911582/b5c6d68e-bfda-4971-bc45-693f8bfebce0)

**Comment by vasu-1** [comment]
Building is not happening, can you please help me this? I identified the issue but not able to test it!

**Comment by souravjain540** [comment]
@vasu-1 can you please open a support ticket in discord?

**Comment by vasu-1** [comment]
> I'm trying to generate the same error but it's showing in building state only, it's running more than 10 mins!
> Below is the screenshot.
> It's just a sample service with mongoDB.

Yes! Just Asked!

Meanwhile there is another issue on which i can work on. Which is #4424 .
