### ISSUE TITLE
As User - I want to be offered better options after creating a service

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6104]
**Overview:**
Today after completing the service creation we offer the user with 3 options
1. "Create entities  for my service"
2. "Create  another service"
3. "I’m done!  View my service"

from examining our BI events it is very clear that users rarely choose to create another service (and it makes sense why)
We will use this opportunity to provide a better option to users instead of the create another service

**Requirements:**
1. For the onboarding wizard replace the "Create  another service" option with "Invite my team". clicking this option should open the team management page
2. Update the client-side event (ServiceWizardStep_Finish_CTAClicked) so the action for the above will be "Invite Team"
3. For the regular wizard replace the "Create  another service" option with "Add plugins to my service". clicking this option should open the Plugins tab within the created service
4. Update the client-side event (ServiceWizardStep_Finish_CTAClicked) so the action for the above will be "Add Plugins"

**Design** - https://www.figma.com/file/fGHkvGfTxVm9P0RsVXYk9b/%23none---New-user-Onboarding-Flow-v2?type=design&node-id=2041%3A14924&t=WuTEcR1oNSTRJUMs-1
![image](https://github.com/amplication/amplication/assets/112330500/8b2d2435-96d6-4c82-aa84-f3e416136dfe)
![image](https://github.com/amplication/amplication/assets/112330500/74148029-b064-47df-bcd2-1f363d5c83de)

**Comment by jaysoni-ash42** [comment]
@GreenMachine01  i want to work on this issue? can i get the access for the new design ?

**Comment by GreenMachine01** [comment]
@alexbass86 please provide link to the assets

**Comment by GreenMachine01** [comment]
@mulygottlieb I am assigning the client work to @jaysoni-ash42 but not sure who should do the BI events part.
@jaysoni-ash42 - assigned to you good luck
