### ISSUE TITLE
🐛 Bug Report: `Config` should be a reserved word 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6111]
### What happened?

When using the name `Config` for an entity the following error is thrown in the build process

```
Failed to execute plugin event CreateServerAppModule. Identifier 'ConfigModule' has already been declared. 
```

See this thread on Discord https://discord.com/channels/757179260417867879/1110874240133103706

### What you expected to happen

this list should be updated

https://github.com/amplication/amplication/blob/master/packages/amplication-server/src/core/entity/reservedNames.ts

### How to reproduce

create an entity with the name `Config`

### Amplication version

1.6.5

**Comment by Jyotiraditya24** [comment]
has this issue been already solved ?

**Comment by yuval-hazaz** [comment]
yes, thanks @Jyotiraditya24

**Comment by abrl91** [comment]
passed QA ✅ 


![Image](https://github.com/amplication/amplication/assets/39680385/addd042b-24e0-479f-b56d-ee90f82e78db)
