### ISSUE TITLE
🐛 Bug Report: Commits page not showing the correct commits

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6115]
### What happened?

Navigating from one project to another, the commits page is showing the wrong commits.
It is showing the correct ones only after an hard reload.

https://jam.dev/c/70a886c2-7dc6-4386-9315-a99944f57733

### What you expected to happen

The commits of the selected project to be displayed

### How to reproduce

Follow the video 😃 

### Amplication version

v1.6.5

**Comment by rielAsh24** [comment]
Hey! I would be glad to look into this issue if assigned.
