### ISSUE TITLE
🐛 Bug Report: `amplication-server` logs PR failures with wrong level

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6118]
### What happened?

When a PR process fails, `amplication-server` logs the error as `info` level in the ActionLog

### What you expected to happen

 `amplication-server` logs the error as `info` level in the ActionLog

### How to reproduce

Check DB for any error and see the level. 
To reproduce it, create a message in the `git.internal.create-pr.failure.1` topic with all required fields plus `errorMessage`  

### Amplication version

v1.6.5

### Tech notes

Leverage the `action.service.ts` `  async log(step: ActionStep, level: EnumActionLogLevel, message: { toString(): string }, meta: JsonValue = {}): Promise<void>` to log the message with the correct level

**Comment by kabhamo** [comment]
@overbit  can you specify what is expected to happen?
 It seems like you want to log the error in a different level than ActionLog level.

**Comment by ankur0904** [comment]
@souravjain540 Can I work on this issue?

**Comment by souravjain540** [comment]
@ankur0904  this campaign is for only new contributors :)

Please take some other issue.

**Comment by ankur0904** [comment]
OK :)

**Comment by manulpatel** [comment]
Hello @souravjain540! Is someone currently working on this? If not, I would be very happy to fix this bug and make myself familiar with the Amplication codebase on the go.

**Comment by souravjain540** [comment]
@manulpatel assigned :)

**Comment by manulpatel** [comment]
Hello @overbit! I am not getting how should I use the `log()` function from `ataction.service.ts` inside https://github.com/amplication/amplication/blob/45a6a45eb0181c74fa35ecf68ea6b702416b6929/libs/util/logging/src/lib/logging.ts#L16

A little hint would be very helpful.

**Comment by overbit** [comment]
Hi @manulpatel, it seems that the method in question is not part of the `@amplication/util/logging`.
In this scenario, as mention in the Tech notes in the description of this issues, you will need to leverage the inner functions of the `action.service.ts`.
Try to follow the code from here https://github.com/amplication/amplication/blob/master/packages/amplication-server/src/core/action/action.service.ts#LL199C15-L199C16; it will lead you to https://github.com/amplication/amplication/blob/master/packages/amplication-server/src/core/action/action.service.ts#L120 where it would be pretty simple to understand how to use it.

**Comment by souravjain540** [comment]
@manulpatel when can I expect a PR?

**Comment by manulpatel** [comment]
Sorry for the delay. Was figuring out the way to test the changes. I will try to wrap up by today.
