### ISSUE TITLE
🐛 Bug Report: Git Smart sync not commiting renamed or deleted files

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6119]
### What happened?

Removing an entity or changing a service base directory cause git to delete / rename all the service generated files.
But `pull-request-service` doesn't commit the renamed or deleted files and log:
```
warn 2023-05-26T08:41:20.774Z Trying to commit empty changeset
``` 

### What you expected to happen

Renamed files to be pushed as usual

### How to reproduce

With PRO plan:
1. Create  a service and connect a bit provider.
2. Build the service
3. Change the base directory of the service
4. Build the service again
5. Observe the PR

### Amplication version

v1.6.5

**Comment by overbit** [comment]
@mulygottlieb I've the feeling that this issue was introduced by this https://github.com/amplication/amplication/pull/6043

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/50481a2e-f80f-4022-85e5-d1edb1cb4223)
