### ISSUE TITLE
🐛 Bug Report: services with entities with JSON field cannot run successfully on monorepo

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6121]
### What happened?

<img width="833" alt="image" src="https://github.com/amplication/amplication/assets/2861984/90bf4bca-a213-4cc0-b529-65c95546d855">

### What you expected to happen

Creating a service with an entity with a JSON field will produce a code that depends on `type-fest`.
Since this dependency should only be a `devDependency` it will cause the application to not start successfully.

 

### How to reproduce

Create a service with an entity with a JSON field

### Amplication version

v.1.6.5

**Comment by Rahulcheerio** [comment]
Hii @overbit , want to contribute to this bug , can you please explain more how to create the service .

**Comment by overbit** [comment]
@Rahulcheerio sorry for the late reply. This issue needed more internal discussions and we decided to not open it to the community.
Please have a look to any issue tagged as `open to community` https://github.com/amplication/amplication/labels/open%20to%20community
