### ISSUE TITLE
🐛 Bug Report: Creating a service without Git repo throws an error

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6124]
When you try to create a service without selecting a repo you get an error at the last screen

![Image](https://github.com/amplication/amplication/assets/112330500/f3e444f0-9e60-4b42-a0eb-0a22fa298c19)

**Expected:**
We know to generate a service without it being connected to a repo

**Comment by morhag90** [comment]
Passed QA:

https://github.com/amplication/amplication/assets/97830649/864407ad-098b-42ef-9d3b-63ce7336a6c4
