### ISSUE TITLE
🐛 Bug Report: Commits page doesn't show previous commits if you go there from the "rebuild" button inside a specific service

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6127]
### What happened?

If you press the "rebuild" button from *within a specific service* rather than from the workspace, you only see a single commit (the current rebuild) and do not see the history of all commits

![image](https://github.com/amplication/amplication/assets/1912933/13378bfe-8c61-445e-b2ce-75d0b9f3c483)

![image](https://github.com/amplication/amplication/assets/1912933/b62ab1c7-7bae-4c52-a3f4-c5fa635285be)

### What you expected to happen

Last 20 commits should appear in every path of navigation to the commits page

### How to reproduce

go inside a specific service in the workspace, press the "rebuild" button there

### Amplication version

1.6.5

**Comment by morhag90** [comment]
Passed QA: 


Uploading Screen Recording 2023-05-30 at 11.35.31.mov…
