### ISSUE TITLE
🐛 Bug Report: Commits page showing duplicate commits

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6129]
### What happened?

If you rebuild a service and during rebuild you press "load more", and then navigate away from the commits page and back into the commits page - you will see the same commit duplicated in the list (it can appear more than 2 times in the commit list)

![image](https://github.com/amplication/amplication/assets/1912933/a37ffb49-34cd-462b-98c2-bc2fcafc0bef)

![image](https://github.com/amplication/amplication/assets/1912933/c0a0acd6-fb2e-437b-bdef-5f8093e4372f)

### What you expected to happen

each commit should only appear once in the list

### How to reproduce

press rebuild on a service
while rebuilding press "load more"
navigate into the build itself (pressing the link of the build ID)
navigate back to the commits page
observe the duplication of the same build in the lost

### Amplication version

1.6.5

**Comment by morhag90** [comment]
Passed QA: 


https://github.com/amplication/amplication/assets/97830649/4d836d0b-adb6-43ce-8836-814945b82fd6
