### ISSUE TITLE
As User - I want any plugin that I install to be set to always update to the latest version on my next commit

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6136]
**Overview:**
Currently, when a user installs a plugin on a service the plugin is set with a fixed plugin version. so if a new version of the plugin is released the user will need to manually select to upgrade the version of the plugin and build.
We currently allow users to set a plugin to always update to the latest version. We want installed plugins to be set for automatic version upgrades by default. The user will have the option to set the version to a fixed version manually.

![Image](https://github.com/amplication/amplication/assets/112330500/d81b7f88-f53b-46fb-a2f7-b69d8c8cba37)

**Requirements:**
1. When a plugin is installed by the user manually or by the Service Wizard the version is set to the "Latest" option

**Comment by overbit** [comment]
Linked to #5556
