### ISSUE TITLE
As Designer -  I want to improve the design of the "load more" button

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6145]
please use this button style
https://www.figma.com/file/osARayPfp0aRiETAc93x66/%23none---Commit-page-V3?type=design&node-id=2041%3A14924&t=4Fd9zCwNaEuG8hAX-1

![load active](https://github.com/amplication/amplication/assets/96179897/ae108003-2436-40c0-b1e4-281b85ef41d5)

![load disabled](https://github.com/amplication/amplication/assets/96179897/0155855e-819a-4f1c-be07-b7808df237bf)

_Originally posted by @alexbass86 in https://github.com/amplication/amplication/issues/6098#issuecomment-1568108911_

**Comment by mulygottlieb** [comment]
@morhag90 please provide an effort estimation for @GreenMachine01

**Comment by riju951** [comment]
Can you assign this issue to me ?

**Comment by souravjain540** [comment]
@riju951  assigned. let me know if you need any help :)

**Comment by vilsi12** [comment]
Hey I can work on it

**Comment by souravjain540** [comment]
@vilsi12 take some other issue :)

**Comment by riju951** [comment]
Sure, Thanks

**Comment by riju951** [comment]
> @riju951 assigned. let me know if you need any help :)

Sure, Thanks

**Comment by riju951** [comment]
> @riju951 assigned. let me know if you need any help :)

@Can i get access to Figma File ?

**Comment by alexbass86** [comment]
Here you go 
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?type=design&node-id=1946%3A23678&t=ArdRiMYNXtAnKe2n-1
thanks for the contribution ;)

**Comment by souravjain540** [comment]
@riju951 any updates?

**Comment by riju951** [comment]
Will Update you by end of the day

**Comment by riju951** [comment]
I have started working on it

**Comment by riju951** [comment]
@souravjain540 I have worked on the Button, The link is uneditable so i have make a copy of that file : https://www.figma.com/file/DWmFJ4dPVo9AzQZfR8Mbks/Diagram---Community---Task-Assets?type=whiteboard&node-id=1946-23678&t=a5C4sJ8rObM3tMW4-0
let me know your views

**Comment by riju951** [comment]
> @souravjain540 I have worked on the Button, The link is uneditable so i have make a copy of that file : https://www.figma.com/file/DWmFJ4dPVo9AzQZfR8Mbks/Diagram---Community---Task-Assets?type=whiteboard&node-id=1946-23678&t=a5C4sJ8rObM3tMW4-0 let me know your views

@souravjain540 what can i do next ?

**Comment by souravjain540** [comment]
@riju951 why you want to edit the file?

**Comment by riju951** [comment]
> @riju951 why you want to edit the file?

Actually i didn't got any confirmation so thought of asking

**Comment by souravjain540** [comment]
> > @riju951 why you want to edit the file?
> 
> 
> 
> Actually i didn't got any confirmation so thought of asking

You have to implement the design in code

**Comment by riju951** [comment]
> > > @riju951 why you want to edit the file?
> > 
> > 
> > Actually i didn't got any confirmation so thought of asking
> 
> You have to implement the design in code

Okay, will do it

**Comment by souravjain540** [comment]
@riju951 any updates?

**Comment by iamrakhmatov** [comment]
Hey @souravjain540, I would love to work on the issue if there is no progress, pls let me know :)

**Comment by riju951** [comment]
> @riju951 any updates?

I have Generated the code

**Comment by riju951** [comment]
``

> > @riju951 any updates?
> 
> I have Generated the code

https://github.com/riju951/Amplification-Code_Temp
You can Find the code here and Can you help me i am unable to find the repo in the Amplification where to make PR.

**Comment by Tsubame2** [comment]
Can I be assigned this issue? Would like to contribute

**Comment by GreenMachine01** [comment]
@Tsubame2 assigned to you. good luck!
@souravjain540 FYI

**Comment by AtharvSabde** [comment]
can you assign me this issue

**Comment by GreenMachine01** [comment]
@AtharvSabde We are planning a completely new UI for the platform so I am keeping this item on the side as it might not be needed with the new UI.

**Comment by souravjain540** [comment]
@GreenMachine01 please close this issue if not needed.

**Comment by yuval-hazaz** [comment]
not relevant after recent changes in the UI
