### ISSUE TITLE
Client: Drill down from an existing commit to see the list of changes

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#615]
Currently, on the publish page, in the list of pending commits, the user cannot drill down into a commit to see the list of changes made in the commit.

The user should be able to click on a commit to see the list of changes made in the commit with the option to compare each change and see the diff.

**Comment by iddan** [comment]
@yuval-hazaz can this be closed?

**Comment by yuval-hazaz** [comment]
Yes, it was already implemented as part of the new commit flow
