### ISSUE TITLE
🐛 Bug Report: Fix the typo in `npm run` commands in the documentation, for running project components

### ISSUE THREAD

**Issue by ognjenjevremovic** [amplication/amplication#6161]
### What happened?

Documentation provided in the `README.md` file, with instructions on how to run different components locally (in `Development` section, under `Scripts`) have typo on all of the `npm` commands. 
Copying the `npm run` commands supplied in the documentation _(blindly)_ will fail due to the typo in the commands name.

i.e.:
For running the server component, instructions provided in the `README.md` states to run the following command:
 ```sh
npm run server:server
```

Which results in:
```sh
npm ERR! Missing script: "server:server"
```

### What you expected to happen

All of the listed `npm run` commands, for starting different amplication components, should be updated in order to supply copy-ready commands for newcomers to the project.

### How to reproduce

n/a

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by levivannoort** [comment]
Thanks for the contribution! this was probably introduced with the refactor of the main readme, so nice catch!
