### ISSUE TITLE
🐛 Bug Report: missing `dotenv` dependency in the server's `package.json`

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#6175]
### What happened?

In the `seed.ts` file in the generated server, we call the `dotenv` package
https://github.com/amplication/amplication/blob/2c8dba3d55bf27cd88dfc34c1a82a2670c447cfc/packages/data-service-generator/src/server/seed/seed.template.ts#L7 
But the package itself is not in the `pacakge.json` of the server

### What you expected to happen

Every package that is used supposes to be in the `package.json` file

### How to reproduce

generate a service

### Environment

pnpm 8.6.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@GreenMachine01 can we block @tupe12334 ??

@tupe12334 you are on a trip in South America, go enjoy the view instead of looking at code!
