### ISSUE TITLE
🐛 Bug Report: broken link

### ISSUE THREAD

**Issue by sumitbhanushali** [amplication/amplication#6193]
### Description (What is it?)

https://docs.amplication.com/running-amplication-platform/connect-server-to-github/

clicking next on this page redirects to same page

![Screenshot 2023-06-09 091824](https://github.com/amplication/amplication/assets/9103781/59a95259-25b0-4a34-ad7a-f5de3109b89b)

### Use Case (Why does the user need it?)

clicking next should direct to next page in the list. In this case `Connect Amplication server to Bitbucket`

### Issue URL

https://docs.amplication.com/running-amplication-platform/connect-server-to-github/

### How it works (How does the user use it?)

going through tutorial on how to setup amplication locally

### Screenshots

![Screenshot 2023-06-09 091824](https://github.com/amplication/amplication/assets/9103781/bcf5a219-6228-4a66-aec7-a0223fa0d620)

### Code Samples

N/A

### Figma URL

N/A

**Comment by dericksozo** [comment]
Hey @sumitbhanushali, thank you for reporting for this one! It's now fixed. Please do let us know if you encounter anything else in our docs. 😊
