### ISSUE TITLE
As a User - I'd like to select a git branch different from the default as the pull request base branch 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6195]
### Feature description

Amplication smart git sync creates a new PR for `amplication` to `default` branch. 
There are scenarios when a user wants to use a development branch instead of the default repository branch for various reasons. If that is the case, the user should be able to target the development branch instead of the default.

This feature will allow users to not need to deal with possible conflicts / problems. 

Use a new entitlement for this feature via Stigg 'feature-change-git-base-branch'
input will be a text box (simple validation on the text - use git rules)
if the branch doesn't exist we can throw an error
Suggest solution for empty input (use default)

**Comment by overbit** [comment]
@GreenMachine01 we need the UX/UI for this. I believe the place will be in the `Sync with Git Provider` page as part of the repository details since it can be overwritten by services configurations.

**Comment by GreenMachine01** [comment]
@overbit You are correct. we are working on the UI for it.
