### ISSUE TITLE
Add the default user/pwd to the generated README files of the service and the admin-ui

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6200]
### Feature description

Today people sometimes ask how to login into the generated admin UI with user/pwd.
As we always generate a default user/pwd when we seed the DB, it will be nice to add those as a comment on the README files of the service and admin-ui (near where we instruct how to run the server and UI) to assist people finding this information faster

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by professorabhay** [comment]
@souravjain540, I would like to work  on it 
assign it to me

**Comment by souravjain540** [comment]
@professorabhay assigned, let me know if you need any help :)

**Comment by professorabhay** [comment]
@souravjain540 and @mulygottlieb 
It will be great if you describe the path to the `README files`

**Comment by professorabhay** [comment]
Hey @souravjain540, Please take a look on the PR - https://github.com/amplication/amplication/pull/6308
