### ISSUE TITLE
🐛 Bug Report: drop down with options on the project has different capitalization 

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#6212]
### What happened?

![image](https://github.com/amplication/amplication/assets/73097785/c928522b-062a-426f-9dba-74c0e686323f)
The texts in the drop-down are not consistent in using CAPS

### What you expected to happen

have every word start with capitalization. 
"Project Configuration"
"View Code"

### How to reproduce

With in workspace select a desired project and click on 'Resource list'

### Amplication version

1.7.1

**Comment by levivannoort** [comment]
@GreenMachine01 please provide whether we would want all of the second word capitalized or none of them.

**Comment by GreenMachine01** [comment]
@levivannoort let's go for capping all words.
so we expect to see "View Code"

**Comment by vishalpawarR** [comment]
@GreenMachine01 I have raised the pull request for the above issue. In case of no issue please accept it

**Comment by GreenMachine01** [comment]
@vishalpawarR Thanks for another contribution :)

**Comment by vishalpawarR** [comment]
Thank you for accepting PR! and Closing it!
