### ISSUE TITLE
🐛 Bug Report: the pricing on the pricing page should be more readable

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#6213]
### What happened?

![image](https://github.com/amplication/amplication/assets/73097785/4b7edbf3-a4a0-49e5-9177-d3b9cc6cb446)

### What you expected to happen

That the interface loaded from Stigg should be loaded in a readable manner

### How to reproduce

Go to the `upgrade` button on within amplication, where you will be redirected to the `pricing & plans`

Pricing page on the amplication website (https://amplication.com/pricing):
![image](https://github.com/amplication/amplication/assets/73097785/278b39bb-8a5e-48e3-94d3-98c921e86247)

### Amplication version

1.7.1

**Comment by souravjain540** [comment]
copy of https://github.com/amplication/amplication/issues/6224
