### ISSUE TITLE
🐛 Bug Report: wrong README.md file on amplication-build-manager

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6215]
### What happened?

The README.md file on amplicaiton-build-manager is the default one created by nestJS.

https://github.com/amplication/amplication/tree/master/packages/amplication-build-manager

### What you expected to happen

The file should be updated with a description of the package and other content similar to other packages in the project 

e.g. 
https://github.com/amplication/amplication/tree/master/packages/data-service-generator
https://github.com/amplication/amplication/tree/master/packages/amplication-plugin-api

### How to reproduce

check the file here:
https://github.com/amplication/amplication/tree/master/packages/amplication-build-manager

**Comment by yuval-hazaz** [comment]
@mulygottlieb @GreenMachine01 please provide instructions for the new content

**Comment by souravjain540** [comment]
@mulygottlieb need this by tomorrow eod

**Comment by yuval-hazaz** [comment]
Saurav, please use this as a starter 

## Amplication Build Manager

amplication-build-manager is an essential part of the Amplication project. This package is responsible for managing the queue of build requests and running the DSG to generate the code.

### Installation
To use this package, follow the instructions at https://github.com/amplication/amplication

### Contributing
We welcome contributions from the community. If you wish to contribute, please take a look at our [contributing guidelines](https://github.com/amplication/amplication/blob/master/CONTRIBUTING.md).

**Comment by vishalpawarR** [comment]
Hey, can I help you in this here is the above message needs to be added in the README.md file of the amplication-build-manager?

**Comment by yuval-hazaz** [comment]
@vishalpawarR thanks for offering your help.
We are launching a campaign to help first-time contributors so we are holding some of the "god first issues" for that purpose.
so, this one is not available.

Thanks so much!

**Comment by vishalpawarR** [comment]
@yuval-hazaz Thank you for letting me know. and I was one of them and I contributed my first company Open Source PR to your organization.

**Comment by surajsharma14** [comment]
I want to contribute into there assign me this issue.

**Comment by souravjain540** [comment]
@surajsharma14 i just assigned you another issue. let someone other take this one :)

**Comment by professorabhay** [comment]
@souravjain540....
Assign it to me plz

**Comment by syedzubeen** [comment]
I'll take this one.

**Comment by souravjain540** [comment]
@syedzubeen assigned. let me know if you need any help!

**Comment by souravjain540** [comment]
@syedzubeen are you working on it?

**Comment by syedzubeen** [comment]
Yes

**Comment by syedzubeen** [comment]
Updated the PR with the suggested changes.
