### ISSUE TITLE
🐛 Bug Report: wrong README.md file on amplication-prisma-db

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6216]
### What happened?

The README.md file on amplicaiton-prisma-db is the default one created by nestJS.

https://github.com/amplication/amplication/tree/master/packages/amplication-prisma-db

### What you expected to happen

The file should be updated with a description of the package and other content similar to other packages in the project 

e.g. 
https://github.com/amplication/amplication/tree/master/packages/data-service-generator
https://github.com/amplication/amplication/tree/master/packages/amplication-plugin-api

### How to reproduce

check the file here:
https://github.com/amplication/amplication/tree/master/packages/amplication-prisma-db

**Comment by souravjain540** [comment]
@mulygottlieb need this before launch of the campaign tomorrow

**Comment by yuval-hazaz** [comment]
@souravjain540 , please use this as a starter. 

## amplication-prisma-db

amplication-prisma-db is an essential part of the Amplication project. This package holds the DB schema file (schema.prisma) used by amplication-server and amplication-git-pull-service

Installation
To use this package, follow the instructions on https://github.com/amplication/amplication

Contributing
We welcome contributions from the community. If you wish to contribute, please take a look at our [contributing guidelines](https://github.com/amplication/amplication/blob/master/CONTRIBUTING.md).

**Comment by vishalpawarR** [comment]
Hey, can I help you in this here is the above message needs to be added in the README.md file of the amplicaiton-prisma-db?

**Comment by yuval-hazaz** [comment]
@vishalpawarR thanks for offering your help.
We are launching a campaign to help first-time contributors so we are holding some of the "god first issues" for that purpose. 
so, this one is not available. 

Thanks so much!

**Comment by vishalpawarR** [comment]
@yuval-hazaz Thank you for letting me know. I will not be fixing the too easy issues.

**Comment by jainrishi2001** [comment]
Can this issue be assigned to me?

**Comment by souravjain540** [comment]
@jainrishi2001 assigned. Let me know if you need any help!

**Comment by jainrishi2001** [comment]
Hey!
Can you please review the PR?
Thanks
