### ISSUE TITLE
🐛 Bug Report: naming consistencty `Git provider` across project overview

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#6217]
### What happened?

![image](https://github.com/amplication/amplication/assets/73097785/9030eea0-2af8-4689-8218-dc3134f1e73c)

### What you expected to happen

Change the wording `git provider` to be `Git provider` in both the title and text of the `Sync with git provider` part.

### How to reproduce

Create/go to a project within an amplication workspace.

### Amplication version

1.7.1

**Comment by vishalpawarR** [comment]
Please close this PR request in case of no conflict https://github.com/amplication/amplication/pull/6263

**Comment by ShreyashSomvanshi** [comment]
@souravjain540 I would like to work on it!

**Comment by vilsi12** [comment]
Will love to contribute to this can you assign @levivannoort

**Comment by souravjain540** [comment]
@ShreyashSomvanshi assigned to you.

@vilsi12 please pick some other issue

**Comment by harshal-growthx** [comment]
Hey @souravjain540 is it just the content change?
And we'll be geting tshirt for changing it?
Is it true?

**Comment by souravjain540** [comment]
@ShreyashSomvanshi are you working on it?

**Comment by ShreyashSomvanshi** [comment]
> @ShreyashSomvanshi are you working on it?

Yes @souravjain540  I have made a PR #6293 today. Can you please review it and suggest changes if any?
