### ISSUE TITLE
🐛 Bug Report: naming consistency `Feature Request` across the project overview

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#6218]
### What happened?

Within the text itself the words `Feature Request` are capitalized but the title of the block itself is not.

<img width="395" alt="image" src="https://github.com/amplication/amplication/assets/73097785/25c5f54c-4a2a-429d-8fa2-322d53d39cbd">

### What you expected to happen

That the title aligns with the capitalization in the text, so `Feature Request`

### How to reproduce

Navigate to any project overview.

### Amplication version

1.7.1

**Comment by vishalpawarR** [comment]
@GreenMachine01 Please close this PR https://github.com/amplication/amplication/pull/6262 in case of no conflict and match of requirement

**Comment by ventesh** [comment]
@souravjain540 I want to work on this.

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/4eb8116b-9899-4448-8e75-fc5f8213f26a)
