### ISSUE TITLE
As User - I want to see the commit number in the Amplication UI instead of the GUID

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6219]
**Depends on** - https://github.com/amplication/amplication/issues/6198

**Overview:**
Once we add the commit # on the commit message, we may want to consider to show that number in the UI also in the commit page instead of the GUID

**We need to plan the impact on the UI and how to show the commit #**

**Comment by pratik-codes** [comment]
Hey I would love to work on this. Please elaborate a little on on the feature. From my understanding what is expected if a user add #andsomething on the commit message it should be show on the commit page. Please also attach a screenshot on where should this be shown

**Comment by GreenMachine01** [comment]
@pratik-codes this item is on hold while we finalize what exactly we expect.
