### ISSUE TITLE
🐛 Bug Report: project settings specify plural `Base Directories` while only one can be specified

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#6220]
### What happened?

<img width="1508" alt="image" src="https://github.com/amplication/amplication/assets/73097785/7f663a81-34d8-48f3-969c-33fad510c8f1">

### What you expected to happen

Change the naming in the settings overview to be singular as reflected by the option to provide the base directory in the configuration option itself.

`Base Directories` > `Base Directory`

### How to reproduce

Navigate to a project and go to the settings for that project.

### Amplication version

1.7.1

**Comment by levivannoort** [comment]
same things applies to the `service` settings

**Comment by vishalpawarR** [comment]
@levivannoort Please check this PR https://github.com/amplication/amplication/pull/6261 and close it in case of no issues!

**Comment by professorabhay** [comment]
Hey @souravjain540, May I work on that issue.

**Comment by souravjain540** [comment]
@professorabhay I assigned you another issue already

**Comment by professorabhay** [comment]
@souravjain540 actually I have some doubts with that issue but in this one I'm ready to raise a  PR. 
I will unassign myself from older one.

**Comment by BhavyaMPatel** [comment]
@souravjain540  if no one is working on this then you can assign this issue to me Thank you

**Comment by souravjain540** [comment]
Assigned @BhavyaMPatel

**Comment by BhavyaMPatel** [comment]
thank you @souravjain540

**Comment by CHAMP010** [comment]
I want to work on this issue, @souravjain540 please assign me this!

**Comment by BhavyaMPatel** [comment]
@souravjain540 small doubt after making some changes how can I verify locally could you please suggest that

**Comment by mulygottlieb** [comment]
QA Passed:


![Image](https://github.com/amplication/amplication/assets/1912933/c61242bd-e8a7-498c-ab99-b3a7902803fb)

**Comment by BhavyaMPatel** [comment]
Thank You ,  That's my another little step in open source world
