### ISSUE TITLE
🐛 Bug Report: Text is missing break lines in FAQ

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6223]
**Actual:**

![Image](https://github.com/amplication/amplication/assets/112330500/b2a351ed-a61e-4716-b897-9ef62f98c079)

**Expected:**

![Image](https://github.com/amplication/amplication/assets/112330500/91e40194-21ee-4a86-adb9-841647e84154)

**Requirements:**
1. break lines in the text according to the design example
2. remove the ' from "quote" at the end

**Comment by vishalpawarR** [comment]
@GreenMachine01 I have fixed the issue. I have created the PR for the same.

**Comment by GreenMachine01** [comment]
@vishalpawarR Thank you for your contribution!
