### ISSUE TITLE
🐛 Bug Report: Pricing page in the app looks bad (wrong width)

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6224]
### What happened?

The in-app pricing page (when you click "upgrade" on the UI) looks bad - the width of each column is narrower than desired and this causes the text to line-break in the wrong places and look bad altogether:
<img width="904" alt="image" src="https://github.com/amplication/amplication/assets/1912933/cabb0bde-87b0-42ef-ba13-3bd37ea714c1">

It should look identical to the pricing page on the website at https://amplication.com/pricing :

<img width="1033" alt="image" src="https://github.com/amplication/amplication/assets/1912933/1d6d2ee9-5d11-4f76-8392-14c60322f7dc">

### What you expected to happen

The in-app pricing page should look like the pricing page on the website 

### How to reproduce

in the app press the "upgrade" button to get to the pricing page

### Amplication version

1.7.1

**Comment by mulygottlieb** [comment]
@souravjain540, we want to give this one high priority, can you find a brave community member that wants to take this as soon as possible? :)

**Comment by vishalpawarR** [comment]
Hey I would like to help need more info given If given I will fix the issue

**Comment by souravjain540** [comment]
@vishalpawarR assigned, what info do you need to work?

**Comment by vishalpawarR** [comment]
@souravjain540, I need the specific device size for closing the issue or the steps to replicate the issue on the starting size and ending screen size for media query for fixing this issue.

**Comment by souravjain540** [comment]
@mulygottlieb can you help here?

**Comment by vishalpawarR** [comment]
@souravjain540 Hey It is still unclear to me what I need to do here.

**Comment by souravjain540** [comment]
@vishalpawarR  can you be more specific?

**Comment by GreenMachine01** [comment]
As we need to fix this item ASAP I opened it up for someone to take it.

**Comment by mulygottlieb** [comment]
@souravjain540, please let me know if you find a community member to take it, or we should take it internally

**Comment by harshit-senpai** [comment]
Hey I have re-created the issue and would like to work on it 
![image](https://github.com/amplication/amplication/assets/93075068/7954c3c1-071a-4e38-a659-1dba809d3d38)

**Comment by thekavikumar** [comment]
Hey Can I work on this?
