### ISSUE TITLE
As PO - I want to update text in the Service Overview section

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6225]
**Current text** - "Push the auto-generated code to Github and take it to the moon with your coding skills."
**Requested text** - "Push the auto-generated code to your Git provider and take it to the moon with your coding skills."

![Image](https://github.com/amplication/amplication/assets/112330500/2bcd77c7-b5a0-4d08-bf39-9b94f1402a8a)

**Comment by karthickbharathi1** [comment]
Hi @GreenMachine01 , I would like to work on this issue. Can you tell me where is the service overview section is located?

**Comment by GreenMachine01** [comment]
@abrl91 please assist.

**Comment by GreenMachine01** [comment]
@karthickbharathi1 assigned to you. good luck!

**Comment by GreenMachine01** [comment]
@X-sena-X thanks! if the item becomes available Ill let you know.

**Comment by karthickbharathi1** [comment]
@GreenMachine01  Can you tell me where the location of service overview section

**Comment by Karthick20s** [comment]
@GreenMachine01 hi bro

**Comment by GreenMachine01** [comment]
@karthickbharathi1 When you click on a service you reach its overview page.
![image](https://github.com/amplication/amplication/assets/112330500/da2b8e5c-7d33-4fa6-9ea9-65f042d59323)
I asked @abrl91 to assist with showing you where you need to make the change.

**Comment by mulygottlieb** [comment]
Hi @karthickbharathi1,

Thanks again for your contribution!
I'm really sorry, but there has been a slight confusion, and this ticket is actually not needed - we had a misunderstanding internally. So, unfortunately, I am closing this ticket and the PR you've contributed :(
Please accept our sincere apology, and I'm sure you will be able to find more opportunities to contribute 💪

**Comment by GreenMachine01** [comment]
not needed as the text is dynamic and knows to show the relevant provider name.
