### ISSUE TITLE
🐛 Bug Report: Service settings are not saved

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6230]
### What happened?

When you make changes to the service settings in one of these categories:
![image](https://github.com/amplication/amplication/assets/1912933/461e11c4-1a03-41f9-a1a4-56bd368e1ef0)

They are not saved:
https://amplic-my.sharepoint.com/personal/mor_amplication_com/_layouts/15/stream.aspx?id=%2Fpersonal%2Fmor%5Famplication%5Fcom%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files%2FScreen%20Recording%202023%2D06%2D13%20at%2018%2E10%2E10%2Emov&referrer=Teams%2ETEAMS%2DELECTRON&referrerScenario=p2p%5Fns%2Dbim&ga=1

### What you expected to happen

Service settings should save when changing tabs

### How to reproduce

create a service in Amplication, go to the service settings, make changes e.g. to base directories, navigate away, return to those settings - observe your changes were not saved.

### Amplication version

1.7.1

**Comment by AkhilJ321** [comment]
Hey, I wanted to try working on this issue, but I am new to the codebase, I regenerated the error, but am not able to locate the code for the specific. It would be very significant if you could help me with that.

**Comment by AkhilJ321** [comment]
Hey, I am interested in working on this issue,could you please assign it to me?

**Comment by GreenMachine01** [comment]
@souravjain540 FYI

**Comment by souravjain540** [comment]
@AkhilJ321 assigned :) you can get a limited edition amplication shirt for this issue. let me know if you need any help!

**Comment by AkhilJ321** [comment]
Thanks for assigning me. I have been trying to solve the issue since it is posted, but as this is first time  I have been trying to contribute to this project and the project structure is new to me. I found the component where the code is written for this page, but i am not able to find from where it is actually rendering. So it will be really great if you could help me with finding the required files for this bug from which it is actually rendering.

**Comment by souravjain540** [comment]
@mulygottlieb can you help @AkhilJ321 ? maybe you guys can talk in discord support :)

**Comment by AkhilJ321** [comment]
I have solved the issue.I will be posting the PR soon after reading contributing guidelines.

**Comment by souravjain540** [comment]
@AkhilJ321 cool. let me know :)

**Comment by AkhilJ321** [comment]
@souravjain540 .Hey sorry to bother, but I was hoping if my PR could be reviewd for changes I did.As there is no response since my last changes,I was wondering if the issue has been closed or still open.

**Comment by mulygottlieb** [comment]
Verified on staging (the fix was merged to master, my mistake) - will pull master into next towards release, but anyway this is verified
