### ISSUE TITLE
🐛 Bug Report: Change discord link in readme

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#6236]
### What happened?

the link of discord in `amplication/packages/amplication-build-manager/README.md` is `https://discord.gg/G7Qnnhy`. change it to `https://amplication.com/discord`

### What you expected to happen

change link

### How to reproduce

open the given path

**Comment by vishalpawarR** [comment]
@souravjain540 Please check and close this issue in case on no conflict https://github.com/amplication/amplication/pull/6260

**Comment by shrinishant** [comment]
@souravjain540 i would like to work on it

**Comment by souravjain540** [comment]
@shrinishant  assigned :) let me know if you need any help!

**Comment by shrinishant** [comment]
@souravjain540 opened [PR](https://github.com/amplication/amplication/pull/6283) for the issue
