### ISSUE TITLE
🐛 Bug Report: change discord link in client readme

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#6237]
### What happened?

change discord link from `projects/amplication/packages/amplication-client/README.md` https://discord.gg/G7Qnnhy` to `https://amplication.com/discord`
<img width="849" alt="Screenshot 2023-06-14 at 2 54 19 PM" src="https://github.com/amplication/amplication/assets/53312820/f0e18607-de2b-4d1d-b17a-8fb68e3fe5f4">

### What you expected to happen

change link.

### How to reproduce

open the given path

**Comment by vishalpawarR** [comment]
@souravjain540 Please check this PR and close in case of no issues https://github.com/amplication/amplication/pull/6259

Also I was not able to find this issue in the specified location. Refer the issue below:
change discord link from projects/amplication/packages/amplication-client/README.md [https://discord.gg/G7Qnnhy`](https://discord.gg/G7Qnnhy%60) to https://amplication.com/discord

**Comment by AdityyaX** [comment]
#6268 changed discord link from projects/amplication/packages/amplication-client/README.md

**Comment by riju951** [comment]
Can you assign this issue to me ?
