### ISSUE TITLE
🐛 Bug Report: change discord link in SupportMenu.tsx`

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#6238]
### What happened?

Change this discord link to `https://amplication.com/discord`

<img width="415" alt="Screenshot 2023-06-14 at 2 58 21 PM" src="https://github.com/amplication/amplication/assets/53312820/f40700b1-4ae8-42e7-b1bf-7aca19bda557">

### What you expected to happen

change link

### How to reproduce

open this path: `amplication/packages/amplication-client/src/Layout/SupportMenu.tsx`

**Comment by vishalpawarR** [comment]
@souravjain540 Please close this PR https://github.com/amplication/amplication/pull/6258 In case of no issues

**Comment by surajsharma14** [comment]
assign to me

**Comment by chandanck22** [comment]
Hey this going to be my first contribution @souravjain540 plz assign this to me

**Comment by professorabhay** [comment]
Hey assign it to me !!
Ready to create pr

**Comment by souravjain540** [comment]
first come first serve. assigned to @surajsharma14 

@chandanck22  @professorabhay  please grab some other issues :)

**Comment by surajsharma14** [comment]
done

**Comment by souravjain540** [comment]
@surajsharma14 have you raised a PR?

**Comment by surajsharma14** [comment]
YEssss

**Comment by surajsharma14** [comment]
@souravjain540 merge it. I done the changes

**Comment by souravjain540** [comment]
@surajsharma14 what's your pr number?

**Comment by surajsharma14** [comment]
> @surajsharma14 what's your pr number?

[9878d01](https://github.com/surajsharma14/amplication/commit/9878d019d824e9dc4970affd9b84193a67710611)

**Comment by souravjain540** [comment]
@surajsharma14  you have to make PR again the amplication/amplication `master` branch.

**Comment by overbit** [comment]
## Test results
✅
