### ISSUE TITLE
🐛 Bug Report: change the discord link in WelcomePage

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#6239]
### What happened?

<img width="415" alt="Screenshot 2023-06-14 at 3 01 09 PM" src="https://github.com/amplication/amplication/assets/53312820/e37edc4c-c07b-469b-9e5d-e24fa54b1ad8">

change this discord link to `https://amplication.com/discord`

### What you expected to happen

change link

### How to reproduce

path: `amplication/packages/amplication-client/src/Layout/WelcomePage.tsx`

**Comment by vishalpawarR** [comment]
@souravjain540 I think I have resolved this issue in the same PR of this one please confirm also there are few place which still have discord.gg link please check and if you want those to be fixed please assign me for resolving those issues. Thanks!

**Comment by abhinav2712** [comment]
@souravjain540 Assign me with this issue, can fix this one easily

**Comment by professorabhay** [comment]
@souravjain540, I would like to work on that issue .
Assign it to me

**Comment by souravjain540** [comment]
@abhinav2712 assigned. you can get a limited edition amplication shirt by solving this issue. let me know if you need any help :)

**Comment by abhinav2712** [comment]
> @abhinav2712 assigned. you can get a limited edition amplication shirt by solving this issue. let me know if you need any help :)

sure! on it

**Comment by abhinav2712** [comment]
> > @abhinav2712 assigned. you can get a limited edition amplication shirt by solving this issue. let me know if you need any help :)
> 
> Done, check my PR : #6274  . Since this was a minor change, I did change the main branch, let me know if thats fine

**Comment by abhinav2712** [comment]
@souravjain540 Do check once #6274

**Comment by mulygottlieb** [comment]
The link in line 89 of the same file also needs to change

**Comment by abhinav2712** [comment]
> The link in line 89 of the same file also needs to change

On it

**Comment by abhinav2712** [comment]
> The link in line 89 of the same file also needs to change

just added a new PR for both the fixes: #6295
