### ISSUE TITLE
🐛 Bug Report: change the second discord link in WelcomePage 

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#6240]
### What happened?

<img width="566" alt="Screenshot 2023-06-14 at 3 03 26 PM" src="https://github.com/amplication/amplication/assets/53312820/15ad1490-c997-409d-bdc3-9bfe466a5180">

Change the link to `https://amplication.com/discord`

### What you expected to happen

change link

### How to reproduce

open the path: `amplication/packages/amplication-client/src/Layout/WelcomePage.tsx`

**Comment by kirtanchandak** [comment]
Can I work on this issue??

**Comment by souravjain540** [comment]
@kirtanchandak assigned. let me know if you need any help :)
