### ISSUE TITLE
🐛 Bug Report: change the discord link in prismadb readme

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#6241]
### What happened?

<img width="565" alt="Screenshot 2023-06-14 at 3 05 27 PM" src="https://github.com/amplication/amplication/assets/53312820/6af1fcf7-ddf1-48b3-960b-78326392840b">

change the discord link to: https://amplication.com/discord

### What you expected to happen

change link

### How to reproduce

path: `/amplication/packages/amplication-prisma-db/README.md`

**Comment by prasadfirame** [comment]
@souravjain540 hey plz assign this to me .

**Comment by prasadfirame** [comment]
Hey this going to be my first contribution @souravjain540 plz assign this to me

**Comment by souravjain540** [comment]
@prasadfirame  assigned, you can get a t-shirt by solving this issue :) Let me know if any help needed!

**Comment by ParthChittora** [comment]
If not merged till now could you assign it to me.
@souravjain540

**Comment by prasadfirame** [comment]
I was busy ,now working on this issue , please don't assign this to someone else @souravjain540 , I'll submit the pr soon

**Comment by kumarankit999** [comment]
Can I work On this Issue because it is still Opened

**Comment by mulygottlieb** [comment]
Marking as passed QA, although another change to the README.md of this package has actually overwritten this, as part of #6216 ( @yuval-hazaz FYI)
