### ISSUE TITLE
🐛 Bug Report: enforce naming in the `workspace settings` page 

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#6242]
### What happened?

<img width="1503" alt="image" src="https://github.com/amplication/amplication/assets/73097785/c36b5c5d-ae51-4fc6-9e9b-39c58ba70187">

Under the `Workspace Name` if `workspace ID`.

### What you expected to happen

`workspace ID` should be `Workspace ID`

### How to reproduce

select a workspace, go to workspace settings on the bottom left corner

### Amplication version

1.7.2

**Comment by vishalpawarR** [comment]
@souravjain540 and @levivannoort Please check this PR https://github.com/amplication/amplication/pull/6255 and close in case of no issue.

**Comment by vishalpawarR** [comment]
@souravjain540 I wanted to mention that I agree with the decision not to raise a pull request (PR) before being assigned. I am learning a lot while participating in Open Source. I was wondering why my PR wasn't accepted. It would have been helpful if you had mentioned the importance of getting issue assignment before closing them. I had set aside time to address and close those issues.

I appreciate any guidance you can provide to enhance my contributions. Thank you.

**Comment by souravjain540** [comment]
> @souravjain540 I wanted to mention that I agree with the decision not to raise a pull request (PR) before being assigned. I am learning a lot while participating in Open Source. I was wondering why my PR wasn't accepted. It would have been helpful if you had mentioned the importance of getting issue assignment before closing them. I had set aside time to address and close those issues.
> 
> I appreciate any guidance you can provide to enhance my contributions. Thank you.

I am sorry. I don't mean to waste your time or anything else. 

That's the cost exactly you have to pay when you work on a PR without getting it assigned. We already picked these issues for a campaign dedicated to first-time contributors so that they can start their open source journey.

I would love to offer you a t-shirt for your time and would love to see more PRs by rule. :)

**Comment by sobhanbera** [comment]
Will love to contribute to this
Pls Add me as an assignee for this issue @souravjain540 @levivannoort
Thanks!

**Comment by souravjain540** [comment]
@sobhanbera assigned. let me know if you need any help!

**Comment by vishalpawarR** [comment]
> > @souravjain540 I wanted to mention that I agree with the decision not to raise a pull request (PR) before being assigned. I am learning a lot while participating in Open Source. I was wondering why my PR wasn't accepted. It would have been helpful if you had mentioned the importance of getting issue assignment before closing them. I had set aside time to address and close those issues.
> > I appreciate any guidance you can provide to enhance my contributions. Thank you.
> 
> I am sorry. I don't mean to waste your time or anything else.
> 
> That's the cost exactly you have to pay when you work on a PR without getting it assigned. We already picked these issues for a campaign dedicated to first-time contributors so that they can start their open source journey.
> 
> I would love to offer you a t-shirt for your time and would love to see more PRs by rule. :)

Thank you for your understanding. It was truly exciting for me to submit my first PR with an actual company like yours. I apologize if I worked on the issue without it being assigned to me.

I'm delighted😊 by your offer of a t-shirt👕, and I'm eager to receive it. Could you please let me know the process for obtaining the t-shirt?

Once again, thank you for your support and encouragement. I look forward to continuing my journey with Open Source and submitting more **PRs by rule :)**

**Comment by mulygottlieb** [comment]
QA pssed:


![Image](https://github.com/amplication/amplication/assets/1912933/bb867be6-4321-45db-8daf-3338649851d2)
