### ISSUE TITLE
🐛 Bug Report: inconsistent capitalization on code generation

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#6244]
### What happened?

<img width="1509" alt="image" src="https://github.com/amplication/amplication/assets/73097785/eba18014-2d58-4b7d-bd62-51a0a8207216">

### What you expected to happen

The first line of code generation on the `Adding task to queue` part should be changed from `create build generation task` to `Create build generation task`.

### How to reproduce

Build any service in any project.

### Amplication version

1.7.2

**Comment by levivannoort** [comment]
Another change that could be made in that same space is the following (no capitalization on the word 'version'):

```
2023-06-05T13:59:04.342Z (Info) Build Version: 14x6peyw
```
>
```
2023-06-05T13:59:04.342Z (Info) Build version: 14x6peyw
```

**Comment by vishalpawarR** [comment]
Hey! I have raised this pull request https://github.com/amplication/amplication/pull/6254 please accept.

**Comment by souravjain540** [comment]
Can't accept this PR. Sorry!

You should follow the rules of contributing to open source.

First get it assigned to you and then make a PR.

**Comment by VaibhavTalkhande** [comment]
i would like to work on it @souravjain540 sourav

**Comment by souravjain540** [comment]
@VaibhavTalkhande assigned. let me know if you need any help!

**Comment by ParthChittora** [comment]
It will be my first contribution, if not merged till now could you assign it to me

**Comment by souravjain540** [comment]
@ParthChittora  this is already assigned please check these issues: https://github.com/amplication/amplication/issues?q=is%3Aopen+label%3Afirst-timers+assignee%3Asouravjain540

**Comment by ashutosh887** [comment]
I'm next on the queue @souravjain540

**Comment by VaibhavTalkhande** [comment]
hey @souravjain540   
I have made changes in  Adding task queue  "create build generation task" to Create build generation task.
should I also change 
Build Version  to Build version

**Comment by VaibhavTalkhande** [comment]
Hey @souravjain540   created a pull request following contributing guideline do let me know if some changes are needed to be 
done .

**Comment by mulygottlieb** [comment]
QA passed:


![Image](https://github.com/amplication/amplication/assets/1912933/bcac0133-4711-4f8a-a6a2-cfdc0d475755)
