### ISSUE TITLE
Thirty Issues for First Timers 👕 

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#6270]
### Feature description

Hello contributors 👋

As proud members of the open-source community, we inspire developers to contribute to open-source projects 💜

To help you get started, we have found  **30 issues** for first-time contributors that can be a great way to fire-start your journey of open-source contribution.

By giving back to the community, you’re also getting a chance to win cool **limited-edition** swag.

For each PR that will be merged by a new contributor, we will reward each one with our **unique** Amplication T-shirt.

 
![30](https://github.com/amplication/amplication/assets/53312820/edb1910a-db5a-4da6-a68a-efb1f2e7b722)

⚠️ The rules are simple:

- This activity applies only to the issues listed as “first-timers.”
- Only new contributors to Amplication are entitled to receive a t-shirt and stickers.
- Each new contributor can solve up to (1) one issue and can get up to (1) one t-shirt.
- Only the person assigned by Team Amplication will be considered a valid contributor
- This activity is on a “first come, first serve” basis

**CAMPAIGN START DATE: Wednesday, June 16th, 2023**

# Issues 💯

| Issue                                                                                                                                | Description                                                           |Status                                                           |
| ------------------------------------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |------------------------------------------------- |
| <a href="https://github.com/amplication/amplication/issues/7067"><img src="https://img.shields.io/badge/6044%20-bug-green.svg"/></a> | UI/UX - Misalignment of Text and Icon in Dropdown Field. |Taken|
| <a href="https://github.com/amplication/amplication/issues/5962"><img src="https://img.shields.io/badge/5962%20-bug-green.svg"/></a> | I want a plugin that creates .devcontainer.json file to be able to use GitHub Codespaces |Taken|
| <a href="https://github.com/amplication/amplication/issues/5428"><img src="https://img.shields.io/badge/5428%20-bug-green.svg"/></a> | I want to easily view and edit the plugin settings in the code view window. |Taken|
| <a href="https://github.com/amplication/amplication/issues/4654"><img src="https://img.shields.io/badge/4654%20-bug-green.svg"/></a> | I want to have an updated and visually appealing design for the topics page in the Message Broker. |Available|
| <a href="https://github.com/amplication/amplication/issues/4653"><img src="https://img.shields.io/badge/4653%20-bug-green.svg"/></a> |I want to easily connect services to my Message Broker topics. |Taken|
| <a href="https://github.com/amplication/amplication/issues/4424"><img src="https://img.shields.io/badge/4424%20-bug-green.svg"/></a> | No default route. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6247"><img src="https://img.shields.io/badge/6247%20-bug-green.svg"/></a> | incorrect naming for GitHub on Push changes to GitHub part of code generation. |Available|
| <a href="https://github.com/amplication/amplication/issues/6244"><img src="https://img.shields.io/badge/6244%20-bug-green.svg"/></a> | inconsistent capitalization on code generation. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6243"><img src="https://img.shields.io/badge/6243%20-bug-green.svg"/></a> | incorrect naming of GitHub on git provider integration. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6242"><img src="https://img.shields.io/badge/6242%20-bug-green.svg"/></a> | enforce naming in the workspace settings page. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6241"><img src="https://img.shields.io/badge/6241%20-bug-green.svg"/></a> | change the discord link in prismadb readme. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6239"><img src="https://img.shields.io/badge/6239%20-bug-green.svg"/></a> | change the discord link in WelcomePage. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6238"><img src="https://img.shields.io/badge/6238%20-bug-green.svg"/></a> | change discord link in SupportMenu.tsx. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6237"><img src="https://img.shields.io/badge/6237%20-bug-green.svg"/></a> | change discord link in client readme. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6236"><img src="https://img.shields.io/badge/6236%20-bug-green.svg"/></a> | change discord link in readme. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6230"><img src="https://img.shields.io/badge/6230%20-bug-green.svg"/></a> | Service settings are not saved. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6220"><img src="https://img.shields.io/badge/6220%20-bug-green.svg"/></a> | project settings specify plural Base Directories while only one can be specified. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6218"><img src="https://img.shields.io/badge/6218%20-bug-green.svg"/></a> | naming consistency Feature Request across the project overview. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6217"><img src="https://img.shields.io/badge/6217%20-bug-green.svg"/></a> | naming consistencty Git provider across project overview. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6216"><img src="https://img.shields.io/badge/6216%20-bug-green.svg"/></a> | wrong README.md file on amplication-prisma-db. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6215"><img src="https://img.shields.io/badge/6215%20-bug-green.svg"/></a> | wrong README.md file on amplication-build-manager. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6214"><img src="https://img.shields.io/badge/6214%20-feat-blue.svg"/></a> | Create a hyperlink on the connections page of a service to the message broker creation wizard. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6200"><img src="https://img.shields.io/badge/6200%20-feat-blue.svg"/></a> | Add the default user/pwd to the generated README files of the service and the admin-ui. |Taken|
| <a href="https://github.com/amplication/amplication/issues/6170"><img src="https://img.shields.io/badge/6170%20-bug-green.svg"/></a> | I want to add test coverage to the subscription service in Amplication server |Available|
| <a href="https://github.com/amplication/amplication/issues/7069"><img src="https://img.shields.io/badge/6163%20-bug-green.svg"/></a> | Generated code is created with linting errors for base services |Taken|
| <a href="https://github.com/amplication/amplication/issues/6145"><img src="https://img.shields.io/badge/6145%20-bug-green.svg"/></a> |  I want to improve the design of the "load more" button |Taken|
| <a href="https://github.com/amplication/amplication/issues/6118"><img src="https://img.shields.io/badge/6118%20-bug-green.svg"/></a> |  amplication-server logs PR failures with wrong level |Taken|
| <a href="https://github.com/amplication/amplication/issues/6099"><img src="https://img.shields.io/badge/6099%20-bug-green.svg"/></a> |  Commit page shows in progress state regardless the build result |Taken|
| <a href="https://github.com/amplication/amplication/issues/6055"><img src="https://img.shields.io/badge/6055%20-bug-green.svg"/></a> |  Generated code should not include @ts-ignore or eslint-disable-next-line import/no-unresolved |Taken|
| <a href="https://github.com/amplication/amplication/issues/6047"><img src="https://img.shields.io/badge/6047%20-bug-green.svg"/></a> |  Malfunctioning UI when no projects are listed |Taken|

**Comment by syedzubeen** [comment]
Are there any open issues left? I see all of them assigned.

**Comment by souravjain540** [comment]
yes 10 of them are still not assigned to anybody

check here: https://github.com/amplication/amplication/issues?q=is%3Aopen+label%3Afirst-timers+assignee%3Asouravjain540

**Comment by yashlondhe90960** [comment]
is there any issues left, if yes then please assign it to me. I am first time contributing to Amplication.

**Comment by Vikash-8090-Yadav** [comment]
is there any issue left?

**Comment by mswat5** [comment]
Shit!why can't I see any open issue there🤞😩?

**Comment by Philip-D21** [comment]
seems as if all issues has been assigned. @souravjain540

**Comment by Agressjames** [comment]
Is there any first time issue
Please assign it to me
