### ISSUE TITLE
🐛 Bug Report: UI breaks when uninstalling amplication git provider from git 

### ISSUE THREAD

**Issue by pratik-codes** [amplication/amplication#6282]
### What happened?

After the git provider is connected and installed after uninstalling amplication from git and going back to dashboard again, even after refreshing the connection of git doesnt gets deleted. In case the user clicks on select repository it gives internal server error

### What you expected to happen

It should give the option to connect again

### How to reproduce

Connect git provider.
Uninstall amplication from git side
Refresh page and try to select reporitory

https://github.com/amplication/amplication/assets/64960569/bc2785a2-1f63-4d60-9598-bf639cace8b9

### Amplication version

Lastest prod

### Environment

Production

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GreenMachine01** [comment]
@pratik-codes Thanks! We already have a ticket to fix this issue - https://github.com/amplication/amplication/issues/4957
