### ISSUE TITLE
📖 Documentation: Can't find Admin credentails for the Admin app of the API created using amplification

### ISSUE THREAD

**Issue by SiddheshKukade** [amplication/amplication#6284]
### Description (What is it?)

Hello  I've created a demo app with amplication found here :https://github.com/SiddheshKukade/amplication-test-todo-api/ 
and after setting up the API and ADMIN 
I opened the Admin UI on /3001
But I could not found the Username and password in the README or in the docs to login as a ADMIN 
![image](https://github.com/amplication/amplication/assets/65951872/9157c8df-39c5-4ab4-a34a-a7de8c1f2b40)

### Use Case (Why does the user need it?)

To login as an Admin 

### Issue URL

N/A

### Pull Request URL

N/A

### How it works (How does the user use it?)

See the default admin username and password and then login 

### Screenshots

![image](https://github.com/amplication/amplication/assets/65951872/2a4d0e0c-ba4b-4bac-b578-97b609992963)

### Code Samples

https://github.com/SiddheshKukade/amplication-test-todo-api/ 

### Figma URL

N/A

**Comment by SiddheshKukade** [comment]
Can anyone help to find where can I get the username and password for the default admin

**Comment by professorabhay** [comment]
Hai @SiddheshKukade, ![Screenshot_2023-06-17-14-01-24-799_com.google.android.googlequicksearchbox.png](https://github.com/amplication/amplication/assets/76243309/a560689b-acf3-4f0f-bae8-b8495ef3ded1)

Try it out. We will add the default credentials in readme files soon.

**Comment by professorabhay** [comment]
@souravjain540 #6200

**Comment by SiddheshKukade** [comment]
Thanks I'll close this now

**Comment by brupelo** [comment]
Hi, I'm running amplication on latest master 4eca01fc07e97ce8c43196e8b29eceae03f62cad I'm trying to find the default user/password so I've landed here.

I've tried email="admin" password="admin" but I'll get

![image](https://github.com/amplication/amplication/assets/18058492/de0b06cd-d18b-48e5-b7c0-bf9ca659c438)

I guess this [PR](https://github.com/amplication/amplication/pull/6360/files) applied to some old version of amplication?

Thanks in advance!
