### ISSUE TITLE
🐛 Bug Report: GitHub is spelled incorrectly (Github) on the sync connection list 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6286]
### What happened?

Github is used with incorrect casing 

<img width="938" alt="image" src="https://github.com/amplication/amplication/assets/43705455/1dc50bc6-5d67-4980-9c75-9eee37942d4f">

### What you expected to happen

instead of Github is should be spelled GitHub

The relevant code is in 
/Users/yuvalhazaz/projects/amplication.git/amplication/packages/amplication-client/src/Resource/git/GitActions/GitProviderConnection.tsx

It happens because the component is using the enum value as string. 

instead we need to use a mapping from a providerName to DisplayName
something like 

```typeScript
const PROVIDERS_DISPLAY_NAME: {
  [key in models.EnumGitProvider]: string;
} = {
  [models.EnumGitProvider.Github]: "GitHub",
  [models.EnumGitProvider.Bitbucket]: "Bitbucket",
};
```

### How to reproduce

go to Git Sync page

**Comment by professorabhay** [comment]
Hey @yuval-hazaz, I would like to resolve that issue. Please assign it to me. Will submit PR asap !! 🙂

**Comment by professorabhay** [comment]
@souravjain540
Am I eligible to work on that ??

**Comment by souravjain540** [comment]
@professorabhay Yes but this is not part of first-timers :)

**Comment by professorabhay** [comment]
😶 @souravjain540, 
I knew it !! 
I didn't only contribute to win swags only 🌐
Thanks for assigning 🙂

I also have the doubt in the #6200. I comment on it, help me if you can !!

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/4bf50860-60a0-42fa-96a2-8d4de36156ad)
