### ISSUE TITLE
🐛 Bug Report: Update node version requirement in CONTRIBUTING.md

### ISSUE THREAD

**Issue by manulpatel** [amplication/amplication#6288]
### What happened?

Currentlty the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CONTRIBUTING.md) mentions requirement of node version as `node version: ^16.3.0 || ^14.0.0"`. But Amplication works perfectly fine with `Node.js v16 or above` as mentioned in the [README.md](https://github.com/amplication/amplication/blob/master/README.md).

Hence we need to update the version requirement of node in CONTRIBUTING.md.

### What you expected to happen

Updated version requirement of node in CONTRIBUTING.md showing it is supported with Node.js v16 or above.

### How to reproduce

New contributor refering to [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CONTRIBUTING.md) for local dev setup.

### Environment

Node version: 18.16.0
Npm version: 8.1.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment]
@mulygottlieb please review

**Comment by ashutosh887** [comment]
@mulygottlieb @yuval-hazaz Please let me work on this

**Comment by professorabhay** [comment]
Hey @souravjain540, If that issue is still not resolved then please assign it to me. I would like to contribute!
