### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by bagiyal** [amplication/amplication#6289]
### What happened?

I Recently Setup Amplication in local when I filled all details in Sign Up getting this error 
![image](https://github.com/amplication/amplication/assets/63339447/f711586e-940f-4aae-85b6-10fab73b05f1)

### What you expected to happen

I am not able to Sign up 

### How to reproduce

Setup Project Locally and Try to Sign Up

**Comment by sumitbhanushali** [comment]
@bagiyal have you run all scripts from scripts section in readme? maybe you forgot to run script to start server

**Comment by bagiyal** [comment]
I did but same error

**Comment by bagiyal** [comment]
Can you help me out

**Comment by razuro** [comment]
@bagiyal
After running `npm run serve:server`, check in your console if you received this error message: `FetchError: request to https://app.posthog.com/capture/ failed, reason: unable to get local issuer certificate`

If you do, you can bypass that error by disabling the HTTPS cert check. In `/packages/amplication-server/.env` put `NODE_TLS_REJECT_UNAUTHORIZED=0` at the first line.

Hope that helps.
