### ISSUE TITLE
As User - I want an easy way to create the user entity via the service settings

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6305]
1. Create a new section in the service settings "Entities" (Place it below the 'General' settings)
2. Add a button to create the default 'User' entity

**Comment by sumitbhanushali** [comment]
@GreenMachine01 correct me if i m wrong but user entity is created by default? even if auth is skipped

**Comment by jaysoni-ash42** [comment]
@GreenMachine01  can i work on this issue ?

**Comment by GreenMachine01** [comment]
@jaysoni-ash42 I am still baking how I want this capability to look like in the UI. so for now its on hold.
Thanks!
