### ISSUE TITLE
As Free Plan User - I want to know there is a promotion offer on the pro plan

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6314]
**Overview:**

In order to promote our two-month free offer for the Pro plan, we will be implementing a gift icon feature. This gift icon will always be visible to users who are on the Free plan. The purpose of this feature is to increase awareness of the special offer and to encourage users to upgrade to the Pro plan.

**Requirements:**

1. **Gift Icon Visibility:** A gift icon should be permanently displayed on the side bar for all users on **Free** plans. (according to the design)
2. **Button Click Action:** Clicking on the gift icon button should redirect users to the pricing page where they can learn more about the Pro plan and our special offer.
3. **Tooltip Display:** When users hover over the gift icon, a tooltip should appear that displays the text "Enjoy 2 months absolutely FREE with our limited time offer!" This tooltip provides immediate information about the offer without requiring the user to leave their current page.
4. **Tracking Event:** In order to track the effectiveness of this feature, implement a new client-side tracking event named "UpgradeOnSideBarClick". This event will trigger each time a user clicks on the gift icon button to go to the pricing page. This data will be used for analyzing user interaction and conversion rates related to the gift icon feature.

**Event Details:**

Event Name: "UpgradeOnSideBarClick"
Description: This event is triggered when a user clicks the gift icon in the side bar.
Reason: “Side panel CTA”
Location: App

**Figma** - https://www.figma.com/file/d5DTMR3KzcKLgZbMraoXrs/Coupon-pop-up?type=design&node-id=3014%3A5789&t=LZiAV09ZnaNy7EN2-1

**Comment by GreenMachine01** [comment]
@yuval-hazaz the button image has a bug

**Comment by mulygottlieb** [comment]
Except for the icon which we can change later, I QAed this - it appears and functions on free plan, and does not appear on a pro plan workspace. considering this as passed QA, we can update the icon later.

**Comment by GreenMachine01** [comment]
@yuval-hazaz @mulygottlieb who is going to fix the icon?
you want me to open a bug on it?
