### ISSUE TITLE
As PO - I want to improve the 'rate us' notification functionality

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6322]
![Image](https://github.com/amplication/amplication/assets/112330500/6e99ff63-4468-40ae-a5f7-1bff15748d0a)

**Overview:**
Currently, when a user clicks to rate us the notification hides after the click. We decided it's better to keep showing the notification to the user until he actively clicks to close it.

**Requirements:**
1. When a user clicks the rate us CTA we do not close the notification

**Comment by Himanxu1** [comment]
assign this to me

**Comment by kush002** [comment]
I am sorry I am new to open source I have already worked on it. Please assign it to me if you can, submitted PR already

**Comment by kush002** [comment]
@souravjain540 thanks i have already submitted my PR let me know if there is anything you want me to do

**Comment by ashutosh887** [comment]
@souravjain540 Let me work on this now if the issue still persists
