### ISSUE TITLE
🐛 Bug Report: PR fails when no changes on a service in a multiservice project

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6328]
### What happened?

In a project with more then one service, when building in amplication after changing only one service, the untouched service build fails to push with the following message

```sh
2023-06-20T15:18:30.222Z (Info) Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between main and amplication"}
```

### What you expected to happen

No PR to be created or updated for unchanged services

### How to reproduce

1. create a multi-service project (`service1` and `service2`)
2. connect the project to GitHub 
3. click build 
4. merge the PR created in GitHub 
5. make a change to `service2`
6. click build
7.  if `service1` build is executed before `service2` the git push will fail with 
```sh
2023-06-20T15:18:30.222Z (Info) Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between main and amplication"}
```

### Amplication version

v1.7.5

**Comment by overbit** [comment]
This issue might need a big change due to the fact that it will be caused by the `target` and `base` branch not having any change. 
I suggest we can deprioritise it until we received more reports of the issue. @GreenMachine01 @mulygottlieb

**Comment by yuval-hazaz** [comment]
@mulygottlieb I think this one is already fixed?

**Comment by mulygottlieb** [comment]
yes, already fixed. closing this one
