### ISSUE TITLE
Improve pull request creation performance - Part 1: improve the clone performance

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6329]
### Feature description

Currently for big monorepo repository the pull request creation takes a lot of time and it grows with the repository history.
The pr creation should take the least time as possible to avoid issues on UX, resource starvation and long kafka message processing time.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mulygottlieb** [comment]
@overbit I merged your PR (nice!) but I am leaving this as "in progress" since I believe you intend to add more PRs on this card.

**Comment by overbit** [comment]
I'm planning to add at least one for the branch recreation unless it became too complex

**Comment by levivannoort** [comment]
Sanity QA, pull-request is still being created.
