### ISSUE TITLE
As a User - I want to see the most recent state in the UI after importing a Prisma schema

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6333]
Related issue: #4290 
Related PR: #6164 

After importing a Prisma schema, the newly created entities are not visible on: 
- the pending changes - fixed by #6367 
-  in the related entity dropdown - fixed by - #6398 

We need to re-fetch in these places.

**Comment by mulygottlieb** [comment]
This only works after a page refresh, so I am re-opening this one (not a blocker for release)
