### ISSUE TITLE
Improve pull request creation performance - Part 2: improve the branch recreation performance

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6345]
### Feature description

Currently for big monorepo repository the pull request creation takes a lot of time and it grows with the repository history.
The pr creation should take the least time as possible to avoid issues on UX, resource starvation and long Kafka message processing time.

### Test instructions

1. create a new service with github attached in a pro workspace
2. run a build
3. delete the amplication branch and the PR created
4. re-run a build
5. check that is not erroring

_No response_

**Comment by overbit** [comment]
Continuation of #6329

**Comment by mulygottlieb** [comment]
Re-opening. I followed the instructions (I didn't make any changes between the first and the second build though) and got this error:
```
2023-06-29T12:38:50.555Z (Info) Starting to push changes to Github
2023-06-29T12:39:42.963Z (Info) Push changes to Github failed
2023-06-29T12:39:42.971Z (Info) On branch amplication
You are currently cherry-picking commit f3aecf7.
  (all conflicts fixed: run "git cherry-pick --continue")
  (use "git cherry-pick --skip" to skip this patch)
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

nothing to commit, working tree clean
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
```

**Comment by mulygottlieb** [comment]
The above problem also exists in production and therefore is not a regression and not related to the changes in the PRs attached to this ticket
