### ISSUE TITLE
As BA - I want to know if users created a service using our templates or an empty one

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6346]
**Overview:**
The event 'ServiceWizard_ServiceGenerated' is missing the param to indicate if the user used our templates for generating entities.
We want to add this information to improve our understanding of users who use our templates versus those who don't.
While adding this param we can also track which template the user used so we will understand the most common templates users pick

**Requirements:**
1. Add 'DB Initialization' param to the event 'ServiceWizard_ServiceGenerated'
2. The value of the 'DB Initialization' event depends on the selection of the user to use our template or start with an empty service
Values: "Empty", "Template" (In the future we might also support "Schema")
3. Add 'DB Template' param to the event 'ServiceWizard_ServiceGenerated'
4. The value of the 'DB Template' event will depend on the template the user decides to use for now we only have "Order Mgmt"

**Comment by yuval-hazaz** [comment]
@GreenMachine01 The server is unaware of the template that is used to generate the service. 
The server expects to get an optional list of entities. 
The client holds the templates and when the user select a template, the client sent the list of the entities to the server - but the knowledge about the name of the template is not passed.

To support that it requires a change which in my opinion is not helping to any business question. also we expect soon to change the behavior and use AI to generate the list etc, so maybe we can put this hold.

one thing that we can do, is to add the information about the number of entities and/ or fields that are created with the service. 

LMKWDYT

**Comment by GreenMachine01** [comment]
@yuval-hazaz in that case I would like to know two things:
1. was a template used? Yes/No
2. if Yes how many entities and how many fields in total

**Comment by mulygottlieb** [comment]
Fixed in https://github.com/amplication/amplication/pull/6525

**Comment by mulygottlieb** [comment]
QA passed:


![Image](https://github.com/amplication/amplication/assets/1912933/164e6ebd-ad97-4938-a205-1d560a5f333b)
