### ISSUE TITLE
As a maintainer - I want to improve `amplication-pull-request-service` Kafka configuration 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6350]
The scope of this issue is to review and update the  Kafka timeout related settings of `amplication-pull-request-service` in accordance with the data collected. 
The session timeout should be at least 1/3 higher of the longest PR generation time.

Live data can be observed in our **[amplication-production-data-metrics](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards/dashboard/amplication-production-data-metrics?start=PT120H&end=null)** dashboard in the production account.

**Comment by mulygottlieb** [comment]
@overbit I believe this can now be considered as done, no?

**Comment by overbit** [comment]
We changed the approach so I think we can close this now.

**Comment by overbit** [comment]
#6566
