### ISSUE TITLE
🐛 Bug Report: wrong postinstall step instructions in Angular and React todo demo docs

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6356]
### What happened?

Currently, in the Angular todos and the React todos tutorials, there is a bit about running the postinstall npm step that is not up to date related to how we generate code today.

https://docs.amplication.com/tutorials/react-todos/step-002/#step-7---run-the-backend
and
https://docs.amplication.com/tutorials/angular-todos/step-002/#step-7---run-the-backend

Should both be updated where it says:
`"postinstall": "npm i --prefix web && npm i --prefix admin-ui && npm i --prefix server"`

It should be replaced by the following:
`"postinstall": "npm i --prefix web && npm i --prefix apps/first-service-admin && npm i --prefix apps/first-service"`
While explaining that `first-service` should, of course, be replaced with the name of the service you've created in Step 1

As a side note, the entire pages are not updated to the existing UI and how the flow of creating a service is today (@GreenMachine01, perhaps you want to open another longer-term task for that)

### What you expected to happen

The instructions about the postinstall should match the reality of the folder structure that we currently generate

### How to reproduce

Follow the angular/react todos tutorial instructions

**Comment by dericksozo** [comment]
Addressing this one in [#314](https://github.com/amplication/docs/pull/314)
