### ISSUE TITLE
🐛 Bug Report: `generate local` code generates an invalid Prisma schema

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6358]
### What happened?

`generate local` code generates an invalid prisma schema:  model "User": The unique index definition refers to the unknown fields: displayName

```
 @@unique([name(sort: Desc), displayName])
  @@index([name, displayName])
```

### What you expected to happen

The generated Prisma schema should be valid

### How to reproduce

run `npx nx generate-example-input-json data-service-generator` and then `npx nx generate-local-code data-service-generator`

Then open `.amplication/generate-local-code/server/prisma/schema.prisma`

### Amplication version

1.7.6

**Comment by overbit** [comment]
TEST RESULTS  ✅
