### ISSUE TITLE
🐛 Bug Report: logger is showing only first 100 rows

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6365]
### What happened?

When the build log includes more than 100 rows per "action step" the logger displays only the first 100 rows.
This happens because the lazy-log component uses a default value 100 for a parameter called `overscanRowCount`

In usual cases, this parameter should not affect the view since lazy-log knows how to automatically display the rows based on the actual view and the current scroll position.

In our case, since we use multiple lazy-log instances in the same view (one for each step), we use auto-height, which breaks the default behavior of the component. 

So far, the DSG logs do not reach more than 100 rows, so we didn't see this issue so far - the issue was found during the work on importing DB schema, which creates more log records per operation. 

### What you expected to happen

The logger view should show all records 

### How to reproduce

Use a log with more then 100 rows 

### Amplication version

1.7.4

**Comment by abrl91** [comment]
✅


https://github.com/amplication/amplication/assets/39680385/3a88fe36-0b6b-4bef-9195-21b081743a04
