### ISSUE TITLE
Incorrect Docs: Wrong links in plugin events reference

### ISSUE THREAD

**Issue by d-sonuga** [amplication/amplication#6366]
In the docs for the Create Entity Controller Base plugin event, it is specified that the default template used for the event is here: [service template](https://github.com/amplication/amplication/tree/master/packages/data-service-generator/src/server/resource/service/service.template.ts) instead of here: [controller base template](https://github.com/amplication/amplication/tree/master/packages/data-service-generator/src/server/resource/controller/controller.template.ts).

The Create Entity Controller docs page has the same problem. It is specified that its base template is here: [service base template](https://github.com/amplication/amplication/tree/master/packages/data-service-generator/src/server/resource/service/service.base.template.ts) instead of here: [controller template](https://github.com/amplication/amplication/tree/master/packages/data-service-generator/src/server/resource/service/controllertemplate.ts).

**Comment by dericksozo** [comment]
Hey @d-sonuga, thank you for letting us know about this bug. The fix is now live on the docs site: https://docs.amplication.com/plugins/plugin-events/create-entity-controller-base/

CC: @GreenMachine01
