### ISSUE TITLE
🐛 Bug Report: How to deal with these errors.

### ISSUE THREAD

**Issue by swastkk** [amplication/amplication#6368]
### What happened?

I am facing these errors while  using command `npm run serve:server`
```
Must provide either SENDGRID_API_KEY_SECRET or SENDGRID_API_KEY_SECRET_NAME{} 
```
```
Must provide either SEGMENT_WRITE_KEY_SECRET or SEGMENT_WRITE_KEY_SECRET_NAME {}
```
Please provide solution!

### Amplication version

I am developing it on my local system.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GreenMachine01** [comment]
@swastkk please contact the support channel on Discord - https://discord.com/channels/757179260417867879/1063337571184279582
