### ISSUE TITLE
🐛 Bug Report: CI fails - heap out of memory

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6371]
### What happened?

The CI fails on the Test step with the following error

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

<img width="1096" alt="image" src="https://github.com/amplication/amplication/assets/43705455/daa04075-7465-4191-8d90-cadd4e4598bb">

### What you expected to happen

CI should complete successfully 

### How to reproduce

Run the CI on this GitHub Action

https://github.com/amplication/amplication/actions/runs/5364818371/jobs/9733241632?pr=6164

### Amplication version

1.7.6

**Comment by overbit** [comment]
Reviewed https://github.com/amplication/amplication/pull/6164/commits/c5341232417d0033a0cff18000d4b7d21d803ed6
