### ISSUE TITLE
As PO - I want to improve the display of completed roadmap items on the website

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6382]
![Image](https://github.com/amplication/amplication/assets/112330500/1838e14c-1bbf-4ed4-a9d3-1eefae2a04da)

**Overview:**
In the roadmap we show on the website we have items that were not completed showing up above items marked down as completed. For consistency and easier digestion of the roadmap status we want completed items to show above open items within each category

**Requirements:**
1. Sort the items within each category in the roadmap so that completed items show up above the open(remaining) items

**Comment by kush002** [comment]
Please assign this to me @GreenMachine01 @souravjain540

**Comment by kush002** [comment]
I have Submitted PR for this. Please Look into it and let me know if you have something for me, thanks.

**Comment by GreenMachine01** [comment]
@ashutosh887 The item was already completed. thanks!

**Comment by ashutosh887** [comment]
You reopened it 😅 
No worries @GreenMachine01
