### ISSUE TITLE
Delete Button Required in Workspace

### ISSUE THREAD

**Issue by kush002** [amplication/amplication#6407]
### Feature description

**Feature Required**: Current version do not have delete button to remove workspace which looks like this..

![current](https://github.com/amplication/amplication/assets/16662383/80b552d0-d205-4c9f-8943-154d769cc33f)

It must have this button featured 

### Use case

User must have this option to empty the workspace, should look like this with functionality...

![Requested](https://github.com/amplication/amplication/assets/16662383/ee670809-e4ff-410d-ad7d-d1adfbd21056)

### Are you willing to submit PR?

Yes

**Comment by GreenMachine01** [comment]
@kush002 - Thanks! we already have this request here - https://github.com/amplication/amplication/issues/1900
