### ISSUE TITLE
🐛 Bug Report: the settings of the of the plugins are not able to be saved

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#6416]
### What happened?

When trying to save the settings of a plugin on any of the environments you get the error below:

![image](https://github.com/amplication/amplication/assets/73097785/4d91cdc6-b82a-4af9-83c1-84474367c25a)

### What you expected to happen

That the changes I made to the plugin settings will be saved

### How to reproduce

Change settings in an instaleld plugin and save

### Amplication version

1.7.6

**Comment by overbit** [comment]
TEST RESULTS
✅ 
https://jam.dev/c/5a3ffc1f-f439-4c51-af5d-9d2181f2efaf
