### ISSUE TITLE
🐛 Bug Report: Getting an error when changing the `id Type` on the system-field `ID`

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6426]
### What happened?

When changing the `id Type` dropdown for the `ID` field, you get an error (returned from the server):
![image](https://github.com/amplication/amplication/assets/1912933/f9f676c8-170a-463e-8300-d3a2cfad57bb)

Change it and then:
![image](https://github.com/amplication/amplication/assets/1912933/a66fd550-2e9b-469d-8270-037103ffe69d)

### What you expected to happen

Users should be able to update the `id Type`

### How to reproduce

Try to change the `id Type` dropdown on the `ID` field

### Amplication version

1.7.6

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by overbit** [comment]
## Test Results

✅  Successfully changed Id type of few entities
