### ISSUE TITLE
Increase Kafka message max bytes for big messages

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6446]
Related issue: #5431 

When importing Prisma schema, we could get message greater than 1MB, which is the default value for Kafka messages:
https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#message-max-bytes

We need to increase that value as well as the `maxBytesPerPartition` in the consumer option of the NestJS Kafka configuration
https://kafka.js.org/docs/consuming#a-name-options-a-options
![image](https://github.com/amplication/amplication/assets/39680385/9a83a799-b8d3-484f-b9cf-c401596ce78d)

The intention is to increase the allowance to 10MB being a good compromise between easiness of the change and performance impact across the platform.

**Comment by mulygottlieb** [comment]
@levivannoort @abrl91  just note that this issue is closed, yet the actual merge was only done on Sandbox. We need to keep it here until we apply the change on staging and prod as well.
