### ISSUE TITLE
🐛 Bug Report: in some occasions, build fails to push to github on pro plan

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6451]
### What happened?

In some occasions, like in for the following repository, amplication build fails to push to github due to a failure in the PR process.
https://github.com/mulygottlieb/amplicationdevtesting1

From an initial investigation, it seems to be related to the `amplication` branch recreation process that fails when the defaul branch contains empty commits authored by the amplication[bot]. This was an old issue that is now solved but it still prevent the successful  branch recreation.

### What you expected to happen

NA

### How to reproduce

![MicrosoftTeams-image](https://github.com/amplication/amplication/assets/2861984/bbd74a5d-23ac-4a74-9f06-ac8590566b47)

**Comment by abrl91** [comment]
Passed QA ✅ 


![Image](https://github.com/amplication/amplication/assets/39680385/edf3a32c-64fb-428f-bfe9-9087c2dc0a51)
