### ISSUE TITLE
As User - I want to know I get 2 months free upgrade to pro when I see the "passed plan limits notification" pop-up

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6458]
**Overview:**
We aim to improve the user experience and conversion rates for users who have exceeded the limits of the free plan. Currently, users receive a notification when they try to build and their workspace exceeds the free plan limits. We want to update the notification's Call-To-Action (CTA) with a promotional offer that encourages users to upgrade to the Pro Plan by offering them two months free.

**Requirements:**
1. Update the CTA design and text according to the design in Figma

![Image](https://github.com/amplication/amplication/assets/112330500/c1eec66f-8e85-4cd2-9b54-872fa69fab55)

**Figma** - https://www.figma.com/file/d5DTMR3KzcKLgZbMraoXrs/Coupon-pop-up?type=design&node-id=3137%3A9014&mode=design&t=fltE4WJcKaXBGkhq-1

**Comment by abhiraj-ku** [comment]
Hey, @GreenMachine01 please allow the access to Figma file so that contributors like me can have a look and hopefully contribute to it. Thank You
