### ISSUE TITLE
🐛 Bug Report: Plugins page sometimes crashes (empty page loads) due to a race-condition

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6459]
### What happened?

Sometimes when you try to open the "Plugins" menu item on a service, you get an empty page and an error in the console about trying to access the properties of an `undefined` object.

This is due to a race condition between `useMemo` and `useQuery` - The `useMemo` is dependent on the query but when the query did not yet run, it should account for the fact that the returned object from the query can be `undefined`

### What you expected to happen

Plugins page should load with no errors

### How to reproduce

Open the plugins menu item on a service. 
Since this is a race condition, it's not always happening so it takes a few attempts.

### Amplication version

1.7.7

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by overbit** [comment]
## Test results

🟥  unfortunately it does still happen
https://jam.dev/c/7f88b9d1-ea0b-4f5c-8782-8702c17914b4
