### ISSUE TITLE
Document the import DB schema

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6478]
Related issue: https://github.com/amplication/docs/issues/292

Write a Notion page describing:
- the preparation steps: all modifications on models, fields, data types, etc.
- the conversions - from Prisma data type to amplicaton data types and objects
- the limitations, edge cases, and how we deal with them (composed id field, enums with map, datasource name)

**Comment by abrl91** [comment]
https://www.notion.so/amplication/Import-DB-Schema-f6dbee2a515547628b312c8169b56d2b?pvs=4

**Comment by abhinav2712** [comment]
@abrl91 Are you working on this issue?

**Comment by lalitkumawat1m** [comment]
Hey @abrl91,
Do you need any help?
would love to fix this

**Comment by abrl91** [comment]
Thank you @lalitkumawat1m 
I already did it. We just forgot to close the issue.
