### ISSUE TITLE
As a user - I want to get extra information and hints about the fields I am editing on screen

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6524]
### Feature description

Some fields are not straightforward and require some knowledge from the user in order to edit them.
We need a bult-in and easy way to show the user with tooltips about the fields they are editing

<img width="855" alt="image" src="https://github.com/amplication/amplication/assets/43705455/9ff786c9-2e34-40cf-aef8-c1f2aeff07f5">

**Comment by harshit-senpai** [comment]
hey, @yuval-hazaz as a full stack dev I would love to work on it.

**Comment by mulygottlieb** [comment]
@yuval-hazaz the tooltip is showing for the custom prisma attributes but not for the plural display name - do you want to take a look?

**Comment by mulygottlieb** [comment]
It seems that the "plural display name" was just an example, and the main targets of this ticket are:
1. The frontend "infra" to support hints
2. Putting a hint on the custom prisma attributes
Both of those items are verified, therefore this passed QA
