### ISSUE TITLE
🐛 Bug Report: The relations in the order template service are set in an incorrect way

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6557]
### What happened?

The relation between order and product should be one-to-many

![image](https://github.com/amplication/amplication/assets/39680385/05dbb55e-8e89-4f04-ba1b-f4ced28fd4a3)

same for customer and orders

![image](https://github.com/amplication/amplication/assets/39680385/b7b31859-5406-4467-86b0-2b0519fc1d1c)

### What you expected to happen

The relations should be one-to-many 

### How to reproduce

Create a service from a template

### Amplication version

1.8.0

**Comment by mulygottlieb** [comment]
This seems to have fixed the relation between customers and orders, but the relation between orders and products is still 1:1


![Image](https://github.com/amplication/amplication/assets/1912933/a44153ee-91ec-4531-b30c-120ca440b887)


Re-opening

**Comment by abrl91** [comment]
this is exactly as it was before, I have an old service in prod

12 months ago
![image](https://github.com/amplication/amplication/assets/39680385/3d6b362e-e8c7-4d89-b1be-425d1ea5fe83)

![image](https://github.com/amplication/amplication/assets/39680385/fdc1309b-9acc-4ec7-969f-0145120d4c6b)

![image](https://github.com/amplication/amplication/assets/39680385/90c2df2d-2f2b-4525-aaeb-7e7f7859ce9a)
