### ISSUE TITLE
Custom attributes are not allowed on relation fields

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6581]
We need to make sure that we are not adding custom attributes to relation fields
![image](https://github.com/amplication/amplication/assets/39680385/5c2ca7d7-265f-4404-9a3b-2165cb456ee8)

**Comment by morhag90** [comment]
Passed QA:

configuration:

<img width="1279" alt="image" src="https://github.com/amplication/amplication/assets/97830649/449e9729-f005-4a1e-bb9c-33f2b2286b1b">

schema results: 

<img width="649" alt="image" src="https://github.com/amplication/amplication/assets/97830649/7a3c7c0e-c9ef-4c71-8db3-eb7a8b114f16">
