### ISSUE TITLE
🐛 Bug Report: After service creation, immediate discard of pending changes results in errors later in the service page or service settings page

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6587]
After completing the service creation wizard, if you immediately discard all pending changes, you also discard the service settings, and then you get an error when browsing to the service page or the service settings page (the client tries to fetch service settings from the server, the server fails because the settings were deleted).

**Comment by morhag90** [comment]
Passed QA:


https://github.com/amplication/amplication/assets/97830649/d19eef18-807f-4c98-857e-5b17b483b3ea
