### ISSUE TITLE
🐛 Bug Report - (Typo) missing "up" text in the limit notification

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6589]
On the entitles page...

**Actual:**
"With the current plan, you can use to 7 entities per service. Upgrade now"

**Expected:**
"With the current plan, you can use up to 7 entities per service. Upgrade now"

**Comment by ArslanYM** [comment]
Is this fixed?

**Comment by GreenMachine01** [comment]
@ArslanYM yes, it was already fixed internally. thanks for the help!

**Comment by abrl91** [comment]
✅



![Image](https://github.com/amplication/amplication/assets/39680385/00d76398-714f-426b-a363-ca7bac716816)
