### ISSUE TITLE
As PO - I want to update the generic Git icon

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6592]
**Current Icon:**

![Image](https://github.com/amplication/amplication/assets/112330500/89e6e98a-f3ee-4d50-9d42-c1a2672a51fe)

**New Icon:**

![Image](https://github.com/amplication/amplication/assets/112330500/742b39a2-ffdb-44bd-9ad4-15272c3a8c99)

**Art Instructions:**

![Image](https://github.com/amplication/amplication/assets/112330500/ee39e128-b83e-46cd-8a8e-64c0efceacea)

**Places where the icon is used:**

![Image](https://github.com/amplication/amplication/assets/112330500/39b64eb7-2dda-49f9-8fba-1c8a33196b02)

![Image](https://github.com/amplication/amplication/assets/112330500/c388e975-311f-4016-871c-603cf3419712)

![Image](https://github.com/amplication/amplication/assets/112330500/b6e31735-85a8-4d0a-96bc-aa38083ecefa)

**Comment by ArslanYM** [comment]
Can I work on this?

**Comment by GreenMachine01** [comment]
@ArslanYM assigned to you. good luck!
@souravjain540 FYI.

**Comment by ArslanYM** [comment]
@GreenMachine01 This change is required in the app or the website?

**Comment by GreenMachine01** [comment]
@ArslanYM within the app.

**Comment by santoshy1101** [comment]
can tell me if this bug solves it or not, if it is not solved can you assign me.

**Comment by ArslanYM** [comment]
Thanks, Ill do that.

**Comment by martinez-hugo** [comment]
Hello ! Does this issue is available to work on it ?

**Comment by souravjain540** [comment]
@martinez-hugo assigned :)

**Comment by ashkaaar** [comment]
hey, If no one is working on it, I tried to solve this.
please review @souravjain540 @GreenMachine01

**Comment by pranavkangale5** [comment]
i can fix this if no one has fixed it ! @souravjain540  @GreenMachine01

**Comment by martinez-hugo** [comment]
So @GreenMachine01 this issue is good ? Or there are some other places where we need to change this icon ?

**Comment by GreenMachine01** [comment]
@pranavkangale5 @martinez-hugo. This item has been completed. thanks!
