### ISSUE TITLE
⭐️ Plugin: ESLint

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6605]
### Feature description

This request is for a new plugin that will bring ESLint to the generated solution. 
This plugin will need to leverage the plugin settings to allow users to defined their custom eslint configurations 

**Icon:**
![Image](https://github.com/amplication/amplication/assets/112330500/74336614-5c87-4100-80b6-c431ab8fe6d7)

**Comment by overbit** [comment]
Replace #1703

**Comment by overbit** [comment]
@Shurtu-gal please reply here so I can assign this issue to you

**Comment by Shurtu-gal** [comment]
Hey @overbit!!

**Comment by overbit** [comment]
The initial version doesn't seems to play nicely with the current generate code. 
Can we:
1. check if a different version of eslint supports TS 4.2.3 (used in the generated code)
2. update the default settings to default eslint one i.e. `rules: {}`
