### ISSUE TITLE
🐛 Bug: client ERD component is running too many getEntity queries

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6611]
The ERD component is executing getEntity queries multiple times when it's rendered instead of on generation only.

An example of the issue is visible here (in the network tab)
https://jam.dev/c/1c48cf7f-1dc2-489e-9517-344630919156

**Comment by overbit** [comment]
@mohammed-bahumaish this is the issue related to your previous PR

**Comment by mohammed-bahumaish** [comment]
Hey @overbit , 

I think the queries are triggered because of query pooling in `/packages/amplication-client/src/Entity/EntityList.tsx component`,  not in `packages/amplication-client/src/Entity/EntityERD/EntitiesERD.tsx`

which is the expected behavior i guess?  Let me know what you think.

**Comment by mohammed-bahumaish** [comment]
@overbit Any updates? Is it a feature or a bug? 😅

**Comment by overbit** [comment]
@mohammed-bahumaish we are going to leave as it is for now, potentially increasing the polling time to 60s instead.
