### ISSUE TITLE
Supporting BigInt and Decimal as data types in Amplication and the generated app

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6618]
## Current behavior:
DecimalNumber is translated to `Float` in the generated Prisma schema
WholeNumber is translated to `Int` in the generated Prisma schema

## Desired behavior:
DecimalNumber should be translated by default to `Decimal` in the generated Prisma schema
WholeNumber is translated by default to `Int` in the generated Prisma schema

We should add BigInt and Decimal to the json options of DecimalNumber and WholeNumber

**Comment by santoshy1101** [comment]
I want to work on this issue can you assign me?

**Comment by yuval-hazaz** [comment]
@santoshy1101 we are still investigating this issue to determine how we want to handle it, so for now it is not open for the community. 
Thanks!
