### ISSUE TITLE
As User - I want the Amplication branch to be created from the *latest* amplication commit on the base branch

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6647]
In order to reduce the time taken by amplication to create a pull request whilst avoid a user to resolve the same merge-conflicts over and over, when the `amplication` branch is deleted, we should recreated it from the most recent commit in the base branch.

**Comment by overbit** [comment]
Possible scenario to test:

1. create build
2. in code: inject a new service to an exsting service (like a loggerService)
3. merge
4. add auth plugin
5. in code: change .env value for postgres 
6. build
7. solve conflicts
8. merge
9. add new plugin kafka 
10. merge
