### ISSUE TITLE
🐛 Bug Report: Adding Auth to an unauthenticated service fails

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6661]
### What happened?

https://jam.dev/c/ccfcc133-4e61-40e9-b538-781af7b1e3d2

### What you expected to happen

to work

### How to reproduce

1. Create a new service without any authentication (Skip authentication)
2. Build
3. Add Auth Core plugin
4. Observe that doesn't look like installed
5. Open the installed plugin page see the 🟦  screen of death
6. Impossible to recover, the only option is to delete and recreate the service with auth 

### Amplication version

v1.8.5

**Comment by Meyazhagan** [comment]
@overbit I would like to work on this issue, can you assign to me?

**Comment by overbit** [comment]
Sure, assigned to you.

**Comment by morhag90** [comment]
Passed QA:



![Image](https://github.com/amplication/amplication/assets/97830649/a2b15239-d8b5-4bf4-be9c-b4811d80b07d)




![Image](https://github.com/amplication/amplication/assets/97830649/4c12ec03-9431-4580-abd3-29943239400e)
