### ISSUE TITLE
As User - I want to be able to edit the entity via the ERD

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6683]
1. We need to add a pencil icon to each entity
2. clicking the pencil icon opens the entity page
3. exiting the entity back to view all entities should keep the ERD view

Design example in the comments.

**Comment by Sheersendu** [comment]
I would like to work on this issue. It will be my very first contribution. Can it be kindly be assigned to me @GreenMachine01?

**Comment by GreenMachine01** [comment]
@souravjain540  FYI

**Comment by GreenMachine01** [comment]
@Sheersendu assigned to you. good luck.
@alexbass86 please provide the pencil icon and a design example.

**Comment by Sheersendu** [comment]
Thanks @GreenMachine01 for assigning it to me 😄

**Comment by Sheersendu** [comment]
Hi, @alexbass86  can you kindly provide the pencil icon? Thanks!

**Comment by Sheersendu** [comment]
@GreenMachine01 PR is created and up for review😄. I've followed steps as mentioned in CONTRIBUTING.md .

**Comment by alexbass86** [comment]
@Sheersendu 
Hello, please use this design for the edit icon, If you can on the way to update the font size would be more than welcome :)
thank you so much for your contribution.

**Figma Link:** 
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?type=design&node-id=2123%3A2547&mode=design&t=OiFt1X6bzx9vHVWM-1

**Comment by Sheersendu** [comment]
@alexbass86 your comment was deleted. What should be my next steps kindly let me know @GreenMachine01 or @alexbass86.

**Comment by GreenMachine01** [comment]
@Sheersendu sorry about that. we need to sync internally and we will get back to you.

**Comment by alexbass86** [comment]
> @alexbass86 your comment was deleted. What should be my next steps kindly let me know @GreenMachine01 or @alexbass86.

please use this design, https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?type=design&node-id=2123%3A2547&mode=design&t=T3TyF3nHKCFGQ5NR-1
thanks for your contribution

**Comment by Sheersendu** [comment]
@GreenMachine01 updated according to figma. Kindly review it.

**Comment by GreenMachine01** [comment]
@Sheersendu Thanks! the team will review it.

**Comment by Sheersendu** [comment]
Hey @GreenMachine01, whats the update on this issue, its still pending for review it seems. Its been along time hence wanted to check upon. Happy to make any required changes! 😄

**Comment by GreenMachine01** [comment]
@Sheersendu thanks for the reminder. ill check with the team whats going on.

**Comment by levivannoort** [comment]
QA: 

![Image](https://github.com/amplication/amplication/assets/73097785/b2053033-1d81-4bc1-8139-b0996e924ccb)

**Comment by Sheersendu** [comment]
Hi @levivannoort, can you kindly provide some context like whether QA has Passed/ Failed(reason if so) so that I can work on it if necessary. Thanks!

**Comment by levivannoort** [comment]
@Sheersendu to be clear the QA passed & should be shipped with the next release, which will probably be today!
