### ISSUE TITLE
DB schema import - issue with model names that contains acronyms

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6688]
For example: model name `myDBName` will be formatted to `MyDBName` in the current implementation, but the generated Amplication Prisma client expects to `myDbName` so the desired result should be `MyDbName`

**Comment by morhag90** [comment]
Passed QA:

<img width="517" alt="image" src="https://github.com/amplication/amplication/assets/97830649/af0f5cf9-78dd-44a7-b38a-1316406d7710">
