### ISSUE TITLE
🐛 Bug Report: Bitbucket access token is not refreshed after it expires

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6693]
We had a user using Bitbucket that got errors during the 'push changes to Bitbucket' step

![Image](https://github.com/amplication/amplication/assets/112330500/a7d6cb21-1e3a-470b-a921-7239f00fc3df)

after investigation, we found the issue is related to the expiration of the token used with BitBucket.

**Expected:**
1. Token is refreshed if needed to allow seamless commits to Bitbucket.

**Comment by mulygottlieb** [comment]
Passed QA (log line #10):


![Image](https://github.com/amplication/amplication/assets/1912933/a6fa8f45-2d06-47d3-ba7e-48c1edb1dfed)
