### ISSUE TITLE
As PO - I want to support Mongo with the DB schema import feature

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6694]
Need to check if we can also support Mongo DB with the Prisma schema import feature.
if not why cant we support it currently?
if yes, what do we need to do to support it? what is the effort?

**Comment by overbit** [comment]
We could, but we will need to fix some bugs first.

**Comment by overbit** [comment]
@abrl91 @GreenMachine01 This issue is not matching the PR attached to it. Please update the description accordingly
