### ISSUE TITLE
🐛 Bug Report: Package `npm-run-all` is not longer required

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#6705]
### What happened?

The code generates with `npm-run-all` package in the `package.json` file.
This package is no longer required or used in the generated code.

### What you expected to happen

Remove the unused package.

### How to reproduce

Generate any service with Amplication.

### Amplication version

latest

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by overbit** [comment]
`npm-run-all` is need in order to run `run-s` commanss
