### ISSUE TITLE
⭐️ Plugin: ESLint support for prettier

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6709]
### Feature description

Add a new plugin setting to support the coexistence of the prettier plugin and eslint plugin (https://prettier.io/docs/en/integrating-with-linters.html). 
   i.e. when the configuration is similar to the following, the generated code will include [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) dependency too.
```json
{
 "settings":
 {
   "formatter": "prettier"
 }
}
```

**Comment by overbit** [comment]
@Shurtu-gal, I've updated the other issue and created this one to allow users to use both plugins.
Are you happy to pick this one up, once you finished with the prettier update?

**Comment by Shurtu-gal** [comment]
@overbit This functionality is also included in the same PR https://github.com/amplication/plugins/pull/143. I will test these along with the ESlint ones in a separate PR.

**Comment by abrl91** [comment]
passed QA ✅ 

An issue about the indentation and spaces will be opened



![Image](https://github.com/amplication/amplication/assets/39680385/5cbeb696-b47f-4d52-a4ee-d700b3e7e06c)
