### ISSUE TITLE
As User - I want to get a clear error message when trying to import a schema with an entity that already exists in the service

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6716]
**Current error text** - "(Error) Entity "[entity name]" already exists"

**New error text** - "(Error) Entity "[entity name]" already exists in the service. To proceed with the import, please rename or remove the entity in your schema file or remove the conflicting entity from the service."

**Comment by shaikfareed46** [comment]
I can take up this one

**Comment by shaikfareed46** [comment]
Here is the PR https://github.com/amplication/amplication/pull/6717

**Comment by abrl91** [comment]
passed QA ✅ 


![Image](https://github.com/amplication/amplication/assets/39680385/08bea798-86e2-4a9e-bdb4-3b3cf3acb607)
