### ISSUE TITLE
🐛 Bug Report: Sometimes its possible to delete the entity used for authentication

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6727]
![Image](https://github.com/amplication/amplication/assets/112330500/d5cc3dfc-2056-4cf5-ab06-5a749c9b7f17)

![Image](https://github.com/amplication/amplication/assets/112330500/44a9fe61-80a4-42ef-aa26-72de0e689080)

**Steps to reproduce:**
Unknown. it happenes on old services.

**Comment by mulygottlieb** [comment]
I assume that "old" services that pre-existed before the changes to allow deletion of user entity and/or before the changes that allowed to select a user entity might have some of the validation done wrongly compared to services that were created already after these changes.

**Comment by abrl91** [comment]
Passed QA ✅ 

![Image](https://github.com/amplication/amplication/assets/39680385/85408005-c70c-4425-9d7e-0e39c628369a)

**Comment by GreenMachine01** [comment]
@abrl91 the trash icon should be disabled
![image](https://github.com/amplication/amplication/assets/112330500/e52d2597-582e-4859-bd4e-0e730730f4af)

**Comment by abrl91** [comment]
@GreenMachine01 I understand the point, but this is not what I have asked to test. This is the decision that was made to handle this bug.
