### ISSUE TITLE
🐛 Bug Report: Importing a schema with a self-referencing field is not imported correctly.

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6732]
### What happened?

Importing a schema with a self-referencing field is not imported correctly.
The import completes successfully, but the build process fails, and when viewing the field settings the UI crashes 

### What you expected to happen

The import should create the field correctly

### How to reproduce

use this example schema 

```
datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}

generator client {
    provider = "prisma-client-js"
}

model Post {
    id        Int      @id @default(autoincrement())
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
    published Boolean  @default(false)
    title     String   @db.VarChar(255)
    authorId  Int?
    parentId  Int?
    parent    Post?    @relation("organization", fields: [parentId], references: [id], onDelete: Cascade)
    children  Post[]   @relation("organization")
}
```

after import - click on "Commit" and you will see this build log 
<img width="969" alt="image" src="https://github.com/amplication/amplication/assets/43705455/27beca50-f433-4023-8c27-bdc97b99c501">

also, go to the entity page, and click on the field "Parent" and the UI will crash

### Amplication version

1.8.6

**Comment by mulygottlieb** [comment]
QA passed:
![image](https://github.com/amplication/amplication/assets/1912933/01eea5d2-1711-4948-a1bc-d8f45ef1606b)

![image](https://github.com/amplication/amplication/assets/1912933/511e8857-5460-4826-9863-9b3930d6b093)
