### ISSUE TITLE
Dependencies in generated code should be ordered alphabetically 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6740]
### Feature description

At the moment, when any plugin add a new dependency, the final generated code contains an un-ordered set of dependencies and devDependencies in package.json. 
This behaviour will increase the number of merge conflicts since git is comparing lines.

To avoid additional issues in the git sync and keep a more understandable configuration, the list of dep and devDep must be ordered alphabetically

Example of merge conflict
<img width="1031" alt="image" src="https://github.com/amplication/amplication/assets/2861984/0742c0e3-4943-4487-a3d4-ddc80f94b021">

**Comment by Naman-sharma00100** [comment]
Hey @overbit I am trying to reproduce this in my local maybe I will be done with this today only, can we connect later for discussing this....

**Comment by Naman-sharma00100** [comment]
Can you assign me this

**Comment by Akash02032002** [comment]
Can you please assign me this issue for Hacktoberfest contribution.

**Comment by capedCrusaderr** [comment]
if anyone is not working on this issue , can I give it a try?

**Comment by Meyazhagan** [comment]
@overbit I would like to work on this issue. Can you assign me.

**Comment by martinez-hugo** [comment]
Hi ! Can I work on this issue ?
