### ISSUE TITLE
🐛 Bug Report: ERD view is not showing properly the entities after updates such as deletion or schema import

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6741]
**Scenario1**
1. Create a service with a few entities
2. view the entities in the ERD view
3. delete one of the entities
4. return to the ERD view

**Expected:**
The ERD is updated to show all previous entities without the one that was deleted

**Actual:**
ERD view shows an empty canvas. only after a refresh it shows properly the entities in the service

**Scenario2**
1. Create a service with a few entities
2. view the entities in the ERD view
3. Add more entities via the import schema feature
4. return to the ERD view

**Expected:**
The ERD is updated to show all previous entities + all the new entities that were added by the schema import

**Actual:**
ERD view shows only the previous entities. only after a refresh it shows properly all the entities in the service

**Comment by GreenMachine01** [comment]
@mohammed-bahumaish wanna take it?

**Comment by mohammed-bahumaish** [comment]
@GreenMachine01 Yeah sure, I'll take it.

**Comment by GreenMachine01** [comment]
@mohammed-bahumaish amazing. assigned to you. good luck!

**Comment by mohammed-bahumaish** [comment]
@GreenMachine01 Please check my PR.
