### ISSUE TITLE
🐛 Bug Report: Build process fails with "Failed to execute plugin event CreateServer. Invalid name: " ". Name must start with a letter and can contain only letters, numbers and underscores"

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6759]

**Comment by abrl91** [comment]
Passed QA ✅ 


![Image](https://github.com/amplication/amplication/assets/39680385/14a38712-5a34-418d-88cf-d03ba32272cc)


![Image](https://github.com/amplication/amplication/assets/39680385/03512067-7c20-43cf-b666-e3f97a5f1781)
