### ISSUE TITLE
Client: Entities Circular Reference

### ISSUE THREAD

**Issue by alonram** [amplication/amplication#676]
If table A is related to table B, user should not be allowed to relate table B to table A.
![Screenshot (8)](https://user-images.githubusercontent.com/40050499/97025214-c2bbe880-1525-11eb-8430-84d2f7ea9439.png)
![Screenshot (9)](https://user-images.githubusercontent.com/40050499/97025218-c3547f00-1525-11eb-8b6b-c18f60b906e9.png)

**Comment by yuval-hazaz** [comment]
@alonram, although it is not always the best practice still there is no reason to prevent circular reference.

There may be many business cases where this behavior is required.
Just one simple example would be a team may have multiple members,   while one of the members is the team lead.
This can be described with entity user which reference team and entity team which reference the user table.

There may be several other rules which need to be enforced in circular references (e.g. at least one side must not be required, or instead allowing to create both in a single transaction). These rules will be listed and thought of in one of the next sprints before MVP
