### ISSUE TITLE
🐛 Bug Report: Wrong DB written on the dashboard

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#6766]
### What happened?

When I select "MongoDB" instead of "PostgreSQL"in the service wizard, I should see the same DB in the service dashboard as well not "Postgresql"
<img width="1465" alt="Screenshot 2023-08-29 at 12 26 51 PM" src="https://github.com/amplication/amplication/assets/53312820/033d1dcc-2061-4997-b104-bb1730dbde8b">

### What you expected to happen

show correct db in the service dashboard

### How to reproduce

just build a service using MongoDB in the database

**Comment by Sheersendu** [comment]
I would like to work on this issue, can it be assigned to me please?

**Comment by GreenMachine01** [comment]
I think it will be merged.
@Sheersendu assigned to you.

**Comment by Sheersendu** [comment]
Hey @GreenMachine01 , as per my investigation, all the data displayed are hard-coded, so need to a couple of things to be implemented hence the tag for this issue should be Feature instead of Bug :)

**Comment by GreenMachine01** [comment]
@barshimi are the values in the overview hardcoded?

**Comment by GreenMachine01** [comment]
@Sheersendu I see now the value of postgres is hard coded. Now I understand what you mean.
Lets put this bug on hold as we are planning a new UI soon which will make this bug not relevant.
