### ISSUE TITLE
As Dev - I want to create a new AI Service to support in the future various operations in Amplication with AI

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6796]
**Overview:**
Amplication aims to simplify the development process by automating repetitive tasks and providing a robust framework for application development. To take this to the next level, we are planning to integrate an AI service that will act as an intermediary between Amplication and various AI providers like OpenAI. This service will enable us to add a multitude of AI-powered features to Amplication in the future.

One of the key use-cases we envision is the ability for users to describe the service they want to build in natural language. The AI will then interpret this description to automatically set up all the necessary configurations and database schemas, thereby significantly reducing the time and effort required to go from idea to implementation.

**Requirements:**

AI Provider Interface:
1. The service must be able to communicate with multiple AI providers, starting with OpenAI.
2. It should be able to send requests to and receive responses from the AI providers.
3. Support for specifying the version/model of the AI provider to be used (example GPT 3.5 VS GPT 4)

Data Pass-Through:
1. The service should be capable of passing user-provided descriptions and other data directly to the AI providers without modification.
2. The service should be able to direct the AI to follow templates for the response
3. It should be able to receive and forward the processed data back to Amplication.

Error Handling:
1. The service should be able to handle errors gracefully.
2. It should provide meaningful error messages to the user in case of failure.

Security:
1. All communications with AI providers should be encrypted.
2. User data should be handled securely and in compliance with privacy regulations.
3. Implement rate-limiting and other abuse prevention mechanisms to protect against malicious use or hacking attempts.

Usage Tracking:
1. The service should log usage metrics such as the number of requests made, types of requests, volume of data processed, and any errors or failures.
2. These logs should be securely stored and easily accessible for analysis.

Simple Testing Interface:
1. A basic interface should be developed for internal testing purposes to send and receive messages from AI providers.

**Non-Functional Requirements:**

Scalability:
1. The service should be designed to handle a growing number of users and AI features.

Performance:
1. The service should be optimized for speed to provide a seamless user experience.

Extensibility:
1. The architecture should be modular to easily allow the addition of more AI providers and features in the future.

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/c5335d0e-43f2-4e83-b58a-f8ac0231059e)
