### ISSUE TITLE
As User - I want to know how to use the DB import feature

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6826]
------------------------------------------------------------------------------------------------------------------------------------
**Important Note for Developers:**

Please ensure that any fixes related to this issue are made against the new UI. This updated UI can be found in the 'Next' branch. Do not apply fixes to the old UI. If you have any questions or need further clarification, please reach out.

Thank you for your attention to this matter.

------------------------------------------------------------------------------------------------------------------------------------

**Overview:**
We have the new DB schema import feature. This new capability requires some understanding by the user in order to use properly and minimize issues. We want to help users to know more about the feature by sending them to read the docs.

![Image](https://github.com/amplication/amplication/assets/112330500/ac28073d-3b3f-4b1d-92a6-df7bde811ac2)

**Requirements:**
1. Add the instruction text with link to the docs below the import box according to the design example
2. Clicking the "Documentation" link should open the docs in a new tab
**Text** - Need more guidance? Explore our documentation on importing Prisma schema files
**Link** - https://docs.amplication.com/how-to/import-prisma-schema/

**Figma** - https://www.figma.com/file/oHXSDAmqxMWS2RelcoVugZ/Import-DB-Scheme?type=design&node-id=3449%3A1415&mode=design&t=sjZUf6iDJxef3bqv-1
**Link for Community** - https://www.figma.com/file/gSaabsX9ijlekZZaMj4Z5C/Website---Megamenu?type=design&node-id=1%3A2190&mode=design&t=4aLcJDaZd01jQjgW-1

**Comment by GreenMachine01** [comment]
@alexbass86 please adda link to the design example the community can access

**Comment by alexbass86** [comment]
@GreenMachine01, please use this link
https://www.figma.com/file/gSaabsX9ijlekZZaMj4Z5C/Website---Megamenu?type=design&node-id=1%3A2190&mode=design&t=4aLcJDaZd01jQjgW-1

**Comment by Himanxu1** [comment]
assign this to me

**Comment by GreenMachine01** [comment]
@Himanxu1 assigned to you. good luck!
@souravjain540 FYI

**Comment by souravjain540** [comment]
@Himanxu1  are you working on it?

**Comment by theebank** [comment]
Hi @souravjain540, if he is not working on it, could I get this assigned to me?

**Comment by souravjain540** [comment]
@theebank  assigned to you

**Comment by pawpaw2022** [comment]
hi, can you assign this to me, I can finish it in 3 days

**Comment by Sukhendu2002** [comment]
Hey @souravjain540, Can I work on this issue?

**Comment by astitva0011** [comment]
assign me

**Comment by iamshabell** [comment]
@souravjain540 can you please assign it to me? already done the PR: https://github.com/amplication/amplication/pull/7001

**Comment by GreenMachine01** [comment]
------------------------------------------------------------------------------------------------------------------------------------
**Important Note for Developers:**

Please ensure that any fixes related to this issue are made against the new UI. This updated UI can be found in the 'Next' branch. Do not apply fixes to the old UI. If you have any questions or need further clarification, please reach out.

Thank you for your attention to this matter.

------------------------------------------------------------------------------------------------------------------------------------

**Comment by souravjain540** [comment]
@iamshabell are you working on the issue?

**Comment by iamshabell** [comment]
> @iamshabell are you working on the issue?

Already made a PR #7001
