### ISSUE TITLE
As a User - I'd like to see a mention of the service built in the generated PR 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6849]
### Feature description

When using a PR per service, I'd like to see PR names containing the service created to make easier to understand what is what.

Current:
![image](https://github.com/amplication/amplication/assets/2861984/b261e265-99c7-4b31-ac8f-6f45d9f319d7)

Ideal example:
![image](https://github.com/amplication/amplication/assets/2861984/ae26bb85-7e89-4e04-ad4b-7a6f89bda874)

PR naming rules:
- for unique PR created : `chore(amplication): updated generated code`
- for one PR per service: `chore(amplication): updated generated code for <serviceName>`

**Comment by mulygottlieb** [comment]
Passed QA:

![Image](https://github.com/amplication/amplication/assets/1912933/87ad3b2e-30d0-4c39-aba3-74888bb1238f)
