### ISSUE TITLE
🐞 Bug Report: the generated `jwtStrategyBase` service spec is not compiled

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6859]
`jwt.strategy.spec.ts`

The issue:
![image](https://github.com/amplication/amplication/assets/39680385/a0e9f986-1d3f-49af-a44d-eed524395545)

How to solve:
![image](https://github.com/amplication/amplication/assets/39680385/f1883740-2da6-4327-b0de-7a187066dcbe)

**Comment by GreenMachine01** [comment]
@abrl91 whats the severity of the bug?

**Comment by abrl91** [comment]
> @abrl91 whats the severity of the bug?

I think major, because the code is running but the tests fail on this

**Comment by abrl91** [comment]
passed QA ✅ 
Tested locally.
Will be published with: https://github.com/amplication/plugins/pull/254
