### ISSUE TITLE
🐞 Bug Report: MongoDB plugin generated wrong docker compose files

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6863]
How to reproduce:
- create a service with mongodb
- clone
- npm i
- npm run docker:dev
- npm run db:init

Getting the following error:
![image](https://github.com/amplication/amplication/assets/39680385/f28becab-13c5-49e0-a82e-ebfb8f2c8cce)

**Comment by morhag90** [comment]
Passed QA:



![Image](https://github.com/amplication/amplication/assets/97830649/91cc736a-0f50-4eaf-b9f7-d99696f1c1b5)
