### ISSUE TITLE
As PO - I want to update the roadmap

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6886]
**Overview:**
We need to update our roadmap as some items were already completed and new items we plan to work on are not mentioned.

![Image](https://github.com/amplication/amplication/assets/112330500/f89fb650-4132-4251-b0a4-7eb9334cca5a)

**Expected:**
![image](https://github.com/amplication/amplication/assets/112330500/55179884-2fd0-47a5-abf4-c8c536328707)

**Requirements:**
1. In the Database section mark the "ERD View" and "Connect to your own database" as completed
2. In the Database section add a new item "Import schema from existing database" and mark it as completed
3. In the Database section add a new item "MS SQL" **and mark it as completed.**
4. In the Git section mark the "Multiple branches" as completed and move it to be above the GitLab item
5. In the Framework section mark "Other transports" as completed
6. In the Microservices mark "Monitoring & observability" as completed and move it to be above the Logging item
7. In the API section add a new item "Custom actions"
8. In the API section add a new item "Custom types"
9. In the API section add a new item "API gateway"
10. In the Microservices section add a new item "Storage resource"
11. In the Microservices section add a new item "Central auth resource"
12. In the Microservices section add a new item "Service without database"
13. In the Framework section add a new item "Multi tenancy"
14. In the Framework section add a new item "Serverless"

**Comment by outlivo** [comment]
Hi @GreenMachine01, I would like to work on this issue.

**Comment by GreenMachine01** [comment]
@outlivo I need to finish all requirements for the item and then the community can take it. please sync on this with @souravjain540

**Comment by astitva0011** [comment]
assign me

**Comment by souravjain540** [comment]
@outlivo @astitva0011 please take another issue, somebody just submitted a PR already :/

**Comment by StyleShit** [comment]
Assign me
