### ISSUE TITLE
As a User - I want to get generated code with the latest version of Nestjs and relevant dependencies

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6916]
### Feature description

Currently, all amplication generated code is based on dependencies that are outdated. In particular, it is produced with Nestjs v8 that is 2 major version behind.
I'd like to get amplication new builds to produce code that runs Nestjs v10, with all relevant dependencies updated too.

### Use case

Reduce effort need to migrate applications to new nestjs framework, and introduce the latest security and code fixes.

**Comment by overbit** [comment]
Check this to understand the work needed to achieve this upgrade: https://github.com/yuval-tets2/packages/commits/main

**Comment by overbit** [comment]
Tech comments:

https://github.com/yuval-tets2/packages/commit/2d2c20a1be2d0824cf69bd8fa15a020659d2483d 
This will require to find a solution for plugin-codeGenerator version linking since the auth core plugin is in charge of supporting generating ACL related code

**Comment by overbit** [comment]
Blocked by https://github.com/amplication/amplication/discussions/7139

**Comment by overbit** [comment]
Current plugins usage:

|Plugin name  |Services active in production that use the plugin  |
|--|--|
|@amplication/plugin-cache-redis|75|
|@amplication/plugin-broker-redis|13|
|@amplication/plugin-broker-kafka|323|
|@amplication/plugin-broker-rabbitmq|0|
|@amplication/plugin-transport-grpc|0|
|@amplication/plugin-observability-opentelemetry|38|

**Comment by morhag90** [comment]
Passed QA:

<img width="1328" alt="image" src="https://github.com/amplication/amplication/assets/97830649/aaadd45c-76db-4b7c-9118-f4d8fe9827a6">
