### ISSUE TITLE
As a maintainer - I want to fix the `Build.ts` file by adding the `{     nullable: boolean   }` options to the GraphQL `@Field` decorator

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6922]
In the `Build.ts` file we need to add  `{  nullable: true  }` / `{  nullable: false  }` to the GraphQL `@Field` decorator to make the GraphQL know if the field is nullable or not

**Comment by DanielLai20** [comment]
Done, PR submitted

**Comment by souravjain540** [comment]
> Done, PR submitted

I am sorry but we will not accept any PR if you are working on it without getting it assigned to you.

**Comment by DanielLai20** [comment]
Oh, I wasn't aware of this. How do I get an issue assigned?

**Comment by levivannoort** [comment]
Assigned to @DanielLai20
