### ISSUE TITLE
🐛 Bug Report: the import schema status should not be "completed successfully" when the process had errors

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6935]
### What happened?

when there are errors in the import schema process, the status should not be "success" 

<img width="659" alt="image" src="https://github.com/amplication/amplication/assets/43705455/c07d4c81-a890-42cc-8671-9b2f3204913e">

### What you expected to happen

The status should be "failed", and the last message should be "Import operation completed with errors."

### How to reproduce

Import a file  with errors

### Amplication version

1.8.11

**Comment by iamshabell** [comment]
Hey, can I work on this issue?

**Comment by morhag90** [comment]
Currently, there is no easy or known way to test this issue.
I approved it now and we will watch the status on production.
@abrl91 @mulygottlieb

**Comment by morhag90** [comment]
@abrl91 @mulygottlieb  :

<img width="1370" alt="image" src="https://github.com/amplication/amplication/assets/97830649/709ba976-6de2-4337-9ec3-1f628e1d67ee">
