### ISSUE TITLE
🐛 Bug Report: as a user I want to be able to import a Prisma schema with @default(dbgenerated()) attribute

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6936]
### What happened?

We support four types of ID fields - CUID, UUID, Incremental Int, and Incremental BigInt - where each converts to a specific default value on the Prisma schema.  

https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#default

Prisma also supports a default value using a function called dbgenerated - see this
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#dbgenerated

Any @default attribute with the dbgenerated function will be mapped to the `Custom Attribute` field for all field types but not for ID fields. 

<img width="688" alt="image" src="https://github.com/amplication/amplication/assets/43705455/a0b4bb09-a17a-414a-a22b-91d9d2ed9757">

### What you expected to happen

Users should be able to successfully import the schema file even when it contains an ID field with @default(dbgenerated()) attribute 

### How to reproduce

Import the below schema

```

datasource postgres {
  provider = "postgresql"
  url      = env("DB_URL")
}

generator client {
  provider = "prisma-client-js"
}

model order {
    id        String   @id() @default(dbgenerated("uuid_generate_v4()")) 
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
}
```

### Amplication version

1.8.11

**Comment by yuval-hazaz** [comment]
This issue should be looked at in a more generic way than just adding support for dbgenerated function.

To overcome this issue and other cases with other attributes on the ID field, I suggest enabling the `custom attribute` field and allowing the user to override the default behavior of the generated schema. This means any @default or @id attributes that will be added to the `custom attribute` will be used instead of the default @id and @default attributes. 
This way, we will import the attributes AS-IS from the schema. 

Suggested logic:

1. Import all attributes on an ID field from the imported schema to the `custom attributes` field (same as all other fields)
2. In case the @default attribute is one of the cases that we support out-of-the-box (CUID, UUID, incremental) - we will remove the @default attribute from the `custom attributes` field (leaving all other attributes, if they exist)
2. In case the @id attribute is one of the cases that we support out-of-the-box (empty @id() attribute) - we will remove the @id attribute from the `custom attributes` field (leaving all other attributes, if they exist)
3. The `custom attributes` field on the ID field will be editable (currently disabled) 
4. The `prisma-schema-dsl` package should check whether the custom attribute field contains @id and/ or @default for an ID field (and maybe for all scalar fields) and will ignore the default value property and will print the field based on the custom attributes.

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/8d9a89f6-6a32-4e0f-8446-9fc3e654b463)
