### ISSUE TITLE
🐛 Bug Report: as a user I want to be able to import a Prisma schema with @id(map : "string") attribute

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6937]
### What happened?

When a user tries to import this model, the map on the ID field will be lost 

model post {
    id        String   @id(map: "PK_dd4f738d44") @default(cuid())
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
    title     String
}

### What you expected to happen

The value of the map property should be retained 

### How to reproduce

import this model

model post {
    id        String   @id(map: "PK_dd4f738d44") @default(cuid())
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
    title     String
}

### Amplication version

1.8.11

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/f04208c3-2103-432b-88db-9736d4629ea2)
