### ISSUE TITLE
🐛 Bug Report: as a user I want to be able to import a Prisma schema with custom attributes on an ID field

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#6938]
### What happened?

When a user tries to import this model, the @db.Uuid on the ID field will be lost.

model order {
    id        String   @id() @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
    createdAt DateTime @default(now()) @db.Timestamp(6)
    updatedAt DateTime @default(now()) @db.Timestamp(6)
}

### What you expected to happen

The value of the map property should be retained

### How to reproduce

Import this model

```
model order {
    id        String   @id() @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
    createdAt DateTime @default(now()) @db.Timestamp(6)
    updatedAt DateTime @default(now()) @db.Timestamp(6)
}
```

### Amplication version

1.8.11

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/d6f9cc40-21a5-414e-9f3e-56c701fc3828)
