### ISSUE TITLE
🐞 Bug Report: DB Schema Import - id field named id that doesn't have `@id` attribute and the model has `@@id` attribute

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6989]
In the current implementation, when a model introduces a composite id: `@id([field1, field2])`, we change the attribute from `@@id` to `@@unique` and add an id field to the model

Due to data loss risk, we decided not to support this and throw an exception when the schema has composite ID models.

There are cases in which the model `@@id` attribute used as a regular PK field `@@id([field])` and in this case we should convert the model `@@id` attribute to field `@id` attribute.

Example schema:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Doctor {
  fullName      String    	
  tagId             Int @default(dbgenerated())

  @@id([tagId])
}
```

The desired outcome:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Doctor {
  fullName    String    	
  id                String @id @default(cuid()) map("tagId")

  @@unique([id])
}
```

**Comment by overbit** [comment]
@abrl91 what is the expectation here? Why the id field should be produced with `@id` if this table has a composite primary key?

**Comment by morhag90** [comment]
Currently, there is no easy or known way to test this issue. 
I approved it now and we will watch the status on production. 
@abrl91 @mulygottlieb

**Comment by morhag90** [comment]
Passed QA:

<img width="549" alt="image" src="https://github.com/amplication/amplication/assets/97830649/982a0bd7-ae6d-4f7c-aa75-c584a3c94a58">
