### ISSUE TITLE
🐛 Bug Report: npm run setup:dev erroring on step 2. 

### ISSUE THREAD

**Issue by udaya-reddy** [amplication/amplication#6996]
### What happened?

![image](https://github.com/amplication/amplication/assets/67152550/d279e7cc-3744-480f-93ac-4b2358c11c90)

### What you expected to happen

To compile and work as mentioned in readme

### How to reproduce

install amplicaton on local as the readme docs. after yarn install. npm run setup:dev  failes

yarn install done. But python was not found in final step. one of the dependencies needed engine <18. so used ignore-engines command.

### Amplication version

the one cloned from github

### Environment

Node: 18.17.0
npm: 9.0.0
docker : 24.0.6
os: windows 10

**Comment by overbit** [comment]
@udaya-reddy probably a typo, but amplication uses `npm` and not `yarn`.
If you did use `yarn install`, try deleting your `./node_modules` and re-go through the README

**Comment by udaya-reddy** [comment]
Thanks that worked.
