### ISSUE TITLE
🐛 Bug Report: `data-service-generator` logs show the wrong version

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7006]
### What happened?

Currently, releases that affect dsg, will cause new dsg container to have a wrong reference in it.
https://github.com/amplication/amplication/actions/runs/6300465341/job/17103423814#step:9:136

This means, that even, if the container tag is correct (i.e. v.1.9.10) the dsg logs will show a wrong reference like below:

<img width="693" alt="image" src="https://github.com/amplication/amplication/assets/2861984/e479aa24-e050-497c-99e6-3db0df02e183">

### What you expected to happen

dsg container needs to be built passing the same version that is used to tag the container.
i.e. in the example above, `data-service-generator` version v1.9.10 should show 
```sh
2023-09-25T14:18:54.442Z (Info) Running DSG version: v1.9.10 <458d36>
```
instead of `v1.9.5`

### How to reproduce

Release in prod

**Comment by mulygottlieb** [comment]
This is actually QA-able only after we release a new DSG version (@overbit )

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/2906b81b-6118-4065-9783-93d94282e73a)
