### ISSUE TITLE
⭐ Plugin: GitHub Codespaces

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7012]
## Requirements:
1. The new plugin will be well documented with instructions and HowTos
2. A new base codespaces configuration file that will allow to run the generated service, and if selected the adminui application.
4. The plugin should leverage into the `docker-compose.yml` file created by `CreateServerDockerCompose` event instead of redefining new rules
5. The plugin settings will contain a property that will allow the user to define a custom location for `devcontainer.json`. The default value for this setting should be `<repo-root-dir>/.devcontainer/devcontainer.json`
6. The plugin settings will contain a property that will allow the user to generate the configuration based on the service name. When this setting is `true` the configuration location will be set as  `<repo-root-dir>/.devcontainer/<service-name>/devcontainer.json`
7. The plugin will contains unit tests to cover the expected scenarios

## Icon
![GitHub Codespaces](https://github.com/amplication/amplication/assets/112330500/d934c39a-270b-4606-80d6-b313e3d164d6)

## Prize: USD 200 🏆 

Reply with the proposed solutions and structures.

**Comment by Meyazhagan** [comment]
@GreenMachine01 @souravjain540 I would like to work on this plugins

Here is an approach,
1. Create a plugin from plugins template
2. In `CreateServerDockerCompose` event, create docker-compose file
3. Based on the plugin settings, we create devcontainer in customLocation or separate for each services.
4. will also create unit tests to cover the expected scenarios

```json
{
   "settings" : {
       "customLocation" : "<custom-location-for-devcontainer>",
       "separateForEachService": true
   }
}
```
Please have a look, thanks!

**Comment by souravjain540** [comment]
@Meyazhagan thanks for the approach but you work on only one plugin for this campaign.

**Comment by MatteoGheza** [comment]
@GreenMachine01 @souravjain540 I would like to work on this feature request, if no one has been assigned so far.

My approach would be similar (almost identical I think):
1. Create a plugin using plugins template
2. In CreateServerDockerCompose event handler, create `docker-compose.yml` file
3. Generate `devcontainer.json`, using plugin settings
4. Add unit testing for all the possible settings

```
{
   "settings" : {
       "location" : "<custom-location-for-devcontainer>",
       "includeServiceName": true
   }
}
```

**Comment by souravjain540** [comment]
@MatteoGheza can you explain a lil bit more?

maybe creating an example before actually creating the plugin?

**Comment by Tjsingh01996** [comment]
@souravjain540 can you pls assign this task to me

**Comment by Tjsingh01996** [comment]
@souravjain540 
 Here is an approach,

1. create plugin using plugin template

2. create an for creatDevcontainer event this event will be register(before , after fuction to update module or event params ) 
to the plugins which was selected from 

3. path of the file will be set according the plugin settings

4. then move to write test cases for all expected scenarios

**Comment by overbit** [comment]
@MatteoGheza if you are still up for it, I can assign it to you

**Comment by MatteoGheza** [comment]
> @MatteoGheza if you are still up for it, I can assign it to you

I tried to setup a dev env for working on this, but I couldn't (using a 16-core Codespaces machine): it throws many errors, and after fixing them I can't replicate a working Github App and login, so I can't go to dashboard (and then code gen doesn't work).
Do you have any tutorial or wiki I can follow for this? Thanks.

**Comment by overbit** [comment]
@MatteoGheza you can find the docs at docs.amplication.com. For this particular case, this page might help https://docs.amplication.com/running-amplication-platform/configure-github-auth/

**Comment by MatteoGheza** [comment]
> @MatteoGheza you can find the docs at docs.amplication.com. For this particular case, this page might help https://docs.amplication.com/running-amplication-platform/configure-github-auth/
> 
> If you have faced issue with codespaces, please raise an issue and you fancy after that, you can create a PR with the fixes too. That would be much appreciated

![chrome_zPbhbj77Mb](https://github.com/amplication/amplication/assets/27729549/a6d76973-0abf-4b8f-b15e-0ea73c0be0de)
I am now stuck on this error...
![chrome_MwzCFg6nkE](https://github.com/amplication/amplication/assets/27729549/52e00af9-30ea-4c04-b8be-e4aed6690e02)

**Comment by souravjain540** [comment]
@MatteoGheza any update?

**Comment by MatteoGheza** [comment]
> @MatteoGheza any update?

I tried to fix it for myself, but I don't know the codebase enough. Can you look into the issue?
If needed, I can open a new Github issue for that, then I can start working on this

**Comment by overbit** [comment]
@MatteoGheza it seems related to the secret being malformed. 
Can you confirm that you have followed this https://docs.amplication.com/running-amplication-platform/connect-server-to-github/ **point 1.5** ?
> Click Generate a private key, download, open the generated certificate, add \n at the end of each line except the last line and join all lines to obtain a single line string

The `\n` is really important

**Comment by PentesterPriyanshu** [comment]
@overbit   i can work on it because he has taken too much time

**Comment by souravjain540** [comment]
@PentesterPriyanshu please write an approach

**Comment by PentesterPriyanshu** [comment]
My approach 

1. I will create a new directory for my plugin and add the necessary files, including a `pom.xml` file, a `README.md` file, and a `src` directory.
2. I will define the plugin's settings, including the `githubCodespaces.devcontainerLocation` and `githubCodespaces.generateConfigBasedOnServiceName` settings.
3. I will create a `CreateServerDockerCompose` event handler that will create a new `docker-compose.yml` file based on the services defined in the `devcontainer.json` file.
4. I will create a `GenerateConfig` event handler that will generate the configuration files based on the service name.
5. I will use the `docker-compose.yml` file created by the `CreateServerDockerCompose` event handler and the `devcontainer.json` file to define the services and their dependencies.
6. I will write unit tests for the plugin, including tests for the `CreateServerDockerCompose` and `GenerateConfig` event handlers and the plugin's configuration.

**Comment by souravjain540** [comment]
@pyxelpioneer assigned to you.

Please join our discord and dm me. I will add you to pvt channel.

**Comment by souravjain540** [comment]
@pyxelpioneer  any updates?
