### ISSUE TITLE
⭐ Plugin: Secret Manager - AWS Secrets Manager

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7015]
As a user, I'd like to use a plugin that will allow to use AWS Secrets Manager  for my services.

## Requirements:

- the plugin will modify the  generated `SecretManager` service enabling the user to collect secrets
- the plugin must leverage the default credentials of AWS SDK. If the AWS SDK reads environment variables directly, then a new set of default variables needs to be populated in the `.env` file.  
- documentation regarding how the plugin works and, if defined, explain any secrets naming convention used in the plugin

### Settings
- the plugin settings will contain a property `fetchMode` that will allow to collect secrets at start time (`STARTUP`) or at run time (`ON_DEMAND`)

If the user select the option to collect secrets at start-up time (`STARTUP`), the documentation and the plugin settings will need to define a property `secretsNames` that will contain an array of all the secrets that need to be collected during the SecretManager instantiation. 

i.e. `.amplicationrc.json`
```jsonc
// ...
  "settings": {
    "fetchMode": "STARTUP",
    "secretsNames": [
      "/secretA",
      "/path/path2/secretB",
      "/path/path2/path3/secretC"
    ]
  },
// ...
```

## Tech Notes
Reference: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/secrets-manager/

## Icon
![AWS Secrets Manager](https://github.com/amplication/amplication/assets/112330500/46e06f9f-33ed-4b15-ab9e-b4e50f244821)

## Prize: USD 250 🏆 

Reply with the proposed solutions and structures.

**Comment by duwudle** [comment]
This is my possible approach for this plugin

1. Create a function in the secrets root folder that fetches the secrets and parses them as a JSON object
2. Then, In `SecretsManagerModule`, the function is loaded with the `ConfigModule`

As for the `secretNames`, the function will return only the names defined in the `secretNames` rather than returning all the secrets.

Im a bit bad at explaining but I hope you get the gist of my approach, lemme know if I am unclear at some point.

Lemme know if you want to see a quick impl of the plugin 😄

**Comment by overbit** [comment]
@duwudle try to have a look to the current default SecretsManagerService and the base SecretsManagerServiceBase to better plan the implementation.

**Comment by duwudle** [comment]
@overbit, I see...

Lemme know what you think about these:

1. In the `SecretsManagerServiceBase` i can add a function (named, for example, `loadSecrets()` that will load all the secrets with the SDK and then save those secrets in a member variable (can be called `SecretsManagerService` contructor .
2. In the `getSecret<T>` function, i can use the member variable to get the secret and return it as the `T` generic

- or -

1. In the `getSecret<T>` function, i can fetch the secret key in that function itself with the SDK and return the value as `T` generic.

**Comment by overbit** [comment]
@duwudle this is a better approach, but I'd recommend not to change the Base file.
There is a new issue open that will simplify the plugin development https://github.com/amplication/amplication/issues/7112 but in the meantime I'd recommend to start from an amplication generated service and add all the code that you require to have a working solution. Once you are happy with the result, we can review it and get the green light to implement the plugin.

**Comment by duwudle** [comment]
@overbit aight cool!
