### ISSUE TITLE
⭐ Plugin: Secret Manager - Azure Key Vault

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7018]
As a user, I'd like to use a plugin that will allow to use Azure Key Vault as secret manager for my services

## Requirements:

- the plugin will modify the  generated `SecretManager` service enabling the user to collect secrets
- the plugin must leverage the official Azure SDK. If the Azure SDK reads environment variables directly, then a new set of default variables needs to be populated in the `.env` file.  
- documentation regarding how the plugin works and, if defined, explain any secrets naming convention used in the plugin. This documentation may contain links to official docs for any SDK specifics

### Settings
- the plugin settings will contain a property `fetchMode` that will allow to collect secrets at start time (`STARTUP`) or at run time (`ON_DEMAND`)

If the user select the option to collect secrets at start-up time (`STARTUP`), the documentation and the plugin settings will need to define a property `secretsNames` that will contain an array of all the secrets that need to be collected during the SecretManager instantiation. 

i.e. `.amplicationrc.json`
```jsonc
// ...
  "settings": {
    "fetchMode": "STARTUP",
    "secretsNames": [
      "/secretA",
      "/path/path2/secretB",
      "/path/path2/path3/secretC"
    ]
  },
// ...
```
## Icon
![Azure Key Vault](https://github.com/amplication/amplication/assets/112330500/266bd2a5-bc34-427a-b6c1-89634916e032)

## Tech Notes
References: 
- https://learn.microsoft.com/en-us/azure/key-vault/general/developers-guide
- https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-node?tabs=windows
- https://azure.microsoft.com/en-us/products/key-vault

**Comment by ShatilKhan** [comment]
Hi I'd like to work on this, can I share my proposal?

**Comment by duwudle** [comment]
Can I work on this?
