### ISSUE TITLE
⭐ Plugin: Secret Manager - GCP Secret Manager

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7019]
As a user, I'd like to use a plugin that will allow to use Google Cloud Secret Manager for my services.

## Requirements:

- the plugin will modify the  generated `SecretManager` service enabling the user to collect secrets
- the plugin must leverage the default credentials of Google Secret Manager SDK. If the Google Secret Manager SDK reads environment variables directly, then a new set of default variables needs to be populated in the `.env` file.  
- documentation regarding how the plugin works and, if defined, explain any secrets naming convention used in the plugin

### Settings
- the plugin settings will contain a property `fetchMode` that will allow to collect secrets at start time (`STARTUP`) or at run time (`ON_DEMAND`)

If the user select the option to collect secrets at start-up time (`STARTUP`), the documentation and the plugin settings will need to define a property `secretsNames` that will contain an array of all the secrets that need to be collected during the SecretManager instantiation. 

i.e. `.amplicationrc.json`
```jsonc
// ...
  "settings": {
    "fetchMode": "STARTUP",
    "secretsNames": [
      "/secretA",
      "/path/path2/secretB",
      "/path/path2/path3/secretC"
    ]
  },
// ...
```

## Tech Notes
Reference: https://cloud.google.com/secret-manager

https://cloud.google.com/secret-manager/docs/reference/libraries#client-libraries-install-nodejs

## Icon
![GCP Secret Manager](https://github.com/amplication/amplication/assets/112330500/83a4cdc2-14ec-4555-b5a9-1d182c84dfec)

## Prize: USD 250 🏆 

Reply with the proposed solutions and structures.

**Comment by ptdatta** [comment]
@GreenMachine01 Can I work on it?

**Comment by GreenMachine01** [comment]
@ptdatta need to ask @souravjain540 . This plugin is meant to be built as part of Hacktoberfest.

**Comment by ptdatta** [comment]
Amazing, I am also participating o Hacktoberfest. @souravjain540 Can I work on it?

**Comment by ptdatta** [comment]
My Approach:
 - Create new plugin using plugin template (https://github.com/amplication/plugin-template).
 - Declare all the google cloud constants on `src/contants.ts` file.
 - I will access the environment variables by `beforeCreateServerDotEnv` event.
 - Create new event `beforeSecretManager` and `afterSecretManager` to access or modify the secret variables.
 - Create an `init` function which will start according to user `STARTUP` or `ON_DEMAND`.

**Comment by overbit** [comment]
@ptdatta a couple of requests: 

1. can you raise a new feature request issue for the SecretsManager plugin events? (I can assign this to you)
2. Sorry but I do not understand what do you mean with:
 > Create an init function which will start according to user STARTUP or ON_DEMAND
 Can you elaborate more?

My suggestion is to start from a service generated by amplication and modify it as per the plan.
Once everything works as expected and only then, start working on a plugin. (having the manually generated code available in a public repo will definitely help the review process)

**Comment by ptdatta** [comment]
@overbit  by init function I mean after running that function the plugin will start to collect secrets. According to user on `STARTUP` or `ON_DEMAND`
Here is the secret manager event's issue #7112.
Please assign this to me.

**Comment by overbit** [comment]
@ptdatta The init function might make sense only for STARTUP mode as in ONDEMAND the getSecret (or however it's called) will perform the request to GCP each time it is called

**Comment by souravjain540** [comment]
@ptdatta assigned this one to you, i am making a pvt channel for you in discord lets discuss your daily updates there.

**Comment by directioner1d** [comment]
Here is my approach to the problem:

1. Before the envCreate event, i will populate any extra env vars required for the GCP SDK.
2. In the `beforeCreateServerSecretsManager` event, I will run a function which will parse all the secrets (according the new secrets manager event)
3.  For the fetch mode `STARTUP`, i will load all the secrets and store it privately in a variable and override the `getSecret` function to return the secrets from that variable
4. For the fetch mode `ON_DEMAND`, i will load all the secrets directly in the `getSecret` function

This is my approach to the plugin.

**Comment by overbit** [comment]
@directioner1d we now have a new event to support secret manager providers: `CreateSecretsManager` 
Have a look to how this plugin got migrated to it
https://github.com/amplication/plugins/pull/261

**Comment by directioner1d** [comment]
@overbit Okay... so how about this then?

1. Before the envCreate event, i will populate any extra env vars required for the GCP SDK.
2. In the event before `CreateSecretsManager`, I will parse all the secrets that are defined in the settings, and then push them to the `eventParams.secretsNameKey` variable
3. In the event before `CreateServer`, I will update the user's code based on the fetch mode choosen

If the fetch mode chosen is `STARTUP`, I will load all the secrets and store it privately in a variable and override the `getSecret` function to return the secrets from that variable.

If the fetch mode chosen is `ON_DEMAND`, i will load all the secrets directly in the `getSecret` function by using the SDK

**Comment by souravjain540** [comment]
@directioner1d assigned to you, please join our discord and dm me so that i can add you to a pvt channel
