### ISSUE TITLE
Amplication Hacktoberfest 2023 🥇 

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#7026]
# Amplication Hacktoberfest 2023 [Starting Oct 1, 2023]

![Hacktoberfest Banner give](https://github.com/amplication/amplication/assets/53312820/9a626620-0395-4663-9179-567fec391176)

### Amplication is a proud sponsor of Hacktoberfest 2023 ❤️ 

Hello contributors 👋

As proud members of the open-source community, we inspire developers to contribute to open-source projects, and what's better than the month of open source, Hacktoberfest? 💜

To help you get started, we have plenty of issues for open-source contributors.

By giving back to the community, you’re also getting a chance to win cool limited-edition swag.

# Prizes 🏆 

### Code and Non-Code Issues.

1. Contributors making one to two valid pull requests will get an Amplication Hacktoberfest Exclusive sticker sheet.
2. Contributors making three or more valid pull requests will get an Amplication Hacktoberfest Exclusive T-Shirt.

[Click here to see all of the issues.
](https://github.com/amplication/amplication/issues?q=is%3Aopen+is%3Aissue+label%3A%22open+to+community%22)

### Premium Issues

This year, we have introduced Premium Issues to our Hacktoberfest campaign; these are the issues associated with gift cards worth up to USD 500.

[Click here to know more](https://github.com/amplication/amplication/issues/7027)

### Build Web Apps Using Amplication:

We are inviting our community to use and build creative and new projects using Amplication: [Click here to know more](https://github.com/amplication/amplication/issues/7028)

## Support

Stuck anywhere? Don't worry; we are here to help you. [Join our discord server ](https://amplication.com/discord)and our team will help you with the issue.

# Rules ⚠: 

- This activity applies to all of the issues in `amplication\amplication` with label `open to community.`
- Only the person assigned by Team Amplication will be considered a valid contributor
- You can also open new issues, but that has to be accepted by someone from Team Amplication to be considered as a valid issue.
- Every contribution that is made between October 1, 2023, to October 31, 2023, in any time zone will be considered a valid contribution.
- We will allow you to complete the reviews or feedback our team gave until November 7, 2023.
- This activity is on a “first come first serve” basis.
- Any participant can get only one swag. No stacking of SWAG is allowed.
- The SWAG is in limited quantity.
- Not every contribution will be merged. Only contribution-matching standards can be merged; however, we will give the PR `hacktoberfest-accepted` label to count it as a contribution.

[Click here to learn all the Rules and T&C.
](https://github.com/amplication/amplication/issues/7030)

**Comment by Asiachanel** [comment]
Good project

**Comment by NitkarshChourasia** [comment]
# Good Project.

**Comment by hridaya423** [comment]
Can i make tutorials on amplication. Would that be valid? @souravjain540

**Comment by NitkarshChourasia** [comment]
> Can i make tutorials on amplication. Would that be valid? @souravjain540

@hridaya423 Just make it. Show us the demo. At least.

**Comment by iam-joshi** [comment]
Good to contribute with you? How ?
