### ISSUE TITLE
Premium Issues: Plugin Development [WIN UPTO USD 500] 💰 

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#7027]
# Premium Issues [Updated deadline Nov 30]

Amplication has a robust plugin development system. Since its launch, with the help of our open-source community and the fantastic work of our R&D team, we currently have **[18 Plugins developed.](https://amplication.com/plugins)**

This year, we invite experienced developers who want to work on something thousands of developers will use. 

We have a list of 10+ plugin ideas that we would like our community to work on.

## Plugin Ideas:

Basic File Upload[USD 500]: https://github.com/amplication/amplication/issues/7043
Elasticsearch [USD 500]: https://github.com/amplication/amplication/issues/7013
GitHub Codespaces[USD 200]: https://github.com/amplication/amplication/issues/7012
RabbitMQ Message Broker[USD 200] https://github.com/amplication/amplication/issues/6878
Secret Manager - HashiCorp Vault [USD 250]: https://github.com/amplication/amplication/issues/7014
Secret Manager - AWS [USD 250]: https://github.com/amplication/amplication/issues/7015
Secret Manager - Bitwarden[USD 250]: https://github.com/amplication/amplication/issues/7016
Secret Manager - 1Password[USD 250]: https://github.com/amplication/amplication/issues/7017
Secret Manager - GCP [USD 250]: https://github.com/amplication/amplication/issues/7019
JSON Logger [USD 250]: https://github.com/amplication/amplication/issues/7033
Keycloak[USD 400]: https://github.com/amplication/amplication/issues/7044

## Prizes

- Gift Cards up to $500 for the platform of your choice.
- You can also choose to donate the amount of gift card to any open source project of your choice.

### Rules

- We invite experienced developers willing to take a challenge and build something that can help thousands of developers.

- We have a list of 10+ premium issues associated with a gift card worth up to $500. This mainly includes new plugin development for our robust plugin system.

- If you think you are qualified and have knowledge for the task, please select the plugin you want to work on and feel free to share the structure and approach on how you are going to build the plugin and get it assigned.

- Once the issue is assigned to you, we will invite you to a private discord channel where you can talk with our team members, ask for help, and share the progress you have made on the task.

For making sure someone is working on the issue constantly and other community member does not have to wait for the issues, non-activity for 3 days can lead to re-assigning issue to other community members.

Comment on each issue with the relevant information as mentioned to get it assigned to yourself, it will be first come first served.

**T&C Applied**

**Comment by ptdatta** [comment]
Hey @souravjain540, I want to work on this plugin development.

**Comment by SaketKaswa20** [comment]
I would love to work on this. I would love to definitely give it a try. Also, I am confident enough that with your help and support I can do it.

**Comment by ptdatta** [comment]
Hey @souravjain540 , I have two idea for this.
1. Currently amplication only have basic-auth-provider so I want to add a Auth0 plugin for better and more secure auhentication.
2. To build a docker plugin to containerize applications quickly.
What do you think?

**Comment by souravjain540** [comment]
@ptdatta someone from the team will reply soon.

**Comment by souravjain540** [comment]
> I would love to work on this. I would love to definitely give it a try. Also, I am confident enough that with your help and support I can do it.

@ptdatta choose any plugin from the list, go to that issue, and write your approach.

**Comment by symaticvisuals** [comment]
@souravjain540 I'm interested as well for working on the plugin.

**Comment by souravjain540** [comment]
@symaticvisuals  please choose a plugin go to that issue leave a comment sharing approach and structure

**Comment by NitkarshChourasia** [comment]
Sign me up, too.

**Comment by CodeDrinks270** [comment]
@souravjain540 
I want to work on a plugin .
Please assign it to me

**Comment by NitkarshChourasia** [comment]
@CodeDrinks270 Sorry, it is already reserved.
You can't make this.

**Comment by NitkarshChourasia** [comment]
@souravjain540 I am offically announced as an devrel for this project.
Thanks for your service. @souravjain540

**Comment by PentesterPriyanshu** [comment]
is anyone working on it still this issue is open because i am ready to work on it

**Comment by souravjain540** [comment]
> is anyone working on it still this issue is open because i am ready to work on it

please write an approach
