### ISSUE TITLE
Build Web Apps Using Amplication 👕 

### ISSUE THREAD

**Issue by souravjain540** [amplication/amplication#7028]
###  Contribute a Tutorial & Grab an Amplication T-Shirt! 🎉

**Starting October 1, 2023**

Hello Amplication Enthusiasts! 🌟

We are excited to announce a special initiative for our vibrant community. We are inviting all of you to create a web application using Amplication and share your journey through a detailed tutorial or a video walkthrough. Each participant, upon approval and submission, will receive an exclusive Amplication T-shirt!

**How to Participate?**
1. Propose your application idea by commenting below or directly reaching out to our team for approval.
2. Once approved, build your application using Amplication.
3. Craft a detailed tutorial explaining the process or create a video walkthrough. Ensure clarity, comprehensiveness, and creativity.
4. Post the tutorial on the blog/video-sharing platform of your choice.
5. Submit a PR with the tutorial link to `amplication/amplication/tutorials/filename`
6. Once approved, your tutorial will be featured on our official channels, and you'll receive your T-shirt!

**Need Ideas? Here are some to get you started:**
1. Personal Expense Tracker
2. Online Quiz Platform
3. Event Management System
4. Book Review Portal
5. Fitness Routine Planner
7. Recipe Sharing Application
8. Real Estate Listing Portal
9. Virtual Classroom Management
10. Local Services Directory
11. Blogging Platform

Of course, these are just suggestions. We're eager to see the innovative ideas you come up with. The sky's the limit!

**Community Examples**

- Build an AirBnB clone using Amplication: https://youtu.be/nkmPmUpUM6U?si=heeaZ_HvPOdh4_KE
- Building a Real-time Chatroom using Amplication: https://amplication.com/blog/creating-a-chatroom-in-angular-using-amplication

**Guidelines:**
- The idea should be unique and not replicate existing tutorials or samples.
- The content should be original and not violate any copyright rules.
- Make sure the tutorial is detailed, with screenshots or video sections clearly showcasing each step.
- Ensure your app doesn't promote any form of hate, discrimination, or anything that violates Amplication's community guidelines.

Looking forward to seeing the amazing applications and tutorials you all create! Let's learn, share, and grow together! 🚀

**Comment by Sapna127** [comment]
Hii @souravjain540 
I will be building the 'dev dashboard' using amplication..
The web app will be all in one platform for devlopers it includes - project tracking, github integration, code review and collaborayion everything at one place.. 
The ui is alreday ready - 
![image](https://github.com/amplication/amplication/assets/91309280/ead01913-e5e0-42d3-9e12-20ad061293f6)

Please assign this issue to me!

**Comment by souravjain540** [comment]
> Hii @souravjain540 I will be building the 'dev dashboard' using amplication.. The web app will be all in one platform for devlopers it includes - project tracking, github integration, code review and collaborayion everything at one place.. The ui is alreday ready - ![image](https://user-images.githubusercontent.com/91309280/271020531-ead01913-e5e0-42d3-9e12-20ad061293f6.png)
> 
> Please assign this issue to me!

wonderful, you can start working on it and submit PR as mentioned on or after Oct 1, 2023.

**Comment by sarojregmi200** [comment]
Hey @Sapna127.
I want to build and explore a project for my father's business or our family business. That helps us manage tools and items that are needed for managing the food for big events. +50 members.

I will be working on the design after I complete with my current projects. So, I want to ask if this is available after octuber or not?

**Comment by utsavbhattarai007** [comment]
Hello @souravjain540, I'm looking to create a website that captures high-resolution screenshots of other sites by passing the url of that site. Additionally, I'd like features for editing these images and saving them in personalized collections on our platform.

**Comment by ffex** [comment]
Hello! I want to implement a simple and fast job/life organizer, with to-do lists, calendar, daily schedule and something like that with some customization.

**Comment by souravjain540** [comment]
> Hello @souravjain540, I'm looking to create a website that captures high-resolution screenshots of other sites by passing the url of that site. Additionally, I'd like features for editing these images and saving them in personalized collections on our platform.

@utsavbhattarai007 this idea is approved make sure you are using Amplication in the backend.

**Comment by souravjain540** [comment]
> Hello! I want to implement a simple and fast job/life organizer, with to-do lists, calendar, daily schedule and something like that with some customization.

@ffex approved, make sure you are using Amplication in backend :)

**Comment by loopteam0** [comment]
Hello, I want to create a job posting application, where users can post and apply for jobs

**Comment by sarojregmi200** [comment]
> Hey @Sapna127. I want to build and explore a project for my father's business or our family business. That helps us manage tools and items that are needed for managing the food for big events. +50 members.

Hey @souravjain540, what is the status of my idea?

**Comment by cp-Coder** [comment]
Hello, I'm planning to create a project that serves as a platform for both sports facility owners and players. The idea is to allow facility owners to register their facilities, providing all the necessary details. Players, on the other hand, can conveniently book these facilities for specific time slots by paying a nominal fee. Additionally, I intend to include a community feature, enabling players to connect with each other, organize games, and foster a sense of community within the platform. My plan is to develop the backend for this project using Amplication.

**Comment by souravjain540** [comment]
> Hey @Sapna127. I want to build and explore a project for my father's business or our family business. That helps us manage tools and items that are needed for managing the food for big events. +50 members.
> 
> I will be working on the design after I complete with my current projects. So, I want to ask if this is available after octuber or not?

Idea sounds good, this is a hacktoberfest issue so need to be completed before Oct 31. But you can DM me and we can talk.

**Comment by souravjain540** [comment]
> Hello, I'm planning to create a project that serves as a platform for both sports facility owners and players. The idea is to allow facility owners to register their facilities, providing all the necessary details. Players, on the other hand, can conveniently book these facilities for specific time slots by paying a nominal fee. Additionally, I intend to include a community feature, enabling players to connect with each other, organize games, and foster a sense of community within the platform. My plan is to develop the backend for this project using Amplication.

sounds good.

**Comment by Cioraz** [comment]
Hey,
Im planning to build a Recipe Sharing Application wherein there would be the recipes from different peoeple around the world showcased. Ill use amplification as the main backend along with nextjs. I would implement sharing of recipes from around the world along with items list and required commodities. There would be some dummy mails to contact the recipe makers to help create an open source like recipe sharing community.

**Comment by heysagnik** [comment]
I want to work on Personal Expense Tracker.

**Comment by souravjain540** [comment]
@heysagnik approved.

**Comment by souravjain540** [comment]
@Sapna127  @sarojregmi200  @cp-Coder @ffex @loopteam0 any update folks?

**Comment by Cioraz** [comment]
Hello, 
I would be interested to work on book review portal

**Comment by loopteam0** [comment]
> @Sapna127  @sarojregmi200  @cp-Coder @ffex @loopteam0 any update folks?

I'm OK with it, I'll start working on it

**Comment by AryanParashar24** [comment]
Hey @souravjain540 i will try to build a personnel website telling out my skills, experiences and events i will be attending in the future and also if i can publish or atleast put the notification of blog or youtube tutorial on the website

**Comment by cp-Coder** [comment]
> @Sapna127 @sarojregmi200 @cp-Coder @ffex @loopteam0 any update folks?

Sorry for the delayed response. I am currently working on it.

**Comment by choudhary-vaibhav** [comment]
hey @souravjain540 , I want to work on Recipe Sharing Application

**Comment by shravan20** [comment]
@souravjain540: 

**Project Idea: PollarBear**

**Description:**
An online platform that allows users to create, distribute, and analyze surveys and feedback forms. Users can sign up, create custom surveys with various question types (multiple-choice, open-ended, rating scales), share surveys with respondents, collect responses, and view analytics and reports.

Please request for approval

**Comment by souravjain540** [comment]
@Cioraz  @choudhary-vaibhav @AryanParashar24   @shravan20  approved

**Comment by Paulie-Aditya** [comment]
Would make a Movie Review, Sentiment Analysis Project.
Please approve this so that I can start working on it.

**Comment by Better-Boy** [comment]
I would like to work on Real Estate Listing Portal. Requesting for approval.

**Comment by Prashidha0O1** [comment]
I would like to make Voice Powered Expense Tracker. Requesting For approval

**Comment by souravjain540** [comment]
@Paulie-Aditya @Better-Boy @Prashidha0O1 approved, make sure to use Amplication in the backend

**Comment by Yaduttam95** [comment]
Hey! @souravjain540  i would like to create a Recipe sharing application , Requesting for Approval!

**Comment by souravjain540** [comment]
@Yaduttam95 someone is already making it, if you have some other idea maybe?

**Comment by sushilbhattarai45** [comment]
Hey i want to make an website called "MyYt"  from where users can download high resolution youtube videos from a simple click.

**Comment by souravjain540** [comment]
@sushilbhattarai45 amazing! Approved.

**Comment by VanshajPoonia** [comment]
I'm working on a web app for a restaurant business. It can be used in real-world scenarios.

**Comment by MSaiKiran9** [comment]
Hey @souravjain540 I want to make a simple drawing app which has functionalities like saving the front-end drawings to backend etc ... . Let me know if that's good to go

**Comment by hridaya423** [comment]
Hi, @souravjain540  I'd like to make a blogging system

**Comment by RaturiAR7** [comment]
@souravjain540  I would like to a make a small blog platform. Please approve.

**Comment by DiySane** [comment]
@souravjain540 I would like to build a disposable anonymous communication channel which will be only accessible for people having the link.

**Comment by MohitSingh2002** [comment]
Hey @souravjain540 I would like to work on library management system where you can prebook any book and check the status of when to return it and any fine you have pending
This project will basically more suitable for colleges

**Comment by Raunakkumarr** [comment]
@souravjain540 can I make a tourism focused application to connect tourists to local guides offering their own rates and services somewhat like Indrive.

**Comment by CodeDrinks270** [comment]
@souravjain540 
I would like to develop a dashboard using Amplication.

**Comment by thompsgj** [comment]
Hello @souravjain540 
I'd like to build the Virtual Classroom Management application.

**Comment by aliveevie** [comment]
Hello @souravjain540 I will like to create e-cheques.
Please assign this task to me

**Comment by MSaiKiran9** [comment]
Is this issue still live @souravjain540 @yuval-hazaz ?

**Comment by souravjain540** [comment]
@VanshajPoonia @MSaiKiran9 @RaturiAR7 @DiySane  @MohitSingh2002  @Raunakkumarr @CodeDrinks270 @thompsgj @aliveevie  approved! great ideas, just make sure to use Amplication in the backend, best of luck!

**Comment by souravjain540** [comment]
> Is this issue still live @souravjain540 @yuval-hazaz ?

it surely is.

**Comment by jrsmarcilio** [comment]
Hello @souravjain540 , I would like to create an Event Management System

**Comment by Nupoor10** [comment]
Hello @souravjain540, I would like to create a travel diary app, where users can add, view and search entries about their travels. Can I work on this?

**Comment by souravjain540** [comment]
@jrsmarcilio  @Nupoor10 approved, make sure to use amplication in the backend

**Comment by AqilJaafree** [comment]
Hello I would like to create a gym management system

**Comment by STUDIOUS-WOLF** [comment]
Hello I would like to create a application for renting houses

**Comment by STUDIOUS-WOLF** [comment]
Hi @souravjain540 I would like to create a house-renting solution  using amplication

**Comment by craigouma** [comment]
Hello @souravjain540 I would like to create a Quote of the Day web app that displays a daily inspirational or thought-provoking quote to users. It's a minimalistic project that offers a bit of daily motivation.
