### ISSUE TITLE
🐛 Bug Report: When a user's plan is in pro trial, the UI shows the account as free

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7031]
### What happened?
For this user
<img width="471" alt="image" src="https://github.com/amplication/amplication/assets/2861984/5ad2f021-948f-4b59-9e6b-6b9592a127f1">
This is what the UI shows instead of `Pro Plan`
<img width="504" alt="image" src="https://github.com/amplication/amplication/assets/2861984/730871f7-7a7f-4737-8c5f-b09e8d0417b5">

### What you expected to happen

The UI to show the workspace as `Pro Plan`

### How to reproduce

Create new workspace and activate the trial

### Amplication version

v1.9.5

**Comment by gopivaibhav** [comment]
Hey @overbit I want to work on this issue. Can you please assign me this?
Thanks!!

**Comment by asi309** [comment]
I would like to work on this. Please assign it to me
