### ISSUE TITLE
⭐️ Plugin: JSON Logger

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7033]
As a user, I'd like to use a plugin that will allow to my services to generate logs in JSON format instead of the less common string NestJs format.

## Requirements

The plugin must:
- wrap the package `nestjs-pino` in with a settings that will allow to produce the following logs:
- allow user to setup the logLevel in the settings that will be reflected in `.env` and configured on start time.
- each log will contain a property `serviceName` populated with the name of the service in amplication
- each log will contain a any additional properties defined in the `additionalLogProperties` settings.

In addition - add relevant documentation (in the plugin README) on how to use this in the generated services by injecting this logger where needed in the generated code. A usage example of the new logger in a generated code is needed.

### Settings
i.e. `.amplicationrc.json`
```jsonc
// ...
  "settings": {
     "logLevel" : "WARN",
     "additionalLogProperties": {
     
     }
  },
// ...
```

## Tech Notes
Reference: https://github.com/iamolegga/nestjs-pino

## Icon
![JSON Logger](https://github.com/amplication/amplication/assets/112330500/fd785dbf-d2bd-4789-8566-f5a49a5057e9)

## Prize: USD 250 🏆 

Reply with the proposed solutions and structures.

**Comment by ptdatta** [comment]
@overbit Can I work on it?

**Comment by pnkjbee2** [comment]
hey @overbit , will you assign this to me, Approach:-
1. create a custom logger module that wraps nestjs-pino
2. i will define the Configuration Interface for Log levels and other info.(amplication-logger.service.ts)
3. i will modify the AmplicationLogger service to use the provided configuration for log level and include the service name and additional log properties in the log messages.
4. i will define additionalLogProperties as needed:

**Comment by ptdatta** [comment]
@pnkjbee2 I'm already working on it.

**Comment by souravjain540** [comment]
> @pnkjbee2 I'm already working on it.

Please don't. We didn't assign it to you. I am again saying NO PRs will be accepted if issue is not assigned to you.

Please don't waste your time on working without getting it assigned to you.

**Comment by souravjain540** [comment]
> hey @overbit , can you assign this to me, Approach:-
> 
> 1. create a custom logger module that wraps nestjs-pino
> 
> 2. i will define the Configuration Interface for Log levels and other info.(amplication-logger.service.ts)
> 
> 3. i will modify the AmplicationLogger service to use the provided configuration for log level and include the service name and additional log properties in the log messages.
> 
> 4. i will define additionalLogProperties as needed:
> 
> 

Thanks for the propose solution, someone from team will reply to you soon.

**Comment by overbit** [comment]
> hey @overbit , can you assign this to me, Approach:-
> 
> 1. create a custom logger module that wraps nestjs-pino
> 2. i will define the Configuration Interface for Log levels and other info.(amplication-logger.service.ts)
> 3. i will modify the AmplicationLogger service to use the provided configuration for log level and include the service name and additional log properties in the log messages.
> 4. i will define additionalLogProperties as needed:

@pnkjbee2 It sounds good to me. 
My suggestion is to start from a service generated by amplication and modify it as per the plan. Once everything works as expected, start working on a plugin. (having the manually generated code available in a public repo will definitely help the review process) 

In the meantime, I'll assign it to you.

**Comment by souravjain540** [comment]
@pnkjbee2  please [join our discord](https://amplication.com/discord) and tell me your username. I will make a pvt channel for us. (It is a must in order to follow the rules.

**Comment by souravjain540** [comment]
@pnkjbee2 please join and dm me.

**Comment by pnkjbee2** [comment]
@souravjain540 my username is pnkj30

**Comment by craigouma** [comment]
@souravjain540 @levivannoort Is this issue still open?

**Comment by souravjain540** [comment]
@sakurablossoms01 assigned to you. please join our discord and dm me so that i can add to pvt channel
