### ISSUE TITLE
Amplication UI improved navigation and layout

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#7041]
### Feature description

https://www.figma.com/file/WeoGDXg8j0svKfGICORfww/Application-v2---Main-screen-%2B-On-boarding?type=design&node-id=266%3A20427&mode=design&t=wxQSOo2eOFF8IOEZ-1

**Comment by ptdatta** [comment]
@yuval-hazaz  I want to work on it please assign it to me.

**Comment by souravjain540** [comment]
@ptdatta please dm me on discord.

**Comment by Sheersendu** [comment]
I would like to work on this issue if its not already assigned! I come with experience in vue, react, typescript hence would love to contribute to amplication for a great experience!

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/e45bb51b-ac5b-401f-83da-fb02356f523d)
