### ISSUE TITLE
⭐️ Plugin: Keycloak

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7044]
As a user, I'd like to use a plugin that will allow authentication through KeyCloak for my services.

## Requirements:

The plugin must:
- modify the generated service with the necessary changes to allow authentication through KeyCloak 
- modify the generated `.env` file with any new variable
- modify the `docker-compose.yml` and `docker-compose.dev.yml` with the new dependency (KeyCloak)
- contain documentation regarding how the plugin works, and how to use it allowing users to easily configure it. It will also contain any necessary links to the official documentation

### Settings

The default plugin settings must consists of all the necessary parameter needed to configure the integration 
i.e. `.amplicationrc.json`
```jsonc
// ...
  "settings": {
    KEYCLOAK_HOST: "",
    KEYCLOAK_REALM: "",
    KEYCLOAK_CLIENT_ID: "",
    KEYCLOAK_CLIENT_SECRET: "",
    // ...
  },
// ...
```

## Tech Notes
Reference:  https://www.keycloak.org/

Try to keep the implementation simple leveraging the Passport.js strategy https://github.com/exlinc/keycloak-passport

## Icon
![Keycloak](https://github.com/amplication/amplication/assets/112330500/ad6533fe-7aad-40e2-b7f3-7645c5a116b4)

## Prize: USD 400 🏆 

Reply with the proposed solutions and structures.

**Comment by iamshabell** [comment]
Hey @overbit / @souravjain540, I want to work on this

**Comment by fumblehool** [comment]
Hi @overbit, I would love to work on this!
Here is an approach - 
1. Create new plugin using plugin template (https://github.com/amplication/plugin-template).
This will follow JWT-auth plugin (https://github.com/amplication/plugins/tree/master/plugins/auth-jwt)
2. It'll use events: `CreateServerDockerCompose, CreateServerDockerComposeDev, beforeCreateServerDotEnv etc` to modify .env and docker-compose files.
3. It'll let user specify `keycloak secrets` similary how `observability-opentelemetry-plugin` does.
4. Implement `createAuthModule` and `keycloak.strategy` using https://github.com/exlinc/keycloak-passport

Additional refs:
[custom-authentication-with-passport](https://docs.amplication.com/authentication/#custom-authentication-with-passport)
[Auth-Core plugin](https://github.com/amplication/plugins/tree/master/plugins/auth-core)
[Observability-Opentelemetry plugin](https://github.com/amplication/plugins/tree/master/plugins/observability-opentelemetry)


Please have a look, thanks 😄

**Comment by overbit** [comment]
@fumblehool  It sounds good to me but I'd add to have also a look to other auth plugin like `JWT Auth Provider` and `Basic Auth Provider`.
The plugin will leverage authentication as the authorization will be performed by current amplication generated code.

My suggestion is to start from a service generated by amplication and modify it as per the plan. 
Once everything works as expected and only then, start working on a plugin. (having the manually generated code available in a public repo will definitely help the review process)

In the meantime, I'll assign it to you.

**Comment by souravjain540** [comment]
@fumblehool  please [join our discord](https://amplication.com/discord) and tell me your username. I will make a pvt channel for us. (It is a must in order to follow the rules.

**Comment by overbit** [comment]
@Shurtu-gal  I've tried to use this plugin, installing it on an existing service, and I get the following errors on build:


![Image](https://github.com/amplication/amplication/assets/2861984/24f22f5d-1695-44ab-b702-0e73a04c29ea)

**Comment by Shurtu-gal** [comment]
I will look into this.

**Comment by Shurtu-gal** [comment]
@overbit I believe that the auth-core plugin is adding a password field to the generated code. This should be moved to the specific plugins needing it as was done for the [password service](https://github.com/amplication/plugins/pull/185). 

Any thoughts ?

**Comment by Shurtu-gal** [comment]
@overbit this is due to user entity having a password field which is not having any default value as can be [over here](https://github.com/amplication/plugins/blob/8240b1a1512917cd73a2cc8140a7db4a11b34b03/plugins/auth-keycloak/src/utils/createAuthProperties.ts#L116-L121).

Could you please give me some advice on what should I do regarding this?

There are two options:
- Make default password `password` and allow user to change it later for later compatibility with other plugins.
- Throw an error.

**Comment by overbit** [comment]
I'd suggest to follow the same approach used for the `Email` field, throwing an error in case of missing or wrong configuration. What do you think @Shurtu-gal ?

**Comment by Shurtu-gal** [comment]
Yeah that works.

I will make a new PR fixing this in both auth0 and keycloak.
