### ISSUE TITLE
🐛 Bug Report: In the service wizard the "MySQL" option has 2 dots at the end of the text

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7045]
------------------------------------------------------------------------------------------------------------------------------------
**Important Note for Developers:**

Please ensure that any fixes related to this issue are made against the new UI. This updated UI can be found in the 'Next' branch. Do not apply fixes to the old UI. If you have any questions or need further clarification, please reach out.

Thank you for your attention to this matter.

------------------------------------------------------------------------------------------------------------------------------------

**Steps to Reproduce:**
1. Open the service creation wizard
2. Reach the step for selecting the DB

**Expected:**
The description text for the MySQL option ends with only 1 '.'

**Actual:**
The description text for the MySQL option ends with 2 '.'

![Image](https://github.com/amplication/amplication/assets/112330500/1654310b-3324-4738-b967-2934c9715db8)

**Comment by Aditya-joshi-devl** [comment]
Hey Saurav, had the pleasure of discussing open source and Amplication with you at API day Jaipur, I'm a beginer in open source but have some experience with web dev and ML , could you assign this issue to me.

**Comment by adityavamsi** [comment]
Hello Saurav, I am new to this open source but not in web dev. Could you assign this issue to me? I want to start with a smaller one.

**Comment by vnaveenprasanth** [comment]
Hey  GreenMachine01 , I've made a PR for this. Can you check on that!

**Comment by Sukhendu2002** [comment]
Hey @souravjain540, Can you please assign this issue to me so I can work on it?

**Comment by granthpai** [comment]
Hi @souravjain540 @GreenMachine01. If the issue is still open, I would like to work on it.

**Comment by shivamrazorpay** [comment]
Hey @GreenMachine01 i have attached the PR , it is a very change. Can review it. Thank you

**Comment by astitva0011** [comment]
assign me

**Comment by anish-patro** [comment]
Can you assign me this issue @souravjain540 @GreenMachine01 , as I can contribute in this repository as my first issue.

**Comment by souravjain540** [comment]
@Aditya-joshi-devl  assigned, please let me know the updates. (ETA for this issue is 2 days)

**Comment by GreenMachine01** [comment]
------------------------------------------------------------------------------------------------------------------------------------
**Important Note for Developers:**

Please ensure that any fixes related to this issue are made against the new UI. This updated UI can be found in the 'Next' branch. Do not apply fixes to the old UI. If you have any questions or need further clarification, please reach out.

Thank you for your attention to this matter.

------------------------------------------------------------------------------------------------------------------------------------

**Comment by Aditya-joshi-devl** [comment]
Hey @GreenMachine01, thanks for the heads-up, had made the PR into main initially but updated it to next branch after going through your last message, however the text content has changed entirely on the "next" branch, not sure how helpful this issue and PR is going to be moving forward. @souravjain540 / @GreenMachine01 please review.
Thx

**Comment by GreenMachine01** [comment]
@Aditya-joshi-devl thanks for reminding me the text was updated. I am closing this request.

**Comment by GreenMachine01** [comment]
@Aditya-joshi-devl please find other items to contribute to. sorry about the mixup.
