### ISSUE TITLE
🐛 Bug Report: error on tests generated code `src/tests/auth/jwt/jwt.strategy.spec.ts`

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7046]
### What happened?

Error on running tests on generated code base in pipeline:

link: https://github.com/amplication/example-kubernetes-deployment/actions/runs/6275454946/job/17042969238

![image](https://github.com/amplication/hacktoberfest-issues/assets/73097785/ab4ac66f-eee9-4ff6-9880-09d922b95c8c)

### What you expected to happen

The testing steps on the generated code to execute with every test passing.

### How to reproduce

Generate code for a service and add github actions plugin, which in turn runs the tests on every new commit on the main branch.

### Amplication version

1.9.4

**Comment by ptdatta** [comment]
@souravjain540 @levivannoort Can I work on it?

**Comment by souravjain540** [comment]
@ptdatta assigned

**Comment by souravjain540** [comment]
@ptdatta any updates?

**Comment by ptdatta** [comment]
Will start work after #7047.

**Comment by levivannoort** [comment]
@ptdatta are you working on this or going to be working on this any time soon? It is a blocker for a piece of content we're doing.

**Comment by ptdatta** [comment]
> @ptdatta are you working on this or going to be working on this any time soon? It is a blocker for a piece of content we're doing.

My exams are going so I need another week to work on it.

**Comment by Prathyush-KKK** [comment]
I'd be happy to assist in resolving this issue. It seems to be related to module resolution, and I'll do my best to investigate and find a solution.
