### ISSUE TITLE
As a user - I want the title of the pull request created by amplication to follow convention commit guidelines

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7050]
---

Similar issue regarding commit messages - changes should be paired when releasing: https://github.com/amplication/amplication/issues/6198

---

## Feature description

The title of a pr doesnt necessarily have to follow the - although this promotes the option to automaticly release with semantic releases - https://github.com/semantic-release/semantic-release - the conventional commit spec. However the auto generated pr title in it current form doesn't match the spec - i.e., `amplication` is not a scope.

### **current form**:
```
chore(Amplication): Update Generated Code
```

---

### **proposed form - amplication-branch users**: 
_As pull request can container multiple service at the same time the scope should be abstracted from the pull request title._
```
chore: update generated code
```

### **proposed form - branch-per-resource users**: 
_As a pr is created per service, it would be nice to include the actual scope for the pr in the title, which in this case will be the name of the service. This could be based off the stigg entitlement called `feature-branch-per-resource`_
```
chore(<serviceName>): update generated code
```

**Comment by rahullli** [comment]
I would like to work on this issue .

**Comment by souravjain540** [comment]
@cp-Coder assigned to you, lmk the updates

**Comment by levivannoort** [comment]
@cp-Coder I am retracting this issue for now, after some internal talk we'd like to further spike this issue to finalize the design as there is another big issue on changing the Amplication created comments. I'll ask to re-assign you after this spike has been concluded.

**Comment by cp-Coder** [comment]
> @cp-Coder I am retracting this issue for now, after some internal talk we'd like to further spike this issue to finalize the design as there is another big issue on changing the Amplication created comments. I'll ask to re-assign you after this spike has been concluded.

Sure
