### ISSUE TITLE
As a User - I would like a more usefull feedback when pressing the version number

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7051]
### Feature description

![image](https://github.com/amplication/hacktoberfest-issues/assets/73097785/7475292b-0fb7-4386-8090-98abf16eed85)

At the moment of writing, pressing the version number leads to the version number being added to the user's clipboard. With the new adaptation of the `data-service-generator-catalog` allowing for running different version of the dsg, i'd opt for redirecting to the dsg selection menu OR going to the github releases page where the different release notes can be viewed.

### Use case

Giving the versioning in the top left corner a purpose.

**Comment by DanielLai20** [comment]
PR submitted, I added a link to the release notes on github.

**Comment by DanielLai20** [comment]
Hello, can I please have this issue assigned to me. I already created a branch and fixed the issue but my previously pull request was denied. Thank you.

**Comment by souravjain540** [comment]
@DanielLai20 assigned.
