### ISSUE TITLE
🐛 Bug Report: Code view shows two scrollbars 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#7053]
### What happened?

When viewing a file in the code view page, the code panel shows two scroll bars instead of one

![image](https://github.com/amplication/hacktoberfest-issues/assets/43705455/2219e6a6-9f5d-4e2d-a518-2db4b0ab6017)

### What you expected to happen

a single scrolbar

### How to reproduce

view a file

### Amplication version

1.8.11

**Comment by ptdatta** [comment]
@yuval-hazaz @souravjain540 I want to work on it. Please assign it to me.

**Comment by LunarMarathon** [comment]
Please re-assign this to me in case of inactivity. Thank you
(The image can't be seen)

**Comment by souravjain540** [comment]
I will assign other issues to you @ptdatta, @LunarMarathon assigning it to you.

**Comment by levivannoort** [comment]
This has since been merged.
