### ISSUE TITLE
🐛 Bug Report: Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [amplication/amplication#7059]
### What happened?

The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

URL 
https://amplication.com/

ScreenShot
<img width="916" alt="Screenshot 2023-09-08 100840" src="https://github.com/amplication/amplication/assets/91591901/a6cdda68-e9da-49ac-b666-940fe0c20bc3">

### What you expected to happen

The Twitter logo should be changed to X

### How to reproduce

Scroll to the footer section and see Twitter old logo

@yuval-hazaz 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AyushDhimanIITR** [comment]
Can I work on it?

**Comment by granthpai** [comment]
Hi @souravjain540 @GreenMachine01. If the issue is still open, I would like to work on it.

**Comment by lalitkumawat1m** [comment]
Hello Team, 
I want to work on this issue please assign it to me

**Comment by Vishrut19** [comment]
I want to work on it. Please assign me!

**Comment by astitva0011** [comment]
i want to work on this
assign me

**Comment by souravjain540** [comment]
@lalitkumawat1m assigned it to you.

**Comment by Kkartik14** [comment]
I would like to work on this
Assign it to me

**Comment by Tejodeep2002** [comment]
I like to work

**Comment by deauthe** [comment]
Can i still work on the issue even though it's assigned?
