### ISSUE TITLE
As User - I want to be offered to select my repo automatically after connecting to my git org

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7072]
![Image](https://github.com/amplication/amplication/assets/112330500/831a8a67-8adb-4da9-8798-db1493033c4b)

**Overview:**
Currently, after the user successfully connects to his Git provider he needs to click again to select the repo he wants to use.
The need to perform an additional click can be saved and help more users complete the task of selecting a repo.

**Requirements:**
1. Immediately after a successful connection to a Git provider, the system should prompt the user with the list of accessible repositories from the selected Git org.

**Comment by cherish2003** [comment]
@souravjain540 i want to work on this issue can you assign me

**Comment by souravjain540** [comment]
> After starting the project locally, after I create & sign in with a account, if I click "Connect with Github", the URL of the pop-up window is **[http://localhost:3001/[github-app-installation-url]](http://localhost:3001/%5Bgithub-app-installation-url%5D)** , which is wrong.
> 
> I am not sure if it is part of this issue, should I create a new issue for this ?
> 
> <img alt="Screenshot 2023-09-23 at 5 58 34 PM" width="1724" src="https://user-images.githubusercontent.com/72980748/270139221-d8053053-b37f-4aee-be22-9a40286420db.png"> <img alt="Screenshot 2023-09-23 at 5 59 24 PM" width="1728" src="https://user-images.githubusercontent.com/72980748/270139222-c85c9976-b07f-4355-a9a8-0cc318787046.png">

this is not wrong, you have to follow these steps: https://docs.amplication.com/running-amplication-platform/connect-server-to-github/

**Comment by souravjain540** [comment]
@pawpaw2022 any updates

**Comment by pawpaw2022** [comment]
all done, i am ready to make a pull request

**Comment by pawpaw2022** [comment]
> @pawpaw2022 any updates

Just submitted a PR, please let me know if there is any issue :)

**Comment by souravjain540** [comment]
@pawpaw2022 please mention the issue number in the PR. Its a must.
