### ISSUE TITLE
As a User - I want to have a more precise idea of when my PR creation process starts

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7076]
### Feature description

Currently, the PR creation process only shows 3 messages and sometime it seems stack on the following message
> Starting to push changes to  

It would be great to know when the process really start and when it is waiting for a worker to be picked up.

Please use these texts:
1. "Pull request creation job added to queue. Waiting for available worker..."
2. "Worker assigned. Starting pull request creation..."

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by overbit** [comment]
Related to the issue https://github.com/amplication/private-issues/issues/44

**Comment by mulygottlieb** [comment]
@overbit, I do not think that the Product team has seen this issue, prioritized it, approved the texts, etc.  Let's make sure we keep @GreenMachine01 in the loop before we start coding.

**Comment by GreenMachine01** [comment]
@mulygottlieb @overbit I actually had this item in the backlog - https://github.com/amplication/amplication/issues/6530

**Comment by mulygottlieb** [comment]
@GreenMachine01 This is similar but a bit different. We can discuss it tomorrow with @overbit

**Comment by GreenMachine01** [comment]
@overbit 
Please use these texts:
1. "Pull request creation job added to queue. Waiting for available worker..."
2. "Worker assigned. Starting pull request creation..."

**Comment by GreenMachine01** [comment]
@overbit Lets try one line and see how it feels.
