### ISSUE TITLE
As New User - I want to describe the service I wish to build so that Amplication AI can generate relevant data models

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7087]
![Image](https://github.com/amplication/amplication/assets/112330500/bbde2634-476c-4748-8ec7-272cbc7b2bd6)

**Acceptance Criteria:**

1. Service Description Screen:
    -    After the welcome step in the onboarding, The user should be presented with a screen that matches the provided design, prompting him to describe the service he is trying to build.
    - The user should not encounter a separate screen requesting the service name.

2. Continuation of Onboarding:
    -    Once the user entered the service description, he should be able to proceed with the rest of the service creation wizard flow.
    -    Behind the scenes, the AI should start processing the user description to produce a schema file. This schema will be used to populate the service with entities, fields, and relations.

3. AI Processing Feedback:
    -    If the user reaches the end of the onboarding process and the AI is still processing his description, the user should see an "in progress" loader.
    -    The loader should match the provided design example and clearly indicate that the system is waiting for the AI to finish generating the data models.

Figma - https://www.figma.com/file/6EyBvXQvvhpCb2AAImzH3D/Using-AI-for-generating-entities?type=design&node-id=2041%3A14924&mode=design&t=j7zYkWwleBUeKChG-1

**Comment by asi309** [comment]
Hi,
I would like to work on this issue. Please assign it to me

**Comment by overbit** [comment]
@PazYanoverr / @mulygottlieb  is this still valid?

**Comment by PazYanoverr** [comment]
@overbit - for now- this ticket is on-hold / not relevant

**Comment by yuval-hazaz** [comment]
not relevant since we have Jovu. closing
