### ISSUE TITLE
As New User - I want to select from existing service suggestions if I'm unsure about my requirements

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7089]
Relates to - https://github.com/amplication/amplication/issues/7087

![Image](https://github.com/amplication/amplication/assets/112330500/911c97a5-8ccc-4f66-974b-ce47d1a177a8)

1. In the new AI description step allow the user to pick from 4 AI suggestions to populate his service description input box.
2. Allow the user to generate 4 new options if he doesn't find what he is looking for

**Comment by asi309** [comment]
Hi @GreenMachine01,
I would like to work on this. Please assign it to me.
