### ISSUE TITLE
Improvement in login page.

### ISSUE THREAD

**Issue by Owais24code** [amplication/amplication#7095]
### Feature description

login page improvements Assign this issue to me as contributor hacktoberfest2023.

![Uploading Screenshot 2023-10-02 122931.png…]()

### Use case

join discord community must hover and improve the styling of a login page and add a better welcome message to the page.

### Are you willing to submit PR?

Yes, I am willing to submit a PR!

**Comment by souravjain540** [comment]
@Owais24code can't see the screenshot
