### ISSUE TITLE
🐛 Bug Report: Copying custom attributes during schema import on the ID field when we already take care of the ID field

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7096]
The issue is with custom attributes such as 'Default' and 'Id'
custom attributes should be copied only if they are not supported by Amplication out of the box.

**Comment by sidling1** [comment]
Can i look into it ?

**Comment by GreenMachine01** [comment]
@sidling1 This item needs to be done by our internal team. Thanks! I hope you can find other items to contribute to. search for the "open to community" label.
