### ISSUE TITLE
🐛 Bug Report: align pending changes style with the design

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#7097]
### What happened?

align pending changes style with the v2 design in figma 

### What you expected to happen

align pending changes style with the v2 design in figma 

### How to reproduce

see ui

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/fc3ffc3e-7d58-41d9-b484-31c62d5eda91)
