### ISSUE TITLE
🐛 Bug Report: `PR Labeler` fails on contributors pull requests

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7100]
### What happened?

Currently the `PR labeler` GitHub workflow fails on contributors pull requests as shown here
https://github.com/amplication/amplication/actions/runs/6340524843/job/17288607782?pr=7011

### What you expected to happen

`PR labeler` to finish without errors

### How to reproduce

Raise a new community PR and observe the github action failing

## Tech notes

Check this blog to solve this issue: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by mulygottlieb** [comment]
I am in favor of prioritizing this @GreenMachine01 in particular now towards Hacktoberfest

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/1e453497-05b5-41bc-a941-03f7c80f4e42)
