### ISSUE TITLE
🐛 Bug Report: error when installing a generated helm chart

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7106]
### What happened?

When trying to install a helm chart for a generated service to the cluster, an error was shown, because some of the values that are populated via the .env of the service contained booleans. These have to be changed to strings to be able to install the configmap onto the cluster.

### What you expected to happen

A generated helm chart which can be installed on the cluster without an error shown.

### How to reproduce

Install helm chart plugin (version: 1.0.1) on a generated service and install into a kubernetes cluster.

### Amplication version

1.9.5

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by levivannoort** [comment]
![image](https://github.com/amplication/amplication/assets/73097785/68298eb9-94ca-49b7-aee1-294e825ea94e)

**Comment by GreenMachine01** [comment]
Milestone 1.10.0
