### ISSUE TITLE
Show categories on the `plugins` tab of a service

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7109]
------------------------------------------------------------------------------------------------------------------------------------
**Important Note for Developers:**

Please ensure that any fixes related to this issue are made against the new UI. This updated UI can be found in the `next` branch. Do not apply fixes to the old UI. If you have any questions or need further clarification, please reach out.

Thank you for your attention to this matter.

------------------------------------------------------------------------------------------------------------------------------------

### Feature description

Within the `amplication/plugin-catalog` repository each of the plugins are supplemented with `category data` as can be seen here: https://github.com/amplication/plugin-catalog/blob/master/plugins/deployment-helm-chart.yml

![image](https://github.com/amplication/amplication/assets/73097785/e81ab257-5435-4bd4-89b5-48768b75a280)

As can be seen in the original design, categories of different plugins are shown. I think it would be nice to change the `All Plugins` header to `Catalog` and under that filter the different plugins in the different catagories.

This could then also be implemented on the website, here: https://amplication.com/plugins

### Use case

With our plugin catalog becoming bigger, it would be nice to be able to navigate more easily on the category type for all plugins available.

**Comment by levivannoort** [comment]
![image](https://github.com/amplication/amplication/assets/73097785/f5e6c3d9-b0af-4f38-9d1c-10f0a249eb4d)

[Figma](https://www.figma.com/file/WeoGDXg8j0svKfGICORfww/Application-v2---Main-screen-%2B-On-boarding?type=design&node-id=269%3A7437&mode=design&t=muvirqMvfGdsrdN7-1)

**Comment by levivannoort** [comment]
------------------------------------------------------------------------------------------------------------------------------------
**Important Note for Developers:**

Please ensure that any fixes related to this issue are made against the new UI. This updated UI can be found in the `Next` branch. Do not apply fixes to the old UI. If you have any questions or need further clarification, please reach out.

Thank you for your attention to this matter.

------------------------------------------------------------------------------------------------------------------------------------

**Comment by CoderGhost37** [comment]
@levivannoort can I work on this issue?

**Comment by levivannoort** [comment]
Sure! assigned to @CoderGhost37

**Comment by souravjain540** [comment]
@CoderGhost37 any updates?

**Comment by Abhi3685** [comment]
Hi @levivannoort @souravjain540 Can you assign this to me?
Does it involve backend changes too? Should we get all the plugins and then filter them based on the selected category?
Or fetch just the selected category plugins? I see the categories is not yet visible in the API response which shouldn't be an issue as it can be easily added to GraphQL queries.

**Comment by jatingodnani** [comment]
> **Important Note for Developers:**
> 
> Please ensure that any fixes related to this issue are made against the new UI. This updated UI can be found in the `Next` branch. Do not apply fixes to the old UI. If you have any questions or need further clarification, please reach out.
> 
> Thank you for your attention to this matter.
> 
> ### Feature description
> Within the `amplication/plugin-catalog` repository each of the plugins are supplemented with `category data` as can be seen here: https://github.com/amplication/plugin-catalog/blob/master/plugins/deployment-helm-chart.yml
> 
> ![image](https://user-images.githubusercontent.com/73097785/271995274-e81ab257-5435-4bd4-89b5-48768b75a280.png)
> 
> As can be seen in the original design, categories of different plugins are shown. I think it would be nice to change the `All Plugins` header to `Catalog` and under that filter the different plugins in the different catagories.
> 
> This could then also be implemented on the website, here: https://amplication.com/plugins
> 
> ### Use case
> With our plugin catalog becoming bigger, it would be nice to be able to navigate more easily on the category type for all plugins available.

I am not understand your first few lines if i change my branch from master to Next it showing this . 
![IMG-20231017-WA0029](https://github.com/amplication/amplication/assets/97869761/6c18be05-b2ba-4ba8-9fca-fbb1e14b0ef6)
help needed @levivannoort  @souravjain540

**Comment by jatingodnani** [comment]
> **Important Note for Developers:**
> 
> Please ensure that any fixes related to this issue are made against the new UI. This updated UI can be found in the `Next` branch. Do not apply fixes to the old UI. If you have any questions or need further clarification, please reach out.
> 
> Thank you for your attention to this matter.
> 
> ### Feature description
> Within the `amplication/plugin-catalog` repository each of the plugins are supplemented with `category data` as can be seen here: https://github.com/amplication/plugin-catalog/blob/master/plugins/deployment-helm-chart.yml
> 
> ![image](https://user-images.githubusercontent.com/73097785/271995274-e81ab257-5435-4bd4-89b5-48768b75a280.png)
> 
> As can be seen in the original design, categories of different plugins are shown. I think it would be nice to change the `All Plugins` header to `Catalog` and under that filter the different plugins in the different catagories.
> 
> This could then also be implemented on the website, here: https://amplication.com/plugins
> 
> ### Use case
> With our plugin catalog becoming bigger, it would be nice to be able to navigate more easily on the category type for all plugins available.

I am not understand your first few lines if i change my branch from master to Next it showing me this
help needed @levivannoort  @souravjain540 
![Uploading 2e3d712e-4089-4623-a43d-2e52e7f4a57c.jpg…]()

**Comment by jatingodnani** [comment]
@levivannoort assign me this issue

**Comment by jatingodnani** [comment]
> **Important Note for Developers:**
> 
> Please ensure that any fixes related to this issue are made against the new UI. This updated UI can be found in the `next` branch. Do not apply fixes to the old UI. If you have any questions or need further clarification, please reach out.
> 
> Thank you for your attention to this matter.
> 
> ### Feature description
> Within the `amplication/plugin-catalog` repository each of the plugins are supplemented with `category data` as can be seen here: https://github.com/amplication/plugin-catalog/blob/master/plugins/deployment-helm-chart.yml
> 
> ![image](https://user-images.githubusercontent.com/73097785/271995274-e81ab257-5435-4bd4-89b5-48768b75a280.png)
> 
> As can be seen in the original design, categories of different plugins are shown. I think it would be nice to change the `All Plugins` header to `Catalog` and under that filter the different plugins in the different catagories.
> 
> This could then also be implemented on the website, here: https://amplication.com/plugins
> 
> ### Use case
> With our plugin catalog becoming bigger, it would be nice to be able to navigate more easily on the category type for all plugins available.

I am not understand your first few lines if i change my branch from master to Next it showing me this
help needed @levivannoort @souravjain54
![2e3d712e-4089-4623-a43d-2e52e7f4a57c](https://github.com/amplication/amplication/assets/97869761/7043cb67-cd4c-4181-9095-cd0c84deaf40)

**Comment by mulygottlieb** [comment]
@CoderGhost37, since there were no updates from you in the last two weeks I am unassigning this from you.

**Comment by jatingodnani** [comment]
@mulygottlieb assign me this

**Comment by mulygottlieb** [comment]
@Abhi3685 I am assigning this to you since you are the second person who asked about it.
You are correct that server changes need to be performed as well. 
"Should we get all the plugins and then filter based on the selected category?" - Yes.

Note that, as you mentioned, the categories are currently not returned to the client, so you need to work on adding the categories to the response from the plugin-api.
Look into `packages/amplication-plugin-api/src/plugin/github-plugin.service.ts`, 
`packages/amplication-client/src/Plugins/hooks/usePlugins.ts`, and
`packages/amplication-client/src/Plugins/queries/pluginsQueries.ts`

**Comment by mulygottlieb** [comment]
@Abhi3685, please note that the categories are an array, so the same plugin can appear in multiple categories. The list of categories shown in the UI should be dynamic and contain the union of all the categories that were returned from all the plugins.

**Comment by Abhi3685** [comment]
Ohk @mulygottlieb, In the code also, it was being treated as string and hence the confusion. Thanks for your confirmation.
https://github.com/amplication/amplication/blob/master/packages/amplication-plugin-api/src/plugin/plugin.types.ts

**Comment by mulygottlieb** [comment]
@Abhi3685 you should test it yourself but I assume the string is a comma-separated string of categories e.g "aws, terraform, db" which is one string with three categories.

**Comment by jatingodnani** [comment]
@mulygottlieb can i work on this issue. Should i need to make menu to navigate between the plugins

**Comment by Abhi3685** [comment]
Just an update, I will try to wind up my changes by this weekend based on my understanding and will keep you all posted

**Comment by Abhi3685** [comment]
Hello @mulygottlieb, @levivannoort,
I had so much fun working on this one end-to-end considering this is my first assignment on Amplication.
I would request your valuable review on the PR. Please excuse me for any obvious mistakes that I might have made as I am still learning. Thanks for giving me a chance to contribute to Amplication!

**Comment by mulygottlieb** [comment]
Thanks a lot @Abhi3685 
we will review shortly

**Comment by Abhi3685** [comment]
The status for PR seems to be wrong. It should be changed from `Code changes requested` to `PR waiting for review`

**Comment by mulygottlieb** [comment]
This issue was handled as part of another epic - closing
