### ISSUE TITLE
🐛 Bug Report: Missing the ERD view in the new UI

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7114]
**Expected:**
The user can view and use the ERD view in the new UI

**Actual:**
The ERD view shows an empty page

![Image](https://github.com/amplication/amplication/assets/112330500/5587ee0c-6425-4b64-b2a6-d74c760f4f11)

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/334a1dc5-c92d-4d0e-8ee6-d88bce2d1c5e)
