### ISSUE TITLE
Publish/Deployment: counter bug

### ISSUE THREAD

**Issue by isabr85** [amplication/amplication#712]
When deploying or publishing new version, counter is indicating invalid time (-1h -1m -2s) and counting forward for few seconds and then it going back to normal and start from 0.

**To Reproduce**
1. Make a change in your app (add new entity)
2. Commit and publish your changes
3. Look at the counter below

![image](https://user-images.githubusercontent.com/11903954/97210999-126d0f00-17c7-11eb-908a-4f026f5abe89.png)

Desktop:
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.75

**Comment by yam-golombek** [comment]
@isabr85 thank you for your first contribution!

**Comment by iddan** [comment]
@yuval-hazaz can this be closed?

**Comment by yuval-hazaz** [comment]
Yes, the component was re-structured entirley
