### ISSUE TITLE
🐛 Bug Report: tooltip on `logout`

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7121]
------------------------------------------------------------------------------------------------------------------------------------
**Important Note for Developers:**

Please ensure that any fixes related to this issue are made against the new UI. This updated UI can be found in the `Next` branch. Do not apply fixes to the old UI. If you have any questions or need further clarification, please reach out.

Thank you for your attention to this matter.

------------------------------------------------------------------------------------------------------------------------------------

### What happened?

In the top right corner various buttons have tooltips, but the most right button used for logging the user out of the application doesnt have a tooltip.

![image](https://github.com/amplication/amplication/assets/73097785/652cb760-9e5c-426d-9726-9c1a3393d508)

### What you expected to happen

Similar to the search button I would expect `Logout` when hovering over the button in top right corner.

![image](https://github.com/amplication/amplication/assets/73097785/53efcd08-ff1f-4741-b01c-a8b28b7aeffd)

### How to reproduce

Navigate to the top right corner on a project and see that there is no tooltip.

### Amplication version

1.9.5

### Environment

branch: `NEXT`

**Comment by Sheersendu** [comment]
I would like to work on this issue, please assign it to me @levivannoort

**Comment by souravjain540** [comment]
assigned @Sheersendu, please lmk the updates

**Comment by Sheersendu** [comment]
Issue has been fixed and PR has been raised @souravjain540

**Comment by Sheersendu** [comment]
@souravjain540 , @GreenMachine01 do let me know my next steps! Thanks :)

**Comment by Sheersendu** [comment]
@souravjain540 , @GreenMachine01 the issue has been assigned to me for which PR has already been created but some other PR has been linked to it. Kindly look in to it!

**Comment by Sheersendu** [comment]
Thanks @souravjain540 :heart:

**Comment by morhag90** [comment]
Passed QA:
<img width="395" alt="image" src="https://github.com/amplication/amplication/assets/97830649/6114ebc7-8349-42fd-b1fa-ada349a34225">
