### ISSUE TITLE
🐛 Bug Report: On PR to master E2E workflow is running twice for no reason 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7126]
### What happened?

<img width="857" alt="image" src="https://github.com/amplication/amplication/assets/2861984/eb47db74-c3b9-44dd-910b-a1adf4dbdffe">

i.e. 
https://github.com/amplication/amplication/pull/6873 

### What you expected to happen

E2E to be run only once in the PR from `next` to `master`.

Same solution implemented here: https://github.com/amplication/amplication/issues/6957

### How to reproduce

.

**Comment by martinez-hugo** [comment]
Hi ! Can I work on this issue ?
