### ISSUE TITLE
🐛 Bug Report: Release apps workflow should include all changes to the release notes

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7129]
### What happened?

Currently, the release notes only include PR with code that affect any app or library apart from `data-service-generator` leaving PRs for CI files or other repository files behind.

### What you expected to happen

The release notes should consists of the following categories:
- What's changed in amplication apps? _(changes that affect any app apart from  `data-service-generator`)_
- What's changed in the libraries? _(changes that affect any library)_
- Other changes _(changes to Github actions, checks, markdown, root files)_

### How to reproduce

.

**Comment by martinez-hugo** [comment]
Hi ! Can I work on this issue ?
