### ISSUE TITLE
🐛 Bug Report: "Next" button not working properly on Getting started

### ISSUE THREAD

**Issue by guptadeepak8** [amplication/amplication#7130]
### What happened?

On the documentation page for getting started, there is a "Next" button that is intended to link to the next page of the documentation. However, it seems that this button is not functioning correctly.

### What you expected to happen

the link to the next page may not be properly attached only for Getting started.   

### How to reproduce

1. Go to the Getting Started documentation page.
2. Scroll down to the bottom of the page.
3. Locate the "Next" button, which is intended to take you to the next page of the documentation.
4. Click on the "Next" button and observe the behavior.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by martinez-hugo** [comment]
Hi ! Can I work on this issue ?

**Comment by AyushDhimanIITR** [comment]
Hey @guptadeepak8 , can I work on this?

**Comment by Yashgupta9330** [comment]
i want to work on this issue?
