### ISSUE TITLE
As Dev - I want to fix spelling mistakes in the code

### ISSUE THREAD

**Issue by jbampton** [amplication/amplication#7147]
Please revert this single change and then the matching changes in all the *.snap files - we wish to exclude the changes to the generated code from this PR. You can open a new issue and submit a PR just for this change separately (with the matching *.snap files)

_Originally posted by @mulygottlieb in https://github.com/amplication/amplication/pull/7085#discussion_r1343773504_

This issue is for fixing spelling mistakes in the codebase.

Please assign me to this issue. Thanks !

**Comment by mulygottlieb** [comment]
Passed QA:
![image](https://github.com/amplication/amplication/assets/1912933/c268eb3c-d26f-42f9-998a-27ea833b5fd3)
