### ISSUE TITLE
🐛 Bug Report: Fix plugin template bundling configuration

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7150]
### What happened?

As reported in https://github.com/amplication/amplication/issues/7104, plugins are meant to be bundled with all their dependencies to avoid.

Currently the plugin template is excluding from the bundle any node dependency and this is not correct.

This issue is in regards of updating the plugin template bundler configuration by replacing the externals   
```ts
module.exports = {
   // ...
   externals: [nodeExternals()]
   // ...
};
```
with:
```ts
module.exports = {
   // ...
  externals: ["@amplication/code-gen-utils", "@amplication/code-gen-types"],
   // ...
};
```

and remove the dependency to `webpack-node-externals`.

### What you expected to happen

Plugin template to bundle all its dependencies

### How to reproduce

Check the bundled code

### Acceptance criteria

both, the plugin template repo https://github.com/amplication/plugin-template and the plugin-template in the plugins repo https://github.com/amplication/plugins need to be updated

**Comment by trishanu-init** [comment]
@overbit Can you assign me this issue? I want to work on it

**Comment by overbit** [comment]
@trishanu-init done! Let me know if you have any questions

**Comment by overbit** [comment]
@trishanu-init any updates on this?

**Comment by trishanu-init** [comment]
I am working on it please allow me some time

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by overbit** [comment]
@trishanu-init Check again the description. I've just updated it.

**Comment by trishanu-init** [comment]
@overbit I have created the PR please review it and merge it
