### ISSUE TITLE
🐛 Bug Report: GitHub icon used when not connected to a git provider instead of the generic Git icon

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7151]
------------------------------------------------------------------------------------------------------------------------------------
**Important Note for Developers:**

Please ensure that any fixes related to this issue are made against the `Next` branch. If you have any questions or need further clarification, please reach out.

Thank you for your attention to this matter.

------------------------------------------------------------------------------------------------------------------------------------

**Steps to Reproduce:**

1. Create a new project and make sure it is not connected to a Git provider
2. Create a new service and inherit the Git provider from the project settings
3. Go to the Project page to view all your services

**Actual:**
The new service shows it is not connected to a Git provider but it uses the GitHub icon

![Image](https://github.com/amplication/amplication/assets/112330500/530bf92e-792e-425f-8e04-2d4beaecfb16)

**Expected:**
The new service shows it is not connected to a Git provider and it uses the generic Git icon

![Image](https://github.com/amplication/amplication/assets/112330500/8b84b9aa-6a62-4168-80a9-9a8982033da7)

**Comment by GreenMachine01** [comment]
@souravjain540 - FYI

**Comment by xonx4l** [comment]
I made a pr please check .Thanks.

**Comment by trishanu-init** [comment]
@GreenMachine01 can you assign me this issue

**Comment by GreenMachine01** [comment]
@souravjain540 - FYI

**Comment by ankushbhardwaj408** [comment]
Hi @souravjain540  I would like to work on this.

**Comment by yuval-hazaz** [comment]
I think the GitHub Icon make more sense to most users and we should leave it

**Comment by GreenMachine01** [comment]
@xonx4l I assigned to you as you requested first and provided a PR. the team will check it.

**Comment by xonx4l** [comment]
THANKS @GreenMachine01 .

**Comment by mulygottlieb** [comment]
> I think the GitHub Icon make more sense to most users and we should leave it

Closing this ticket based on this comment
