### ISSUE TITLE
Responsive issues : version text covers the content behind and navbar padding-top covers behind content.

### ISSUE THREAD

**Issue by Abhivic000** [amplication/amplication#7153]
## Related Issue
To make changes for fully Responsive home page

## Description of Changes
To change in margin, padding and text

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| [Original screenshot](https://drive.google.com/file/d/1ZhLkU-qHTdH0sIAwa_CHzLDuf76fa2mh/view?usp=sharing) | [Updated screenshot](https://drive.google.com/file/d/1hqFo81JS5cBZ2SFpURgh7pJpyyG_mO7E/view?usp=sharing) |

**Comment by Abhivic000** [comment]
Hi, Can you assign it to me I'm working on it.

**Comment by ShreyasMandlik** [comment]
Hi, Would like to work on this can you assign it to me.
