### ISSUE TITLE
🐛 Bug Report: Local development environment fails to create PR

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7155]
### What happened?

<img width="905" alt="MicrosoftTeams-image" src="https://github.com/amplication/amplication/assets/2861984/67e3b2b9-bc7c-49a1-8e63-56f651be57cb">

### What you expected to happen

The generated code gets pushed to the git provider successfully as a pull request

### How to reproduce

Start the local development environment without any billing key and try to build a new service with a git provider connection.

**Comment by morhag90** [comment]
Passed QA:

<img width="1265" alt="image" src="https://github.com/amplication/amplication/assets/97830649/ff6c61d7-a9c5-4fbf-8501-7d8d31f54730">
