### ISSUE TITLE
🐛 Bug Report: The base properties of the ID field cannot be edited

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#7164]
### What happened?

When users try o edit the Custom Attributes field of an ID field, they get the following error

<img width="810" alt="image" src="https://github.com/amplication/amplication/assets/43705455/4a71ce1d-fb4c-4191-baab-b057a73088a8">

### What you expected to happen

be able to edit the "Custom attributes" field

### How to reproduce

import schema with attributes on the ID field and then try to edit the attributes

### Amplication version

1.10.0

**Comment by ayush4345** [comment]
Hey, is this issue open to work on ?

**Comment by ayush4345** [comment]
Can I work on this issue ?
