### ISSUE TITLE
🐛 Bug Report: text for delete project button should be aligned to the middle

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7177]
### What happened?

<img width="899" alt="image" src="https://github.com/amplication/amplication/assets/73097785/3236ddef-a1fd-4837-9f92-d1016114240b">

### What you expected to happen

Should be middle left side of the box, instead of top left.

### How to reproduce

Go to the settings part of a project.

### Amplication version

1.10.1

**Comment by hassansuhaib** [comment]
I would like to work on this

**Comment by levivannoort** [comment]
@hassansuhaib assigned!

**Comment by vnaveenprasanth** [comment]
I would like to take up this if available!  @levivannoort

**Comment by souravjain540** [comment]
@hassansuhaib  any updates?

**Comment by hassansuhaib** [comment]
I was having problems with running my development environment. I will be creating a PR tonight @souravjain540

**Comment by souravjain540** [comment]
@hassansuhaib if you can't raise a PR right now, someone has already, if you don't mind i can assign issue to him.

**Comment by hassansuhaib** [comment]
Ok go ahead @souravjain540

**Comment by sanskar-soni-9** [comment]
@samerosenberg I'm eager to work on this issue if it becomes available.

**Comment by sanskar-soni-9** [comment]
RThanks @souravjain540, looking forward to getting this assigned and getting my PR merged.

**Comment by sanskar-soni-9** [comment]
@souravjain540 PR is already merged.
