### ISSUE TITLE
🐛 Bug Report: Matching and fixing Invalid Input Icon

### ISSUE THREAD

**Issue by NXKED** [amplication/amplication#7184]
### What happened?

Mismatched or non consistent design on the info circle amp icon.

Some are completely mission, others are not centered and in general not uniform.

### What you expected to happen

![Screenshot 2023-10-06 190648](https://github.com/amplication/amplication/assets/107938013/dbb8125f-e191-4be6-b1c9-2adbea50c76b)
![Screenshot 2023-10-06 164752](https://github.com/amplication/amplication/assets/107938013/ded1b1f5-03bc-4b21-84e0-a62d35fcbe97)
![Screenshot 2023-10-06 190601](https://github.com/amplication/amplication/assets/107938013/c30a3c49-a6d1-4b68-ba32-64f819fe8649)

### How to reproduce

Check out User Profile Settings, Entities/General Settings etc. 
Various input fields.

### Amplication version

v1.10.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by harshit-senpai** [comment]
hey if the issue is valid I would like to work on it.

**Comment by NXKED** [comment]
In case my Issue is valid, could I please get assigned, so I can work on it?
