### ISSUE TITLE
🐛 Bug Report: Update Twitter Icon with new X icon

### ISSUE THREAD

**Issue by gauravxroy** [amplication/amplication#7193]
### What happened?

Issue Description:
The current Twitter icon used on the website  https://amplication.com/  in the footer section is outdated and does not align with the latest branding or design standards. This issue was created to request an update to the Twitter icon to X.

Current Twitter Icon: 
<img width="288" alt="outdated twitter icon" src="https://github.com/amplication/amplication/assets/96660449/66348a61-f1be-45db-bec4-8c1195692584">

Desired Twitter Icon: 
<img width="146" alt="new icon" src="https://github.com/amplication/amplication/assets/96660449/24758cfd-e977-4f5f-b46b-eca30e8b75eb">

.

### What you expected to happen

We expect that upon addressing this issue, the following will happen:

New Twitter Icon: The outdated Twitter icon currently in use will be replaced with the updated Twitter X-icon in the footer section as specified in this issue.

Visual Consistency: The updated icon will align with the latest branding guidelines, ensuring visual consistency across the website.

Improved Aesthetics: The updated Twitter  X-icon will enhance the overall aesthetics of the platform, contributing to a more modern and appealing user interface.

### How to reproduce

Here's how you can provide instructions for updating the icon:

Reproduction Steps for Changing Outdated Twitter Icon in Footer Section:

Locate the Current Icon:

Go to the web page or application where the outdated Twitter icon is displayed in the footer section.
Identify the Current Icon:

Find the specific location of the outdated Twitter icon in the footer.
Access the Source Code:

Depending on your development environment, access the source code of the web page or application where the footer section is defined.

Replace the Icon:
Locate the HTML/JSX code responsible for displaying the Twitter icon in the footer.
Replace the existing code or image source link with the new Twitter icon image or code.

**Comment by Paulie-Aditya** [comment]
can I get assigned to this?

**Comment by sha0urya** [comment]
Can you please assign me this issue under hacktoberfest so that I can send a PR ?

**Comment by Yash-Ambekar** [comment]
The source code of the footer can be found on the amplication-site repository and not this repository. 
Link to source code: https://github.com/amplication/amplication-site/blob/main/components/Footer/FooterBottomBar/index.jsx
