### ISSUE TITLE
🐛 Bug Report: `data-service-generator` fails to package into a container image

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7197]
### What happened?

https://github.com/amplication/amplication/actions/runs/6456771127/job/17527432370

### What you expected to happen

To build properly

### How to reproduce

run `npx nx package:container data-service-generator`

### Amplication version

next

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mulygottlieb** [comment]
Passed QA:
![image](https://github.com/amplication/amplication/assets/1912933/6286577a-0b1a-4a39-b8a9-c6092f272bf1)
 (and the CI now runs successfully)
