### ISSUE TITLE
As a Developer - I want to see the entity name (like in older UI version)

### ISSUE THREAD

**Issue by vincenzodomina** [amplication/amplication#7217]
### Feature description

I can't see the Entity name anymore like in the older UI version, which makes it more burdensome to navigate the new Amplication UI.

![image](https://github.com/amplication/amplication/assets/54762917/e158b89e-8846-48c5-8faa-05640cc5f96b)

### Use case

When creating a new Entity and navigating to the Entity detail page, I don't know anymore in which entity I am because I don't see the name, so I have to navigate back and select the entity again or look into the "General Settings" tab

**Comment by yuval-hazaz** [comment]
Thanks @vincenzodomina 
I agree that the entity name is missing. We will take it internally to think of a system-wide solution (for things like role name, energy name, and other titles for future pages )
Feel free to suggest any idea you may have.

**Comment by yuval-hazaz** [comment]
@vishalhampiholi this issue is not ready for dev yet. @alexbass86 @GreenMachine01 let's discuss this soon, so we can assign it to the community

**Comment by PazYanoverr** [comment]
Thanks @vishalhampiholi!
https://github.com/amplication/amplication/pull/7850 is merged (soon in production) and should also handle this issue.
You are welcome to check it and share your feedback!
