### ISSUE TITLE
🐛 Bug Report: CI failing to release in production

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7224]
### What happened?

https://github.com/amplication/amplication/actions/runs/6482409905/job/17601878662

https://github.com/amplication/amplication/actions/runs/6482784175/job/17602984696

### What you expected to happen

.

### How to reproduce

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by levivannoort** [comment]
![image](https://github.com/amplication/amplication/assets/73097785/95a8df00-e190-40bc-9a5a-ac596f8522b3)
