### ISSUE TITLE
Client: New roles isn't display in entities page until refresh the page

### ISSUE THREAD

**Issue by yoni10** [amplication/amplication#723]
**Describe the bug**

**To Reproduce**
1. Go to 'Roles' page and create new role
2. Go to 'Entities' page > Permision section > choose Granular.

**Expected behavior**
the new created role will be displayed.

**Actual behavior**
The new role isn't displayed until refresh the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/10399248/97344618-a5727b80-1891-11eb-9783-583dc351d3e5.png)

![image](https://user-images.githubusercontent.com/10399248/97344725-ce930c00-1891-11eb-9be5-61c21c1798b1.png)

**Comment by iddan** [comment]
Hey Yoni, thank you for reporting this bug. We will take care of it in the next release.
