### ISSUE TITLE
🐛 Bug Report: Services with field Id type AUTO_INCREMENT_BIG_INT fail to build 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7230]
### What happened?

The generated code of a service with at least one entity with a field id of type `AUTO_INCREMENT_BIG_INT` with a relation with another entity, fail to build due to the following type issues:

<img width="1038" alt="image" src="https://github.com/amplication/amplication/assets/2861984/e9da35ff-f708-47b3-a384-dcf6e52f7fa8">

<img width="1021" alt="image" src="https://github.com/amplication/amplication/assets/2861984/f7fc6995-9490-48df-9547-221637598b68">

### What you expected to happen

A buildable service get created

### How to reproduce

Either create a service as mention above, or use the following `input.json` and run `npx nx generate-local-code data-service-generator`

### Amplication version

v1.10.12

**Comment by Meyazhagan** [comment]
@overbit I would like to work on this issue, can you assign to me
