### ISSUE TITLE
🐛 Bug Report: 'Close' CTA is in the wrong position in the service creation wizard

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7234]
**Actual:**
The close option is located at the top **center** of the screen
![Image](https://github.com/amplication/amplication/assets/112330500/35a7e81d-dce4-4bce-b6e3-0ed5725b3e7e)

**Expected:**
The close option is located at the top **right** side of the screen
![Image](https://github.com/amplication/amplication/assets/112330500/6a57b72d-3794-49ac-bd8b-0a69365d5bff)

**Comment by HeetVekariya** [comment]
- I would like to work on this issue, can you please assign it to me.
- I think i just need to change the css, but i don't able to see the ```x Close``` in the website.

![image](https://github.com/amplication/amplication/assets/91054457/1c32490a-a296-4d6e-aba1-adf6db92889d)

**Comment by GreenMachine01** [comment]
@HeetVekariya during the first time a user creates a service we do not show the cancel option. create a second service and you should see it.

**Comment by HeetVekariya** [comment]
So can i start working on this issue ?

**Comment by GreenMachine01** [comment]
@HeetVekariya for that @souravjain540 is responsible.
Good luck in case he assigns it to you :)

**Comment by amyra98** [comment]
Can you please assign me this issue and also assign hacktoberfest label to this? @souravjain540

**Comment by GreenMachine01** [comment]
We need to check internally what caused the position to change before the community can assist with a fix.
