### ISSUE TITLE
As PO - I want to remove the "repo must not be empty" notification from the service wizard

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7235]
![Image](https://github.com/amplication/amplication/assets/112330500/c210a7f6-03fc-4b46-9199-c07d04cb1f42)

**Overview:**
In the 'Connect to Git' step within the service creation wizard the user is warned that the repo must not be empty but this is no longer true. we now do support empty repos.

**Requirements:**
1. Remove the "The selected repository must not be empty" notification from the service creation wizard

**Comment by HeetVekariya** [comment]
I would like to work on this issue, can you please assign it to me

**Comment by GreenMachine01** [comment]
@souravjain540  - FYI

**Comment by sanskar-soni-9** [comment]
@souravjain540 I would like to work on this issue.

**Comment by trishanu-init** [comment]
@GreenMachine01 Please assign this issue to me

**Comment by HeetVekariya** [comment]
@GreenMachine01 @souravjain540 I think the PR should be accepted only if it is made by the assignee, right ?

**Comment by HeetVekariya** [comment]
@souravjain540 I am ready with the solution, can you please assign the solution to me.

**Comment by trishanu-init** [comment]
@GreenMachine01 @souravjain540 any updates??

**Comment by vedant-z** [comment]
@GreenMachine01 I found the relevant file where the changes are required to be made.

File: packages/amplication-client/src/Resource/git/GitSyncNotes.tsx

Possible solution would be to simply remove the last list item containing the "The selected repository must not be empty" notification.

If you think I am suitable to work on this please assign me this issue. Also this would be a great one to start as I am new here.

**Comment by levivannoort** [comment]
@vedant-z assigned

**Comment by morhag90** [comment]
Passed QA:

<img width="941" alt="image" src="https://github.com/amplication/amplication/assets/97830649/9922e16a-370b-4d9e-be3c-03009d6fda1c">
