### ISSUE TITLE
Update Redis broker plugin to Nestjs v10 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7239]
### Feature description

Once the new `data-service-generator` is released, the **Redis broker** plugin will not be compatible due to the generation of code with wrong version dependencies.

This issue is intended to update the existing plugin with the support for the latest `data-service-generator` 
(nestjs 10)

- [x] https://github.com/amplication/amplication/issues/6916

### Tech notes

Check the official documentation for the needed changes:
https://docs.nestjs.com/v9/migration-guide#redis-strategy-microservices

**Comment by levivannoort** [comment]
![Image](https://github.com/amplication/amplication/assets/73097785/cafcc351-6098-4e9d-b716-5eb705bc902c)

**Comment by levivannoort** [comment]
https://github.com/amplication/amplication/issues/7363

**Comment by abrl91** [comment]
- install the redis broker plugin in all of the services that you need to publish or subscribe
- create a broker service
- create topics
- set receive or send on the connection page of each service
- if the services use the same db - rename the db name in the db plugin settings
- build + clone
- run only one of the docker-compose.dev.yml
- add some logic to listen and send a message

https://github.com/amplication/amplication/assets/39680385/f7ea9ea8-c462-41fc-904f-baa5f84c6841
