### ISSUE TITLE
Update Redis Cache plugin to Nestjs v10

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7240]
### Feature description

Once the new `data-service-generator` is released, the Redis Cache plugin will not be compatible due to the generation of code with wrong version dependencies.

This issue is intended to update the existing plugin with the support for the latest `data-service-generator` 
(nestjs 10)

- [ ] https://github.com/amplication/amplication/issues/6916

### Tech notes

Check the official documentation for the needed changes:
https://docs.nestjs.com/migration-guide#cache-module

**Comment by HeetVekariya** [comment]
@overbit I can work on this, i get more clear about the issue

**Comment by overbit** [comment]
@HeetVekariya this is not open to the community yet as the blocking feature is not yet completed
