### ISSUE TITLE
🐛 Bug Report: Inconsistent Dropdown Behavior Across Components

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#7257]
### What happened?

Our dropdown is malfunctioning, and its appearance varies from one component to another.

**Example**
<img width="336" alt="image" src="https://github.com/amplication/amplication/assets/96179897/6df9dc02-f9c6-4512-bab4-72af0d15d4b8">

<img width="692" alt="image" src="https://github.com/amplication/amplication/assets/96179897/eb53f811-7437-4aee-9dc1-6d866fd18f55">

### What you expected to happen

All dropdown fields should have a consistent appearance aligned with our design system.

**Figma**
https://www.figma.com/file/MQ0awwJRdlFYlHhj25ByEI/Community-Task-2023-24?type=design&node-id=2301%3A6614&mode=design&t=N3VXlBkJzOjOrLt4-1

### How to reproduce

You can find this in all screens that have dropdown fields, for example, entity creation.

### Amplication version

1.10.5

**Comment by MaheshReddy901** [comment]
Hi @GreenMachine01 I want to work on this issue.

**Comment by GreenMachine01** [comment]
@MaheshReddy901 Assigned to you. good luck!

**Comment by MaheshReddy901** [comment]
Hi @GreenMachine01 @alexbass86 @abrl91 I submitted PR #7302, please review it. Thank you:)

**Comment by MaheshReddy901** [comment]
I am attaching few dropdowns after the changes .
![Screenshot 2023-10-20 175309](https://github.com/amplication/amplication/assets/56298061/6afec7e5-2b62-40d2-9477-ec950230e122)

![Screenshot 2023-10-20 175328](https://github.com/amplication/amplication/assets/56298061/3a15097b-baa1-4c9d-a544-2433546cee42)

![Screenshot 2023-10-20 175242](https://github.com/amplication/amplication/assets/56298061/52727f08-aeea-44d6-a86d-b5c68557ad65)

**Comment by alexbass86** [comment]
> I am attaching few dropdowns after the changes . ![Screenshot 2023-10-20 175309](https://user-images.githubusercontent.com/56298061/276930533-6afec7e5-2b62-40d2-9477-ec950230e122.png)
> 
> ![Screenshot 2023-10-20 175328](https://user-images.githubusercontent.com/56298061/276930563-3a15097b-baa1-4c9d-a544-2433546cee42.png)
> 
> ![Screenshot 2023-10-20 175242](https://user-images.githubusercontent.com/56298061/276930589-52727f08-aeea-44d6-a86d-b5c68557ad65.png)

Hey, please notice that these attributes are still not aligned:
1. The border color should be the same in all different dropdown cross-app - #444B66
2. Dropdown width - needs to be the same width as the field itself
3. The field should have the same padding-left 12px, right 8px, top + bottom 6px
4. We use the same drop-down look cross-app - no dividers
![image](https://github.com/amplication/amplication/assets/96179897/f5753895-1461-47f2-bee5-e72b33813c29)
5. Active state is white not purple - it need to look the same cross app

**Comment by MaheshReddy901** [comment]
Hi @alexbass86 , Okay I will do the necessary changes and update here.

**Comment by alexbass86** [comment]
> Hi @alexbass86 , Okay I will do the necessary changes and update here.

thanks :)

**Comment by MaheshReddy901** [comment]
But for the active state, all the other fields in this page looks purple. If we change it to white then it might look odd.

**Comment by alexbass86** [comment]
> @alexbass86 But for the active state, all the other fields in this page looks purple. If we change it to white then it might look odd.
> 
> ![Screenshot 2023-10-22 174524](https://user-images.githubusercontent.com/56298061/277163999-749af1c9-56ce-4840-b7c9-da8fb4b32bed.png)
> 
> Above image for reference, Here the active states are purple (field border)

it should be white everywhere its currently purple

**Comment by MaheshReddy901** [comment]
okay got it. thanks for clarifying it. @alexbass86

**Comment by MaheshReddy901** [comment]
Hi @alexbass86 @souravjain540 please review my PR #7302. I made the changes told to me and updated the PR
