### ISSUE TITLE
As User - I want the error on "Looks like your code hasn't changed" to be a warning and not an error

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#7263]
Currently, if you press "Rebuild" again without making any new changes, there is no new code to push to Git and you will get the following error:

![Image](https://github.com/amplication/amplication/assets/1912933/42b96952-454f-4eaf-8e3e-8d334e14f050)

This should be a warning rather than an error.
The task is to find where we add the the following message to the build log:
"Hey there! Looks like your code hasn't changed since the last build. We skipped creating a new pull request to keep things tidy."
And change that log line from Error to Warning

**Comment by Sheersendu** [comment]
I would like to work on this issue. Can it be kindly assigned to me please. Thanks

**Comment by levivannoort** [comment]
@Sheersendu assigned

**Comment by Sheersendu** [comment]
Hi, @levivannoort , PR has been raised but its not getting auto linked with the issue ☹️. Do let me know my next steps! Thanks 😄

**Comment by levivannoort** [comment]
@Sheersendu Thanks! I'll attach it properly and put it in the queue for review. Thanks for your efforts thus far.

**Comment by Sheersendu** [comment]
Thanks a lot @levivannoort. Do let me know how to attach properly so that from next time I don't make this same mistake.

**Comment by abrl91** [comment]
passed QA ✅ 



![Image](https://github.com/amplication/amplication/assets/39680385/a499345d-a36d-4e20-bdad-2885d1a1141d)
