### ISSUE TITLE
🐛 Bug Report: Empty state image Misalignment on Commits Page

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#7275]
### What happened?

On the "commits" page, the image associated with the empty state (no elements) is not correctly centered. 
It should be centered in the middle, but currently, it is aligned to the top.

### What you expected to happen

The image should be vertically centered in the middle of the page when there are no elements.

### How to reproduce

1. Navigate to the "commits" page.
2. Ensure there are no elements displayed.
3. Observe the misaligned image.

**Bad**
![image](https://github.com/amplication/amplication/assets/96179897/b3db804c-93ab-4463-9773-f02c5457031e)

**Good**
![Entities - List](https://github.com/amplication/amplication/assets/96179897/8340338c-b9cb-42e2-9924-9dc0aef918d8)

**Figma**
https://www.figma.com/file/MQ0awwJRdlFYlHhj25ByEI/Community-Task-2023-24?type=design&node-id=2318%3A637&mode=design&t=S0ND8zrjH9XYAQcn-1

### Amplication version

1.10.5

**Comment by GreenMachine01** [comment]
@alexbass86 please add expected example.

**Comment by alexbass86** [comment]
> @alexbass86 please add expected example.

done

**Comment by sjcode99** [comment]
Hey @GreenMachine01 , would like to work on this issue. assign this to me please.

**Comment by GreenMachine01** [comment]
@sjcode99 Assigned to you. Good luck!

**Comment by Prashant04627** [comment]
Can I work on this issue?

**Comment by GreenMachine01** [comment]
@Prashant04627 the item was already assigned. if it becomes available Ill check with you.

**Comment by sjcode99** [comment]
Hey @GreenMachine01, I can see the PR is still not merged. Is there anything that requires my attention?

**Comment by GreenMachine01** [comment]
@mulygottlieb - FYI
