### ISSUE TITLE
🐛 Bug Report: wrong amplication logo on generated code

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7289]
### What happened?

On the generated code a logo is used where, next to the amplication logo the text is in purple. This change needs to happen on both the admin-ui side aswell as the server.

### What you expected to happen

That is houses the new design of the logo, a purple amplication logo with white text next to it.

![amplication logo](https://github.com/amplication/amplication/assets/73097785/fbf3277d-3f4f-462e-949e-929f24fafa46)

### How to reproduce

Generate a service and have a look at the readme.

### Amplication version

1.10.5

**Comment by Prashant04627** [comment]
Can i try to solve this issue?

**Comment by levivannoort** [comment]
Newer icon:
![amplication logo](https://github.com/amplication/amplication/assets/73097785/e481b8e9-0ed9-4fc5-8e76-1f67760a15ab)

**Comment by levivannoort** [comment]
@Prashant04627 sure thing, i'll assign you good luck. I added the icon and more relevant information.

**Comment by Prashant04627** [comment]
Obly the text should be changed to white?

**Comment by lalitkumawat1m** [comment]
Hey @Prashant04627 do you need any help

**Comment by Prashant04627** [comment]
Yes where can i find the generated code on the page(website)

**Comment by Prashant04627** [comment]
Can anybody help where i can see the issue?

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/4ce0ba2b-c8f0-4498-9173-714ec22c9227)
