### ISSUE TITLE
As a Dev - I want to add the word "field" to the reserved words

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7292]
Add "field" to the `RESERVED_NAMES` array in the server.

**Comment by martinez-hugo** [comment]
Hi ! Can I work on this issue ?

**Comment by Devvrat1010** [comment]
Hi @abrl91 , I would like to work on this issue

**Comment by overbit** [comment]
## Test Results

Passed ✅  

![Image](https://github.com/amplication/amplication/assets/2861984/bd8cd5b7-adfb-4a6c-be4d-0d32b39db8e2)
