### ISSUE TITLE
As PO - I want to improve the design for the notification icon

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#7293]
**Current:**
![Image](https://github.com/amplication/amplication/assets/112330500/eddf6d45-ae69-40e9-827b-084bd0d6a7f1)

**Expected:**
with new message
![Image](https://github.com/amplication/amplication/assets/112330500/1cbb8b30-c902-4064-8951-ed8e8f32c3d8)

without new messages
![Image](https://github.com/amplication/amplication/assets/112330500/13808bfc-ef23-40cb-8dc0-aeed81779847)

**Requirements:**
1. Set the notification icon according to the design example
2. Set the new messages dot according to the design example

**Design instructions:**
Circle in the bell icon:
Color - #FFBD70
Circle size - 6px
Bell icon size - 16px
No alerts Bell color without tiny circle - #686F8C
https://www.figma.com/file/b5wvIgBlJftZaDKBzyppvu/Notification-Icon-v.2?type=design&node-id=757%3A1353&mode=design&t=PuNPRJbsFPWEBtkB-1

**Comment by Sheersendu** [comment]
I would like to work on this issue. Pls assign it to me. Thanks!

**Comment by git-create-devben** [comment]
I would love to work on this

**Comment by Sheersendu** [comment]
> @Sheersendu We are checking if it can be done by the community. ill update.

Do let me know if there are any updates @GreenMachine01. Thanks!

**Comment by lalitkumawat1m** [comment]
I want to work on this issue please assign to me

**Comment by mulygottlieb** [comment]
@Sheersendu , I opened this item for the community now, and you are the first one who asked, so assigning it to you. Good luck!

**Comment by Sheersendu** [comment]
Hi, @mulygottlieb  due to some unforeseen events I'll not been able to  work for few weeks, requesting you to assign this to someone. Thanks for your cooperation.

**Comment by PazYanoverr** [comment]
@git-create-devben - Can you still take it?

**Comment by git-create-devben** [comment]
> @git-create-devben - Can you still take it?

Thanks @PazYanoverr I'll definitely give it a shot please assign me

**Comment by PazYanoverr** [comment]
Done as part of other notification improvements. 
@git-create-devben - FYI
