### ISSUE TITLE
BILLING_ENABLED is false still bit bucket is showing locked

### ISSUE THREAD

**Issue by devarsh-mavani-19** [amplication/amplication#7305]
### Overview

I am doing development locally and want to enable bitbucket, i BILLING_ENABLED=false in .env.local file and remove .env file temporarily but still the bitbucket icon is locked when i open localhost:3001

### Cause

When trying to access bitbucket locally

### Resolution

Not sure how to resolve problem

### Tags

Local development, Bitbucket, billing

### Related Discord Threads

https://docs.amplication.com/running-amplication-platform/connect-server-to-bitbucket/#step-2-configure-amplication-server-and-amplication-git-pull-request-to-work-with-the-newly-created-bitbucket-oauth-consumer

**Comment by souravjain540** [comment]
@devarsh-mavani-19 hello, bit bucket is only right now available for our enterprise customers.

**Comment by devarsh-mavani-19** [comment]
@souravjain540 and what about the 3 service limit? is that also only available for enterprise user?
