### ISSUE TITLE
🐛 Bug Report: cannot open show page with numeric ID

### ISSUE THREAD

**Issue by kernelogic** [amplication/amplication#7310]
### What happened?

Hi, I created a postgresql entity with a numeric auto increment ID, however on the auto generated table, I cannot open edit page. GraphQL returns "Variable "$where" got invalid value "1" at "where.id"; Float cannot represent non numeric value: "1""

### What you expected to happen

Show entity page should open normally.

### How to reproduce

Create a postgresql entity with a numeric auto increment ID

### Amplication version

Latest

**Comment by souravjain540** [comment]
@kernelogic can you open a support ticket in our discord channel? https://amplication.com/discord
