### ISSUE TITLE
🐛 Bug Report: RabbitMQ plugin is not fully functional - getting an error: `There is no matching event handler defined in the remote service`

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7360]
Currently the RabbitMQ plugin is not generating fully functional work returning the follow error on event emission:
```sh
There is no matching event handler defined in the remote service
```

**Comment by PazYanoverr** [comment]
This is potentially solved (?) per this comment
https://github.com/amplication/amplication/issues/6878#issuecomment-1792708842

**Comment by overbit** [comment]
@PazYanoverr unfortunately this issue is not resolved as the current state of the plugin is unusable due to the implementation rely on an event pattern that is not supported by RabbitMQ. (need to be changed to be ad-hoc)

**Comment by mulygottlieb** [comment]
Passed Sanity QA:


![Image](https://github.com/amplication/amplication/assets/1912933/923d55d3-6ffd-4164-adb2-e2de32e2dceb)
