### ISSUE TITLE
🐛 Bug Report: Redis Broker plugin not creating required environment variables on docker-compose

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7363]
### What happened?

When trying to run the docker-compose after adding the redis broker plugin to the generated service, the following error can be seen when starting the generated service's docker compose file.

![image](https://github.com/amplication/amplication/assets/73097785/3a6875bf-c57a-4a32-a9c3-8e385d22928a)

### What you expected to happen

That the services on the docker-compose start succesfully and will be used by the generated-service

### How to reproduce

Add the redis broker plugin to a generated service, build the service & try to start the docker-compose locally.

### Amplication version

1.10.5 / 2.0.0

**Comment by abrl91** [comment]
can't reproduce

https://github.com/amplication/amplication/issues/7239#issuecomment-1788715936
