### ISSUE TITLE
As a User - I want to be able to start the generated service in HTTPS and/or HTTP mode

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7364]
### Feature description

As a User I would like to be able to start my generated service in HTTPS mode as well as / or in HTTP mode. Currently the generated service only supports HTTP.

HTTPS:
```typescript
const httpsOptions = {
  key: fs.readFileSync('./secrets/private-key.pem'),
  cert: fs.readFileSync('./secrets/public-certificate.pem'),
};

const app = await NestFactory.create(AppModule, {
  httpsOptions,
});

await app.listen(3000);
```

HTTP & HTTPS:
```typescript
const httpsOptions = {
  key: fs.readFileSync('./secrets/private-key.pem'),
  cert: fs.readFileSync('./secrets/public-certificate.pem'),
};

const server = express();
const app = await NestFactory.create(
  AppModule,
  new ExpressAdapter(server),
);
await app.init();

const httpServer = http.createServer(server).listen(3000);
const httpsServer = https.createServer(httpsOptions, server).listen(443);
```

Documentation: https://docs.nestjs.com/faq/multiple-servers

---

Suggestion implementation: 
> "I would like to see variable(s) in the env file to instantiate one or the other.  we would probably only instantiate the https version."

### Use case

Currently the generated service support starting the service in HTTP mode, which is suitable for many usecases, but sometimes it is desired to have the TLS termination be at the application level as well as or instead of at the loadbalancer level.

**Comment by xonx4l** [comment]
Is this looks good to you @levivannoort . if yes then I can work further on this otherwise you can direct me towards the right side .

**Comment by overbit** [comment]
@PazYanoverr as we decided to implement this feature as a plugin, we will need an icon in order to release it. Can you help with that?

**Comment by overbit** [comment]
## Test result: ✅
