### ISSUE TITLE
🐛 Bug Report: Remove redundant dependency from generated app

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7367]
### What happened?

The latest version of dsg generates code with `@amplication/nest-access-control` dependency that is not used as the code leverage the `nest-access-control` library instead.

### What you expected to happen

Unused dependencies should be added to the generated code.

### How to reproduce

.

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/0bbd028b-10bb-4da2-b241-a3b491957748)
