### ISSUE TITLE
🐛  Bug Report: typo on the README - contributer => contributor

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7373]

**Comment by balagowda** [comment]
hey 👋 ! i would like to work on this where exactly the issue is??

**Comment by Hrishi000001** [comment]
Hey ,
I would like to work on this issues.

**Comment by sagarkori143** [comment]
Hey @PazYanoverr I think we should close the issues which have been resolved. This creates a confusion to the new contributors.

**Comment by PazYanoverr** [comment]
Agree, @sagarkori143 - thanks!
@abrl91 @mulygottlieb - Can you please close this issue?
