### ISSUE TITLE
🐛 Bug Report: `@amplication/plugin-auth-jwt` and `@amplication/plugin-auth-core` rely on statically named secrets for `JWT_SECRET_KEY`

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7375]
### What happened?

When using a secret manager plugin, all the secrets must be customisable otherwise the provider would need to contain a  `JWT_SECRET_KEY` making impossible to integrate more the one service to the secret provider (there would be a clash in the secret as different service might have different values for the JWT secret key).

### What you expected to happen

Using a secret manager `X` I want to store the value of the jwt secret key in the following location as `JWT_SECRET_KEY` won't be a valid name. 
`domain/service-name/jwt-secret` 

Defining the JWT_SECRET_KEY secret manager key name, I'd like to use the stored secret from the provider.

### Tech Notes

- [x] add a new dsg plugin event (with wrapper and co.) for modifying the new `secret-key-name.enum.ts`
 https://github.com/amplication/amplication/pull/7399
- [x]  #7398 
  - [x] dsg to. add a default empty `secret-key-name.enum.ts`
  - [x] update dsg `secretsmanager.service`, its interface and its base, signature to leverage the `secret-key-name.enum.ts` 
- [x] update Auth-core plugin to remove references to `JWT_SECRET_KEY` (#7414)
- [x] #7416
- [x] #7417

### Amplication version

dsg v2.0.0

**Comment by overbit** [comment]
Related to https://github.com/amplication/amplication/issues/7414

**Comment by abrl91** [comment]
passed QA ✅ 


![Image](https://github.com/amplication/amplication/assets/39680385/01f97be3-51f6-4511-a8c8-f9c754c84ddc)




![Image](https://github.com/amplication/amplication/assets/39680385/b46254e9-a16e-4179-9a21-8b6f32f0a125)



![Image](https://github.com/amplication/amplication/assets/39680385/31e608a8-2382-4139-b885-f9c5d2afcdb5)
