### ISSUE TITLE
🐛 Bug Report: After release amplication v1.10.1+ debugger doesn't attach to breakpoints in any service

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7380]
### What happened?

Currently, contributors are not able anymore to run amplication services with a debugger attach making the developer experience quite poor.

### What you expected to happen

I'm expecting to be able to attach the debugger to any of the services I'm running locally without issue.

### How to reproduce

Try to run amplication locally and attach the debugger

### Amplication version

v1.10.7

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abrl91** [comment]
Passed QA ✅
