### ISSUE TITLE
Update react-admin in admin-ui (dsg) to v4

### ISSUE THREAD

**Issue by Shurtu-gal** [amplication/amplication#7395]
### Feature description

Currently, the react-admin version is [3.19.12](https://github.com/amplication/amplication/blob/b0eabb424b127dacdfc91977e880aa243541b21b/packages/data-service-generator/src/admin/package-json/package.json#L13). However some things have been [depreciated in v4 of react-admin](https://marmelab.com/react-admin/Upgrade.html) hence the need to upgrade.

### Use case

I was trying to make a demo for WebSockets to be implemented in plugin, in which there are some conflicts and breaking changes b/w major versions.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Meyazhagan** [comment]
@Shurtu-gal can I take this

**Comment by Shurtu-gal** [comment]
Sure @Meyazhagan.

**Comment by mulygottlieb** [comment]
Closing the issue for now since this is not where we want to focus our efforts.
