### ISSUE TITLE
🐛 Bug Report: Failing pull request with `Cannot read properties of null (reading 'url')`

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7421]
### What happened?

<img width="728" alt="image" src="https://github.com/amplication/amplication/assets/2861984/003b1c26-4f3b-444e-8c4f-b36daa5824d3">

### What you expected to happen

.

### How to reproduce

1. Create a service and connect it to GitHub
2. Build
3. merge the PR
4. delete PR and branch
5. build again without changes

**Comment by overbit** [comment]
Related to https://github.com/amplication/amplication/pull/7278

**Comment by abrl91** [comment]
passed QA ✅ 


![Image](https://github.com/amplication/amplication/assets/39680385/6a0517cc-1f40-4777-9262-8ffc3a495c1c)
