### ISSUE TITLE
`data-service-generator` should generate dotenv files sorted alphabetically

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7426]
### Feature description

To increase stability (irrelevant changes in files), dsg should generate dotenv files sorted in a deterministic way

**Comment by Meyazhagan** [comment]
@overbit I created a PR for this. you can review it

**Comment by mulygottlieb** [comment]
Passed QA


![Image](https://github.com/amplication/amplication/assets/1912933/b8122e16-ee8e-4da5-8478-514cc7aa0c5d)


Thanks @Meyazhagan !
