### ISSUE TITLE
Arrange plugins into categories

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7429]
### Feature description

Based on https://github.com/amplication/amplication/issues/7109, we want to arrange the plugins in categories, and allow better navigation and feedback mechanism.

Functional description - immediate:
- [x] #7509
- [x]  #7513

TBD later:
- [ ] #7510
- [ ] #7511
- [ ] #7512

Notes:
1. Any user interaction- i.e. choosing a plugin category, pressing the "Coming Soon" option, voting etc. should generate an event (- server-side if possible). 
2. The votes, and the plugin-requests should be saved "persistently" (db or such), so we can share the vote results with our users, get the list of votes for a specific plugin etc.
3. If possible- please fetch the list of plugins and their existing categories for review before merging this FR.

**Comment by mulygottlieb** [comment]
@barshimi @PazYanoverr - I created subtasks from all sub-items mentioned here and opened them in "todo".
The first three are assigned to @barshimi  and the last two I left unassigned for additional prioritization once we finish the first three.

**Comment by mulygottlieb** [comment]
@barshimi after chatting with Paz we are prioritizing for now just #7509 and #7513 .
I updated the description above to reflect this and moved the relevant tickets to you / unassigned you from the future ones that are not prioritized for now.

**Comment by yuval-hazaz** [comment]
@PazYanoverr  can we close this issue and leave just the children issues?
