### ISSUE TITLE
🐛 Bug Report: Impossible to add required fields

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7438]
### What happened?

After this PR https://github.com/amplication/amplication/issues/7419, users might find themself in a bad situation where they cannot resolve the issue in any way.

<img width="691" alt="Screenshot 2023-11-16 at 14 39 37" src="https://github.com/amplication/amplication/assets/2861984/a079691f-3fa9-470b-b7dd-468d469abf2c">
<img width="669" alt="image" src="https://github.com/amplication/amplication/assets/2861984/80410f84-d3e2-4304-9908-935f67fe88c0">

### What you expected to happen

Being able to add the fields reported missing during the code generation

### How to reproduce

1. Create a service with template and authentication
2. build
3. delete username and password fields from User entity
4. build again
5. try to add the fields again

**Comment by abrl91** [comment]
passed QA ✅ 

![image](https://github.com/amplication/amplication/assets/39680385/2957dd54-a8c1-445b-aa45-902bc2911193)
