### ISSUE TITLE
Add support for showing prerelease plugins only on specific environments

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7451]
### Feature description

In order to simplify testing of new plugin versions we will need a way to publish prerelease that would only being available in non production environments

To achieve this, we will need to:

- [x] for Production and Staging:  only store plugin version matching the regex 
      `^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)`

- [x] for every other environment:  only store plugin version matching the regex 
      `^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`

Part 2 of #7441 

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abrl91** [comment]
In sandbox:



![Image](https://github.com/amplication/amplication/assets/39680385/5408a371-7335-495c-a04a-eae75767c760)
