### ISSUE TITLE
🐛 Bug Report: DSG version doesn't match the selected version

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7459]
### What happened?

<img width="853" alt="image" src="https://github.com/amplication/amplication/assets/2861984/83202fe8-a59b-4ab3-be92-369396678cfb">

<img width="745" alt="image" src="https://github.com/amplication/amplication/assets/2861984/c89f04df-7a61-4119-95ea-4b0c16d62c60">

### What you expected to happen

the selected version like v2.2.1

### How to reproduce

.

### Amplication version

v1.10.9

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/341630d2-482f-4d7d-81e6-04425ad87557)
