### ISSUE TITLE
`data-service-generator` version in build log should be more visible

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7463]
As per v2.2.1, `data-service-generator` version is shown after the dynamic installation.

In order to increase its visibility, it should be the first log in the build log `Generation Application` section
<img width="1165" alt="image" src="https://github.com/amplication/amplication/assets/2861984/3608edda-b0d4-4049-b043-60be79d3f3e4">

**Comment by adityabisht02** [comment]
I can take this up if no one is currently working on it 👍

**Comment by overbit** [comment]
@adityabisht02 sure, thanks!

**Comment by Meyazhagan** [comment]
@adityabisht02 any update! 

@overbit if no update, can I work on this change?

**Comment by adityabisht02** [comment]
@Meyazhagan Sorry been extremely busy. I'll try to finish it this weekend, in case I wont ill let you know and you can work on it. Hope thats okay

**Comment by mulygottlieb** [comment]
Passed QA


![Image](https://github.com/amplication/amplication/assets/1912933/9ee02f28-aec5-40b7-9b3f-d2d8cb6d4be0)
