### ISSUE TITLE
🐛 Bug Report: the UI of plugin settings in not reflecting the actual plugin settings especially when we update it

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7466]
When we add settings to a plugin or update the settings of a plugin, it is not visible in the UI.
In order to see it the user needs to click on `save`

https://github.com/amplication/amplication/assets/39680385/89c85a98-9f76-4b0e-8323-f5dcad4f86d2

**Comment by PazYanoverr** [comment]
@abrl91 - NSIU the sequence of events (from the video). The JwtSecretKey (- the json settings) was saved before (in a previous session), and did not appear in the UI?

**Comment by abrl91** [comment]
> @abrl91 - NSIU the sequence of events (from the video). The JwtSecretKey (- the json settings) was saved before (in a previous session), and did not appear in the UI?

No. In the latest version (1.4.4 => latest), we have updated the settings of the JWT plugin. However, these changes are not reflected in the user interface. As a result, when users upgrade to the latest version and access this page, they are unable to see the updated settings, as they are not displayed on the page. It is the same for users who already use the latest version and just navigate to the plugin's settings page.

The settings were updated only after I clicked on the 'Save' button.

**Comment by PazYanoverr** [comment]
@abrl91 -  Got it, thanks! Let's prioritize

**Comment by overbit** [comment]
@abrl91 this might become a big change as currently there is no way to update a resource plugin settings on new plugin released

**Comment by PazYanoverr** [comment]
@overbit - Good point. So we'll need to get a rough estimation and decide accordingly

**Comment by mulygottlieb** [comment]
Passed QA:


https://github.com/amplication/amplication/assets/1912933/1934fb14-2876-492c-afb1-22c7da507c2c
