### ISSUE TITLE
DSG: Docker build failed when a related entity is missing

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#747]
**Describe the bug**
The Docker build process is failing with a generic error "Build Docker failed" when a related entity is missing.

**To Reproduce**
1. Create Entity A
2. Create Entity B
3. On Entity B, add a field of type "Related Entity" and link it to Entity A.
4. Delete Entity A
5. Commit changes and build a new version

**Expected behavior**
* The system should show a warning or an error when trying to delete an entity that is referenced from another entity.
* The build process should return a detailed error when generating code and an entity is missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/43705455/97991105-a5223500-1de9-11eb-86ba-3b755f0fe32a.png)

**Comment by shahriar-shojib** [comment]
I am interested in fixing this.

**Comment by yuval-hazaz** [comment]
@shahriar-shojib thanks!.
We should add validation on the server-side before deleting an entity- that there are no related fields that referencing the entity. If there are any, an error should be thrown from the server with the name of the referencing field and entity

**Comment by EugeneTseitlin** [comment]
@souravjain540 As far as we don't build docker image anymore I think the issue can be closed as irrelevant. Am I right?

**Comment by souravjain540** [comment]
> @souravjain540 As far as we don't build docker image anymore I think the issue can be closed as irrelevant. Am I right?

closing :)
