### ISSUE TITLE
🐛 Bug Report: Relation to Entity Radio Button doesnt turn off

### ISSUE THREAD

**Issue by Sixchalice** [amplication/amplication#7471]
### What happened?

When creating a new Field in an entity and selecting the Data Type to "Relation to Entity", You have to select between 2 radio buttons. when selecting the 2nd option both of them are lit up as if both are selected as opposed to only one.

<img width="685" alt="284714808-d6b3c591-5a61-4c75-8e9b-a87f6db8a27f" src="https://github.com/amplication/amplication/assets/82182019/a947ca9f-0e93-4c3e-b340-f22d8704b4d2">

### What you expected to happen

Only a single button should show up as selected.

### How to reproduce

Create a service and create an entity. Then add a field with any name. Then select the Data Type of "Relation to Entity", and select both radio buttons.

**Comment by Meyazhagan** [comment]
@souravjain540 I would like to work on this issue, can you assign me?

**Comment by mulygottlieb** [comment]
Passed QA:


https://github.com/amplication/amplication/assets/1912933/951cd8ec-28ab-42a2-9aca-bb0b2440fc76
