### ISSUE TITLE
Build is stuck after installing Kafka without a message broker

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7472]
Happened to @yuval-hazaz.
After installing the Kafka plugin and running a build, the DSG failed but the logis kept spinning

![Image](https://github.com/amplication/amplication/assets/149934977/87f12919-b812-42ab-b724-742bec4aefcd)

Expected result:
1. The build should not get stuck - solved in version 1.10.10
2. The plugin should avoid failing the build in such case, and instead- issue a warning message which will say something like: "The Kafka plugin has been installed in the absence of a message broker service. Kindly incorporate a message broker service to enable the utilization of the Kafka plugin."
3. _When installing a broker plugin, without message broker setup, a message should be issued instructing the user to set up a message broker to utilize the installed plugin._ new issue open for this https://github.com/amplication/amplication/issues/7700

**Comment by PazYanoverr** [comment]
@overbit -
There are a few issues here- (1) the build that got stuck, (2) the build failure, which I believe is not necessary, (3) the message itself.
Regarding the message, I'd prefer to state action item/s rather than a question. So something like "Check that a message broker provider is installed in the "plugins" tab" or such. WDYT?

**Comment by overbit** [comment]
That makes absolutely sense. Having a prompt in the plugins (categorised as broker) to help user understand that they need the message broker setup makes a lot of sense

**Comment by PazYanoverr** [comment]
@overbit - Your suggestion is excellent. In addition to the build message- issue a message while adding a relevant plugin without a broker setup.
Will add it to the expected result list. Thanks!

**Comment by abrl91** [comment]
@PazYanoverr the "hanging" status was related to a different issue that was solved in version `1.10.10`

**Comment by PazYanoverr** [comment]
@abrl91 - Great, thanks. Updated the issue that the first item was handled.

**Comment by mulygottlieb** [comment]
QA: 
Item 1 was solved in 1.10.10.
Item 2 passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/c75bfe4d-fd9b-4c51-b9e7-fe3d8296b34f)


Item 3 has a separate ticket in the backlog.

So moving this to passed QA.
