### ISSUE TITLE
🐛 Bug Report: `amplication-server` throwing many `ERROR [Runner] Error when calling eachMessage`

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7473]
### What happened?

There are many errors like:
> ERROR [Runner] Error when calling eachMessage

> Error: Argument where of type BuildWhereUniqueInput needs at least one argument

### What you expected to happen

server to run successfully

### How to reproduce

No repro steps are currently available. 
Check the log dashboard in CW

### Amplication version

v1.10.9

**Comment by overbit** [comment]
<img width="1195" alt="image" src="https://github.com/amplication/amplication/assets/2861984/58051a46-5677-4647-84cc-d3c4d68d7b90">

**Comment by abrl91** [comment]
Passed QA ✅
