### ISSUE TITLE
Design proposal: change the panels on the service overview page to be clickable instead of a button in the right corner

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7476]
![Screenshot 2023-11-22 at 19 50 33](https://github.com/amplication/amplication/assets/39680385/a9e1c438-9563-4dac-87fe-1ddf7005c573)

**Comment by PazYanoverr** [comment]
@alexbass86 - Let's find the best UX here ()

**Comment by PazYanoverr** [comment]
New design- https://www.figma.com/file/SeGRp1W43m3bbBQxLHqPU4/UX-Improvement---Service-overview?type=design&node-id=757%3A1353&mode=design&t=KFsBfKOEpeFbvIX2-1

**Comment by Mudit-Jxin7** [comment]
Hey , Can I solve this issue ?

**Comment by PazYanoverr** [comment]
@Mudit-Jxin7 - Sure, assigned the ticket to you. Good luck!
@alexbass86 - Can you please share the design with the community?

**Comment by KrishavRajSingh** [comment]
> @Mudit-Jxin7 - Sure, assigned the ticket to you. Good luck!
> @alexbass86 - Can you please share the design with the community?

Hey, I was thinking to work on this if no one was working but I don't have the access of the figma file, how can I get it??

**Comment by PazYanoverr** [comment]
Thanks @KrishavRajSingh - We are considering redesigning the whole page, so I think you should better find another ticket to work on.
@Mudit-Jxin7 - Since there was no progress in the last few months (+ see my comment before), I'll un-assign this ticket.

**Comment by KrishavRajSingh** [comment]
> Thanks @KrishavRajSingh - We are considering redesigning the whole page, so I think you should better find another ticket to work on.
> @Mudit-Jxin7 - Since there was no progress in the last few months (+ see my comment before), I'll un-assign this ticket.

Yeah sure

**Comment by Gobinath-B** [comment]
@PazYanoverr what is the status of this issue? I wanna work in this feature

**Comment by PazYanoverr** [comment]
@Gobinath-B - We've decided to redesign the page (in a different way). Closing this ticket now. Sorry and thanks.

**Comment by PazYanoverr** [comment]
The page is about to be redesigned, so the ticket is not relevant anymore.
