### ISSUE TITLE
As a User I want to have a better navigation to the service from the build page

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7477]
When a user views the build page, it is at the level of a project, but the build is for a specific service, and usually he wants to view the service settings/installed plugins, etc.

![image](https://github.com/amplication/amplication/assets/39680385/35c10821-8636-4791-85be-382ed22c3aaf)

In the current situation he has 2 options:
1. navigate back to the commits page and click on the selected icon
![image](https://github.com/amplication/amplication/assets/39680385/d1cb81b2-7138-48ec-b926-75692a969d88)

2. navigate to the project's area by clicking on the navbar, and then selecting the service.
![image](https://github.com/amplication/amplication/assets/39680385/266d0f8c-630f-4f15-ae06-4e0e26fda3f2)

**Comment by PazYanoverr** [comment]
@alexbass86 - Let's improve the UX here (https://app.asana.com/0/1205802498439398/1206015883162164/f)

**Comment by PazYanoverr** [comment]
Design- https://www.figma.com/file/lDpeH9fLQry18R9xlsCh7w/UX-Improvement---Build-screen-navigation?type=design&node-id=757%3A1353&mode=design&t=JFjq1DXuw6KcoUyn-1

**Comment by pratik-pc** [comment]
@mulygottlieb I would like to work on this issue

**Comment by PazYanoverr** [comment]
@pratik-pc - I assigned the issue to you! Good luck!
@alexbass86 - Can you please make the design available to the community?

**Comment by alexbass86** [comment]
> @pratik-pc - I assigned the issue to you! Good luck! @alexbass86 - Can you please make the design available to the community?

Hey please use this link:
https://www.figma.com/file/MQ0awwJRdlFYlHhj25ByEI/Community-Task-2023-24?type=design&node-id=2440%3A3&mode=design&t=7MRbCrLMJQFjspWF-1

**Comment by sanskar-soni-9** [comment]
Hi, I want to work on this if available. @PazYanoverr

**Comment by PazYanoverr** [comment]
@pratik-pc - It seems like there has been no progress in the last 2 weeks. Reassigning it.
@sanskar-soni-9 - Sure, assigning to you. Good luck!

**Comment by sanskar-soni-9** [comment]
Hi @abrl91 can you check the PR if its correct or need any corrections. Thanks!

**Comment by 609harsh** [comment]
hi is the issue still open? or is someone working on this?

**Comment by PazYanoverr** [comment]
@abrl91 - We can close this issue as Done, right?

**Comment by abrl91** [comment]
closed by https://github.com/amplication/amplication/pull/7759
