### ISSUE TITLE
As a user I want to have a clearer visualization of the entity I am currently working on

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7479]
When a user visits the entity page, they can immediately discern which entity they are currently working on only if the "General Settings" tab is actively selected.

![Screenshot 2023-11-22 at 19 53 00](https://github.com/amplication/amplication/assets/39680385/5bfd73e5-d6c0-466f-84e4-279b39132827)

![Screenshot 2023-11-22 at 19 53 17](https://github.com/amplication/amplication/assets/39680385/59ec0f98-e4b3-49fe-b55a-7a744f6b330e)

**Comment by PazYanoverr** [comment]
@alexbass86 - Let's find the best UX here (https://app.asana.com/0/1205802498439398/1206015883162171/f)

**Comment by PazYanoverr** [comment]
Design: https://www.figma.com/file/l78DCOSVfwmxdYERWaAqYB/UX-Improvement---Entity-visualization?type=design&node-id=757%3A1353&mode=design&t=8j6CCovufqNYLAhb-1

**Comment by Himanxu1** [comment]
Assign this to me

**Comment by abrl91** [comment]
@alexbass86 can you make the Figma link available for the community?

**Comment by alexbass86** [comment]
> @alexbass86 can you make the Figma link available for the community?

Hi please use this link:
https://www.figma.com/file/MQ0awwJRdlFYlHhj25ByEI/Community-Task-2023-24?type=design&node-id=2427%3A3&mode=design&t=PhIZoY6mriO9lPAX-1

**Comment by abrl91** [comment]
@Himanxu1 see Alex's comment. Good luck!

**Comment by PrathameshGujar08** [comment]
Has this issue been solved?

**Comment by PazYanoverr** [comment]
@Himanxu1 - Any progress with it, or should we move it to someone else?
@PrathameshGujar08 - No. Do you want to work on it?

**Comment by PrathameshGujar08** [comment]
Yeah I want to work on it

**Comment by PazYanoverr** [comment]
@Himanxu1 - Two weeks passed with no progress. Assigning it to @PrathameshGujar08
@PrathameshGujar08 - good luck!

**Comment by arybecks23** [comment]
@PazYanoverr It's been about a month with no progress. Would you be able to assign it to me please?

**Comment by PazYanoverr** [comment]
@PrathameshGujar08 - A month passed, with no progress.
Assigning the ticket to @arybecks23

**Comment by arybecks23** [comment]
@PazYanoverr I was wondering if you had a chance to check the PR.

**Comment by arybecks23** [comment]
@mulygottlieb @abrl91 any update on this PR by any chance?

**Comment by overbit** [comment]
![Image](https://github.com/amplication/amplication/assets/2861984/3c05bdfa-e4cc-4c3c-b0db-32376eabb803)

**Comment by anuragbhatt408** [comment]
Please close this if it is done
