### ISSUE TITLE
By default, the "Username" field in the "User" entity should be a "Unique Field"

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7492]
As for now, the "Username" field in the "User" entity is not a unique field by default.
This should be changed so the "Username" field is unique by default and disabled so users won't be able to change it.
This change should apply to new services only.

**Comment by abrl91** [comment]
@PazYanoverr 
Is this requirement is only for new services? or also for existing?
If it is also for existing services, we will need a migration + it will change the users' schema and they will also need a migration for their DB

**Comment by PazYanoverr** [comment]
@abrl91 - Good question. This change should apply to new services only. I will update the ticket's description accordingly. Thanks!

**Comment by mulygottlieb** [comment]
Passed QA:



![Image](https://github.com/amplication/amplication/assets/1912933/4f8740a8-8a54-4551-93cf-3381796a02b2)
