### ISSUE TITLE
The "Password" field in "User" entity should be NOT unique by default and disabled

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7493]
As password entity field type should never be unique across multiple users for security reasons, any field entity of type password should be not unique by default and disabled so users won't make mistakes.

**Comment by abrl91** [comment]
So, this issue happens in other fields, and I have found the cause. 


https://github.com/amplication/amplication/assets/39680385/abf1a697-2b95-45c7-99fa-c247612d905a

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/9d2d62f5-00a1-49de-afed-c61ac1197ace)
