### ISSUE TITLE
As a Dev - I want to change the CI workflow on the plugins repository to publish a beta version only on comment

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7499]
Related issue: https://github.com/amplication/amplication/issues/7441

## Current implementation 
A new plugin beta version is published on every new and synchronized pull request.

## New requirement
On every comment on the PR a new beta version of a plugin will be published with the same format that we have in the current implementation: `<version in package.json>-beta.pr-<pr number>.<commit short sha (7 chars)>`
i.e. for pr # 7441 `1.2.1-beta.pr-7441.979a26c`

- get affected plugins
- execute a `publish` dry run for every plugin that was changed and check if the current version can be published 
- publish

**Comment by overbit** [comment]
@abrl91 ⚠️ 
Version bump validation must happen on PR for every commit as we don't want to merge a PR with changes on a plugin that has not been version bumped otherwise we will have a failing publish pipeline in `master`
