### ISSUE TITLE
🐛 Bug Report: Missing `@material-ui/styles` package

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#7502]
### What happened?

In the generated code inside the Admin UI there is a use of `@material-ui/styles` in the `src/Login.tsx` file but this package is missing from the `package.json` file of the Admin UI

### What you expected to happen

All the packages that are consumed need to be declared

### How to reproduce

Just generate any service with Admin UI in it.

### Amplication version

1.10.10

### Environment

Using pnpm 

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by xonx4l** [comment]
if this is correct then I can go forward with opening a pull request .
