### ISSUE TITLE
Plugin arrangement [7429]: Plugin categories and filtering

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#7509]
In the "Plugins" screen, the user will see the available plugin categories, and filter the plugins list based on it. Note that the user should be able to filter based on more than one category (as each plugin can belong to multiple categories), and AND condition should apply between the chosen filters.

**Comment by overbit** [comment]
## Test result ✅ 




![Image](https://github.com/amplication/amplication/assets/2861984/c34489f2-4ff7-4564-81e4-63bc8c7acf02)

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/debd023e-21b6-4f67-90b3-6127899994e6)

**Comment by mulygottlieb** [comment]
Need to align plugin category names later based on the spec from Paz
