### ISSUE TITLE
🐛 Bug Report: when microsoft sql plugin is installed, dsg also installs postgres 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7515]
### What happened?

Currently it's not a major issue as the postgres changes are overridden by the ms sql plugin but some of the changes might not have been rewritten.

### What you expected to happen

.

### How to reproduce

Install the ms sql plugin , run a build and check the logs

**Comment by abrl91** [comment]
✅  passed qa


![Image](https://github.com/amplication/amplication/assets/39680385/84ee2366-b71f-4db5-bb2b-7477f25036c1)
