### ISSUE TITLE
Improve the in-app notification widget

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7525]
The current in-app notification widget (by Novu) seems bad, and not related to Amplication look&feel at all (- see below).
Based on @alexbass86's instructions - let's update the design using the available Novu customizations, and make it look more Amplication's

![Image](https://github.com/amplication/amplication/assets/149934977/0a7930e3-af19-4423-86ce-dee87cf62355)

**Comment by overbit** [comment]
## Test result: ✅ 

![Image](https://github.com/amplication/amplication/assets/2861984/39ce382e-497d-4073-b387-a73200d2a9fb)
