### ISSUE TITLE
Notification center's events

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7539]
We would like to add events around the notification center-

1. An event when a user opens the notification center
2. An event when a user clicks on a notification
3. An event when a user enters a notification from the email

**Comment by barshimi** [comment]
I need clarification regard the notification events includes names

**Comment by PazYanoverr** [comment]
Adding it also here-
Event names-
OpenNotificationCenter
ClickNotificationMessage - add a prop of messageType (with only 1 possible option now- buildSucceeded)
ClickNotificationEmail - add a prop of messageType (with only 1 possible option now- buildSucceeded)
(@yuval-hazaz - in case you want to review it)

**Comment by overbit** [comment]
## Test Results: ❌ 

`OpenNotificationCenter` and `ClickNotificationMessage` are triggered successfully but it is missing the `ClickNotificationEmail` event.

![Image](https://github.com/amplication/amplication/assets/2861984/514f222e-efff-4305-ad03-92171406e394)

**Comment by mulygottlieb** [comment]
Email bsased notifications is descoped, therefore this is considered passed QA now
