### ISSUE TITLE
🐛 Bug Report: It's not possible to Add Action in custom modules 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7541]
### What happened?

<img width="1265" alt="image" src="https://github.com/amplication/amplication/assets/2861984/f53fc563-a6e0-4c89-b5cc-fa8a04c9d81b">

There is no way for a user to know why it cannot `Add Action` or if it could even.

Related to :
-  #7408

### What you expected to happen

Clicking on `Add Action` to open something or hovering to open a tooltip for the user

### How to reproduce

As enterprise user, create a new project and open the `Modules` tab

### Amplication version

next

**Comment by professorabhay** [comment]
Hey, @overbit! I would like to work on this.
Kindly tell me more about that.

**Comment by yuval-hazaz** [comment]
this feature is only part of phase 2 which is still under design and dev
