### ISSUE TITLE
🐛 Bug Report:Generated Controller unit tests doesn't work with auth-core plugin. 

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#7549]
### What happened?

Testing fails in a generated service with the auth-core plugin/ when installing and deleting the auth-core plugin. 

### What you expected to happen

Testing will pass. 

### How to reproduce

Generate a service with auth-core plugin and try to run tests.

**Comment by overbit** [comment]
Running `npm run test` on generated server with latest version of auth-core, we obtain the following errors:
<img width="1187" alt="image" src="https://github.com/amplication/amplication/assets/2861984/5df4a053-b088-4e64-8b38-0c7f648482b2">

**Comment by overbit** [comment]
## Test results: ✅
