### ISSUE TITLE
🐛 Bug Report: builds using DSG versions `<v2.2.0` fail 100% of the time

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7550]
New DSG versions that support build split work, but old DSG versions that don't support build split fail without any message

<img width="1671" alt="image" src="https://github.com/amplication/amplication/assets/2861984/d1d0fe92-08d1-4681-8136-11845624bf99">

_Originally posted by @overbit in https://github.com/amplication/amplication/issues/7494#issuecomment-1840670806_

**Comment by overbit** [comment]
<img width="1510" alt="image" src="https://github.com/amplication/amplication/assets/2861984/7b08916e-27ae-4731-a6a9-16f33ad0a501">

**Comment by levivannoort** [comment]
QA:

![image](https://github.com/amplication/amplication/assets/73097785/061fb06a-6f79-425b-b296-7edfe3ec3a7a)
