### ISSUE TITLE
Build log is not clear when logs are coming from server or admin-ui generation

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7554]
### Feature description

![image](https://github.com/amplication/amplication/assets/2861984/fbc99f97-3d6d-41f7-bb4a-fad1d1d25807)

As shown, logs seems to be duplicated but they are coming from different jobs generators

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by levivannoort** [comment]
QA:
![image](https://github.com/amplication/amplication/assets/73097785/0d56d516-1391-4c1d-aaca-f868b3069254)
