### ISSUE TITLE
Custom Actions: "Relation" methods do not appear after migration

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7561]
After the "custom actions" migration, the methods displayed in the Modules tab do not include the "relation" methods, e.g. in case the entity "User" has a relation with the entity "Verification Token", the relation methods do not appear in the User list, nor in the Verification Token list (- see attached for the missing methods)

![Image](https://github.com/amplication/amplication/assets/149934977/2ccc8704-3540-440b-8073-3e05c5fc014d)

It seems that relations which are defined after the migration- do appear in the Modules tab (but it should be doube-checked)

**Comment by overbit** [comment]
### Test result: ✅ 



![Image](https://github.com/amplication/amplication/assets/2861984/0eabab43-27cd-4051-bd7b-8c2bfa4afe5a)
