### ISSUE TITLE
🐛 Bug Report: Snapshot tests are failing on branch `next` after updating the `auth-jwt` plugin

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7567]
### What happened?

Snapshot tests are failing on branch `next` after updating the `auth-jwt` plugin

### What you expected to happen

not to fail on the CI

### How to reproduce

on every pr that changes something in code-gen-types/data-service-generator

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by overbit** [comment]
## Test result: ✅ 

https://github.com/amplication/amplication/actions/runs/7197792740
