### ISSUE TITLE
🐛 Bug Report: backend.tf file not generating expected values [provisioning-terraform-gcp-core]

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7569]
### What happened?

![image](https://github.com/amplication/amplication/assets/73097785/803813eb-f4e3-4ae0-920e-6867f7109107)

`backend.tf` contains `undefined` instead of valid backend code for gcp, i.e. local or gcs.

### What you expected to happen

By default the GCP Core plugin should generate a valid backend.tf file.

### How to reproduce

Install GCP Core plugin and build the service.

### Amplication version

0.0.2 [plugin]

**Comment by varsubham** [comment]
@levivannoort i have raised a fix, please review if this looks fine

Thanks

**Comment by levivannoort** [comment]
@varsubham thanks for the pull request ill look into it shortly.

**Comment by levivannoort** [comment]
QA:
<img width="771" alt="image" src="https://github.com/amplication/amplication/assets/73097785/a54fc898-a3fb-406d-b066-2bd61fedc8bb">
