### ISSUE TITLE
Notification center (new design) - Bugs

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7586]
1. Is it possible to add to the email also the name of the service? I get a few emails which differ in the build id only. It's hard to understand why I get a few emails without the service name.
2. After the first build- the notification added to the list, but I had no indication next to the alarm or such that I have new notifications. In the proceeding builds- I got emails, but no notification was added to the notification center - see below. Only after pressing the "view build log", I got at once all the 8 build messages + notification in the alarm.
@mulygottlieb - "This is proably about client hooks (when do changes get visible). I assume if you refreshed the page you would get all the notifications + bell icon"
 
![Image](https://github.com/amplication/amplication/assets/149934977/14a16e79-af35-487d-adef-5cf02b8b8cdb)
![Image](https://github.com/amplication/amplication/assets/149934977/df125cef-31ec-4dca-9adf-f6d70a7990d8)

**Comment by barshimi** [comment]
the first request is doable. the second, I can check, but I'm not sure we can do something about it. it is part of the local scope of Novu components

**Comment by PazYanoverr** [comment]
@barshimi - So let's also check the second issue, as I would be surprised that this is the user experience that Novu supplies.
@mulygottlieb

**Comment by barshimi** [comment]
After the first build- the notification added to the list, but I had no indication next to the alarm or such that I have new notifications -> the notification is a closed feature, we need to open the network in order to get notification. can it be that this is the reason you don't see the bell and the notifications ?

**Comment by PazYanoverr** [comment]
@barshimi - No, it's a different issue (and after discussing it with you, the issue you've described seems to be ok.
However, I tried to reproduce the refresh issue, and I didn't manage. It's your lucky day :)

**Comment by overbit** [comment]
## Test results: ✅ 



![Image](https://github.com/amplication/amplication/assets/2861984/3a368aae-3551-4294-8acd-cc5e3a180394)



![Image](https://github.com/amplication/amplication/assets/2861984/6566a7c0-2502-473c-90d0-92920e37fcf5)
