### ISSUE TITLE
Server: Changing and then changing back to original state is still counted as change

### ISSUE THREAD

**Issue by iddan** [amplication/amplication#761]
Steps to reproduce:
 1. Change data type of field
 2. Chagne back to original data type
 3. Still shows pending changes

**Comment by vimota** [comment]
Likewise for creating new entity then deleting entity, still shows up as a pending change.

**Comment by yenicelik** [comment]
same mechanics, but the github code diff doesn't show any resulting line changes (except the push version) which is good
