### ISSUE TITLE
Server: My Sample App - User Entity Capital Letter

### ISSUE THREAD

**Issue by alonram** [amplication/amplication#762]
When My Sample App is created one of the entities is "User". It was created with lower case (user), when trying to build I get the following error: 
"Error: Invalid entity name: "user". Name must start with a capital latin letter and only contain alphanumeric characters" 
Unable to correct entity name to capital because textbox is not enabled.
ckfe1nq2o157920ws67n8jr921/entities/ckfe1nq40158110ws6uwe3d5o3
![Screenshot (13)](https://user-images.githubusercontent.com/40050499/98263593-03b7f200-1f55-11eb-927a-a130e5b03712.png)
![Screenshot (12)](https://user-images.githubusercontent.com/40050499/98263595-04508880-1f55-11eb-9be3-e46af89fbb6f.png)

**Comment by yuval-hazaz** [comment]
We cannot reproduce this issue. it may be related to an old sample app that was created in the early stages,
