### ISSUE TITLE
Plugin categories - Improvements

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7625]
A few UI improvements for the plugin categories (- can be handled as part of the next plugin improvements)
See https://www.figma.com/file/DnFcgmEh2K751F3MYpiz7f/%237625---Plugin's-categories---Improvements?type=design&node-id=3401%3A2240&mode=design&t=An3URuf3OGLGjhjk-1
Notes:
1. By default the category list should be closed (same as today)
2. For each plugin, the category list should be displayed as 'labels' (Notion like) - see design. The labels should be clickable and affect the filter (- new filter)
3. Note the "View on GitHub" design and the font (size, weight) of the plugin's name and description.

**Comment by overbit** [comment]
## Test Results: ❌ 

Wrong colour is displayed in the `View on GitHub`

![Image](https://github.com/amplication/amplication/assets/2861984/551fab5b-0bf6-4b71-af60-871a9e5421a6)



![Image](https://github.com/amplication/amplication/assets/2861984/e84a6a9f-4dd2-4d83-a3a5-ac9d6c2dd7ff)

**Comment by overbit** [comment]
@PazYanoverr the label looks good but the rest did not match the requirements. If you are happy to release with this changes, please remember to update this issue description :)

**Comment by PazYanoverr** [comment]
Good catch, @overbit 
Let's update according to the design (and I will update the description)

**Comment by mulygottlieb** [comment]
Passed QA :


![Image](https://github.com/amplication/amplication/assets/1912933/a3e375b9-bf6a-4217-a7db-0e20757b00b9)
