### ISSUE TITLE
Bug: the code generator versions drop down appear empty with no versions

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#7657]
![image](https://github.com/amplication/amplication/assets/1912933/e016792c-d76f-4fb9-a70b-d0871298b48b)

**Comment by overbit** [comment]
## Test results: ✅ 

![Image](https://github.com/amplication/amplication/assets/2861984/b86a3b8b-b3e7-4892-951d-c4c0551d22d4)
