### ISSUE TITLE
🐛 Bug Report: generated code contains ts-ignore and lint ignore comments

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7668]
### What happened?

The current generated code contains "ignore" comments that should not be there. 
i.e.
<img width="1431" alt="image" src="https://github.com/amplication/amplication/assets/2861984/8216954d-4f7b-4371-8857-d843fbaa4cd9">

### What you expected to happen

As a production ready code written in ts, the generated code should not contain either of the following:
- `// @ts-ignore`
- `// eslint-disable-next-line import/no-unresolved`
- `// eslint-disable @typescript-eslint/no-explicit-any`

### How to reproduce

Build with latest code generator version (v.3.0.1)

### Amplication version

v1.12.3  (DSG v.3.0.1)

**Comment by overbit** [comment]
Discovered as part of https://github.com/amplication/private-issues/issues/104

**Comment by overbit** [comment]
@PazYanoverr  Maybe not 5 minutes but it shouldn't take much. The biggest time investment effort is detecting the origin of the issue (if from plugin or dsg core)

**Comment by Meyazhagan** [comment]
I removed most of ts-ignore and lint ignore comments from template files and static files! 
you check the PRs.

**Comment by PazYanoverr** [comment]
Great, thanks @Meyazhagan!
@mulygottlieb @overbit - Can you please review?

**Comment by mulygottlieb** [comment]
@overbit I am not sure why you moved this to "Ready for QA" since the PRs are not yet reviewed and merged. Moving this back to "Code Review" status
