### ISSUE TITLE
🐛 Bug Report: Json Logger INFO log error on v1.12.3

### ISSUE THREAD

**Issue by pmannion2** [amplication/amplication#7673]
### What happened?

After adding the `Json Logger` plugin to a service, I attempted to pull, and rebuild the code as necessary to run the service. It appears INFO log level was not included in the plugin, though I had not investigated deeper myself yet. 

### What you expected to happen

Log below

`[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [NestFactory] Starting Nest application...
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] LoggerModule dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] AccessControlModule dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] UserModuleBase dependencies initialized +1ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] BatchModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] PurchaseOrderModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] SuperbatchModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] RouteModuleBase dependencies initialized +1ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] AssetModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] ProductionOrderModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] ItemModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] InventoryModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] TestModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] OperationModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] RecipeModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] RouteRecipeModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] BomModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] OperationStepModuleBase dependencies initialized +1ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] TestTypeModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] TestParameterModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] GeneaologyModuleBase dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] PrismaModule dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] HealthModule dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] SecretsManagerModule dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] CacheModule dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +0ms
[Nest] 46304  - 12/20/2023, 11:04:38 AM   ERROR [ExceptionHandler] default level:INFO must be included in custom levels
Error: default level:INFO must be included in custom levels
    at assertDefaultLevelFound (C:\Users\PatrickMannion\WebstormProjects\whk-mes\apps\core-mes\node_modules\pino\lib\levels.js:167:11)
    at pino (C:\Users\PatrickMannion\WebstormProjects\whk-mes\apps\core-mes\node_modules\pino\pino.js:157:3)
    at new PinoLogger (C:\Users\PatrickMannion\WebstormProjects\whk-mes\apps\core-mes\node_modules\nestjs-pino\PinoLogger.js:54:51)
    at Injector.instantiateClass (C:\Users\PatrickMannion\WebstormProjects\whk-mes\apps\core-mes\node_modules\@nestjs\core\injector\injector.js:365:19)
    at callback (C:\Users\PatrickMannion\WebstormProjects\whk-mes\apps\core-mes\node_modules\@nestjs\core\injector\injector.js:65:45)
    at Injector.resolveConstructorParams (C:\Users\PatrickMannion\WebstormProjects\whk-mes\apps\core-mes\node_modules\@nestjs\core\injector\injector.js:144:24)
    at Injector.loadInstance (C:\Users\PatrickMannion\WebstormProjects\whk-mes\apps\core-mes\node_modules\@nestjs\core\injector\injector.js:70:13)
    at Injector.loadProvider (C:\Users\PatrickMannion\WebstormProjects\whk-mes\apps\core-mes\node_modules\@nestjs\core\injector\injector.js:97:9)
    at Injector.resolveComponentHost (C:\Users\PatrickMannion\WebstormProjects\whk-mes\apps\core-mes\node_modules\@nestjs\core\injector\injector.js:215:13)
    at resolveParam (C:\Users\PatrickMannion\WebstormProjects\whk-mes\apps\core-mes\node_modules\@nestjs\core\injector\injector.js:128:38)
`

### How to reproduce

Add Json Logger Plugin to v1.12.3 Amplication build, run locally via `npm run start` 

### Amplication version

1.12.3

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by overbit** [comment]
@pmannion2 if you have set some custom settings when installing this plugin, please replace them with the following and rebuild:
```json
{
  "logLevel": "info",
  "additionalLogProperties": {}
}
```

if not, just rebuild!
