### ISSUE TITLE
🐛 Bug Report: blank pages when clicking around the platform

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7678]
### What happened?

https://jam.dev/c/ea2863ee-aa71-4933-96bd-e8369bbad201

and another error in the console that doesn't appear every time: `Cannot convert undefined or null to object`

![image](https://github.com/amplication/amplication/assets/39680385/c559ddac-f469-49e2-b419-16d4e2619aae)

### Amplication version

1.12.3

**Comment by PazYanoverr** [comment]
Happened to me a few times as well. 
Seems like an important issue to handle.
@mulygottlieb

**Comment by PazYanoverr** [comment]
Happened again -
![Image](https://github.com/amplication/amplication/assets/149934977/1cfcebe1-5b4c-492d-8e30-9dd7178709c4)

**Comment by mulygottlieb** [comment]
It no longer happens, moving to "Done" status.

**Comment by mulygottlieb** [comment]
Passed QA ✅
