### ISSUE TITLE
Client: Add details on the differences between name and display name when creating an entity field or entity

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#768]
**Is your feature request related to a problem? Please describe.**
When creating a new entity field, there are two different fields for name "display name" and "name".
The differences and usage of each between the two fields is unclear.

**Describe the solution you'd like**
Add a tooltip to describe what are the differences

**Describe alternatives you've considered**
hide one of the fields from the user until later stages in the processes

**Additional context**
This should be implemented anywhere we use "Name" field

**Comment by yenicelik** [comment]
this is implemented, can be closed?
