### ISSUE TITLE
🐛 Bug Report: mismatch in ports on nginx configuration & dockerfile exposed port

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7680]
### What happened?

When working with a generated application (after the non-privileged user changes) in Kubernetes. I noticed that there was an issue on exposing the admin-ui part. The dockerfile exposes port `80`, this has been so for quite a long time. However with the changes where we moved from a root user to a non-root user we also had to add nginx configuration to use a different port as a non-privileged user is not allowed to bind port `80`, that is why port `8080` was set in the `admin-ui/configuration/nginx.conf`.

However now the Dockerfile exposes port `80` and the process in the container is actually running under the port `8080`, letting

### What you expected to happen

That the ports used on the process & exposed on the container align. So either align the dockerfile to be `8080` as the nginx.conf file is OR align it what is generated in the `.env` and mentioned in the readme, that it uses port `3001`.

### How to reproduce

Generated a service and also include the admin-ui component. Try and run the service as the docker container, and try to acces the service on the exposed port (`80`)

### Amplication version

v1.12.3

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/efbe9510-9b9b-40a6-a037-dd60addc7cf1)


![Image](https://github.com/amplication/amplication/assets/1912933/08e53f90-8a19-4ad2-947d-334dffeb75a2)


![Image](https://github.com/amplication/amplication/assets/1912933/342c306c-cddd-4a84-a399-a7fe788ee197)
