### ISSUE TITLE
Client: Geographic address should be called "coordinates"

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#769]
**Is your feature request related to a problem? Please describe.**
The field data type "geographic address" can be easily confused with "street address". 

**Describe the solution you'd like**
Change the name of the data type to "coordinates" 

**Describe alternatives you've considered**
Consider adding a built in data type for "street address" which will hold a structured data including street, city, state ,zip etc.

**Comment by MichaelSolati** [comment]
I'll take this, I've done a lot in the world of geo so I think I can manage this.

**Comment by yuval-hazaz** [comment]
@MichaelSolati thanks!
please note, for backward compatibility we should not change the actual data type, but just renaming the display name of the type in the UI
