### ISSUE TITLE
Breaking the monolith (phase 1)

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7695]
Spec:
https://www.notion.so/amplication/Breaking-the-Monolith-Phase-1-ee82ceea689f4b15b3a422077a91d014?pvs=4

Design:
https://www.figma.com/file/SSOYJbY3vYMjwcNUABSjwd/UX%2FUI---Breaking-the-monolith-(phase-1)?type=design&node-id=757%3A1353&mode=design&t=OiiciJ4JI4asHFmn-1

**Comment by PazYanoverr** [comment]
@mulygottlieb - created this issue for "breaking the monolith" project. Note that the design is complete.

**Comment by mulygottlieb** [comment]
@PazYanoverr I think we may want to converge it with the existing ticket https://github.com/amplication/amplication/issues/7581

**Comment by PazYanoverr** [comment]
@mulygottlieb - Great, closing this ticket as duplicate

**Comment by mulygottlieb** [comment]
@PazYanoverr I copied the comment for the spec and design to the original issue #7581 and I am closing this one.
Let's make sure to add subtasks there as we go.
