### ISSUE TITLE
🐛 Bug Report: server error on logout

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7708]
### What happened?

![image](https://github.com/amplication/amplication/assets/39680385/09c7549d-77cc-41c5-b6c6-f653f2d8011e)

### How to reproduce

logout

**Comment by abrl91** [comment]
![image](https://github.com/amplication/amplication/assets/39680385/ae27c52e-e842-4c6f-80da-ab65e3e3e88c)

**Comment by mulygottlieb** [comment]
According to @barshimi , this only happens for localhost and not in any other environment, and therefore we can ignore this for now. Closing this ticket.
