### ISSUE TITLE
Snapshots tests are failing on branch next

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7711]
This happened after fixing the formatting and the linting in our plugins.

![image](https://github.com/amplication/amplication/assets/39680385/d3d570ef-c9b5-4777-86d0-95281aecf07e)

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/b032acc3-a84b-4614-bca2-8659b25f0cd9)
