### ISSUE TITLE
New plugins' experience

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7714]
Spec-
https://www.notion.so/amplication/New-Plugins-Experience-1fbe7cecaec942058c79aa0f3ea15dd1?pvs=4

Design-
https://www.figma.com/file/xlAggFpOUjN1efy6j9HX3c/UX-Improvement---Plugins-arrangement?type=design&node-id=2476%3A887&mode=design&t=4xt7juQkFVrNMTTT-1

**Comment by PazYanoverr** [comment]
@mulygottlieb @yuval-hazaz @abrl91 - Please review the updated spec (based on the new design and Shimi's comments).

**Comment by abrl91** [comment]
@PazYanoverr @mulygottlieb 
It looks good. Passed my QA ✅ 


https://github.com/amplication/amplication/assets/39680385/3e78db1d-54c3-4f4a-be1d-756333a992ca
