### ISSUE TITLE
🐛 Bug Report: premium feature indicator on the custom action page for enterprise - not in trial

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7715]
### What happened?

![image](https://github.com/amplication/amplication/assets/39680385/87e8e911-08d4-46fa-b9fa-9ae33c902630)

### What you expected to happen

no indication at all

### How to reproduce

- enterprise not in trial workspace
- custom actions add-on

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/3cdf0cd9-1710-4b5e-ad82-0f36659957e8)



![Image](https://github.com/amplication/amplication/assets/1912933/58c5c9d5-a38b-4447-8e6a-dc9c28dcadd9)
