### ISSUE TITLE
As Product Manager - I want an easy way to experiment with GPT GW Prompts I define and be able to tweak them iteratively

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#7722]
The GPT GW UI only allows the basic CRUD operations to create/delete messages.
We need to augment it (or find another easy way) so that we can use it to experiment with defined messages (prompts) - send them to OpenAI and see the responses in order to be able to tweak the various prompts.

It doesn't have to be a full-blown UI. Any easy way that will allow the Product team to experiment with the defined prompts and tweak them is good enough.

Related to: https://github.com/amplication/private-issues/issues/104

**Comment by overbit** [comment]
Issues:

- Generated admin-ui is created with react-admin v3 and it doesn't support custom pages
- gpt-gateway only support a Kafka event based architecture
-
