### ISSUE TITLE
🐛 Bug Report: Import Prisma schema error: In the entity "<EntityName>", there is no field referencing the entity "<ReferencedEntityName>"

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7724]
### What happened?

![image](https://github.com/amplication/amplication/assets/39680385/5d195616-ef4a-4ed9-a215-bcaa389bc979)

### How to reproduce

Import prisma that has more than one named relation

### Amplication version

1.12.3

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mulygottlieb** [comment]
Passed QA:


https://github.com/amplication/amplication/assets/1912933/c492a5cd-1213-4399-8d0f-5b6e1f1f94db
