### ISSUE TITLE
🐛 Bug Report: Log level configuration is not respected in production

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7738]
### What happened?

![image](https://github.com/amplication/amplication/assets/2861984/59449ec9-72b8-43d3-8580-e7dd6483dccf)

### What you expected to happen

Only errors that with level higher then the configured LogLevel should be logged.

### How to reproduce

Check the log platform

### Amplication version

v1.12.5

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by RohanMishra315** [comment]
Hey @overbit Can I look at the issue ?
