### ISSUE TITLE
🐛 Bug Report: `gpt-gateway` uses the wrong logger in non local envs

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7741]
### What happened?

<img width="718" alt="image" src="https://github.com/amplication/amplication/assets/2861984/9fbdc22c-cd0d-4a61-b30a-4e82ceaf3a42">

### What you expected to happen

To use the amplication json logger

### How to reproduce

check if logger platform shows any log entry

**Comment by overbit** [comment]
Related to https://github.com/amplication/amplication/issues/7722

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/d5ee0ef5-d3b6-47bc-8bfe-04fc2856eebf)
