### ISSUE TITLE
`@amplication/util/nestjs/kafka` KafkaProducer must validate message against schema before emitting 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7742]
### Feature description

Currently KafkaProducerService doesn't perform any data validation against the schema registry defined event key and value before emitting a Kafka event.
This can be the source of big issues where a message not conform to the specs is published as all the consumer might fail and stop processing other events due to unexpected data.

Instead, the producer should validate and through relevant exceptions in case of validation failures to avoid issues down the line.

**Comment by xonx4l** [comment]
Add:KafkaProducer validate message against schema before emitting . #7776.  Feedback@overbit.
