### ISSUE TITLE
🐛 Bug Report: `gpt-gateway` fails on JSON encoded kafka messages 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7744]
### What happened?

Messages like the following will cause the  `gpt-gateway`  service to fail with no recovery possible:
```json
{
    "requestUniqueId": "dani-1",
    "messageTypeKey": "BREAK_THE_MONOLITH",
    "params": [
        {
            "userInput": "for a ecommerce platform"
        }
    ]
}
```

<img width="802" alt="image" src="https://github.com/amplication/amplication/assets/2861984/e6e40274-7216-4f3f-977f-2b49a411e130">

### What you expected to happen

Currently, the `gpt-gateway` is expecting strings as message in `ai.conversation.start.1` topic but it should instead relying on the json representation of the message avoiding any stringify / parsing.

### How to reproduce

.

**Comment by abrl91** [comment]
✅  Passed QA

from Kaka UI:
![Image](https://github.com/amplication/amplication/assets/39680385/adf0dbed-3d28-480f-b0ed-3dc138ccb974)
