### ISSUE TITLE
Improve DevEx for local environment for Kafka event based services

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7749]
### Feature description

In order to simplify development and testing of services that rely on Kafka events, a user would need an easy way to publish messages in JSON format. Currently the only easy out-of-the-box in amplication local environment, is to use kafka-ui but it only support variation of number, Avro or string format making impossible to send json key or value messages.

The current setup, causes developer to mistake the expectations, as it would always expect a string, once instead in a production environment where other services send messages, the event will consists of key and values in JSON format.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by overbit** [comment]
This is potentially the reason for the wrongly implemented parsing here: https://github.com/amplication/amplication/issues/7744

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/13cfbe1a-b061-4576-be00-b12e1a2d7a24)
