### ISSUE TITLE
🐛 Bug Report: When changing the type of a relation (1:m, m:1, 1:1,m:m) the default actions are not updated 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#7752]
### What happened?

When changing the type of a relation (1:m, m:1, 1:1,m:m) the default actions are not updated.

### What you expected to happen

The default actions should be updated based on the new type of relations

### How to reproduce

Initial state:
entity Customer, field City 
entity City, field customers
Relations: one customer can be related to one city

default actions:
Customer module - Customer Get City
City Module - City Connect Customers, City Update Customers, City Find Customers, City Disconnect Customers

Change the relation on the customer side to "one customer can be related to many cities"
expected: 
the default actions on the customer module to be changed from " Customer Get City" to 
- Customer Connect Cities
- Customer Disconnect Cities
- Customer Update Cities
- Customer Find Cities

### Amplication version

1.12.5

**Comment by morhag90** [comment]
QA FAILED: 

<img width="1019" alt="image" src="https://github.com/amplication/amplication/assets/97830649/93405940-fea8-41e2-bba0-e360aced4b62">

<img width="1234" alt="image" src="https://github.com/amplication/amplication/assets/97830649/82a19cc0-332b-4b7a-8566-0ec9e02f65dd">

**Comment by mulygottlieb** [comment]
Re-QA:
It does work as expected, but there is a cache issue in the modules tab - meaning that when you go back to the modules tab you still see the old module actions but after a full page refresh you get the updated actions for the n:n relation as expected.
@yuval-hazaz do you want to keep this as re-opened to fix the cache issue, or open a new issue for the cache and mark this one as passed QA?

**Comment by mulygottlieb** [comment]
Moving this to passed QA based on the re-test (with full refresh):
![image](https://github.com/amplication/amplication/assets/1912933/097d58e0-1fa0-46ad-a3f5-2e4570268723)

Will open a separate issue for the modules cache issue

**Comment by mulygottlieb** [comment]
cache issue reported in:
https://github.com/amplication/amplication/issues/7847
