### ISSUE TITLE
CI is failing on build and dockerize due to Nx cache issues

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7760]
<img width="1046" alt="image" src="https://github.com/amplication/amplication/assets/39680385/b1a09628-7289-47cd-a27d-6b1ea97705f1">

<img width="1046" alt="image" src="https://github.com/amplication/amplication/assets/39680385/b5ee7c82-9478-405d-a82e-78ccff0edfd1">

<img width="1057" alt="image" src="https://github.com/amplication/amplication/assets/39680385/68b60a43-0eb5-42aa-a283-7834c88de3b4">

**Comment by overbit** [comment]
Fixed by clearing the node_module cache

**Comment by overbit** [comment]
Still happening
https://github.com/amplication/amplication/actions/runs/7503351067/job/20427925039#step:10:82

**Comment by mulygottlieb** [comment]
Looks good after upgrading the nx version:


![Image](https://github.com/amplication/amplication/assets/1912933/71f0fe28-6846-493b-b225-663d17a42ceb)


Will re-open if this surfaces again, for now it seems okay so moving this to passed QA
