### ISSUE TITLE
Update `integration-openai` plugin to generate code using openai SDK v4

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7766]
### Feature description

The current version of the plugin is generating code that leverage openai SDK v3. This request is to update it so users will use the latest major version of the SDK.

v3 to v4 Migration Guide : https://github.com/openai/openai-node/discussions/217

**Comment by mulygottlieb** [comment]
Passed QA (code dependency updated):


![Image](https://github.com/amplication/amplication/assets/1912933/d36dc61e-4a0a-4532-b7cc-89b0dac92d14)
