### ISSUE TITLE
The CI on branch `next` is failing on various errors on the build step

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7770]
1. https://github.com/amplication/amplication/actions/runs/7459804953/job/20296914508#step:10:479
2. https://github.com/amplication/amplication/actions/runs/7459804953/job/20296914508#step:10:738

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/bd403649-1d2e-4337-aece-510eb280e4f6)
