### ISSUE TITLE
`amplication-client` eslint rules are too permissive

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7777]
Current configuration for ESLint rules for the client will allow the following:

```json
"rules": {
        "@typescript-eslint/ban-ts-comment": "off",
        "@typescript-eslint/no-empty-function": "off",
        "@typescript-eslint/no-explicit-any": "off",
        "react-hooks/exhaustive-deps": "off",
        "react/jsx-no-useless-fragment": "off",
        "no-console": "off"
      }
```

These rules are too permissive and don't help developer to prevent potential issues like missing dependencies in react hooks.

The new set of rules should be:
```json
"rules": {
        "@typescript-eslint/ban-ts-comment": "warn",
        "@typescript-eslint/no-empty-function": "off",
        "@typescript-eslint/no-explicit-any": "warn",
        "react/jsx-no-useless-fragment": "off",
        "no-console": "off"
      }
```

**Comment by mulygottlieb** [comment]
@overbit Don't you want to put the `exhaustive-deps` as `warn` as well for now? Otherwise, we would have to review and fix many existing places in the client.

**Comment by overbit** [comment]
@mulygottlieb the default value for that rule is already `warn` but we can make it explicit if needed.

**Comment by mulygottlieb** [comment]
I'm changing the required result to include 
`"@typescript-eslint/ban-ts-comment": "warn"`   (instead of removing the exclusion completely and turning this to error)
since without this exclusion, we have several lint errors I do not wish to address ATM

CC: @yuval-hazaz @overbit

**Comment by mulygottlieb** [comment]
Passed QA - changes applied to the next branch:


![Image](https://github.com/amplication/amplication/assets/1912933/2575108c-da01-4808-8295-5042e6a91776)
