### ISSUE TITLE
BTM - Update the Prisma schema upload flow

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7815]
The flow of the upload should be updated to the following:
1. Initial screen- same as today, i.e. 

![Image](https://github.com/amplication/amplication/assets/149934977/f9194f25-4b50-4e89-92f0-e517f3b88d7b)

2. During the upload process - the progress part should be just as today - 

![Image](https://github.com/amplication/amplication/assets/149934977/74abf392-c524-45a8-a420-5ad96ca54500)

while the top part should be like defined in the design- 

![Image](https://github.com/amplication/amplication/assets/149934977/0f2fdea5-aa9e-432a-9973-1f1f0f933dd3)

3. In case the upload succeeded - follow the design- 

![Image](https://github.com/amplication/amplication/assets/149934977/a9e3b6d5-3166-48a1-b389-5328ebdcdcb2)

(but no need to update the design of the logs' "screen" part)
4. In case the upload failed - the logs' "screen" should be same as today, while the upper "text" should be updated to "Schema import failed" (- as the title => same font and design like the "Schema import completed successfully" in the design), and the sub-title should include the error message (better the one that includes the call-to-action text). In the below example: "The relation attribute on field "permission" contains multiple fields. Only one single field is supported"

![Image](https://github.com/amplication/amplication/assets/149934977/b33b6766-17e5-4e94-a9ae-0d8b87a53e89)
5. In case of a successful upload, and the user chooses to finish the process without AI, the user will be redirected to the “entities” tab of the service.
6. In case of a successful upload, and the user chooses to use AI, the “Breaking the monolith automatically” flow will be applied (- see Spec)
    1. One exception- in case the user chooses to “Cancel” the AI result, the Entities tab should be displayed (without applying the AI suggestion).

**Comment by overbit** [comment]
Test result ❌ 

3. design doesn't match requirements: 

![Image](https://github.com/amplication/amplication/assets/2861984/e20998b4-31d6-4139-9c73-250768ba0e46)

4. Title doesn't match requirement and subtitle shows wrong message
![Image](https://github.com/amplication/amplication/assets/2861984/9137cd41-8318-4e4a-9c26-c0461eaec228)

**Comment by abrl91** [comment]
> Test result ❌
> 
> * [ ]  3. design doesn't match requirements:
> 
> ![Image](https://private-user-images.githubusercontent.com/2861984/307303645-e20998b4-31d6-4139-9c73-250768ba0e46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Mzk0MDMsIm5iZiI6MTcwODkzOTEwMywicGF0aCI6Ii8yODYxOTg0LzMwNzMwMzY0NS1lMjA5OThiNC0zMWQ2LTQxMzktOWM3My0yNTA3NjhiYTBlNDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMDkxODIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmViOWMxMGMzMmFlMjQ0N2I0NjkzZTk0MTM1NDBmNWZmMDc0OGFhZGMwNjg0NGQzMjBhZDI0ZGM4NzRlY2Q2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8nD5deVFloIllNN4HxiiTs_tUoZh3sE_2Ypn9RONAz8)
> 
> * [ ]  4. Title doesn't match requirement
> * [ ]  4. Subtitle shows wrong message
>   ![Image](https://private-user-images.githubusercontent.com/2861984/307304201-9137cd41-8318-4e4a-9c26-c0461eaec228.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Mzk0MDMsIm5iZiI6MTcwODkzOTEwMywicGF0aCI6Ii8yODYxOTg0LzMwNzMwNDIwMS05MTM3Y2Q0MS04MzE4LTRlNGEtOWMyNi1jMDQ2MWVhZWMyMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMDkxODIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjEwNmVjZWFhY2ZkNjc4YjIzM2U5MDZhOGZkM2Q1MDMyY2VkODU5YWQ3ZmIzYTE0ZTA5MzkxZTA0YTViZjBiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oun3DEfENKl2GzL7ZSECtbu0EI6axuffUfPEe_udFxA)

Regarding the button, we decided to use small buttons.
As to the error message - I'll fix it.

**Comment by overbit** [comment]
Test result ✅ 

![Image](https://github.com/amplication/amplication/assets/2861984/50c0c35d-5d2c-496e-b9fb-34b6d17fdce4)
