### ISSUE TITLE
Expose BTM AI recommendation for an easy display to the user

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7818]
Once BTM generation is completed, the suggestion must be persisted and be retrievable by any client through a GraphQL query. 
The query must be protected by auth, and the resulting data must be returned only to the users of the workspace where the resource belong to.
In any other case, an unauthorised error should be returned.

## Tech notes

GQL query: 
```gql
query FinalizeBreakServiceIntoMicroservices($userActionId: String!) {
  finalizeBreakServiceIntoMicroservices(userActionId: $userActionId) {
    data {
      microservices {
        name
        functionality
        dataModels {
          originalEntityId
          name
        }
      }
    }
    status
    originalResourceId
  }
}
```

The query above will be easy to map to the data needed in the UI [#7819](https://github.com/amplication/amplication/issues/7819) and the Architecture UI https://github.com/amplication/amplication/issues/7693

**Comment by overbit** [comment]
```ts
resources.map(resource => {
    name: resource.name
    entities: entities.filter(entity => entity.targetResourceId === resource.id).map(entity => {
        name: entity.name
    })
})
```

**Comment by abrl91** [comment]
The recommendation output was changed to
```
"microservices": [
  {
    "name": string // service name
    "functionality": string, // description
    "dataModels": [
      {
        "originalEntityId": string,
        "name": string // entity name
      }
    ]
  },
]
```

**Comment by overbit** [comment]
Test result ✅ 

![Image](https://github.com/amplication/amplication/assets/2861984/13a41d45-b3b2-45af-a0ed-382540137c62)
