### ISSUE TITLE
As User - I want to review the AI suggested BTM services and entities

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7819]
As a user, when the generation is completed, I want to be presented with the list of resources with their entities and fields.

Details:
1. There are a few places in which the AI flow should be activated-
      1. Project Overview ("BTM")
      2. Service Overview ("BTM")
      3. Architecture tab; Overview mode ("AI Helper")
      4. Architecture tab; Redesign mode ("AI Helper")
      5. Upload Prisma flow ("AI Helper")
2. In the following places pressing the button will open an option to choose one service to break out of all the services available- # i, # iii above. The rest of the places will use the service which is in the current context.
3. After we have the relevant service to break, the following will take place-
       i. The service data should be sent to OpenAI
       ii. The loader will be displayed with the following text-
            1. Headline- "Experience the Microservices Marvel using Amplication AI"
            2. Text- "Our AI-driven magic is currently at work, suggesting how to elevate your Service (<service name>) and its entities into a thriving microservices wonderland"
            3. Concept of the design- see below
       iii. The user will be able to Close the modal / screen, and stop the process
4. When we have the results from OpenAI, the following will take place-
       1. Headline- Microservices Suggestion by Amplication AI
       2. Text- Our AI has mapped out a sleek microservices architecture for you. Check out the suggested breakdown and start streamlining your system
       3. The suggested Services should be displayed in "cards" while each card title is a service name, and the content of the card is the relevant entities.
       4. The CTAs of the modal / screen should be "Cancel" and "Let's go!"
5. The flow should appear as a modal in the following cases- # iii, and # iv. In the other cases- the flow will appear as a full screen. 
6. Check also https://github.com/amplication/amplication/issues/7864, as the design may overlap (and should be implemented only once...)

<img width="807" alt="image" src="https://github.com/amplication/amplication/assets/149934977/baaa80d3-beae-4c35-b911-c2b27018ec03">

Events:
- [ ] The user presses a "Break the monolith" button on an existing service/project
   - Name: StartBreakTheMonolithClick
   - Parameters: 
      - Button location (where was it pressed: service/project/schema upload/etc.) 
      - Service name
      -  The user's plan type (Enterprise, Trial, Free, Preview)

## Tech notes
Data to be displayed and stored in the local storage can be retrieved from  #7818

**Comment by PazYanoverr** [comment]
@yuval-hazaz @abrl91 @mulygottlieb - Please review the ticket description, and share your comments

**Comment by overbit** [comment]
Test result ✅ 

https://jam.dev/c/4f5bc98e-6a70-4899-817b-2df43b0e65e3
