### ISSUE TITLE
BTM- Handle name collisions (client)

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7820]
We should handle name collisions which may occur as part of the BTM flow-
- [x] Entity names- An error message should appear in case moving entities between services and name collision occurs. The error should include the name of the "problematic" entity/entities.
- [x] Service names- In case creating a new service with a name collision(between services)- an error message should appear. The error should include the name of the "problematic" service.

**Comment by mulygottlieb** [comment]
Passed QA:


https://github.com/amplication/amplication/assets/1912933/b86f81b1-c0a4-4c4f-8afd-852e8ff6ff2f
