### ISSUE TITLE
🐛 Bug Report: Signup with business email fail unclear message 

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7826]
### What happened?

![image](https://github.com/amplication/amplication/assets/39680385/53d09cdc-f00b-49b8-9bd0-1ec978a8d95d)

### What you expected to happen

To see a clear error message

### How to reproduce

just enter invalid work email

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mulygottlieb** [comment]
Passed QA:

![Image](https://github.com/amplication/amplication/assets/1912933/33fc0b1e-6ed8-4a8f-be2b-c57b50a8754a)
