### ISSUE TITLE
🐛 Bug Report: invite member fails on limitation for enterprise plan

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7835]
### What happened?

 Invite member fails on limitation for enterprise plan

### What you expected to happen

enterprise plan should not have a limitation on invite member

### How to reproduce

Invite a member while your workspace on an enterprise plan

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/38dd73ef-fffc-46d6-a624-3edd1bcc850f)
