### ISSUE TITLE
Update the style of the sign up flow

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#7839]
### What happened?

The current signup flow style requires an updated based on the below

<img width="849" alt="image" src="https://github.com/amplication/amplication/assets/43705455/716550f8-3d01-4e43-852d-a60d113c15be">

### What you expected to happen

fix style

### How to reproduce

na

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/7ca0cbd0-8d3b-4e92-a1f3-55cdad440f32)
