### ISSUE TITLE
🐛 Bug Report: Number of entities limitation warning appears in the Free Plan although it's no longer relevant

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#7866]
In the entities screen of a service, while in a free Plan, you get a warning on the screen for the limitation to 7 entities per service, which is no longer relevant.
This should not appear on the screen.

![Image](https://github.com/amplication/amplication/assets/1912933/85a21afb-9d52-4858-8fcc-37bc3c176231)

**Comment by abrl91** [comment]
✅ passed QA



![Image](https://github.com/amplication/amplication/assets/39680385/8a2db590-c549-4407-b9a0-01dc8510fc99)
