### ISSUE TITLE
🐛 Bug Report: Login with Business email fails with custom auth domains

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7880]
### What happened?

https://jam.dev/c/d6b98efc-67b3-43af-94ca-27f4e7184cea

### What you expected to happen

Not to fail.

### How to reproduce

Try to login with a business email in staging

### Amplication version

next

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/59e7307c-9f4e-40a0-912c-b8e910cf4821)



![Image](https://github.com/amplication/amplication/assets/1912933/019f832d-fb72-4528-977f-ff5765ecc1bb)
