### ISSUE TITLE
BTM - UX of the user that returns to the Architecture-Redesign screen

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7883]
In case a user (1) did some architecture changes in the Architecture-Redesign mode, (2) moved to other screen (! Architecture tab), and (3) back to the Architecture tab:
1. The Redesign mode should be displayed.
2. A pop-up message should appear saying 
"Your architecture tweaks are ready to be applied, allowing Amplication to generate its code. 
To reset or fetch updates not in the current state, use the buttons in the top toolbar." 
with "Got it" CTA.
3. The redesign state should be taken from the local storage, and avoid fetching updates from the server, unless specifically requested by the user.

Note:
1. In case a user (1) moved to the Redesign mode, but did not change anything, and then (2) moved to other screen, and (3) back to the Architecture tab - the Overview tab should be displayed for her (- with the up-to-date state, taken from the server)

**Comment by overbit** [comment]
Test result ✅ 

![Image](https://github.com/amplication/amplication/assets/2861984/a8b96688-833a-4900-ad08-00380bda297a)

**Comment by overbit** [comment]
Related to amplication/private-issues#159
