### ISSUE TITLE
BTM: Redesign not disabled without the proper entitlement

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#7886]
When I don't have the redesign entitlement, the redesign button is not disabled.

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/1b549b8b-9acd-4d15-b24c-5b1e11f2f9fa)



@morhag90 look at the tooltip itself, not sure it's the tooltip we want
