### ISSUE TITLE
🐛 Bug Report: New services created in the Architecture redesign mode do not inherit the Project Git connection

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#7892]

**Comment by overbit** [comment]
# Test result: ❌ 

Git provider doesn't look properly connected.

https://jam.dev/c/4857892d-b71a-4efc-a2a9-4c479747884f

**Comment by overbit** [comment]
@yuval-hazaz can you please double check this? (check the video above for details)

**Comment by mulygottlieb** [comment]
Passed QA:


https://github.com/amplication/amplication/assets/1912933/9dbcff50-ad73-411c-9dd4-171a6361159c
