### ISSUE TITLE
CI workflow using deprecated node version 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7893]
![image](https://github.com/amplication/amplication/assets/2861984/1b6f8d2d-c7bd-46e7-bad9-e00438421a9b)

**Comment by mulygottlieb** [comment]
Passed QA - Current CI job annotations do not include warnings about Node16 as they had previously:


![Image](https://github.com/amplication/amplication/assets/1912933/c8ba78f8-2a25-43b0-aa26-b6d136477496)
