### ISSUE TITLE
🐛 Bug Report: Changes to username and password fields on User entity are not persisted

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7911]
### What happened?

Any change on the User entity in the username or password field, are not persisted

### What you expected to happen

the system to reflect the users actions regardless the entity

### How to reproduce

- Create a new service with the order management template
- go into the user entity
- go into the username field, change something and  observe that no pending changes are shown
- go to another field and come back and observe

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mulygottlieb** [comment]
Passed QA:
