### ISSUE TITLE
Model organizer - show success messages

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#7922]
### Feature description

Show the user success messages on the following events:

start redesign- You can start breaking <service name>, and drag entities to other services
fetch - Updates were fetched and merged successfully"
discard - Redesign changes were discarded successfully

**Comment by overbit** [comment]
Test result ✅ 



https://github.com/amplication/amplication/assets/2861984/205d6a98-646b-4f47-92ba-238255b6d6e0
