### ISSUE TITLE
🐛 Bug Report: project redesign flow does not move realations as expected 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#7931]
### What happened?

In some use cases, the relation fields of moved entities are not moved as expected and the flow fails.
- Self relation
- relations between multiple entities that moved to the same service

also, some properties of a relations fields are not copied correctly - description, custom attribute, unique, searchable, required

The current code is based on a new implementation for creating entities and fields. 
There is already an existing implementation in EntityService.createBulkEntitesAndFields which is used by the schema import flow.
We should relay on the existing code instead of creating another implementation for the same problem. 

### What you expected to happen

use the existing code from  EntityService.createBulkEntitesAndFields

### How to reproduce

move multiple entities with relations

**Comment by overbit** [comment]
# Test Result: ✅ 

https://jam.dev/c/85810e42-391d-4841-8f6e-398f7853f538
