### ISSUE TITLE
🐛 Bug Report: I cannot see new services added to the model organizer 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#7933]
### What happened?

When a users adds a new service in the model organizer, sometimes the new services is created and placed outside of the current view, and the the user cannot see that the new service was created

### What you expected to happen

The new service should be visible after creation

### How to reproduce

create a few services in the model organizer

**Comment by mulygottlieb** [comment]
Passed QA:


https://github.com/amplication/amplication/assets/1912933/317d012f-ec37-490e-9a85-4a2e35afef22
