### ISSUE TITLE
BTM- When adding services in the Architecture screen and applying, the new services are not visible in the project overview page

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#7937]
When you use the Architecture screen in Redesign mode, and add new services, after you apply the changes if you return to the project overview page, you will not see the newly added services unless you refresh the page.

Expected: newly created services will be visible (after applying the arch. changes) in the project overview page without needing to refresh the page.

**Comment by overbit** [comment]
# Test result: ✅ 

https://jam.dev/c/a2691754-def3-4fd6-8061-f8f82e5a2082
