### ISSUE TITLE
BTM - New services added via the Architecture screen get a weird description

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#7938]
When you create a new service via the Architecture screen, it gets a weird service description text:

![Image](https://github.com/amplication/amplication/assets/1912933/fd1ecd08-bca8-4004-91ed-51f5c93d5bfc)

Expected: No service description should be added

**Comment by overbit** [comment]
# Test result: ✅ 

![Image](https://github.com/amplication/amplication/assets/2861984/7151dc19-4d24-4cc3-8a45-d92e96de8e61)
