### ISSUE TITLE
Have the correct Redesign tooltip in case the user has the BTM entitlement

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7949]
When the user / account has the BTM entitlement- the user should see the following tooltip for the "Redesign" button-
“Redesign your system architecture by breaking a monolith Service into microservices”

**Comment by mulygottlieb** [comment]
Passed QA:

With the entitlement:

![Image](https://github.com/amplication/amplication/assets/1912933/a467814a-aaf4-428c-8b24-db03bd2a1579)

Without the entitlement:

![Image](https://github.com/amplication/amplication/assets/1912933/f2dd0452-c680-44e7-9564-3abc086d5ed5)
