### ISSUE TITLE
BTM - Breaking relations - the relation field that is "left behind" (in the original service) needs to be renamed to add 'Id' suffix like the side that gets moved to another service

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#7956]
When we break a 1:n or 1:1 relation, in one side of the relation that moves to another service, the field name gets an additional suffix "id" (E.g., "Customer" --> "CustomerId").
However, the relation side that stays in the original service is only getting the field type updated, but not the field name, which also needs the same "Id" suffix added.

**Comment by mulygottlieb** [comment]
@PazYanoverr @morhag90 FYI I opened this ticket per our QA today of the relation breaking fixes

**Comment by PazYanoverr** [comment]
@mulygottlieb @morhag90 - Just to make sure- the ID suffix should be added only for the "n" side in 1:n relation, and for both "1" sides in 1:1 relation, right?

**Comment by mulygottlieb** [comment]
Yes @PazYanoverr.
