### ISSUE TITLE
BTM- Enforce existing commit validations in the confirmation modal

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7959]
Implement the existing commit button (as a component)
Build the code button - add delay until build starts

**Comment by abrl91** [comment]
✅  passed QA


![Image](https://github.com/amplication/amplication/assets/39680385/0dded744-856f-42e3-9393-7eed75c1a602)

**Comment by PazYanoverr** [comment]
@mulygottlieb @abrl91 - Isn't it just the same not-ideal behavior of two dialogs?

**Comment by mulygottlieb** [comment]
@PazYanoverr yes. I think it's not a blocker for the release (definitely not the one we want for today), and I have advised Amit that we should open a separate ticket for that. Your call.

**Comment by PazYanoverr** [comment]
Agreed. Let's open a new ticket (not blocker)

**Comment by mulygottlieb** [comment]
@abrl91  did you already open a new ticket for the double dialog or should I?

**Comment by mulygottlieb** [comment]
@PazYanoverr I opened https://github.com/amplication/amplication/issues/8032 to track this
