### ISSUE TITLE
BTM- Improve the new service dialog

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7962]
Under the "New service" title, add a sentence that the service will not be created before applying the architecture:
"The service will be created and added to the project only after applying the Redesign changes"

![Image](https://github.com/amplication/amplication/assets/149934977/8b28c14c-b376-49ba-93ab-3a36ab5ecad9)

**Comment by abrl91** [comment]
✅ passed QA


![Image](https://github.com/amplication/amplication/assets/39680385/4912a997-21ea-4a25-ba16-52173f0e7def)

**Comment by PazYanoverr** [comment]
@abrl91 @morhag90 @mulygottlieb - The sentence should appear below the "New Service" title and not below the "Type New Service Name" (- see ticket description)

**Comment by mulygottlieb** [comment]
Passed QA take 2:


![Image](https://github.com/amplication/amplication/assets/1912933/b83fc5c1-78a1-43ec-80b7-87e950c567ae)


@PazYanoverr
