### ISSUE TITLE
BTM - Error log dialog missing close button

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7963]
The log dialog should have a "Close" button. Is it possible to have it instead of the 'X' button and in the same place?

![Image](https://github.com/amplication/amplication/assets/149934977/c28aea3e-4a2a-4033-9ce8-86469694b15e)

**Comment by yuval-hazaz** [comment]
@PazYanoverr  do we still need this ticket?

**Comment by PazYanoverr** [comment]
@yuval-hazaz - No, I will close it
