### ISSUE TITLE
BTM - Entities are too close/overlapping to the separator line under the service name/description

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7964]
Hint: Remove crosshair / drag icon

Example:
![Image](https://github.com/amplication/amplication/assets/149934977/f596ec1c-9fbb-480a-845c-88feab4ef9d7)

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/be47cb46-aff9-4e50-8482-95293fc1010d)
