### ISSUE TITLE
BTM - Improve the search option

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7966]
1. The search in the Arch tab is case sensitive. It should be insensitive. 
2. The search should apply also to the entitie names, so one can search for a name, choose the best option, and the entity should be highlighted somehow in the Overview mode, and mark as chosen in the Redesign mode.

**Comment by lalitkumawat1m** [comment]
Can I take this issue?

**Comment by abrl91** [comment]
✅  Passed QA



https://github.com/amplication/amplication/assets/39680385/c9e79f90-62b3-4a4c-81da-fde4fd17ca28
