### ISSUE TITLE
BTM - Entity selection context menu - Select all related entities (first relatives)

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7967]
**NOTE: We need to plan and estimate this before starting, since the decision on implementing or not will depend on the estimation**

Add this part of the design / spec.
- [ ] Add the context menu on entities (the "...")
- [ ] In the context menu add a single option "Select all related entities"
- [ ] If clicked, all *first order* related entities will be in selected mode
- [ ] The user can (as usual) add/remove selection with command key and click

**Comment by overbit** [comment]
@PazYanoverr what is the expectation for Win users? 
`cmd` + `left mouse click` is only available for Mac. 
Is the `control` + `click` the correct mapping?

📝 Suggestion:  It would make sense to have a legend with these common user interaction commands

**Comment by PazYanoverr** [comment]
@overbit - For Win users- Ctrl + Click

**Comment by overbit** [comment]
Test result: ✅ 
https://jam.dev/c/f73d3b88-ea34-4ad1-a717-d92bea9cdb80
