### ISSUE TITLE
BTM - better Handle new services creation in the Arch tab

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7968]
See https://github.com/amplication/amplication/issues/7864 for more context.

1. Enable the two APIs (REST, GQL), and admin UI for any new service created in the Arch tab (Redesign mode)
2. Base folders - make sure the new services do not override prev services folders.
     i. In case the base directory is empty (in the monolith service)- leave it empty 
     ii. Check for the last '/' in the base directory, and replace the string *after* with < service-name > and < service-name >-admin
     iii. In case no '/' - replace all string with < service-name > and < service-name >-admin

**Comment by abrl91** [comment]
[mono-repe]: Test 2 was created during the architecture redesign.

![Image](https://github.com/amplication/amplication/assets/39680385/2af66a13-449e-48d5-b0dd-29d834f1498f)

[poly-repo]: Test 3 poly was created during the architecture redesign.

![Image](https://github.com/amplication/amplication/assets/39680385/0a13d890-c79b-44ad-b909-44ea1b068d5b)
