### ISSUE TITLE
BTM- Add notification (in app) for the new feature release (beta)

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7969]
1. Novu trigger id- btm-feature-alert (in-app only)
2. All the users that logged in during the last 6 months should get it (all plans) when the feature is released.
![Image](https://github.com/amplication/amplication/assets/149934977/4a282e46-cfcf-4ece-b3ba-1f969fb42cf5)

**Comment by morhag90** [comment]
Passed QA:
<img width="474" alt="image" src="https://github.com/amplication/amplication/assets/97830649/2feed679-0099-4ebb-89b6-736af913476b">
