### ISSUE TITLE
BTM- Redesign options when there is only one service in the project

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7972]
When the project contains only one service, no need to display the services option after clicking the Redesign button, and before moving to the Redesign mode. We can immediately take the user to the Redesign mode for the single Service

**Comment by PazYanoverr** [comment]
@abrl91 - Note that the same should apply for Break the monolith / AI helper button when applicable.

**Comment by abrl91** [comment]
✅  Passed QA


https://github.com/amplication/amplication/assets/39680385/756d0e55-0df2-404e-bf9a-e1f6dbb54949
