### ISSUE TITLE
BTM (AI)- Handle service name collisions from suggested services VS existing services

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7974]
We should handle name collisions that may occur as part of the BTM flow-

Service names- the LLM process of BTM may cause a name collision (between services)-
In case the name of a new service suggested by OpenAI already exists, the new service should be called [name]-< random suffix >
(The BTM spec was updated accordingly)

**Comment by overbit** [comment]
Test result ✅ 



https://github.com/amplication/amplication/assets/2861984/2687df42-a463-482e-983b-6068b51e07ff
