### ISSUE TITLE
DSG: Import from Prisma namespace on EntityService may conflict with DTOs imports

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8004]
### Feature description

The imports of the Prisma entities and DTOs in the service base file conflict with DTO imports.

The entities are imported directly from the Prisma package - like this:

<img width="718" alt="image" src="https://github.com/amplication/amplication/assets/43705455/f603383d-aa24-4ff8-8ab3-9280bd725ec5">

As part of the efforts for Custom Actions phase 2, we allow the user to create custom actions in the service, which may need to import types from the entities DTOs and cause a conflict 

for example :
<img width="718" alt="image" src="https://github.com/amplication/amplication/assets/43705455/fa2b34d6-8154-413b-a221-bc3b67549c45">

To avoid the conflict, we want to import the entities from Prisma with aliasing in `PrismeEntity` format - like this

<img width="718" alt="image" src="https://github.com/amplication/amplication/assets/43705455/65af6949-6a69-4aa1-bd9b-4d59fb942eb4">

**Comment by overbit** [comment]
@yuval-hazaz  would it make more sense to rename the dto with a Dto suffix? 

In an MVC pattern it common naming the business model in a simple form as Customer, Order, etc and view models or dtos with CustomerDto, CustomerView and not the other way around

**Comment by yuval-hazaz** [comment]
For the purpose of current issue - it is already resolved. 
If you think it makes more sense to change the current naming format in general (and not just because of this issue) I suggest that we think about it after considering different best practices, the impact, and the value of such change

**Comment by overbit** [comment]
@yuval-hazaz is there any easy way to test this issue?
Do you have an input.json I can use?

**Comment by overbit** [comment]
Test result ✅ 

Automated tests.
https://github.com/amplication/amplication/pull/8006/files#diff-8e56062d3bf78d23d02b260a21d149cd721a3a1e11b453eb0cac779529ec9554
