### ISSUE TITLE
DSG: importContainedIdentifiers should not add imports to identifiers that appear in the import declaration and qualified Names

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8005]
### What happened?

The function importContainedIdentifiers traverse the AST tree and automatically adds missing imports for IDs that are found in the page:
1. The function adds new import declarations to IDs that are found in other declarations
2. The functions add improts to qualified Names, although it is not expected to do it.

For example, in the below code 
1. The ID `CustomerFindManyArgs` should not be added to the import declaration because it is part of the qualified name `Prisma.CustomerFindUniqueArgs`
2. the ID Customer should not be added because it appears in the import declaration 
<img width="596" alt="image" src="https://github.com/amplication/amplication/assets/43705455/f618919f-8df9-48d7-b030-f0c9136c123a">

### What you expected to happen

Only IDs fron the body of the code and only IDs that are not part of a qualified names should be imported

### How to reproduce

Add import to the tempalte

**Comment by overbit** [comment]
Test result ✅ 


![Image](https://github.com/amplication/amplication/assets/2861984/c5cd19c7-d304-4f38-9f28-24c4bcaab371)
