### ISSUE TITLE
Update the text of the "Commit changes & build" button

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8013]
In order to make the "Commit changes & build" button more explanatory, and pushes to action, we want to update the text of the button to "Generate the code"

**Comment by mulygottlieb** [comment]
@PazYanoverr when there are no pending changes, the button currently says "Rebuild"
<img width="275" alt="image" src="https://github.com/amplication/amplication/assets/1912933/b241bf4c-de17-401f-a5da-2c92da31dfd7">

What would you like the text to be in that case (no pending changes)?

**Comment by PazYanoverr** [comment]
@mulygottlieb - In this case the same text should appear- "Generate the code"

**Comment by morhag90** [comment]
Passed QA: 
<img width="272" alt="image" src="https://github.com/amplication/amplication/assets/97830649/690024b6-c8a5-446d-a650-c3398f13af0a">

**Comment by sagarkori143** [comment]
is this issue still open to work?
@PazYanoverr

**Comment by PazYanoverr** [comment]
@sagarkori143 - Sorry, it was already done, and about to be deployed. You are welcome to pick any other ticket which is open to our great community :)
