### ISSUE TITLE
🐛 Bug Report: Json plugin should not log sensitive data by default

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8016]
### What happened?

Currently the plugin Json logger logs a lot of data such as req and res. This objects may contain sensitive information like auth tokens or PII.

### What you expected to happen

The plugin should ignore logging standard sensitive data like header.authorization and allow users to easily configure the ignore fields

### How to reproduce

install the plugin and make some requests. Observe the result

**Comment by Shurtu-gal** [comment]
@overbit could you elaborate on which logs we want and which we don't?

For example:- 

![image](https://github.com/amplication/amplication/assets/100484401/4d981e59-4afe-4d21-9a63-ecb54014d04f)
This is a request log and contains the fields which you mentioned. Should we not log the specific fields as set by the user or something else?

**Comment by overbit** [comment]
I'd default to ignore all the request and response headers and body as they are usually the place where PII and authorisation data are passed

**Comment by overbit** [comment]
Test result ✅
