### ISSUE TITLE
BTM (AI) - Verify the entitlement enforcement for the AI buttons in all places

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8029]
All the AI buttons should use the same BTM add-on (entitlement)-
* In the project overview
* In the service overview
* In the Architecture tab (Overview and Redesign)
* In the Upload schema flow

The behavior and UX should follow the design (https://www.figma.com/file/SSOYJbY3vYMjwcNUABSjwd/UX%2FUI---Breaking-the-monolith-(phase-1)?type=design&node-id=757%3A1353&mode=design&t=mpDTnX55j52QuDxC-1) and spec- for the various plans (https://www.notion.so/amplication/Breaking-the-Monolith-Phase-1-ee82ceea689f4b15b3a422077a91d014?pvs=4).

**Comment by overbit** [comment]
Test result ✅ 


https://github.com/amplication/amplication/assets/2861984/54d2dbbf-13de-4864-b620-4334c7f8a36c
