### ISSUE TITLE
🐛 Bug Report: generated code returns `ENOENT: no such file or directory, stat '/swagger/index.html'`

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8044]
### What happened?

When running a freshly generated server application, the following error get logged on every openapi specification load.
```sh
ERROR: ENOENT: no such file or directory, stat '/......./swagger/index.html
```

### What you expected to happen

No error to be printed

### How to reproduce

Generate a new server, build and start it.
observe the results

**Comment by shravan20** [comment]
@overbit: Can i pick this up?

**Comment by abrl91** [comment]
Passed QA ✅ 

`npm run run build` finished successfully

![Image](https://github.com/amplication/amplication/assets/39680385/32e53eaf-84e0-4aca-ab1e-790680a0e704)
