### ISSUE TITLE
🐛 Bug Report: Open Telemetry plugin creates bad configuration for the OpenTelemetry container causing it not to start

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8047]
After generating code with the OpenTelemetry plugin, the resulting docker-compose.dev contains an invalid configuration, causing the OTEL container to stop immediately after starting:

![Image](https://github.com/amplication/amplication/assets/1912933/1ccde354-d88e-408e-9617-f2172032764c)

**Comment by overbit** [comment]
Test result ❌ 

![Image](https://github.com/amplication/amplication/assets/2861984/fe195528-dba0-4aac-aaa6-299ea377d420)
