### ISSUE TITLE
Docs: Typo in link to Github

### ISSUE THREAD

**Issue by prayashm** [amplication/amplication#806]
**Describe the bug**
There's a typo in the gitbook Docs for the github link.

**To Reproduce**
1. Go to https://docs.amplication.com
2. Click on 'GitHub' link on top right corner
3. See error 404 as it navigates to `https://github.com/amplicaiton/amplication` (notice typo in org name)

**Expected behavior**
It should navigate to `https://github.com/amplication/amplication` instead.

**Screenshots**
<img width="745" alt="image" src="https://user-images.githubusercontent.com/424487/99694416-6ca17d00-2ab2-11eb-8951-3a8ba9abfaab.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 83.0 (64-bit)

**Comment by yuval-hazaz** [comment]
Thank you very much @prayashm for reporting this issue

**Comment by yuval-hazaz** [comment]
@prayashm you are invited to join our discord channel 
https://discord.gg/b8MrjU6
