### ISSUE TITLE
BTM (Preview) - Text of the "select the monolith you want to break" - make it more informative, and exciting

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8074]
The new suggested text:

Title: Break the Monolith with Amplication: A Journey of Transformation! 🚀✨

Dive into a transformative journey by selecting an open-source monolith, defined by its database schema. With Amplication, this is where innovation begins. We import the monolith’s schema and meticulously dissect it, preparing for a groundbreaking transformation.

Witness the magic as Amplication proposes a new, streamlined architecture of microservices, designed for scalability and efficiency. You're not just observing; you’re part of the process, reviewing the suggested microservices architecture, understanding its dynamics, and visualizing the future.

Embrace this collaborative adventure with Amplication, where breaking the monolith opens a world of possibilities and showcases the true potential of technological innovation.

----

Issue updated:
![image](https://github.com/amplication/amplication/assets/39680385/a0b26803-46a3-44be-af49-54dd8d22d264)

**Comment by overbit** [comment]
Test result: ❌ 

![Image](https://github.com/amplication/amplication/assets/2861984/aa070cff-609b-489d-9c16-7a4c5c9c6c4a)

@PazYanoverr @abrl91  where is this text supposed to be?

**Comment by PazYanoverr** [comment]
@overbit - The ticket talks about the text that should be displayed when the user chooses the monolith to break.
The text was updated during dev, and the ticket was not updated accordingly.

**Comment by overbit** [comment]
> Test result: ❌
> 
> ![Image](https://private-user-images.githubusercontent.com/2861984/307289349-aa070cff-609b-489d-9c16-7a4c5c9c6c4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Mzg0NjUsIm5iZiI6MTcwODkzODE2NSwicGF0aCI6Ii8yODYxOTg0LzMwNzI4OTM0OS1hYTA3MGNmZi02MDliLTQ4OWQtOWMxNi03YTRjNWM5YzZjNGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMDkwMjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRmN2Q0MWIyYWVmOThjZDc1ZWY3YjYxNmY2YzI5Zjc1YmE4MDkyOWFiMmVlYzU4ZTdjN2YyMGI4NDc5MmNlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Fet6U4hpUHtt_F8WeBqeoyCPnAXqnLexlSB4TCUPu8M)
> 
> [@PazYanoverr](https://github.com/PazYanoverr) [@abrl91](https://github.com/abrl91) where is this text supposed to be?

Test result ✅ 

Card requirements were not updated
![Image](https://private-user-images.githubusercontent.com/2861984/307289349-aa070cff-609b-489d-9c16-7a4c5c9c6c4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Mzg0NjUsIm5iZiI6MTcwODkzODE2NSwicGF0aCI6Ii8yODYxOTg0LzMwNzI4OTM0OS1hYTA3MGNmZi02MDliLTQ4OWQtOWMxNi03YTRjNWM5YzZjNGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMDkwMjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRmN2Q0MWIyYWVmOThjZDc1ZWY3YjYxNmY2YzI5Zjc1YmE4MDkyOWFiMmVlYzU4ZTdjN2YyMGI4NDc5MmNlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Fet6U4hpUHtt_F8WeBqeoyCPnAXqnLexlSB4TCUPu8M)
