### ISSUE TITLE
BTM (Preview) - After signup - add an explanation message

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8080]
After the preview user signups to Amplication and login (after reset password flow), the following message should appear **in a modal** on top of the first screen he sees = project overview page:

**Title**: Welcome Aboard! 🚀 

Congrats on joining us! With Amplication, you've unlocked streamlined backend code generation and boundless possibilities.

Now, let's dive into your application journey. Explore our intuitive interface, craft solutions effortlessly, and enjoy a free 14-day trial with unlocked Enterprise features.

Embrace the adventure ahead, and let's create magic together! ✨

**Comment by PazYanoverr** [comment]
@mulygottlieb - Updated the description. Please assign it to the team.

**Comment by abrl91** [comment]
@PazYanoverr 
The first screen the user sees is the schema list page

**Comment by PazYanoverr** [comment]
@abrl91 - NSIU which page is it. The Project overview?

**Comment by abrl91** [comment]
✅ passed QA


![Image](https://github.com/amplication/amplication/assets/39680385/8047365d-e4cf-49b2-add0-5f6672b3e068)
