### ISSUE TITLE
BTM (Preview) - Omit the Close button in the preview flow; The user should not be able to close it ("Experience the Microservices....")

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#8086]
Preview user flow:
- on the schema list page, after "Break" a monolith: remove the close button from the modal
- on the page that shows the imported monolithic service: remove the close button from the modal

**Comment by overbit** [comment]
Test result ✅ 

https://github.com/amplication/amplication/assets/2861984/616fa029-1a67-4385-a66b-bceccb71db07
