### ISSUE TITLE
Server: ERD feature

### ISSUE THREAD

**Issue by nvwebm** [amplication/amplication#809]
**Is your feature request related to a problem? Please describe.**
When I develop my apps it really useful to see the DB diagram

**Describe the solution you'd like**
The solution I'd like to see it's the option to see live diagram of my DB scheme

**Describe alternatives you've considered**
I haven't

**Additional context**
https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model
![image](https://user-images.githubusercontent.com/12819552/99802045-a79dc200-2b3f-11eb-9e18-573ca7edbe1c.png)

**Comment by rienheuver** [comment]
This would be a great addition in my opinion too! Even more so if you can create new entities and edit entities through the diagram. There's already a nice library that implements this for Prisma!
