### ISSUE TITLE
🐛 Bug Report: `openai plugin` generates provider code outside `src` folder

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8101]
### What happened?

openai plugin is currently generating provider code outside `src` folder instead of inside the `src/provider` folder

### What you expected to happen

.

### How to reproduce

- create a service
- install the openai plugin
- observe the code

**Comment by KrishavRajSingh** [comment]
I would like to work on this

**Comment by abrl91** [comment]
Passed QA ✅ 


![Image](https://github.com/amplication/amplication/assets/39680385/e125cd7f-d4fb-4a23-9185-289883b120f8)
