### ISSUE TITLE
BTM (AI + Preview) - Left menu buttons- are not aligned

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8103]
In the architecture page, menu icons on the left are not aligned. 

i.e. 

<img width="935" alt="image" src="https://github.com/amplication/amplication/assets/2861984/a5580c79-fdad-415e-9fb2-cf63d31281ae">

**Comment by ShreeMundade** [comment]
![image](https://github.com/amplication/amplication/assets/60389699/af858697-c240-46eb-893b-f9d008aeaf7a)

![image](https://github.com/amplication/amplication/assets/60389699/3f844ae0-25db-433b-9b42-dc592948ae4a)


Making it center align will work.

**Comment by mulygottlieb** [comment]
QA note - this was merged as a HF to master, needs to be QAed on Staging

**Comment by overbit** [comment]
Test result: 

![Image](https://github.com/amplication/amplication/assets/2861984/e731baca-7b41-4bf7-84e1-844fb1b1f8e5)
