### ISSUE TITLE
BTM (Preview) - Update the preview user's profile

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8105]
The User Profile of the preview user, should be updated from - 

![Image](https://github.com/amplication/amplication/assets/149934977/e763f9e1-cca6-4fc2-8a43-f463319a89dc)

To-
First Name- The (real) email address
Last Name- empty 
(- this is identical to the user profile we have for our "regular" users)

**Comment by PazYanoverr** [comment]
@mulygottlieb @abrl91 - FYI. Can be handled after the release

**Comment by abrl91** [comment]
✅ Passed QA


![Image](https://github.com/amplication/amplication/assets/39680385/6a32ecad-1620-4d5c-ad1a-e9b7c5b9851c)

**Comment by overbit** [comment]
Test result ✅ 



![Image](https://github.com/amplication/amplication/assets/2861984/58f56480-7315-4afe-a370-e460ee465959)
