### ISSUE TITLE
BTM (AI) - Improve the "cards" screen look

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8106]
The updated "cards" screen looks great -  

![Image](https://github.com/amplication/amplication/assets/149934977/71e5142b-0f1e-44c6-8750-eadf0b1a50ba)

However, the "All suggestions can be edited and customized..." takes too much focus. Let's try to improve it by making its width identical to the cards' width.

Please share the result- so we can decide whether it's good enough or additional changes should take place.

Updated requirement 28/2/2024:

- Move the highlighted text to be part of the gray text above it "Our AI.." as a new paragraph
- Below the gray text just place the "Let's go" button (centered)
- No background needed

**Comment by PazYanoverr** [comment]
@mulygottlieb @morhag90 - FYI

**Comment by mulygottlieb** [comment]
- Move the highlighted text to be part of the gray text above it "Our AI.." as a new paragraph
- Below the gray text just place the "Let's go" button (centered)
- No background needed

**Comment by overbit** [comment]
Test result ✅ 

![Image](https://github.com/amplication/amplication/assets/2861984/3fae4f25-8819-4a4f-a957-b762695b8bd9)
