### ISSUE TITLE
🐛 Bug Report:  BTM (Preview) - break-the-monolith-preview page is not showing fields on request 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8111]
### What happened?

<img width="1713" alt="image" src="https://github.com/amplication/amplication/assets/2861984/c9ac4886-fdef-41ae-ae34-9e8725299a6e">

### What you expected to happen

Toggle view fields should display the entities fields

### How to reproduce

create a preview account and use the toggle

**Comment by PazYanoverr** [comment]
@mulygottlieb - Added to the TODO list. Let's handle

**Comment by mulygottlieb** [comment]
Implementation note: this is a client issue - refreshing the page solves this. In some cases, some/all entities arrive at this screen with no fields. After refresh all entities' fields are shown

**Comment by morhag90** [comment]
Passed QA:

<img width="890" alt="image" src="https://github.com/amplication/amplication/assets/97830649/e726f27a-ab34-439f-8ff2-be15a1db2a3c">
