### ISSUE TITLE
🐛 Bug Report: subscription plans error when working locally with billing disabled

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8113]
### What happened?

![image](https://github.com/amplication/amplication/assets/2861984/483947c5-541a-4ee6-baeb-fc20c6b08898)

### What you expected to happen

Login working as usual

### How to reproduce

Start client and server with stock .env configuration
Try to create an account to sign in.

### Amplication version

v1.13.8

**Comment by shreyash010** [comment]
Test result ✅
