### ISSUE TITLE
As a User - I want to have information about the amount of changes (Lines of code - LOC) I get from Amplication

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8146]
Part of 
https://www.notion.so/amplication/Workspace-Dashboard-5285374805704dfea58395db4a2156d6?pvs=4

We want the users to have access to analytical information about the number of changes they get from Amplication.
We already have things like number of build, frequency of build, changed entities, APIs, etc - and now we want to add information of LOC that were added/removed/modified.
This task is comprised of the following parts:
- [x] Spike task: check how we can use the local git client in git-sync-manager to find out during PR creation the real number of changes compared to the target branch (the number of "highlighted" lines that will appear in the PR view in Git later)
- [x] Add the above number to the response from git-sync-manager all the way back to the server
- [x] Discuss DB schema to store this data is the server and implement it
- [ ] Get UX from Product team and implement the UI/UX side

**Comment by mulygottlieb** [comment]
@abrl91 let's start with the first one on the list - a spike task for git client. And move on from there.

**Comment by PazYanoverr** [comment]
@mulygottlieb @abrl91 - As discussed- note that deleted lines should be counted just as new or updated lines.

**Comment by abrl91** [comment]
can be QAed with #8167

**Comment by overbit** [comment]
Test result ✅
