### ISSUE TITLE
🐛 Bug Report: `opentelemetry-nestjs` not supporting graphql and other instrumentations

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8154]
### What happened?

Currently the [opentelemetry-nestjs](https://github.com/amplication/opentelemetry-nestjs) is implemented in a way that will not allow auto instrumentation libraries to successfully work due to the order of imports i.e. `graphql` library could be imported after the instrumentation lib making this not able to work properly. 

### What you expected to happen

Library to fully support all auto instrumentation libraries

### How to reproduce

Use the lib and try to instrument, i.e. graphql. 
Check the reported traces

**Comment by overbit** [comment]
discovered as part of https://github.com/amplication/amplication/issues/8147

**Comment by overbit** [comment]
Test result ✅ 



![Image](https://github.com/amplication/amplication/assets/2861984/f4d4f347-fc92-4c4d-bd6d-1b5831fd62b2)

**Comment by ssilve1989** [comment]
I think this is still relevant in v5? If you enable the @opentelemetry diagnostic logger and try to use other instrumentations, like the following 
```typescript 
  instrumentations: [
    new PgInstrumentation({
      enhancedDatabaseReporting: true,
      addSqlCommenterCommentToQueries: true,
    }),
    new GrpcInstrumentation(),
    new RedisInstrumentation(),
    new PinoInstrumentation(),
  ],
```
the diagnostic logger will yield 
```
@opentelemetry/instrumentation-pg Module pg has been loaded before @opentelemetry/instrumentation-pg so it might not work, please initialize it before requiring pg
@opentelemetry/instrumentation-pg Module pg-pool has been loaded before @opentelemetry/instrumentation-pg so it might not work, please initialize it before requiring pg-pool
@opentelemetry/instrumentation-grpc Module @grpc/grpc-js has been loaded before @opentelemetry/instrumentation-grpc so it might not work, please initialize it before requiring @grpc/grpc-js
@opentelemetry/instrumentation-redis-4 Module @redis/client has been loaded before @opentelemetry/instrumentation-redis-4 so it might not work, please initialize it before requiring @redis/client
@opentelemetry/instrumentation-pino Module pino has been loaded before @opentelemetry/instrumentation-pino so it might not work, please initialize it before requiring pino
```

I saw [this](https://github.com/open-telemetry/opentelemetry-js/issues/4116) that indicates the gRPC issue might be related to some other exporter, but if I attempt to register instrumentations the "old" way via `--require` of a CJS module, I don't get that kind of warning about the non-grpc instrumentations in this example.
