### ISSUE TITLE
[Epic] As a User - I want to have an Analytics Dashboard to see the value I get from Amplication over time

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8167]
Notion Spec:
https://www.notion.so/amplication/Analytics-Dashboard-5285374805704dfea58395db4a2156d6?pvs=4

**Technical Requirements:**
- A new service - Analytics Service - to store the relevant analytical information, aggregate it as needed, and expose it to the client with GQL
- The new service will be a dogfooding service created with Amplication. We can start with a regular Postgres DB or consider if there is any benefit to MongoDB for this use case
- The new service will listen to various Kafka topics that will allow it to update its internal DB with analytics for required metrics
- The actual metrics should be easily extendible (so in the future we will be able to hold new metrics easily)
- Metrics should be saved with timestamp (e.g. `createdAt`), and be linked to a `resourceId` (and perhaps also `projectId` and `workspaceId`) so we can collect all metric of a certain "metric type" for a given resource/project/workspace over a specified time range
- Metrics (where applicable) should be stored as numbers so we can perform numerical operations like sum, max, avg, median, etc.
- Required metrics to hold:
   - Number of Builds (builds over time)
   - Number of LOC per build
   - Number of entities changed/created
   - Number of APIs (ModuleAction) changed/created per build (only "enabled" ones? all? count enabling/disabling itself as something?)
   - Number of Plugins installed / updated
  

**Concerns that need to be discussed:**
- Initial data migration - do we create all the historical data or this dashboard will only contain data starting from the date it was introduced (similar question will arise in the future for new metrics we will add)
- If we calculate LOC changed in a PR (Amplication Build), and the user does **not** merge the PR, and then creates another build - we may count the same LOC twice - do we care? can this be considered a "known limitation" or even a "by design feature" (if I add and remove the same thing and build in between - perhaps I am actually touching more LOC)
- How do we enforce permissions for this data in the new service? Is the new service accessed directly from the client, or relayed via the server?  
- Do we count/represent changes that were done in the platform **without** building or just save data for each new build? E.g. I may be working a lot with the system and changing things but not pushing new PRs

**Comment by overbit** [comment]
Test result: ❔ 

- Unnecessary newline
<img width="720" alt="image" src="https://github.com/amplication/amplication/assets/2861984/3e9925e6-3e33-4378-95bb-a1c6cccdb708">
-
