### ISSUE TITLE
Mobile onboarding preview

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8172]
### Feature description

https://www.figma.com/file/kGGuDR4q2XmzUBbKLqpGJ7/Preview-User-Onboarding?type=design&node-id=1732%3A1483&mode=design&t=0sVpV4lGlimUPdeO-1

### Use case

allow users to run an onboarding flow to generate a service and get a link to the generated code in a demo repo

**Comment by abrl91** [comment]
for Auth0


![Image](https://github.com/amplication/amplication/assets/39680385/12e062e6-bb53-4abb-b6c6-04586bc818dd)

**Comment by mulygottlieb** [comment]
QA:
- General sanity tested on many flows ✅
- Supertokens ✅

**Comment by mulygottlieb** [comment]
QA:
- Supertokens fixed (allow only REST or only GQL)
