### ISSUE TITLE
🐛 Bug Report: Generated code fails to run after release of TypeScript 5.4

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#8180]
### What happened?

Getting the following errors:
![image](https://github.com/amplication/amplication/assets/39680385/022a9da2-9bbc-4196-ba99-ee3ca23236a4)

### What you expected to happen

To work 😄 

### How to reproduce

`cd {service-name} && npm i && npm run build`

**Comment by overbit** [comment]
Test result ✅

**Comment by abrl91** [comment]
Passed QA ✅ 



![Image](https://github.com/amplication/amplication/assets/39680385/8fdea4b1-e7e8-4e6e-b92b-016a1ad4a761)



`npm run run build` finished successfully.

![Image](https://github.com/amplication/amplication/assets/39680385/32e53eaf-84e0-4aca-ab1e-790680a0e704)
