### ISSUE TITLE
As Product - I want to remove the beta indication from the Architecture tab

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8187]
Currently, in the Architecture tab, we have a beta indicator tab and we wish to remove it

![Image](https://github.com/amplication/amplication/assets/1912933/b098055e-208c-4185-b120-cb88641db2e0)

**Comment by overbit** [comment]
Test result ✅ 



![Image](https://github.com/amplication/amplication/assets/2861984/e04d9cb3-2aaf-4f68-bf7d-23cd98553817)
