### ISSUE TITLE
Plugins CI is showing all plugins as affected 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8192]
Currently, when releasing a plugin, its package.json is updated with the new version.
This causes the root level package-lock to be updated too causing all the projects in the Nx workspace to be affected.

**Comment by overbit** [comment]
Related to https://github.com/nrwl/nx/issues/22259

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/36b90b07-972d-4d96-a7b1-52ff669f5802)
