### ISSUE TITLE
🐛 Bug Report: Default actions can be disabled when using the Custom Action form

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8222]
### What happened?

Even when the user cannot disable actions from the list of actions, they can still go into the action form and disable it or update some of its fields.
![image](https://github.com/amplication/amplication/assets/43705455/c60f2fef-6470-43c9-9855-a61e33fc01dc)

### What you expected to happen

The user should not be able to disable or edit default actions without the module license 

### How to reproduce

see latest version on next

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/2c0714d7-9dfe-47a3-add1-f364e7cc713f)
