### ISSUE TITLE
As Product - I want to implement some UI feedback for the Usage Analytics screen

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8254]
1. The titles of the columns of the bar chart should change from:

![Image](https://github.com/amplication/amplication/assets/1912933/dd88c2a7-54c3-476a-ad0d-fd5d9b3bd612)

To:
Entity Changes
Builds
Plugin Updates
API Changes

2. In small screens, this tooltip has a space that needs to be removed (unify the lines, remove the unnecessary line break)

![Image](https://github.com/amplication/amplication/assets/1912933/1bf6288e-83b8-4390-9f9b-50ac0c99a00b)

**Comment by abrl91** [comment]
Passed QA ✅ 

<img width="934" alt="image" src="https://github.com/amplication/amplication/assets/39680385/a2ec8077-915f-4dd4-a7c5-c084593c225d">

![image](https://github.com/amplication/amplication/assets/39680385/167b30ca-b238-4f13-91db-7192a1b50139)
