### ISSUE TITLE
Custom Actions & Types- Add notification (in app) for the feature release

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8272]
1. Novu trigger id- custom-actions-and-types-feature-alert (in-app only)
2. All the users that logged in during the last 12 months should get it (all plans) when the feature is released.

NOTE: Please show me the result (- how the notification looks in the app) before releasing!

```
import { Novu } from '@novu/node'; 

const novu = new Novu('<API_KEY>');

novu.trigger('custom-actions-and-types-feature-alert', {
    to: {
      subscriberId: '<REPLACE_WITH_DATA>'
    },
    payload: {
      payload: {
        envBaseUrl: '<REPLACE_WITH_DATA>',
        workspaceId: '<REPLACE_WITH_DATA>',
        projectId: '<REPLACE_WITH_DATA>',
        serviceId: '<REPLACE_WITH_DATA>'
      }
    }
  });
```

**Comment by mulygottlieb** [comment]
Notification tested with Paz on Staging.
Now I've sent the notification on production to all users active in the last year (365 days).

**Comment by PazYanoverr** [comment]
Passed QA -
<img width="395" alt="image" src="https://github.com/amplication/amplication/assets/149934977/b4d2743b-1a12-4606-8263-253ac72f27da">
