### ISSUE TITLE
.NET: Update the pricing page (x2) with the .NET code-generation

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8291]
![Image](https://github.com/amplication/amplication/assets/149934977/c071e1b7-966e-4154-a1b0-db8c373653d5)

==== This issue is pending design (in progress) ====
-----------------------------------------------------

We have two pricing pages- one in the website, and one in the product. Both should be updated to include:
1. Below the "$0", and the "Contact us", an icon of node.js, and icons of node.js and .NET should be displayed (respectively)
2. Below the "Unlimited code push to Git" in the Free plan description, a new option of "Code generation in node.js only" should be displayed.
3. Above the "Unlimited code generation builds" (i.e. the first item in the list) in the Free plan description, a new item of "Code generation in node.js only" should be displayed.
4. Above the "Unlimited projects" (i.e. the first item in the list) in the Enterprise plan description, a new item of "Code generation in node.js and .NET" should be displayed.
5. The .NET code-generation should have a dedicated entitlement

**Comment by mulygottlieb** [comment]
@yuval-hazaz I assigned it to you since it will be the same change in the website and the product and I assume you will handle that.

**Comment by PazYanoverr** [comment]
@yuval-hazaz @mulygottlieb - We can close this ticket, right?

**Comment by mulygottlieb** [comment]
@PazYanoverr yes. The website is updated, and in the product you no longer see this (and if you will, that is also updated already).

**Comment by mulygottlieb** [comment]
Passed QA:
![image](https://github.com/amplication/amplication/assets/1912933/ff2fcd81-e8f6-437b-b6fa-80bb2f345753)
