### ISSUE TITLE
.NET- Update the login/signup page

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8292]
The login page should be updated to omit any "node.js" reference-

The text (left side of the login page) should be updated to:
"Instantly generate quality backend services
Just code what matters.
Your generated apps are production ready. Every app generated by the Amplication platform contains production-ready, open-source components and packages. We include only those that are popular, documented, secured and supported. Read more about our stack [here](https://docs.amplication.com/getting-started).

amplication is an open-source project and you can send us [feature requests](https://github.com/amplication/amplication/issues/new/choose), [bug reports](https://github.com/amplication/amplication/issues/new/choose), and contribute through our [GitHub repository](https://github.com/amplication/amplication)."

![Image](https://github.com/amplication/amplication/assets/149934977/f1f4a40b-db63-47f9-b033-ce71f1005b4c)

**Comment by overbit** [comment]
Test result ✅  

<img width="1383" alt="image" src="https://github.com/amplication/amplication/assets/2861984/a7daf3bc-6cd2-466c-951e-5c57ae50d5ff">
