### ISSUE TITLE
Jovu: Update / add documentation pages to Jovu knowledge

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8302]
In order to improve Jovu's answers we need to update the list of files attached to Jovu.
A [file](https://github.com/amplication/amplication/files/14950354/combined_markdown.md) which contains all the merged docs is attached. It can be viewed and tested also in https://platform.openai.com/assistants/asst_VozIV5TTZ6861aEeAMnj4fJ4 ("Jovu- Merged Files" assistant)

Note:
1. The file limit is set by OpenAI to 20.
2. More info can be found at https://www.notion.so/amplication/Jovu-Amplication-Ai-Assistant-ac71280e3f2749b5a1a9b49185abb847?pvs=4

**Comment by mulygottlieb** [comment]
Passed QA ✅
