### ISSUE TITLE
Jovu: Update the available "closed" questions for the initial discussion with Jovu

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8305]
When starting a conversation with Jovu, there are a few "closed" questions that are displayed to the user. The goal of these questions is to allow quick engagement of the users (without the need to type a question) while pushing them to the areas that we identify as necessary and demonstrating Jovu's capabilities to them.

The closed questions should focus on entities, APIs, plugins, and Amplication benefits.
The following are the suggested questions:
1. "Does Amplication auto-generate APIs?"
2. "I want to create a new project with a couple of services. Can you help me?"
3. "Can you recommend the plugins I should install for my Service for an event-driven architecture?"
4. "What are the benefits that Amplication can provide to my backend services?"

Important:
The "closed" questions should appear only at the beginning of the conversation, and then- it should disappear. Like the ChatGPT experience in which the "closed" questions are displayed at the beginning- 

![Image](https://github.com/amplication/amplication/assets/149934977/fd56beb5-0226-4f45-9266-c1ac057a142c)

And then, it "disappears"-

![Image](https://github.com/amplication/amplication/assets/149934977/ec0f1bc6-0b5f-4077-bd9e-837b060dc815)

**Comment by yuval-hazaz** [comment]
@PazYanoverr I am missing a question or a message about creation of something. all 4 questions are around knowledge and Jovu is not creating anything 

I am using this for now instead of the 4th one, but let's talk about it
"I want to create a new project with a couple of services. Can you help me?

**Comment by yuval-hazaz** [comment]
also, the answer for the suggested quesions are not perfect and we shoudl consider 
1. teaching Jovu how to answer them
2. rephrase the questions to guide Jovu to the correct answer

for example,
for the first questions it talks about Service ID which is confusing.

```
Yes, Amplication automatically generates REST and GraphQL APIs for your entities. When you create an entity in an Amplication service, it not only creates the entity structure, but also generates the corresponding CRUD (Create, Read, Update, Delete) APIs for managing instances of that entity. These APIs are production-ready and come with standard features such as sorting, filtering, and pagination.

The generated APIs follow industry standards and best practices to ensure your backend services are reliable and scalable. Additionally, you have full ownership and control over the generated code, which means you can customize and extend these APIs as needed. Once you connect your project to a Git repository, you can continuously get more code changes and updates from Amplication to evolve your service while maintaining customizations you've added to the code.

If you have any specific entities or relationships you want to generate APIs for or any customization you'd like to implement, feel free to ask!
```

for the second questions it talks about custom code first, as it is not supported OOTB
```
Yes, you can integrate Kafka or other message brokers with your services in Amplication. While Amplication focuses on accelerating backend development by auto-generating REST and GraphQL APIs, managing database models, and simplifying service setup, integrating with external systems like Kafka often requires custom development.

Here's how you can approach adding Kafka to your services:

Custom Code: After generating your service with Amplication, you can customize the generated code to integrate Kafka clients or producers/consumers as needed. This involves writing custom service logic for event publishing and consumption, and configuring Kafka connection details.

Plugins: While Amplication provides a range of plugins to extend functionality, specifically for Kafka, you would typically handle the integration manually in the generated code. However, checking the available plugins or forthcoming features on the Amplication roadmap can be beneficial for future integrations.

Environment Configuration: Ensure your Amplication-generated service has the necessary environment configurations for connecting to your Kafka cluster. This includes Kafka brokers, security protocols, topic configurations, etc.

If you're interested in knowing more about the custom development process or how to efficiently integrate Kafka within the code generated by Amplication, please let me know! I can guide you on where to add custom code for Kafka or how to ensure your service is ready for such integrations.
```

**Comment by PazYanoverr** [comment]
@yuval-hazaz 
1. I agree the suggested questions were more about knowledge and less about "actions".
2.  Instead of the 2nd question- I would go with- "I want to add new services to my project. Can you help me?". This is more action-oriented and reveals better results IMO.
3. I agree the 3rd question is problematic, and it seems like we have an issue with the plugin and its list... Any idea how we can better fine-tune it? I wish we could ask here about Jovu's suggestions for plugins to install, but the results for such a question are bad.
4. Regarding the 4th question- When running "I want to create a new project with a couple of services. Can you help me?" Jovu creates a new empty project, and then ask to connect it to git etc. I think the UX is not so good. I think we should have the general question of "So, what are the benefits that Amplication can provide to my backend services?" which makes a good summary.

**Comment by PazYanoverr** [comment]
@yuval-hazaz - Updated the ticket's description based on our discussion.

**Comment by overbit** [comment]
@PazYanoverr  the 4th question doesn't match the requirements. 

> "So, what are the benefits that Amplication can provide to my backend services?"

vs

> "What are the benefits that Amplication can provide to my backend services?"

**Comment by PazYanoverr** [comment]
@overbit - My bad- Yuval and I discussed it, and decided to remove the "So,". I'll update the spec. Thanks for noting!

**Comment by overbit** [comment]
Test ✅ 

<img width="552" alt="image" src="https://github.com/amplication/amplication/assets/2861984/5aad4b56-ad92-4c46-a191-844f32f175f1">
