### ISSUE TITLE
Jovu: Add “teasers” in the “regular” UI to activate Jovu

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8308]
1. Every page in our app should have an "Ask Jovu" (+ an AI icon) button. Pressing the button will open Jovu screen. When Jovu is "active," the button should be disabled and re-enabled when the Jovu screen is closed.
2. The Project Overview screen should have a "Create API with Jovu" (+ an AI icon) button, with the same above functionality.
3. The Service Overview page should have a "Create Entity with Jovu" (+ an AI icon) button, with the same above functionality.
4. The "APIs" screen (Service) should have a "Create API with Jovu" (+ an AI icon) button, with the same above functionality.
5. The "Entities" screen (Service) should have a "Create Entity with Jovu" (+ an AI icon) button, with the same above functionality.
6. The "Plugins" screen (Service) should have a "Install Plugin with Jovu" (+ an AI icon) button, with the same above functionality.

When pressing the Jovu button in cases #2-#6 - the "general" request and the page context should be injected into Jovu, so it will ask right away the relevant next question in order to perform the request.

**Comment by yuval-hazaz** [comment]
I think "ask Jovu" is more catchy

**Comment by yuval-hazaz** [comment]
instead of  "Create Plugin with Jovu"  should it be "install a plugin" or " add a pluing" ?
also, what do you expect to happen here? how the process shoudl start?

**Comment by PazYanoverr** [comment]
Thanks @yuval-hazaz for your feedback!
Regarding the process- this is what I suggested- "When pressing the Jovu button in cases # 2 to # 6 - the "general" request and the page context should be injected into Jovu, so it will ask right away the relevant next question in order to perform the request.", e.g. Great! You want to install a new plugin. Please check the following plugin list, and let me know which plugins you want to have in your service.
WDYT?

**Comment by PazYanoverr** [comment]
@yuval-hazaz - Was it completed? Was the teaser added to add-entity, add-DTO, add-enum, and add-action?

**Comment by yuval-hazaz** [comment]
✅ - passed qa
