### ISSUE TITLE
Update first PR message

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8310]
The first PR message (in git & email) should be updated to [this message](https://www.notion.so/amplication/Git-Messages-b8c351b898cd4513976706711e03c663?pvs=4)  in order to better reflect Amplication benefits.

**Comment by morhag90** [comment]
Passed QA:

<img width="1018" alt="image" src="https://github.com/amplication/amplication/assets/97830649/2826949f-181b-4009-8458-ea80c189612e">
