### ISSUE TITLE
🐛 Bug Report: New Module editing name results in ApolloError

### ISSUE THREAD

**Issue by pmannion2** [amplication/amplication#8321]
### What happened?

Created new module in the API pane, tried to rename the module. 

### What you expected to happen

The name to update to the newly provided name. Ran into this: 
![image](https://github.com/amplication/amplication/assets/54895416/bf7be061-ea1b-4437-b0a8-4b438db19fd9)

### How to reproduce

Create new module, hit edit button, update name.

### Amplication version

v1.16.4

**Comment by PazYanoverr** [comment]
@mulygottlieb @morhag90 - FYI

**Comment by pmannion2** [comment]
Thanks team!
