### ISSUE TITLE
[Epic:`.NET`] Introduce new `File` (previously known as `Module`)  and `FileMap` ( previously known as `ModuleMap` )

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8353]
Extends the current code-gen-types with a new File and FileMap interfaces and classes to allow generic file content instead of string only

**Comment by morhag90** [comment]
Passed QA: code generated as expected: 

<img width="1546" alt="image" src="https://github.com/amplication/amplication/assets/97830649/2c95b2c0-2418-459f-8733-82a8724087fb">

Link to the PR:

https://github.com/morhag90/test/pull/1
