### ISSUE TITLE
design system: Icons are not displaying correctly

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#836]
**Describe the bug**
The icons in components from the "amplicaiton-design-system" package are not displaying correctly.

In the below screenshot, the icon on the top is not correct, and the list is missing the delete icon.

![image](https://user-images.githubusercontent.com/43705455/100123440-2e75d600-2e83-11eb-9fb5-a58437941365.png)

**Expected behavior**
Icons should use the "amplicationicons" font but instead, the material-icons are in use

**Additional context**
In the file "index.tsx" in "amplication-client" we use RMWCProvider to set the font to be used for icons.
This setting is missing in "amplication-design-system"

```HTML
<React.StrictMode>
    <ApolloProvider client={apolloClient}>
      <RMWCProvider
        // Globally disable ripples
        ripple={false}
        icon={{
          basename: "amp-icon",
        }}
      >
        <Router>
          <App />
        </Router>
      </RMWCProvider>
    </ApolloProvider>
  </React.StrictMode>,
```

**Comment by iddan** [comment]
Resolved by https://github.com/amplication/amplication/pull/838
