### ISSUE TITLE
[Epic:`.NET`] adding support for multi DSG images

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#8368]
![image](https://github.com/amplication/amplication/assets/39680385/b2138f39-a37a-4c53-a36d-edb7b333eee5)

**Comment by morhag90** [comment]
Passed QA: code generated as expected: 

<img width="1546" alt="image" src="https://github.com/amplication/amplication/assets/97830649/2c95b2c0-2418-459f-8733-82a8724087fb">

Link to the PR:

https://github.com/morhag90/test/pull/1
