### ISSUE TITLE
[Epic:`.NET`] Implement create-resource files (Dtos/controllers/services) / use FileMap / pluginWrapper.

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#8457]
* Implement create-resource files: 
- Controller / controllerBase (will complete in issue:https://github.com/amplication/amplication/issues/8446
- Service & serviceBase full (issue for full serviceBase: https://github.com/amplication/generator-dotnet-webapi/pull/29)

* Use the new FileMap class.
* adjust the plugin wrapper to DOTNet.

**Comment by mulygottlieb** [comment]
Passed QA ✅
Tested in: https://github.com/muly-demo-repos/dotnet-tests-1
