### ISSUE TITLE
🐛 Bug Report: Selecting specific generator version fails the build

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8484]
### What happened?

For any service, when a code generator version different from latest is selected, the build fails with no messages.

### What you expected to happen

Generator to complete as espected

### How to reproduce

Select a generator version different from latest

### Amplication version

v2.0.0

**Comment by mulygottlieb** [comment]
Passed QA


![Image](https://github.com/amplication/amplication/assets/1912933/51f36fd4-ad3e-46f9-a7c7-efd1e1a16a25)
