### ISSUE TITLE
🐛 Bug Report: DSG fails when using null or undefined as property type

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8495]
### What happened?

Null and undefined exist to support union types. 
as long as we do not support union types, we should remove the option to select null or undefined 

<img width="1179" alt="image" src="https://github.com/amplication/amplication/assets/43705455/6e3eb04e-d159-4103-b39f-7a4b9dd893c2">

### What you expected to happen

the user should not be able to select null or undefined as types

### How to reproduce

use null or undefined

**Comment by mulygottlieb** [comment]
Passed QA ✅
