### ISSUE TITLE
Generate code per service

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8500]
General: We would like to have the following build / code generation options:
1. Generate code for all services
2. Generate code for all services that have pending changes
3. Generate code for a specific service

Detailed request:
1. When pressing the "Generate the code" option- the code will be generated for all the services
2. The "Generate the code" will also have an "arrow" option that will open a menu with the following options:
    a. Generate the code for all services
    b. Generate the code for services with changes
    c. Generate the code for service [name]
    d. Generate the code for service [name]
3. In case the user chooses option c- and there are pending changes for other services, a message should appear saying-
"**Note:** There are pending changes for other services as well. 
Generating the code for service '[name]' will update all services with their changes, but only the code for the chosen service will be generated."
Buttons: Cancel, Generate
4. We need to modify the commit event to include the chosen type of commit out of the options above (add new metadata to the existing event) - preferably on the server side event

**Comment by abrl91** [comment]
@PazYanoverr 
what about having an icon to "generate code" on each service (like the delete button)
It can be disabled if there are no pending changes.

<img width="395" alt="image" src="https://github.com/amplication/amplication/assets/39680385/5de9468d-82ad-40aa-aceb-d41079231da3">

**Comment by PazYanoverr** [comment]
@abrl91 - It's a good idea! The only problem with it, is that when generating the code for service A, the pending changes and other changes (DSG-originated and such) will be applied for other services as well. I am afraid it's a little bit confusing, so I think we should try to avoid this path in a prominent location.  
WDYT?

**Comment by mulygottlieb** [comment]
Requires completing the client side

**Comment by mulygottlieb** [comment]
@PazYanoverr I am moving this back to "todo" for the client side (server is done)

**Comment by mulygottlieb** [comment]
Passed QA ✅

- Commit only pending changes (1 service out of two):
https://github.com/user-attachments/assets/b7e41086-10df-4e4f-9927-bcfff66836e9


- Commit all services by choosing all in the drop down + verify the "pending changes only" option does not appear when no changes:
https://github.com/user-attachments/assets/8f193b97-ef40-48b4-8f03-7129c703f19a


- Commit all services by just hitting the button itself (default behavior):
https://github.com/user-attachments/assets/b9a0f3ca-f6ae-4696-b6c8-93e0d161deb2


- Commit a single service:
https://github.com/user-attachments/assets/c0a697e2-4fa2-45e0-83fd-f8fa2fa27a78
