### ISSUE TITLE
[Epic:`.NET`] Add MSSQL Server support as a plugin

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8501]
Depends on #8528 since the docker-compose generation may vary in comparison with the nestjs generation

**Comment by overbit** [comment]
Currently blocked by https://github.com/amplication/amplication/issues/8509

**Comment by mulygottlieb** [comment]
Passed QA ✅
Tested in: https://github.com/muly-demo-repos/dotnet-tests-1
