### ISSUE TITLE
🐛 Bug Report: Jovu tries to create entities and fields with reserved names and fails

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8521]
### What happened?

Sometimes Jovu will try to create the entity or field with a reserved name and it will fail.

The response on failure sometimes is not expected from the user who may not asked to create it.

### What you expected to happen

Jovu should not use reserved names, but since sometimes it may do it unexpectedly, we should gracefully handle the issue and let the creation complete successfully. 

### How to reproduce

use this prompt
```
Create a new service for employee management, including working hours, locations, managers, employees, functions, and salary
```

**Comment by mulygottlieb** [comment]
Passed QA:
I used the prompt above to reproduce and got a successful generation by Jovu:


![Image](https://github.com/amplication/amplication/assets/1912933/20221544-aaba-418c-8eac-53ffd8ca3637)
