### ISSUE TITLE
Jovu: Improvements

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8523]
1. Make sure Jovu does not do anything which was not requested. Instead- Jovu should suggest and ask for the user's permission.
2. Make sure Jovu does not create many entities, services, and fields without stopping. Let's make sure he stops once in a while, and wait for the user's approval to continue.
3. Fix errors, mostly around (saved) names
5. Let's try to encourage Jovu to suggest APIs and plugins (as for now, he mostly suggests and creates entities)

**Comment by PazYanoverr** [comment]
@yuval-hazaz @mulygottlieb - Can we close this ticket as done?

**Comment by mulygottlieb** [comment]
Passed QA ✅
