### ISSUE TITLE
New onboarding (Jovu): Improve the "view code" experience

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8524]
1. "Go to view code" button - 
![Image](https://github.com/amplication/amplication/assets/149934977/f0d626fe-792c-46e3-9c74-1bab8dda0f87)
      a. In case git repo is connected to the project / service (demo or user's repo)- the git repo should be opened (via the git provider)
      b. In case no git repo is connected- the Project --> Code View tab should be opened.

---------> ---------> Below this line: items moved to #8743 ---------> ---------> ---------> 

2. The Project --> Code View tab -
      a. In case git repo is connected to the project (demo or user's repo)- link to the repo should be displayed at the top of the screen, with the text- "Browse the code on your Git provider". The message should be clear and dominant. 
     b. In case no git repo is connected - the following component should appear at the top of the page- 
![Image](https://github.com/amplication/amplication/assets/149934977/3197adb2-b80f-4ac7-ad32-bbab1a40ea5d)

3. Make sure we have an event for pressing the "Go to view code" button (- I didn't find such event)

**Comment by mulygottlieb** [comment]
Part (1) - Passed QA
Part (2) - Not implemented yet (move to a new ticket?)
Part (3) - same as (2)

@yuval-hazaz  @PazYanoverr

**Comment by mulygottlieb** [comment]
I opened #8743 for the remaining parts that were not fixed here. Therefore the parts that were fixed here passed QA ✅
