### ISSUE TITLE
[Epic:`.NET`] Seed script for DB (initial user, roles)

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8532]

**Comment by mulygottlieb** [comment]
This is already handled in https://github.com/amplication/amplication/issues/8533

**Comment by overbit** [comment]
## Test result
✅  https://github.com/amplication/dotnet-8-sample-generated/pull/4/files#diff-dcae18e9d13d140ab95f722d5bce28132b7a45b56b1faa9e6dcf3a03871fc36a
