### ISSUE TITLE
[Epic:`.NET`] Add auth logic as a plugin

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8533]
check https://github.com/overbit/dot-net8-api-sample/pull/2)

- [x] update controller methods to have the correct `[Authorize(Roles="xxx,yyy,zzz")]` attributes. => will implemented in auth-plugin 
- [x] add static file https://github.com/amplication/dotnet-8-api-sample/blob/main/src/Infrastructure/RolesManager.cs to generation => will implemented in auth-plugin

**Comment by overbit** [comment]
## Test result
✅  https://github.com/amplication/dotnet-8-sample-generated/pull/4/files#diff-dcae18e9d13d140ab95f722d5bce28132b7a45b56b1faa9e6dcf3a03871fc36a
