### ISSUE TITLE
[Epic:.NET] Add PostgreSQL support as a plugin

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8538]

**Comment by mulygottlieb** [comment]
Passed QA ✅

**Comment by morhag90** [comment]
Passed QA:

<img width="804" alt="image" src="https://github.com/amplication/amplication/assets/97830649/63791bc2-faa9-4625-a60e-b5eafd7fb211">

<img width="253" alt="image" src="https://github.com/amplication/amplication/assets/97830649/2939264b-f24d-4cbb-9886-ec8676d46c00">
