### ISSUE TITLE
BTM: Failed to get the AI suggestion

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8546]
Failed with error- "Uncaught TypeError: Cannot read properties of null (reading 'microservices')"

See the below recording-
https://github.com/amplication/amplication/assets/149934977/2245b81c-8c54-4713-aba4-07e9f390c9b3

**Comment by PazYanoverr** [comment]
QA:
Works as expected in Production env.
Fails in Sandbox. Probably the key should be updated in Sandbox as well

**Comment by mulygottlieb** [comment]
@PazYanoverr  I added a new key for Sandbox now, it should work now. Can you try again?

**Comment by mulygottlieb** [comment]
FWIW - I also updated Staging with a new key now and validated it works on staging as well
