### ISSUE TITLE
BTM- Update UI/UX

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8547]
After handling [https://github.com/amplication/amplication/issues/8546](url), we would like to update the BTM UI/UX to-
1. Remove the BTM button from the Project Overview screen
2. Remove the BTM button from the Service Overview & Service Entities screens
3. Leave only the "AI helper" button in the Project --> Architecture tab, and update its name to "Break the Monolith"

**Comment by PazYanoverr** [comment]
Failed on Sandbox-
#1 and #2 work as expected.
In #3- the name of the button was not updated to "Break the Monolith"
@overbit @mulygottlieb

**Comment by overbit** [comment]
Test result ✅
