### ISSUE TITLE
🐛 Bug Report: .NET Microsoft SQL Server plugin migration container fails to start

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8555]
### What happened?

<img width="1207" alt="image" src="https://github.com/amplication/amplication/assets/2861984/fa97b750-318a-483d-b031-fd3b216c2372">

### What you expected to happen

.

### How to reproduce

.

**Comment by mulygottlieb** [comment]
Passed QA ✅
Tested in: https://github.com/muly-demo-repos/dotnet-tests-1
