### ISSUE TITLE
🐛 Bug Report: Build errors are not obvious to find when using Jovu to commit changes

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8559]
### What happened?

when using Jovu to commit changes, the user is not taken to the build log and it is easy to miss build error message

### What you expected to happen

the user should be able to see build error message in visible location

### How to reproduce

create a service and install auth plugin and choose a dummy entity as the auth entity to trigger an error message 

### Amplication version

2.0.2

**Comment by mulygottlieb** [comment]
Passed QA


![Image](https://github.com/amplication/amplication/assets/1912933/8752d948-3e3c-4a1b-a4e4-2d8b08bee91c)
