### ISSUE TITLE
Workspace Overview- The project box is not clickable

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8565]
In the Workspace Overview --> List of projects - The box of each project is not clickable, but only the project name itself.
It's a "degradation", as it worked properly in previous versions. 

![Image](https://github.com/amplication/amplication/assets/149934977/9d3565d3-d5f1-4183-a590-4b590aa3a133)

**Comment by mulygottlieb** [comment]
Passed QA (on staging):
<img width="400" alt="image" src="https://github.com/amplication/amplication/assets/1912933/7fe40756-bca6-4bbd-94d3-8e7bf4bfae7d">
