### ISSUE TITLE
🐛 Bug Report: [ .NET ] `RangeAttribute` does not contain a constructor that takes 1 arguments error

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8579]
### What happened?

RangeAttribute' does not contain a constructor that takes 1 arguments
<img width="311" alt="image" src="https://github.com/amplication/amplication/assets/2861984/12fd85c5-9158-4979-9276-12aab9e0b573">

### What you expected to happen

.

### How to reproduce

.

**Comment by mulygottlieb** [comment]
Passed QA ✅
Tested in: https://github.com/muly-demo-repos/dotnet-tests-1
