### ISSUE TITLE
🐛 Bug Report: [ .NET ] Code generated with Many to many relationship is not buildable

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8580]
### What happened?

/workspace/amplication/generator-dotnet-webapi/.amplication/generate-local-code/generated/src/APIs/Order/OrdersExtensions.cs(19,29): error CS1061: 'Order' does not contain a definition for 'Products' and no accessible extension method 'Products' accepting a first argument of type 'Order' could be found (are you missing a using directive or an assembly reference?) [/workspace/amplication/generator-dotnet-webapi/.amplication/generate-local-code/generated/src/order-management.csproj]

/workspace/amplication/generator-dotnet-webapi/.amplication/generate-local-code/generated/src/APIs/Order/Base/OrdersControllerBase.cs(84,28): error CS1061: 'IOrdersService' does not contain a definition for 'ConnectProducts' and no accessible extension method 'ConnectProducts' accepting a first argument of type 'IOrdersService' could be found (are you missing a using directive or an assembly reference?) [/workspace/amplication/generator-dotnet-webapi/.amplication/generate-local-code/generated/src/order-management.csproj]

### What you expected to happen

.

### How to reproduce

.

**Comment by mulygottlieb** [comment]
Passed QA ✅
Tested in: https://github.com/muly-demo-repos/dotnet-tests-1
