### ISSUE TITLE
[Epic:`.NET`] Bug Report: wrong syntax for switch case

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#8601]
### What happened?

wrong syntax for switch case
`case caseOne || caseTwo:`
instead of: 
```
case caseOne:
case caseTwo:
```

### What you expected to happen

to have the correct syntax

### How to reproduce

---

**Comment by mulygottlieb** [comment]
Passed QA ✅
Tested in: https://github.com/muly-demo-repos/dotnet-tests-1
