### ISSUE TITLE
🐛 Bug Report: Service Creation fails on the DB step when selecting .NET

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8605]
### What happened?

when selecting .NET at the first step, the DB plugin list is empty and the wizard fails to complete 

### What you expected to happen

the user should see the .NET DB plugins

### How to reproduce

select .NET

**Comment by morhag90** [comment]
Passed QA:

<img width="1071" alt="image" src="https://github.com/amplication/amplication/assets/97830649/15a98e67-0ca4-4973-bd52-bbec53958646">
