### ISSUE TITLE
Jovu: Suggest plugins based on the service and its tech stack

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8610]
We want to update Jovu, so he can suggest, and install relevant plugins based on the specific service, and its tech stack.

**Comment by mulygottlieb** [comment]
Passed QA:

![Image](https://github.com/amplication/amplication/assets/1912933/b22e5050-6078-4bf0-8eed-97086cc6e536)

![Image](https://github.com/amplication/amplication/assets/1912933/2460aefd-f45f-4f6c-9756-939f34fa7b42)

![Image](https://github.com/amplication/amplication/assets/1912933/e78705fa-ab6b-4395-95d8-6bbc191a29d5)
