### ISSUE TITLE
Bug / Sync with Git: Misleading indications

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8612]
There is a bug in which sometimes a project is not connected to Git, but in the "Sync with Git" tab, it appears like the project is connected.
In this case, the "Connect to git" red icon appears at the bottom of the screen.

![Image](https://github.com/amplication/amplication/assets/149934977/8177ff31-5cf0-460c-bb5b-00e5882f1b6d)

![Image](https://github.com/amplication/amplication/assets/149934977/a32790a1-c572-473d-9e54-d98fd95de81d)

**Comment by overbit** [comment]
## Test result

✅ 
![Image](https://github.com/amplication/amplication/assets/2861984/f52eea13-f8d3-43df-a6df-7b4a5562d3c8)
