### ISSUE TITLE
[Epic:`.NET`] Using a DTO from module A as a property for a DTO in module B fails the code generation process

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8618]
![image](https://github.com/amplication/amplication/assets/1912933/62911004-e8c4-48fd-a630-f130de06ae41)

`{"buildId":"clx76jkrz000opjfnj2xn44gw-server","component":"generator-dotnet-webapi","errorMessage":"Cannot read properties of undefined (reading 'dtoType')","event":"CreateServer","level":"error","message":"Failed to execute plugin event CreateServer. Cannot read properties of undefined (reading 'dtoType')","resourceId":"clx1kl52500byvgimjyx9fzd0","stack":"TypeError: Failed to execute plugin event CreateServer. Cannot read properties of undefined (reading 'dtoType')\n    at getEnumDtoName (/workspace/packages/generator-dotnet-webapi/src/server/create-modules/common/get-enum-or-dto.js:16:76)\n    at getDtoFieldType (/workspace/packages/generator-dotnet-webapi/src/server/create-modules/create-module-dto.js:93:51)\n    at generateDtoFields (/workspace/packages/generator-dotnet-webapi/src/server/create-modules/create-module-dto.js:76:19)\n    at createDtoFile (/workspace/packages/generator-dotnet-webapi/src/server/create-modules/create-module-dto.js:36:23)\n    at createDtoFiles (/workspace/packages/generator-dotnet-webapi/src/server/create-modules/create-module-dto.js:24:36)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async createModulesFiles (/workspace/packages/generator-dotnet-webapi/src/server/create-modules/create-modules.js:19:13)\n    at async createServerInternal (/workspace/packages/generator-dotnet-webapi/src/server/create-server.js:41:32)\n    at async pluginWrapper (/workspace/packages/generator-dotnet-webapi/src/plugin-wrapper.js:22:20)\n    at async createDataService (/workspace/packages/generator-dotnet-webapi/src/create-data-service.js:36:31)","timestamp":"2024-06-09T06:45:23.961Z"}`

**Comment by morhag90** [comment]
Passed QA:

<img width="539" alt="image" src="https://github.com/amplication/amplication/assets/97830649/5bb01ba8-63a8-432d-968a-a0424ced8ea8">

<img width="1378" alt="image" src="https://github.com/amplication/amplication/assets/97830649/8f7fd0e1-0570-42c9-ae6f-6588a510a140">
