### ISSUE TITLE
[Epic:`.NET`] Disable the Admin-UI build when building .NET services (disable splitting and do not run the admin UI at all)

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8619]

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/57bd9cb9-9955-4a15-a676-c0def2a65f38)



![Image](https://github.com/amplication/amplication/assets/1912933/9ad4b0fa-bb75-4101-a413-df62159e36dd)



![Image](https://github.com/amplication/amplication/assets/1912933/211e744a-24b5-4c24-93da-60db7b5e0a7d)
