### ISSUE TITLE
[Epic:`.NET`] ID Field types handling - mostly around adding auto-increment in EF core

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8621]

**Comment by overbit** [comment]
@PazYanoverr  @mulygottlieb @yuval-hazaz  This is already implemented as EF core works out of convention

> By convention, non-composite primary keys of type short, int, long, or Guid are set up to have values generated for inserted entities if a value isn't provided by the application. Your database provider typically takes care of the necessary configuration; for example, a numeric primary key in SQL Server is automatically set up to be an IDENTITY column.

link: https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#primary-keys
