### ISSUE TITLE
[Epic:`.NET`]  Auth plugin issues

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#8626]
- Remove authEntity and use the IdentityUser.
- Add missing references 
- Fix missing placeholders

**Comment by overbit** [comment]
## Test result
✅  https://github.com/amplication/dotnet-8-sample-generated/pull/4/files#diff-dcae18e9d13d140ab95f722d5bce28132b7a45b56b1faa9e6dcf3a03871fc36a
