### ISSUE TITLE
🐛 Bug Report: Importing a DB model with no required fields (all fields except for the PK are optional) creates errors in the generated code

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8627]
The issue is with DB models that have no required fields i.e. that all the fields on the model are optional except for the PK field.
In this case, the way that Prisma creates the TS types is slightly different, and we need to adjust how we generate the code to work with that.
This does not usually happen since when creating entities from our UI you always get the "updatedAt" and "createdAt" fields as required fields, and ususally most DB tables have at least one required field (on top of the Primary Key that is) - so we didn't encounter this before.

Technical Details:
- We use the Prisma types directly in our service
- In the case mentioned above, Prisma creates the type for the model as `{field1: string | null, field2: string | null} | {}` and that addition of the `| {}` at the end of the type definition is causing a types mismatch in the generated service base in the implementation of the `create` function for the entity (e.g. `CustomerCreate`).

**Comment by morhag90** [comment]
Passed QA:

<img width="625" alt="image" src="https://github.com/amplication/amplication/assets/97830649/05d98c1b-cce4-44fa-8f82-c774ae581eb3">

<img width="1200" alt="image" src="https://github.com/amplication/amplication/assets/97830649/47a8e41c-8ffd-4a19-bbd4-4348dcf783da">
