### ISSUE TITLE
Add paid plan - Essential

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8631]
### Feature description

Add support for a new paid plan for small teams

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/03cb40c4-5392-4e92-90fd-3109d0ee4e26)


![Image](https://github.com/amplication/amplication/assets/1912933/d0a63b75-215c-433e-9891-e4bb9777eb10)


![Image](https://github.com/amplication/amplication/assets/1912933/33548816-8f0e-4ba1-8eeb-c0b0d4c13457)


![Image](https://github.com/amplication/amplication/assets/1912933/189ca57f-fca3-47e1-aece-1ed4c0db2066)
