### ISSUE TITLE
🐛 Bug Report: API for entity meta has the wrong path

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8636]
### What happened?

<img width="1044" alt="image" src="https://github.com/amplication/amplication/assets/2861984/e8e830e9-db53-4eb8-b203-219b217f8172">

The REST endpoints have not been generated yet. However, the GraphQL resolver currently returns only the count for multiple entities, not for individual entities 

### What you expected to happen

.

### How to reproduce

.

**Comment by overbit** [comment]
@mulygottlieb @PazYanoverr probably this needs a quick chat as we either use the wrong endpoint for `count` or this is a real issue

**Comment by PazYanoverr** [comment]
@overbit @mulygottlieb - NSIU the issue. Let's chat "offline"

**Comment by morhag90** [comment]
Passed QA:

<img width="1204" alt="image" src="https://github.com/amplication/amplication/assets/97830649/fd697b42-cd2d-4e99-89f8-1593aedb145a">
