### ISSUE TITLE
Add link to pricing page 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8645]
### Feature description

add a link to the pricing page from the header menu 

### Use case

add a link to the pricing page from the header menu

**Comment by morhag90** [comment]
@yuval-hazaz, the route does not work on the first try. See screen recording:

https://github.com/amplication/amplication/assets/97830649/3888ee66-d126-4eb1-99c7-b9d7b309a22c


https://github.com/amplication/amplication/assets/97830649/b3efa9f8-a076-44c1-a214-2687fffcf648

**Comment by mulygottlieb** [comment]
For me it sometimes doesn't work at all (even on the 5th click)

**Comment by morhag90** [comment]
@mulygottlieb  Same. It's in the second record I added.

**Comment by morhag90** [comment]
Passed QA:

https://github.com/amplication/amplication/assets/97830649/9ef961a5-5e00-4599-ac1a-47f9674bbcd2
