### ISSUE TITLE
Essential Trail on Node.js

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8646]
### Feature description

When a user is on trial, they should get access to Node.js

**Comment by morhag90** [comment]
Passed QA:

<img width="554" alt="image" src="https://github.com/amplication/amplication/assets/97830649/70373204-1e89-44b8-acd1-d91bef65777c">

<img width="267" alt="image" src="https://github.com/amplication/amplication/assets/97830649/9492a966-885a-47e7-b803-0ab7a2b3e125">

<img width="882" alt="image" src="https://github.com/amplication/amplication/assets/97830649/70a721fd-0e99-4f28-ae1e-dbfe57a3a46b">

<img width="518" alt="image" src="https://github.com/amplication/amplication/assets/97830649/89b1cad1-b73f-4e80-a627-00825a535c62">
