### ISSUE TITLE
🐛 Bug Report: Project description is not relevant 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8649]
### What happened?

all projects are created with the same description which is not relevant 

<img width="401" alt="image" src="https://github.com/amplication/amplication/assets/43705455/3b75d4b9-9e08-4fd1-b07d-11969965a2fd">

### What you expected to happen

create the project without a description 

### How to reproduce

create a project

**Comment by mulygottlieb** [comment]
Passed QA


![Image](https://github.com/amplication/amplication/assets/1912933/bb0e268c-378c-4c71-a7fc-5d84a74e8c05)
