### ISSUE TITLE
Jovu should be able to set the code generator of the service when creating a new service

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8650]
### Feature description

Allow jovu to set the code generator when creating a new service 

### Use case

Users with a license for both .NET and Node.js may want to select the code generator when creating a new service via Jovu.

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/fedc2243-132b-490d-9917-c3ceb6057374)

**Comment by mulygottlieb** [comment]
One potential bug: Jovu created the Dotnet service with the settings set to create GQL and Admin UI:


![Image](https://github.com/amplication/amplication/assets/1912933/af361b45-b3da-456b-bf57-2f8de4b2d50f)

**Comment by mulygottlieb** [comment]
Moving this to "Passed QA" - opened https://github.com/amplication/amplication/issues/8660 for the additional issue
