### ISSUE TITLE
LicenseIndicatorContainer has several unused properties and code paths

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8652]
### Feature description

LicenseIndicatorContainer has several unused properties and code paths

### Use case

refactor LicenseIndicatorContainer to remove the unused code and properties

**Comment by morhag90** [comment]
Passed QA:

<img width="964" alt="image" src="https://github.com/amplication/amplication/assets/97830649/12e6c596-7c19-45d1-8842-ef257369793a">
