### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8656]
### Feature description

https://www.notion.so/amplication/Updated-Q-A-New-Pricing-June-2024-4159568eeb824c89bd893fa733b5f795

**Comment by PazYanoverr** [comment]
Passed QA (Staging).
A few small comments (non-blocking)-
1. The first two questions in the product should contain links to "contact us"
2. The links in the product (see below example) should be colored purple-
![Image](https://github.com/amplication/amplication/assets/149934977/8da4c65a-04f6-43e8-a051-3af8143b6901)

3. In the question (product pricing)- "Can you assist with deploying to various cloud providers like AWS?" the "create a custom plugin" should be a link (see the "spec"- https://www.notion.so/amplication/Updated-Q-A-New-Pricing-June-2024-4159568eeb824c89bd893fa733b5f795?pvs=4)
4. In the question (product pricing) "Does Amplication support advanced security features like 2FA, audit logs, and SSO for organizational security concerns?" - the "Single Sign-On (SSO)" should be a link. See the "spec")
5. In the question (website) -"Does Amplication support advanced security features like 2FA, audit logs, and SSO for organizational security concerns?" the "Single Sign-On (SSO)" should be a link (- see spec)
