### ISSUE TITLE
Add link to upgrade when the user completes their Jovu requests

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8659]
Today, when Jovu's requests are completed, the following message appears-
![Image](https://github.com/amplication/amplication/assets/149934977/8273368c-14ca-4602-a62b-a34c574eece2)

Let's remove the "Talk with us" link and replace it with "Upgrade" - a link to the product's pricing page

**Comment by morhag90** [comment]
Passed QA:

<img width="352" alt="image" src="https://github.com/amplication/amplication/assets/97830649/e0f5d114-aa5e-4d98-acfd-d3445808e166">
