### ISSUE TITLE
Essential Plan: Update all the tooltips to point to the Pricing page

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8665]

**Comment by morhag90** [comment]
Passed QA:

<img width="641" alt="image" src="https://github.com/amplication/amplication/assets/97830649/7bfd00e8-d968-4238-983d-7547fa772fcd">

<img width="616" alt="image" src="https://github.com/amplication/amplication/assets/97830649/d1a65dc5-2527-400c-8675-0b777d540d72">

<img width="621" alt="image" src="https://github.com/amplication/amplication/assets/97830649/24321a72-1632-475d-86ac-6850f2ccc394">

<img width="631" alt="image" src="https://github.com/amplication/amplication/assets/97830649/94e6ff83-b459-48f5-b20c-75e1519cd31b">

<img width="1187" alt="image" src="https://github.com/amplication/amplication/assets/97830649/a2aa28bc-696b-4ef9-a488-ca0ff846232c">
