### ISSUE TITLE
Enforce services limitation for the Essential plan

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8669]
The Essential plan is limited to 5 services, but 6 services can be created.
Creation of the 7th service fails.

![Image](https://github.com/amplication/amplication/assets/149934977/595aa320-730c-47fe-9338-93759f3155d5)

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/6615aa4e-33ea-4d67-9365-517f6f415f6c)
