### ISSUE TITLE
🐛 Bug Report: Jovu- Failed sometimes to create one-many relation fields

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#8691]
### What happened?

Jovu sometimes failed to create one-many relation fields because he tried to create both sides. 

### What you expected to happen

The fields will be created successfully.

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/d718d2ad-8edf-4ff3-81b4-185c9b656843)



![Image](https://github.com/amplication/amplication/assets/1912933/6b3c03c9-b458-4aeb-8b56-acaff4ccd362)
