### ISSUE TITLE
Improve Jovu's experience and interaction with the platform

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8725]
Jovu should be improved to-
1. Redirect the user to the "Commits" screen with focus on the relevant commit, whenever Jovu is asked to generate the code by the user.
2. Redirect the user to the ERD screen once a session, and after a new entity is created by Jovu.

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/amplication/amplication/assets/1912933/e940dec1-f10a-4e0b-9fc2-5c2e33f5538c)



![Image](https://github.com/amplication/amplication/assets/1912933/9c013d5b-6d26-42cd-b175-e78f884ae6dd)
