### ISSUE TITLE
🐛 Bug Report: Jovu is not familiar with the built-in fields of the user entity

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8729]
### What happened?

When using jovu to create an entity for Users, the entity is created with the default User entity fields like username, password, etc
but, Jovu is no aware of the default fields and it tries to create them and get an error

https://insights.hotjar.com/r?site=2379803&recording=56062549576&startTime=215000

### What you expected to happen

Jovu should be aware of the new fields

### How to reproduce

create an entity called user and ask jovu to create fields on the entity

### Amplication version

3.1.2

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/user-attachments/assets/57d1b9ea-c9fb-4266-95f8-fad8400a8b58)
