### ISSUE TITLE
Pending changes list - collapse grops by default

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8745]
### Feature description

to allow the user better understands the pending changes and remove some of the cognitive overload for new users, the list of pending changes should be shown in the collapsed state by default 
<img width="330" alt="image" src="https://github.com/amplication/amplication/assets/43705455/030685e9-5acd-47fe-8746-0bf9ec71dbe2">

**Comment by morhag90** [comment]
Passed QA:

<img width="251" alt="image" src="https://github.com/amplication/amplication/assets/97830649/16e041e6-69d6-49c3-af78-55c7638987f5">

<img width="254" alt="image" src="https://github.com/amplication/amplication/assets/97830649/2e7238bf-80ea-4422-8890-cccd5ae6834c">
