### ISSUE TITLE
🐛 Bug Report: Code view screen align style

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8747]
### What happened?

1. collapse icons on left side which is not standard
2. items text wrap 
3. item text overflow + horizontal scroll
4. extra padding above the code panel
5. empty space when scrolling down on code panel

![image](https://github.com/amplication/amplication/assets/43705455/d6fb26f2-b680-482a-91aa-266bf063e4c9)
the 

### What you expected to happen

align style

### How to reproduce

see image

**Comment by JanviGupta12** [comment]
Hi, Can I pick this up?

**Comment by morhag90** [comment]
Passed QA:

<img width="291" alt="image" src="https://github.com/amplication/amplication/assets/97830649/dbe30835-5c4d-4f64-840a-e9ff722d4ac4">
