### ISSUE TITLE
Onboarding tools: Create new onboarding checklist and relevant onboarding product tours

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8755]
The following tasks (with this priority) should be handled-
1. ✅ The checklist should be displayed only after at least 1 service exists. This should be based on the following-
![image](https://github.com/amplication/amplication/assets/149934977/7d1e45f7-3f59-41ce-96b7-fc1956684ac4)

![image](https://github.com/amplication/amplication/assets/149934977/e553c1bb-64e9-4113-8550-6230b0503904)

![image](https://github.com/amplication/amplication/assets/149934977/9c696543-5eeb-4cbb-ad95-9102fc76ba9b)

https://help.productfruits.com/en/article/identifying-users?_ga=2.95263957.815182041.1720344766-1659879962.1720168420
 
2. ✅ Handle the "Item API ID" (checklist-generate-code) of the "view your code" step to generate the code (- **only in case** it was not generated before at all) and move to the commits screen.
3. ✅ Handle the "Item API ID" (checklist-open-jovu) of the "AI" step to open the Jovu conversation box.
4. ✅Handle the "completion" of the "APIs" step - DTOUpdated OR APIUpdated (i.e. at least one Action or DTO is created using the API management UI)
5. ✅Handle the "completion" of the "View your code" step - ViewPRClicked (i.e. the user pressed the "View code" new button at least once)
6. ✅Handle the "completion" of the "Plugins" step - PluginInstalled (i.e. at least one plugin is installed manually in the plugin screen)
7. ✅Handle the "completion" of the "Roles and permissions" step - RoleCreated (i.e. besides the “user” role, at least one role is added)
8. ✅Handle the "completion" of the "Event-driven architecture" step - MessageBrokerCreated (i.e. at least one message-broker is created)
9. ✅״Tackle Tech Debt & Keep Version Updates Easy״  click is not correctly opening the choose-dsg-versions tab

**Comment by morhag90** [comment]
Passed QA:



![Image](https://github.com/amplication/amplication/assets/97830649/95b266b0-ff39-4cc4-8f00-0ec9fb9f9106)
