### ISSUE TITLE
Client: Entity list display issue when pending changes bar is open

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#876]
**Describe the bug**
in the Entity page the line cuts before it ends

**Screenshots**
<img width="1280" alt="Screen Shot 2020-12-01 at 11 03 28" src="https://user-images.githubusercontent.com/8940907/100721900-9f0f7c00-33c8-11eb-95c9-dcda5fe2b8f3.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Google Chrome
 - Version 87.0.4280.67

**Comment by yuval-hazaz** [comment]
@Leeyaacov @MatanForU this issue was resolved in the last build but your approval is still required,
the current solution is based on a horizontal scroll on the bottom but you probably will want to resolve it in a nicer way
