### ISSUE TITLE
Update Jovu in case a request is partially succeeded

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8760]
Today when Jovu fails to create one field out of a few requested fields, he "thinks" that all the operation failed. 
As a result, Jovu tries to create all the fields again while fixing only the problematic field. The issue is that besides the problematic field, the other fields were created successfully, so the new request fails again on recreating existing these fields. This confuses Jovu unnecessarily.

![Image](https://github.com/amplication/amplication/assets/149934977/985e3d02-8ca4-47e1-8946-5a9add2e0be6)

**Comment by PazYanoverr** [comment]
@mulygottlieb @yuval-hazaz - FYI

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/user-attachments/assets/e85cda7b-2309-4214-a55e-8d2c0dd6259e)

![Image](https://github.com/user-attachments/assets/96158550-e49d-435b-902a-c16bebe5b9d5)

![Image](https://github.com/user-attachments/assets/db8cbbbf-4346-4aec-917f-a6c841f9d1d4)
