### ISSUE TITLE
Git sync as part of the Service creation wizard does not take place

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8769]
Step to reproduce:
1. Create a new project (and avoid connecting it to Git)
2. Create a service using the "manual" wizard
3. As part of the wizard- connect the new service to a GitHub repo.
4. Complete the wizard
Result: When checking the newly created service in the "Sync with Git" screen- it seems like the service is not connected to the chosen GitHub repo-

![Image](https://github.com/user-attachments/assets/88876de9-fcb2-421e-9a68-9a19505e06b0)

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/user-attachments/assets/b48dc4af-ce51-45b7-a157-828fffd06d1c)
