### ISSUE TITLE
Foreign Key is marked as required, although optional

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8773]
When choosing the Data Type of an entity's field to be "Relation to Entity", two fields are marked as required- "Related Entity" (correct), and "Foreign Key Field Name (Optional)" (incorrect).
The "Foreign Key Field Name (Optional)" field should not be required but optional.

![Image](https://github.com/user-attachments/assets/baa8ce96-9d30-4315-8457-9bd1feda8002)

**Comment by Amitrochates** [comment]
may i try this?

**Comment by mulygottlieb** [comment]
Let's go @Amitrochates :) Assigning it to you.

If you haven't done so before, please read or [contribution guide](https://github.com/amplication/amplication/blob/master/CONTRIBUTING.md)

**Comment by mulygottlieb** [comment]
Solved in #8892
