### ISSUE TITLE
Bug: Code Generation now changing prisma schema and dto properties from alphabetical sorting to UI order

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8789]
Apparently, a change caused the code generator to change all field orders in the generated Prisma file, all DTOs, all controller selects, and tests from alphabetically sorted fields to an order based on how the properties were added to the Amplication UI.

**Comment by morhag90** [comment]
Passed QA:

<img width="294" alt="image" src="https://github.com/user-attachments/assets/c9576d67-668c-4b29-bb34-e703e5ea2d57">


<img width="513" alt="image" src="https://github.com/user-attachments/assets/886282ca-3cd8-47b8-8e01-55ad21d056bb">

<img width="613" alt="image" src="https://github.com/user-attachments/assets/f4f21408-cd06-4fda-9a2c-a5fc4b04ee97">

<img width="520" alt="image" src="https://github.com/user-attachments/assets/d54d772a-8c50-4e32-8021-9b77b1c4ec16">
