### ISSUE TITLE
Bug (.NET): Disabled actions are still generated in the controller

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8803]
When you disable individual actions, they still get generated. Only if disabling the entire ModuleContainer (entire module) - the methods are no longer generated.

The expectation is that:
- In the controller, disabled methods will not appear at all
- In the service and service interface, generate all default methods and relation methods, but do not generate disabled *custom* actions

**Comment by yuval-hazaz** [comment]
✅ - passed
