### ISSUE TITLE
Update the tooltips of the Overview metrics to avoid talking about Node.js only

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8806]
The (i) /tooltip text of the (1) Time saved, (2) Cost saved, and (3) Code quality metrics in the Workspace Overview and Project Overview screens should be updated to avoid talking about Node.js only-

"Wondering about the time saved by Amplication generated code for your Node.js backend?
Based on our research and considering the efficiency of Node.js backend developers,...."

Should be updated to-
"Wondering about the time saved by Amplication generated code for your backend development?
Based on our research and considering the efficiency of backend developers,..."

I.e. "your Node.js backend" should be updated to "your backend development"
and "Node.js backend developers" should be updated to "backend developers"

Same should apply to the other two metric's text. 

![Image](https://github.com/user-attachments/assets/a36f1feb-9822-4ddd-bad4-e1b52f3d0457)

**Comment by morhag90** [comment]
Passed QA:

<img width="821" alt="image" src="https://github.com/user-attachments/assets/52839140-f315-4400-9fd6-9c9bbfb46a5e">
