### ISSUE TITLE
🐛 Bug Report: Error details when private plugin is not available are not clear

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8827]
### What happened?

When a private plugin is missing in the source repo, the error message is not clear enough

<img width="1164" alt="image" src="https://github.com/user-attachments/assets/fdc9f36f-e611-4685-a76f-10fd7c58d338">

### What you expected to happen

Show the user a message that will indicate that the plugin is missing 

### How to reproduce

try to download a plugin that does not exist in the repo

**Comment by mulygottlieb** [comment]
Passed QA:


![Image](https://github.com/user-attachments/assets/4920ad6e-aca7-436f-8983-aaebf0436880)
