### ISSUE TITLE
🐛 Bug Report: .NET DSG - Service.FIndOne - use method and types names from module actions and DTO

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8837]
### What happened?

.NET DSG - use method and types names from module actions and DTO

### What you expected to happen

.NET DSG - use method and types names from module actions and DTO

### How to reproduce

see the code

**Comment by morhag90** [comment]
Passed QA:

before:

<img width="660" alt="image" src="https://github.com/user-attachments/assets/74e769e5-6a62-406c-a1f4-960ee26f594c">

after:
<img width="686" alt="image" src="https://github.com/user-attachments/assets/70883413-f180-4c3f-8b09-286e0dccf28c">
