### ISSUE TITLE
NET DSG - Change all module action to PascalCase in PrepareContext

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8838]
### What happened?

The method names are changes from camelCase to PascalCase on each file separately. Instead use the prepare-cotext service to set the method naming standard 

### What you expected to happen

Change all module actions to PascalCase in PrepareContext

### How to reproduce

see code

**Comment by morhag90** [comment]
Passed QA:

<img width="678" alt="image" src="https://github.com/user-attachments/assets/d1298232-21f8-4450-93c8-5b29b043417e">
