### ISSUE TITLE
.NET: Improve program.cs events

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8840]
Customer request:
"The issue is that different services may have slightly different requirements, leading to variations in the "shape" of the Program.cs file.
Therefore, when making changes to the Program.cs template, I would prefer more flexibility in the CreateProgramFile event. For example, in addition to the builderServicesBlocks and appBlocks from CreateProgramFileParams, you could include options such as (if it's actually possible etc):
startFileBlocks and endFileBlocks
A useTryFinally flag along with catchBlocks and finallyBlocks"

**Comment by mulygottlieb** [comment]
@PazYanoverr - this can be a great task for @haimbell, with guidance from @morhag90

**Comment by mulygottlieb** [comment]
Implementation notes:
- Add new type of ASTNode for "PlainFile". This ASTNode will contain array(s) of CodeBlock which are the content of the file, as well as "try/catch/finally" enum (no try catch / try-catch / try-catch-finally), and "Try block" and "catch blocks".
- Replace the "Program.cs" event from arrays of code blocks to this new type
- Expose relevant parts in the plugin event

**Comment by mulygottlieb** [comment]
@haimbell / @morhag90, do we need another PR in code-gen-types to add the new event params for this event (using this new ASTNode type), or does this already exist?

**Comment by mulygottlieb** [comment]
Passed QA ✅
