### ISSUE TITLE
🐛 Bug Report: Commit list is missing a proper loading state after commit

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8864]
### What happened?

After the user clicks on generate the code and then moved to the commit list, a button for "generate the code" is shown while the commit list is loading 

<img width="1285" alt="image" src="https://github.com/user-attachments/assets/d6593427-fa03-44ba-a028-15311bcb765a">

### What you expected to happen

The button should not be shown and instead, the user should see a loading message

### How to reproduce

click on generate the code

**Comment by morhag90** [comment]
Passed QA:

<img width="846" alt="image" src="https://github.com/user-attachments/assets/fac1dfb8-6418-4794-92a3-ec398543b510">
