### ISSUE TITLE
Bug:  can not create custom module with the name auth when installing the auth-core plugin  

### ISSUE THREAD

**Issue by morhag90** [amplication/amplication#8873]
Cannot create a custom module with the name "auth" when installing the auth-core plugin, it causes to named collision
(in the folder name and module name)

**Comment by PazYanoverr** [comment]
@morhag90  @mulygottlieb - Is it just about disallowing the creation of a custom module called "auth"? or there is a better solution here?

**Comment by mulygottlieb** [comment]
@PazYanoverr - disallowing a custom module named Auth is the quickest solution. We can decide on better approaches. I think there are several possibilities, but IMO the best one is to allow plugin installations to make platform changes such as adding modules and actions, and then the auth plugin installation will represent the module it will create (Auth) in the module list, and if such a module already exists the installation can either fail or decide on a different name, etc (perhaps with plugin settings).

**Comment by mulygottlieb** [comment]
BTW @PazYanoverr, the approach I've mentioned is aligned with the customer's desire to add his own custom actions into the Auth module that was created by the plugin. But I can think of simpler solutions to achieve the same (e.g. "merge" the modules if they have the same name).

**Comment by PazYanoverr** [comment]
@mulygottlieb - Thanks! I think we should start with the quickest solution as the first step, and then consider improving it.

**Comment by PazYanoverr** [comment]
@mulygottlieb - Can you estimate the work required in order to disallow creating a custom module named Auth?
If it's very quick- let's prioritize this quick solution.

**Comment by mulygottlieb** [comment]
@PazYanoverr it's very quick. 1 hour seems reasonable to add a validation in the client and in the server. Perhaps 1 and a bit with full testing cycle.

**Comment by PazYanoverr** [comment]
@mulygottlieb - Thanks! Moving it to the Todo list

**Comment by mulygottlieb** [comment]
Passed QA ✅
![Image](https://github.com/user-attachments/assets/36479695-efea-41d2-8bcf-a54ae770772e)
