### ISSUE TITLE
Bug: "Foreign Key Field Name" option in the UI is confusing and is missing a validation

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8886]
![Image](https://github.com/user-attachments/assets/fc9962b9-6f3d-419b-b63b-086afb932260)

- [ ] #8892
- [ ] #8893

**Comment by PazYanoverr** [comment]
@mulygottlieb - Closing this ticket as it's handled in two separated tickets- #8893  and #8892
