### ISSUE TITLE
Upgrade the GQL react admin to latest RA (version 5) , including handling existing plugins for AdminUI (stale templates used in plugins, etc.)

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8891]
Resources:

https://github.com/amplication/ra-data-graphql-amplication/compare/main...feat/support-react-admin-5

https://amplic-my.sharepoint.com/:w:/r/personal/yuval_amplication_com/Documents/Microsoft%20Teams%20Chat%20Files/Admin-UI%20updates.docx?d=we25d86c341f245839f58f88b232bbc52&csf=1&web=1&e=uut51z

- [ ] Upgrade the ra-graphql-amplication 
- [ ] Updates in the Node DSG to the generated code
- [ ] Update all plugins that interact with the AdminUI events as needed

**Comment by mulygottlieb** [comment]
Moved this to next for re-evaluation later on. Feel free to backlog it if needed. @yuval-hazaz @PazYanoverr

**Comment by PazYanoverr** [comment]
Thanks @mulygottlieb.
@mulygottlieb @yuval-hazaz - Do we have an updated effort estimation? I.e. is it a matter of hours or days?

**Comment by mulygottlieb** [comment]
Passed QA
![Image](https://github.com/user-attachments/assets/7c3c8a0c-c53a-4aa6-8e4a-8d04059769ef)
![Image](https://github.com/user-attachments/assets/883d4486-7a29-4ef3-a8cb-40c4e0af2ff0)
![Image](https://github.com/user-attachments/assets/c8c4a14b-22de-4433-b719-92f3c743578f)
