### ISSUE TITLE
As a user I want Amplication to make relevant code changes in my generated customizable (non-base) files

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8895]
Currently, by design and as documented [here](https://docs.amplication.com/how-to/custom-code/), Amplication only generates the customizable (non-base) files for a generated module once and never overwrites them later on.
As a result, sometimes there could be build errors created in those non-base files - e.g. they contain imports to files already removed, or are calling the super() constructor with wrong parameters.

In order to reproduce this - create a Node.js service with default auth plugins (core+JWT), then build the code and merge, then remove all auth plugins are re-generate the code - the result will contain build errors.

Since the Smart Git Sync is working as expected to manage changes, we want to allow Amplication to update the non-base files as it updates the base files and other files.

**EDIT: QA INSTRUCTIONS:**
The original behavior that is documented in the ticket only happens when using a *polyrepo* pattern (when the source folders configuration is left empty). In the monorepo style, we *already* update the customizable files - which seems to be a bug, but a good one in our case since this is the behavior we wanted anyway. Potentially we do need to look into why on monorepo it didn't work as expected to begin with.
ANYWAY - to QA this you need an *existing* project that was created before this fix, and a new project that you've created after this fix. In the old project, create a new service with polyrepo and JWT auth, build the code and merge the PR, then remove both Auth plugins and rebuild the code - note that the `user.resolver.base.ts` is changing but the `user.resolver.ts` (non base) isn't changing, although it contains imports from Auth folders that no longer exist (this is the original bug).
Not repeat the exact same test on a newly created project (again a new service with polyrepo) - and observe that after removing the auth plugins, the `user.resolver.ts` file is also changing in the PR and not just the `user.resolver.base.ts`

**Comment by PazYanoverr** [comment]
Created https://github.com/amplication/docs/issues/518 to manage the documentation changes

**Comment by PazYanoverr** [comment]
@mulygottlieb - We need also to update the comment/s in the generated code (base files) regarding the non-base files that should not be overridden (by Amplication).

**Comment by mulygottlieb** [comment]
QA:
1. Create a service in an existing project, with polyrepo config, and verify the existing behavior persists (backward compatibility) ✅
![Image](https://github.com/user-attachments/assets/b60ef977-8c73-45ab-9aad-e2cf6a72f343)
As expected - the non-base files are not changed (current behavior kept on existing projects):
![Image](https://github.com/user-attachments/assets/26f00918-b302-47f2-a2b0-fda69022c0f7)
![Image](https://github.com/user-attachments/assets/48d13a88-1912-47b1-ab23-2056f3f8b883)


2. Create a service in a *new* project with polyrepo config, and verify that the new behavior is now happening and non-base files gets updated as well ✅
![Image](https://github.com/user-attachments/assets/5b51efb5-d907-4f74-a81c-693d986e1d52)
As expected - base and non-base files are updated in new projects:
![Image](https://github.com/user-attachments/assets/8210231c-1613-4916-9e88-3d09035dfd9d)
