### ISSUE TITLE
No hover ons

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#899]
**Describe the bug**
there are no hover on on any icon

**Desktop (please complete the following information):**
 - OS:  macOS Mojave 10.14.6[e.g. iOS]
 - Browser: Google Chrome [e.g. chrome, safari]
 - Version: Version 87.0.4280.67 (Official Build) (x86_64) [e.g. 22]

**Comment by yuval-hazaz** [comment]
@MatanForU can you please explain the issue?

**Comment by MatanForU** [comment]
when i hover on icon within the pending changes menu, it doesn't show me any hovers on any icon, which really confusing me as a new user that trying to do any project

**Comment by yuval-hazaz** [comment]
closed since it is not relevant anymore
