### ISSUE TITLE
🐛 Bug Report: Failed builds keep running infinitely 

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8999]
### What happened?

When the DSG is throwing an error, the error message is written to the build log, but the build step in the build log is not stopping 

<img width="1168" alt="image" src="https://github.com/user-attachments/assets/09615067-4d69-48ca-9616-fe1bbacfe04f">

### What you expected to happen

the build step in the log should stop with status "failed"

### How to reproduce

Create a service with MS SQL Server 
Create a custom API endpoint, with custom DTO with a property of type JSON
build the service
the DSG will throw an error that JSON is not supported, but the build step in the log will not stop

**Comment by mulygottlieb** [comment]
Deployed as HF to staging - QA needs to be done on staging
