### ISSUE TITLE
Website: show logged in user context

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#901]
**Describe the bug**
i can't log out or change any user

**Screenshots**
<img width="1249" alt="Screen Shot 2020-12-03 at 14 22 53" src="https://user-images.githubusercontent.com/8940907/101018256-e423e180-3573-11eb-8ffe-952d5d400855.png">

**Desktop (please complete the following information):**
 - OS:  macOS Mojave 10.14.6[e.g. iOS]
 - Browser: Google Chrome [e.g. chrome, safari]
 - Version: Version 87.0.4280.67 (Official Build) (x86_64) [e.g. 22]

**Comment by yenicelik** [comment]
should be addressed by the new admin-ui?

**Comment by yuval-hazaz** [comment]
The website (amplication.com) is not currently aware of anything about the user in app.amplication.com
