### ISSUE TITLE
Templates Overview: Display the installed plugins of each template

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9011]
Suggestion:
Display the installed plugins (number and/or [subset of the] icons for the Amplication plugins and number and/or [subset of the] icons for the private plugins

**Comment by morhag90** [comment]
Passed QA:

<img width="1421" alt="image" src="https://github.com/user-attachments/assets/d7964299-2e2f-4172-a0a5-9ac73290ceaf">
