### ISSUE TITLE
Unpublished template should NOT be available for new service

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9058]

**Comment by morhag90** [comment]
Passed QA:

before publish: 

<img width="1704" alt="image" src="https://github.com/user-attachments/assets/0c8404ec-8bfe-4c73-8de7-a0493977400d">

<img width="765" alt="image" src="https://github.com/user-attachments/assets/1c81b8eb-ec32-4d06-933d-e4e4f228156e">

after publish: 

<img width="1380" alt="image" src="https://github.com/user-attachments/assets/612db3aa-b2c3-4ddf-8119-e50b14df96fe">

<img width="580" alt="image" src="https://github.com/user-attachments/assets/685f6dd4-0c16-4696-ae4a-7b1b16aade7c">
