### ISSUE TITLE
Enhance Button Visibility for "Platform Console" and "Service Catalog" Across Screens

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9066]
Instead of having “View Templates” link in the Catalog screen (only), we should have a clear “Platform Console” button at the top of the page that will exist in all the Services-related screens. 
Same goes for “Service Catalog” (?) button on all the Platform screens.

**Comment by mulygottlieb** [comment]
Passed QA
![Image](https://github.com/user-attachments/assets/d21325ce-c101-4fdd-8e04-6a3edc7157d0)
![Image](https://github.com/user-attachments/assets/6d03be1d-0ac3-46c0-82d8-d05f76a6e0e1)
