### ISSUE TITLE
Update the "All set" message when creating a new template

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9072]
<img width="530" alt="image" src="https://github.com/user-attachments/assets/8b794614-dcd4-4ce5-8bf6-ded88cb2c63d">

The message at the end of a new template creation should be updated to-
"All set! We're currently generating your Template. It should only take a few seconds to finish. Don't go away!"

**Comment by mulygottlieb** [comment]
Passed QA:
![Image](https://github.com/user-attachments/assets/432ffe77-513e-4e1c-b151-6563ee51c024)
![Image](https://github.com/user-attachments/assets/f8e857c4-c3eb-47d1-bae7-b594226ddf64)
