### ISSUE TITLE
The message of a template's version is displayed as "commitMessage"

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9073]
In case no message was added when publishing a template's version, "commitMessage" is displayed as its message-

<img width="646" alt="image" src="https://github.com/user-attachments/assets/11b6c3ed-e1e2-46e2-9bf5-d9bcaa6974f5">

In case no message was added, an empty message should be displayed.

**Comment by mulygottlieb** [comment]
Passed QA
![Image](https://github.com/user-attachments/assets/8efc302f-cafa-4c35-825d-8f0d3e6b1b77)
