### ISSUE TITLE
Wrong behavior when updating the DSG version for a template

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9074]
When updating the DSG version for a template:
1. The 'Publish' option is not enabled for this template
2. Even after publishing the template with the updated DSG version, the "derived" services do not get this DSG version.

**Comment by mulygottlieb** [comment]
Item #1 - Passed QA:
![Image](https://github.com/user-attachments/assets/595e3dbf-d086-4099-8c93-5b520dd4e5a4)
![Image](https://github.com/user-attachments/assets/1977c6e4-dd47-4e87-9d2f-e75513c85921)

Item #2 - still not implemented. Moving to a new ticket. FYI @PazYanoverr

**Comment by mulygottlieb** [comment]
Opened #9144 to track item #2
