### ISSUE TITLE
The number indication in the Publish screen should count Resources and PPs and not blocks or changes

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9076]

**Comment by mulygottlieb** [comment]
Passed QA:
![Image](https://github.com/user-attachments/assets/e3bda274-acb2-4384-8e51-c453c5cf2338)


QA comment (@PazYanoverr ) - as can be seen in the screenshot above, all PPs are counted as one (the change is in a single resource - the Plugin Repo) - TBD if this requires an additional change (new ticket)

**Comment by PazYanoverr** [comment]
Opened https://github.com/amplication/amplication/issues/9143 to track it
