### ISSUE TITLE
Update the Private Plugins message in the Plugin screen (Free user)

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9083]
Update the Private Plugins message in the Plugin screen (Free user) from-
<img width="1220" alt="image" src="https://github.com/user-attachments/assets/4d94b37a-91c1-445e-b7ff-f2daf73d00a0">

to-
Unlock Private Plugins for Enhanced Control
Private plugins allow you to create and manage plugins to support your organization's unique tooling and tech. This allows you to define standards and tailor applications to fit your specific needs, ensuring consistency, flexibility, and control over your backend services

**Comment by YoosufAathil** [comment]
May I work on this ? 
Could you please assign me on this please ?

**Comment by PazYanoverr** [comment]
@YoosufAathil - Sure, good luck!
@mulygottlieb - FYI

**Comment by morhag90** [comment]
Passed QA:

![Image](https://github.com/user-attachments/assets/a10437ef-4f57-4f51-a99d-5483591cb57d)
