### ISSUE TITLE
🐛 Bug Report: tech debt list fails to load after a service is deleted

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#9088]
### What happened?

tech debt list fails to load after a service is deleted

### What you expected to happen

the list should load without alerts for deleted services

### How to reproduce

generate alert for a service, delete the service

**Comment by mulygottlieb** [comment]
Passed QA ✅

QA Comment (@PazYanoverr) - the Tech Debt list is not updating automatically when navigating back to it, and a full page refresh is required to get the new list. In my case after deleting the service and going back to the Tech Debt list, it still appeared there until I refreshed the page.

**Comment by PazYanoverr** [comment]
Created https://github.com/amplication/amplication/issues/9142 to track the issue @mulygottlieb  raised
