### ISSUE TITLE
Upadate the content in the plugin repo creation page

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#9090]
Title: 
Unlock the Power of Private Plugins

Text: 
Private plugins let you extend and customize your Amplication
services with unique functionality tailored to your
organization's standards and unique requirements. Get started by
managing your private plugins and enhancing your development
workflow.

Button:
Get Started with Private Plugins

**Comment by YoosufAathil** [comment]
Is the issue resolved ? @yuval-hazaz

**Comment by morhag90** [comment]
Passed QA:

![Image](https://github.com/user-attachments/assets/1d983ae7-904b-480e-b15a-71130e12f503)
