### ISSUE TITLE
Creating a new private plugin ends with Apollo Error (after refresh the plugin is actually created)

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#9094]
In the Private plugins screen, when creating a new plugin (by typing a plugin name and "enter"), the process ends with an Apollo error:
![image](https://github.com/user-attachments/assets/525be381-64b0-402a-9730-57b92498a02d)

After refresh you can see that the new plugin was actually created

**Comment by morhag90** [comment]
Passed QA:


https://github.com/user-attachments/assets/88a2cd21-8cd0-41a4-899a-99bae5ef1c97
