### ISSUE TITLE
The free-trial tooltips should talk about the updated trial period (14 days)

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9100]
After updating the free-trial period to 14 days, we need to update the hard-coded tooltips for the "premium" features to talk about 14 days rather than 7 days-

![Image](https://github.com/user-attachments/assets/9a180ec1-6636-425b-8153-e189e77db7b1)

**Comment by sumit851** [comment]
hey @PazYanoverr  i want to work on this issue plz assign to me - #9100

**Comment by PazYanoverr** [comment]
@sumit851 - Sure, assigning it to you.
@mulygottlieb - FYI

**Comment by sumit851** [comment]
hey @PazYanoverr  i am having issue in dev setup - package installing.

**Comment by PazYanoverr** [comment]
@sumit851 - Lat's take it in Discord (support channel).
CC: @mulygottlieb
