### ISSUE TITLE
🐛 Bug Report: render issues on tech-debt alert list

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#9126]
### What happened?

When changing filters or using the pagination on the tech-debt list, while the data is loading -the entire list is removed for a split second and then displayed again

### What you expected to happen

instead, the current data should be displayed while loading the data and only be replaced when the new data is available.

### How to reproduce

use pagination or sorting on the tech debt list

**Comment by mulygottlieb** [comment]
Passed QA ✅
