### ISSUE TITLE
The versions of a PP are sorted in the wrong way

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9136]
Unlike community plugins, which their versions (Settings screen) are sorted in a way that the later versions appear at the top-
<img width="325" alt="image" src="https://github.com/user-attachments/assets/f9afae1d-5c0c-42ca-9ceb-b293e6d7766b">

The PP's versions are sorted using the opposite way-
<img width="369" alt="image" src="https://github.com/user-attachments/assets/af95285d-9b25-4613-b385-30e91347ba38">

**Comment by morhag90** [comment]
<img width="553" alt="image" src="https://github.com/user-attachments/assets/f5f6ee7b-353f-4a67-919f-d465df457202">
