### ISSUE TITLE
The "View Templates" / "View Services" buttons should be omitted while emphasizing the "Service Catalog" and "Platform Console" buttons

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9137]
1. Since we added the "Service Catalog" and "Platform Console" buttons- we need to remove the redundant "View Templates" and "View Services" buttons-
![image](https://github.com/user-attachments/assets/133e8f33-852c-4bc7-af53-58febc9f989c)

2. However, as part of this change, we need to make the "Service Catalog" and "Platform Console" buttons more dominant

**Comment by yuval-hazaz** [comment]
closed, since we decided to leave the button is place, and move the console navigation button as in #9151
