### ISSUE TITLE
The Private Plugin link in the Platform Changes list leads to empty screen

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9141]
When pressing the Private Plugin (see below), an empty page is opened-

![image](https://github.com/user-attachments/assets/4a7fb850-658c-4e02-82c4-99ff704d06fe)

Expected result- 
The page of the Private Plugin should be opened-
![image](https://github.com/user-attachments/assets/44eaff1a-d345-462d-8879-bf850499b418)

**Comment by morhag90** [comment]
https://github.com/user-attachments/assets/f236f530-3a99-47f8-a12a-1721802807a2

**Comment by morhag90** [comment]
https://github.com/user-attachments/assets/9170f211-fe73-424f-b71a-17a0e958f52d
