### ISSUE TITLE
The number indication in the Publish screen should count Private Plugins

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9143]
The count should be 1 per changed PP, and not 1 per plugin repo.
See https://github.com/amplication/amplication/issues/9076#issuecomment-2428688597 for more info

**Comment by morhag90** [comment]
Passed QA:

![Image](https://github.com/user-attachments/assets/ed50fb47-3b88-4a88-a0d7-fddffd394f38)
