### ISSUE TITLE
update the style of new service from template modal

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#9173]
### Feature description

The instructions are incorrect, and the positioning of the elements needs tuning 

<img width="515" alt="image" src="https://github.com/user-attachments/assets/4abc6276-1786-4546-ac73-eeab117848ee">

**Comment by morhag90** [comment]
Passed QA:

<img width="629" alt="image" src="https://github.com/user-attachments/assets/5e64adb3-10e3-40c8-b418-40ec3b961f80">
