### ISSUE TITLE
Add a new generic ownership model to hold the ownership for any object in the system (currently only resources are supported)

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#9176]

**Comment by morhag90** [comment]
![Image](https://github.com/user-attachments/assets/6ca49e8b-0696-4f57-b2b5-e858750349b8)

**Comment by morhag90** [comment]
Passed QA:

![Image](https://github.com/user-attachments/assets/839ad8e9-2841-4054-b759-bf165c80038c)
