### ISSUE TITLE
Update text on login page

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#9195]
### Feature description

https://www.notion.so/amplication/Look-into-new-pricing-plans-new-customer-onboarding-journey-consider-next-required-steps-125eb180667180429408fa27ab586713?pvs=4#12ceb180667180b8a7fce2776a41aed5

**Comment by mulygottlieb** [comment]
Passed QA:
![Image](https://github.com/user-attachments/assets/a2bfaf2a-68ef-4d33-ad21-242cbcaaaf7f)
