### ISSUE TITLE
Handle alerts after publishing a new template version (including in-product notifications and emails)

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9229]

**Comment by mulygottlieb** [comment]
Passed QA:
Published a new version of a template (that already has a service created from it):
![Image](https://github.com/user-attachments/assets/2abd09c4-aa16-49dc-b309-52f1b5455d85)
Click on the alert takes you to the right place:
![Image](https://github.com/user-attachments/assets/e5e1720c-e75b-4a1e-be4c-66cd8c2e8af3)

I also got an email:
![Image](https://github.com/user-attachments/assets/2dfe7861-eca2-4dd9-b9b4-3c7d127953e6)
And the link from the email also takes you to the same right place ✅
