### ISSUE TITLE
Bug: Empty screen is displayed when entering a project's Catalog or Platform

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9288]
Happened to Derick in Sandbox and Production.
In Sandbox it happened right when entering the workspace Catalog, and in Production happened when entering any project's Catalog or Platform.
Seems like a key is missing in the local storage.

**Comment by mulygottlieb** [comment]
QA results on Staging (HF) - Delete the local storage for the grid columns and refresh:
Before -
![image](https://github.com/user-attachments/assets/0a9e13cf-93fa-4100-a96c-4e7876ec934f)

After Refresh -
![image](https://github.com/user-attachments/assets/e0207aee-39d0-42de-ad4b-e90575f09932)

Passed QA ✅
