### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by pwntester** [amplication/amplication#9332]
Hi,

I reported a critical security vulnerability on Oct 2nd through GitHub's Private Vulnerability Reporting (PVR) but got no answers yet. Can an admin please take a look at the report?

**Comment by yuval-hazaz** [comment]
@pwntester I didnt see the report. 
please send me the details directly if it is still relevant (the email is available on my profile)

**Comment by pwntester** [comment]
@kevinbackhouse @xcorail can you please send @yuval-hazaz the details? Thanks!
