### ISSUE TITLE
Client: Search bar position

### ISSUE THREAD

**Issue by Leeyaacov** [amplication/amplication#973]
**Describe the bug**
The search bar should be next to the page title and not aligned to the right.

**To Reproduce**
Please change the order of the HTML elements to:
![image](https://user-images.githubusercontent.com/65485193/101747291-4df03e00-3ad4-11eb-8372-173b8a6e1e12.png)

And delete the 'search-field' alignment left.

**Screenshots**
See below how it should be:
![image](https://user-images.githubusercontent.com/65485193/101742194-19c84d80-3ad3-11eb-912a-5c8ec1b76fcc.png)

**Comment by yuval-hazaz** [comment]
This cannot be done without further changes in the Entity Field list.\
There are some other changes previously suggested for the entity field list but they are a bit more complicated to implement and with lower priority.
@Leeyaacov, can you please add the details on the other changes so they will be available for future reference when someone starts working on this item?

**Comment by Leeyaacov** [comment]
![image](https://user-images.githubusercontent.com/65485193/102107340-5335eb80-3e3a-11eb-9617-d29f567cdeec.png)
