### ISSUE TITLE
Client: Hide Entity Version in Source Control Panel

### ISSUE THREAD

**Issue by iddan** [amplication/amplication#987]
<img width="1440" alt="Screen Shot 2020-12-13 at 17 32 25" src="https://user-images.githubusercontent.com/12671072/102016358-354c8600-3d69-11eb-8765-1f4e227fd1f0.png">

**Comment by yuval-hazaz** [comment]
@Leeyaacov what do you think?

**Comment by Leeyaacov** [comment]
Agree

**Comment by yuval-hazaz** [comment]
@iddan can this be closed?
